### ISSUE TITLE
Running the app in VSCode

### ISSUE THREAD

**Issue by kimfucious** [dotnet/AspNetCore.Docs#10398]
This article glosses over the setup of vscode to run a dotnet app.  It might help to add in a bit about the setup of a tasks.json and launch.json file.

This article is helpful:  https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md#once-for-each-project

@Rick-Anderson 	 edit: If this content is added, it should go in the /includes folder as this is no unique to WebAPI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by kimfucious** [comment]
I realize that "When a dialog box asks if you want to add required assets to the project, select Yes." will build these for you; however, my c# extension was messed up so I wasn't getting prompted.

**Comment by daveabrock** [comment]
@Rick-Anderson @scottaddie 	If you guys agree that the `tasks.json` and `launch.json` information should be documented, I could help you out since I've [written on the topic](https://daveabrock.com/2018/03/05/full-stack-development-in-vs-code-with-asp-net-core/).

**Comment by guardrex** [comment]
If this issue is worked, consider including a section on configuration of VSC to spawn IIS Express (*iisexpress.exe*) via task (if not too hacky; e.g., IIS Express sys tray might be the easiest path to kill the process/app). It would be useful in some scenarios when testing an app for IIS deployment (e.g., WinAuth). @DanJ210 might be looking into this. I can also help research and test options ... in a week perhaps ... I'm 🏃😅 right now. 

Cross-ref: https://github.com/aspnet/Docs/issues/9357#issuecomment-454415809

**Comment by Rick-Anderson** [comment]
> "When a dialog box asks if you want to add required assets to the project, select Yes."

That's all you need.

**Comment by DanJ210** [comment]
@Rick-Anderson Selecting "Yes" doesn't seem to create the needed assets (tasks) to run dotnet apps, not dotnet core. That's what @guardrex was referring to with what I was looking into. Running iisexpress like Visual Studio does so that I can use VS Code to build and debug dotnet apps.

@kimfucious mentioned dotnet, I don't see dotnet core, so I'm under the impression that he's referring to the same thing that I am. @daveabrock wrote a good piece on dotnet core but we are looking for running and building regular dotnet. There are some company apps that I can't switch over or make into new dotnet core apps. So being able to use the preferred VS Code editor would be great. How to setup those tasks in VS Code documentation would be ideal.

**Comment by Languafe** [comment]
For Visual Studio Code, suggest using dotnet watch run in (Integrated) terminal instead of ctrl+f5, which doesn't auto-recompile on changes. The tool is readily available now unlike before when it had to be installed.

**Comment by Rick-Anderson** [comment]
@daveabrock can you update that link?

> 

> @Rick-Anderson @scottaddie If you guys agree that the `tasks.json` and `launch.json` information should be documented, I could help you out since I've [written on the topic](https://daveabrock.com/2018/03/05/full-stack-development-in-vs-code-with-asp-net-core/).

**Comment by daveabrock** [comment]
> @daveabrock can you update that link?
> 
> > 
> 
> > @Rick-Anderson @scottaddie If you guys agree that the `tasks.json` and `launch.json` information should be documented, I could help you out since I've [written on the topic](https://daveabrock.com/2018/03/05/full-stack-development-in-vs-code-with-asp-net-core/).

This is fixed. It's a few years old, so let me if you come across anything that isn't correct.

**Comment by Rick-Anderson** [comment]
@daveabrock  https://daveabrock.com/2018/03/05/full-stack-development-in-vs-code-with-asp-net-core/ 404's on me

**Comment by daveabrock** [comment]
Take away the last backslash...
