### ISSUE TITLE
documentation/example for services.AddSingleton<IGroupManager, CustomGroupManager>() would be nice

### ISSUE THREAD

**Issue by MolallaComm** [dotnet/AspNetCore.Docs#10415]
Also, on the documentation for that interface, the cancellationToken=null stuff doesn't appear to work in 2.2  - you have to use cancellationToken = default(CancellationToken)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d77892-d376-2f23-2634-f5d34d962a1e
* Version Independent ID: 92ed6330-b49f-1620-6beb-8556a78ac7da
* Content: [Manage users and groups in SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/groups.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/groups.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
`cancellationToken=null` stuff doesn't appear to work in 2.2 - you have to use `cancellationToken = default(CancellationToken)`

@BrennanConroy please review.

**Comment by bradygaster** [comment]
Increasing priority as this looks like a lot of benefit for little work.

**Comment by bradygaster** [comment]
Feel this is good for closure due to age and inactivity. If this is still an issue in 3.1 or 6.0 (cc @BrennanConroy) can we get an issue in the product repo to track? If not, feel free to close. If there's a moniker specific to 2.2 in the doc that's broken, i'd argue for the removal of the 2.2-specific moniker. I'll be going through the MD files and looking for things like this over the next few days and will re-open this and resolve it if I come across this.
