### ISSUE TITLE
Add a doc on how to use services from DI when configuring options

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#10553]
The current [Options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options) topic is mostly of reference of everything you can do with options. We need a doc that is more task oriented that helps users figure out how to access DI services when configuring options for various components.

@Rick-Anderson  edit:
27 K PV, 50% CSAT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by rynowak** [comment]
This is already documented, but it's kinda hard to understand. I'm going to suggest some improvements.

**Comment by rynowak** [comment]
https://github.com/aspnet/Docs/pull/11128

**Comment by Rick-Anderson** [comment]
See also #15987

**Comment by guardrex** [comment]
I can probably work on this in January if there's interest. I was going to work over the topic on the other issue and even address some of the concerns forwarded on a similar issue from a different community member posted several months ago. We can discuss the *options* :smile: here and take it from there. Assign me if you want me to address it in January.

**Comment by Rick-Anderson** [comment]
Dan's right. Ryan's PR #11128 helps but is not enough. What it needs is right off the bat show how to access 
```
public class PositionOptions
{
    public string Title { get; set; }
    public string Name { get; set; }
}

// ...

public void ConfigureServices(IServiceCollection services)
{
    services.Configure<PositionOptions>(Configuration.GetSection("Position"));
    services.AddScoped<MyActionFilterAttribute>();

    services.AddControllersWithViews();
}

```

Then accessing it from a controler and filter like I do in https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/mvc/controllers/filters/3.1sample

**Comment by Rick-Anderson** [comment]
Problems with this doc:

* Too many comments in code, which are not translated.
* Snippets display too many samples at once.

**Comment by guardrex** [comment]
> Dan's right. What it needs is right off the bat show how to access

The sample link that you provided 404s, and I can't find a similar example to the general pattern in the [current filters sample](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/mvc/controllers/filters/sample/FiltersSample). What you're implying based on the code you show is already shown in ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#general-options-configuration

... which isn't what @danroth27 asked for AFAICT. His ask seems to already be addressed by the original coverage and Ryan's PR. **_However,_** I wonder about explaining how to achieve the following pattern that's often used by the framework ...

```csharp
services.AddMyService(options =>
{
    options.SomeOption = "some value";
}
```

... and that's one of the things that I wanted to consider along with taking a look at a few closed reader issues on this topic.

WRT "reference of everything you can do with options" **_isn't a complaint_** because this topic **_has to do that_** for Options. They have to be covered *somewhere* ... this is *IT*. :smile:

WRT code comments ...

> Too many comments in code, which are not translated.

Many are just to orient the reader to the examples across two files (*Startup.cs* and the Razor page that demos them). I don't think that numbered comments ("Example 1," "Example 2," etc.) are difficult to grok, but the word "Example" could be removed so that they're just numbered for easy reference across the two files. Many other comments contain a remark that's simultaneously called out in text. There are some that definitely need a touch of work, but I haven't seen a loc complaint since this topic was written.

> Snippets display too many samples at once

Each example only shows overlap for the ctor, and highlighting is used to call out the lines that pertain to each example. This could have been addressed by using different pages ... one page per example, but navigation then has to be rolled in and more files would end up in the sample ... little benefit for the cost 💸 imo. IIRC, readers aren't calling that out as a concern when they comment on this topic.

cc: @HaoK

**Comment by Rick-Anderson** [comment]
@guardrex 
> The sample link that you provided 404s, and I can't find a similar example to the general pattern in the

It's in PR  #16294 now.

> Many are just

I don't care about many - comments in code needs to be minimized

```
// Example #6: Named options (named_options_1)
// Register the ConfigurationBuilder instance which MyOptions binds against.
// Specify that the options loaded from configuration are named
// "named_options_1".
services.Configure<MyOptions>("named_options_1", Configuration);

// Example #6: Named options (named_options_2)
// Specify that the options loaded from the MyOptions class are named
// "named_options_2".
// Use a delegate to configure option values.
services.Configure<MyOptions>("named_options_2", myOptions =>
{
    myOptions.Option1 = "named_options_2_value1_from_action";
});
```

> Each example only shows overlap for the ctor, 

Creating a mess for everyone but the author.

I'll fix it.

**Comment by djeikyb** [comment]
I'm glad this is being worked on! Another task oriented example that would have saved me a good bit of time recently is configuring jwt bearer auth. When using:

    services.AddAuthentication().AddJwtBearer();

it's critical to implement `IConfigureNamedOptions<JwtBearerOptions>`. I had already successfully used the configure-options pattern with the IConfigureOptions interface to configure the AuthenticationOptions. I could step through with a debugger and see it work. I expected to use the same pattern with the same interface. Instead, I had to use the named version. I don't have a use case for multiple auth schemes, so I didn't even consider that there might be this additional complexity.

The larger task for me here is, I have a set of environment variables required at application startup. I want them strongly typed, validated, and injected as dependencies to things that configure services. Before we discovered asp core's configure-options pattern, we just hacked it in with globals and smattering of boilerplate.

**Comment by SaravananRIndia** [comment]
This article on Options Pattern has confused me instead of enlightening me on Options Pattern. This Article has forced me to look elsewhere for a better write up.

**Comment by Rick-Anderson** [comment]
@SaravananRIndia  I agree and I plan to totally rewrite it. Take a look at [Configuration ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1) which I just rewrote. It does a better job on the options pattern and might get you started.

**Comment by Rick-Anderson** [comment]
cleaned up and moved remainder to #18292
