### ISSUE TITLE
"Additionally, custom protocols can be created."

### ISSUE THREAD

**Issue by daltonks** [dotnet/AspNetCore.Docs#10861]
I cannot find documentation on how to do this, and have run into issues when I've tried to implement my own based on Protobuf.

Please refer to this issue for more information: https://github.com/Azure/azure-signalr/issues/379

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f4bdfd-dfac-d6ae-4bd9-57439d300a5d
* Version Independent ID: 1f37f1ba-3e43-e726-f231-52acc6d26516
* Content: [Differences between SignalR and ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/version-differences.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/version-differences.md)
* Product: **aspnet-core**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Notes:
* `TryParseMessage` should modify the `ReadOnlySequence<byte>` by slicing up to the amount consumed for the message parsed.
* `TryParseMessage` can give partial messages or more than 1 message at a time, so that needs to be handled
* The protocol should be stateless and threadsafe, multiple connections can be using the same class at the same time and they shouldn't be able to affect the parsing/writing of messages for the other connections

**Comment by daltonks** [comment]
Ah interesting. How should partial messages be handled if it should be stateless and threadsafe? I can't seem to find special handling for this in the JsonHubProtocol.

**Comment by BrennanConroy** [comment]
For partial messages the JsonHubProtocol has a message separator and checks if that exists. If it doesn't then it returns false with no message and will be called again when there are more bytes available. https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/common/Protocols.NewtonsoftJson/src/Protocol/NewtonsoftJsonHubProtocol.cs#L80

For returning multiple messages, you parse the first message, slice the input sequence and return true, then the method will be called again with the rest of the bytes

**Comment by daltonks** [comment]
Oh, makes sense! Thanks for the explanation.

**Comment by bradygaster** [comment]
Closing as it looks like the issue was covered.

**Comment by MagicAndre1981** [comment]
when can we expect a proper documentation about writing own protocols?

**Comment by BrennanConroy** [comment]
This isn't a very common scenario so it isn't a high priority doc for us to write.

The conversation above has some good information about how to write a custom protocol. You can also take a look at the current protocol implementations.
[Json](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/common/Protocols.NewtonsoftJson/src/Protocol/NewtonsoftJsonHubProtocol.cs) and [MessagePack](https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/common/Protocols.MessagePack/src/Protocol/MessagePackHubProtocol.cs).

**Comment by vcx** [comment]
+1 for docs, and I'm among those who will need to protobuf due to customer and regulatory requirements.

IMHO, it's a chicken-and-egg problem. Few people are asking because since there's nothing written about it, so people assume it doesn't support Protobuf. We should prioritize it, at least with small sample. It's a common pattern in MSDN docs... see Search, TPL Dataflow and others.

**Comment by bradygaster** [comment]
Closing as I concur with @BrennanConroy that this is outside the scope of the SignalR product discussion. Whilst I agree with @vcx and @MagicAndre1981 that docs on authoring custom protocols is valuable and valid, it is something that would be external to the SignalR product docs, or something that we'd author in the product docs repo alongside the protocol docs.
