### ISSUE TITLE
Update ANCM diagnostics doc for 3.0

### ISSUE THREAD

**Issue by shirhatti** [dotnet/AspNetCore.Docs#11149]
React to/Add entries for
- Changes in log strings https://github.com/aspnet/AspNetCore/pull/4515
- Bitness mismatch event 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2a7104-1d14-2e8a-0984-d92aa311c108
* Version Independent ID: 5e3c0546-c579-afb9-5289-b14532c127eb
* Content: [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-5.0)
* Content Source: [aspnetcore/test/troubleshoot-azure-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/troubleshoot-azure-iis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@tdykstra Same ?: Are they going to take this? I was about to get to this one, too.

**Comment by guardrex** [comment]
@shirhatti As we discussed earlier, I don't see how this topic can be maintained ... at least using the prior approach. It was created and maintained in a *simpler age* 👴 by reverse-engineering the error conditions to determine the error strings for a given condition.

The 2.2 updates that I made (https://github.com/aspnet/AspNetCore.Docs/pull/10319) don't match all of the original strings shown in diff on https://github.com/aspnet/AspNetCore/pull/4515, so it looks like there were intervening changes to the framework along the way. The history of ` src/Servers/IIS/AspNetCoreModuleV2/CommonLib/resources.h` doesn't indicate very many PRs, but the full history perhaps isn't shown (perhaps the repo moved?).

I wish all of these errors had been given stable framework error codes (looks like `HRESULT` is too general). That way, the strings could change and the topic wouldn't, and devs would just search the whole doc for a stable error code. I guess that there are other reasons why such a scheme wasn't instituted.

Anyway ... I'm not sure how to proceed here: There are too many error conditions and permutations of hosting to continue reverse engineering the outcomes. Since 2.2 strings in the doc don't match the diff, I'm scared to blindly find-'n-replace strings (by 'replace', I mean add 3.0 blocks or just update the 2.2 content).

**Comment by guardrex** [comment]
@shirhatti I'm looking at this now. Any i-dears on this one?

**Comment by shirhatti** [comment]
I definitely don't want you to reverse engineer the failure conditions. I'd started writing a document that describes all failure conditions at https://github.com/aspnet/specs/blob/master/notes/ancm/startuperrors.md

If my doc is missing any failure scenarios, @ me. I'm on the hook to address that.

For scenarios where we've updated the error messages for grammar/spelling, I believe the EventIDs are still the same. Just spitballing here, but if we include the EventID in this document, folks should still be able to search in this document. Thoughts?

**Comment by guardrex** [comment]
btw - ☝️ that link 404s (but I only have public access, so that's prob a private repo).

Yeah, if EventID comes out in one of the locations (browser response in Dev env, Application Event Log, ANCM stdout log, or ANCM debug log). My impression was that they **don't** show up (but I certainly may have forgotten what shows up given the time that's passed). Output often includes `HRESULT` codes, which aren't specific enough to be keys for error conditions. At least they weren't in the old days. 👴

Even if EventID is there and will work as keys for the guidance (i.e., those 'things to check' lists that I put in for each error), how do we align the EventIDs with the conditions that cause them any easier than reverse-engineering the errors? That was the only reliable way to produce and maintain this doc in the old days.

**Comment by guardrex** [comment]
@shirhatti Checking in on this one ... is the plan to take the new doc that you started writing and swap its text for most of the content in [Common errors reference for Azure App Service and IIS with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-iis-errors-reference?view=aspnetcore-3.0)?

If so, I guess we'll keep the introduction but swap out everything else starting with the first error condition.

If that's the plan, do you want to paste your topic text in here for me to work it into a PR, or do you want to send the PR (i.e., take over this issue)?

**Comment by guardrex** [comment]
Ping @shirhatti ... Checking in on this one ... should I leave it open. You were saying that you might have a total content replacement in the works. Is that right? The plan will be to keep the introduction here but swap everything else in the topic with your new bits. Is that correct? If so, should this remain on the November sprint, or should I move it back to December (or later)?

**Comment by guardrex** [comment]
@Rick-Anderson ... There's no action here AFAIK. Whatever way it goes, I'm not going to have the time to do anything significant with this, so I'm removing my assignment. I'll leave it to you to assign or close.

**Comment by Rick-Anderson** [comment]
@bradygaster  @shirhatti  if you can update https://github.com/aspnet/specs/blob/master/notes/ancm/startuperrors.md I'll get this documented.

**Comment by Rick-Anderson** [comment]
@jkotalik @shirhatti  is there anything in https://github.com/aspnet/specs/blob/master/notes/ancm/startuperrors.md that should be migrated to this doc? If so, please reopen.
