### ISSUE TITLE
Is this memory cache thread safe

### ISSUE THREAD

**Issue by xcaptain** [dotnet/AspNetCore.Docs#12512]
I want to use this memory cache to implement a lock to avoid http api replay, below is my demo code:

```csharp
string cacheKey = "some_cache_key";
if (_cache.TryGetValue(cacheKey, out string val))
{
    return BadRequest();
} else {
    _cache.Set(cacheKey, "locked", DateTime.Now.AddSeconds(10));
}
```
If `TryGetValue` is thread safe then only the first request can pass and other requests would fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.2)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Hello! Thanks for contacting us. This sounds like a general question about using ASP.NET Core. While we try to look at and respond to all issues, for questions like this we recommend posting to a community support group like [Stack Overflow](https://stackoverflow.com) with the `asp.net-core` tag.

**Comment by drdamour** [comment]
this article should discuss the thread safety of the in memory cache though

**Comment by tbebekis** [comment]
I was wondering the same thing. I checked the source code and I found that the MemoryCache class uses the ConcurrentDictionary class as the internal cache, which is a thread safe dictionary.

**Comment by erxdkh** [comment]
The dictionary is thread safe, but the value is not. What if you cache say "Doctor" object by some key, then get it from cache and try to mutate it (per business logic), - you are mutating a process global variable which leads to crash. And you may need to mutate it, say to do a what-if algorithm based on cached value with some changed fields. We store objects in byte[] with transparent serialization (using Azos Pile), that's why every Get from cache gives us a fresh unique instance, otherwise the semantic of process-global class is dangerous to say the least.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
