### ISSUE TITLE
An e.g of customizing the connection failure user message

### ISSUE THREAD

**Issue by sowsan** [dotnet/AspNetCore.Docs#12569]
It would great if we can have a detailed example/walkthrough on customizing the default signalR server connection failure message to the user. (ref:  Reconnection to the same server) . I'm looking for displaying some user-friendly message with a picture in the center of the page. https://material.io/design/communication/offline-states.html#principles

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#server-side)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The guidance from engineering thus far is to let the SignalR docs cover those aspects. In this case, it would be for https://docs.microsoft.com/aspnet/core/signalr/javascript-client to cover it.

I'll mark this for engineering to take a look and either confirm that or provide guidance for additional Blazor coverage.

**Comment by MisinformedDNA** [comment]
I use Blazor because I hate JS. Blazor is also wrapping SignalR calls, so the instructions are not necessarily the same.

#12572 mentioned the "Configure the SignalR client for Blazor Server apps" section but I don't see that anywhere. I think we need Blazor specific documentation, with links to the SignalR docs, where appropriate.

**Comment by guardrex** [comment]
We have coverage for this ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1#reflect-the-connection-state-in-the-ui

**_but_** ... there is an **important** implementation hole in the coverage because adding the `<div>` displays it on initial render. The classes are modified correctly by the framework thereafter. Therefore, the dev has to add the following to their stylesheet to make it work as expected ...

```css
#components-reconnect-modal {
    display: none;
}

#components-reconnect-modal.components-reconnect-show {
    display: block;
}
```

... per https://github.com/dotnet/aspnetcore/issues/16870#issuecomment-550345922.

I'll fix this now.
