### ISSUE TITLE
Add a note about how to make sure settings files are published

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#13147]
This note was in the Generic Host doc, but it fits better in this one:

To move settings files to the output directory for publishing, specify the settings files as [MSBuild project items](/visualstudio/msbuild/common-msbuild-project-items) in the project file. The sample app moves its JSON app settings files and *hostsettings.json* with the following `<Content>` item:

```xml
<ItemGroup>
  <Content Include="**\*.json" Exclude="bin\**\*;obj\**\*" 
    CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fb594f-04bf-c4d7-c94b-6cd6d8b12d75
* Version Independent ID: 64e973ac-838d-4459-06b0-4e943bff936e
* Content: [Host and deploy ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Unless the 🧀 is moving on SDK choice, not recommended since ...

* The `Microsoft.NET.Sdk.Web` SDK provides the targets to take care of it.
* The guidance always recommends use of that SDK for web apps of all types.

The reason that this is in the Generic Host topic is that the Generic Host <3.0 uses the `Microsoft.NET.Sdk`. Therefore, no targets are provided OOB to move the files. Since that's changing, the note can be dropped over there. Recommend closing here.

**_However..._** (there's always a "however" in the mix! :smile:) the general idea on how to move files that the SDK doesn't move ✨ *auto-magically* ✨ isn't currently covered in the *Hosting and deployment: Overview* topic).

The most coverage that we have on the SDK is in the *VS publish profiles* topic, and that's probably not where folks will look. This could go in the *Hosting and deployment: Overview* to surface it.

Might be a good idea to flesh out SDK coverage a bit there and at least list everything that the SDK does when publishing. That's where a dev might look first if they were trying to figure out how to manually get a file to publish or get additional info for SDK-based publishing actions. It could even go as far as to list out the dev-assignable properties that affect publishing.

**Comment by tdykstra** [comment]
@guardrex Per your suggestion, I moved this to the Deployment overview.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.

**Comment by Rick-Anderson** [comment]
`dotnet publish` moves all the `appsettings{Environment}.json` files to the publish directory.

**Comment by guardrex** [comment]
IIRC, wasn't this was about **_other_** settings files tho? ... ones that aren't moved ✨ *magically*.

**Comment by guardrex** [comment]
Maybe not ... my earlier remark seems to have been for like *preview* Generic Host or something. However, that might true tho ... other types of settings files wouldn't be moved (e.g., INI, XML).
