### ISSUE TITLE
The code in OnStopping() & OnStopped() cannot be executed in LifetimeEventsHostedService 

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#13446]
From @zhaobingwang ...

> in .NET Generic Host ,the code of class LifetimeEventsHostedService in OnStopping() & OnStopped() cannot be executed when i publish to docker run as an container,any idea?

> i debug the code OnStopping() & OnStopped() on windows, it's work fine(press ctrl+c finish the process and the code be excuted). but in docker,the code can't be excuted when i use the command docker stop container

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2#iapplicationlifetime-interface)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.

This issue will be locked after 30 more days of inactivity. If you still wish to discuss this subject after then, please create a new issue!
