### ISSUE TITLE
Unnecessary call to base.OnConnectedAsync and base.OnDisconnectedAsync

### ISSUE THREAD

**Issue by navidmatin** [dotnet/AspNetCore.Docs#13735]
In https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.2#handle-events-for-a-connection 
There is a call to `base.OnDisconnectedAsync(exception)` and one to `base.OnConnectedAsync()`. However when you go to those virtual methods they just return `Task.CompletedTask`. Is there something I am missing or the calls to the base Hub base methods are completely unnecessary in the overridden `OnDisconnectedAsync` and `OnConnectedAsync` methods? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by anurse** [comment]
I see this as one of those "the specification is rigid, the implementation is lenient" cases :). We generally want to remind and encourage authors of Hubs that you should call the base method (especially if you have your own derived Hub class). Thus the sample shows all examples doing this (the "specification" here, the doc, is strictly adhering to our guidance).

However, as you noted, our base implementation doesn't do anything, and we will likely never have it do anything because often users do fail to call the base methods (the "implementation" knows people may forget and thus we put any important logic _outside_ of this virtual method).

So yes, you are correct. Calling the base method doesn't do anything and could be omitted. Is there a specific concern you have about calling the base? (Observable performance impact, etc.)

**Comment by navidmatin** [comment]
Mainly that code example made me wondered if there is a plan for changing the implementation in the future to have logic in the base methods, which was what caused me to ask this question.

My other concern around unnecessary calls is the confusion that it can cause for the beginners and long term maintainers of the code.

**Comment by serpent5** [comment]
Closing based on the remarks made by Andrew Stanton-Nurse.
