### ISSUE TITLE
.NET 6 Update tutorial ASP.NET Core MVC with Entity Framework 

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#13920]
Review team note:  This will be updated directly to .NET 6, skipping 3.1, 5.0 for now.

From @donhuvy ...

&gt; Need update tutorial ASP.NET Core MVC with Entity Framework use Visual Studio 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.2#create-web-app)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Allann** [comment]
Any news on this?  The doc says to look at this issue for dates but nothing is mentioned 

> For information on when this might be updated, see this GitHub issue. https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/?view=aspnetcore-3.0

**Comment by Allann** [comment]
As an aside, the page mentions:
> For new development, we recommend Razor Pages over MVC with controllers and views

This goes against many demos from recent conferences, that mention "Razor Pages are great for demos but not large LOB sites".

Could you please clarify why razor pages are better?

**Comment by jbogard** [comment]
@Allann just as another data point, we use Razor pages on large LOB sites, so I don't know what that's coming from.

Controllers are merely a way to describe routes to methods, Razor Pages improves on this because in a typical controller, the actions don't have much to do with each other. The only case this isn't true is a GET/POST of a single URL, which Razor Pages encapsulate better because it's two methods on the same page.

A single class that holds methods for a number of separate, disparate requests doesn't make much sense from an object design perspective. It's really a legacy artifact from previous MVC frameworks (Rails, Monorail) and not really a true representation of the original MVC pattern.

**Comment by xyz0822** [comment]
I do think Razor Pages just for fresh newer developer  or many older develop that dont want mvc or just for little small sites. cause it likes webform and likes aspx that reduce the work for the older developer that dont want to change.like to learn mvc pattern. 
And another one point, to many people,the business rule,function,class,Di and many other front language may mixed in one class,witch will make the class become a big mud and all in a mess.
so there no better but for newer to learn or some small site quick code(also result in a mess)

**Comment by jbogard** [comment]
@xyz0822 That's no different than a controller action. It's now breaking a controller from multiple disparate actions into more tightly focused pages. But a page's class can still get big.

**Comment by LayersOfAbstraction** [comment]
Can we do this tutorial in Visual Studio Code as well, please?

**Comment by creativcode-ru** [comment]
Я сделал проект Contoso University MVC для EF Core 3.1 на основе EF для Razor Pages. Можете посмотреть здесь https://github.com/creativcode-ru/EF-Core/blob/master/README.md
---------
I made a Contoso University MVC project for EF Core 3.1 based on EF for Razor Pages. You can look here  https://github.com/creativcode-ru/EF-Core/blob/master/README.md

**Comment by creativcode-ru** [comment]
⚠ ВНИМАНИЕ! Опечатка в документации:
https://docs.microsoft.com/ru-ru/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-3.1#add-person-to-the-model

Из класса SchoolContext в методе OnModelCreating(ModelBuilder modelBuilder) закомментируйте 2 строки с классами Student и Instructor, надо оставить только одну таблицу Person вместо двух прежних. При миграции будет предупреждение о потере данных.

-------------------------------------------------
⚠ ATTENTION! Typo in the documentation:
from the SchoolContext class in the OnModelCreating method (ModelBuilder modelBuilder) comment out 2 rows with the Student and Instructor classes, you need to leave only one Person table instead of the two previous ones. During migration there will be a warning about data loss.

**Comment by robertwt7** [comment]
Any update on this guys? I just started migrating to .net core this week and can't seem to follow some of the outdated instructions..

**Comment by Rick-Anderson** [comment]
@wadepickett  after you get RP/EF and all the other tutorials updated, update this for 5.0, skip 3.1

**Comment by pschiager** [comment]
"For information on when this might be updated, see this GitHub issue." led me here, still confused as this left me with little clarity.

**Comment by wadepickett** [comment]
Related to #15620 which I had scheduled in for this month but it was moved yesterday.   I added to the list of work for this month's sprint instead.  Thanks.

**Comment by Rick-Anderson** [comment]
@wadepickett  you'll update this for 5, we're skipping 3.1 on this. You can do this after you update RP/EF to 5

**Comment by wadepickett** [comment]
@Rick-Anderson, we are on the same page.   That is why I gave a thumbs up the first time you mentioned it.  :)  Thanks for double checking though.

**Comment by wadepickett** [comment]
@Rick-Anderson, just realized why you mentioned it again.  Yes this would wait to go out with the final release, but I could at least start on it, then make any last minute changes based on a test with the final release bits when that happens.

**Comment by stephenhauck** [comment]
Anyone ?
My issue just got linked with this and it seems to have been left for dead ?
816 days this has been logged ... 

hey @coolcsh .. if you want it used you have to tell us how !

**Comment by costarec** [comment]
I teach a class that's focused on C#.NET and OO and I love using a bunch of different app types building up to using the Contoso MVC example. I would switch to the Razor pages tutorial, but there is no example of inheritance. Is an example of inheritance in the Razor pages tutorial anywhere on anyone's radar? And thanks for a great tutorial over the years.

**Comment by andrewericson23** [comment]
Why bother having this listed for 6.0 when it doesn't even work? I'm just trying to get this to work to learn how it works.  Thanks for wasting an hour of my life

**Comment by Rick-Anderson** [comment]
This is tracked in #26505
