### ISSUE TITLE
Describe relevance of returned Tasks from StartAsync and StopAsync

### ISSUE THREAD

**Issue by bernhof** [dotnet/AspNetCore.Docs#14156]
It's unclear whether StartAsync should return a Task that completes once a) startup is complete, or b) long-running operation performed by the IHostedService completes.

```
public async Task StartAsync(CancellationToken startupAborted)
{
    await DoLongRunningOperation(cancellationToken: startupAborted); // is this correct?
}
```

Likewise, with StopAsync, although the sentence "Any methods called in StopAsync should return promptly" seems to indicate that StopAsync Task should *not* wait for the long-running operation to actually finish.

```
public async Task StopAsync(CancellationToken nonGracefulShutdown)
{
    _cancellationTokenSource.Cancel(); // signal cancellation of background tasks
    await WaitForLongRunningOperationToFinish(cancellationToken: nonGracefulShutdown); // is this appropriate?
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
> It's unclear whether StartAsync should return a Task that completes once a) startup is complete, or b) long-running operation performed by the IHostedService completes.

It's **a**, once startup is complete. You can see this for yourself if you test it with something like the following:

```cs
public async Task StartAsync(CancellationToken cancellationToken)
{
    await Task.Delay(60000);
}
```

In this case, you'll see that 60 seconds passes before the "Application Started" log message is shown, which confirms that the host waits for your Task to complete before starting.

> Likewise, with StopAsync, although the sentence "Any methods called in StopAsync should return promptly" seems to indicate that StopAsync Task should _not_ wait for the long-running operation to actually finish.

`StopAsync` is called when the host itself is about to exit, allowing you to end any timers, long-running operations, etc, _gracefully_. In general, this should be handled quickly so that the host shutdown process isn't delayed longer than necessary.

If all you need is a long-running operation, have a look at `BackgroundTask`, which is mentioned later in the docs.

**Comment by bruno-brant** [comment]
This is an important issue - I have no idea what to return from those methods. My guess is that the runtime is awaiting on then so to enable asynchronous (and concurrent) startup, but I need to confirm this.

**Comment by guilhermeluizsp** [comment]
By default, when initializing, the web host uses the HostedServiceExecutor to start every IHostedService registered. It does that by calling StartAsync sequentially. If any IHostedService fails to start (i.e, if it throws an exception), the host won't be able to start (the exception will bubble up) and the remaining hosted services won't ever be called. **Consequentially, the longer the hosted service takes to start, the slower the host initialization will be**.

https://github.com/aspnet/AspNetCore/blob/f3f9a1cdbcd06b298035b523732b9f45b1408461/src/Hosting/Hosting/src/Internal/HostedServiceExecutor.cs

https://github.com/aspnet/AspNetCore/blob/d4a2fa1ceb3b9c10054da8a7c6a4bd61801aea18/src/Hosting/Hosting/src/Internal/WebHost.cs#L154

When shutting down (pressing Ctrl+C when running on console or stopping the website on IIS, for example), the host will stop every hosted service also by calling StopAsync sequentially, but this time, it will try to call StopAsync for every hosted service registered. Exceptions will be aggregated and re-thrown as an AggregateException later on. **This will impact the delay of the shutdown process** (as well as the initialization does). The cancellation token for this operation is set up to automatically cancel after 5 seconds, so you should consider this.

https://github.com/aspnet/AspNetCore/blob/d4a2fa1ceb3b9c10054da8a7c6a4bd61801aea18/src/Hosting/Hosting/src/WebHostExtensions.cs

https://github.com/aspnet/AspNetCore/blob/d4a2fa1ceb3b9c10054da8a7c6a4bd61801aea18/src/Hosting/Hosting/src/Internal/WebHost.cs#L348

It is important to mention that neither StartAsync or StopAsync are guaranteed to be executed. If the proccess is abruptly terminated, they may not run.

**Comment by zdenek-jelinek** [comment]
I would like to second this request, especially with focus on the StopAsync task.
If the understanding is that the returned Task represents the stopping operation, a successfully completed task should be returned when stopping is successful and canceled task should be returned if the stopping is canceled.
This behavior is not explicit in any of the samples and the source for BackgroundService uses CancellationTokenSource without ever considering the ExecuteAsync could throw OperationCanceled as a result of the cancelation. If we applied the above naïve logic to ExecuteAsync, e.g. returns a task that represents the execution, I think it would be valid for such task to become canceled if the token is triggered.

**Comment by MV10** [comment]
I agree the docs need clarification.

In my experience (starting and monitoring automated external processes, both scheduled and on-demand), the short version is that `StartAsync` and `StopAsync` should return as quickly as possible, and should arrange to execute the actual work in response to later notification that the application has successfully started (meaning all hosted services returned `Task.CompletedTask` from their `StartAsync` methods).

This seems to differ slightly from the way `BackgroundTask` wraps `IHostedService` since that actually begins execution in `StartAsync`. If you turn on detailed logging, this produces a somewhat confusing chain of events (your background work will start producing output before app startup has completed -- this seems very bad to me).

Because of this, I don't actually use `BackgroundTask`. Instead I inject `IHostApplicationLifetime` and use the `ApplicationStarted` token to register execution of my own `ExecuteAsync` work operation. So in a sense `StartAsync` is more like an initialization event. When my work requires close/dispose activity, I pass a token that is canceled by `StopAsync`, otherwise stop just returns `CompletedTask`. Finally, my work operation calls `IHostApplicationLifeTime.StopApplication` to shut everything down.

**Comment by yakovkiff** [comment]
Check out https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice , it explains IHostedService a lot better.

**Comment by Rick-Anderson** [comment]
Moved to Background tasks with hosted services: master issue #17605
