### ISSUE TITLE
Swagger?

### ISSUE THREAD

**Issue by khteh** [dotnet/AspNetCore.Docs#14791]
Does Swashbuckle work for .Net Core gRPC? This https://github.com/grpc-swagger/grpc-swagger seems to work for gRPC with Java..?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db2d29c-ebfd-9c79-4b08-61fc5192f3c3
* Version Independent ID: 048d1977-93aa-f28a-60ec-6806dec3f70a
* Content: [Introduction to gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/grpc/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by krishnasingh1818** [comment]
we also have add grpc to our .net core 3.1 apis and need swashbuckle to generate swagger.json so that we can publish same in azure api management ? any pointers to get this done using swagger and swashbuckle. or other option i was thinking is to modify our release to add one more steps to read grpc endpoints from some local grpc.json files and create new grpc endpoints in apim for that product. pls advise.

**Comment by JamesNK** [comment]
That package doesn't work but there is this option - https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi?view=aspnetcore-3.0#enable-swaggeropenapi-support
