### ISSUE TITLE
dotnet dev-certs https --trust requires install

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#14801]
Add `dotnet tool install --global dotnet-dev-certs` and `dotnet dev-certs https -c`

see https://github.com/aspnet/AspNetCore.Docs/issues/14776#issuecomment-537815699

The troubleshoot section only applies to Kestrel. For  VS/IIS Express, run the installer repair tool. See https://github.com/aspnet/AspNetCore/issues/16892#issuecomment-556080754

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#troubleshoot-certificate-problems)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Might be good to add when this issue is worked ...

The only thing we say about install is that the SDK install does it on first run. However, I had an expired cert and needed to put a new one in place (turns out that a new SDK install doesn't replace it automatically). The topic could call out that running `dotnet dev-certs https` will provide a new cert, then one trusts it, so the sequence should be clean-install-trust for this scenario.

**Comment by Rick-Anderson** [comment]
Moved to Enforce HTTPS Master issue #17356
