### ISSUE TITLE
How to scaffold authentication components to existing Blazor app

### ISSUE THREAD

**Issue by JeffreyMcJeffFace** [dotnet/AspNetCore.Docs#15396]
After using the Blazor getting started tutorials, I then expanded on them for my first Blazor app for an internal tool. Later I realized I would need authentication for my app. 

I searched for adding Authentication to existing Blazor app, but found little help. I've added Authentication to a .NET Core MVC app previously, so I was aware of the scaffolding of the authentication components. 

Attempting to scaffold the auth components caused several issues. I'm sure this is just a documentation issue as I ultimately was able to tweak things until it worked enough for our internal needs.

Issues Faced:
- Scaffolded components required a db context, and tool did not recognize my existing db context which required me to add a second db context. 
- Scaffolded  db context did not set up support for role-based authorization, which was confusing at first until I realized roles weren't being added to claims on login.
- After scaffold, the base layout was switched from MainLayout.razor (per tutorial) to using _Layout.cshtml. This resulted in a whole new nav bar on top of the app. It was unclear how to switch back to using MainLayout.razor after the scaffold of auth components. Ultimately deleting _Layout.cshtml and _ViewStart.cshtml caused app to revert to MainLayout.razor (I think).
-I scaffolded auth components twice so I could override the login page (which I neglected to select on the first scaffold). This resulted in confusion and undid the layout fixing I had done. Also, a second _Layout.cshtml was added to the Areas/Identity/Pages/Shared folder and the /Shared folder at some point. 

Document Needed: Add Authentication to Existing Blazor App

Abstract: This tutorial will show you how to scaffold authentication and authorization components and add them to an existing Blazor app. We will integrate the login functionality into the existing layout and add authorization to specific routes.

**Comment by guardrex** [comment]
Hello @zoenberger ... Because some aspects of authn/authz are still in design, such a topic isn't possible at this time. There's some discussion of showing workaround(s) now at ...

https://github.com/aspnet/AspNetCore.Docs/issues/15160

... and we'll keep a few authn/authz issues open (very similar to your ask), such as ...

https://github.com/aspnet/AspNetCore.Docs/issues/13022

... but this is basically a duplicate issue at this point for an in-design set of scenarios beyond what the topic currently shows. We'll need to wait on guidance from engineering before we can add/update any of the docs. Until then, keep an :ear: open on existing Blazor engineering repo and docs repo issues, consult with devs on support forums, such as Stack Overflow, and talk to devs on support chats, such as Slack and Gitter.
