### ISSUE TITLE
IWebHostEnvironment injected into the Startup ctor

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#15429]
When that's complete, add a link to doc at  #15410 and close that issue too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-3.0#the-startup-class)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Clarification: The topic already shows the injection with `IWebHostEnvironment`. At least, I propose to make a dedicated section out of the content to surface it better and make it easy to cross-link.

Ping @Tratcher for this bit ......

* Should the `Startup` ctor injection example continue to use `IWebHostEnvironment`, or should the example show `IHostEnvironment` instead? Should I attempt to indicate that both are permissible?
* If both are part of the coverage, what should be said about the difference?

  For this use case and if the following scenario is possible, what happens to host building if `DOTNET_ENVIRONMENT` is one environment and a different environment is indicated by the value  of `ASPNETCORE_ENVIRONMENT`?

**Comment by Tratcher** [comment]
IWebHostEnvironment derives from IHostEnvironment to add web specific items. Prefer IWebHostEnvironment in Startup examples. No need to cover both.

**Comment by Tratcher** [comment]
> * For this use case and if the following scenario is possible, what happens to host building if `DOTNET_ENVIRONMENT` is one environment and a different environment is indicated by the value  of `ASPNETCORE_ENVIRONMENT`?

ASPNETCORE_ENVIRONMENT probably wins as it would be applied later, but I haven't tried it.

**Comment by guardrex** [comment]
I'll research and rubber :duck: it a bit before working this.

Host coverage ... *ugh* ... 🚆💥 imo. At least please keep an :ear: open for internal feedback since about ~July 9, when the 3.0 host coverage was released.

**Comment by guardrex** [comment]
> be applied later

Yes, the behavior *everywhere* ... both host builders and regardless of source ... is last setting wins. I'll see how we explain it and try to improve the coverage if needed.

It's confusing to have *two* different "environment" config points (and env var sources) since they'll resolve to last set in the end either way. I guess this was done for backward compat, but it's sad to see backward compat ... once it goes there, one is doomed forever to keep it (probably).

![yoda](https://user-images.githubusercontent.com/1622880/66578590-00c7b380-eb41-11e9-82de-1d97f92e27fe.png)
### *If once you start down the dark path, forever will it dominate your destiny. Consume you, it will!*

\- Yoda ([Frank Oz](https://www.frankoz.com/)) [Star Wars: Episode V: The Empire Strikes Back](https://www.starwars.com/), &copy;1980 [Lucasfilm Ltd.](https://www.lucasfilm.com/)/[The Walt Disney Company](https://www.thewaltdisneycompany.com/)

**Comment by guardrex** [comment]
@Rick-Anderson IIRC, you're planning additional work on this one. I assigned it over. There's no new cross-linked PR yet, so I'll mark it back for triage in November (*guessing*).

**Comment by guardrex** [comment]
I'm going to move this to backlog just so that we can close this old milestone ... it keeps popping up on me and getting in the way when working with new issues. 🏃
