### ISSUE TITLE
Blazor State Mangement doesn't really have any details about long running processes.

### ISSUE THREAD

**Issue by BrainSlugs83** [dotnet/AspNetCore.Docs#15590]
[EDIT by guardrex to add the metadata]

**Help us make content visible**

- Tell us what search terms you used and how you searched docs.

`Blazor long running process`, `Blazor state` `blazor circuits`

- Tell us what docs you found that didn't address your concern.

The closest, and most common result is this page: https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management

I've also looked up and down the treeview on the left, and tried looking through the source on github (but honestly, I have no idea where to look.  I did stumble onto the `CircuitOptions` class which looks promising, but googling that also just lead me back full circle to that same page which has no information about configuring circuits or anything to do with the actual `Task`s that you kick off, or Life cycle management, it just has vague details that eventually the server will forget the state -- how long is eventually? -- And what does that entail?).

**Describe the new topic:**
I want to know: in server-side Blazor, if I kick off a long running async `Task` from the client, and they close the browser, how long will that thread continue to execute?

Will it be halted immediately? -- What if it's a forever process, how long will it live before the server decides to kill it? -- (I understand that it may not be predictable, and possibly subject to garbage collection-like rules, but what conditions effect these scenarios, and how can I configure them?)

And from the flip-side of the coin: what if I *want* the process to run until it finishes (i.e. not a forever process), even if the user disconnects? (e.g. the user kicks off a job that sends them an email when it's done.  Is that job guaranteed to continue running, or will the framework eventually stop it after a few minutes?)

**Explain why this topic is needed.**

Yes, I'm aware of web jobs/Azure functions, and I have a solution that does use those today -- but it's a LOT of extra baggage, and it's not easy to get real time feedback back to the client (we have a hacky solution now that I abhor).  I want to know more about how to manage Blazor circuits, and more about how to manage the life cycle of the long running tasks that I kick off.

**Suggest a location in the Table of Contents:**

Honestly, it seems like it should fit under state management, since the tasks a user kicks off is part of their state, right? -- Maybe I'm wrong and this belongs somewhere else... but, I don't know where that is...

**Write an abstract. In one *short* paragraph, describe what this topic will cover:**

When you kick off a `Task` in Blazor server, here's what happens.  Here's how it behaves if the client disconnects.  Here's what happens if the client reconnects.  Here's information about the life cycle of that code.  Here's what happens to the database call you were in the middle of making on that thread, etc., etc.

**Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic:**

 - Circuit Configuration
 - Long Running Process Lifecycle / Recycling? (Is that a thing? -- I honestly can't find a mention of the rules anywhere).
 - How to kill your long running task when the client disconnects.
 - How to keep your long running task running when the client disconnects.
 - How reconnects are handled.
 - Any other caveats gotchas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae14b3e3-3271-b919-9e0a-6f317a6b2d2d
* Version Independent ID: e5e1273b-195e-5da1-b4aa-66bbcff1425b
* Content: [ASP.NET Core Blazor state management](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/state-management.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/state-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello ... just fyi ... please use the **This Page** feedback button/form to open an issue. It pings the author and adds metadata. No worries tho ... I'll add it manually.

**Comment by BrainSlugs83** [comment]
@guardrex thanks! -- Apologies, I must have got here some other way.  Thanks for adding that.

**Comment by alex47** [comment]
Has there been any update regarding this since 2019?
I would really like to know what is the best practice for long running jobs that can run in the background after the user clicked a button and navigated away from the page.

**Comment by guardrex** [comment]
Not yet, @alex47. This hasn't been reached; but AFAIK, management still wants to consider more and specific coverage for background tasks and Blazor apps.

* One of the asks here is about circuit management. That's covered in a general way in the circuit handler options coverage for [`DisconnectedCircuitMaxRetained` and `DisconnectedCircuitRetentionPeriod`](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/signalr#circuit-handler-options-1).
* Since this ask deals with Blazor Server, we can also point to the current background tasks coverage in the main doc set ...
  * [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/aspnet/core/fundamentals/host/hosted-services)
  * [Host ASP.NET Core SignalR in background services](https://docs.microsoft.com/aspnet/core/signalr/background-services)
  * A bit of info about keeping the middleware pipeline running is in [WebSockets support in ASP.NET Core: Accept WebSocket requests](https://docs.microsoft.com/aspnet/core/fundamentals/websockets#accept-websocket-requests)
* We have relevant info on at least a subset of use cases in [ASP.NET Core Razor component lifecycle: Cancelable background work](https://docs.microsoft.com/aspnet/core/blazor/components/lifecycle#cancelable-background-work-1). How much of it covers the ask here depends on the goals and behaviors that one requires. This coverage could be moved into a new topic on the subject of background tasks with Blazor apps, if management decides to go that way.

In these cases where we don't have a lot of directly helpful coverage for complex scenarios, we recommend that devs speak with the community. We recommend the usual public support channels ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

One tends to run into devs who have faced things like this down, know about good blog posts out there, and who are able to provide tips and info on gotchas.

Speaking of blog posts, etc. ... one should search the Net. There are probably good posts out there. There might be some bits over at [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor) that apply.

This issue will receive more consideration *shortly-ish* ....... "-ish" because we're still working hard on 6.0 coverage for the November release. There will also be a significant amount of post 6.0 GA work from the end of November into mid-December. Then, the 🎁 *holidays* ⛄ hit (I'm hoping to take two weeks off myself 😩). I think management will address this issue further in early 2022 ... January probably. Note, however, that they might decide to close it as a `won't-fix` for docs as an advanced scenario that devs need to work out on their own beyond the docs already provided ... they might determine that there are just too many wide-ranging scenarios and use cases to cover and/or that we don't have the resources in light of other higher priority doc issues to address.

**Comment by Aeroverra** [comment]
After a recent review of my logs I had a task attached to a button running hours after a user exited a page. It was just a quickly thrown together single use page for researching so it wasn't using a great pattern but that seems like a recipe for disaster especially with new devs.

**Comment by guardrex** [comment]
I'm closing this because we already have coverage for it at ...

**Cancelable background work** in the *ASP.NET Core Razor component lifecycle* article
https://learn.microsoft.com/aspnet/core/blazor/components/lifecycle#cancelable-background-work

... which can be further extended by devs for other purposes (e.g., state management scenarios, dB processing, slow network processing, slow resource processing, etc.).

The section already cross-links the guidance on disposal that answers other questions in the OP at ...

https://learn.microsoft.com/aspnet/core/blazor/components/lifecycle#component-disposal-with-idisposable-and-iasyncdisposable

WRT ...

> And from the flip-side of the coin: what if I want the process to run until it finishes (i.e. not a forever process), even if the user disconnects? (e.g. the user kicks off a job that sends them an email when it's done. Is that job guaranteed to continue running, or will the framework eventually stop it after a few minutes?)

Use a singleton service and perform all of the background work from there. It doesn't matter what the user does after that kicks off, and the service can manage its own resources and take whatever followup actions it needs to take (e.g., email the user that their background job is finished).

Such jobs can also be run from entirely external services via web API, which is nice for when you want running services to even continue when the user-facing app is down (e.g., being updated or suffers a catastrophic failure 💥😨).

btw ... Azure Functions API used to have some kind of problem with Blazor. I don't know about that personally, but Jeff Fritz said in a podcast/video that he worked with it and didn't have luck early on. However, that was a *L...O...N...G time ago* ... in a galaxy far, far away 😄 ... wait ... what? ... did I just imply that Jeff is an 👽🤣??! I think by this point that Azure Functions probably do play nice with Blazor apps. If so, an option should be to trigger an Azure FN that runs in a fire-and-forget mode. Any of *several other third-party services* like Azure FNs could also work in this scenario.
