### ISSUE TITLE
Add two sections with details about scaffolding into server-side blazor apps

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#15651]
With auth.
Without auth.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Since I'm not currently aware of any difference for scaffolding into a Blazor Server app (configured for auth from the template or without) over a web app, I'll need more guidance to work this. Let's put it on the Blazor.Docs project for more info when this is triaged.

**Comment by Rick-Anderson** [comment]
Related: https://github.com/aspnet/AspNetCore/issues/16972

**Comment by guardrex** [comment]
... and cross-link from [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio).

**Comment by mkArtakMSFT** [comment]
@javiercn what details are you interested in here to be covered?

**Comment by Rick-Anderson** [comment]
@javiercn  @mkArtakMSFT  bot closing due to lack of information.

**Comment by VR-Architect** [comment]
Running the Identity scaffold on Blazor server Core 3.1 does not work.  I created a new Server app with local identity in my SQL database. The error is "Scheme already exists: Identity.Application".

We really need instructions for Blazor for 1) run the scaffolding, 2) create ApplicationUser custom class, and 3) change the UserId in database from nvarchar(450) to Guid. BTW, the use of nvarchar(450) prevents the ability to use compound primary keys.

**Comment by rogmauri** [comment]
Ainda não conseguimos utilizar 'Scaffold Identity' com Blazor, mesmo na versão .NET Core 3.1.
Alguma previsão?

**Comment by Rick-Anderson** [comment]
@VR-Architect 

>  The error is "Scheme already exists: Identity.Application".

That has nothing to do with Blazor. I've seen that error when you create a new web app with authorization, register a user, then scaffold.

Drop the DB, run update and try again. 
Verify that *\Areas\Identity\IdentityHostingStartup.cs* doesn't have a duplicate `AddDefaultIdentity` call.

>  change the UserId in database from nvarchar(450) to Guid. 

See [Identity model customization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1)

**Comment by win32nipuh** [comment]
Is it possible to add an example with some custom Identity provider implementation? 
For example this can be useful:
https://github.com/Robynhu/AspNetCore.Identity.PostgreSQL
It uses PostgreSQL as a user storage and does not use EF. No any Migrations etc, only creation db structure by script.

**Comment by guardrex** [comment]
@mkArtakMSFT I've researched this a bit more. The issue that I opened (and just closed) at #16944 is a dup of this issue, so I'm going to work the scenarios from here.

I took a look at the scaffolding topic at ...

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio

... and it's similar ... the steps are about the same, but that topic so RP/MVC-ish (code and markup examples), that I think we'd be better served by placing the Blazor scaffolding into Blazor's auth topic or creating a new topic for it in the Blazor TOC. Conversely, the current scaffolding topic would need work to make it more generic so that it would apply to all three scenarios (RP, MVC, and Blazor).

🤔 Your thoughts?

**Comment by Rick-Anderson** [comment]
> creating a new topic for it in the Blazor TOC (probably the better choice).

That gets my non-counting vote. I think that's better than adding Blazor to the existing doc.

**Comment by guardrex** [comment]
Yeah ... it's gonna be a fight to get it in there .... looks a bit *overhaul-ish* to make that work and avoid lots of duplication in that topic (i.e., if just sections are added). If we go with a little Blazor version of it over here, I can work it right after those high priority Blazor docs issues get worked, and those go forward right after the current crop of PRs merge.

**Comment by mkArtakMSFT** [comment]
@guardrex I think having a generic identity scaffolding topic is fine, and for the Blazor TOC, we can have a tiny writeup, where we can say something like "The auth for Blazor Server is exactly what it is for MVC and/or RP, so please look into there (link here) for how to scaffold identity).

**Comment by guardrex** [comment]
@Rick-Anderson *Scaffold Identity* is one of your 👶. Resolving this issue *might* require significant structural and content changes to the topic. I looked briefly, but that was my impression given the examples and markup shown. Do you want me to go ahead and stomp around in there 🐾, or would you prefer to work this one?

**Comment by Rick-Anderson** [comment]
@guardrex  can't you just add a Blazor section outlining what needs to be done? Do we need a complete walk through like I provided for MVC/RP?

**Comment by guardrex** [comment]
I can try. I have a feeling that there will be a lot of duplication with what you have there. The current guidance is about right for Blazor ... it's just that all of the examples/markup aren't the same.

Let's do that ... I'll try it with only sections and see how it composes. If it starts to go badly tho ... hitting problems ... I'll ping back here with it for further discussion.

**Comment by guardrex** [comment]
Note to self ... 

https://github.com/dotnet/aspnetcore/issues/19148#issuecomment-602022059

**Comment by guardrex** [comment]
@bdnts ... I've finally come to a day that I can dedicate to this one. Thanks for your notes over on https://github.com/dotnet/aspnetcore/issues/19148.

I think I see what I'd like to do on the PR with this to get the ball rolling with basic coverage that we can revise and extend thereafter. I'll ping you on the PR, which should land this evening.

You spoke about converting some number of page-based auth endpoints over to Razor components. Idk what the design will be later for that ... will they make a set of component-based auth endpoints for the OOB experience? I'll :pray: to the *server gods* for it! ... but I'd like to link a set of components from a Blazor node sample folder attached to the topic ... not show them ... just cross-link a set of them. Potentially, it could save a *massive* number of developer hours. If you have a set, would you be willing to provide them?

I understand from your notes that the Login page presents a major challenge, and I get that devs have been using an API-based approach for that. Those points are probably worth mentioning because devs are going to want to know what's possible *today*. Did you ultimately work out a SignalR approach? If not, which approach did you land on?
