### ISSUE TITLE
Visual Studio 2019 - Unable to add dependency

### ISSUE THREAD

**Issue by damien-alchemylabz** [dotnet/AspNetCore.Docs#15732]
When i follow point 4 : Select the Azure SignalR Service in the Dependencies &gt; Add drop-down list:
Following the on screen instructions pressing [next] does nothing 
Would you know why this could be the case ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b6b716-41ad-91d5-13a9-64f6c4a559c7
* Version Independent ID: 2fe5cca1-8690-0b91-3af6-5de9946c965d
* Content: [Publish an ASP.NET Core SignalR app to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/signalr/publish-to-azure-web-app?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/signalr/publish-to-azure-web-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/publish-to-azure-web-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by jpd21122012** [comment]
I have the same problem, I cannot add the Azure Signal Service on the dependencies.

Please some help

**Comment by ptrotter1** [comment]
I also have the same problem. The Next button does nothing.

**Comment by elmorych** [comment]
The same for me.

**Comment by bradygaster** [comment]
Adding @vijayrkn FYI from engineering side, also @spboyer on docs/e2e side. Folks - are you iterating on the doc mentioned and simply, the Next button does nothing? Is it enabled or is it disabled?

**Comment by vijayrkn** [comment]
Can you please confirm what VS version you are using?

**Comment by ptrotter1** [comment]
Microsoft Visual Studio Professional 2019
Version 16.5.4

Tried to upload a .gif here, but it would not work.

https://gifyu.com/image/l6yK

Nothing happens when we click the Next button. It does not appear to be disabled.

**Comment by benicillin** [comment]
same issue here. vs pro 2019 16.4.5

**Comment by flacidsnake** [comment]
Same problem described by @ptrotter1 
Visual Studio 2019 Pro 16.5.5

**Comment by vijayrkn** [comment]
@benicillin @flacidsnake can you please try the same scenario with the latest 16.6 preview? We have upgraded this experience to automatically detect missing components, add more types of dependencies etc. My guess is in the above case some of the Azure components are missing from the install. Can you check if the azure workload is checked in the vs installation?

**Comment by benicillin** [comment]
@vijayrkn i installed the preview build. the experience is indeed upgraded. i made sure to include the azure components in the install. i had to remove my existing publish profiles and create them again because there was an error but once i did that i was able to install the signalR dependency and configure it.

i suspect you are correct about the azure components being missing from the install. i checked my non preview vs 2019 install and the box was not checked for the components. i would recommend the others in this thread check this first and install the azure workload if its not installed and then try again. if that doesnt work, installing the vs preview version with the azure workload included will do the trick.
