### ISSUE TITLE
StateHasChanged Explained (vs base.InvokeAsync(StateHasChanged)

### ISSUE THREAD

**Issue by kevingates** [dotnet/AspNetCore.Docs#16119]
[EDIT by guardrex to add the metadata. We'll get an update from the product unit on this after 5.0 reaches GA. Everyone is 🏃😅 on 5.0 at the moment (9/24).] 

The differences between `StateHasChanged()` and `base.InvokeAsync(StateHasChanged);` is never clearly explained.

A topic on when a developer **should invoke** state has changed (via either method) as well has when is best to use each option would be helpful.

I understand that one handles things asynchronously, but are there times when it is better to have on method over the other? And what is being changed automatically vs us needing to call the method manually?

### Location:
Blazor --> Web Apps --> Components / State Management / "New Item"

### Abstract:
This topic will cover how State is managed in a Component, when it automatically updates, when a developer may want to manually update, and what options are available to the developer for updating the state.

### Potential Outline
1.0 - Definitions: Defining State in Blazor Components.
2.0 - How State is Updated
  2.1 - Automatic Updates
  2.2 - Manual Update
    2.2.1 - Example Scenarios when you will want to manually update.
3.0 - Manual Update Options
  3.1 - `StateHasUpdated();` Explained
    3.1.1 - Examples
  3.2 - `base.InvokeAsync(StateHasChanged);` Explained
    3.2.1 - Examples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Blazor lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1#state-changes)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @kevingates ...

It's covered *lightly* in a spots where it's relevant to make the call, typically for a render when Blazor isn't aware that it should update the UI. For example:

* [Invoke component methods externally to update state](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#invoke-component-methods-externally-to-update-state)
* [TabSet example (cascading parameters)](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#tabset-example)
* [Invoke JavaScript functions from .NET methods](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1#invoke-javascript-functions-from-net-methods)

... but *yes* to possibly covering it further. The *good spots* for more coverage are probably either or both of:

* *Lifecycle* topic at [State changes](https://docs.microsoft.com/en-us/aspnet/core/blazor).
* *State Management* as you suggested. I think 🤔 ... hope :pray: ... that we can place coverage in the existing topic as opposed to creating a new topic. I don't think very extensive coverage is required .. *maybe*. :smile:

I'll mark this for triage on the Blazor topic for engineering to review. Stand-by tho if it takes a while to get an answer ... we're **_very close_** to the holidays 🎁⛄️, so I think it's likely that they won't remark on this until we get into 2020.

**Comment by mkArtakMSFT** [comment]
Let's add more information about the `StateHasChanged` in the Lifecycle page: https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1#state-changes

**Comment by SteveSandersonMS** [comment]
@guardrex I've written the following suggested documentation to cover this topic. Do you think this is suitable, and where do you think it should be added? I would suggest adding it as a new page called "Rendering" within Blazor's "Fundamendals" category.

If you want I can convert this into an actual PR for this, but if that's the sort of thing you can do in minutes yourself (having decided really where it should go) then that sounds good to me.

---

## When components render

All components *must* render when they are first added to the component hierarchy by their parent component. This is the only time that a component strictly must render.

A component *may* choose to render at any other time according to its own logic and conventions.

## Conventions for ComponentBase

By default, `.razor` components inherit from `ComponentBase`. This base class contains logic to trigger re-rendering at the following times:

 * After applying an updated set of parameters from the parent component
 * After applying an updated value for a cascading parameter
 * After being notified of an event and invoking one of its own event handlers
 * After a call to its own `StateHasChanged()` method

Components inherited from `ComponentBase` will skip the re-render (but not the initial render) if any of the following are true:

   * All of the parameter values are of known immutable primitive types (`int`, `string`, `DateTime`, etc.) and have not changed since the previous set of parameters
   * The component's own `ShouldRender()` method returns `false`

## Controlling the rendering flow

In most cases, the `ComponentBase` conventions mean that the correct subset of components will re-render after an event, without developers needing to write any manual logic to tell the framework which components to re-render. The overall effect of the conventions is that the component receiving an event will itself re-render, which recursively triggers re-rendering of descendant components whose parameter values may have changed.

## When to call StateHasChanged()

The `StateHasChanged()` method on `ComponentBase` lets you trigger a render at any time. However you should be careful not to call this unnecessarily (which is a common mistake) because that would impose unnecessary extra rendering costs.

You should *not* need to call `StateHasChanged` when:

 * Routinely handling events, whether synchonrously or asynchronously, since `ComponentBase` triggers a render in those cases anyway
 * Implementing typical lifecycle logic, such as `OnInitialized` or `OnParametersSetAsync`, whether synchonrously or asynchronously, since `ComponentBase` triggers a render in those cases anyway

However, it can make sense to call `StateHasChanged()` in the following cases.

### When an asynchronous handler involves multiple asynchronous phases

Consider the following "counter" component, which updates the count four times on each click:

```razor
@page "/counter"

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private async Task IncrementCount()
    {
        currentCount++;
        // Renders here automatically

        await Task.Delay(1000);
        currentCount++;
        StateHasChanged();

        await Task.Delay(1000);
        currentCount++;
        StateHasChanged();

        await Task.Delay(1000);
        currentCount++;
        // Renders here automatically
    }
}
```

The way that tasks are defined in .NET means that a receiver of the `Task` can only observe its final completion, not any intermediate asynchronous states. So, `ComponentBase` can only know about triggering re-rendering when you first return the `Task` and when that `Task` finally completes. It cannot know to re-render at other intermediate points. So if you do want to re-render at intermediate points, use `StateHasChanged()`.

### When receiving a call from something external to the Blazor rendering and event handling system

`ComponentBase` only knows about its own lifecycle methods and Blazor-triggered events. It doesn't know about anything else that can trigger your code.

For example, if you have a custom data store that raises C# events, then those C# events are unknown to Blazor. As another example, consider the following "counter" component that uses `System.Timers.Timer` to update the count at a regular interval:

```razor
@page "/counter"
@using System.Timers
@implements IDisposable

<p>Current count: @currentCount</p>

@code {
    private int currentCount = 0;
    private Timer timer = new Timer(1000);

    protected override void OnInitialized()
    {
        timer.Elapsed += (sender, eventArgs) => OnTimerCallback();
        timer.Start();
    }

    void OnTimerCallback()
    {
        _ = InvokeAsync(() =>
        {
            currentCount++;
            StateHasChanged();
        });
    }

    void IDisposable.Dispose() => timer.Dispose();
}
```

In this example, `OnTimerCallback` has to call `StateHasChanged()` for the UI to be updated, because otherwise Blazor doesn't know anything is happening. `OnTimerCallback` runs outside of any Blazor-managed rendering flow or event notificaiton.

Similarly, because this callback is invoked outside Blazor's synchronization context, it's necessary to wrap the logic in `InvokeAsync` to move it onto the renderer's synchronization context. `StateHasChanged()` can only be called from the renderer's synchronization context and will throw an exception otherwise. This is equivalent to marshalling to the UI thread in other UI frameworks.

### To render component outside the subtree that is re-rendered by a particular event

Your UI might involve dispatching an event to one component, changing some state, and needing to re-render a completely different component that is not a descendant of the one receiving the event.

One way of doing this is to have some "state management" class, perhaps as a DI service, injected into multiple components. When one component calls a method on the state manager, the state manager may raise a C# event that is then received by an independent component.

Since these C# events are outside the Blazor rendering pipeline, you would need to call `StateHasChanged()` on other components you wish to render in response to your state manager's events.

This is very similar to the previous case with `System.Timers.Timer`. However, since your execution call stack typically remains on the renderer's synchronization context, you will not normally need to use `InvokeAsync()` in this case. You would only need to use `InvokeAsync()` if your logic does something to escape from the synchronization context, such as calling `ContinueWith` on a `Task`, or awaiting a `Task` with `ConfigureAwait(false)`.

**Comment by guardrex** [comment]
> adding it as a new page called "Rendering" within Blazor's "Fundamendals" category

We've been classifying "fundamentals" subjects as more like 'fundamental to any app' (e.g., logging, config, DI, environments, startup ... etc.). Are you ok if this goes into the *Components* node of topics somewhere under the *Overview* ...

https://docs.microsoft.com/aspnet/core/blazor/components/

> convert this into an actual PR

No worries ... I'll take care of it and ping u on the PR later.

**Comment by SteveSandersonMS** [comment]
Yes, please place it wherever you feel is best! Thanks for making the PR.

**Comment by kevingates** [comment]
@SteveSandersonMS : is it possible for you to address when to use `await base.InvokeAsync(StateHasChanged);` versus `StateHasChanged()`? I don't see that mentioned in the documentation. It looks like you were getting to that at the end maybe but nothing was explicitly mentioned.

That sound: wow, thank you for this documentation. It's very help! :)

**Comment by guardrex** [comment]
@SteveSandersonMS, I'll have this up and ready to merge shortly. There are only grammar nits, so I'm not planning on pinging u for review. I'll wait to merge the PR until tomorrow (Wednesday) morning to see if you respond to @kevingates and supply additional text for the topic to cover that.

**Comment by SteveSandersonMS** [comment]
> is it possible for you to address when to use await base.InvokeAsync(StateHasChanged); versus StateHasChanged()? 

I'm not sure where the `base.` prefix is coming from. Is that mentioned somewhere else in docs? If so we should change that.

The `InvokeAsync` method is on the base class. Prefixing the invocation with `base.` doesn't achieve anything. It's the same as just calling `InvokeAsync`. The docs I wrote do discuss when `InvokeAsync` is needed.

**Comment by guardrex** [comment]
It's not anywhere in the docs.

**Comment by kevingates** [comment]
I guess I don't see it anymore either. Note, this issue was originally posted **December 2019**. I remember finding that somewhere, but perhaps it was removed / edited. If it isn't relevant now (and not currently listed in documentation) then don't worry about.

I appreciation the clarification.

**Comment by guardrex** [comment]
Yes, that's possible. The docs have churned a lot since then.
