### ISSUE TITLE
How to use Microsoft.dotnet-openapi?

### ISSUE THREAD

**Issue by doggy8088** [dotnet/AspNetCore.Docs#16158]
Is there any workable example that shown the Microsoft.dotnet-openapi's usage?

I totally have no idea how to use Microsoft.dotnet-openapi to generate client code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 653e14ef-227e-a165-0360-2f59259e16c6
* Version Independent ID: e4685d05-e874-76a3-9780-66b864eca6c1
* Content: [Develop ASP.NET Core apps using OpenAPI](https://docs.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/Microsoft.dotnet-openapi.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/Microsoft.dotnet-openapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ryanbrandenburg
* Microsoft Alias: **rybrande**

**Comment by Rick-Anderson** [comment]
This is what we have.

**Comment by doggy8088** [comment]
I really don't understand how to use the tool. I can't find any other useful information either. Is it possible to improve the doc?

**Comment by rafaelldi** [comment]
Hi,
call this comand `dotnet openapi add url -p ./Client.csproj --output-file SomeApi.json http://localhost:5000/swagger/v1/swagger.json`. It will generates `SomeApiClient.cs` partial class in the `obj` folder from the OpenAPI contract. After that, add an empty `SomeApiClient` to your project. Now, you can call API methods with `SomeApiClient`.
Here is my [example project](https://github.com/rafaelldi/RestWithAspNetCore/tree/master/GeneratedWithGlobalTool).

**Comment by doggy8088** [comment]
@rafaelldi It do works. Thanks for your example! I'm just thinking the doc should have more relevant context or contains more technical details.

**Comment by jkone27** [comment]
Can you guys re-open this? docs don't seem to explain exactly how to use it, or what it actually does: https://docs.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-3.1 

Very nice though! thanks

**Comment by Rick-Anderson** [comment]
Dup of #16158

**Comment by doggy8088** [comment]
@Rick-Anderson This issue is #16158 😅

**Comment by joepb** [comment]
The docs still don't give a single clue how to use it. I don't get any file generated anywhere, apart from the json I already had.

**Comment by fuentco** [comment]
Hello,

Some comments on usage, and a question. I have a dotnet worker app where I'll test API calls. I'm generating an openapi client csharp file using

`dotnet openapi add file OpenApiDefinitions/autenticacion.json --code-generator NSwagCSharp`

where autenticacion.json is my API swagger definition.

Then `dotnet run`.  This generates autentacionClient.cs in the obj folder. Since I want to analyze the generated file, and maybe do some changes, I copy it to another directory in my project (e.g. Services). Then deleted the obj reference so it's not created in every compilation (`dotnet openapi remove file `OpenApiDefinitions/autenticacion.json`) This removes the reference in csproj file (it also deletes autentication.json file, so it's good to have a copy elsewhere - it does not matter when using an openapi definition URL instead of a file)

I can successfully use the generated classes and make an API call:

var apiCall = new autenticacionClient(new Httpclient());
var response = await apiCall.SeedAsync(); // This is the api call

The API Call returns a XML in the body. When I try to get the response, there is the error "Could not deserialize the response body stream as System.Byte[]"

It seems that the generated code is treating the response as JSON. How can I read the raw response?

Thanks

**Comment by dexcompiler** [comment]
I don't understand the haste to close this issue while it is still unresolved

**Comment by wadepickett** [comment]
Re-opened with #34786 so it is tracked with the newer location and file name for this topic and not orphaned.

This document was moved and its file name re-named at one point.
It now published here:
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/openapi-tools?view=aspnetcore-9.0
Source:
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/openapi/openapi-tools.md

Some new topics have been published recently and other updated to expand on what we have available for samples and instruction:
[Overview](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/overview?view=aspnetcore-9.0)
[Generate OpenAPI documents](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?view=aspnetcore-9.0)
[Include OpenAPI metadata](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/include-metadata?view=aspnetcore-9.0)
[Customize OpenAPI documents](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/customize-openapi?view=aspnetcore-9.0)
[Use OpenAPI documents](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/using-openapi-documents?view=aspnetcore-9.0)
[Create a controller-based web AP - (Also shows how to use additional tooling to create ad hoc test pages for your API](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-9.0)
[Create a minimal web API](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-9.0)

The last 3 topics in the list above show how to use additional tooling, both from Microsoft and others to quickly generate code and ad-hoc UI testing pages to consume the API from the client end, which may be closer to I think to what you were originally looking for.  Examples there include using NSwag/SwaggerUI, Scalar, Spectral and Visual Studio's [Endpoints Explorer and .http files](https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-9.0#use-endpoints-explorer) to quickly auto-generate client code  and even UI for ad-hoc testing your API.
