### ISSUE TITLE
IOptionsChangeTokenSource<T> and IChangeToken

### ISSUE THREAD

**Issue by John0King** [dotnet/AspNetCore.Docs#16360]
hi, I'm implement my own changable options, and I'm confusing about the `IChangeToken` now.
This questions is also related to  the `IOptionsChangeTokenSource<T>`,

The  `IOptionsChangeTokenSource<T>.GetChangeToken()`  return a `IChangeToken` ,  but it seems not all `IChangeToken` can fire event

https://github.com/aspnet/Extensions/blob/06dcb43bfb372585d3801cfc333a2d9ee9c189ea/src/Primitives/src/IChangeToken.cs#L18-L22

that said 
```c#
 /// <summary> 
 /// Indicates if this token will pro-actively raise callbacks. If <c>false</c>, the token consumer must 
 /// poll <see cref="HasChanged" /> to detect changes. 
 /// </summary> 

 bool ActiveChangeCallbacks { get; } 
```

and I read all the source code, but I can not find any method that handle `ActiveChangeCallbacks=false`  ,  so does that mean if my changetoken can not fire event, the `IOptionMonitor<T>` can not fire event too ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @John0King ... Fair question. We added "change notifications" only to the extent that they exist (and imply that they work for the scenarios covered by the topic when the framework needs to track changes in Options). Thus far, it's been considered an advanced scenario, and your question is the first of this nature since the topic was written.

I'd like to see about adding content and an example to cover this question. I don't know what that will look like at this time, and I can't answer your question simply because I haven't dug into the source or worked with Options beyond what we currently show.

Although I don't think that this will take very long to address, I don't think that January will be possible ... I'm 🏃😅 for at least January. February is possible. I recommend in the meantime that you ask on a support forum, such as Stack Overflow, and seek out examples on the Net for this scenario.

Leave this issue open. When I come up with something for this, I'll float it to engineering here. You'll get the ping on the discussion about it.

**Comment by guardrex** [comment]
@John0King ... Unfortunately (as you can see :point_up:), I'm not finding the time to get to this issue. I'm 🏃😅 on priority Blazor issues as far as the :eye: can see.

@Rick-Anderson Does this one fall into the 'advanced scenarios' bucket for the community to discuss and dig into (e.g., blog about)? If so, then we can close. If you want it worked, it will need to go to someone on the docs team or one of the engineers for content.

**Comment by Rick-Anderson** [comment]
This is out of the scope of the document.
