### ISSUE TITLE
Creating Dynamic component with databinding from datatable (ADO.NET).

### ISSUE THREAD

**Issue by NavinAT** [dotnet/AspNetCore.Docs#16370]
In our existing control we used to bind the data directly from Datatable (without using poco class).

so, in blazor we couldn't bind the data directly from datatable, it requires poco class to bind data to the components/HTML elements.

Is there any possibility to bind data directly from datatable in blazor ?
Example:

We have Employee Table with two fields 'Name' and 'MobileNumber'.
Wants to bind the Employee data to the input element.

&lt;input @bind=row["Name"] /&gt;
&lt;input @bind=row["MobileNumber"] /&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0&source=docs#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
#### OOF for the :gift: *holidays* :snowman: and will return on January 6.

If you need support, we recommend contacting devs on support channels and chat:

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)

Potential bugs in the ASP.NET Core framework and product feedback can be reported at [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore) (include full repro steps and cross-link to a repro project in GH when appropriate). For Visual Studio, use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture or [Suggest a Feature](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019) gesture within VS, which open internal issues for the VS team. For Visual Studio Code, you can open an issue at [microsoft/vscode issues](https://github.com/Microsoft/vscode/issues).

:dancer::man_dancing: **_Happy New Year! See you in 2020!_** :balloon::champagne:

**Comment by guardrex** [comment]
Hello @NavinAT ... I'm back from vacation. ⛄️

Looks like it will require a [TypeConverter](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter?view=netcore-3.1) because Blazor can't bind a datatable out-of-the-box as it can with more common types. `TypeConverter` was added on https://github.com/dotnet/aspnetcore/pull/10730), but I haven't messed with it myself (*yet!*) in Blazor. We don't have an example of it. You can ask around on support chat for tips and look for examples online in the meantime.

* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [aspnet/Blazor Gitter](https://gitter.im/aspnet/Blazor)

When management sees this, they can let me know if we should have a type converter example in the doc.

You can leave this issue open. Either management will close it or triage it. If worked, it will automatically close when the PR merges.

**Comment by NavinAT** [comment]
Hai **@guardrex**, thanks for the response.

We tried the conversion work using Reflection, which you have mentioned above and it worked for us.
But, **we are looking for some better solution**. Here i will share the code that we achieved using Reflection.
**Custom Component:**
```
<MyField ControlType="TBText" LabelText="Caption" Bind="@datarow["Caption"]" Obj=@datarow></MyField>
<MyField ControlType="TBNumber" LabelText="ShortCaption" Bind="@datarow["ShrtCaption"]" Obj=@datarow></MyField>
```
We added two Parameters, one (Bind) accepts DataRow value and another one (Obj) accepts DataRow object.

```
builder.AddAttribute(3, "value", this.Bind);
builder.AddAttribute(4,"onchange",EventCallback.Factory.CreateBinder(this.Obj, ValueChangeEvent, this.Bind.ToString(), CultureInfo.InvariantCulture));
```
ValueChangeEvent() Method will do the conversion:

```
public void ValueChangeEvent(object obj)
		{
			// DataTable
			DataRow row = this.Obj as DataRow;
			if(row != null)
			{
				row[this.LabelText] = obj;
				return;
			}
                 }
```

**Comment by guardrex** [comment]
Hello @NavinAT ... sorry for the long delay. This was marked as a lower priority issue, and I've been 🏃 for many moons!

I'm still not aware if what engineering did with `TypeConverter` is appropriate. There's a lot of discussion centering around using them for **_parameters_**, not property-to-HTML attribute value binding.

I see `IValueConverter` out there, but that's [not part of .NET Standard yet](https://github.com/dotnet/standard/issues/536). It's also something that I haven't used, so I can't say if it would be appropriate for this scenario if it were available today.

**_Yes!_** perhaps on `CreateBinder`. I was just looking at this recently when we put up [InputText based on the input event](https://docs.microsoft.com/aspnet/core/blazor/forms-validation#inputtext-based-on-the-input-event).

The one that I created for fun was a color picker. Binding like this ....

```razor
<input type="color" @bind="item.Color" />
```

... where `Color` is a `System.Drawing.Color` works for applying the value from the HTML color picker to the class's `Color` property, but it fails going from the `Color` property to the color picker. The color picker renders without a `value` attribute, so it defaults to black. This happens because `@bind` doesn't result in an HTML hex color value (e.g., `#00ff00`), which is required for the color picker to work.

I hacked up the following with `CreateBinder` ......

```razor
@page "/createbinder"
@using System.Drawing 

<h1>CreateBinder Example</h1>

<ul>
    @foreach (var item in items)
    {
        <li>
            Color Picker:
            <input type="color"
                   value="@HexConverter(item.Color)"
                   @onchange="EventCallback.Factory.CreateBinder<Color>(
                        this,
                        __value => item.Color = ColorLogic(__value),
                        item.Color)" />
        </li>
    }
</ul>

<h2>Items</h2>

<ul>
    @foreach (var item in items)
    {
        <li>Color: @item.Color</li>
    }
</ul>


@code {
    private IList<ColorfulItem> items = new List<ColorfulItem>();

    protected override void OnInitialized()
    {
        items.Add(new ColorfulItem { Color = Color.ForestGreen });
        items.Add(new ColorfulItem { Color = Color.CadetBlue });
    }

    private static string HexConverter(Color c)
    {
        return string.Format("#{0:X6}", c.ToArgb() & 0x00FFFFFF);
    }

    private static Color ColorLogic(Color c)
    {
        if (c == Color.Red)
        {
            return Color.Blue;
        }

        return c;
    }

    public class ColorfulItem
    {
        public Color Color { get; set; }
    }
}
```

Notice that I added a little logic there (`ColorLogic`) for the incoming value that will convert a red choice in the HTML color picker into `System.Drawing.Blue` for the instance.

@mkArtakMSFT, something simple like that, assuming it isn't another *Rex Code Smell*:tm: 💩👃😵, would be good for the *Binding* topic. Seems like it comes in handy from time-to-time. Do you concur?

Next ❓ is WRT `TypeConverter`. We don't have anything on it. It might be quicker for engineering to whip up a little something. I think I read that it's useful (and was requested a lot) for generics. Perhaps, we need another section in the *Binding* topic for it. Thoughts?

**Comment by guardrex** [comment]
btw @SteveSandersonMS ... Related to what we were just discussing on `CreateBinder`, there's this related issue that asks about how to bind things that the framework can't bind on its own. See my last issue comment :point_up: and @NavinAT's original ask :point_up:.

Thoughts? For example ...

* Should we close this issue as a **_won't fix_** for docs?
* Or, is the use of a **_`TypeConverter`_** the right approach? If so, I'll likely need engineering support to address this issue (but later tho ... in 2021 ... there's no way that I reach this by EOY).

**Comment by guardrex** [comment]
Cross-referencing `TypeConverter` test in framework tests:

* https://github.com/dotnet/aspnetcore/blob/e66ad54db4e996b5aa25c22983a840322727eca8/src/Components/Components/test/BindConverterTest.cs#L256-L305
* https://github.com/dotnet/aspnetcore/blob/e66ad54db4e996b5aa25c22983a840322727eca8/src/Components/Components/test/BindConverterTest.cs#L229-L246

@NavinAT ... Sorry that it's taking so long to get to this, but I've been 🏃😅 on higher priority issues for quite a while. This issue hasn't been forgotten, and I hope to draft something for this in 2021. Your exact request (i.e., row of a datatable) or the color picker scenario are still possibilities for showing how to use a `TypeConverter`.

**Comment by NavinAT** [comment]
Hai @guardrex thank you for the sample code, I looked at it and it's useful for us to work with Datatable.

**Comment by guardrex** [comment]
OK ... I finally did get an answer on this. It came back ......

> `CreateBinder` is in an awkward place where it’s technically public, but has always been accompanied by a comment in its XML docs saying “For internal use only”. It’s really intended as an implementation detail of Razor compilation.

 Therefore, we won't be documenting it at this time, and the product unit will continue to take feedback on special binding scenarios.

As for `TypeConverter`, I don't have direction from the product unit at this time to cover it. If/when they call for such coverage, then we'll open a new issue for it.
