### ISSUE TITLE
Updates to Blazor WASM Startup content

### ISSUE THREAD

**Issue by rynowak** [dotnet/AspNetCore.Docs#16648]
As part of the next preview we're reworking Blazor WASM's startup experience: https://github.com/dotnet/aspnetcore/pull/18455

This item tracks making all of the documentation updates as well as:

- How to run initialization code before the UI is shown (new example)

Note: we expose `IConfigurationBuilder` as part of the API now, but we don't plan to include it in the docs at this time. We haven't nailed down the details of how we expect config sources to show up here.

**Comment by guardrex** [comment]
@captainsafia ... Did we get this one done with the work we did on config earlier? If not, do you know what we're missing?

**Comment by captainsafia** [comment]
We've got pretty good docs on configuration.

> How to run initialization code before the UI is shown (new example)

I think we cover this. I'd probably include this like configuring logging and auth as "run initialization code before UI is shown".

I feel pretty comfortable with closing this and adding specific pieces of content in response to user requests since I can't think of anything we aren't covering WRT to this.
