### ISSUE TITLE
Highlight the importance of order when inserting NewtonsoftJsonPatchInputFormatter 

### ISSUE THREAD

**Issue by rbenitti** [dotnet/AspNetCore.Docs#16740]
It should be noted that adding `NewtonsoftJsonPatchInputFormatter `at the end of `options.InputFormatters` will yield an unexpected behaviour, as the `InputFormatters `collection is traversed in order and `Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter` (which supports "application/*+json" as media type) would be found first. Thus, it will be the later the one to consume and parse the body request, generating a null or empty `JsonPatchDocument`.
Besides, it would be helpful if the article pointed out that `NewtonsoftJsonPatchInputFormatter `only supports `"application/json-patch+json"` as media type, so the patch header "Content-Type" should be set to this value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm  if you can provide a draft of this I'll add it to the article.

**Comment by lsuarez5280** [comment]
@Rick-Anderson You could probably do this with a sufficient update to the [JsonPatch, AddNewtonsoftJson, and System.Text.Json](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.1#jsonpatch-addnewtonsoftjson-and-systemtextjson) code sample. To be honest, the sample is duplicative, clunky, and probably not the best way to go about achieving the objective because it recreates a second service provider when none is needed. The formatter is already present in the collection. It just needs to be moved after configuration is complete. Here's a suggested change to the code sample that should sufficiently avoid creating a second service collection and explain the purpose of the block:

```
public void ConfigureServices(IServiceCollection services)
{
    services.PostConfigure<MvcOptions>(options =>
    {
        // Move the JSON patch input formatter to the first index of the list so it is evaluated before other formatters to handle applicable content types
        var patchFormatter = options.InputFormatters.OfType<NewtonsoftJsonPatchInputFormatter>().First();
        options.InputFormatters.Remove(patchFormatter);
        options.InputFormatters.Insert(0, patchFormatter);
    });
}
```

**Comment by Rick-Anderson** [comment]
Tracked in JsonPatch Master issue. Look here #18330
