### ISSUE TITLE
Split the `JSInterop` Blazor topic

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#16935]
Currently, the `JavaScript Interop` topic is quite long and has two main subsections:
- Invoke .NET methods from JavaScript functions
- Invoke JavaScript functions from .NET methods

It would be great to turn these into separate articles under `JavaScript Interop` node in the TOC.
@guardrex I know we've talked in a separate thread that a flat list under `Blazor` would be fine, but treat that as a the first step. So let's turn these two into separate topics.

**Comment by guardrex** [comment]
There's common content, so we need an overview topic to go with them. It's also best if we create the *TOC node* (folder) now because I can't change the UID later when topics are moved into a node (folder) without a lot of pushback from the docs cats. No worries if we just set it up with a node/folder now. Because the advanced scenarios and common content require a simple/quick explanation first, the node could go something like this ...

* JS interop
  * Overview
    * Introduction
    * Simple/quick example of invoking .NET method
    * Simple/quick example of invoking JS FN
    * Common JS interop content
  * Invoke .NET methods from JavaScript functions
  * Invoke JavaScript functions from .NET methods
