### ISSUE TITLE
Create a new topic for TestServer scenarios

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#16953]
In .NET Core 3.0 pretty much everything in ASP.NET Core moved to use the new generic host, but this doc still discusses using TestServer with the older web host. This doc should be updated to show how to use TestServer with the generic host. Like this: https://github.com/dotnet/aspnetcore/blob/master/src/Hosting/TestHost/test/TestServerTests.cs#L51

**Comment by guardrex** [comment]
I asked at the time (first bullet) ...

https://github.com/aspnet/AspNetCore.Docs/pull/14265#issue-316624590

... but I didn't get that guidance ...

https://github.com/aspnet/AspNetCore.Docs/pull/14265#issuecomment-532171607

I'll get this scheduled.

**Comment by guardrex** [comment]
@danroth27 I don't understand this pattern in the context of a separate test project. Comparing the example that you linked, the host isn't created in the *Arrange* step ... it's a separate project that the factory bootstraps. Can you/Javier convert one test for me? ... the basic test below. I'll use that as a template to proceed with the updates. Conversely, point me to an existing sample that tests a separate project, and I can grok the pattern from it.

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/IntegrationTests/BasicTests.cs

```csharp
public class BasicTests
        : IClassFixture<WebApplicationFactory<RazorPagesProject.Startup>>
{
    private readonly WebApplicationFactory<RazorPagesProject.Startup> _factory;

    public BasicTests(WebApplicationFactory<RazorPagesProject.Startup> factory)
    {
        _factory = factory;
    }

    [Theory]
    [InlineData("/")]
    [InlineData("/Index")]
    [InlineData("/About")]
    [InlineData("/Privacy")]
    [InlineData("/Contact")]
    public async Task Get_EndpointsReturnSuccessAndCorrectContentType(string url)
    {
        // Arrange
        var client = _factory.CreateClient();

        // Act
        var response = await client.GetAsync(url);

        // Assert
        response.EnsureSuccessStatusCode(); // Status Code 200-299
        Assert.Equal("text/html; charset=utf-8",
            response.Content.Headers.ContentType.ToString());
    }
}
```

**Comment by danroth27** [comment]
Adding @Tratcher and @javiercn to get their thoughts on how this should be documented.

**Comment by Tratcher** [comment]
@guardrex WebApplicationFactory is aware of both WebHost and GenericHost and creates the TestServer accordingly. You shouldn't need to modify that sample.

@danroth27 I don't see anything in this article that needs updating. I don't see any articles that deal directly with TestServer for that matter.

**Comment by guardrex** [comment]
@danroth27 Ok to close this?

**Comment by danroth27** [comment]
@Tratcher @guardrex I filed this issue because a customer had pinged me about how to setup their TestServer when using HostBuilder. I pointed the customer to https://github.com/dotnet/aspnetcore/blob/master/src/Hosting/TestHost/test/TestServerTests.cs#L51, but I couldn't find this pattern explained in the docs. Is it covered and I just missed it?

**Comment by guardrex** [comment]
@danroth27 That pattern isn't covered in the docs, but that's *by-design*. IIRC, Javier said something like he/the team doesn't intend for devs to use `TestServer` directly in most scenarios. If you want, I'll research back and see if I can locate that discussion with exactly what was said at the time.

**Comment by Tratcher** [comment]
We should add docs for TestServer, but it's scenarios are different. This integration testing doc is for testing entire applications. TestServer is built to test individual components like middleware.

**Comment by guardrex** [comment]
In that case, I'll mark this for a new doc. We'll need to round up the usual suspects:

* Title
* TOC (filename, URL)
* UID
* Outline

I'm burning thru Blazor issues at a decent pace. I can probably work the issue if one of you will provide an outline, main examples of what should be shown, and any tips, gotchas, etc.

**Comment by Tratcher** [comment]
Maybe what we need is a testing section added to the middleware authoring doc:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-3.1

Intro:
Middleware can be tested in isolation using the TestServer. This allows you to instantiate an app pipeline containing only the components you need to test and send custom requests to verify their behavior. The requests are sent in-memory rather than being serialized over the network and avoid concerns like port management, https certificates, etc.. Exceptions in the middleware can also flow directly back to the calling test.

Example 1: Set up your test app, add your own middleware and services
https://github.com/dotnet/aspnetcore/blob/169f07c6675712aba5cf84c41e61838cebde2906/src/Hosting/TestHost/test/TestServerTests.cs#L53-L60

Example 2: Send a request using HttpClient
https://github.com/dotnet/aspnetcore/blob/169f07c6675712aba5cf84c41e61838cebde2906/src/Hosting/TestHost/test/TestServerTests.cs#L62

Example 3: 
Send a request using `SendAsync(Action<HttpContext>)`. This lets you directly configure an HttpContext object rather than using the HttpClient abstractions. Use this when you need to manipulate structures only available on the server like HttpContext.Items or HttpContext.Features.
https://github.com/dotnet/aspnetcore/blob/169f07c6675712aba5cf84c41e61838cebde2906/src/Hosting/TestHost/test/HttpContextBuilderTests.cs#L28-L33

**Comment by guardrex** [comment]
We're not 100% there yet, but we've been trying to coalesce testing guidance in the *Test, debug, and troubleshoot* node and then cross-link it where it applies.

Thanks for that ☝️. I have enough here to work this now. If things go well with my next two Blazor tasks (CSP with Blazor and EF Core with Blazor), I think I can work this next week.
