### ISSUE TITLE
dotnet [SPACE] aspnet-codegenerator vs dotnet-aspnet-codegenerator 

### ISSUE THREAD

**Issue by msjaber** [dotnet/AspNetCore.Docs#16997]
@Rick-Anderson  edit:

It's `dotnet-aspnet-REST-of-command`
Not `dotnet SPACE aspnet-REST-of-command`
` END OF EDIT`

In Scaffold a controller, the command should be fixed  from
"dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers"

to
"dotnet-aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers"

`@Rick-Anderson edit `

They ultimately run the same tool, but `dotnet SPACE aspnet-REST-of-command` is preferred because it has better error handling. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 63377](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63377)

**Comment by Rick-Anderson** [comment]
This needs to be fixed:

* Here, for Web API
* In RP
* In MVC

Need to also add the following command after  `dotnet tool install --global dotnet-aspnet-codegenerator`:

`dotnet tool update -g Dotnet-aspnet-codegenerator`

**Comment by Rick-Anderson** [comment]
@msjaber actually they resolve to the same tool. On the next doc update, we'll want to update this.

**Comment by quammy** [comment]
Hi, 
I'm on VSCode and and when running the command 

```dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers```

It results for me with this error:

PS C:\Users\XXX\TodoApi> dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers   
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-aspnet-codegenerator does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

I checked the PATH and it has the ..\dotnet\tools registered and the dotnet-aspnet-codegenerator in the folder.
I tried also with the dash (instead of the space) but got the same result.
I also executed this one "dotnet tool update -g Dotnet-aspnet-codegenerator" from the above comment.
Any idea what is wrong?
Thanks.

**Comment by joffarex** [comment]
If you guys are on windows 10, run ```set PATH=$HOME/.dotnet/tools:$PATH``` command, restart terminal and then you can use ```dotnet aspnet-codegenerator```

**Comment by kewalaka** [comment]
@joffarex I didn't need to change the path, but i did have to restart the terminal, I think that should be noted in the docs?

**Comment by joffarex** [comment]
@kewalaka Yes indeed. even what i wrote about changing the path must have been in docs.

**Comment by wadepickett** [comment]
closed with #19500

**Comment by wadepickett** [comment]
This was closed accidently when just one of the docs with this issue was fixed.  There are several.  Sorry it was closed.  This needs to remain open until all the docs have been addressed that Rick pointed out above.
