### ISSUE TITLE
Add section on TypeConverter

### ISSUE THREAD

**Issue by drdamour** [dotnet/AspNetCore.Docs#17002]
Lots of ways to encode a date & datetime, this article should describe what formats the default binders accept, or at least link to info about that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@dougbu  please comment.

**Comment by dougbu** [comment]
Unassigning myself because I'm commenting.

ASP.NET Core doesn't special-case `DateTime` values at all; binding is done using the default `TypeConverter` for the type. This is the same for most simple types though we add special cases for `decimal`, `double`, `enum`, and `float`. The details should already be described in the .NET and .NET Core docs.

If we don't already cover fact `TypeConverter`s are used in model binding, that might be worth documenting somewhere so readers know where to look for supported formats. And, if we take the time to do that, **might** also mention the following special cases:
- support thousands separators in received strings for `decimal`, `double` and `float` values unless `FloatingPointTypeModelBinderProvider` is removed from `MvcOptions.ModelBinderProviders`
- disallow binding undefined integer values to an `enum` unless `EnumTypeModelBinderProvider` is removed from `MvcOptions.ModelBinderProviders`

----
/cc @pranavkm in case you have something to add

**Comment by Rick-Anderson** [comment]
[Model binding review](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1#model-binding-review) has some info on `TypeConverter`, but not much.
cc @serpent5  if you're interested.

**Comment by serpent5** [comment]
It looks like this is similar to #11820, which is being tracked in #16319.

**Comment by Rick-Anderson** [comment]
Moved to #16319
