### ISSUE TITLE
No explanation of how @ prior to a parameter name affects the way the value is passed

### ISSUE THREAD

**Issue by binki** [dotnet/AspNetCore.Docs#17119]
[EDIT by guardrex to fix the encoding]

It seems like doing something like `<a @onclick="x" />` somehow does double binding against the member `x` (or one way binding if `x` is not writable). And that `<a onclick="@x" />` does one-way passing of the member.

Where is this explained? When should I use one style versus the other?

It seems that `@parameter="«expression»"` is used to pass a non-string value. But `parameter="@expression"` is really just a super-simple variant of `parameter="some string @withOptionalInterpolatedValues"`.

It’d be nice if the documentation was clear on this ;-).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#parameters)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The syntax is covered in the https://docs.microsoft.com/aspnet/core/blazor/event-handling topic. Although as you say, we don't get into passing a value to a DOM event handler element attribute value ... that's just ordinary Razor ... and we cross-link here to the Razor syntax topic. We're not focusing on the basic Razor aspects. Let's stick with the current language and see if we receive more feedback of this nature. I'll keep an :ear: open as we go forward.

However, I do see a few nits related to the language that explains event handling and binding syntax, so I'll use this issue to tighten that language up a bit. This issue will close automatically when the PR merges.

Thanks for commenting on this @binki! :rocket:

**Comment by binki** [comment]
Hi @guardrex,

Sorry in advance for sounding harsh below. However, it is my thoughts and hopefully it gives you a better understanding of my confusion. Thank you for your consideration of my feedback and for putting work into this project!

> The syntax is covered in the https://docs.microsoft.com/aspnet/core/blazor/event-handling topic.

I would beg to differ. The syntax covered in that article is specifically quoted here:

> For an HTML element attribute named [`@on{EVENT}`](https://docs.microsoft.com/aspnet/core/mvc/views/razor?view=aspnetcore-3.1#onevent) (for example, `@onclick`) with a delegate-typed value, a Razor component treats the attribute's value as an event handler.

This is not a documentation of syntax. It is a description of one particular pattern using the Razor syntax.

A description of Razor syntax would say:
 > When instantiating a component, any attributes specified using the syntax `«attributeName»="«razorStringExpression»"` will be passed the `string` value yielded by evaluating `«razorStringExpression»`. You may interpolate values in `«razorStringExpression»` because this expression is evaluated using razor (for example, `myAttribute="This is my name: @name"` or `name="@name"`). You may not include elements in `«razorStringExpression»`.
>
> Some components accept/require/expect complex types. These cannot be passed using the above syntax. To pass a complex type, place a snail before the attribute name when specifying its value. The syntax is `@«attributeName»="«codeExpression»"`. You may place any expression of the file’s language (e.g., C#) directly in `«codeExpression»`. For example, `@code{ var x = new Person("Nathan", "Brink"); } <Component @person=”x"/>` or `<Component @person="peopleList[0]"/>`.
>
> Note that `«codeExpression»` is interpreted based on the typing of the component property being called. This means that you may write lambdas directly (i.e., instead of writing `@myAttribute='new EventHandler((sender, e) => {})'`, you may simply write `@myAttribute='(sender, e) => {}'`) and rely on any implicit conversions (e.g., you may use `@myAttribute='"x"'` to specify a value for an attribute expecting [`XName`](https://docs.microsoft.com/dotnet/api/system.xml.linq.xname?view=netframework-4.8#properties) rather than having to specify `@myAttribute='(XName)"x"'`).

When I visit a document entitled “Create and use ASP.NET Core Razor components”, I expect to be told how to consume (“use”) Razor components. Including an obvious link to the syntax and a description of what it does.

> Although as you say, we don't get into passing a value to a DOM event handler element attribute value ... that's just ordinary Razor ... and we cross-link here to the Razor syntax topic.

Where is this link? Isn’t this a critical part of (let me quote the title of the document again) “use”-ing “Razor Components”? I was trying to find this when I gave up and filed this issue. Maybe the disconnect is that there isn’t language in that document which clearly explains how Blazor uses Razor syntax and how the sorts of things I am looking for in that document should be read from Razor documentation. There needs to be a paragraph or two which look like the information I am looking for with a link at the end for me to actually find it. I.e., a trap for those like me who are trying to understand Blazor expressions and looking for how to pass attributes which clearly says “The above is a short summary. For more details, please see Razor syntax and its discussion on `<Component/>` syntax **here**” (though for some reason I was certain that `<Component/>` syntax was Blazor-specific…).

> We're not focusing on the basic Razor aspects. Let's stick with the current language and see if we receive more feedback of this nature. I'll keep an 👂 open as we go forward.
> 
> However, I do see a few nits related to the language that explains event handling and binding syntax, so I'll use this issue to tighten that language up a bit. This issue will close automatically when the PR merges.
> 
> Thanks for commenting on this @binki! 🚀

**Comment by guardrex** [comment]
Thanks ... yes ... my response was a bit quick there 🏃. I was keying in on the event handling directive attributes part of your initial comment. I knew that the directive attribute is cross-linked from the *Event handling* topic, but I didn't realize that it **_wasn't cross-linked_** from the *Component parameters* section of the *Use components* topic (and indeed several of them aren't well cross-linked here). Side note: We just performed two big splits of the *Components* topic ... *Event handling* is a relatively new topic, *Data binding* as well. We're still working on post-split cross-linking. Contributing to the problem, the *Event handling* topic is listed **_after_** this one in the TOC (table of contents), so the typical reader won't see it before reading the *Use components* section.

Couple of points for further work ...

**Guidance on framework fundamentals guidance**

Early in the [Component classes](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#component-classes) section, there's this blanket statement with "Razor" cross-linked to the *Razor syntax* topic ...

> The UI for a component is defined using HTML. Dynamic rendering logic (for example, loops, conditionals, expressions) is added using an embedded C# syntax called Razor.

That's probably not going to cut it all by itself. My concern is that we don't say that a reader new to .NET or new to programming should go ahead and familiarize themselves with that content. Indeed, we take the same approach for many ASP.NET Core fundamentals concepts as they relate to Blazor. Perhaps, there should be some guidance in the Blazor framework *Overview* topic on what to read or where to find fundamentals topics.

**Razor syntax and usage in Blazor in the Blazor TOC node**

Let me broaden my earlier response a bit ... what I was saying about `on{EVENT}` was more of just an example for that specific use case.

> clearly explains how Blazor uses Razor syntax and how the sorts of things I am looking for in that document should be read from Razor documentation

Yes, that's the goal. To the extent it isn't accomplished yet, it's mostly due to normal doc challenges (e.g., heavy workload, recent doc changes ... the *topic split* that I mentioned, the appearance of feedback for things that we don't spot or think of in the first place).

AFAIK, most/many of the directive attributes are linked to the Razor syntax topic where they appear in this node of the TOC ... but not everywhere. 

*I need to address the problem further for all of the directive attributes here.*

**Blazor directive attributes (and component directives, too) in the Razor syntax topic**

I just noticed that the *directives* have this lead-in paragraph ...

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1#directives

... which may or may not be sufficient (we'll need to look closer at that, too), but the *directive attributes* section doesn't have any such lead-in paragraph ...

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1#directive-attributes

*The section should have a lead-in to explain what the directives that follow are/do.*

I'll re-open and take another stab 🔪 at this soon. I'll look at your language for improvements on how these concepts are described. Thanks again for your feedback.

**Comment by binki** [comment]
@guardrex 
> ... which may or may not be sufficient (we'll need to look closer at that, too), but the _directive attributes_ section doesn't have any such lead-in paragraph ...
> 
> https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1#directive-attributes
> 
> _The section should have a lead-in to explain what the directives that follow are/do._

A lead-in paragraph here could be that missing link! It describes common attribute patterns and some universal attributes (e.g., `@key`). But it doesn’t really explain that it is referring to directives placed within a component “invocation” (i.e., in the opening tag where attributes passed to the component are placed). And while I have suspicions from grappling with things and reading around what a “directive attribute” is, it seems like a weird name for it. They are kind of different from top-level directives like `@page` and `@using`, but now I am starting to see how they are similar. Maybe directive attributes are not as much like react props as I think they are. Or maybe sometimes they are but not always.

> I'll re-open and take another stab 🔪 at this soon. I'll look at your language for improvements on how these concepts are described. Thanks again for your feedback.

Again, thanks very much!

The historical background and WIP nature of the docs is interesting to hear about. It is also reassuring that you understand the confusion of an outsider such as myself :-).
