### ISSUE TITLE
Style change has made table column too small

### ISSUE THREAD

**Issue by JamesNK** [dotnet/AspNetCore.Docs#17124]
The "Option" column in the tables on this page is small and the option name is being wrapped. It is hard to understand what it is suppose to say.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fc8dc9f-9cc8-bda7-2cda-e9461f7c3a5d
* Version Independent ID: 85b23cfb-29a8-37f4-16f7-fdf6b0dde773
* Content: [gRPC for .NET configuration](https://docs.microsoft.com/en-us/aspnet/core/grpc/configuration?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/grpc/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
What I see:

![image](https://user-images.githubusercontent.com/303201/75323464-d43aeb00-58d9-11ea-8562-de3a00a0934b.png)

**Comment by guardrex** [comment]
You can force it and maintain the breaking behavior in other table cells. Instead of normal markdown code fencing for these ... for example ...

> \`MaxSendMessageSize\`

... force the style not to break (has to be done with the `<code>` element given the stylesheet rule in place) ...

> &lt;code style="word-break:normal"&gt;MaxSendMessageSize&lt;/code&gt;

If they're all done that way, it *should* work. 🤞🍀

**Comment by JamesNK** [comment]
Re-opening. Can close when we've confirmed it has been fixed.

**Comment by guardrex** [comment]
I'm performing one more test before throwing in the towel. IMHO, they should leave explicit tags alone ... but I'm sure they don't care what I think. :smile: lol

**Comment by guardrex** [comment]
@JamesNK **_Partial success!_** :tada: Turns out they will leave a `<span>` alone. Are you ok with non-code-styled entries in that first column?

https://docs.microsoft.com/en-us/aspnet/core/grpc/configuration

...... **_OR_** I can style the `<span>` to match a `<code>` style and then put the rest of them back to reverse-ticks (code) if you really want everything code styled. :ear:

**Comment by JamesNK** [comment]
I'm ok with non-code styled entries.

**Comment by guardrex** [comment]
Cool beans ... fixed by https://github.com/dotnet/AspNetCore.Docs/pull/17137.

Note to us ...... they strip `style` attr from `<code>` elements, but we seem safe with others.
