### ISSUE TITLE
IOptionsMonitor<MyOptionsWithDelegateConfig> in the example will not update with changes

### ISSUE THREAD

**Issue by redtaped** [dotnet/AspNetCore.Docs#17146]
The example shows using IOptionsMonitor with a delegate registration. Unfortunately, this will work the same as IOptions because the framework will not register an IOptionsChangeTokenSource&lt;TOptions&gt;.

This will only work if also using the non delegate registration that receives an IConfiguration, as this method will register the IOptionsChangeTokenSource&lt;TOptions&gt; and then the subsequent delegate will be fired as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@HaoK We didn't hit any stumbling blocks when we set this guidance up. Can you confirm that this is a problem? Note that I can work this issue, but I might be delayed a few weeks due to high priority Blazor work. If you find a problem here, let me know how **_severe_** you think it is so that I can prioritize this correctly in light of that other work.

**Comment by HaoK** [comment]
Its unclear to me exactly what section/doc is being referenced, but generally yes, there would need to be something that triggers the reload, i.e. a `Configure(configuration)` or some other mechanism that triggers the reload.  I don't think this is high priority since it should be inferred that something needs to trigger the invalidation/reloads

**Comment by guardrex** [comment]
Thanks @HaoK ... I was hoping such is the case and that perhaps the doc just isn't explicit enough on the point. I'm 🏃🏃🏃🏃🏃😅 at the moment. Thanks again for the report @redtaped. I'll take a closer look as soon as I get some time.

**Comment by Rick-Anderson** [comment]
Tracked in Options pattern master issue: Check here first #18291
