### ISSUE TITLE
How to set pathbase in Visual Studio 2019

### ISSUE THREAD

**Issue by hultqvist** [dotnet/AspNetCore.Docs#17185]
[EDIT by guardrex to change the topic]

What's the equivalent of "dotnet run --pathbase=" when running from Visual Studio 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8f53b58-a048-69ca-2e89-3625bb4cc839
* Version Independent ID: 32a343a1-ba87-7274-e861-2ac194d5aa3d
* Content: [Web server implementations in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-3.0&tabs=windows)
* Content Source: [aspnetcore/fundamentals/servers/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hultqvist ... It's **_almost_** covered in the [Server startup section of the Servers topic](https://docs.microsoft.com/aspnet/core/fundamentals/servers/#server-startup) ... it's just not explicit and the linked topics there don't call it out. We have it sprinkled in the docs in a few critical spots, but the best spot is probably here in the *Servers* topic. It's a project launch settings property (`commandLineArgs` in *Properties/launchSettings.json*) ...

<img width="664" alt="Capture" src="https://user-images.githubusercontent.com/1622880/75777172-19687e00-5d1b-11ea-816a-03b9fac6d998.PNG">

<img width="504" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/75777210-284f3080-5d1b-11ea-9960-9fc23392651b.PNG">

Leave this open because I think @Rick-Anderson will want to call it out. He'll make the call.

**Comment by Rick-Anderson** [comment]
This issue shows how to do it.  ⌚️ to see if it needs to be added to doc.
