### ISSUE TITLE
Update the `Getting Started` content for Blazor to reflect on the renamed components packages

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#17197]
@guardrex the Blazor package names have been renamed and that also impacted the templates package.

**Comment by guardrex** [comment]
@mkArtakMSFT Looking at the app's provided by the preview template, the name changes aren't obvious. Is there a list somewhere?

Also, this issue is probably as good a spot as any to call out the following versioning challenge given that one or more of these component name changes may apply to Blazor Server apps/docs ...

We're not going to have an `aspnetcore-3.2` moniker with which to version content because this isn't a formal ASP.NET Core release.

We're fine for Blazor WebAssembly because we're just keeping everything current for Blazor WebAssembly.

Versioning updates for **Blazor Server** might get a little tricky. I'll probably need to have alternative blocks of content with lines saying things like ...

> For an app based on the Blazor Server template version 3.2 or later, blah blah blah ...

> For an app based on the Blazor Server template version 3.1 or earlier, blah blah blah ...

We'll know more as I work thru the updates and see what's what.

**Comment by danroth27** [comment]
@guardrex It's fine to leave the Blazor WebAssembly content in the ASP.NET Core 3.1 docs. The initial release of Blazor WebAssembly will be based on .NET Core 3.1.

**Comment by danroth27** [comment]
@guardrex This issue is really about the recent *package* renames: https://github.com/dotnet/aspnetcore/issues/18384. `Basically Microsoft.AspNetCore.Blazor.*` -> `Microsoft.AspNetCore.Components.WebAssembly.*`. This affects namespaces too.
