### ISSUE TITLE
Startup.cs no longer a part of Blazor WASM projects

### ISSUE THREAD

**Issue by adam000** [dotnet/AspNetCore.Docs#17233]
In [this section](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio#add-signalr-services-and-an-endpoint-for-the-signalr-hub) the tutorial makes references to Startup.cs, which IIUC is no longer a thing.

I figured out that the equivalent for `services.AddSignalR();` is now `builder.Services.AddSignalR();` in Program.cs but I'm fairly new to this whole world and have no idea how to convert `endpoints.MapHub&lt;ChatHub&gt;("/chatHub");`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio#add-signalr-services-and-an-endpoint-for-the-signalr-hub)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @adam000 ... It's a Blazor **_Hosted_** app, so there's a server project in the solution. The *Startup.cs* for that is here in the sample app for this topic :point_right: https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp/Server/Startup.cs

**Comment by adam000** [comment]
Thanks for the clarification. This is the first time I've heard the "hosted" keyword as meaning a distinct type of project... (how many are there?? :) )

And the title doesn't mention "Hosted", leading to my confusion.

I guess the root of the issue is that I don't know what I need to do to use SignalR in my app -- are there different docs for using SignalR not-hosted, but in C#? Do I need to switch to hosted? What are the differences?

Any links to help me figure this out would be appreciated.

**Comment by guardrex** [comment]
> the "hosted" keyword as meaning a distinct type of project... (how many are there??

There's *Blazor WebAssembly* in a standalone or hosted configuration and *Blazor Server*.

The *Hosted* template is described in the *Hosting models* topic :point_right: https://docs.microsoft.com/aspnet/core/blazor/hosting-models#blazor-webassembly

... and there's a bit in the Blazor *Host and deploy* topic :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/blazor/webassembly#hosted-deployment-with-aspnet-core

> the title doesn't mention "Hosted", leading to my confusion

It's basically an implementation detail that's not wildly relevant since you could have a Blazor WebAssembly app set up and configured as a completely separate project using a completely separate backend server app as the SignalR hub. It just so happens that there's this nice template that will both host and serve the Blazor WebAssembly app ... here, the backend app of this template can be set up as the hub.

> I don't know what I need to do to use SignalR in my app -- are there different docs for using SignalR not-hosted, but in C#

*Yes, indeed!* ... there's a whole *Encyclopedia of SignalR* starting at :point_right: https://docs.microsoft.com/aspnet/core/signalr/introduction

It's cross-linked at the bottom of this topic. 😉

**Comment by adam000** [comment]
Very helpful thanks!

This is the part I was missing:

> you could have a Blazor WebAssembly app set up and configured as a completely separate project using a completely separate backend server app as the SignalR hub

I currently have a project of the `webapi` type that my Blazor WASM app is getting JSON from. Basically the "hosted" template just creates that for me. I suppose I could have converted my old project to use SignalR but it was easier for me to just start with a new "hosted" app and bring the small amount of code I have over to the new world and follow the tutorial as-is.

Thanks again!
