### ISSUE TITLE
Last example should show validation summary on invalid submit rather than valid submit

### ISSUE THREAD

**Issue by ClaudioFriederich** [dotnet/AspNetCore.Docs#17362]
The last example seems backwards - the example shows the validation summary on a valid submit.  This does not seem to make sense - it should show it on an invalid submit (otherwise the user will only see it if they submit it with no errors to show).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It depends on the flow that you want to achieve. This flow for this example is ...

1. The form has a disabled **Submit** button and the `ValidationSummary` isn't displayed/used initially. Individual fields have active validation checks based on their model annotations.
1. The user begins to interact with one of the fields. As soon as the field loses focus, all of the field validation fires. However, the `ValidationSummary` remains hidden ... just because in this flow, the `ValidationSummary` will be used **_after_** the first time the user selects **Submit**.
1. The user finishes the form, the **Submit** button becomes active. The user selects the button. The `ValidationSummary` is now active. You're correct ... it doesn't display anything at this point. It's not supposed to given this flow.
1. It's when either:
  * The user makes additional changes to the form that the `ValidationSummary` displays information about failing fields.
  * Some additional check is made after form submission that would result in a failed validation that isn't directly associated with a field.

Three points ......

1. The main concept here is merely that if one doesn't like the OOB behavior of `ValidationSummary`, they either shouldn't use the `ValidationSummary` component or control it via its CSS style. There are several ways that a form like this can behave, and we can't cover them all, of course. We just want to show how to change the style. In this case, some devs might find it distracting to have **_all fields_** except the first show up in the `ValidationSummary` immediately after the user interacts with the **_first field_**. It's just one behavioral gesture that a dev might want. It's up the dev to take it from there for their form's requirements after they see how they can control the behavior.
1. I think this, like the other examples we discussed on the other issue, can be improved. As we said, this (and the other one) don't show a non-field validation check being made after form submission, nor does it show how to trigger the validation such that an error is displayed in the `ValidationSummary` based on such a failed check. I'd also like to provide some on-page feedback about the valid form submit (i.e., instead of writing it to the console).
1. Finally, I'm not even sure that an example is all that critical to making the main point. The main point is that the dev's options are either don't use it or control it with a style. I can make that point without an example at all or with a minimalist example. It's up the dev to take it from there and create whatever flow they want.

   ```razor
   ...
   <ValidationSummary style="@_displaySummary" />
   ...

   @code {
       private string _displaySummary = " ... ";
   }
   ```

Let me give you the full code that I have locally ... drop this into a test app and you'll see what I mean about this flow. This type of example also might be rolled into the downloadable sample app later after we get caught up and past the 3.2 release.

```razor
@page "/FormsValidation"
@using System
@using System.ComponentModel.DataAnnotations

<h1>Starfleet Starship Database</h1>

<h2>New Ship Entry Form</h2>

<EditForm EditContext="@_editContext" OnValidSubmit="@HandleValidSubmit">
    <DataAnnotationsValidator />
    <ValidationSummary style="@_displaySummary" />

    <p>
        <label>
            Identifier:
            <InputText @bind-Value="_starship.Identifier" />
        </label>
    </p>
    <p>
        <label>
            Description (optional):
            <InputTextArea @bind-Value="_starship.Description" />
        </label>
    </p>
    <p>
        <label>
            Primary Classification:
            <InputSelect @bind-Value="_starship.Classification">
                <option value="">Select classification ...</option>
                <option value="Exploration">Exploration</option>
                <option value="Diplomacy">Diplomacy</option>
                <option value="Defense">Defense</option>
            </InputSelect>
        </label>
    </p>
    <p>
        <label>
            Maximum Accommodation:
            <InputNumber @bind-Value="_starship.MaximumAccommodation" />
        </label>
    </p>
    <p>
        <label>
            Engineering Approval:
            <InputCheckbox @bind-Value="_starship.IsValidatedDesign" />
        </label>
    </p>
    <p>
        <label>
            Production Date:
            <InputDate @bind-Value="_starship.ProductionDate" />
        </label>
    </p>

    <button type="submit" disabled="@_formInvalid">Submit</button>

    <p>
        <a href="http://www.startrek.com/">Star Trek</a>,
        &copy;1966-2019 CBS Studios, Inc. and
        <a href="https://www.paramount.com">Paramount Pictures</a>
    </p>
</EditForm>

@code {
    private Starship _starship = new Starship();
    private bool _formInvalid = true;
    private EditContext _editContext;
    private string _displaySummary = "display:none";

    protected override void OnInitialized()
    {
        _editContext = new EditContext(_starship);
        _editContext.OnFieldChanged += HandleFieldChanged;
    }

    private void HandleFieldChanged(object sender, FieldChangedEventArgs e)
    {
        _formInvalid = !_editContext.Validate();
        StateHasChanged();
    }

    private void HandleValidSubmit()
    {
        _displaySummary = "display:block";
        Console.WriteLine("OnValidSubmit");
    }

    public void Dispose()
    {
        _editContext.OnFieldChanged -= HandleFieldChanged;
    }

    public class Starship
    {
        [Required]
        [StringLength(16, ErrorMessage = "Identifier too long (16 character limit).")]
        public string Identifier { get; set; }

        public string Description { get; set; }

        [Required]
        public string Classification { get; set; }

        [Range(1, 100000, ErrorMessage = "Accommodation invalid (1-100000).")]
        public int MaximumAccommodation { get; set; }

        [Required]
        [Range(typeof(bool), "true", "true",
            ErrorMessage = "This form disallows unapproved ships.")]
        public bool IsValidatedDesign { get; set; }

        [Required]
        public DateTime ProductionDate { get; set; }
    }
}
```

Artak, please mark this with the same priority that you give https://github.com/dotnet/AspNetCore.Docs/issues/17360, and I'll work them together on the same PR. Please provide your feedback if you have guidance.
