### ISSUE TITLE
Request additional access tokens - standalone

### ISSUE THREAD

**Issue by tomidix** [dotnet/AspNetCore.Docs#17415]
Hi,

I need 'Request additional access tokens' scenario but for wasm - standalone, I suppose this is already possible but probably the documentation about it is missing.
Then, what's also missing is how to use those tokens further in httpClient calls. I assume that we don't have to inject those tokens manually.
I'd appreciate if you could add this.

I described what I need to achieve in detail: https://stackoverflow.com/questions/60754751/blazor-webassembly-standalone-access-multiple-aad-protected-apis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2cdb52c-843f-5944-429d-11ea821c1e22
* Version Independent ID: 9c4f99ef-f070-b527-4efc-96a04798d9ef
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by tomidix** [comment]
Any comments on this?
@guardrex ?

**Comment by guardrex** [comment]
Not yet ... I don't have any further information on it yet. I put up the engineering guidance complete as it was provided to me.

Additional details (such as your ask) will be addressed as they arrive. Since this wasn't triaged last Friday, it will probably be triaged on Friday, March 3.

SO was a good idea, but these bits are so new that few know the answer at this time and might not discover your question. There's also a [Blazor Gitter room](https://gitter.im/aspnet/Blazor), where devs may know.

You can [open an issue directly for engineering to ask](https://github.com/dotnet/aspnetcore/issues). If you do, please add "cc: @guardrex" to the end of your opening comment so that I can track the discussion. Provide them the level of detail that you provided in your SO post. In the end, you can summarize your result here if you want, which will probably speed up my ability to cover the scenario.

**Comment by guardrex** [comment]
btw ...

> I assume that we don't have to inject those tokens manually.

Don't assume that ... it's what the `FetchData` component is doing in the current examples ...

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1#fetchdata-component

**Comment by guardrex** [comment]
... also reminds me of this piece ...

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#request-additional-access-tokens

... and :pray: *hopefully* 🙏 that `tokenResult` is the one needed to get the token to make the API request. If so, then you're on the right track thus far ... just add this piece for the call.

**Comment by guardrex** [comment]
I ran a test here that ✨ *Just Works!*:tm: ✨ ...

I granted `Chat.Read` in the portal to my AAD test app. Then, I gave the Client app ...

```csharp
options.ProviderOptions.AdditionalScopesToConsent.Add("https://graph.microsoft.com/Chat.Read");
```

... and ...

```razor
@attribute [Authorize]

<h1>Test Chat.Read Scope</h1>

<p>This component demonstrates obtaining a Chat.Read token.</p>

<button @onclick="GetChatReadToken">Get Chat.Read token</button>

<p>Chat.Read token: @_token</p>

@code {
    private string _token = "No token yet.";

    private async Task GetChatReadToken()
    {
        var tokenResult = await AuthenticationService.RequestAccessToken(
            new AccessTokenRequestOptions
            {
                Scopes = new[] { "https://graph.microsoft.com/Chat.Read" }
            });

        if (tokenResult.TryGetToken(out var token))
        {
            _token = token.Value;
        }
        else
        {
            _token = "Token request failed.";
        }
    }
}
```

<img width="437" alt="Capture" src="https://user-images.githubusercontent.com/1622880/77924636-86632b00-7269-11ea-8bab-a32921543679.PNG">
