### ISSUE TITLE
difference between bind and property name

### ISSUE THREAD

**Issue by junpark12** [dotnet/AspNetCore.Docs#17618]
Hi I cannot clearly distinguish the following differences. 
From the parent-to-child binding section, we can use one of these..
@bind-Year="parentYear" or Year="@parentYear".
Please let me know. Thanks.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1b6ad8-13ba-0195-8829-ade3b1b0b9cb
* Version Independent ID: 6609ea68-a918-f3b9-8c9c-004a4436e350
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1#child-to-parent-binding-with-chained-bind)
* Content Source: [aspnetcore/blazor/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @junpark12 ...

`@bind-Year="parentYear"` is the proper syntax with the `@bind` directive. Year="@parentYear"` should only fill the value of `parentYear` into the value of an attribute named `Year` and not actually bind it (but I haven't even tested that, since it isn't supported). Use the `@bind` directive syntax.
