### ISSUE TITLE
Redirect to HTTPS with IIS standalone deployment

### ISSUE THREAD

**Issue by cornem** [dotnet/AspNetCore.Docs#17617]
Blazor produces its own *web.config*. Is there any way to enable HTTP to HTTPS redirection on IIS without having to edit the generated *web.config* file?

As a workaround, I have added this to my *App.razor* file:

```csharp
protected override void OnInitialized()
{
    if (NavigationManager.Uri.StartsWith("http://"))
    {
        NavigationManager.NavigateTo("https://" + NavigationManager.Uri.Substring(7));
        return;
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b4d6a1-1436-7ba8-a5c5-8dcb6a955bb0
* Version Independent ID: 4a6a13b4-fe5c-a9fb-5d7d-33d5aa0fbac3
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/blazor/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @cornem ... *Yes!* ... **_BUT_** ... you just flagged 😵 **_unexpected behavior_** 😵 in the framework.

Normally, you would supply your own custom *web.config* file in the root of the project and add this to the project file ...

```xml
<PropertyGroup>
  <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
</PropertyGroup>
```

Reference: https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/#configuration-of-iis-with-webconfig

**_BUT_** ... I just ran a test on that. The custom *web.config* is moved to the target framework folder (*bin/Release/netstandard2.1* folder); however, it isn't moved to the *bin/Release/netstandard2.1/publish* folder, which is where you'd really want it for deployment.

Turns out that engineering is already using that property for Blazor WebAssembly ...

https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/Build/src/targets/Publish.targets#L9

Therefore, don't use that ...... **_use this instead_** ...

```xml
<Target Name="CopyWebConfigOnPublish" AfterTargets="Publish">
  <Copy SourceFiles="web.config" DestinationFolder="$(PublishDir)" />
</Target>
```

... which should do the trick.

I'll put that into the topic. Thanks, and I'll ping u on the PR.

I opened https://github.com/dotnet/aspnetcore/issues/20569 for engineering to see if they want to do something else for this scenario.

**Comment by cornem** [comment]
Thanks!

Just to be sure... This means one has to actually include the contents of Blazor's own *web.config* file as well, right? Because if I make a new *web.config* file with just the HTTPS redirection rules, then it just copies my file right over to */publish* without the `<staticContent>`, `<httpCompression>` and `<rewrite>` sections that Blazor produces.

So if you want to use a custom *web.config* file, you start with the one produced by Blazor, and then add you own stuff, correct?

**Comment by guardrex** [comment]
> include the contents of Blazor's own web.config file

Correct ... supply your custom *web.config* at the root of the project exactly the way that you want it deployed. It's going to copy that file at the end of the MSBuild publish to the *publish* folder and overwrite the one that the framework places there.
