### ISSUE TITLE
FetchData documentation

### ISSUE THREAD

**Issue by 23min** [dotnet/AspNetCore.Docs#17673]
I've searched until the edges of the Internet to find out how to get an accessToken to call my Azure Function API after being authenticated (Standalone with AAD / code auth flow).

Thinking that Hosted with AAD B2C topic didn't apply to my scenario I never bothered to look here.

Please add this example or a link to it to each of the documentation pages in this Chapter/Topic. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d682d4c-86b5-c47e-89a3-3684b2235320
* Version Independent ID: a80e115c-466a-288d-a918-9ef7514f5add
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @23min ... It's already covered (*lightly*) in each of the standalone topics. For example in the *Standalone with AAD* topic, it says in the [Authentication service support](https://docs.microsoft.com/aspnet/core/security/blazor/webassembly/standalone-with-azure-active-directory#authentication-service-support) section ...

> The Blazor WebAssembly template doesn't automatically configure the app to request an access token for a secure API. To provision a token as part of the sign-in flow, add the scope to the default access token scopes of the MsalProviderOptions:

... with an example.

I admit that the example isn't generic enough, but I'm going to work on that today. Actually, I'll use this issue for the work because I haven't opened an issue yet for it.

It would be more apparent if the text and example were **_their own sections_** in these docs, so I'll do that, too.

**_... AND_** Those sections should link down to the [Request additional access tokens](https://docs.microsoft.com/aspnet/core/security/blazor/webassembly/additional-scenarios#request-additional-access-tokens) section of the *Additional scenarios* topic.

Thanks for the comment and suggestions. I'll ping u on the PR.

**Comment by 23min** [comment]
Thanks! Yes, token retrieval is not automatic, but that's where the reader was left hanging, without any pointers on how to do this :)

Btw when you write these docs, will you also will test this code to verify they work in the sections they document? (It seems that this code does not work in Preview3 for Azure AD code auth flow because the retrieved token is null / similar symptoms to https://github.com/dotnet/aspnetcore/issues/20288 though it could be user error)

Looking forward to the updated docs!

**Comment by guardrex** [comment]
Yes, indeed. I will test ... and also engineering will perform a careful review of the preview docs before the 3.2 release in May to make sure that they agree with everything before the final docs go live. Right now, these docs are under heavy ... almost daily ... revision. They're usually kind'a crappy at this stage ... incomplete 🙈 ... disorganized 🙊 ... unclear 🙉 ... until we massage them into something halfway decent for release. Fortunately, we have about a month to work on them before 3.2 comes out.

However, note WRT testing that I only have time to perform limited testing. A decent test would be for a standalone app to do something simple like a Graph API call. I won't be able to test more specialized use cases, such as an Azure Function. The community of devs will call out, as you did, when things 💥 with the guidance. Everyone wishes that it didn't have to be this way, but we're a small team with *400 topics to maintain!* **_YIkes!_** 🏃😅

**Comment by guardrex** [comment]
Ok ... well that turned out fine ... I hate to say "**_as expected_**" when it comes to anything having to do with security. :smile: lol

I gave my standalone AAD test app permission to get Organization data via Graph API in the portal.

Then ...

```csharp
options.ProviderOptions.AdditionalScopesToConsent.Add(
    "https://graph.microsoft.com/Organization.Read.All");
```

... and ...

```razor
@page "/organizationdata"
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication
@inject IAccessTokenProvider AuthenticationService
@inject NavigationManager Navigation
@inject HttpClient Http
@attribute [Authorize]

<h1>Organization Data</h1>

<p>This component demonstrates fetching organization data from Graph API.</p>

<p><button @onclick="FetchData">Fetch Data</button></p>

<p>Token: @_token</p>

<p>Data: @_data</p>

@code {
    private string _data;
    private string _token;

    private async Task FetchData()
    {
        var httpClient = new HttpClient();
        httpClient.BaseAddress = new Uri(Navigation.BaseUri);

        var tokenResult = await AuthenticationService.RequestAccessToken(
            new AccessTokenRequestOptions
            {
                Scopes = new[] { "https://graph.microsoft.com/Organization.Read.All" }
            });

        if (tokenResult.TryGetToken(out var token))
        {
            _token = token.Value;
            
            httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {token.Value}");
            _data = await httpClient.GetStringAsync("https://graph.microsoft.com/v1.0/organization");
        }
        else
        {
            Navigation.NavigateTo(tokenResult.RedirectUrl);
        }
    }
}
```

... :beers: :tada: ...

<img width="401" alt="Capture" src="https://user-images.githubusercontent.com/1622880/78823389-363f4380-79a2-11ea-9779-65a01b81f552.PNG">

I'm making the improvements discussed and fixing other little nits.

There's one more thing to take a stab at. The possible reason that I'm having a different experience than Javier is that he was using V2 tokens and I'm using V1. I'm going to try upgrading my app to V2 and see if I can get the full scope URI to work.

Anyway ... PR should be up shortly.
