### ISSUE TITLE
Saving Data

### ISSUE THREAD

**Issue by ctreslovehayes** [dotnet/AspNetCore.Docs#17670]
Hi, I have followed the Tutorial but when I stop debugging all data is lost. Is this expected?
When I actually deploy the app, will the data stay permanent or will it be lost on reboot or similar?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by HamidMolareza** [comment]
Hi, This article use an **in-memory database**. This means that all the data is stored in **memory**, and after the program stops, all the data will be deleted. So yes, this is expected.

This method is usually used in **educational articles** or **during development**. (Because it's easy)
**Data Seeding** is also used to prevent data deletion.

There are better methods in the industry that I suggest you read about databases and their types.

**Comment by ctreslovehayes** [comment]
So what type would you recommend for this? The other Tutorial I found using DBs is completely different from this. I coded this all around JSON like the tutorial and now I cannot save it. Any suggestions?

**Comment by HamidMolareza** [comment]
@ctreslovehayes, Databases are very diverse and designed for **different needs**. That's why it's not easy to make a suggestion. Be sure to read at least about them. (SQL types and NOSQL types)

Suggestion to start:
Follow this tutorial: [Create a web app with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/?view=aspnetcore-3.1). **Specially** follow [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.1&tabs=visual-studio-code) and [Work with SQL in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-3.1&tabs=visual-studio).

In this tutorial you will learn how to use **SQL Server** and SQLite.

After reading that article, you will learn how to use SQL Server in this project.
For more guidance, more information is needed.
