### ISSUE TITLE
Update document regarding the accumulation of Transient services

### ISSUE THREAD

**Issue by akovac35** [dotnet/AspNetCore.Docs#17766]
Using transient services my cause memory leaks: https://github.com/dotnet/extensions/issues/1785

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @akovac35.

We might be able to base the updates directly on @brandondahler's *Situations and Solutions* and *General Guidelines* (and, of course, @brandondahler, is welcome to submit a PR) for the [Fundamenals DI topic](https://docs.microsoft.com/aspnet/core/fundamentals/dependency-injection).

For Blazor, the relevant sections are ...

   * [Utility base component classes to manage a DI scope](https://docs.microsoft.com/aspnet/core/blazor/dependency-injection#utility-base-component-classes-to-manage-a-di-scope)
   * [Use of Entity Framework DbContext from DI](https://docs.microsoft.com/aspnet/core/blazor/dependency-injection#use-of-entity-framework-dbcontext-from-di)

@mjrousos, I can *probably* perform the updates, but updates will be faster and require less engineering support if you or one of the framework jockeys makes them.

![mccoy](https://user-images.githubusercontent.com/1622880/79122812-4c605180-7d5e-11ea-9af1-7a59ebcd7daa.png)
 
**_Damn it Mike! ... I'm an LOB dev! ... Not a framework designer!_** :smile:

**Comment by mjrousos** [comment]
@guardrex, I don't think I'll get a chance this week, but I've added this to my todo list to take a look at if you don't get to it first.

**Comment by guardrex** [comment]
Thanks, I'll assign myself for now.

**Comment by akovac35** [comment]
Hi Team - regarding my remark, I would like to point out that users really don't expect the described behavior from the DI framework. It might be better to just introduce a braking change and make it perform as expected instead of documenting it - this is something EF Core team is doing regularly and it shows because the framework is getting better and better. Otherwise, how exactly are you planning to document this? Don't use transients in case of ... ? It just doesn't seem right :)

**Comment by guardrex** [comment]
A factory pattern was mentioned that might be a good approach to show. For Blazor, such a factory might be something to further what we discuss/show for the 2nd bullet (the *Register the DbContext in the service container with a transient lifetime* content) at [Use of Entity Framework DbContext from DI](https://docs.microsoft.com/aspnet/core/blazor/dependency-injection#use-of-entity-framework-dbcontext-from-di).

For content, it would be more efficient for me to *receive* text, notes, and/or a PR on what/where would be best to say. It would be easy/fast for me to polish it up for publication. Alternatively, I'll do what I normally do in these cases ... study it further and *hack up a draft* 🙈😄.

> introduce a braking change and make it perform as expected instead of documenting it

I didn't get the impression from the discussion that that's even a consideration at this point. They seem to be saying that the soonest for anything coming out would be 5.0.

The soonest that I'll be able to reach this issue is perhaps .... errrrr 🤔 ... maybe a week or two ... which probably means *three weeks* 🏃😅 ... or **_SIX weeks_**. lol ... Honestly, I'm not sure. *There's a lot of work to do!* I'm working Blazor security issues right now, some of which are for WebAssembly's release in May. If anyone wants to float a PR ... or even just notes ... for example, knock us up an example of the aforementioned *factory pattern* ... that would be great.

**Comment by guardrex** [comment]
btw ---- To surface this issue both for the *Fundamentals* DI topic **_AND_** the Blazor DI topic, I'm going to open a sister issue on that topic, which will cross-link the engineering discussion and this issue. It won't be an issue that gets worked. This issue will be the main issue. The sister issue will be seen by devs looking at the Blazor DI topic to surface this.
