### ISSUE TITLE
Blazor WebAssembly App template missing

### ISSUE THREAD

**Issue by matthewphilipdixon** [dotnet/AspNetCore.Docs#17762]
Installed VS 2019 Preview 16.6.0 Preview 2.1, followed the instructions above.  However, at step #5 I cannot proceed because the Blazor WebAssembly App option does not exist.  I tried to follow the instructions here:
https://stackoverflow.com/questions/59272624/missing-visual-studio-2019-blazor-webassembly-app-template
Which pointed me here:
https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor.Templates
Which showed that it was deprecated, and led me here:
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/
Which finally did work.  
I think this could be added to the VS 2019 preview by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It was added. I don't have any information on the current guidance not working for 16.6 Preview 2. Sometimes, devs have had to reinstall the template to get it to appear. Sometimes, upgrading VS exhibits the same behavior and requires a template re-install, and I've sporadically experienced a required re-install myself. Release 3.2 is due to come out in May. After release, Blazor WebAssembly will be supported across-the-board and no separate template install command will be required. I believe that issues pertaining to template install and availability will go away completely at that point.
