### ISSUE TITLE
Install the .NET Core Hosting Bundle Link Not Working

### ISSUE THREAD

**Issue by willydavidjr** [dotnet/AspNetCore.Docs#17872]
When I visited this site for the first time, I selected my version ASP.NET Core 2.1 on the options at the left hand side. Then when I click the link: Install the .NET Core Hosting Bundle, nothing happens? So what is the link or is this the same link with ASP.NET Core 3.1 version since when ASP.NET Core 3.1 version is selected, the link is working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1#install-the-net-core-hosting-bundle)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @willydavidjr ... Good point. Both versions of the doc use the same "permalink," and they both download the latest version of the Hosting Bundle ...

https://dotnet.microsoft.com/permalink/dotnetcore-current-windows-runtime-bundle-installer

Since (IIRC) the 3.x runtime isn't backwards compat for 2.x, that's not a *good cross-link user experience*. However, we don't really want to use ...

https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-aspnetcore-2.2.8-windows-hosting-bundle-installer

... because the team will rev the version of 2.x and then the link will become stale. They might release a 2.2.9 version.

Let's go with ...

https://dotnet.microsoft.com/download/dotnet-core

... and text that says download the Hosting Bundle for the version of .NET Core in use. I'll put up a PR for something along those lines.

You can get the exact 2.1 installer here ...

https://dotnet.microsoft.com/download/dotnet-core/2.1

In the right column, you'll see the link there for "Hosting Bundle, and it goes to ...

https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-aspnetcore-2.1.17-windows-hosting-bundle-installer

Leave this issue open. It will automatically close when the PR merges. Thanks for writing in on this.

**Comment by guardrex** [comment]
Actually, good news. There's already an "earlier version" section. I need to fix the text tho just a hair.

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1#earlier-versions-of-the-installer-2

**Comment by willydavidjr** [comment]
> Actually, good news. There's already an "earlier version" section. I need to fix the text tho just a hair.
> 
> https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1#earlier-versions-of-the-installer-2

Thanks for the assistance. I was able to download it now. :thumbsup:
