### ISSUE TITLE
3.1 update of Safe storage of app secrets i

### ISSUE THREAD

**Issue by lertoo** [dotnet/AspNetCore.Docs#17892]
When CreateDefaultBuilder isn't called, add the user secrets configuration source explicitly by calling AddUserSecrets in the Startup constructor.

The constructor is:
public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

where this is from:
public Startup(IWebHostEnvironment env){...}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
See [Access a secret](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=windows#access-a-secret) where 2.1 code is used.

**Comment by Rick-Anderson** [comment]
cc @serpent5

**Comment by serpent5** [comment]
I don't think that's 2.1 code. The `Startup` class creates its own `IConfiguration` because the one available through DI will, by default, only include the _host_ configuration, and not all the other providers added by `CreateDefaultBuilder`.

I think the sample and explanation is valid as is, even for 3.x. However, in my opinion, it would be better to add the configuration inside of `Program`, using `ConfigureAppConfiguration`. e.g.:

```csharp
public static void Main()
{
    var hostBuilder = new HostBuilder()
        .ConfigureAppConfiguration((context, builder) =>
        {
            // Add other providers for JSON, etc.

            if (context.HostingEnvironment.IsDevelopment())
            {
                // builder.AddUserSecrets<Program>();
            }
        })
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });

    hostBuilder.Build().Run();
}
```

That's a basic `Host` setup, that doesn't include logging, etc, but it demonstrates the point. But, as I said, it's only my opinion that this is where it should be done. I think the existing sample code in the topic is valid.

**Comment by Rick-Anderson** [comment]
@serpent5  great idea.

**Comment by serpent5** [comment]
@Rick-Anderson Could you fix up the monikers in this file? I count 20. I would do it myself but I don't have a way to validate them. There's no rush, but it'd make it easier to use the snippet above for 3.x only.

**Comment by Rick-Anderson** [comment]
@serpent5 if I don't fix it in the next 2 days, send me a reminder.
