### ISSUE TITLE
Microsoft.AspNetCore.SpaServices.Extensions Docementation

### ISSUE THREAD

**Issue by IamDZN** [dotnet/AspNetCore.Docs#17902]
Where is the documentation for "Microsoft.AspNetCore.SpaServices.Extensions" package?

I am getting below warning when using "Microsoft.AspNetCore.SpaServices" with a Vue based .NET Core applciation. It seems like these packages were made obsolete with "Microsoft.AspNetCore.SpaServices.Extensions" package but there are no documentation about this package. 

warning CS0618: 'PrerenderTagHelper' is obsolete: 'Use Microsoft.AspNetCore.SpaServices.Extensions'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c771657b-a681-8e8a-52ed-3d974520f528
* Version Independent ID: 318e32fc-62f2-c0e5-4658-5729aad48c91
* Content: [Use JavaScript Services to Create Single Page Applications in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/client-side/spa-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @IamDZN ...

Mentioned in the [2.2 to 3.0 migration topic](https://docs.microsoft.com/aspnet/core/migration/22-to-30#add-package-references-for-removed-assemblies) under **SPA Services**. It links to the NuGet package at ...

https://www.nuget.org/packages/Microsoft.AspNetCore.SpaServices.Extensions

Also linked in the [Use JavaScript Services to Create Single Page Applications in ASP.NET Core]() topic. The WARNING says ...

> The features described in this article are obsolete as of ASP.NET Core 3.0. A simpler SPA frameworks integration mechanism is available in the Microsoft.AspNetCore.SpaServices.Extensions NuGet package. For more information, see [Announcement] Obsoleting Microsoft.AspNetCore.SpaServices and Microsoft.AspNetCore.NodeServices.

Where it links to the NuGet package again and an Announcement, which explains more about what's going on with it.

https://github.com/dotnet/AspNetCore/issues/12890

Since it's called out and cross-linked, I'll go ahead and close, but Scott will see this and re-open it if it requires more work later. He's OOF for the moment but will see this when he returns.

**Comment by jrummell** [comment]
Those links only talk about why the new package was created and why the old one is deprecated, there's no documentation on how to actually use `Microsoft.AspNetCore.SpaServices.Extensions` (that I can find). Examples would be great as well. I only got it working after spending a few hours in object explorer looking for method names similar to the ones in `Microsoft.AspNetCore.SpaServices`.

**Comment by IamDZN** [comment]
> Those links only talk about why the new package was created and why the old one is deprecated, there's no documentation on how to actually use `Microsoft.AspNetCore.SpaServices.Extensions` (that I can find). Examples would be great as well. I only got it working after spending a few hours in object explorer looking for method names similar to the ones in `Microsoft.AspNetCore.SpaServices`.
> 
> I would love to see the existing doc (https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-3.0#what-is-spaservices) updated for `Microsoft.AspNetCore.SpaServices.Extensions`, instead of just saying "hey, this is deprecated, here's the new undocumented nuget package".

This is exactly what I was talking about. It would be nice to see the documentation get updated with examples.

**Comment by eparizzi** [comment]
Deprecating a package, providing a new one without any documentation? 3.1 it's been LTS for a while now. Please provide documentation on how to use this because I could only make it work with the default create-react-app that comes in the template. I want to use my own react app (not cra-based) but I can't get it to work. It fails to proxy to the react app. There's no documentation on how to specify the port of the client app.

**Comment by MaximDelyukin** [comment]
Any news on where is the documentation?

**Comment by shawty** [comment]
Another call for doc's please folks.  I'm trying to upgrade some Aurelia apps done under core 2.1.

**Comment by guardrex** [comment]
This issue is closed, so let's lock this one out in favor of the newer issue at https://github.com/dotnet/AspNetCore.Docs/issues/18405.
