### ISSUE TITLE
change component name

### ISSUE THREAD

**Issue by behroozbc** [dotnet/AspNetCore.Docs#17992]
hi 
how i can change component name ??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#use-components)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @behroozbc ... The name of the file is the name of the component. Change the file name. When I edit these documents within the next month or two, I'll be added more examples of this. For example, the text today might say something like ...

> Use the `XYZ` component to do X, Y, or Z.

In the future, many of these references will be updated to say ...

> Use the `XYZ` component (*Pages/XYZ.razor*) to do X, Y, or Z.

... or if in the *Shared* folder ...

> Use the `XYZ` component (*Shared/XYZ.razor*) to do X, Y, or Z.

There isn't an issue yet for the updates because we're still working hard on basic feature coverage, but I anticipate opening such an issue after 3.2 releases in May.
