### ISSUE TITLE
ASPNETCORE_ENVIRONMENT not used after 3.1 upgrade

### ISSUE THREAD

**Issue by danobri** [dotnet/AspNetCore.Docs#18002]
I am in the process of upgrading an application from ASP.NET Core 2.1 to 3.1, and when I deploy to our test server, the application is no longer reading from the ASPNETCORE_ENVIRONMENT variable.  The variable is set to "TEST" on the server, but the application is running with development settings.  I updated the Program.cs to use ConfigureWebHostDefaults as indicated in this article, but that does not make no difference.  Is there some other reason the application would not using the ASPNETCORE_ENVIRONMENT variable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by danobri** [comment]
I was only able to get it the application working after adding <EnvironmentName>Test</EnvironmentName> to the .pubxml, but it's not clear to me why that is necessary  in 3.1 when it was not in earlier versions.  The documentation above says this puts the environment name in the web.config.  Should this be necessary?  Shouldn't the application  be able to read the value from the global environment variable on the server?

**Comment by danobri** [comment]
&lt;EnvironmentName&gt;Test &lt;/EnvironmentName&gt;

**Comment by Rick-Anderson** [comment]
See this in the doc
The About page from the sample code includes the preceding markup and displays the value of IWebHostEnvironment.EnvironmentName.

**Comment by danobri** [comment]
So do I understand correctly that ASP.NET no longer uses environment variables for web applications hosted in IIS?  It uses the web.config instead?  Any perspective on why this was changed in ASP.NET Core 3?

**Comment by Rick-Anderson** [comment]
> So do I understand correctly that ASP.NET no longer uses environment variables for web applications hosted in IIS? It uses the web.config instead?

Why do you say that?

The doc suggests exactly what you did.

**Comment by danobri** [comment]
What I did is set the environment via the web.config as a work around because the application is not reading the value from the system defined ASPNETCORE_ENVIRONMENT variable from the server as expected.  My question is, why doesn't the application use the system variable anymore?  A web config setting can be changed by any developer with access to the code, whereas an environment variable can only be set by a server admin.

**Comment by Rick-Anderson** [comment]
If `ASPNETCORE_ENVIRONMENT` is not set, it defaults to `Production`.

> the application is not reading the value from the system defined ASPNETCORE_ENVIRONMENT variable from the server

How did you determine that?

**Comment by danobri** [comment]
The ASPNETCORE_ENVIRONMENT system variable on this server is set to "Test", but the application is using Development settings (unless I set the EnvironmentName config setting).  Not sure why it's using Development settings if the default is production though.  As I mentioned - this is an existing application using it's existing test server and the issue started after upgrading from 2.1 to 3.1.

**Comment by Rick-Anderson** [comment]
You need to read and understand this doc. You should try to reproduce the problem with a new app to help you figure out the bug(s) in your code.

**Comment by danobri** [comment]
I have read the document more than once and am posting a question because what I experienced in my own application / environment was not consistent with what the document indicated, so I was trying to get clarification that I understood correctly.  If you had answered my original question by saying - "No, you should not have to set the environment via the web.config, there must be something else going on." - then I would have found the issue more quickly and not wasted more of your time with additional posts.

At this point I've found the issue, but am not sure how to prevent it.  It appears that since I upgraded to 3.1, environment variables are getting added to the web.config every time I run the application locally to debug.  So my web.config has the ASPNETCORE_ENVIRONMENT set to Development, and if I remove it, the setting just gets re-added the next time I run locally.  Any idea why this happening, and how I can prevent the behavior?  

Here is my web.config before the upgrade:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="true" startupTimeLimit="3600" requestTimeout="00:05:00">
      <environmentVariables />
    </aspNetCore>
  </system.webServer>
</configuration>
```
And here it is after the upgrade, and after running locally:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="true" startupTimeLimit="3600" requestTimeout="00:05:00" hostingModel="InProcess">
      <environmentVariables>
        <environmentVariable name="ASPNETCORE_HTTPS_PORT" value="44311" />
        <environmentVariable name="COMPLUS_ForceENC" value="1" />
        <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
      </environmentVariables>
    </aspNetCore>
  </system.webServer>
</configuration>
 ```
You can reproduce this behavior if you create a brand new 3.1 Razor Pages Project in VS, and add a web.config with these contents (minus the environment variables section).  When you run the application the environment variables section will get added.  This did not happen in 2.1, why is it happening in 3.1, and how can I prevent it?

**Comment by danobri** [comment]
It appears this is issue is already being tracked [here](https://github.com/aspnet/websdk/issues/564#issuecomment-592760255) and a fix is planned for VS 2019 16.6.

Please update this documentation to call out the issue, or perhaps add it to the existing warning [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#setting-environment-variables).  It sounds like quite a few users have inadvertently overwritten production environment settings due to this issue.

**Comment by danobri** [comment]
Sorry - that second link should be [this](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.0#set-environment-variables).

**Comment by Rick-Anderson** [comment]
Open an issues for [Configuration with web.config](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#configuration-with-webconfig) 
cc @guardrex

**Comment by guardrex** [comment]
@danobri ... I take it that when you say ...

> are getting added to the web.config every time I run the application locally to debug

... you're debugging via IIS locally and don't want to use the app's non-IIS, Kestrel-based debugging profile. Debugging with IIS locally is a pattern that devs use, of course, but many just run the app on Kestrel and don't debug with IIS/*web.config*; therefore, that's one way to avoid it.

I wasn't aware that recently VS started doing something on its own with *web.config* that you couldn't easily stop. One can prevent the SDK from messing with the *web.config* with your own *web.config* sitting in the project folder and then publishing with ...

```dotnetcli
dotnet publish /p:IsWebConfigTransformDisabled=true
```

https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/transform-webconfig#prevent-webconfig-transformation

... **_or even simpler_**, add the [](https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/#webconfig-file) property to the project file ...

```xml
<PropertyGroup>
  <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
</PropertyGroup>
```

https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/#webconfig-file

It sounds like you tried these approaches and VS isn't respecting them ... only the SDK is respecting them.

The other angles to at least temporarily solve this are to either (and these are probably on that issue you linked, I didn't look at the full discussion) ...

* [Transform the web.config](https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/transform-webconfig) might work after VS messes with it.
* Don't deploy the *web.config* at all from the project to the server. Remove it post-publish from the *publish* folder. Leave your good working copy on the server and don't overwrite the full app on deployment. You can try this and see if it ✨ **_Just Works!_**:tm: ✨ ...

  ```xml
  <Target Name="RemoveWebConfigFromDeployment" AfterTargets="AfterPublish">
    <Delete Files="$(PublishDir)\web.config" />
    <Delete Files="$(PublishUrl)\web.config" />
  </Target>
  ```

  When you go to test that, delete your *bin* folder first to make sure it doesn't leave a prior copy of the file sitting there. When you publish, it **_should_** 🤞 be *Hasta la vista, amigo!*

   ... and use both `Delete`s there because IIRC the `PublishDir` path takes care of the CLI case and the `PublishUrl` path takes care of the VS case.

**Comment by danobri** [comment]
Thanks for the additional suggestions - I'll probably just stick with setting the EnvironmentName in the pubxml as a workaround until the VS update is released. 

So will someone update the documentation on ASP.NET Core environment variables to call out this pending issue?  It seems like a fairly nasty issue since it can result in a dev unknowingly turning their production environment into a dev environment.

**Comment by guardrex** [comment]
It's *almost* documented ... in the sense that it isn't cross-linked properly.

https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module#set-environment-variables

... doesn't cross-link to ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/visual-studio-publish-profiles#set-the-environment

The happy path is if the dev knows they should read the publish profiles doc ... they have to :eyes: see it there and know they should read it. It's not going to be clear to many/most that that's the case.

@Rick-Anderson, do you want me to do a little something with this? I think a couple of cross-links and perhaps a sentence or two will clear it up in a stable way that the team won't have to revert later. Since the docs don't say anything about the SDK/VS modifying the file outside of the default to `Production` on publish, I don't think that engineering's fix will result in any change to the doc set later.
