### ISSUE TITLE
WASM AddOidcAuthentication is defaulting to OIDC v1

### ISSUE THREAD

**Issue by TaylorWatson** [dotnet/AspNetCore.Docs#18045]
Is there a way to tell it to choose v2?

builder.Services.AddOidcAuthentication(options =&gt;
            {
                // Configure your authentication provider options here.
                // For more information, see https://aka.ms/blazor-standalone-auth
                builder.Configuration.Bind("Local", options.ProviderOptions);
            });

defaults to openid-connect.{PROVIDER}.com/oidc ...

I'm not entirely sure why it would default to that when most identity providers support v2. Is there a way to have to default to
{DOMAIN}.{PROVIDER}.com/oidc/2 ???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55d96ce7-2ead-ebc2-973e-e319082937b0
* Version Independent ID: 44ee9a17-4e34-6463-66e8-f1eb212845a4
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @TaylorWatson ... Yes, there is. The issue is a dup of https://github.com/dotnet/AspNetCore.Docs/issues/17578, which says "B2C," but I'm really working Blazor Server guidance generally on that issue. I'm working on the issue right now, so I hope to have a PR up within a day or two. For right now, see the notes at ...

https://gist.github.com/javiercn/62044bab948e42cc9e4e695e4aaee7b8#updating-your-application-to-use-v20-endpoints

... elements of that will likely make their way into the Blazor Server security topic on this upcoming round of updates.

> I'm not entirely sure why it would default to that when most identity providers support v2

I believe it's a current default, so it should go v2 at some point. I don't have an ETA on that right now, but I'm looking into exactly that type of thing for the next round of Blazor Server topic updates.

**Comment by guardrex** [comment]
Actually, I'm going to focus those updates on Blazor Server, not WASM. I'll perform a similar update for WASM topics, and I'll use this issue to track it.

**Comment by CodedByDesign** [comment]
Thanks for getting back to me :)

I tried implementing the += "/v2.0" however not all IDP's use that numbering format so I'm out of luck as there seems to be no way to customize that. I do thank you for the prompt reply however as it stands. I think a lot of us will have to wait until until we can adjust the numbering scheme.

**Comment by guardrex** [comment]
You can set the `Authority` to whatever you want. That's just the easy way for to tack the v2 version segment on to what configuration provides. For example in the Blazor Server case with AAD it just goes from ...

> https://login.microsoftonline.com/{CLIENT_ID}

... to ...

> https://login.microsoftonline.com/{CLIENT_ID}/v2.0

... but you can set `options.Authority` to anything you want in code or set it via configuration.
