### ISSUE TITLE
[Blazor][Wasm] Document httpclientfactory patterns

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#18042]
The recommendation here is to use different clients if you have authenticated and unauthenticated endpoints. In general, different httpclient instances for endpoints with different security characteristics.

**Comment by guardrex** [comment]
Ah ... didn't see this when I worked it from another issue. This issue was resolved by https://github.com/dotnet/AspNetCore.Docs/pull/18240, which provides the coverage at ...

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#unauthenticated-or-unauthorized-web-api-requests-in-an-app-with-a-secure-default-client
