### ISSUE TITLE
Update VS for Mac Steps

### ISSUE THREAD

**Issue by leahtmsft** [dotnet/AspNetCore.Docs#18097]
@danroth27
Through some user testing videos, we noticed some inconsistencies VS for Mac steps that should be made it clearer. 
- Step 2 is listed as 'New' instead of 'New Project' in the first window. 
- Step 4 should say 'Select Next' instead of 'Select Create'.
- The steps do not mention anything about VS asking for authentication, so we should add a step directing the user to select the correct option and continue.
- Nothing prompts the user to confirm a Target Framework in Step 5, so it should be removed. 
- Step 7 should say 'Select Run &gt; Start Without Debugging'.
I do not have a Mac to check these myself so it would be helpful if someone could do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio-mac#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I just walked these with Preview 4, but I'll walk them again and see what's what.

**Comment by guardrex** [comment]
@leahtmsft ... You were using Preview 4, right? ... or I mean the video was, right? If they're using an earlier preview release, all bets will be off. :smile: lol

**Comment by danroth27** [comment]
@guardrex The users were just following the steps listed in the Blazor getting started page, which just says to install VS4Mac. It doesn't say to install a VS4Mac preview.

**Comment by guardrex** [comment]
Yes, we used to say that and dropped the language at some point, probably because we angled devs away from WASM ...

https://github.com/dotnet/AspNetCore.Docs/pull/12061/files#diff-aad9be3b2ba853ffc4d9ec1bb908d272R76

> 1. Install [Visual Studio for Mac](https://visualstudio.microsoft.com/vs/mac/). Switch the [Update channel to Preview](/visualstudio/mac/install-preview).

I suppose we need to go Preview channel until 8.6, then drop in favor of the release version?

**Comment by danroth27** [comment]
> I suppose we need to go Preview channel until 8.6, then drop in favor of the release version?

Only for Blazor WebAssembly. Blazor Server is supported with the stable release of VS4Mac.

**Comment by guardrex** [comment]
Ok :+1: ... I'll knock this one out and take it live by EOD.

**Comment by guardrex** [comment]
I'm going to need to table this overnight until Saturday morning. My ancient iMac is on the Preview channel. When I drop it off of Preview, it's going to re-install the entire app. As slow as my iMac is, it will literally take an hour or more just to get off of the Preview channel. I've been up since 5am, so I have to go to bed 🛌💤😴 soon. I'll square this away first thing in the morning.
