### ISSUE TITLE
routing guards/filters

### ISSUE THREAD

**Issue by hoksource** [dotnet/AspNetCore.Docs#18110]
Any future plans on implementing route guards/route filters for @page components something similar to 

@attribute [Authorize]
or
https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1
or
https://angular.io/guide/router#milestone-5-route-guards

just to control user from navigating. looks like the best way right now is create a base class which implements the initialize or on navigate to check if user has authorization/access to specified page then redirect or display error.

It would be cool to have something like
from the authorize attribute
@attribute [MyCustomPageComponentAuthorize]
then redirect or trigger an error response. Also please do document how to implement multiple custom attributes, is this possible?
@attribute [MyFilter, MyFilter2]

the above features are corollary to my previous question
https://github.com/dotnet/AspNetCore.Docs/issues/16111

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79da574a-570f-04eb-86bd-c8065a016f44
* Version Independent ID: ac771374-6102-b838-57d2-e99bcf3f7d3e
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-gb/aspnet/core/blazor/routing?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Sorry about that @hoksource ... we didn't actually address your ask on #16111.

Yes, the `[Authorize]` attribute is covered in the Blazor security *Overview* ...

https://docs.microsoft.com/aspnet/core/security/blazor/

The approach for controlling the content that's served to a non-authorized user is to merely customize the content of the `AuthorizeRouteView` component ...

https://docs.microsoft.com/aspnet/core/security/blazor/#customize-unauthorized-content-with-the-router-component

... and that's obviously not very fine-grained to just place text/markup there. However, you could further tailor that by sticking your own component(s) in there that contain special content and logic.

WRT to further routing options or features that they're working on, I'll leave this up for triage for Artak to take a look at. These issues are usually looked at on Fridays.

**Comment by guardrex** [comment]
... and one more tidbit WRT to general doc improvements. We've been so busy getting basic features covered on high priority issues, that a *BIG* sweep on topics for improved guidance is needed. There should be a quiet period right after 3.2 lands in May. The entire Blazor doc set will receive attention during that time. For example, your issue here implies that better cross-linking between the *Routing* and *Security* topics is called for. Those types up updates will occur with the UE work shortly.

Artak, unless you have something specific to call out, I recommend that we close this. Soon, I'll set up a tracking issue for discussion prior to the UE sweep, and **_better cross-linking_** will be a bullet point on that task list for UE improvements.

**Comment by hoksource** [comment]
the exact problem i'm trying to solve is:

a page/X created by user A.
if user B tries to access page/X,
then a filter/event/guard should check the database if B has access to page/X.
If not force a NotFound response. then it will trigger the router results <NotFound>
or redirect to another page etc.

Im not sure if you can solve this with component life cycle OnInitialize or is there a BeforeInitialize event?

**Comment by guardrex** [comment]
Hasn't this been asked and answered? ...

https://github.com/dotnet/aspnetcore/issues/18425

**Comment by guardrex** [comment]
... try it the way that Javier suggested. Create your own `MyCustomWrappingComponent` to use based on `AuthorizeRouteView`, which you can find in the ref source. Customize it however you like.

**Comment by guardrex** [comment]
https://github.com/dotnet/aspnetcore/blob/master/src/Components/Authorization/src/AuthorizeRouteView.cs

**Comment by guardrex** [comment]
Artak, perhaps we should say in passing (one line quick remark) that readers can provide their own custom `AuthorizeRouteView` component with custom logic. I don't intend to link to the component ref source 🙈, but we can say that the `AuthorizeRouteView` component can be found in ref source and link to the engineering repo. They only need to search for it at that point.

**Comment by hoksource** [comment]
My questions are more of feature requests, Javier suggestion would involve the page does not exists. and strongly integrated with identity framework

my current problem is blogger A created a post with id 1 '/edit/1'. Since @page "/edit/{postid?}" should be restricted to the creator. from the implementation of policy based authentication.

https://docs.microsoft.com/en-gb/aspnet/core/security/authorization/policies?view=aspnetcore-3.1

the IAuthorizationHandler does not seem to have access to request context nor request parameters.
So if so there should be a way to force the page to redirect to NotFound or return a NotFound result. when blogger B accessed 'edit/1'.

**Comment by guardrex** [comment]
His suggestion applies to every user component navigation, not just a missing page request ... you can do anything you want with that approach, including any kind of authn/z logic.

Feature requests have to go to the product unit, so you'd need to open an issue there ...

https://github.com/dotnet/aspnetcore/issues

... but I don't recommend it because I think Javier is going to give you the same answer.

Your request for coverage on custom code is outside of the current doc scope. We recommend chatting with devs on the usual support channels for things like this.

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter: Blazor](https://gitter.im/aspnet/Blazor)

Leave this open tho because it might be a good idea to call out the idea of a custom `AuthorizeRouteView` component to surface it to readers. After that tho, it's up the dev to build it on their own.

**Comment by hoksource** [comment]
I can't seem to fit the case. example:
```

<Router AppAssembly="@typeof(Program).Assembly">
    <Found Context="routeData">
        <MyCustomWrappingComponent RouteData="@routeData">
            <AuthorizeView>
                <Authorized>
                    @if(CanEditBlogPost(context.User.Identity.Name, routeData["id"]) {
                           
                    <MyCustomRedirectComponent />
                    } else {
                     <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
                    }
                </Authorized>
                <NotAuthorized>
                    <MyCustomRedirectComponent />
                </NotAuthorized>
            </AuthorizeView>
        </MyCustomWrappingComponent>
    </Found>
</Router>
```


where <MyCustomRedirectComponent>
`
    protected override void OnInitialized()
    {
        NavigationManager.NavigateTo("MyNotFoundPage");
    }

`

is the above practive good? calling NavigationManager.NavigateTo when OnInitialized is called?
because it might have loaded some of the data before redirecting. I'm not really sure. That is why i need a onbeforeinitialized or a filter attribute that calls navigateto before data is loaded.

**Comment by hoksource** [comment]
Also users can just type 'mywebsite.com/edit/1' if the user is logged in then the client should do an ajax request for the data. if the data is not found, the user is redirected to MyNotFoundPage.

im not really sure how this is implemented with the blazor framework.
- from razor pages you can create non-auth filters.
- from angular they have client side guards, loads the data then checks the data, if so they can redirect or display an error message.

**Comment by guardrex** [comment]
That's not anything like what the recommended approach would be via just using the provided options laid out in the Blazor Security topic. That's all done for you using the built-in bits. You would just establish a role claim and set up a policy and then check the policy with the `[Authorize]` attribute as the topic shows.

You'll have to inquire further on a support channel. I'm up to my 👂👂 in work 🏃😅. We just don't have the staffing to provide product support. Try those support channels that I listed.

**Comment by guardrex** [comment]
When I get to a doc sweep right after 3.2 releases, I'll have more time to assess the overall presentation of concepts, and I hope to work further clarifications and examples into the topics, including perhaps a security sample app. Right now tho, I recommend sticking with the approaches in the topics ... authenticate the user, they have a role claim (or a few if needed), the components use policies and procedural logic to check their role claim(s) to permit certain actions. In Blazor WASM, checks need to be made client and server-side because anything client-side in a WASM app can be hacked.

**Comment by hoksource** [comment]
problem with role claim is that the IAuthorizationHandler does not have access to the route parameters id=1 from /edit/1. So i can't check if the user is the owner of post 1.


from 
https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1
and 
https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Components/HTTPRequestTester.razor


Since authentication can't access route parameters, and non-auth filters are not supported, will below be a good alternative practice?



1. create a base class BlogPostBase with ajax inside oninitializedasync 
2. redirecting when error is received.
3. all page that follows the the same authorization, lets say /edit/1 or /review/1 or /publish/1 should inherit by @inherit BlogPostBase


BlogPostBase.cs
```

public class BlogPostBase : ComponentBase {

   ...
protected override async Task OnInitializedAsync() {
    try{

        var res = CallHttpRequest("CheckUserAccessTo/GetPostContent", request["postId"]);
        //api should never return the content if not authorized to view
        ....
    }catch(Exception ex) // returned 401 or error
    {
        NavigationManager.NavigateTo("MyErrorPage");
    }

}


}
```

Edit.razor
```

@page "/edit/{id}"
@inherit PostBase

....
```



Publish.razor
```

@page "/publish/{id}"
@inherit PostBase

....
```


will the above alternative be a good practice? im not sure.

**Comment by guardrex** [comment]
I'm going to close this because it was asked and answered by engineering and is a general support request. We don't have the staffing to provide general support. Converse with the community further based on Javier's response in the engineering issue ...

* [Stack Overflow](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Blazor)
