### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by carlblanchard** [dotnet/AspNetCore.Docs#18123]
How would you go about retrieving the {OAUTH TOKEN} in Blazor WebAssembly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5e2e10-ff7b-2b9f-84da-f16028ae2c53
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Call a web API from ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @carlblanchard ... Are you just asking about a missing cross-link to the security topics? I'm aware of the need for better cross-linking, and I'm working rapidly to improve that across the Blazor docs.

If you literally mean that you don't know where the content is, check out the articles in the Blazor Security node, starting with ...

https://docs.microsoft.com/aspnet/core/security/blazor/webassembly/

I'm going to close this given that I'll be opening a UE ("User Experience") general issue to track broad updates later to include cross-linking work.

If you run into an issue with one of the security topics in that node, you can open a new issue from the bottom of a topic there.

**Comment by carlblanchard** [comment]
No Sorry. I meant, in the example above you have this 
requestMessage.Headers.Authorization = 
           new AuthenticationHeaderValue("Bearer", "{OAUTH TOKEN}");

It would be great if you could show the example code to obtain the {OAUTH TOKEN} in Blazor client.

**Comment by guardrex** [comment]
Ah ... I see what you mean now. This particular section is fine because it's a low-level approach that provides a high degree of customization opportunities. The more automatic approaches are over in the new *Additional scenarios* topic ...

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios

... especially the 2nd section *Attach tokens to outgoing requests*. I need to resolve the problem here by calling it out explicitly and possibly moving the section that you're asking about here over to the *Additional scenarios* topic. I'll take a closer look and see what we need to do.

Thanks for calling it out. I'll get this addressed quickly.

**Comment by guardrex** [comment]
I found out as I was updating this section (and moving this section to the *Additional scenarios* topic) that a few spots were missed on obtaining a token manually with `IAccessTokenProvider.RequestAccessToken` on the Preview 5 release. I'm making the updates now.
