### ISSUE TITLE
currentCount Styling

### ISSUE THREAD

**Issue by leahtmsft** [dotnet/AspNetCore.Docs#18148]
@danroth27 and I noticed that the templates in Visual Studio now show this field as 'currentCount' instead of '_currentCount', so we should update the code on this page to match.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I wish it were the other way around ...

https://github.com/dotnet/aspnetcore/pull/18446

... and we perhaps threw the 👶 out with the bathwater on that one because I think it was only closed over the use of `this`. The rest of the updates there may have been ok and would've resolved the inconsistency.
