### ISSUE TITLE
Having two `Tutorials` is confusing

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#18171]
I just noticed the existence of two `Tutorials` sections [in the docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-3.1):
![image](https://user-images.githubusercontent.com/34246760/81249760-47e12e80-8fd4-11ea-85eb-80208a30d7f8.png)

It's really confusing and reading `Tutorials (Microsoft Learn)` tells me nothing.
Instead, I suggest reworking this as follows:

- Tutorials
  - Web apps
  - Web API apps
  - Real-time web apps
  - Remote Procedure Call apps
  - Data access
  - Microsoft Learn articles
    - Web apps
    - Web API apps
    - Data access
    - Web app security

**Comment by Rick-Anderson** [comment]
I agree that would be a nice improvement but @scottaddie  owns this and their may be higher level rules on the TOC.

**Comment by scottaddie** [comment]
@mkArtakMSFT I agree that we can do better to differentiate between the two types of tutorials. How about using the text **Microsoft Learn modules** instead of **Microsoft Learn articles**? I think the term *articles* sells them short, especially since they all offer interactivity via the Azure Cloud Shell.
