### ISSUE TITLE
/connect/authorize route not recognized

### ISSUE THREAD

**Issue by parejajd** [dotnet/AspNetCore.Docs#18209]
Hi,

I implement this guide in a Blazor WebAssembly Hosting App with Identity Server.

In development environment this work perfectly, but in production a i am getting an error.

1. Access to Home Page 
2. Access to /authenticacion/login 
3. This component redirect to /connect/authorize/ 

In this moment i am geting "Sorry, there is nothing at this address" .

I already clean cookies, app data, local storage, use private browsing.

¿any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17515ff7-32a6-c6f7-0425-535775cd6e28
* Version Independent ID: 1416abd7-0b23-ca93-62e7-59d2532d4275
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @parejajd ... Working on this topic with Identity Server was my first experience ever working with it, so I'm not the best person to ask. Do either of the following:

* Try one of the usual support channels, where you should be able to find devs with Identity Server experience ...

  * [Stack Overflow](https://stackoverflow.com/questions/tagged/blazor)
  * [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
  * [ASP.NET Gitter](https://gitter.im/aspnet/Blazor)

* Open an issue on the engineering repo. The topic might have a bug 🐞 in the guidance, or the topic might be missing a piece of information.

  https://github.com/dotnet/aspnetcore/issues

  Add a `cc: @guardrex` to your opening comment so that I can follow the discussion.
