### ISSUE TITLE
Task or valuetask

### ISSUE THREAD

**Issue by erikthysell** [dotnet/AspNetCore.Docs#18226]
I have a hard time understanding when to use valuetask in stead of task. Most often in regular desktop app development I use task but I can see that many places when invoking javascript the interop method returns valuetask. Is that better for javascript or is there some other reason???  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aada0049-99a8-2f91-5d60-6970474e2371
* Version Independent ID: c29fb1a8-028f-6efd-f1bc-e889fb362311
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @erikthysell ... 🏃 **_Performance_** 🏃 should be the answer. There was a time when all of our JS interop examples used `Task`, and we switched over to `ValueTask` for these because the calls would be just a tiny bit faster. I don't recall the details ... the changes were made a while ago. It was something that engineering started doing, and I picked up on it and changed the sample app, followed by a couple of readers suggesting that we further make the topic in-text examples embrace it. Engineering agreed, so we updated the return types to what you see today.

For more info generally on the choice, see the remarks in the linked API doc for the benefits and conditions ...

https://docs.microsoft.com/dotnet/api/system.threading.tasks.valuetask-1

... and see the discussion with remarks by Stephen Cleary and Stephen Toub on an [SO answer](https://stackoverflow.com/questions/43000520/why-would-one-use-taskt-over-valuetaskt-in-c).

If would be interesting if you benchmarked some JS interop calls both ways and actually found out that `ValueTask` was 🐌 *slower* 🐌 in certain scenarios. If you make such a discovery, I recommend that you let us know.

I don't have any further info. If you want to dig deeper into the subject, see if you can find a deep dive blog post, additional SO posts, and/or chat with language experts on one of the usual support channels ...

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)

You probably also could [Tweet Stephen Cleary](https://twitter.com/aSteveCleary) if you have a question. He's a cool :cat2: and helpful to talk to about things like this.
