### ISSUE TITLE
Call Web Api without Access Token

### ISSUE THREAD

**Issue by Alienroid** [dotnet/AspNetCore.Docs#18230]
This is a corner case.

I am using Blazor WASM with AADB2C. Calling WebAPI works when the user is logged in. However, there are cases that I want anonymous user to access some data from the server. It seems every time I try to perform GetAsync, it takes me to the login page.

I understand this is the expected behavior, part of // Supply HttpClient instances that include access tokens when making requests to the server project.

But what about anonymous users? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5e2e10-ff7b-2b9f-84da-f16028ae2c53
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Call a web API from ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Alienroid 

> HttpClient instances that include access tokens when making requests to the server project

Yes ... if set up that way by the dev. In the vanilla case ...

```csharp
builder.Services.AddBaseAddressHttpClient();
```

... or ...

```csharp
builder.Services.AddTransient(sp => 
    new HttpClient
    {
        BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)
    });
```

... the OOB client doesn't trigger any special auth behavior that I'm aware of. If the component and controller aren't marked with the `[Authorize]` attribute and no token is requested by the component, it should ✨ *Just Work!*:tm: ✨. If a token is already present, I wouldn't be surprised if the `HttpClient` sent it (but I haven't checked myself on it).

There's more flexibility with `HttpClient` now that requires additional coverage, and the topic should be upgraded for the base case with `AddBaseAddressHttpClient`. The other approaches (e.g., `HttpClientFactory` and typed client) need coverage here, and Javier did a really nice write-up on it on the engineering issue at https://github.com/dotnet/aspnetcore/pull/20682.

Our auth coverage in the Blazor WASM security node should get the auth-related coverage, and this topic needs a touch-up on the `HttpClient` registration side.

Thanks for opening this issue to call it out.

@mkArtakMSFT I'm going to go ahead and schedule this for P0 because I can see that this is important coverage that we need. It shouldn't take long given Javier's nice framework design and write-up. I should be able to knock this out 🥊😵 early this week ... Monday I hope.

**Comment by Alienroid** [comment]
Thanks for response Luke, look forward to the documentation.

By the way, I'm pretty sure I removed [authorize] from the controller and the component, however it still kept giving me noaccesstokenException. I'll check it today.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guardrex** [comment]
I've run this scenario, and it worked, but it worked in a *ancient times* 👴 (Preview 2 or 3). :smile:

I have a few minutes here, I'll try again right now with the RC bits and see what happens.

**Comment by Alienroid** [comment]
I also recall it worked before (in preview2). I ran into this issue on RC.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guardrex** [comment]
Oh ... I forgot when I mentioned `AddBaseAddressHttpClient` that they removed that. Yeah, I'll need a configured client for my test then.

**Comment by guardrex** [comment]
There's a typo in one of his examples ... the factory one asks for an `HttpClient`, but it should be getting an `IHttpClientFactory`.

The setup goes like this ...

* Server app gets a controller without `[Authorize]` attribute, which I'll call `WeatherForecastNoAuth`.
* Client app gets a named client without auth handling in `Program.Main` ...

  ```csharp
  builder.Services.AddHttpClient("HostB2C.ServerAPI.NoAuth", 
      client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress));
  ```

  The component has no `[Authorize]` attribute and uses the named no-auth client via the factory ...

  ```razor
  ...
  @inject IHttpClientFactory ClientFactory

  ...

  @code {
      private WeatherForecast[] forecasts;
      private HttpClient _client;

      protected override async Task OnInitializedAsync()
      {
          _client = ClientFactory.CreateClient("HostB2C.ServerAPI.NoAuth");

          forecasts = await _client.GetFromJsonAsync<WeatherForecast[]>(
              "WeatherForecastNoAuth");
      }
  }
  ```

### :tada: :beers: :+1:

**Comment by Alienroid** [comment]
Ohh... Yeah I thought of doing this... Will try this later. Thank you!

So basically we need one httpclient for auth case and additional httpclient for no auth.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Alienroid** [comment]
How come it was working in preview before, that we only needed to change the [authorize]?? :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guardrex** [comment]
> one httpclient for auth case and additional httpclient for no auth.

Yes because this bit ...

```
.AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();
```

... ties the default clients to an auth/tokenized approach everywhere.

Apparently, it's opinionated about it. *Apparently* ... I'm not 100% sure about about it. After `BaseAddressAuthorizationMessageHandler` is stuck on any registration, I guess all unconfigured (unnamed) clients will assume tokenized dealings with the endpoints. One just goes with ...

```csharp
forecasts = await Http.Get...<T>("...");
```

... without mentioning which named client (if there are several).

I guess that's a question that I need to follow-up with Artak/Javier on. Like what if I had two different named client registrations with different auth messages handlers? ... which one would be the default? Idk.

> How come it was working in preview before

I think he changed the design quite a bit across those previews.

**Comment by Alienroid** [comment]
Thanks again Luke! I thought I was going crazy.

Yesterday I ran into bunch issues, got so fed up and just port stuff back to server side lol :)

Not related issue (just for fun): one web API call I kept getting content type issue saying it's application/+json and it failed to do getFromJsonAsync. It worked for getAsync. After I changed all the calls to getAsync, closed vs, reopen vs, getFromJsonAsync worked again...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guardrex** [comment]
Glad you opened this. It's going to lead to important improvements on Monday.

**Comment by guardrex** [comment]
>  content type issue saying it's application/+json

Common when the server is sending back HTML ... i.e., unhandled exception error page content.

**Comment by Alienroid** [comment]
Yep, just weird that clean solution still had the issue until I restarted vs.

Thanks again!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Alienroid** [comment]
Trying it out, getting the following errors:

info: System.Net.Http.HttpClient.HostB2C.ServerAPI.NoAuth.ClientHandler[101]
      Received HTTP response after 144.3699ms - NoContent
info: System.Net.Http.HttpClient.HostB2C.ServerAPI.NoAuth.LogicalHandler[101]
      End processing HTTP request after 156.045ms - NoContent

My Call:
            var client = ClientFactory.CreateClient("HostB2C.ServerAPI.NoAuth");
            forecasts = await client.GetFromJsonAsync<WeatherForecast[]>("WeatherForecastNA");

If I use the auth one, this call goes through once it's logged in.

We don't need to add the client using builder.Services.AddTransient in program.cs right?

my program.cs:

            builder.Services.AddHttpClient("HostB2C.ServerAPI", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
                .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();
            builder.Services.AddHttpClient("HostB2C.ServerAPI.NoAuth",
                    client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress));
            // Supply HttpClient instances that include access tokens when making requests to the server project
            builder.Services.AddTransient(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("HostB2C.ServerAPI"));

**Comment by Alienroid** [comment]
removed a comment. Made a mistake

**Comment by guardrex** [comment]
No, you shouldn't need that. The scenario works here the way that I showed it :point_up:, so I'm not sure what's going on with ur app. Try cleaning everything, rebuilding, and using an in-private browser window.

**Comment by Alienroid** [comment]
Sorry I made a mistake 😉

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
