### ISSUE TITLE
Blazor WASM State Management topic

### ISSUE THREAD

**Issue by taylorchasewhite** [dotnet/AspNetCore.Docs#18297]
Are there plans with the 3.2 release to add examples / best practices for proper state management in Blazor Web Assembly?

I know this is all Blazor Server, but given that Blazor WebAssembly is a common pattern too, I figure this is a fair question :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae14b3e3-3271-b919-9e0a-6f317a6b2d2d
* Version Independent ID: e5e1273b-195e-5da1-b4aa-66bbcff1425b
* Content: [ASP.NET Core Blazor state management](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/state-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
@guardrex, ProtectedBrowserStorage support is now in (https://github.com/dotnet/aspnetcore/pull/23553). @MackinnonBuck can you share a small sample showing how to use the new ProtectedBrowserStorage?

**Comment by mkArtakMSFT** [comment]
Also, I do like the idea of having a separate node for Blazor WebAssembly state management: `Create a new doc for state management in WASM`, as you referred to it.

**Comment by mkArtakMSFT** [comment]
As for the categories (your last question), maybe we should hold on for now. Let's roll the simple state management doc and then see how community will react and tell us what more they will need.

**Comment by guardrex** [comment]
> Blazor server feature and does not work in WebAssembly

Then, the options are down to ...

* Convert the doc to cover both WASM and Server given the overlap in approaches in the *Where to persist state* section and with possible 3rd party libs. Sections that would pertain to one or the other clearly marked within the topic.
* New doc for WASM (and a node to hold both topics), and it will have similar coverage to what's in the *Where to persist state* section, possibly made generic and put into an INCLUDES file so that both topics could use that content. Same for the 3rd party package remarks.
* Don't address WASM at this time and only use this issue to fix up the current coverage for Blazor Server.

**Comment by guardrex** [comment]
@mkArtakMSFT I'm working on this issue now. I think we should try a single **_pivot_** topic for this at first. I can use INCLUDES for common content. Let's give it a shot. I think it would reduce our burden for:

* A new node and *Overview*.
* More complicated content split between/among topics.
* More messing about with the ToC.
* Another redirection file entry.

If it doesn't work out on review, I can set up a new PR with the node-topic approach.

As a reminder on pivots, see the Tooling doc, which performs pivots on OS. For this work, we'd pivot our *State management* topic on *Blazor WebAssembly* and *Blazor Server* ...

https://docs.microsoft.com/aspnet/core/blazor/tooling

**Comment by guardrex** [comment]
@MackinnonBuck ... You mentioned (and showed) a change for local storage `GetAsync`. Is the current coverage on **_session storage_** still accurate? ...

> To recover the `currentCount` data if the user returns to the `Counter` component later, including if the user is on an entirely new circuit, use `ProtectedSessionStore.GetAsync`:

```csharp
protected override async Task OnInitializedAsync()
{
    currentCount = await ProtectedSessionStore.GetAsync<int>("count");
}
```

**Comment by MackinnonBuck** [comment]
@guardrex The new changes apply for both local storage and session storage.

**Comment by guardrex** [comment]
Ok ... I'll likely need to make one more commit then. Stand-by before you review.

**Comment by guardrex** [comment]
lol ... I forgot ...... tomorrow. I need to sleep on it one more night. I'll make the changes, and they'll be on the PR in the morning.

**Comment by guardrex** [comment]
@scottaddie ❓ ... For the new pivot group `blazor-hosting-models`, I'll go with ...

```yml
- id: blazor-hosting-models
  title: Blazor Hosting Model
  prompt: Choose a Blazor hosting model
  pivots:
    - id: webassembly
      title: Blazor WebAssembly
    - id: server
      title: Blazor Server
```

... but I noticed while adding the new group that prefixing the OSes in the `operating-systems` group with `os-` is overkill. It's a common and meaningless prefix for a whole topic that uses pivot groups on OS. It seems to make more sense to drop the `os-`. After all, I don't plan on using `hosting-model-webassembly` and `hosting-model-server` for the `blazor-hosting-models` pivots. The only reason those `os-` prefixes are there is because the file that I stole from the other repo had it. I propose that we do this for that group ...

```yml
- id: windows
  title: Windows
- id: linux
  title: Linux
- id: macos
  title: macOS
```

**_Now_** is the time ⏰ to make this change, while there's only one doc on the repo that uses pivot groups.

**Comment by scottaddie** [comment]
@guardrex Your zone pivots proposal sounds good to me.
