### ISSUE TITLE
Updated the Auth overview docs to include to include note about updating existing projects

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#18309]
We've got this report https://github.com/dotnet/aspnetcore/issues/21825, where the customer missed to add the auth script reference in the index.html file.
Need to add a small section in the [Overview](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/?view=aspnetcore-3.1) article to include that.

**Comment by guardrex** [comment]
Ok, but it's in the OIDC topic itself ...

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1#index-page

@yopez83, were you actually looking at https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library and missed a step for the script in the *Index* page?

**Comment by yopez83** [comment]
@guardrex I was looking at https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/?view=aspnetcore-3.1#feedback

**Comment by yopez83** [comment]
The page I was looking at it's like an overview sort of speak, whereas the implementation details are covered in the page you mentioned @guardrex. I would say, a link will be great.

**Comment by guardrex** [comment]
> I would say, a link will be great.

Yes, that's best ............

I was just responding with some additional TOC background for this issue ...

The *Overview* doesn't contain any configuration/implementation guidance, nor is it supposed to contain such information. I've even been trying to factor it out where it occurs because readers don't like heavy-handed "overviews" ... they want just literally *an overview*. What happens is that they either totally skip the implementation guidance when reading docs down the TOC ... then miss guidance when they get into the more detailed topics below (or we end up duplicating content, which is bad), or they read it but it doesn't make a lot of sense because it's a lot of disconnected, seemingly random bits of coverage.

@mkArtakMSFT This is going to lead to 😵 *Messy Docs*:tm: 😵 if we go down this road of semi-randomly calling out implementation guidance in *Overview* topics. For this bit of TOC, readers should (in the base case) access the first topic (on the Auth Lib for standalone projects) for basic OIDC coverage, or ... **_OR_** we should kill the first topic and move all of it's coverage into the *Overview* as the base case. Actually tho, I'm kind'a happy right now with what we have.

The *Additional resources* of the *Overview* topic states ...

> Articles under this Overview provide information on authenticating users in Blazor WebAssembly apps against specific providers.

Perhaps, we should make it more promoninent in the *Overview* ... I can make a section that calls out the cross-links. That way, the reader will get to the right topic for their provider and the *Overview* won't get bogged down in duplicate implementation guidance.

**Comment by mkArtakMSFT** [comment]
@guardrex I think your concern is valid and the link is a fine way to handle this. I looked through the PR and it turned out fine.
