### ISSUE TITLE
ClientId on server side should be the value for _Application ID URI_

### ISSUE THREAD

**Issue by goekboet** [dotnet/AspNetCore.Docs#18319]
I get an error where the server fails to validate audience. Should the value for clientId be the value for Application ID URI instead of the ClientId guid? When I make this change the example works fine. i.e.
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "{DOMAIN}",
    "TenantId": "{TENANT ID}",
    "ClientId": "{SERVER API APP CLIENT ID}", &lt;-- Application ID URI
  }
}

for example:
{
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "contoso.onmicrosoft.com",
    "TenantId": "e86c78e2-8bb4-4c41-aefd-918e0565a45e",
    "ClientId": "api://some.clientid.uri",
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9816eaee-5eff-c3c8-5d58-e2c02c760a00
* Version Independent ID: 60992d09-2a04-1d10-4c85-9642b20ff0e3
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @goekboet ... That config sounds more likely for the v2.0 endpoint. For the v1.0 endpoint (and Azure Identity Platform v1.0), it should be as the topic describes (i.e., the GUID-based Client ID).

We're in a bit of a transitional phase here with Azure. You may have noticed that all of the Azure docs and packages have gone v2.0 (`Microsoft.Identity.Web` package and friends). However, the package here (`Microsoft.AspNetCore.Authentication.AzureAD.UI`) and the configuration is all v1.0 OOB/by-default. This is a known situation, and engineering is working on it. We'll document new bits as they come out.

At the end of the day, *yes!* ... do what works. If you're on the v2.0 endpoint, that's more likely the correct config. There's a PR up for review now that should call that point out. See the diff at ...

https://github.com/dotnet/AspNetCore.Docs/pull/18308

Also, I'll be walking all of the topics in this node this weekend to see what works and what has broken since we put the topics up a few weeks ago and try to fix them up by EOD on Monday.
