### ISSUE TITLE
The button onclick event binding seems wrong

### ISSUE THREAD

**Issue by carlthecoder** [dotnet/AspNetCore.Docs#18345]
The button onclick event binding seems wrong. It does not seem to accept method groups, but instead wants a method call with the parantheses included.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de31c7e-7895-9d7c-0d9a-5bdfe83b60a9
* Version Independent ID: 334b7206-d383-40c3-b346-b54df9d87293
* Content: [ASP.NET Core Blazor event handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/event-handling?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello! Thanks for contacting us. This sounds like a general question about using ASP.NET Core Blazor. While we try to look at and respond to all issues, for questions like this we recommend posting to a community support forum or chat:
 
* [Stack Overflow](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Blazor)

**Comment by carlthecoder** [comment]
Hi,

It is not a question I am telling you the documentation on the page is wring!
________________________________

**Comment by guardrex** [comment]
I hear u, but ...

* The topic isn't wrong. Method names are valid C# entries for the `@onclick` attribute directive.
* We don't have the staffing to provide support. If you work out what the problem is, then we might provide coverage for it ... a caveat, a common incorrect setup/config scenario, or an edge case that devs hit. Right now tho, something is amiss in the way you've set up the app or component.

Post your code to a support forum, such as SO, and then let me know back here what the source of the problem turned out to be.

**Comment by carlthecoder** [comment]
Ok, I will double check later and let you know.
In my case at least visual studio was not accepting method groups.

Kind regards,
Carl
________________________________
