### ISSUE TITLE
References to Thread.CurrentPrincipal being thread-static are not correct.

### ISSUE THREAD

**Issue by madelson** [dotnet/AspNetCore.Docs#18362]
In multiple places, the page refers to `Thread.CurrentPrincipal` as being "thread-static" and says that it will not work in async scenarios. There is even an included code example intended to demonstrate this:

```
// Create a ClaimsPrincipal and set Thread.CurrentPrincipal
var identity = new ClaimsIdentity();
identity.AddClaim(new Claim(ClaimTypes.Name, "User1"));
Thread.CurrentPrincipal = new ClaimsPrincipal(identity);

// Check the current user
Console.WriteLine($"Current user: {Thread.CurrentPrincipal?.Identity.Name}");

// For the method to complete asynchronously
await Task.Yield();

// Check the current user after
Console.WriteLine($"Current user: {Thread.CurrentPrincipal?.Identity.Name}");
```

**However**, `Thread.CurrentPrincipal` is not, in fact, thread-static. It behaves more like `AsyncLocal` and flows nicely across awaits. Simply running the code snippet demonstrating the problem shows that it works fine on both .NET Framework and .NET Core (at least in the scenarios I tried) :-)

We were migrating to ASP.NET Core with a large codebase that used Thread.CurrentPrincipal pretty heavily. All we had to do to get things working was set this in a middleware upfront and it flows nicely just like it did before.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b42a61c-cf3a-3bdb-0145-dc6295c5ba23
* Version Independent ID: 5b8d2082-1e70-eb9a-1bbe-7b93f74bdd3a
* Content: [Migrate from ClaimsPrincipal.Current](https://docs.microsoft.com/en-us/aspnet/core/migration/claimsprincipal-current?view=aspnetcore-3.1)
* Content Source: [aspnetcore/migration/claimsprincipal-current.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/claimsprincipal-current.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @mjrousos
* Microsoft Alias: **scaddie**

**Comment by mjrousos** [comment]
It looks like [this behavior changed](https://github.com/dotnet/corefx/pull/34747/files) about a year ago. I think our general guidance to avoid `Thread.CurrentPrincipal` in ASP.NET Core scenarios is still correct since using global mutable statics like this is an anti-pattern in ASP.NET Core (aspnet/Security#322, dotnet/aspnetcore#481). 

The docs should be updated, though, to not say that `Thread.CurrentPrincipal` is thread static since, as @madelson points out, it *could* be set in Midddleware and accessed elsewhere, it's just not the usually recommended solution.

**Comment by Rick-Anderson** [comment]
@serpent5  looks like an easy one.
