### ISSUE TITLE
Improve debug documentation

### ISSUE THREAD

**Issue by floreseken** [dotnet/AspNetCore.Docs#18403]
So, I've been trying to get this to work for an hour.
Only to discover that it takes 8 seconds after the app displays to actually work.. and this is the blazor webassembly template that i'm using.. on a serious desktop machine.. 

Hope to spare others the same fate.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @floreseken ... I'll add a NOTE right now to cover the delay.

You might want to mention it to engineering on the product unit repo. They might want to investigate it further.

If you open an issue for them, please add a `cc: @guardrex` to your opening comment so that I can follow the discussion.

**Comment by guardrex** [comment]
Actually, I think that's best. Eight seconds seems like a loooong time and doesn't match my testing here. It's best if we hear back from them before taking action on the topic. I'll mark this ON HOLD until you get feedback from them.

Please either mention me or this issue on your engineering issue. I'd like to cross-link this issue to their issue.

**Comment by floreseken** [comment]
See it here in action: https://1drv.ms/v/s!Ak-9ieqvyXNQ1t5R4-gPDwJ8gmRrZQ

Will make an item with the engineering team

**Comment by floreseken** [comment]
https://github.com/dotnet/aspnetcore/issues/22028

**Comment by guardrex** [comment]
@floreseken ... Looks like after moving over to the mono repo that they're classifying it as an engineering/product issue. They'll *hopefully* resolve it. I'll keep an :ear: open for more feedback, but it isn't really actionable to just say 'it might take several seconds to start' when I have no idea what the scope of the problem is (i.e., what causes it and how many users are affected). I'll keep and :ear: open. If a lot of devs report the problem, I'll add a NOTE to the topic.

**Comment by floreseken** [comment]
fair enough
