### ISSUE TITLE
About Component parameters

### ISSUE THREAD

**Issue by dubeg** [dotnet/AspNetCore.Docs#18440]
Should we always use `@` when referencing the component members (ie. `Parameter="@Member"), as in the following example?
```
<InputText 
  Value="@EmployeeName"
  ValueExpression="@( () => EmployeeName )"
  ValueChanged="@EmployeeName_Changed"
  />
```

I've noticed that the following works as well:
```
<InputText 
  Value="@EmployeeName"
  ValueExpression="() => EmployeeName"
  ValueChanged="EmployeeName_Changed"
  />
```

However, in this example, the Value parameter is set to the string "EmployeeName", instead of the value it contains.
```
<InputText 
  Value="EmployeeName"
  ValueExpression="() => EmployeeName"
  ValueChanged="EmployeeName_Changed"
  />
```

Is the reason that setting ValueChanged works without the `@`, but not Value is because of type inference performed by the parser?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1b6ad8-13ba-0195-8829-ade3b1b0b9cb
* Version Independent ID: 6609ea68-a918-f3b9-8c9c-004a4436e350
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dubeg ... We don't show that syntax, thus I don't think engineering recommends those approaches for component params. We show everywhere, including in the Forms & Validation topic for these validation components, `@bind-Value` syntax ...

```
@bind-Value="starship.ProductionDate"
```

The "value" (the property on that model) isn't prefixed with `@` because the `@bind-{PROPERTY}` syntax means that whatever is in the quotes will be treated as C#.

I'll leave this up for triage in case Artak has any further remarks. AFAIK Artak, we cover this consistently across topics. If you don't have any further guidance, we can close this.

**Comment by dubeg** [comment]
Hello Rex. Yes, it seems consistent in the docs. 

In some examples/articles on the web, people sometimes write it without the `@`, and I discovered it on my own as well. 

Just thought I'd ask, since this confused me. I kinda liked not using `@` when assigning to ValueExpression since it avoided me an extra pair of parenthesis, but if it's not supported and/or I get too confused, I'll just always use the `@` except for literal values.

I'd maybe suggest an explicit note or warning on this for clarification or guidance. What do you think? Could more people come across conflicting syntaxes on the web and get confused too?

**Comment by guardrex** [comment]
Good point ... we show that approach at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#component-parameters

... because the attribute value is just a string.

I think we **_DO_** need to clarify things a bit further. Thanks for being persistent about it, @dubeg.

If what's in the quotes (the attribute value) is C#, then a value can also be applied with `@` syntax ...

```razor
<ChildComponent Title="@someLocalVar"
                OnClickCallback="@ShowMessage">
    Content of the child component is supplied
    by the parent component.
</ChildComponent>
```

... if needed. I mean if the value is just a string, then you wouldn't use a var there. If the value is in a var, then that should be fine.

... or `@bind={PROPERTY}` syntax can be used in these cases where the value is taken as C# ...

```razor
<ChildComponent @bind-Title="someLocalVar"
                OnClickCallback="@ShowMessage">
    Content of the child component is supplied
    by the parent component.
</ChildComponent>
```

... with the child having an added ...

```csharp
[Parameter]
public EventCallback<string> TitleChanged { get; set; }
```

Sooooo ... :smile: ...... we've given Artak a bit more the chew on here! lol

I'll go ahead and schedule this for further work taking into account anything that Artak adds to the discussion.
