### ISSUE TITLE
var editItem hides private TodoItem editItem

### ISSUE THREAD

**Issue by TNCodes** [dotnet/AspNetCore.Docs#18464]
[Enter feedback here]

Hallo!

I am trying to get this code working and I have discovered an error that exists both in the sample code on this page, and in the file AspNetCore.Docs/aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Pages/CallWebAPI.razor 

The private property "editItem" on the row below:
private TodoItem editItem = new TodoItem();
is hidden in the private void EditItem(long id) by the local variable "editItem" found in the below row:
var editItem = todoItems.Single(i => i.Id == id);

Therefore, the properties of the private property "editItem" will be never be set and the sample code will not work!

Please either add "this." to the below row:
editItem = new TodoItem { Id = editItem.Id, Name = editItem.Name, IsComplete = editItem.IsComplete };
to reference the private property "editItem", or change the name of the private property to "_editItem".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5e2e10-ff7b-2b9f-84da-f16028ae2c53
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Call a web API from ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @thonys001 ... We made a pass recently (*quickly*) updating private fields. This one probably received a foul update. I'll get it addressed quickly.

> AspNetCore.Docs/aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Pages/CallWebAPI.razor

That's surprising given that IIRC I ran that code with the 3.2 update **after** the fields were changed and IIRC it ran ok. I'll check it and see what's what.

**Comment by TNCodes** [comment]
Thank you @guardrex for the quick response!

This is a very easy error to miss and it took me some time to figure it out.

The code started to work immediately when I added "this.":
**this.**editItem = new TodoItem { Id = editItem.Id, Name = editItem.Name, IsComplete = editItem.IsComplete };

An other, and perhaps simpler, solution would be to directly assign the private property in the EditItem function:

private void EditItem(long id)
{
    editItem = todoItems.Single(i => i.Id == id);
    editRowStyle = "table-row";
}

**Comment by guardrex** [comment]
I agree.

This example ... the whole topic really ... is a sort of **_first draft_**. It came into the doc set from engineering and was mostly edited for style+grammar. I haven't had a chance to UE ("user experience") pass some of the new content that was loaded because we were so busy just trying to get new content up.

The error in this example came about two weeks ago: Engineering told me that we should drop the use of the underscore for **all** private fields everywhere ... that it was only around for backwards compat in the framework and that dev code shouldn't be shown using it. Therefore, I did what amounts to little more than a find-'n-replace patch to update everything in one shot on https://github.com/dotnet/AspNetCore.Docs/pull/18182, which touched 46 files. This snuck in on that. 

All of the new content will be carefully edited and updated over the next couple of months. Hopefully, further problems like this that aren't caught by the community will be fixed up as we go.

I'll post something up here shortly to look at before updating so that we can figure out the best approach.

**Comment by guardrex** [comment]
The content is a bit scatterbrained at the moment. The goal of the section is to call out the helpers. It's not really meant to be a tutorial on how to build an app that actually calls these methods ...

* There is no API for this.
* The editing of a `TodoItem` isn't fully fleshed out because all of the items aren't shown in a way that the user can select one to edit (i.e., call `EditItem`).
* We haven't determined yet what we'll show in the sample app, if anything, for this on https://github.com/dotnet/AspNetCore.Docs/issues/14216. Although the `CallWebApi` example might remain, it's overkill for a basic presentation. The sample should probably receive a simpler component, which can then be linked into this topic as it's example.

Anyway, this is cross-linked to that sample update issue now, so I'll see it when I get to that one.

For the time being, I think we should just patch this scenario.

**Comment by TNCodes** [comment]
Thank you @guardrex for the very fast reply and fix of this issue!

I agree that some of the samples need updating, for instance a better UE (normally the read only view of the row you edit is hidden and the editor with save/cancel buttons is shown in its place/same row instead of above as in the sample).

But, thanks to your quick edit, at least the sample code works.
