### ISSUE TITLE
Where do i find the browserInspectUri?

### ISSUE THREAD

**Issue by Assassinbeast** [dotnet/AspNetCore.Docs#18531]
What is the "browserInspectUri"?
Where do i find it for chrome/edge?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Assassinbeast ... Ask in engineering because that level of detail didn't come over in the content.

https://github.com/dotnet/aspnetcore/issues

Cross-link the topic and show them the *launchSettings.json* line.

Please add a `cc: @guardrex` to your issue so that I can track the discussion.

btw -- I'm putting in a patch for the name. It isn't `inspectUri` as the current content says. It's as you say ... `browserInspectUri`. I'll use this issue to fix that.

**Comment by Assassinbeast** [comment]
@guardrex Oh sorry. I thought i had to fill in the curly braces so it looked something like 

"inspectUri": "**https**://**localhost:5001**/_framework/debug/ws-proxy?browser=**xxx**"

**Comment by guardrex** [comment]
I think that's a fair point ... for the topic to say that the placeholder values are filled in and so the dev doesn't need to supply them. I'll put this on the project for triage. If I figure out what to say about the source of the values prior to Artak commenting on this, then I'll submit a PR for it.

**Comment by guardrex** [comment]
Got it ...... rubber :duck: to the rescue. Yes, the extension has the docs on it. I'll draft the update from that and saying the extension fills in the values.

https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly

**Comment by guardrex** [comment]
Since the extension only apples to VSC, I'll craft it to say "tooling." The important point is that the placeholder values aren't provided by the developer.
