### ISSUE TITLE
Recompression of blazor.boot.json not included

### ISSUE THREAD

**Issue by smartprogrammer93** [dotnet/AspNetCore.Docs#18551]
So in the section for changing the dll extension to something else, it says delete the compressed file and recompress Blazor.boot.json without an explanation on how to do so.\

and the recompression of the file is not included in the PowerShell Script so you are stuck with an uncompressed version.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b4d6a1-1436-7ba8-a5c5-8dcb6a955bb0
* Version Independent ID: 4a6a13b4-fe5c-a9fb-5d7d-33d5aa0fbac3
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/blazor/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @smartprogrammer93 ... Yes, it's manual and up to you at this point. Let's ask because I don't see an open engineering issue to provide anything built in at this time. These issues are usually triaged on Fridays, so we might hear back tomorrow on it.

Artak, is it worth my time to create PS-based approaches to Gzip/Brotli-compress the files and update the doc's example script? ... or do you have something coming in the framework to deal with compression in this scenario?

**Comment by guardrex** [comment]
Actually @smartprogrammer93, I found the issue I thought existed. Ask them here if their plans include dealing with compression ...

https://github.com/dotnet/aspnetcore/issues/21489

... I'll keep an :ear: on that for your question and chime in with my ask about creating a PS script for the docs that handles it.
