### ISSUE TITLE
Note about installing dev-certs for being able to connect to remote debugger

### ISSUE THREAD

**Issue by dselvan** [dotnet/AspNetCore.Docs#18554]
Was trying to debug an example using vscode and a completely fresh install of dotnet core following the steps in this guide. When trying to launch the `.NET Core Debug Blazor Web Assembly in Chrome` launch configuration, I was getting a timeout trying to connect to the debugger. I eventually realized it was because I didn't have the dev cert installed and it tries to connect to the debugger via `wss`. It would probably be good to have a note about that as some people might not think to install the dev-cert just to test out a toy example. 

Also on the WSL front this might be extra confusing as you'd have to install the dev-cert from your WSL dotnet installation into your windows certificate store manually (though right now it seems there are bigger issues with getting the [debug proxy launching under WSL](https://github.com/dotnet/aspnetcore/issues/20597)). 

If this is something worth adding, I'd be happy to write it up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dselvan ... The dev cert should be installed with the SDK, which is a prereq for VSC use. I'll keep an :ear: open for more feedback like this. If more devs report hitting it, then we'll see about calling it out.

I'm going to close, but WRT the WSL and issue you linked, I'll cc:

@mkArtakMSFT 
@captainsafia

... to let them know about your feedback. If they feel that we need to document something further, they'll re-open and advise on the updates.

**Comment by dselvan** [comment]
Hi @guardrex. While the cert is installed as part of the sdk installation it is not trusted by defualt (or at least I hope not... wouldn't want a random dev cert to be trusted on my machine without being deliberate) . To trust the cert you need to run `dotnet dev-certs https --trust` as stated in the docs on [enforcing SSL](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&branch=pr-en-us-14568&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos). Without trusting the cert you are going to have an issue the wss connection not being trusted and no way of telling chrome to ignore it. 

But I'm happy to wait and see if this was possibly just an issue for me.

**Comment by guardrex** [comment]
Correct ... not by default, but ...

> as stated in the docs on enforcing SSL

... not so much by way of a mention in a rather deeply buried topic. The SDK install output (or VS tooling) instructs to trust the cert and provides the command. In most cases AFAIK, devs must trust it in order to run anything securely. For example, all of the templates default to HTTPS.

I'm a bit concerned about calling out a fundamental framework/tooling aspect. This could be called out all over the place ... **_many_** docs would get such content for the same reason we'd put it here. Therefore, it would be rather arbitrary to place it here. However, let's see how it goes and if Safia or Artak have a contrarian position.

**Comment by captainsafia** [comment]
I've been working on the new debugging experience in VS Code and have seen quite a few people test it over the past few days.

This issue around debugging not working because SSL certs are not trusted has come up with three different users over the past few days, so it's coloring my perspective a bit.

Although it is a fundamental tooling aspect, I actually found that it is not super easy to figure out that it needs to be done in order to support debugging.

I'm inclined to say that we should include it in the docs. Perhaps not as an outright explainer but a brief sentence that says "hey we assume that you've already trusted dev certs if you're debugging an app secured with SSL"

**Comment by guardrex** [comment]
:+1: I'll put the update in shortly.
