### ISSUE TITLE
Using environment specific variables with Nginx in Docker 

### ISSUE THREAD

**Issue by BaumTom** [dotnet/AspNetCore.Docs#18563]
I'm using the "Standalone Deployment - Nginx in Docker" way of deploying the Blazor app. So far the description is clear and the application works in my Docker container. 

What I couldn't find in the description is how the ASPNETCORE_ENVIRONMENT variable - or any other environment variable - can be used in such a scenario. I want to use it for environment specific app settings (e.g. appsettings.dev.json)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b4d6a1-1436-7ba8-a5c5-8dcb6a955bb0
* Version Independent ID: 4a6a13b4-fe5c-a9fb-5d7d-33d5aa0fbac3
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1&viewFallbackFrom=aspnetcore-3.0#nginx)
* Content Source: [aspnetcore/host-and-deploy/blazor/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @BaumTom ...

* Blazor Server should work the same as an ASP.NET Core app WRT the env var.
* Blazor WebAssembly Hosted shares the environment with the Server app, so that should also work like a regular ASP.NET Core app.
* Blazor WebAssembly Standalone uses a header. See :point_right: https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-model-configuration?view=aspnetcore-3.1#environment

We're about to make changes to the ToC that will make that information easier to find.
