### ISSUE TITLE
Provide clarity on using B2C Custom Policies with Blazor/MSAL

### ISSUE THREAD

**Issue by Tim-Hodge** [dotnet/AspNetCore.Docs#18600]
Currently there is not an obvious 'best practice' implementation story for B2C custom policies and Blazor WASM.

Documentation ([link](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#custom-user-flows)) states that custom user flows are not supported by MSAL - but there is no mention of B2C custom policies.

App Settings ([link](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#app-settings)) section shows a "SignUpSignInPolicyId" which I do not believe is used downstream and can be removed.

Ideally there would be further information on/forward links to:

1. MSAL limitations with respect to integration with B2C (user flows and custom policies).
a. Link to specific MSAL docs and limitations
a. Any other considerations/limitations wrt Blazor -> MSAL -> B2C
1. Expand on "Create custom user flows in developer code". Ideally developers minimise custom code around A&A so this should be specific.
a. Samples would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d682d4c-86b5-c47e-89a3-3684b2235320
* Version Independent ID: a80e115c-466a-288d-a918-9ef7514f5add
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Tim-Hodge ...

> B2C custom policies

User flows work per Azure docs, which are cross-linked. There's no utility yet in Blazor for reaching the edit profile or password reset endpoints without building your own link per Azure docs. For example ...

```csharp
private void ResetPassword(MouseEventArgs args)
{
    Navigation.NavigateTo("https://{TENANT}.b2clogin.com/{TENANT}.onmicrosoft.com/oauth2/v2.0/authorize?" +
	"client_id={CLIENT ID}" +
	"&redirect_uri=https%3A%2F%2Flocalhost%3A5001%2Fpasswordreset-callback" +
	"&response_mode=query" +
	"&response_type=id_token" +
	"&scope=openid" +
	$"&nonce={Guid.NewGuid()}" +
	"&state=12345" +
	"&p=B2C_1_passwordreset1");
}
```

... not much fun to work with! :smile: This is known to engineering, of course. My understanding is that further improvements are coming. We'll document new features as they roll out. I suspect that they'll have the framework build these links for devs ... some kind of navigation endpoint/method that can be used/called.

If you build your own link and you find that something in Azure docs breaks or has unexpected behavior after being directed to Azure, then you can [open an issue for the product unit](https://github.com/dotnet/aspnetcore/issues) or at the bottom of the Azure doc to ask the Azure folks. If you want to ask engineering directly about edit profile and/or password reset ... or any other user flow-related question for upcoming Blazor releases (**_on the Blazor side_** ... plz don't ask them Azure questions) ... you can open an issue for that with them. Please add a `cc: @guardrex` to your issue so that I can follow the discussion.

> "SignUpSignInPolicyId" which I do not believe is used downstream and can be removed.

It is used to build the B2C provider address for sign in.

> MSAL limitations with respect to integration with B2C (user flows and custom policies).
>
> Expand on "Create custom user flows in developer code".

We don't have anything else to cover outside of what's in the the *Custom user flows* section at this time. We'll document new features as they roll out. WRT a sample, such as :point_up:, that's covered by the cross-linked Azure docs. We don't want to maintain that coverage in this doc set.

Thanks for commenting. You'll see improvements as the Blazor framework goes forward, especially in moving to OIDC 2.0 on the Blazor side. Azure docs and examples have heavily moved that way, and Blazor is being worked internally in the same direction.
