### ISSUE TITLE
How to exclude a entire subfolder and its contents from the assets manifest

### ISSUE THREAD

**Issue by comfycoder** [dotnet/AspNetCore.Docs#18630]
[Enter feedback here]
I have been unsuccessful in figuring out how to exclude an entire subfolder and its contents from the generated assets manifest. Would you show an example on this page, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8c235e-1ce4-046f-e848-294096361922
* Version Independent ID: 6240f626-97d4-ace0-5e34-20e1c3592f86
* Content: [Build Progressive Web Applications with ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/progressive-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/progressive-web-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @comfycoder ... Could you open an issue on the engineering repo asking this? Open it at ...

https://github.com/dotnet/aspnetcore/issues

Add a `cc: @guardrex` to your issue so that I can follow the discussion.

Leave this issue open. When we get an answer there, I'll react over here on this issue.

**Comment by SteveSandersonMS** [comment]
This seems like an MSBuild question. You'll want to do [something like this](https://github.com/rainersigwald), except instead of removing from `<Content>`, you need to remove from `<ServiceWorkerAssetsManifestItem>`.

**Comment by guardrex** [comment]
@SteveSandersonMS, sounds like you're saying that this is an edge case that we won't be covering. Is that correct?

**Comment by SteveSandersonMS** [comment]
No, just saying it's a question about MSBuild rather than Blazor :) See MSBuild docs for info about how to manipulate its item groups.

**Comment by SteveSandersonMS** [comment]
Oh, if you're asking whether I think this should be covered in Blazor docs, I'd say no, since it's not our goal in Blazor docs to document all the ways you can manipulate things with MSBuild.

**Comment by SteveSandersonMS** [comment]
Actually my apologies, I was wrong. There isn't a good supported way to remove items from the list after it's been populated, because it's populated inside the Blazor build internal targets, and we don't support hooking into the before/after states of those targets.

Anyone who really wants to do this can look at the sources at https://github.com/dotnet/aspnetcore/blob/master/src/Components/WebAssembly/Build/src/targets/ServiceWorkerAssetsManifest.targets#L103-L113 to see how the behavior could be modified in custom MSBuild targets, but please be cautioned that we don't consider the underscore-prefixed target names to be public API, so we may change them in any future release.

If we get more customer feedback that further extensibility is needed here we can certainly look into adding a feature for it in the future.

**Comment by guardrex** [comment]
Thanks @SteveSandersonMS 

@comfycoder, I'm going to close as not actionable for the docs, but that should give u enough info to do something ..... well ...... 💀 *dangerous at your own risk!* 💀 :smile: lol

**Comment by scottaddie** [comment]
> If we get more customer feedback that further extensibility is needed here we can certainly look into adding a feature for it in the future.

I opened the issue linked above ☝️ to see if that drums up interest from any other customers.
