### ISSUE TITLE
Custom AuthorizationMessageHandler not working

### ISSUE THREAD

**Issue by srudin** [dotnet/AspNetCore.Docs#18677]
I have been following this documentation: https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1

However my client and server are not hosted at the same url. Therefore I came to this page and followed the instructions about creating a custom AuthorizationMessageHandler.

The following works:
- Accessing a component -> Redirected to azure ad login and back to app
- In the browser I can see the token etc. in the session storage
- Calling an unsecured server api method and getting data

But as soon as I add the code about the custom AuthorizationMessageHandler the same call to the server api method throws and runs into an infinite loop with the try/catch -> AccessTokenNotAvailableException.Redirect().

I have no idea how to fix this or even where to look at... any help please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2cdb52c-843f-5944-429d-11ea821c1e22
* Version Independent ID: 9c4f99ef-f070-b527-4efc-96a04798d9ef
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srudin** [comment]
Ok I was able to get it to work. I was missing the scope information.

Feedback: The documentation already has a hint about adding scopes but to me it was not to clear what I have to put. I tried some values but they all resulted in authentication failures - but it worked when leaving it away so that's what I did. The token I got was even valid for the server when sending it over curl or some other test tool BUT then the AuthorizationMessageHandler didn't work. I now assume this is because of the IAccessTokenProvider that is internally used will not find the item in the browser storage (it is named "msal.SCOPE.idtoken") if the scope is not specified... a meaningful exception message would make this clear and prevent that people like me need to spend hours to figure it out!

**Comment by guardrex** [comment]
Hello @srudin ... Thanks for that feedback.

> a hint about adding scopes

A scope is required for an API call, and I think you're the second dev to ask on that point. This topic will be worked on further soon, and I'll try to make that point clearer in all of the Blazor WASM security topics when I make the next round of updates.

> it was not to clear what I have to put

I don't think that we'll be able to address that generally. That's variable depending on the provider. It can even be different between v1.0 and v2.0 endpoints.

> will not find the item in the browser storage (it is named "msal.SCOPE.idtoken") if the scope is not specified... a meaningful exception message would make this clear 

We only work on the docs here. You would need to address that to engineering in an issue on their repo at ...

https://github.com/dotnet/aspnetcore/issues

If you open an issue with them, please add a `cc: @guardrex` to your opening comment so that I can follow the discussion.
