### ISSUE TITLE
InvokeAsync to wrap StateHasChanged?

### ISSUE THREAD

**Issue by ndc** [dotnet/AspNetCore.Docs#18690]
In the "Invoke component methods externally to update state" section the example for the event handler uses `ComponentBase.InvokeAsync` to wrap the call to `StateHasChanged()`.

Is it necessary to use InvokeAsync? I tried to call StateHasChanged without wrapping it in InvokeAsync and it still worked. What does InvokeAsync do in this example?

I think it is worth adding explanation in the documentation if InvokeAsync is important. If it is not necessary then the example can be simplified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ndc ... The code and explanation in this section came directly from engineering. They provide a reason for calling `InvokeAsync` in the text, namely to ...

> [dispatch] to Blazor's synchronization context.

At the end, they wrote ...

> InvokeAsync is used to switch to the correct context and queue a render.

You can inquire further on it with the product unit on the engineering repo at ...

https://github.com/dotnet/aspnetcore/issues

... link directly to that section with ...

https://docs.microsoft.com/aspnet/core/blazor/components#invoke-component-methods-externally-to-update-state

... and cross-reference this issue with ...

```
https://github.com/dotnet/AspNetCore.Docs/issues/18690
```

Add a `cc: @guardrex` to your opening comment so that I can follow the discussion. If they have more to say (or less, i.e., they want to simplify it), then I'll re-open this issue.
