### ISSUE TITLE
The dotnet example is opaque for the type of visitor you should be expecting on this page.

### ISSUE THREAD

**Issue by simonziegler** [dotnet/AspNetCore.Docs#18735]
Hi, in the Create the App section you have a `dotnet` command. Unless I am familiar with B2C (and I'm not, which is why I am using this page at all), the items that you place in curly brackets `{}` are very very difficult to identify. Please add an example, and state where on Azure B2C/Azure AD to find each datum. I anticipate spending several hours or even a day or more just trying to figure out a command that you should be able to lead me through in a couple of minutes.

As a general point I find a lot of the microsoft documentation is like this. At the key point where I need the most guidance you assume that I already have the knowledge you are attempting to teach. Please review your pages imagining that you lack prior experience and see if you can complete the task only doing as the help page instructs and without any reliance on your individual knowledge.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d682d4c-86b5-c47e-89a3-3684b2235320
* Version Independent ID: a80e115c-466a-288d-a918-9ef7514f5add
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @simonziegler ...

This is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/18379, which is coming up for work soon. However, examples are present in this topic ...

Record the following information:

* AAD B2C instance (for example, https://contoso.b2clogin.com/, which includes the trailing slash)
* AAD B2C Tenant domain (for example, contoso.onmicrosoft.com)

Record the following information:

* Server API app Application ID (Client ID) (for example, 11111111-1111-1111-1111-111111111111)
* Directory ID (Tenant ID) (for example, 222222222-2222-2222-2222-222222222222)
* AAD Tenant domain (for example, contoso.onmicrosoft.com): The domain is available as the Publisher domain in the Branding blade of the Azure portal for the registered app.

Record the following information:

* App ID URI (for example, https://contoso.onmicrosoft.com/11111111-1111-1111-1111-111111111111, api://11111111-1111-1111-1111-111111111111, or the custom value that you provided)
* Default scope (for example, API.Access)

The *looong* CLI command will eventually appear on a CLI tab, and Visual Studio guidance will be placed on another tab with instructions for using the VS new project UI. It will be easier to use the UI to get each piece of information in the right spot than dealing with the command.

**Comment by simonziegler** [comment]
Thank you. I'll attempt to understand! I appreciate the swift response.

**Comment by simonziegler** [comment]
@guardrex, can I ask if you know of any resource that can tell me how, in a Blazor Server app (not Webassembly) to get hold of the JWT bearer token that I assume is returned from my B2C signupsignin user flow? I need to add this to my http headers and just cannot work out where to find the token. Thanks.

**Comment by guardrex** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/blazor/server/additional-scenarios?view=aspnetcore-3.1#pass-tokens-to-a-blazor-server-app

**Comment by simonziegler** [comment]
I think I'm nearly getting there, but again the docs have unexplained references that will take a lot of guesswork:

```
using Microsoft.AspNetCore.Authentication.OpenIdConnect;

...

services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
{
    options.ResponseType = "code";
    options.SaveTokens = true;

    options.Scope.Add("offline_access");
    options.Scope.Add("{SCOPE}");
    options.Resource = "{RESOURCE}";
});
```

What are `SCOPE` and `RESOURCE` please?

**Comment by guardrex** [comment]
* Scope is a permission granted for a request.
* Resource is the URI of the web API that receives the requests.

For example with oAuth v1.0, a Graph API scope might be for something like `offline_access` or `Directory.Read`, and the resource would be `https://graph.microsoft.com`. For v2.0 endpoints, the `Resource` goes away because the scope contains the resource and the permission in v2.0.

Side Note: MS and the industry is in a transitional state right now moving from oAuth/OIDC 1.0 to 2.0. All of the Identity platform docs, Azure docs and the Azure portal and most of the examples, sample code, and packages have moved to 2.0 and MS's new Identity Platform 2.0. Here in the ASP.NET Core docs, we're still on 1.0 or transitioning/adding coverage for 2.0. The packages for Blazor apps are built around 1.0. 2.0 is backwards compat, which is why we have [content on using 2.0 endpoints with the current packages](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#use-open-id-connect-oidc-v20-endpoints). For more info on the transition, see [Why update to Microsoft identity platform (v2.0)?](https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/azure-ad-endpoint-comparison). We *should* (AFAIK) 🤞 be moving to new packages built around 2.0 for ASP.NET 5.0.

> docs have unexplained references that will take a lot of guesswork

I feel your pain because I face the same problem on a regular basis. Although I try to cross-link to helpful resources and the API docs, a given *advanced* topic these days, which is what this topic is, will contain unexplained methodology and terminology. One ends up having to read other topics on fundamental subjects before such a topic will make full sense. It's even worse here because we can't cover all of the Azure portal UI gestures and behaviors. I don't think it's possible to jump directly into a topic like this and have it go very smoothly.

Check out the following doc sets. I know they're rather *large*, but that's just the nature of tech these days. There's *a lot* of platforms, features, UIs, scenarios, etc.

* [ASP.NET Core Security node of topics](https://docs.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-3.1)
* [Microsoft identity platform documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/)
* [Azure AD docs](https://docs.microsoft.com/en-us/azure/active-directory/)

**Comment by simonziegler** [comment]
Thanks. Your'e going above and beyond here. I really appreciate the help on what you rightly point out is a brutally complex subject for a new entrant.

**Comment by simonziegler** [comment]
Hi @guardrex, I seem to be getting closer but now fall foul of the following:

`Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: IDX21336: Both 'id_token' and 'access_token' should be present in OpenIdConnectProtocolValidationContext.ProtocolMessage received from Token Endpoint. Cannot process the message.`

I believe you might now have the answer via https://github.com/dotnet/aspnetcore/issues/20002#issuecomment-621446595. Would you mind letting me know if you do? Thanks!

**Comment by guardrex** [comment]
I don't know ... I don't recall why I wrote that. It was probably a temporary error that I hit while testing.

According to the remark made by Ash Tappin, you might try working with the scope that you're using and see if that's to blame. Apparently, they had to add the client id to the scope to get it to work. For example, the scope name might be `API.Access`, but the scope provided might work if it includes the app's client id (`11111111-1111-1111-1111-111111111111/API.Access`).

**Comment by simonziegler** [comment]
Thanks. I'll have a go.

**Comment by simonziegler** [comment]
Hey @guardrex manu thanks for your assistance. I finally managed to get my access token and use it to a protected web api (ASP.NET). The next challenge is to get a refresh Yoel. And work out how to use that. Again the docs confuse me. Do you have any good pointers? Presently I can even get the refresh token from B2C. Tx, Simon

**Comment by guardrex** [comment]
Refresh token flow isn't supported for Blazor WebAssembly apps on the grounds that it's a security risk. The recommended pattern is that the Blazor WebAssembly app makes a request to a server API app and the server API app keeps and uses refresh tokens with some other APIs that need to be accessed with token refresh. The refresh token is never sent down to and used by the client-side Blazor WebAssembly app ... that's a safe pattern to follow, so it's the only one supported by the product unit. We have some coverage on it here ...

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#make-api-calls-from-the-client-to-the-server-api-in-order-to-call-third-party-apis

btw -- side note -- There's been some additional discussion today surrounding devs having trouble with their apps working after following the documented approaches but **_they're NOT clearing lingering cookies between their test runs_**. Idk if we discussed it earlier :point_up:, but consider following the advice in the *Troubleshooting* section of any of these docs where it explains how to set up VS to start a fresh inprivate/incognito browser session **_for every single run_**. The only downside is that you have to log a test user in every run, but that's ok. Lingering cookies are frustrating the heck out of devs. I'm going to elevate the coverage on it in these topics to make it more clear to everyone on the next round of updates.

**Comment by simonziegler** [comment]
Thanks @guardrex, I wasn't aware of the potential security issue. The pattern suggested in your link ("Make API calls from the client to the server API in order to call third-party APIs" ) makes a lot of sense and I'll iterate towards this. I can see this being a long and bumpy road! Do you know if there are any samples around that might give me a head start? I'm presently using Blazor Server but intend to migrate to Webassembly at some point after AOT arrives, so following the safe pattern from the start is the obvious way to go.

Regarding clearing cookies, I'll update my setup, however I don't think this is an issue for me, because I find that I need to log in each debugging run, and am comfortable that this is the right thing to do.

**Comment by guardrex** [comment]
> that this will all change when Microsoft Identity Web is released

Possibly ... I'm not sure how much churn there will be. I suspect that we'll see some preview bits for 5.0 with updated approaches in a few months.

> Do you know if there are any samples around

There's no sample for a secure web API that calls another secure web API. The intermediate API between the WASM app and the other API would just be using normal ASP.NET Core security, so all of the normal ASP.NET Core security docs apply. If we get enough feedback for it, I'm sure we'll build something.
