### ISSUE TITLE
Cannot get sample app to pull secrets from key vault

### ISSUE THREAD

**Issue by SB-o-matic** [dotnet/AspNetCore.Docs#18748]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by SB-o-matic** [comment]
Hello,

I am not a developer. I am an Azure AD admin and I am currently learning .Net core so I can assist developers looking to protect APIs with Azure AD. I have populated the appsettings.json with the required parameters. However, when I run the app, it doesn't show values from the key vault. I have attached output.
1. App registration created and cert uploaded
2. Key Vault created and access policy added giving Get & List permission to service principal
Not sure what else I am missing. 
Please help.
![KV](https://user-images.githubusercontent.com/44109318/84331776-bc1d6d80-ab50-11ea-819b-8a3429079bf9.PNG)

**Comment by Rick-Anderson** [comment]
Can you get https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-cli working?

**Comment by guardrex** [comment]
I still have the sample app locally ... ran it ... and ...

<img width="594" alt="Capture" src="https://user-images.githubusercontent.com/1622880/84335017-73b67d80-ab59-11ea-84b6-d58f0bafd90c.PNG">

... it still works ok. I did need to change one minor thing. I stored my cert for the `LocalMachine`, so I needed to get it from there. That would be obvious tho to a dev running the sample, as it would throw when it didn't find the cert on the machine.

It's likely going to be a configuration problem on the Azure side or between Azure and the app. If you institute logging in the app ...

* [Logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1)
* [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1#troubleshoot-on-azure-app-service)

... you should be able to get an error message from Azure Key Vault.

Otherwise, you would just need to re-walk the steps here carefully and make sure everything is wired up correctly. Don't forget that this app has to be run in the Production environment or else it doesn't actually try to get the secret values from Azure Key Vault. If you want to do a quick flip on that then just change ...

```csharp
if (context.HostingEnvironment.IsProduction())
```

... to ...

```csharp
if (context.HostingEnvironment.IsDevelopment())
```

... in *Program.cs*.

btw @Rick-Anderson --- They expanded the portal for this scenario. These commands that the topic uses to set the secrets ... those steps can be done right in the portal now. When we wrote this topic in the ancient days of ASP.NET Core 👴 (*a year or two ago* :smile:), that wasn't a portal feature. I think we're probably too busy to fix it up to use that process (I know I am. 🏃😅), and the current commands *should still work* 🤞.

**Comment by guardrex** [comment]
@SB-o-matic, I think this is going to turn out to be a configuration issue given that the sample app runs. If you don't get a helpful error message from Azure via logging, you'll need to walk the topic steps again (and perhaps access Azure docs on Key Vault) and see if you can determine where the problem lies. 

The only change that I'm aware of is that you're not strictly required to use the Azure CLI any longer to set the secrets in Azure. You can do that in the portal now with new UI that Azure didn't have when the topic was written. However, I expect those Azure CLI commands still work if you want to use them.

We don't have the staffing to provide product support, so we can't take further action unless/until we know exactly what the problem is in a topic like this. I'm going to close this and cross-link the support channels we generally recommend if you have questions ...

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)

We can re-open this issue when you find out what the problem turns out to be if it's actionable for the doc. I've added a few *gotchas* from prior devs to the [topic's troubleshooting guidance](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1#troubleshoot) to help steer devs in the right direction when they hit problems. If you come up with a **new _gotcha_** :boom: that we can call out there, I'll re-open this and add it to the list.
