### ISSUE TITLE
Shorten all paths to under 190 characters

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#18749]
Details in  https://github.com/dotnet/AspNetDocs/issues/403

**Comment by wadepickett** [comment]
Checked the entire repo.  We are already good (barely) for all .md and .png file path lengths.  

This is the very longest one we have at 187 characters:
https://github.com/dotnet/AspNetCore.Docs/tree/live/aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/3.0/TodoApi.Swashbuckle/sample_images/data-annotations-response-types.png

We exclude the first 26 characters of "https://github.com/dotnet/" from the character count requirement.  

The ASPNETDOCS repo however has a lot of hits.  Closing this issue since the AspNetCore.Docs repo checks out and is fine.

**Comment by Rick-Anderson** [comment]
This is the wrong  repo. I just created this issue because we track work here and not the other repo. The real issue is  in dotnet/AspNetDocs#403

**Comment by wadepickett** [comment]
Loc team fixed on Localization process side since the shortened path issue would restrict every repo published across docs.microsoft.com and require many to rename/touch a lot of directories/file names for content and dependencies including the code samples.
