### ISSUE TITLE
Blazor WA Security model

### ISSUE THREAD

**Issue by markiemarkus** [dotnet/AspNetCore.Docs#18763]
What is the correct approach when using a Blazor WA app for security and setting the authorization views

I have a .net core web API which returns the 'ApplicationUsers' - User class + Roles associated to each.
User1 - readonly
User2 - isadmin

My blazor WA app can query the roles, how do I layer them into the AuthorizeView and then use the different custom policies

**Comment by guardrex** [comment]
Hello @markiemarkus ... We have a node of topics pertaining to Blazor WebAssembly security. See ...

https://docs.microsoft.com/aspnet/core/security/blazor/webassembly/

... but also back out to the main Blazor security node because there's general info there that applies to both Blazor hosting models ...

https://docs.microsoft.com/aspnet/core/security/blazor/

**Comment by guardrex** [comment]
oh ... and I should mention that we don't provide product support. If you need assistance with implementation or have scenario-specific questions, we recommend the usual support channels ...

* [Stack Overflow](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Blazor)
