### ISSUE TITLE
Link to Use, Run, and Map has changed

### ISSUE THREAD

**Issue by serpent5** [dotnet/AspNetCore.Docs#18811]
This topic links to _Use, Run, and Map_ in the Middlware topic, but that section was renamed a while back to _Branch the middleware pipeline_, so it doesn't resolve correctly.

I can fix this along with #18785.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This is happening repeatedly (for topics that I wrote) because I don't use named anchors because they don't conform to HTML5 (and I have an accessibility concern for link lists generated from a page).

* The build system is either failing to find broken bookmarks, or authors aren't checking the build report.
* Authors aren't performing a find-'n-replace when changing section headings.

*I've mistakenly done both of those!* However, I think I'm on spec.

Generally, the guidance is **_not_** to use named hyperlinks for bookmarking ...

> Adding explicit anchor links using the <a> HTML tag isn't required or recommended, except in hub and landing pages. Instead, use the auto-generated bookmarks as described in bookmark links.

https://docs.microsoft.com/en-us/contribute/how-to-write-links#explicit-anchor-links

The [bookmark links guidance](https://docs.microsoft.com/en-us/contribute/how-to-write-links#bookmark-links) is to use the HTML5-friendly (possibly accessibility-friendly) automatic `id` of the section heading.

**Comment by guardrex** [comment]
@serpent5 ... I marked this in-progress for you for your PR. Thanks **_again_** for everything ur doing to help out around here!

**Comment by serpent5** [comment]
Thanks @guardrex. I keep a list of issues I've said I'll look at as bookmarks in the browser, but, yeah, it would be awesome if things could be assigned like that. I can see why it's not OK to assign issues to a rando on the Internet, though. 😆 

Thanks for the information about the links - I hadn't seen that guidance before. I'll be sure to do the find-'n-replace thing, too. It looks like I actually broke this one myself, when I did some work in that topic a few months back.

Also thanks to you for a lot of indirect help in the docs in general. I often look at work you've done when I'm trying to decide how best to do something and I _may_ have even borrowed some wording here or there... 😇

**Comment by guardrex** [comment]
We can't assign because the contributions are on a **_volunteer_** basis. Using GH's issue assignment feature could be misconstrued as a literal assignment. It also probably puts too much pressure on a community member. I was in the same situation before Aquent/MS picked me up. I worked many issues over several months unassigned on a *verbal handshake* 🤝 that I'd take care of them.

**Comment by Rick-Anderson** [comment]
WE could make a `Serpent5-FYI` label to point out issues.

**Comment by serpent5** [comment]
> It also probably places too much pressure on a community member.

Sure, that does make sense. I didn't really think about the pressure side of it...

Can either of you help me with something, please? In [http-modules.md](https://raw.githubusercontent.com/dotnet/AspNetCore.Docs/master/aspnetcore/migration/http-modules.md), there's this:

```
* [Pipeline branching](xref:fundamentals/middleware/index#use-run-and-map)...
```

That topic isn't versioned at all, so changing the `#` there would break it for 2.1, at least. How should I handle that? All I can come up with is using a moniker for the bullet with `< 3.0` and `>= 3.0` versions to make sure it's the correct link.

**Comment by serpent5** [comment]
> 
> 
> WE could make a `Serpent5-FYI` label to point out issues.

Ooh a label just for me. ✨ 

I'm OK with the bookmark system for now, really. I went through everything I was mentioned in recently and built a list from that. Now I just drag-drop it onto the folder and it's fine. Although `Good serpent5 issue` or `serpent5 wanted` both have a nice ring to them 🔔 .

**Comment by Rick-Anderson** [comment]
If there's only one place that differs, use 

```
::: moniker range=">= aspnetcore-3.0"

// 3.1 stuff
::: moniker-end
::: moniker range="< aspnetcore-3.0"
/// 2.2
::: moniker-end
```

You don't need full file versioning

I also like to drop in
` <a name="myH2"></a>`

and use that. In 5.x I'll use
` <a name="myH2-5"></a>`

**Comment by serpent5** [comment]
Ok, thanks! I'll go with the monikers for now. It looks like the guidance Luke pointed out doesn't like those explicit anchors as much, so I'll _try_ and keep everyone happy.

**Comment by guardrex** [comment]
> I'll try and keep everyone happy

Vegas odds have you at 100-1 ......... **_against!_** 😁

**Comment by Rick-Anderson** [comment]
I created label:GII
![image](https://user-images.githubusercontent.com/3605364/84711384-e8930a00-af01-11ea-9d66-4935a54b82cb.png)
