### ISSUE TITLE
Incomplete tutorial

### ISSUE THREAD

**Issue by samira-ouraga** [dotnet/AspNetCore.Docs#18840]
The tutorial does not specify that we need to install SQLite or SQLServer to continue. Now I have this error when I run these commands:
dotnet ef migrations add InitialCreate
dotnet ef database update

Error:
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You don't need to install SQL Server. 

Try creating a new project with authentication and see if you get the same error. Are you using Visual Studio?

**Comment by gmriggs** [comment]
For https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio, on the 'Update-Database' step, I also had this same error (VS 2019 and .NET 5). It turned out to be unrelated to the tutorial though

I was able to resolve it with this:

https://stackoverflow.com/questions/40022742/localdb-parent-instance-version-invalid-mssql13e-localdb

From a command prompt, 'sqllocaldb info MSSQLLocalDB' was reporting:

Printing of LocalDB instance "MSSQLLocalDB" information failed because of the following error:
Unexpected error occurred inside a LocalDB instance API method call. See the Windows Application event log for error details.

Event Viewer > Windows Logs > Application was showing this:

LocalDB parent instance version is invalid: MSSQL12E.LOCALDB
Source: SQLLocalDB 13.0

Supposedly an error from a localdb upgrade, although I have never used localdb before

**Comment by Rick-Anderson** [comment]
Thanks for the update.
