### ISSUE TITLE
Topic links to itself

### ISSUE THREAD

**Issue by serpent5** [dotnet/AspNetCore.Docs#18888]
In the final link of the first section, the topic links back to itself, but this doesn't appear to be the intent. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8795bcc-45ef-7edc-4657-fca867c8ff81
* Version Independent ID: d0b1a040-5dae-8233-dbee-c5837a0c231d
* Content: [ASP.NET Core Blazor logging](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/fundamentals/logging.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/logging.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
No ... definitely not. :smile: It's just due to content moving around a bit on the ToC shakeup. We'll probably spot a few more of these over the next few weeks. It was worth it tho ... we're in a better spot now with this section of the ToC. Organization is improved, and these topics are easier to maintain (i.e., filtering searches on a single folder in the repo is a breeze over using a long location filter string).

I'll fix this up right now. I'm between coats of paint on my Jeep hood. *Hum ... there's something familiar about this hood logo!*

![hood](https://user-images.githubusercontent.com/1622880/85233046-3eb3f180-b3c9-11ea-9f7d-65e985b2f07d.png)
