### ISSUE TITLE
Out of box AAD B2C not grabbing user.identity.name

### ISSUE THREAD

**Issue by DatenThielt** [dotnet/AspNetCore.Docs#19019]
I have been following along the documentation for setting up a Blazor server app with AAD B2C found at the Linked article which also then points to the below link for AAD B2C

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-3.1

This works to a point,  You get the login and user creation dialog which work,  and you can log in, be returned to the page and are shown as Authorized, however @context.User.Identity.Name Is null

This issue is very much like the one reported here #17598 

however that issue was Blazor WASM instead of Blazor Server,  Trying fixed from that post did not resolve the issue.

This could potentially be related to something missing in startup?  Unfortunately I am too new to AAD B2C to be able to figure out the solution to provide here.

Visual Studio Preview: 16.7.0 3.1
Blazor Server App
.net core 3.1

If any additional information is needed please let me know

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6032832-e645-24a1-583e-7b1898019fd1
* Version Independent ID: 8da62490-e36f-8f38-8f06-d5d6bceaafde
* Content: [Secure ASP.NET Core Blazor Server apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/server/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/server/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
You can try what I placed in the WASM with B2C topic ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#useridentityname

... which is related to the options config that you see in the topic that you linked at ...

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-3.1#configure-the-underlying-openidconnectoptionsjwtbearercookie-options

However if that approach doesn't work, re-open a new issue from the bottom of the topic that you linked at ...

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-3.1

... because we (probably) won't be duplicating Blazor Server config in the Blazor docs node because such apps are really like ASP.NET Core apps in terms of their security configuration and setup. We just don't want a lot of double-coverage in the Blazor node.

btw - You also can check for (perhaps cross-linked) Azure docs on this, which are in a different doc set. IIRC, they have at least one ASP.NET Core tutorial. The only potential gotcha there is that their docs, examples, and tutorials have moved on to oAuth 2.0, and the packages and framework here are still on 1.0. That's going to be resolved fairly soon over here. It's being worked on right now.
