### ISSUE TITLE
List of Dos under "Avoid Blocking Calls" is missing suggestion

### ISSUE THREAD

**Issue by darraghjones** [dotnet/AspNetCore.Docs#19037]
Under the heading **Avoid Blocking Calls**, I feel like one of the suggested **Dos** should be:

- Do use Task.Factory.StartNew(..., TaskCreationOptions.LongRunning) to make a synchronus API asynchronous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.1)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mjrousos should I add that?

**Comment by mjrousos** [comment]
This one's tricky. Creating new tasks as LongRunning could help to avoid ThreadPool starvation, but it's very situational. You wouldn't want to use it, for example, if you didn't already have issues with thread pool exhaustion, and you definitely wouldn't want to use it if the task was IO-bound and could be done in an *actually* async way. 

In the past, our recommendation has been to not use LongRunning until you find through performance profiling that you actually need it. I can see how it may come up more often in ASP.NET Core (enough that an argument could be made for proactively using it for long-running, compute-bound tasks), but even in ASP.NET Core, needing LongRunning is often going to just be a symptom of something else being wrong with the app (if everything else is async, the ThreadPool shouldn't be so clogged up that it matters). I guess the bottom line is that the LongRunning pattern may be useful sometimes, but I think it's nuanced enough that I'd rather not recommend it in a doc like this. @stephentoub - do you have an opinion on this? When giving performance best practices for ASP.NET Core, are there cases where we should recommend using `Task.Factory.StartNet(..., TaskCreationOptions.LongRunning)`?

Also, if we ignore the LongRunning case, creating tasks for synchronous work, in general, is not something I'd recommend in a performance doc. It is useful for performing synchronous work concurrently but it doesn't really effect perf (since the same number of threads are still in use) and could accidentally encourage the wrong behavior if developers start using that pattern for tasks that could have been using async alternatives.

**Comment by stephentoub** [comment]
We should not add that as a recommendation.  LongRunning is essentially equivalent to `new Thread(...).Start()` and should be used exceedingly sparingly.

**Comment by darraghjones** [comment]
I expect there are many existing APIs which are I/O bound, but synchronous.

Assuming the below was a third party library, which you are unable to change, how would you call an API such as this, while avoiding thread starvation?

```
    public class StockPriceWebService
    {
        decimal GetStockPrice(string stockSymbol)
        {
            var price = new HttpClient().GetStringAsync($"http://...{stockSymbol}").ConfigureAwait(false).GetAwaiter().GetResult();
            return Decimal.Parse(price);
        }
    }

```

In my experience, `Task.Factory.StartNew(..., LongRunning)` is the only way I could find.

**Comment by stephentoub** [comment]
> Assuming the below was a third party library, which you are unable to change, how would you call an API such as this, while avoiding thread starvation?

Get the library to change its implementation, or don't use it.  I realize that's easier said than done, but no matter how you invoke this, it's going to result in inefficiencies.  Using `LongRunning` isn't a best practice here; it's a band-aid that will end up having its own problems.  For example, if you wanted to download 10,000 stock prices and did `Task.WhenAll(from stock in stocks select Task.Factory.StartNew(() => GetStockPrice(stock), LongRunning))`, that's going to create 10,000 threads... or at least try to... most likely either failing outright or causing massive problems for the server.  In one off situations, if you find that LongRunning in such a situation works for your needs and is the lesser-evil, then by all means, go ahead and use it, but it's not something we should be blanketly recommending as a best practice.
