### ISSUE TITLE
How does one pass flags to protoc?

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/AspNetCore.Docs#19164]
[Enter feedback here]
I.e. to use optional parameters in protobuf it requires --experimental_allow_proto3_optional passed to protoc.  But the documentation doesn't specify how you can pass this parameter and use this vital functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a7d945-e49f-d76f-a5fd-43ac81dbef80
* Version Independent ID: b5b132db-9667-d5a9-8671-002cb2c0277f
* Content: [Manage Protobuf references with dotnet-grpc](https://docs.microsoft.com/en-us/aspnet/core/grpc/dotnet-grpc?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/dotnet-grpc.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/dotnet-grpc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by JunTaoLuo** [comment]
@JohnGalt1717 There are no supported ways of specifying options that are used by protoc due to limitations of the Grpc.Tools implementation. However, there are ways to work around this with the `_GrpcOutputOptions` and `_OutputOptions` metadata on the `Protobuf` itemgroup. This is not a supported workflow and hence why they have the `_` prefix but these two metadata are passed to protoc [here](https://github.com/grpc/grpc/blob/88cd5b0881a6af3d27db17d0717689bd7bbddafe/src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.targets#L287-L290). `_GrpcOutputOptions` is passed to the grpc code generation logic while `_OutputOptions` is passed to the protobuf code generation logic so you'll need to figure out which one of these experimental_allow_proto3_optional applies to.

As for documentation, since this is an unsupported workflow, we probably won't add any documentation for this.

**Comment by JohnGalt1717** [comment]
Ok, but I've tried it on <ItemGroup> and <Protobuf> in my csproj and obth throw an error saying that it is unrecognized.
