### ISSUE TITLE
using statements in client section not correct

### ISSUE THREAD

**Issue by allenh100** [dotnet/AspNetCore.Docs#19212]
The using statement "using GrpcGreeter" is incorrect.  To fix, you can either:
1. update the greet.proto copied from the server project to the client project to reflect the new namespace "GrpcGreeter"
OR
2. change using to reference the namespace in greet.proto to "using GrpcService".

1 is probably the best fix

Update/correction:  The target topic here seems to be:  
[Tutorial: Create a gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio) 
The initial topic this was attached to, [Introduction to gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.1), does not mention "using GrpcGreeter".  - Wade

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db2d29c-ebfd-9c79-4b08-61fc5192f3c3
* Version Independent ID: 048d1977-93aa-f28a-60ec-6806dec3f70a
* Content: [Introduction to gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by wadepickett** [comment]
@allenh100, thanks for taking the time to write up this issue!    The topic this issue is attached to is [Introduction to gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.1), which does not refer to "using GrpcGreeter"

I think you might have meant for the issue to be attached to this tutorial topic?  [Tutorial: Create a gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio).  I will assume this is the topic to fix unless I hear otherwise.  Thanks again.
