### ISSUE TITLE
AccessToken null when TokenProvider resolved

### ISSUE THREAD

**Issue by FrederikNygart** [dotnet/AspNetCore.Docs#19225]
In the example you're adding TokenProvider as a scoped service. Consequentially it will create a new instance of the TokenProvider per request made to the WebApp. Wouldn't that make the tokens reset for every new request?

I have tested the example locally, and  i get the token in App so that's all well and good. But when I resolve the service in a constructor, the tokens are now null, as it is a new instance of the TokenProvider - that is atleast what i expect is happening.

Is this intentional or am I overlooking something?

PS.
I can make it work by adding TokenProvider as a singleton, but that would mean that the token state is the same for all requests, and that is probably not desirable?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8acbbf-c9d4-7041-c1a7-ec9ce8f0981b
* Version Independent ID: c98be365-408d-7ee6-cb74-14c44d01b0b8
* Content: [ASP.NET Core Blazor Server additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-3.1#pass-tokens-to-a-blazor-server-app)
* Content Source: [aspnetcore/blazor/security/server/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/server/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @FrederikNygart ... It's intentional (https://github.com/javiercn/blazor-server-aad-sample). The tokens are assigned via `HttpContext` only when `_Host.cshtml` code runs (i.e., this approach is about getting the tokens for use in components). Did you try just getting the token(s) directly from `HttpContext.GetTokenAsync("access_token")` (assembly: `Microsoft.AspNetCore.Authentication`, [GetTokenAsync](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.authentication.authenticationtokenextensions.gettokenasync)) in the controller (and probably with [`IHttpContextAccessor`](https://docs.microsoft.com/aspnet/core/fundamentals/http-context))? If you need further support, we recommend accessing a support channel because we just work on docs here and don't have the staffing to provide general support ...

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)

**Comment by FrederikNygart** [comment]
Hi @guardrex 

Thank you for the quick reply. This is meant as feedback, but i needed to clarify the above.

Based on your response, the example in the documentation will not work end to end, as the accesstoken returned is null when resolving the tokenprovider:

`public class WeatherForecastService
{
    private readonly TokenProvider _store;

    public WeatherForecastService(IHttpClientFactory clientFactory, 
        TokenProvider tokenProvider)
    {
        Client = clientFactory.CreateClient();
        _store = tokenProvider;
    }

    public HttpClient Client { get; }

    public async Task<WeatherForecast[]> GetForecastAsync(DateTime startDate)
    {
        var token = _store.AccessToken;
        var request = new HttpRequestMessage(HttpMethod.Get, 
            "https://localhost:5003/WeatherForecast");
        request.Headers.Add("Authorization", $"Bearer {token}");
        var response = await Client.SendAsync(request);
        response.EnsureSuccessStatusCode();

        return await response.Content.ReadAsAsync<WeatherForecast[]>();
    }
}`

If i have misunderstood anything please let me know.

Best,
Frederik

**Comment by guardrex** [comment]
Sorry ... I didn't realize that you were asking about `WeatherForecastService`. I thought you were asking about some general controller ctor in the MVC part of the app.

Javier registers the `WeatherForecastService` service as transient and the `TokenProvider` as scoped ...

* https://github.com/javiercn/blazor-server-aad-sample/blob/master/BlazorServerAuthWithAzureActiveDirectory/Startup.cs#L54
* https://github.com/javiercn/blazor-server-aad-sample/blob/master/BlazorServerAuthWithAzureActiveDirectory/Startup.cs#L42

... so I think the topic is correct. When I put *some*&dagger; of the code into a test app, I do get the token in the service ...

<img width="386" alt="Capture" src="https://user-images.githubusercontent.com/1622880/87683638-ef9e7980-c746-11ea-84a2-c559fc2a2f3d.PNG">

&dagger;When I say "some," I mean just when I put the `WeatherForecastService` into the app. I didn't go so far as to actually have a web API set up to return data. Nor have I tried to wire up Javier's sample and run it. I just wanted to see if I was getting the token provided by the service because I do have a sample app that I use for other testing that already had the `TokenProvider` in it ... it was quick and easy to check just that one aspect by dropping the `WeatherForecastService` into the app.

Given that it's working here, this isn't actionable (yet) for any doc changes. You might want to try pulling down Javier's sample first, wiring that up to your auth, and see if you can get that sample app to run. If it works, then compare and see what the difference is to what you're doing in your app. If it doesn't work, then open an engineering issue at https://github.com/dotnet/aspnetcore/issues.

If you need general support, you'd have to ask on a support channel. We're a *very* small team and don't have the staffing to provide general product support. Of course, I **_DO_** want to hear what turned out in the end to cause the problem. If it is something that we can surface in the doc to help devs, that would be great. You can either comment on this issue (I'll re-open it), or you can open a new issue from the bottom of the topic.

**Comment by iofluxdev1** [comment]
Running into the same problem. The token provider values are null when I use DI to inject it into a transient service unless TokenProvider is registered as singleton. The service that is relying on the token provider is a DelegatingHandler that injects the tokens into a HttpClient's headers. I dont want to store this in local storage as others do as that is a security riks.
