### ISSUE TITLE
QueuedHostedService implementation will throw OperationCanceledException

### ISSUE THREAD

**Issue by thorstenmz** [dotnet/AspNetCore.Docs#19253]
The current implementation of ```QueuedHostedService``` will most likely encounter an ```OperationCanceledException``` in the ```var workItem = await TaskQueue.DequeueAsync(stoppingToken);``` line. This exception will not be caught. This in turn means that the logging _"Queued Hosted Service is stopping."_ - and any clean up code! - will not be executed. A finally clause is in order here, I think.

There is a [master issue](https://github.com/dotnet/AspNetCore.Docs/issues/17605) for that page, so if you agree  with my suggestion you might want to add it there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1&tabs=visual-studio#queued-background-tasks-1)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> This exception will not be caught. 
Why not, `catch (Exception ex)` catches all exceptions.

@halter73 please review or suggest a reviewer

The code in question:
```
private async Task BackgroundProcessing(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            var workItem = 
                await TaskQueue.DequeueAsync(stoppingToken);

            try
            {
                await workItem(stoppingToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, 
                    "Error occurred executing {WorkItem}.", nameof(workItem));
            }
        }
    }
```

**Comment by thorstenmz** [comment]
The line ```var workItem = await TaskQueue.DequeueAsync(stoppingToken);``` is not within the try block. Maybe it should got there?

**Comment by halter73** [comment]
Glancing at the quoted code, `BackgroundProcessing` has inconsistent behavior depending on how the `stoppingToken` cancellation is observed.

If the cancellation is observed by `workItem`, and it throws an OperationCanceledException, it will be appropriately logged and swallowed. The while loop will then exit gracefully.

If the cancellation is instead observed by `TaskQueue.DequeueAsync`, the exception won't be swallowed.

I don't think expanding the existing try block is the fix, because the error log wouldn't make sense. Swallowing the exception without a log is probably the right thing to do in this case. It's already possible for the loop to exit gracefully without a log of the cancellation is first observed by the while condition.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
