### ISSUE TITLE
Blazor Webassembly ASP.NET Core Hosted as Windows Service 

### ISSUE THREAD

**Issue by scdehmlow** [dotnet/AspNetCore.Docs#19294]
[EDIT by guardrex to change the metadata]

I had to use `UseContentRoot` with the absolute publish path on the host builder rather than `SetBasePath` on the configuration builder so the Blazor files could be picked up. Is that the best way to do this and is it worth adding to the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @scdehmlow ... I'm going to re-target this for the Blazor doc set. We'll document in Blazor's *Host and Deploy* node overview for this. As for it being the best approach in this scenario, it's certainly sounds good :ear:. We'll need to get engineering to respond, so I'll mark this for triage. After that, *yes* ... it's good to call it out.

**Comment by guardrex** [comment]
It's not clear to me that this *should be a problem* for devs with `UseWindowsService` calling `UseContentRoot` with `AppContext.BaseDirectory` ...

https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetimeHostBuilderExtensions.cs#L49

Devs having a problem with finding paths to assets or with component routing per our ASP.NET Core *Host and deploy* > *Windows Service* doc should open a new issue for the PU ("product unit") to research and respond. I suggest they take a look at this because having to call `UseContentRoot` for this scenario feels hacky to me. They might want to go for a permanent framework fix for this inside of `UseWindowsService` so that devs don't need to find a cryptic mention buried in Blazor docs to make it behave.

Open an issue at: https://github.com/dotnet/aspnetcore/issues
