### ISSUE TITLE
IdentityServer4 Configuration to work with Blazor Standalone & API

### ISSUE THREAD

**Issue by eddiepantoja** [dotnet/AspNetCore.Docs#19316]
There is great documentation on this page but I am am having issues developing a Blazor Standalone app with secure API and IdentityServer4. Marco De Sanctis has an [article](https://medium.com/@marcodesanctis2/securing-blazor-webassembly-with-identity-server-4-ee44aa1687ef) where he covers the topic but it is not updated with the latest releases of Blazor or IdentityServer4.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985b834f-534a-aba6-80a0-d8845adbfc25
* Version Independent ID: d2b5a556-82a4-e939-be68-2357a3d4408f
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @eddiepantoja ... There aren't any current open reports of problems with the topic's guidance. 

> having issues

That isn't specific enough for us to take action here. If you find something specifically wrong (or missing) with the topic's guidance, please do open an issue. Due to our small staff size, we're unable to provide product support. We recommend the usual support channels for assistance ...

* [Stack Overflow](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Blazor)
