### ISSUE TITLE
Application always tries to authenticate

### ISSUE THREAD

**Issue by efonsecab** [dotnet/AspNetCore.Docs#19314]
I finished the tutorial, however, the application is always trying to authenticate as soon as it starts, which does not allow me to have a public section of the website and then authenticate by clicking a Sign Up/Sign In button
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @efonsecab ... I can't explain that behavior, nor are other devs reporting that behavior. It's never been the case here in my own testing. Make sure that you're using a fresh inprivate/incognito browser for **every run**. There's advice in the *Troubleshoot* section of the topic.

We're a tiny team and only work on docs. We don't have the staffing to provide support. We can take a doc bug report if you determine what the cause is and then let us (me) know.

For support, you'd need to contact devs on support channels to get help ...

* [Stack Overflow](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Blazor)

If you think you've found a bug in the framework, you can open an issue for engineering with a minimal repro that shows it ...

https://github.com/dotnet/aspnetcore/issues

**Comment by efonsecab** [comment]
Thanks, from what I found, is that the documentation is not taking in consideration scenarios where you have endpoints which can be invoked anonymously, as soon as the IHttpClient is injected and performas a call, it always requests authentication.

**Comment by guardrex** [comment]
Yes, but don't access a secure resource in `OnInitializedAsync` if you don't want that behavior. Access the resource based on an event triggered by the user that requires the secure resource.

**Comment by guardrex** [comment]
If you need an insecure `HttpClient` for some resources to load without triggering auth, then used a named client.

https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/additional-scenarios#unauthenticated-or-unauthorized-web-api-requests-in-an-app-with-a-secure-default-client
