### ISSUE TITLE
how to set my blazor root url when i deploy it to k8s nginx ingress custom path 

### ISSUE THREAD

**Issue by nocanstillbb** [dotnet/AspNetCore.Docs#19323]
i try seted `<base href="/mypath" > `on _hostcshtml ,
also use `app.useBasePath("/mypath");` on startup.configure method
url Redirector to  `myDomainName/login` when i access `myDomainName/mypath/`  (i use navigateManage.navigateTo(/login)
have any document more detail?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e07aaa4d-4ad4-778f-f74a-60d8f05d9075
* Version Independent ID: c82cf121-831d-75dd-a796-c735aad3b3e9
* Content: [Host and deploy ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @nocanstillbb ... The `<base>` tag should have a trailing slash (`<base href="/mypath/" >`). That's all of the information that we have at this time. If you're still having trouble, we recommend reaching out to devs on support channels ...

* [Stack Overflow](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Blazor)

If you find out what the problem is and we're missing coverage, you can let us know here. With the help of support channels if you can't determine what the problem is, open an issue for engineering at https://github.com/dotnet/aspnetcore/issues.
