### ISSUE TITLE
Build a Blazor todo list app, need to disable HTTPS redirect to view pages

### ISSUE THREAD

**Issue by bensbalancedcode** [dotnet/AspNetCore.Docs#19348]
Following the "Build a Blazor todo list app" tutorial, using VS code, on a box running windows 8.1, viewing 

On step 5:
> Rebuild and run the app. Visit the new Todo page to confirm that the link to the Todo component works.

When I run the app (`dotnet run`) and open the page "http://localhost:5000" my chrome browser (84.0.4147.89) is redirected to "https://localhost:5001" and I get this error:
> This site can’t be reachedThe webpage at https://localhost:5001/ might be temporarily down or it may have moved permanently to a new web address.
ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY

I fixed this by commenting out the line `app.UseHttpsRedirection();` in `Startup.cs` (line 48), which keeps the page on "http://localhost:5000".

I suggest adding that as an instruction or tip. (Can I do that myself? or make a PR? I am new to this documentation style)

I would guess that changing the TLS settings of windows or chrome, or maybe making a self signed cert would let the https site work... but for playing with the new product I stuck with the simple solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bensbalancedcode ... We're going to leave the instruction as it is because the default (and recommendation) is always to run apps secure. If a dev wants to do what you did, that's ok, but we don't want to call that out as a step or note in the doc. This problem is likely related to the cypher suites on the machine, and those are going to break any HTTP2 scenario (probably). Engineering has had a few issues pertaining to that error. See if any of these help ...

https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY+is%3Aclosed

... but make sure that you follow the general advice first to run `dotnet dev-certs https --clean` followed by `dotnet dev-certs https --trust` in a command shell. See if that clears it up before taking further action. https://docs.microsoft.com/aspnet/core/security/enforcing-ssl#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos

If you can't get it resolved using the current (closed) issues and trusting the dev cert, open a new issue with them.
