### ISSUE TITLE
Missing critical information regarding UseStaticFiles with server-side

### ISSUE THREAD

**Issue by Paul-Dempsey** [dotnet/AspNetCore.Docs#19340]
[EDIT by guardrex to replace the scraped content link and remove the metadata]

In order to use a font, I had to extend static files to serve woff/ttf.

```cs
            var provider = new FileExtensionContentTypeProvider();
            provider.Mappings[".ttf"] = "font/ttf";
            provider.Mappings[".woff"] = "font/woff";
            provider.Mappings[".woff2"] = "font/woff2";
            app.UseStaticFiles(new StaticFileOptions
            {
                ContentTypeProvider = provider
            });
```

Turns out that this breaks server-side blazor. After flailing around without a clue as to why my site was dead, other than a cryptic console error about not being able to load 'a resource' (without actually logging what resource that is), I found [this post](https://github.com/dotnet/aspnetcore/issues/9588) that explains why.

There is a critical dependence on using the default UseStaticFiles() in Startup.cs, otherwise you break the serving of _framework.blazor.cs, and it is **absolutetely imperative** that you add an additional call to
```cs
app.UseStaticFiles();
```

The documentation (I started with this page) is missing this vital fact.  The doc for UseStaticFiles(StaticFileOptions) makes no mention of this, either.

**Comment by guardrex** [comment]
Hello @Paul-Dempsey ... Thanks for the note on this. We'll take a look at what/where to cover when this issue is triaged.

Artak, see Javier's remarks at :point_right: https://github.com/dotnet/aspnetcore/issues/9588#issuecomment-505465169

Let's not cover this in the Hosting models overview. That topic isn't meant to hold implementation guidance. Our choices are either of the following:

* New `Static files` topic in the Blazor > Fundamentals node that mirrors how we place our Static Files Middleware coverage in the doc set at large.
* Add a section to the Blazor > Fundamentals > Additional scenarios topic.
