### ISSUE TITLE
"Override configuration" section should be updated?

### ISSUE THREAD

**Issue by bennettfactor** [dotnet/AspNetCore.Docs#19413]
Hi, the section "Override configuration" appears out of date. Is the "UseConfiguration" extension method still the preferred way to configure a web host in ASP.NET Core 3.1? This extension method exists in "Microsoft.AspNetCore.Hosting" which has a latest version of 2.2.7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eafd1b-403a-4aa3-48bc-78fed5b4d05e
* Version Independent ID: f35451f4-7c74-3ada-e969-b769428b94f4
* Content: [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/host/web-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/web-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@bennettfactor Web Host isn't recommended for 3.x apps. Why haven't you embraced the Generic Host?

@Rick-Anderson ... This content was reviewed/approved by Chris back in the day (for 2.x). I doubt that it has changed since then given that they didn't make significant updates to Web Host scenarios since then.

**Comment by bennettfactor** [comment]
Thanks all. Agreed it makes sense for the whole topic to be removed.
