### ISSUE TITLE
What does "Hit breakpoints during app startup." as a debugging scenario mean?

### ISSUE THREAD

**Issue by groogiam** [dotnet/AspNetCore.Docs#19518]
The documentation states that the debugging scenario "Hit breakpoints during app startup." is not supported. This is vague. Could more details be provided here?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@captainsafia to confirm: "During startup" usually means the period before the app is able to process requests, which about coincides with the host being built and run. Therefore, breakpoints in `Program.Main` won't be hit.

**Comment by captainsafia** [comment]
Great question. We're specifically referring to the startup of the debug proxy. This includes breakpoints in Program.Main and also breakpoints in the `OnInitialized` methods of components that are loaded in the first page of the app for example.

**Comment by guardrex** [comment]
Thanks ... I'll clarify it that way in the topic.

**Comment by groogiam** [comment]
Thanks for the additional info. Does startup also include AuthStateProvider logic?

**Comment by guardrex** [comment]
AFAIK based on Safia's remark, the logic might not be hit if it were the first component (specifically, called by the first component) that's requested. After the first request tho, the debug proxy should be running. If you're having a problem with debug in that component after the first component loads, open an issue for engineering, as we only work on docs here ...

https://github.com/dotnet/aspnetcore/issues

Please add a `cc: @guardrex` to your opening comment so that I can follow the discussion and make appropriate doc updates thereafter.
