### ISSUE TITLE
Improve documentation for Microsoft.Extensions.Hosting.Host.CreateDefaultBuilder method

### ISSUE THREAD

**Issue by aannenko** [dotnet/AspNetCore.Docs#19519]
This page describes order of actions done by CreateDefaultBuilder method.
Remarks sections on the [documentation page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.host.createdefaultbuilder?view=dotnet-plat-ext-3.1) for both overloads of this method contain only unordered lists of actions - the actions there are marked with bullet points instead of numbers and their order does not correspond to reality.
Can unordered lists of actions on the documentation page be replaced with ordered and/or the documentation page be complemented with a link to this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @aannenko ... Those API doc comments come from API files in the framework ...

https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L21-L32

Therefore, you would need to open an issue for this on that repo at ...

https://github.com/dotnet/runtime/issues

They would most likely not link to the docs given that our content is less stable than their API comment docs (guessing) but probably prefer to just put the list in order in their API remarks.

Note that they're insanely busy 🏃 over there with 5.0 work, which will run out toward the end of the year. I have a feeling that even if they agree to address it that it would be put off for quite a long time. If you have time to submit a PR to them, you could ask about making the updates. If they agree, you can edit that file and put those lines in order.

I'll close here because this isn't actionable for us on this repo.
