### ISSUE TITLE
Page typo

### ISSUE THREAD

**Issue by DavidBridge** [dotnet/AspNetCore.Docs#19534]
Change 
"anti-request forgery protection"
to
"anti-forgery request protection"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4d39ecf-0465-afd3-2384-aaafe9e8ea79
* Version Independent ID: e9a58581-b565-25eb-49b3-4c93714f0940
* Content: [Overview of ASP.NET Core Security](https://docs.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I agree. cc @serpent5 this should be an easy browser fix.

**Comment by serpent5** [comment]
This one affects the ToC, too.

I think it'd be better as _XSRF/CSRF prevention_ ([inspired by OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html)). CORS is used in the same sentence too, so I think the _XSRF/CSRF_ acronym is OK to use here.

I think the ToC item should be _Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks_. This would take it on to two lines, but the _EU General Data Protection Regulation (GDPR) support_ link from just above already does this, so that might be OK.
