### ISSUE TITLE
Serverside validation

### ISSUE THREAD

**Issue by bessobesso** [dotnet/AspNetCore.Docs#19554]
What if client calls respository controller lets say "StrashipController" without calling "StarshipValidationController"? In that way client can bypass validation? Or is "StarshipValidationController" supposed to call repository methodds(add/update model) too ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1#business-logic-validation)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bessobesso ...

Doesn't your repository controller perform model validation? It's been a while since I've used that pattern; but IIRC, you would be fine calling your repository controller directly. Whatever pattern used, just make sure that all client-side validation is performed server-side. Client-side validation can **_always_** be bypassed.

btw - We don't document the repository pattern ... anywhere really ... it was a high level management decision years ago to leave that pattern to external (mostly 3rd party) docs. Therefore, this particular subject isn't actionable for the doc.
