### ISSUE TITLE
Blazor roles and groups authn in the WASM server API app (Azure AD Hosted)

### ISSUE THREAD

**Issue by swannet** [dotnet/AspNetCore.Docs#19573]
Hi,

After the documentation issue (https://github.com/dotnet/AspNetCore.Docs/issues/19304). I got the roles and groups correctly in the user-claims (setup as https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-3.1). 

Authorization works fine in the web app. I can call the server API app (due the API permission and scope) but I can't get the groups and roles as claim in the server API app to authorize the user that calls the API.

Maybe I'm missing something, but I can't get it to work... Is it possible to document a a bit more for this usecase?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 217bc7a2-94db-e23b-9e74-7ad48b884462
* Version Independent ID: 071763aa-0173-af10-9634-9c50a4d5868b
* Content: [ASP.NET Core Blazor WebAssembly with Azure Active Directory groups and roles](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @swannet ... I'll look into this as soon as I can. We're busy with .NET 5 and other work right now. I'll try to look at this sometime this week. In the meantime if you figure it out, please post back on this issue what the problem was.

**Comment by guardrex** [comment]
Ok ... back. So ...

I searched engineering issues, and I didn't see anything on this subject. Azure docs imply that with the implicit auth flow that one ... "probably" is the word that I think they used ... "probably" needs to call Graph API.

I know that you can make a Graph API call **_in the Server app_**, get a user's roles/groups for claims, and then have policies set based on the claims. **_What a pain tho, right?!!_** :smile: lol

I tried an approach looking at Azure AD docs where you specify `optionalClaims` in the app's manifest trying to get Azure AD to place a claim into the access token (for example, `groups`) ...

```json
"optionalClaims": {
  "idToken": [],
  "accessToken": [
    {
      "name": "groups",
      "source": null,
      "essential": false,
      "additionalProperties": []
    }
  ],
  "saml2Token": []
},
```

Alas, it didn't work. :cry:

I'll leave this on the issue on the Blazor.Docs project for triage so that Artak can take a look at it.

The question is ...... For a hosted Blazor app with Azure AD, is the only way for the **_Server_** app to get the user's roles and groups via its own Graph API call? ... or is there a way to get those claims set up in the **_access token_** in a more automatic way so that the *Server* app receives them as claims and then the *Server* app merely needs one or more policies set up?

**Comment by guardrex** [comment]
I did a bit more research on this today: Various remarks around the Net indicate that implicit flow OAuth 2.0 doesn't support the `groups` claim in access tokens. I see devs in various places having their server API app call Graph API in `OpenIdConnectOptions` > `OnTokenValidated` and setting user claims that way. Then, policies would make quick work of authorizing controllers in the app.

I'll hack around with it in my test app and report back.

**Comment by guardrex** [comment]
@jmprieur ... Do you have a few minutes to take a look at my ADAL v1.0 on-behalf-of approach for Graph API via a web API backend in a hosted Blazor solution? ... or can you suggest someone who might have a few minutes to take a look at this?

This is just to tide us over to .NET 5 GA. I'll have the new Blazor templates with Identity v2.0 API and packages worked up for the release (*I hope*) by mid-October in new hosted Blazor WASM security topics. What I'm working on here is for the current coverage, which is all based on Identity v1.0.

Everything is in just one comment on this issue at :point_up: ...

https://github.com/dotnet/AspNetCore.Docs/issues/19573#issuecomment-678442702

... and it follows the MS examples fairly closely. It seems to run well.

One thing that doesn't match up to MS examples is that I don't attempt to acquire a token silently. I do the following ...

1. Grab the `upn` from the JWT that arrives to the web API ...

   ```csharp
   var accessToken = context.SecurityToken as JwtSecurityToken;
   var upn = accessToken.Claims.FirstOrDefault(x => x.Type == "upn")?.Value;
   ```

1. Use the `upn` for my user assertion:

   ```csharp
   var userAssertion = new UserAssertion(accessToken.RawData, "urn:ietf:params:oauth:grant-type:jwt-bearer", upn);
   ```

   ... and my Graph API call ...

   ```csharp
   userDefinedRoles = await graphClient.Users[upn].AppRoleAssignments.Request().GetAsync();
   ```

1. If anything fails ... `AdalException`, `ServiceException`, etc. ... the code merely fails to provide a valid claim, thus the anthn policy fails and the web API controller is inaccessible with the calling app getting back a 403.

If the approach is a 💩 **_Rex Code Smell_**:tm: 👃😄, then I'll need a tip on the *correct* approach. Attempting to acquire a token silently first doesn't quite make sense to me for this scenario (*yet* ... I might be missing a critical concept on that point). It seems to make more sense to just attempt token acquisition on behalf of the user. If it fails ... 403 back ... if it succeeds ... let the web API run and return the result. Besides all of that, when I tried acquiring a token silently, it always threw :boom: (but perhaps my code was bad).

The whole process is laid out here ...

https://github.com/dotnet/AspNetCore.Docs/issues/19573#issuecomment-678442702

**Comment by jmprieur** [comment]
@swannet 
2 things:
- ADAL OBO does already acquire the token silently. If you get an AdaUiRequiredException, this means that the tenant admin needs to provide admin consent for the Web API to call the downstream API (as API cannot interact with the user)
- You should not need to provide the upn, to my knowledge

What is the exact exception?

However: ADAL is being deprecated and Microsoft Identity asks every first party partner to move to MSAL and MIcrosoft Graph. See Alex Simon's blog: 
https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363

So I would really not invest in any article or code sample on ADAL at that point.

**Comment by swannet** [comment]
@jmprieur 

Thanks for the headsup. I can understand it would be better to go for the MSAL and Graph API approach, I followed the guide https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1 for .NET core 3.1 which uses the "Microsoft.AspNetCore.Authentication.AzureAD.UI" package for the backend (ServerAPI) instead of the MSAL approach. The ClientApp is using "Microsoft.Authentication.WebAssembly.Msal"

Correct my if I'm wrong but is your suggestion to use a MSAL approach for the ServerAPI too? If so, is it just as easy as change the packages and setup the code just like the ClientApp project? And will the token be accepted by the ServerAPI that way?

**Comment by guardrex** [comment]
Sorry @swannet ... Don't mean to step on your question. Let me interject in passing ...

>  that the tenant admin needs to provide admin consent for the Web API to call the downstream API (as API cannot interact with the user) ... You should not need to provide the upn, to my knowledge

Thanks ... it seems then that my code was bad in the silent token acquisition approach. I'll try again.

> every first party partner to move to MSAL and MIcrosoft Graph

MSAL relies on Identity v2.0 packages and API, which is still in preview ...

> For ASP.NET Core web apps and web APIs, MSAL.NET is encapsulated in a higher level library named Microsoft.Identity.Web

The goal of this approach is to cover an end-to-end approach without the use of preview packages. Support for ADAL runs to 2022.

**_Yes tho_** on coverage of MSAL with Identity v2.0 for .NET 5. That's the plan. New docs will cover the use of the new templates, new API, and new packages.

**Comment by guardrex** [comment]
I may have an answer as to why silent token acquisition fails on the first pass and why the silent token call is there at all. Until a token is obtained on behalf of the user the first time, there's no token in the cache for silent token acquisition to occur (imo, not well covered by the docs I was looking at, but it's probably in other docs that I didn't see). Therefore, silent token acquisition should be implemented for *future requests*. I'll run some additional tests now to confirm that that's the case.

**Comment by guardrex** [comment]
**_CONFIRMED!_** ... The behavior is ...

* Silent token acquisition is attempted first because the token might be in the ADAL token cache.
* If the token isn't acquired from cache (`AdalError.FailedToAcquireTokenSilently` or `AdalError.UserInteractionRequired`), a user assertion is made with the client credential to obtain the token on behalf of the user. Then, the `GraphServiceClient` can go ahead and use the token to make the Graph API call. The token is then put into the cache.
* When trying again with the same user, **_the token is acquired from cache silently_**. The client can go ahead with the token from cache.

I wish I had caught an example that explained it out, but the docs that I hit weren't crystal clear. They relied upon looking at the API and knowing more about web API with OAuth 2.0. My professional experience didn't encompass it.

@swannet ... I've updated the code in the remark :point_up: with the latest approach. Of course, it's still 💀 **use at your own risk** 💀 until Javier gets free after RC1 is released and can take a look. However, it does follow the MS published examples now **_very closely_**. WRT MSAL.NET, absolutely that's next, and I'll get that up in preview documentation as soon as we reach RC1 release. I don't usually doc things that complex until RC1 because I've (and MS) have been burned before documenting API that shifts before RC1 lands. It's costly in 🕐 ... thus 💰 ... when it happens.
