### ISSUE TITLE
HttpContext.User Claims Aren't Present? Mostly an FYI.

### ISSUE THREAD

**Issue by taylorchasewhite** [dotnet/AspNetCore.Docs#19576]
I know from reading other comments etc. that you guys are a small group reading, addressing and responding to these comments. I created a StackOverflow question relating to issues I'm having in linking my Blazor WASM app to AzureAD [here](https://stackoverflow.com/questions/63493753/blazor-wasm-azuread-auth-httpcontext-user-claims-are-empty), which almost entirely derived from following this article (thanks for the detailed write up).

I plead some ignorance on the the details of AzureAD and Identity, but one issue I hit when moving from my local accounts Identity server to this AzureAD login flow, is that the HttpContext.User now seemed to be empty. I'm not sure why.

Anyways, I hope/expect to get this answered on my aforementioned StackOverflow post so feel free to close this without any action as you see fit, but I wanted to call this out on this page in the small chance that there is an actual issue and/or others are having a similar experience and the docs might be modified to avoid this confusion. If you have any immediate thoughts as to why I'd be seeing this, please let me know as well.

Thanks,
Taylor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3039ff79-ee86-20b1-0082-d3899a84c823
* Version Independent ID: af4a3a75-ae52-5f6d-2120-737bc2fefb07
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @taylorchasewhite ...

> the HttpContext.User now seemed to be empty

I can't explain that behavior. My test app's `HttpContext` in the controller populates the `User` normally, and I get the user's claims. Their claims are from the access token, which include the identifier `name` for the user.

The only thing I can recommend is what you've done ... reach out to devs on support channels. As you noted, we're too small here to troubleshoot individual dev app issues.

* [Stack Overflow](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Blazor)

I am interested to find out in the end what the cause of the problem is with your app. If we can call out a *gotcha* in the topic, it can save other devs trouble down the road. Please post back to this issue after you've sorted it out.
