### ISSUE TITLE
OK to inject transient into singleton

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#19702]
@halter73  should I add something similar to this doc?

> Transient services that are stateless and don't contain any stateful dependencies can be injected into singleton or scoped services. A transient service injected into a singleton has singleton lifetime, it's not disposed until the app shuts down.

[See this SO response](https://stackoverflow.com/questions/56289997/what-is-definitely-wrong-when-transient-injected-to-singleton/56291583#56291583)

cc @serpent5 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by halter73** [comment]
The SO question seems to be talking about "Lifestyle Mismatches diagnostic warning in SimpleInjector DI container", not our docs. Do we say anything discouraging injecting transient dependencies into singleton or scoped services? If not, I'm not sure we need to add anything saying on subject.

The big problems, like leaking transient services because they implement IDisposable are already called out in our docs. The "Lifestyle Mismatches" is more a matter of style, and I don't think we need to say anything for or against it. FWIW, we do inject transient dependencies into singleton and scoped services in a few places in ASP.NET, and I don't recall this ever being an issue.
