### ISSUE TITLE
Nginx config for signalr web sockets problem

### ISSUE THREAD

**Issue by mrahhal** [dotnet/AspNetCore.Docs#19708]
The documentation mentions the following config to configure nginx for websockets:

```diff
server {
    listen        80;
    server_name   example.com *.example.com;
    location / {
        proxy_pass         http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
+        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
```

Check in particular the highlighted line. I spent a long time trying to debug an issue preventing web sockets from working (signalr had to switch to another method). I finally found a couple places talking about nginx needing  `proxy_set_header   Connection "Upgrade";` instead of "keep-alive", so I tried that out. This made web sockets work properly, but I started seeing another problem. Anything other than GET and OPTIONS requests were failing, and the failure message was related to CORS (false positive). I kept on looking even more and found something about `proxy_set_header   Connection $http-connection;`. This finally resulted in both web sockets and normal http requests working.

So to me, it kinda seems like this part in the docs is just completely wrong? I was never able to get web sockets to work with it, and my app was fairly simple.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Rick-Anderson ... I'll keep an :eye: on this one. I've worked with this subject before.

That topic's guidance is for general config. The specific guidance for SignalR is in the *SignalR Scale* topic at ...

https://docs.microsoft.com/aspnet/core/signalr/scale#linux-with-nginx

... which goes with `$connection_upgrade`.

The cross-linked guidance in the Nginx docs indicates 'upgrade' ...

https://www.nginx.com/blog/websocket-nginx/

... with additional info at ...

http://nginx.org/en/docs/http/websocket.html

> proxy_set_header Connection $http-connection;. This finally resulted in both web sockets and normal http requests working.

Open an issue for that scenario on the product unit repo at ...

https://github.com/dotnet/aspnetcore/issues

Since this isn't actionable here at the moment, we'll close for now while you ask engineering about it. Please add a `cc: @guardrex` to your opening issue comment over there. I'll re-open this and work it if we need to provide additional guidance. It's ok if you don't CC: me, but you would need to ping me back on this issue later to look at their response if you think we need additional guidance.

**Comment by mrahhal** [comment]
@guardrex I'm sorry I didn't notice because I went to the signalr docs home and searched for "nginx" in the sidebar. I keep forgetting this search links to other places sometimes... Thanks.

> Open an issue for that scenario on the product unit repo at https://github.com/dotnet/aspnetcore/issues

Isn't this purely a docs issue though? Does this scenario require any changes beyond docs?

**Comment by guardrex** [comment]
> purely a docs issue though?

Not yet ... the guidance on what to set came from engineering, so they need to remark on the suitability of using something different. We do sometimes ping them on a doc issue, but your question will get a quicker response if you open it on the repo where they're actually working. It's best to refer them directly to the current guidance at ...

https://docs.microsoft.com/aspnet/core/signalr/scale#linux-with-nginx

... and then you can present your scenario and how `$http-connection` worked for you, basically asking them if that setting would have any undesirable outcomes ... *gotchas!* ... that might break or cause problems for an app.

I'll follow along the discussion. If they remark that your setting does make sense and under what circumstances, then it will be actionable for the docs. I'll re-open and work this issue based on what they say.

**Comment by mrahhal** [comment]
I see, makes sense. Thanks! Will open an issue there and CC you.
