### ISSUE TITLE
Component instance method helper class: Assembly name not required/Should be removed?

### ISSUE THREAD

**Issue by swijnands** [dotnet/AspNetCore.Docs#19712]
In the helper class in MessageUpdateInvokeHelper.cs:

```
  [JSInvokable("{APP ASSEMBLY}")]
    public void UpdateMessageCaller()
    {
        action.Invoke();
    }
```

The JSInvokable attribute's identifier parameter is expected to be set to the application's assembly name.
As I understand it this is incorrect/does not make sense, and should be removed (or set to something more sensible, i.e. a unique name within the current assemby).

And the same goes for the DotNet Helper (wrapper) client-side code:

```
window.updateMessageCallerJS = (dotnetHelper) => {
    dotnetHelper.invokeMethod('{APP ASSEMBLY}', 'UpdateMessageCaller');
    dotnetHelper.dispose();
}
```

The first argument supplied to invokeMethod(), _'{APP ASSEMBLY}'_, should be fully removed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bdccf73-41ed-b996-86c1-d8b7838f8773
* Version Independent ID: 32d99e69-dc2d-c452-cfdb-2bf1f1956e16
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's a placeholder. I'll make it more obvious. Lately, I've been including a line under such samples that explains what the placeholder is. That way, when the doc is translated into other languages, it makes sense to non-English speakers. In this case, the line under each of these will read something like ...

> Replace the placeholder `{APP ASSEMBLY}` with the app's assembly name.

**Comment by guardrex** [comment]
@swijnands ... I didn't change it *enough* this weekend and ended up with a regression. :boom: It will work without the identifier **_if the JS helper also doesn't use it_**. I only removed it from the attribute. 🙈 I just reverted that back to fix it.

WRT what you're addressing on this issue ...

> As I understand it this is incorrect/does not make sense, and should be removed (or set to something more sensible,

Removing it would be ok. However, I think engineering was going for using the identifier for the helper **_by assembly_**. I think that's why they provided that content that way ... or allowed me to write it that way if that's my example from early days of JS interop coverage ... going back a couple of years to Blazor beta days when Blazor was just an experiment.

As you suggest, the identifier can be something else. Perhaps, we will end up using different placeholder text or removing it.

I've made a note to confer with engineering on this point when I work on this topic further. I hope to get to it over the holidays *after .NET 5 releases* but before *taking off for vacation* 🏖️. It's cross-referenced on my [tracking issue](https://github.com/dotnet/AspNetCore.Docs/issues/19286), so I won't forget to check with them on it.
