### ISSUE TITLE
Additional code needed in "Component instance method helper class" section to avoid errors

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#19732]
There are 2 additional portions of code that I needed to add in this section in order to avoid errors.

In this class, `[JSInvokable("{APP ASSEMBLY}")]` was needed instead of `[JSInvokable]` to avoid error:

> Unhandled Promise Rejection: Error: System.ArgumentException: The type 'MessageUpdateInvokeHelper' does not contain a public invokable method with [JSInvokableAttribute("MyAssembly")].

```c#
using System;
using Microsoft.JSInterop;

public class MessageUpdateInvokeHelper
{
    private Action action;

    public MessageUpdateInvokeHelper(Action action)
    {
        this.action = action;
    }

    [JSInvokable("{APP ASSEMBLY}")]
    public void UpdateMessageCaller()
    {
        action.Invoke();
    }
}
```

In this javascript, `invokeMethodAsync` was needed instead of `invokeMethod` to avoid error:

> Error: The current dispatcher does not support synchronous calls from JS to .NET. Use invokeMethodAsync instead.

```javascript
window.updateMessageCallerJS = (dotnetHelper) => {
    dotnetHelper.invokeMethodAsync('{APP ASSEMBLY}', 'UpdateMessageCaller');
    dotnetHelper.dispose();
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bdccf73-41ed-b996-86c1-d8b7838f8773
* Version Independent ID: 32d99e69-dc2d-c452-cfdb-2bf1f1956e16
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1#component-instance-method-call)
* Content Source: [aspnetcore/blazor/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mrlife ... I made an update over the weekend to that, and it doesn't look like the localized copies of the doc are updated yet. We document (and the API remarks state) that the identifier is there for cases where the method name won't be used to invoke the method. Since we already covered using a custom identifier with the attribute and it was wrong to use that placeholder, I removed that placeholder string from the example this weekend. See the English-US version of the topic ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1#component-instance-method-helper-class

This exact error ...

> Unhandled Promise Rejection: Error: System.ArgumentException: The type '{helperClassName}' does not contain a public invokable method with [JSInvokableAttribute("{APP ASSEMBLY}")].

... seems to indicate that you didn't change `{APP ASSEMBLY}` to a custom identifier. It looks like you tried to run the code exactly as it appears in a non-English version of the topic.

I'll run a few tests here and confirm the behavior and see what needs to be updated. I'll include asynchronous and synchronous method tests.

**Comment by mrlife** [comment]
>  seems to indicate that you didn't change {APP ASSEMBLY} to a custom identifier

I replaced my assembly name with the generic one when entering the error into the above comment. Sorry, that does seem confusing, so I'll edit that.

The English-US version of the topic is what I'm using, and at the top, it says it was last updated on 08/12/2020. I don't see the changes you're referring to.

**Comment by mrlife** [comment]
I tried a few things, and I think this is was you're referring to (not needing to use the app assembly name at all). Works great!

```c#
[JSInvokable]
public void UpdateMessageCaller()
{
    action.Invoke();
}
```

```javascript
dotnetHelper.invokeMethodAsync('UpdateMessageCaller');
```

**Comment by guardrex** [comment]
> The English-US version of the topic is what I'm using

You quoted this code in your opening comment ...

```
[JSInvokable("{APP ASSEMBLY}")]
public void UpdateMessageCaller()
```

... but that was updated on https://github.com/dotnet/AspNetCore.Docs/pull/19713/files to ...

```
[JSInvokable]
public void UpdateMessageCaller()
```

Try hitting refresh in your browser. Maybe the page has been cached there locally.

This whole topic/**_subject_** is a bit **_confusing_** because there's flexibility in where/how the JS functions are set up, there's sync and async helper calls, using a custom identifier or not, calling from code vs. calling from a component, and static vs. instance! 😵 *Good grief!* There's a lot of flexibility and scenarios, so it's more challenging to cover.

What I'll do now is get the async call there for the helper. I think the rest of it will be ok, but I'm going to run a set of tests now to confirm.

WRT working on this topic further ... improving it in more general ways ... **_Yes, please!_** I'll get to it, but it won't happen until after .NET 5 releases. It will be tracked by https://github.com/dotnet/AspNetCore.Docs/issues/19286. I'll have more time (*I think*) near the holidays to make UE passes on many docs to improve them.

**Comment by mrlife** [comment]
OK thank you, yes I do see where that change is present. I think what's confusing is that right below that, this line needs to be changed.

From

```
dotnetHelper.invokeMethod('{APP ASSEMBLY}', 'UpdateMessageCaller');
```

To

```
dotnetHelper.invokeMethod('UpdateMessageCaller');
```

**Comment by guardrex** [comment]
The reason that you hit that error and had to use the async version with ...

```csharp
[JSInvokable]
public void UpdateMessageCaller()
{
    action.Invoke();
}
```

... is that you didn't make the method static. If you use ...

```csharp
[JSInvokable]
public static void UpdateMessageCaller()
{
    action.Invoke();
}
```

... then you can call it with ...

```javascript
window.updateMessageCallerJS = () => {
  DotNet.invokeMethod('{APP ASSEMBLY NAME HERE}', 'UpdateMessageCaller');
};
```

I'll see how I can surface it.

> I don't mind submitting a PR if that helps in any way.

Thanks, but I'll take care of it.

**Comment by guardrex** [comment]
I think I see why this weekend's update wasn't good. This scenario (*Component instance method helper class*) is going to require the app's assembly as the identifier for the invokable method. I should've tabled the update until I had more time to work on it. I still have a lot on me right now ... and really looking forward to slowing down a bit for the holidays.

I'll update it now ... I'll put the app assembly indentifer back on the attribute, go with the async version of the call, and shoot it into the live docs immediately given that this weekend created a regression in the doc.
