### ISSUE TITLE
dotnet run --pathbase=/myapp does not work

### ISSUE THREAD

**Issue by papaja** [dotnet/AspNetCore.Docs#19758]
[EDIT by guardrex to add inline code markers ... use a single backtick around inline code ... use triple backticks for multiline code blocks]

I have .net core hosted Blazor application. It will be hosted in sub directory under main domain like domain.com/myapp.
In index.html I've set `<base href="/myapp/" />`

After running `dontnet run --pathbase=/myapp` I open `https://localhost:5001` or `https://localhost:5001/myapp` but in both cases I get "An unhandled error occured".

I have also tried setting `--pathbase=/myapp` in Visual Studio debug options and running it from Visual Studio but result is the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e07aaa4d-4ad4-778f-f74a-60d8f05d9075
* Version Independent ID: c82cf121-831d-75dd-a796-c735aad3b3e9
* Content: [Host and deploy ASP.NET Core Blazor](https://docs.microsoft.com/en-in/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-3.1&tabs=visual-studio#app-base-path)
* Content Source: [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @papaja ... The guidance is correct ... generally anyway ... an edge case that breaks is always a possibility, of course. Check the browser tools console for errors. If you can't find a better error message than that in developer tools, put the app (or a minimal repro app) up on GitHub for inspection and reach out to devs on support channels ...

* [Stack Overflow](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Blazor)

If the community can't help you figure out what the problem is or you think you've found a real Blazor framework bug 🐞, open a detailed issue for engineering at ...

https://github.com/dotnet/aspnetcore/issues

Do that after you've worked with the community. The team is super busy 🏃 trying to get .NET 5 done. They should only be contacted as a last resort or for when you're fairly sure you've hit a bug in the framework.
