### ISSUE TITLE
Miss a strategy to handle the refresh of tokens

### ISSUE THREAD

**Issue by andmig-ilty** [dotnet/AspNetCore.Docs#19797]
It would be great if this article would also contains a pattern to handle the token expiration and refresh of the access_token.

BTW, I applied the suggested pattern, while using a customized Oauth Provider and still works fine!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8acbbf-c9d4-7041-c1a7-ec9ce8f0981b
* Version Independent ID: c98be365-408d-7ee6-cb74-14c44d01b0b8
* Content: [ASP.NET Core Blazor Server additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/server/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/server/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @andmig-ilty ... Engineering has refused to show that scenario. They've flatly said that refresh tokens and client-side apps create security risks because there's no way to completely and effectively deal with them. If you search this out over on the engineering repo (try the filter phrase "refresh token" to see if it filters), you'll probably find the answers.

If all of the issues are closed but you'd like to strike up a **_new_** convo with them about some **_new_** approach that might deal with the security aspects, open a **_new_** issue with them (i.e., don't comment on closed issues over there).

Here's the Blazor-filtered engineering issues link ...

https://github.com/dotnet/aspnetcore/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-blazor

**Comment by andmig-ilty** [comment]
As far as I know Blazor Server is a server side application and the secrets are never threated on the client. This is opposite to Blazor WebAssembly where, I'm with you, we should never handle secrets and thus, the oauth implicity flow is then used (no client secret, no refresh_token, etc)

The linked article do refer to Blazor **Server** and for completeness the refresh_token workflow worth to be covered...

**Comment by guardrex** [comment]
Oh ... sorry about that @andmig-ilty ... I did misinterpret the issue. I'm buried in a thorny issue elsewhere, and it takes just about all of my (small) brain to process it. 😖

Yes, we don't show that ... *yet* anyway. I'll put this on the Blazor project for triage for further discussion.

**Comment by guardrex** [comment]
It might take a week (or a few) to get to this. The engineers on the product unit are all 🏃😅 like crazy right now working on the .NET 5 release for RC1. I'll see after RC1 lands if we can get a remark from them on what they'd like to show. You're welcome to post your suggestion here for discussion if you want.

**Comment by guardrex** [comment]
@javiercn ... @andmig-ilty is asking if we can add a topic section + example code for **_Blazor Server automatic token refresh_**. Can/should we? If so, can you provide the code or point me to an example that you feel would be the right thing to show?

**Comment by guardrex** [comment]
@javiercn ... Should we add content and example code for **_Blazor Server automatic token refresh_** using the refresh token in `TokenProvider`. If so, can you point me to an example that you feel would be the right thing to show?

https://docs.microsoft.com/aspnet/core/blazor/security/server/additional-scenarios#pass-tokens-to-a-blazor-server-app

**Comment by BrettMahon** [comment]
I tried to setup my TokenProvider object to contain Func<Task<string>> instead of the plain text token itself. My thinking was when getting the token, my closure would run and I would get the latest token rather than the initial one. Unfortunately the framework did not like that as somewhere in the pipeline (I am guessing between the cshtml file and the Blazor app) the TokenProvider object needs to be serialised - so no lamda possible there. 

I have an app with a 1 hour token expiry so without an example to get a live token I am a bit stuck (I really don't want to force the user to login just because his token has expired). 

If anyone has made any progress here, please let us know.

**Comment by javiercn** [comment]
@BrettMahon any parameter that you pass down to a root component needs to be serializable.

@guardrex there's nothing special about doing the token refresh from server-side Blazor. It involves sending a request to the token endpoint of the OIDC/OAuth provider in the same way you do in a web application.

**Comment by guardrex** [comment]
It's cross-linking the "in the same way" bit that's concerns me. OAuth2 docs have ...

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#refresh-the-access-token

... and truly, that's about it here or there AFAICT. I haven't found a sample app that does it in our doc sets. I suppose refresh is for `OnAuthenticationFailed`. We only have one mention of `OnAuthenticationFailed` in the doc set, and it isn't an example for this. It's literally just a mention ...

> Called if an exception happens during authentication and allows you to react.

... in the cert security topic. I don't see a good example in Azure docs+samples either.

Sorry that I'm so rusty on this scenario 👴 ... I'll research further asap.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
