### ISSUE TITLE
Blazor WASM AAD Auth Instructions require updates to match Azure Portal changes.

### ISSUE THREAD

**Issue by jhurdlow** [dotnet/AspNetCore.Docs#19800]
This page defines steps which no longer align to the layout and options provided in the Azure portal interface. For instance options are presented which are not defined in the instructions, and some instructions are not do-able as the option is not there. Please update to match current Azure portal configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3039ff79-ee86-20b1-0082-d3899a84c823
* Version Independent ID: af4a3a75-ae52-5f6d-2120-737bc2fefb07
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jhurdlow ... can you say exactly what was different because we've had reports like this before and it turned out that the portal hadn't been updated ... it was just a missed instruction step on the reader's part. It wouldn't surprise me, of course, if the portal did change ... it happens quite frequently. If by ...

> For instance options are presented which are not defined in the instructions

... you're just saying that not **_ALL_** of the options are called out. That's normal. We won't do that here because this isn't meant to be a full tour of everything you can do in the portal for this app config. It's just meant to focus on the critical config to make it work.

**Comment by guardrex** [comment]
An alternative to letting me know what you think requires updating is to wait a short bit longer for me to get to ...

https://github.com/dotnet/AspNetCore.Docs/issues/19503

... when I'll be looking at the portal for the RC1/Identity v2.0 updates. In that case, we'll call this a duplicate and close it without further concern.

**Comment by guardrex** [comment]
@jhurdlow ... I'm going to close because I'd need more specific information on what's different. Like I said, we've had these sorts of issues opened in the past where there was a missed step when following the guidance. I'll be taking a look at all of these topics and the portal when I get to #19503 shortly for the .NET 5 RC1 updates (preview docs). I'll confirm or update accordingly when I get to that issue.
