### ISSUE TITLE
Call a web API from WebAssembly is very slow for more json result

### ISSUE THREAD

**Issue by NaserParhizkar** [dotnet/AspNetCore.Docs#19840]
Consider I want to get more than 5000 records from WebApi 
and as you can see in the following code, where I mentioned with my bold comment and it's Blazor code
Would you please tell me how can I fetch data and convert it to my model in Blazor code less than that long time?

protected override async Task OnInitializedAsync()
{
    try
    {
       **// This should have gotten data a few milliseconds like Javascript for 9000, but it took more than 10 seconds**
        forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>(
            "WeatherForcast");
    }
    catch (NotSupportedException exception)
    {
        ...
    }
}

**Comment by guardrex** [comment]
Hello @NaserParhizkar ... btw ... It's best to open issues on the docs repo using the **This page** feedback form at the bottom of any topic. It pings the author and adds metadata to the issue.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

WRT to the issue you've raised, I agree with you ... that doesn't sound good. I hope you checked the web API side first tho to make sure that this is due to Blazor processing and not just a slow request-response-server API that's to blame. I recommend making sure of that first before asking the product unit to comment on this. Otherwise, it will be a bit of a waste of their time. As I'm sure you're well aware, a slow client, slow server, and/or slow network can do just that. I think what you're saying tho by mentioning JS is that you're already aware that the slow speed here isn't any of those but actually that the **_Blazor framework is taking a long time to process the result of the web API call after the data arrives_**. If you've verified that, open an issue for engineering at ...

https://github.com/dotnet/aspnetcore/issues

Explain your environment, the nature of the apps and the data, and the perf figures. Give them all of the relevant info that you can to triage the issue quickly because they're very busy right now with the .NET 5 release. If you think to, please add a `cc: @guardrex` to your issue comment so that I can be pinged on the discussion.
