### ISSUE TITLE
Multiple issues with TOC, Content and formatting for Blazor components

### ISSUE THREAD

**Issue by Paul-Dempsey** [dotnet/AspNetCore.Docs#19850]
I  was trying to find information on doing Radio buttons in server-side Blazor, and hit this page and finding many problems.

In the TOC, when I click on anything between InputCheckBox and InputText area, it does not go to anything with the corresponding heading, and the highlighted item in the TOC appears to be a random one in that group. In particular, clicking InputRadioGroup takes you to a table listing a number of components, and that table doesn't include anything related to radio buttons. In fact, If I use browser Find "InputRadioGroup", it exists nowhere on the page, so I'm left in the dark about these components.

What I do find about radio buttons appears to be basic cshtml razor information, and nothing about the Blazor components.

misc issues:

- Some of the examples of razor source are tagged csharp (example under *Business logic validation*), and some tagged as razor
- Syntax highlighting in razor samples appears to be random - very broken (I don't see how to include a screen snip).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1#built-in-forms-components)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> In the TOC, when I click on anything between InputCheckBox and InputText area, it does not go to anything with the corresponding heading

The section it links **_is_** the coverage at this time, then the links off to the API docs take over. There aren't individual sections for each one because they're implemented and behave similarly.

> highlighted item in the TOC appears to be a random one in that group

It's due to the way in which the ToC attempts to automatically highlight when there aren't sections.

To deal with this ... and further clarify based on your last remark ... I'll create **_sections_**. It will clear up both situations.

> InputRadioGroup takes you to a table listing a number of components, and that table doesn't include anything related to radio buttons

Set the forms topic version to 5.0 ...

<img width="609" alt="Capture" src="https://user-images.githubusercontent.com/1622880/93115798-01869500-f682-11ea-8cd4-e66f192ba9a3.PNG">

It's a point-in-time problem during preview. This one will resolve on its own when we reach 5.0 GA.

What I might do is add a "(5.0 Preview)" in the ToC sidebar. At least that will provide a *hint* until we get there.

> basic cshtml razor information

That's correct for the current release.

> Some of the examples of razor source are tagged csharp

Yes ... those two are 🐞 ... I'll fix them up. The reason that happened is because **_they WERE_** just C#, then there was an update (by me 🙈) to make them components without updating the code language. Thanks for the heads-up. They're 😈 *sneaky* 😈.

> Syntax highlighting in razor samples appears to be random - very broken

I'll take a look and fix up anything that I find.

Thanks for writing in on these! I'll get them squared away quickly ... either this evening for first thing Tuesday morning.

**Comment by Paul-Dempsey** [comment]
Thanks, Luke!

I’m in ASP.NET Core 3.1, not 5 Preview:
[cid:image001.png@01D68A81.AEC504D0]

So the TOC is pretty messed up if 5 Preview stuff is showing up in 3.1 content.

Colorization issues look to be Support colorization of the @code directive for Razor components · Issue #17296 · dotnet/AspNetCore.Docs (github.com)<https://github.com/dotnet/AspNetCore.Docs/issues/17296>
Open since March. Although this issue talks only about @code, the issue duped to it is more comprehensive and would be better as the master, because razor syntax highlighting is seriously broken throughout the docs, and not something an author can address because the issue is in the .razor highlight.js highlighter.

This kind of rendering is pervasive:
[cid:image003.png@01D68A81.AEDE8040]

**Comment by guardrex** [comment]
> So the TOC is pretty messed up if 5 Preview stuff is showing up in 3.1 content.

It's a **_rock and a hard place_** scenario at the moment. I don't have a lot of options. We can't version content **_within a topic_** to show up in the ToC or not. We can only version **_whole topics_** to show up or not. I think adding a little 5.0 mention is the best we can do at the moment. The alternative would be to drop those entries until 5.0 GA, but that comes with its own pain ... it hides the new features.

> Open since March. Although this issue talks only about @code, the issue duped to it is more comprehensive and would be better as the master, because razor syntax highlighting is seriously broken throughout the docs, and not something an author can address because the issue is in the .razor highlight.js highlighter.

I recommend pinging Scott on that issue. He works directly with them on a variety of doc build system issues. It's probably tracked by an internal engineering issue, and he might be able to let you know where it all stands.
