### ISSUE TITLE
About the example provided in the article

### ISSUE THREAD

**Issue by ilanb1996** [dotnet/AspNetCore.Docs#19923]
[Enter feedback here]
In this code example: 
```csharp
public BookService(IBookstoreDatabaseSettings settings)
{
    var client = new MongoClient(settings.ConnectionString);
    var database = client.GetDatabase(settings.DatabaseName);

    _books = database.GetCollection<Book>(settings.BooksCollectionName);
}
```
We use the DI to inject the `IBookstoreDatabaseSettings ` to our service. But then we go and do this :
 `var client = new MongoClient(settings.ConnectionString);`
Do I miss something? shouldn't this be considered a violation of the inversion of control design pattern?
.net core supports DI I think the example should show how to use it properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
How does that violate IOC?

**Comment by ilanb1996** [comment]
Great question, the way i see it, if i want `MongoClient` to be used within my service i would probably want to just get it thrugh my cTor and not initialize it myself. 
Something like that:
```chsarp
public BookService(MongoClient client)
{
    this.client = client;
    var database = client.GetDatabase(settings.DatabaseName);

    _books = database.GetCollection<Book>(settings.BooksCollectionName);
}
```
Also doing "unsafe" operation (meaning they can throw an exception) like `    _books = database.GetCollection<Book>(settings.BooksCollectionName);` in the ctor also feels like a bad practice.

**Comment by Rick-Anderson** [comment]
I think the code is fine

**Comment by prkhandelwal** [comment]
@ilanb1996  Well, I think there's nothing wrong with either approaches. But I think adding `MongoClient` as a _Singleton_ in DI container should be better in some cases since:

- We generally just maintain one instance of MongoClient
- Even if we create multiple instances, they will still share the same pool of connections to the mongoDB anyways.
-  So, having a Singleton instance injected through DI container will just save us the cost of multiple initializations during app startup in other services like `BookService`. (But it won't matter until we have too many of those).

But I think the current code is more beginner friendly, as it does not hide the MongoDriver syntax (even if it's just the initialization) behind framework features like the DI Container. I have seen a lot of people who're just starting up get confused by too many abstractions & "standard practices", so even if someone were writing a console app, the mongo/c# syntanx would be simpler to understand. 

@Rick-Anderson  Would love to hear your thoughts on this...

**Comment by Rick-Anderson** [comment]
@prkhandelwal  Excellent.
