### ISSUE TITLE
No explanation on how to change the default logging location??

### ISSUE THREAD

**Issue by GlenBoonzaier** [dotnet/AspNetCore.Docs#19944]
This article mentions the default logging locations for both Windows and Linux, but nowhere does it explain where to change this.  What if I want to change the logging location to ~/home/mylogs/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See [this SO](https://stackoverflow.com/questions/51886315/how-can-i-configure-ilogger-to-output-the-logs-to-a-specific-file) 
cc @serpent5

**Comment by davidfowl** [comment]
There's no default file logging in ASP.NET Core. You need to plug in a provider like serilog or nlog etc

**Comment by serpent5** [comment]
I think the coverage here is OK as-is. [Built-in logging providers](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#built-in-logging-providers) doesn't show a "file" provider, because there isn't one, as David Fowler says. The only reference to a path seems to be under the [Debug](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#debug) provider, which is a different provider entirely. The [Log during host construction](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#log-during-host-construction) section shows using Serilog and its file sink, but not as the main focus.

Another option is to add something to the "Built-in logging providers" section, highlighting that a third-party provider, e.g. Serilog, has its own built-in log-to-file functionality.

**Comment by Rick-Anderson** [comment]
>  "Built-in logging providers" section, highlighting that a third-party provider, e.g. Serilog, has its own built-in log-to-file functionality.

Yes. and also add `There's no default file logging in ASP.NET Core`
