### ISSUE TITLE
Unsure if documentation regarding OnAfterRender[Async] are correct

### ISSUE THREAD

**Issue by wbuck** [dotnet/AspNetCore.Docs#19948]
Currently in the documentation regarding Blazor life-cycles I see the following quote:

> OnAfterRender and OnAfterRenderAsync aren't called when prerendering on the server.

But I'm using `render-mode="ServerPrerendered"`  and I do see that the `OnAfterRender` and `OnAfterRenderAsync` are indeed being called. 

Is the documentation incorrect or did I miss something? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Blazor lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @wbuck ... The 🧀 may have moved at some point. Late last year, @SteveSandersonMS [provided an update for an update for that line](https://github.com/dotnet/AspNetCore.Docs/pull/15841#discussion_r351358881); so at least as of that time, it was good.

@SteveSandersonMS ...

> `OnAfterRender` and `OnAfterRenderAsync` aren't called when prerendering on the server.

If that changed, which releases (versions) and hosting models does it apply to?

**Comment by SteveSandersonMS** [comment]
It didn't change. I think the confusion is just with how to parse the statement in the docs:

> `OnAfterRender` and `OnAfterRenderAsync` aren't called when prerendering on the server.

This means they aren't called **during the prerendering process**. They are still called when the component is rendered interactively after prerendering is finished. To recap, when you prerender:

1. The component executes on the server to produce some static HTML markup in the HTTP response. During this phase, `OnAfterRender` and `OnAfterRenderAsync` aren't called.
2. Then, when `blazor.server.js` or `blazor.webassembly.js` start up in the browser, they restart all your components this time in an interactive rendering mode. This time, `OnAfterRender` and `OnAfterRenderAsync` **are** called because you're not inside the prerendering phase any more.

**Comment by wbuck** [comment]
@SteveSandersonMS That makes sense. I had a feeling I was just interpreting that sentence incorrectly.
Thanks.
