### ISSUE TITLE
Question: Compare SingalR and gRPC

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/AspNetCore.Docs#19940]
Is it possible to provide comparison between SignalR and gRPC?

For example, why is SignalR not used in MicroServices in backend services?

What is the difference in client server communication in areas of browsers and mobile apps?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8321e4f0-1d12-c4cd-76af-a7df9ca2e732
* Version Independent ID: c9e71059-2e31-3de3-eb26-0946cfe0ec3d
* Content: [Compare gRPC services with HTTP APIs](https://docs.microsoft.com/en-gb/aspnet/core/grpc/comparison?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/comparison.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/comparison.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by Rick-Anderson** [comment]
@JamesNK  there are lots of good articles on [signalr vs grpc](https://www.google.com/search?q=signalr+vs+grpc&rlz=1C1RXQR_enUS990US990&oq=signalR+vs+grpc&aqs=chrome.0.0i512l2.4215j0j7&sourceid=chrome&ie=UTF-8) 
Should we add a section to this doc and maybe rename the doc?

**Comment by wadepickett** [comment]
This doc does mention when to use SignalR rather than gRPC in the following section: [Alternative framework scenarios](https://learn.microsoft.com/en-us/aspnet/core/grpc/comparison?view=aspnetcore-7.0#alternative-framework-scenarios). However, it does not answer the questions posted in this issue. 

Although SignalR and gPRC were designed to solve different problems, there is some confusion out there to address on when to use one or the other.

There is another old issue related to this that is still open, ending with @bradygaster suggesting s a broader scoped topic may be needed: https://github.com/dotnet/AspNetCore.Docs/issues/11733.  I didn't see a follow up, but maybe that was offline.

**Comment by Rick-Anderson** [comment]
Dup of #11733
