### ISSUE TITLE
Standalone Blazor WebAssembly App Authentication Failed with IdentityServer 4

### ISSUE THREAD

**Issue by Akinnagbe** [dotnet/AspNetCore.Docs#20086]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985b834f-534a-aba6-80a0-d8845adbfc25
* Version Independent ID: d2b5a556-82a4-e939-be68-2357a3d4408f
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1&tabs=visual-studio&source=docs)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

Hello,

I created a standalone Blazor App, and tried to authenticate with an external application configured with IdentityServer4. Authentication succeeds on the IdentityServer App but on trying to redirect back to the Blazor App, the user is still not authenticated.

I have tried for several days but without success.

Thanks

**Comment by guardrex** [comment]
Hi @Akinnagbe ... Unfortunately, we aren't able to provide product support. We **_DO_** address specific feedback for discovered doc problems that are reported to us here. Your best bet to work with devs on a support channel to try and determine what the problem is; then when you discover the cause of the problem and identify where the topic didn't steer you in the right direction, open an issue here with the details. We can work it forward from there.

I'll note in passing that if you're on .NET 5 preview, these docs haven't been updated yet for .NET 5. That work is underway, and I hope to have a PR up by the end of next week.

If you are on .NET 3.x, you might want to explore the *hosted* scenario doc for clues as to what might be wrong with your app ...

https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/hosted-with-identity-server

... check out the client and server app configurations there to see what might be wrong with your app in terms of packages, API, etc. I understand that you're not trying to use a hosted scenario, but the setup on the client should be very similar or exactly like what that topic shows ... and the server app ... whatever you're trying to auth against ... should also have similar config to what the topic is explaining.

Also, check the product unit repo issues for any reports that pertain specifically to Identity Server 4 and Blazor WASM. Here's a set of search results on the search label "area-blazor" and "Identity Server" ...

https://github.com/dotnet/aspnetcore/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-blazor+identity+server

Note WRT opening issues for the product unit, that you can't open an issue like this there either without more information. The product unit is also unable to handle very general support requests of the variety 'my app doesn't work.' It's best to open an issue there when you have narrowed down the problem with the help of devs on support channels to exactly what is breaking. You would open an issue there if what you find out about this problem is that it isn't a documentation problem but actually a problem in the Blazor framework itself. They'll need the exact error/behavior ... token values ... detailed logging ... possibly even a full repro project put up on GH for them to look at.

WRT to the support channels that we recommend, you're probably familiar with SO, but you might not be aware of the Slack and Gitter chats.

* [Stack Overflow](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Blazor)

... and as a final note ... I strongly recommend as you test and try to work out the problem that you use a fresh incognito/in-private browser **_for every single test run no matter what you change and where_**. Lingering cookies are a disaster during testing and drive you crazy 😵 as you test an app and try to work out a problem. See the *Troubleshoot* guidance at the bottom of any of the topics in this node to see how to config VS to do that for you.
