### ISSUE TITLE
Documentation should be independent of IS4

### ISSUE THREAD

**Issue by AmSmart** [dotnet/AspNetCore.Docs#20107]
I believe this documentation has confused many developers into believing ASP.NET Core web APIs can't be secured without OIDC. The documentation should be updated to show how both simple and advanced authentication scenarios should be handled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by blowdart** [comment]
And what other authentications methods, other than ODIC/JWT would you suggest?

**Comment by AmSmart** [comment]
I certainly don't know all the rules but I believe IS4/OIDC is an overkill for most apps especially if they aren't trying to achieve SSO. The baked in Identity management with Cookies/JWT is useful in many scenarios but I can hardly find a documention on ASP.NET Core with Spas that talk about that.

**Comment by blowdart** [comment]
As the introduction says

_ASP.NET Core 3.0 or later offers authentication in Single Page Apps (SPAs) using the support for API authorization. ASP.NET Core Identity for authenticating and storing users is combined with IdentityServer for implementing OpenID Connect._

That could be better clarified to "ASP.NET Core 3.0 templates", which would, at least indicate it's a template choice, and one that was made for ease of use and due to customer demand that we used standards and popular open source projects. While Identity Server is now change their direction, they're still in the templates for now, and talking about what's not in templates may lead to even greater confusion. 

If someone were to feel talking about just using cookies, can explain the limitations of that, and the security configuration neccessary then I'm sure we'd take a pull request, and do a bit of renaming to make it clearer that this page is a template choice.

**Comment by AmSmart** [comment]
Thanks for this! A lot of noobs are less confused now
