### ISSUE TITLE
Clarity in upgrade process

### ISSUE THREAD

**Issue by dajma00** [dotnet/AspNetCore.Docs#20143]
When following these instructions on a Blazor webassembly starter project, it is not clear if project file changes should be made to the Client project, Server project or both. The page only states that If updating a "Blazor WebAssembly project, skip to the Update Blazor WebAssembly projects section" and then goes to list the changes required in the project file. Further, it does not make any mention if the changes can be made by using the Visual Studio option "Project-> 'ProjName' Properties" option, or it should not be used at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Thanks for the report @dajma00 ... I'm a bit buried in Blazor WASM security code for the next few days, so I won't be able to address this until probably next week. In the meantime if you're struggling to get a 3.x hosted Blazor solution upgraded to 5.0 preview, I recommend that you create a fresh default hosted Blazor solution from the 5.0 template and compare directly to the app that you're seeking to upgrade in order to determine what must be done. Thanks again for the report, and I'll get back to this as soon as I can to describe hosted Blazor solution migration.

**Comment by dajma00** [comment]
Hi Luke,

No issues. I just created a 5.0 project and inserted my code into it and everything just works fine.
But it would help others were there a bit more clarity in the documents.

Regards,
Amjad.

________________________________

**Comment by guardrex** [comment]
Yes, I agree. I generally wait until RC1 lands before testing framework code locally and updating many docs because the product unit fiddles with the code quite a bit before RC1. Doc updates are too hard to keep up with pre-RC1. The downside to waiting so late is that the updates hit me all at once for at least local testing and often for doc updates themselves. It generally works out ok tho ... in the past, there has been enough time between RC1 and GA that all of the updates get in on time.

After I dig out of all of the 5.0 security updates, I'll get right on this. I hope to address it by early next week. Thanks again for the report.
