### ISSUE TITLE
Please Add Content

### ISSUE THREAD

**Issue by DavidEaton** [dotnet/AspNetCore.Docs#20181]
Under "Standalone Blazor WebAssembly apps:", please add Identity Server. You've published many scenarios but lack the one I'm most interested in. Many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c572618c-8b98-95af-6a75-1f8e413071db
* Version Independent ID: 8670b314-460d-3194-c53b-9a44f39c6b2a
* Content: [Secure ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @DavidEaton ... It's the same config as the [client app of a hosted solution](https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/hosted-with-identity-server#client-app-configuration).

I'll leave this for triage; but even if we were to provide this coverage, it would likely be marked very low priority and wouldn't be addressed well into next year.

**Comment by guardrex** [comment]
@mkArtakMSFT ... How you feel about having a standalone WASM topic for IdS that's really just the existing client-side config content for the *Client* app of the hosted Blazor solution from the *Hosted WASM with IdS* topic? It would surface the scenario when looking at the ToC to have this as a separate (matching) topic ...

* Security and Identity
  * Overview
  * Blazor WebAssembly
    * Overview
    * Standalone with Authentication library
    * Standalone with Microsoft Accounts
    * Standalone with AAD
    * Standalone with AAD B2C
    * :point_right: **Standalone with Identity Server** :point_left:
    * Hosted with AAD
    * Hosted with AAD B2C
    * Hosted with Identity Server
    * Additional scenarios
    * AAD groups and roles
  * Blazor Server
    * ...

I could whip this up quickly, possibly using an INCLUDE file for it so that we don't have duplicate coverage between the new topic and *Hosted with Identity Server*.

This would be a good time because I'm waiting for Jean-Marc to look at that Azure groups and roles bit. I have a few minutes here to knock this issue out if you want to go ahead with it.

If not tho, then we can close this issue as a *won't fix*.

**Comment by guardrex** [comment]
*Ah!* ... this was already addressed by an earlier issue, and there is an existing NOTE at the top of the topic. The product unit recommends following the *Auth Lib* topic for standalone IdS scenarios. I don't know if the **_Client app section_** of the *Hosted with IdS* topic would work, but that's not what they want devs to use to configure a standalone app for IdS. Because the *Auth Lib* topic doesn't (and won't) call out IdS specificially, we should **not** have a ToC link to that topic that mentions IdS ... it would just be confusing. Let's let the NOTE do its job because that's probably where readers are going to go if they're looking for our IdS coverage here. We'll continue to take feedback on the coverage and ToC.

https://github.com/dotnet/AspNetCore.Docs/issues/19208#issuecomment-658715401
