### ISSUE TITLE
Blazor Server configuration and limits

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#20223]
[EDIT by guardrex to add the metadata]

As per various document i have read , it is mentioned that Blazor Server manages state for each connected client.
How can we do sizing for Blazor Server side, How do we get a number on how many concurrent user can a Blazor Server side support?
What kind of memory does it use for each connected user what does it store on server ?
Can timeout be configured for longer or shorter duration than the default ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7367a651-2b27-0a57-e7d0-95686cc97f1c
* Version Independent ID: 8c769648-728d-72ce-ebf6-2a06e5076aa2
* Content: [ASP.NET Core Blazor configuration](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/fundamentals/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @nssidhu ... You can find information on SignalR (which Blazor Server is based on) in the [SignalR doc set](https://docs.microsoft.com/aspnet/core/signalr/introduction). There's some information on scale in the [SignalR: Host and scale](https://docs.microsoft.com/aspnet/core/signalr/scale) node on these subjects. But before looking at SignalR docs, we have some Blazor-specific guidance in the Blazor area of the doc set:

* There's information on what's stored in a Blazor Server circuit in the [Blazor: State management](https://docs.microsoft.com/aspnet/core/blazor/state-management?view=aspnetcore-3.1&pivots=server) topic.
* There's information on Blazor Server's scale, limits, and connections in the [Blazor: Threat mitigation](https://docs.microsoft.com/aspnet/core/blazor/security/server/threat-mitigation) topic.

The amount of memory consumed per connected user can't be stated precisely because it depends on the app and components. There might be some rough minimum for a minimal component, but I don't know what that value is. It also likely changes a bit from release to release. It's probably been getting smaller each release as the framework engineers improve Blazor.

One thing that I'd like to do now that we have a new Blazor [Configuration](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/configuration) topic is add a section there on Blazor Server configuration, including the circuit options described in [Blazor: Threat mitigation: Denial of service (DoS) attacks](https://docs.microsoft.com/aspnet/core/blazor/security/server/threat-mitigation#denial-of-service-dos-attacks) with a cross-link to that DOS content.

Leave this issue open. It will close automatically when the PR merges. Thanks for commenting.
