### ISSUE TITLE
Bug on page

### ISSUE THREAD

**Issue by IT-LCEC** [dotnet/AspNetCore.Docs#20266]
This code 
```
services.AddIdentity<ApplicationUser>()
        .AddEntityFrameworkStores<ApplicationDbContext>()
        .AddDefaultUI()
        .AddDefaultTokenProviders();
```

shows error for AddIdentity. I changed it to AddIdentityCore for my Blazor app. Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9869895-9ba2-5027-46cd-89d1d995cba4
* Version Independent ID: 8750939b-6ae5-3b9a-6c32-5e84b7fea22c
* Content: [Identity model customization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/customize-identity-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/customize-identity-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
What's the error?
[AddIdentity](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.identityservicecollectionextensions.addidentity?view=aspnetcore-3.1)

**Comment by stevebelskie** [comment]
@Rick-Anderson I don’t believe there is an extension method `AddIdentity<TUser>` only `AddIdentity<TUser,TRole>`. There are two other extension methods that do take just `TUser`: `AddIdentityCore` and `AddDefaultIdentiry`.

 I would imagine one of those should be used instead. Possibly would need two examples since AddDefaultIdentity calls AddDefaultUI but also does other things (cookie auth etc.) that would be needed without calling AddDefaultUI (e.g.  if the UI files were added directly by the scaffolder).

Haven’t had a chance to lookup at scaffolded code to see if there an actual issue there or just in the documentation on this page. 

If this sounds correct, I’d be happy to submit a PR.

**Comment by Rick-Anderson** [comment]
@haok can you suggest the right approach
@stevebelskie a PR would be great after @HaoK  responds.

**Comment by HaoK** [comment]
I'd just update to pass in IdentityRole if you need a TRole, or just call AddDefaultIdentity when using all the defaults

**Comment by Rick-Anderson** [comment]
> If this sounds correct, I’d be happy to submit a PR.

ping @stevebelskie

**Comment by stevebelskie** [comment]
@Rick-Anderson sorry completely feel off my radar. Should have time this week to submit a PR.

**Comment by Rick-Anderson** [comment]
No worries, fell off my radar too :)
