### ISSUE TITLE
Need guidance for scaffolding identity into an existing Blazor wasm project 

### ISSUE THREAD

**Issue by dajma00** [dotnet/AspNetCore.Docs#20295]
I need clarity on how to scaffold identity into an existing Blazor wasm project created using Visual Studio. For example, should we scaffold into Client or the Server project? Also it is difficult to understand how to use an already existing dbcontext that I use for the rest of my project, for the Identity database as well. The document https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio mentions Blazor server, but no reference is made to Blazor wasm anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dajma00 ... Scaffold into the *Server* project, but note that there are developments in engineering for scaffolding into hosted Blazor WebAssembly projects that we haven't documented (*yet!*). You can find and read the closed issues on the product unit's repo. Try this set of search results ...

https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+label%3Aarea-blazor+scaffolding

The updates that should have fixed scaffolding in hosted Blazor **_are for 5.0_**, which is releasing soon. I'll go through the updates and see what content we need to produce.

Because the *Server* project of a hosted solution is just an ASP.NET Core app, all of the usual Identity guidance should apply. **_However,_** if your goal is to have Razor components in the client-side app work like scaffolded Identity webpages, there are no such Razor components OOB ... you'd need to create your own or find some on the Net or use a 3rd party lib. There have never been (and they don't currently plan to have) Razor component versions of Identity pages. However, developers have managed to create such Razor components on their own. I've spoken with a few devs who had success in this area, so I know the resources are out there. If you search the issues around here (on these official repos) that discussed it and on the Net (blogs, SO posts, 3rd party GH repos, [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor) links), you should be able to track down examples. Management here has decided not to create such Razor components for the framework or document examples. I think the reason is that there's too much churn and it would create too much overhead for the product unit and docs cats (*me!* lol). Maybe *one day* such Razor components will be a thing, but not in the foreseeable future.

Leave this issue open. I'll use your issue to track updates for 5.0 content that pertains to scaffolding into hosted Blazor WASM, and I agree that we should have a section on it. Until I work on this, take a look at those engineering issues/PRs, especially the ones they marked **5.0** and **Done** to see how to workaround problems in 3.x and what you'll be able to do in 5.0 when it releases.

@Rick-Anderson ... I'm going to mark this one for me and put it on the Blazor.Docs project for work. I should be able to resolve it within a couple of weeks.

**Comment by guardrex** [comment]
... and **Note to Self** ... we should have a scaffolding link in the Blazor ToC that links to this topic since we decided to keep all of the scaffolding together in one place. IIRC, the reasoning was that scaffolding Blazor has always just been ASP.NET Core scaffolding for an ASP.NET Core-type of app, be it Blazor Server or the *Server* project of a hosted Blazor solution. However, I'd like a better cross-link so that devs can find this topic when navigating in the Blazor ToC node.

**Comment by dajma00** [comment]
Hi Luke,

Good job man! You always respond. I am surprised.

Yes, having a section on WASM should be helpful for devs.

Best,
Amjad.

________________________________
