### ISSUE TITLE
Create current .NET version of Specify the .NET Core SDK version

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#20326]
Create 3.1 and 5.0 versions of [Specify the .NET Core SDK version](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-5.0&branch=pr-en-us-20324&tabs=visual-studio#specify-the-net-core-sdk-version) 
Make each a separate doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-5.0&branch=pr-en-us-20324&tabs=visual-studio#specify-the-net-core-sdk-version)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
I think it'd be great if we could have a doc that shows folks how to deploy a .NET 5 app using self-containment. 

1: Show how to do a `dotnet publish --self-contained`, taking care to also show customers how they can figure out if their app service is x84 or x64 (since a surprising number of customers don't know this)

2: Show how to do the self-contained publish using Visual Studio, and Visual Studio for Mac. 

3: Ideally we could also show how to publish using VS Code's App Service tools. 

If we could have a pivot button at the top, too, I think that'd be swell.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
