### ISSUE TITLE
Expand the Blazor InputFile docs to include docs on sending the files to the server in a WASM app

### ISSUE THREAD

**Issue by pranavkm** [dotnet/AspNetCore.Docs#20323]
[EDIT by guardrex to add the metadata]

This doc article: https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@pranavkm ❓ on this one. What we could do is have a hosted sample app for this. Before we broach the question of *who* produces such a sample (likely you or I ... I guess), do you know if there's an existing hosted sample for this scenario in someone's repo ... yours or perhaps Javier's repo?

**Comment by guardrex** [comment]
**Note to self**: The existing sample app doesn't follow all of the doc code conventions (e.g., access modifiers). Perform a quick update to bring it inline with the rest of the doc examples/samples.

**Comment by pranavkm** [comment]
@guardrex I don't think one exists as yet. I think most of the work here was to verify that things like MultipartFormContent that you would use to send a file work with `InputFile` and that you can reliably read the content in the server. Let me try and put together an app for this.

**Comment by guardrex** [comment]
Ok ... if you'll provide the app, it will be a snap for me to handle the description.

**Comment by guardrex** [comment]
@pranavkm ... Checking in on this one.

For Blazor `InputFile` that sends files to the server with `MultipartFormContent`/etc., did you want to produce a quick-'n-dirty sample app for it that I can convert into coverage? ... or should I take a stab at it myself (e.g., if you're busy these days and know it will take quite a while for you to reach).

Alternatively, you can let me know if you think this issue is really either a P2 issue ... or even a P3 issue ... and I can push it back for a future month. If so, what priority should I give it?

My goal is to close out as many P1 issues as possible right now and then return ASAP to UE passes on topics. That's why I'm asking about this issue ... it's currently a P1.

**Comment by scottaddie** [comment]
See the sample app from Ed in the closed issue linked above. I'm guessing pieces of this can be included in the doc.

**Comment by guardrex** [comment]
Yes, that's right. This was already just about to hit. I had a lot of return-from-holiday issues and some other pressing P1s to address. This one is coming up **_real fast_** 🏃 for work.

**Comment by guardrex** [comment]
@EdCharbeneau ... We can use your bits with our coding conventions (I'll touch it up for the PR) and give you credit in the topic, which can cross-link your community work. If that's ok, I should be able to knock this out today. It's definitely a ⌚-saver for a *busy green dinosaur* 🐲🏃.

We don't usually cross-link such resources directly, including in our *Additional resources* sections, outside of [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor) because they usually go stale quickly and we can't confirm valid guidance in external resources.

Via the author byline, we usually cross-link to a contributor's blog website or GH profile. Is it ok if we use your code as the basis for the PR section on this? If so, where do you want your author byline link to go?

Side Note: I see your Blazor Power Hour listed at Awesome Blazor in **Other**. AFAICT, you're the only one listed there offering a weekly live coding show. Perhaps, Adrien should have a **Live Coding** section 🤔 ... or maybe **Twitch Live Streams** ... something along those lines. **_YOU_**  might be the only one in such a section because *Live game development*, which is the only other listing that looks like it was envisioned as a regular show, is dead ... their three links 404 at Twitch.

**Comment by guardrex** [comment]
@EdCharbeneau ... Do you want to write the initial section for the topic? That might be fun ..... *or not* 😄 lol. What we'd do is settle on a section heading and the structure would be as simple as ...

* Section heading &mdash; Probably *Send files to a server* ... or something else. TBD ... any other i-dears?
* Introductory paragraph &mdash; Just the basics of what will be shown ... a few sentences. I'll pitch-in with API cross-links and bits.
* Code - Component followed by Controller &mdash; You can just place your code there in its present form. I'll take care of the coding conventions.

... which could be a formal PR, or you could paste the whole thing right into a comment on this issue. I'll create the PR from that.

What I'd do after touching it up to our coding conventions with grammar updates is circle back around on the coverage when I reach this topic on my UE passes on https://github.com/dotnet/AspNetCore.Docs/issues/19286. We can have minimal coverage right now mostly focusing on the code. I'll probably work on 🌷 *guidance beautification* 💐 on that whole-topic overhaul later.

If you're too busy or have no interest in writing the section, that's cool. I'm just trying to ...... er ...... well .......  🙈 *talk you into contributing so that I can go work on something else* 🙈😄 lol.

**Comment by EdCharbeneau** [comment]
> Via the author byline, we typically cross-link to a contributor's blog website or GH profile. Is it ok if we use your code as the basis for the PR section on this? If so, where do you want your author byline link to go?

A link to my website would be great: https://edcharbeneau.com/

Let me take a stab at the heading > intro. At the very least it will give you a starting point. I'm used to the experience of being an author and having work edited, please feel free to take and adapt as you see fit (I won't take it personally).

**Comment by guardrex** [comment]
Sounds great. If you just want to paste it into a comment here, that's good. Then, I'll pull the code for it from your cross-linked repo on the other issue.

**Comment by guardrex** [comment]
Thanks @EdCharbeneau ... I have the link to your coverage in your repo. I'll take that text and example code and make a PR out of it. I'll ping u on that when it goes up. Thus far, I 🤞🍀 **_should be able to reach this_** 🤞🍀 Saturday morning. No promises tho 😅 ... 🏃🏃🏃🏃🏃🏃🏃. I'll get back to this *ASAP*.

**Comment by guardrex** [comment]
@EdCharbeneau @pranavkm ... Let's put a little 🥩 on the 🦴 here. I'd like to do the following ...

* Build on the existing client-side example that merely shows thumbnails. For the server upload example, let's continue to show thumbnails with the new code client- and server-side that handles the upload.
* Let's provide a **_multiple file_** uploader for this, which is a bit more challenging to work out. Single file upload is fairly easy to build (or strip down to from what we can show for multiple file upload).
* Let's DO and not DO some things ...
  * Let's **_not_** show an example of accessing untrusted/unscanned files. For example, files shouldn't be directly uploaded to webroot 😨.
  * Let's **_not_** trust the provided file names for storage or display.
  * Let's show how how to limit the number of files client- and server-side.
  * Let's show how to limit the size of files client- and server-side.
  * Let's do some server-side logging along the way.

I have worked up a prototype for this based on your, @EdCharbeneau, example, but I'd like to sleep on it for a night and post it after some more tinkering. I'll post it here on Tuesday for discussion.
