### ISSUE TITLE
Reference to AuthenticationService but no explanation where to find it....

### ISSUE THREAD

**Issue by ericsson007** [dotnet/AspNetCore.Docs#20335]
In the section https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-3.1#handle-token-request-errors there is a line `var tokenResult = await AuthenticationService.RequestAccessToken(` but there is nothing mentioned about to reference, or create the AuthenticationService

So this section looks a bit incomplete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f3209c-2414-9b35-6245-383c9b7c6338
* Version Independent ID: cc8dfcd6-8d93-5aa3-c381-2b613e88cdbe
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-3.1#unauthenticated-or-unauthorized-web-api-requests-in-an-app-with-a-secure-default-client)
* Content Source: [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ericsson007 ... Yes, that's unfortunate naming. That example arrived from engineering like that, and I didn't spot it. I was probably distracted and 🏃 on other things at the time. The earlier examples, and examples elsewhere in this node, use ...

```razor
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication
@inject IAccessTokenProvider TokenProvider
```

... **`TokenProvider`**. I'll update it, and I'll include the namespaces and `@inject` directives for the whole example, possibly with cross-links to either (or both) API docs and docs in this node.

I see that the JS interop service is also absent in this example. There's a bit of inconsistency on `IJSRuntime`, too. Sometimes it appears in examples as `JSRuntime`. Sometimes, you'll see it as just `JS`, as it appears here. I'll clean that up, too.

**_AND ..._** there are some inconsistencies in other service naming. For example, `HttpClient` comes into various examples with different names, such as `httpClient` (as it appears here), `Client` (one spot), and often as `Http`.

These inconsistencies are the product of a few factors, mostly because different engineers submitted doc examples at different times with different favorite-naming approaches. What I need to do is go through all of the topic examples and make all of the topics consistent.

There will be a short delay on these updates to probably next week (or *three weeks!* 😅) due to .NET 5 work. We're getting close to release, and those issues take priority over everything else at this time.

Thanks for opening this. I'll use this issue to do the work. Leave this issue open. It will close when the PR merges later.
