### ISSUE TITLE
Blazor WebAssembly Hosted Azure AD Authorization Failed

### ISSUE THREAD

**Issue by scdehmlow** [dotnet/AspNetCore.Docs#20369]
I tried creating a sample ASP.NET Core hosted Blazor WebAssembly project that uses Azure AD by following this guide but I am getting the following error. Am I missing something?
```
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
```
I also noticed that in step 5 of the Register Client App section there was no checkbox to clear on the portal.

Using .NET 5 RC2 version 5.0.0-rc.2.20475.5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3039ff79-ee86-20b1-0082-d3899a84c823
* Version Independent ID: af4a3a75-ae52-5f6d-2120-737bc2fefb07
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @scdehmlow ... Generally, we get these types of issues due to misconfiguration. You should walk the topic's sections and compare to your app to see if you can identify it. Unfortunately, we don't have the staffing to provide product support. Reach out to devs on the usual support channels. If you narrow it down to something specific, please do let us (me) know.

WRT Step 5 ... 

<img width="405" alt="Capture" src="https://user-images.githubusercontent.com/1622880/97760606-87935980-1ad1-11eb-9608-098a1fe997a1.PNG">

**Comment by guardrex** [comment]
@scdehmlow ... I'm going to close this because we don't have anything actionable for documentation updates at this time. As I mentioned earlier, the vast majority of the problems reported here of this nature usually are the result of app or Azure misconfiguration. I recommend going through the topic's sections carefully confirming that the app and Azure config is correct. Also, keep in mind that stale cookies can break an app during testing. See the *Troubleshoot* section for details.

If you find out the cause and think that a doc update is called for, please do open a new issue from the bottom of this topic.

If you need to chat with other devs, we recommend the following support channels ...

* [Stack Overflow](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Blazor)

**Comment by scdehmlow** [comment]
@guardrex Thank you for the response. I went through the configuration and found the issue. The dotnet cli new command prepends the scope uri with a `api://` making it `api://api://{...}` rather than `api://{...}` in the client's Program.cs when you enter the command as specified in the topic. I'll create a new issue to address this specifically.

**Comment by vllama** [comment]
Hi, That checkbox option no longer exits when setting up an app in azure ad.
I am getting the same error with the initial empty blazor webasm app ( created by dotnet new)
I simply added the configuration to Main and I get the same error.

**Comment by maixnor** [comment]
I found that checkbox setting in an existing application registration under the API permissions.

![image](https://user-images.githubusercontent.com/46966993/158079768-b6a4b0fa-3d58-4343-a712-4fe7a2a78cf4.png)

Hope it helps.
For me the issue still persists
