### ISSUE TITLE
[Blazor] Migration for standalone Blazor WASM security

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#20400]
For standalone apps, users need to include a scope so that the app works. Possible solutions are 
```csharp
options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/user.read");
options.ProviderOptions.DefaultAccessTokenScopes.Add("openid");
```

We should also point out to people performing migrations that they need to update their redirect URI registration in the portal to be a SPA redirect URI instead of a Web redirect URI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce89fc06-2c18-fbf8-0ac5-f50d41a67d8a
* Version Independent ID: 490b7aec-0d31-9032-cb1d-ffcdfea5c976
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The last bit is covered ... it's Step 4 of ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-5.0

I didn't think that `User.Read` would be required for merely auth. Currently, the topic has (at the bottom of that same section) ...

```csharp
builder.Services.AddMsalAuthentication(options =>
{
    ...
    options.ProviderOptions.DefaultAccessTokenScopes.Add("openid");
    options.ProviderOptions.DefaultAccessTokenScopes.Add("offline_access");
});
```

... but I'll update tomorrow morning with the scopes you provided.

**Comment by javiercn** [comment]
I didn't see that, we shouldn't need additional steps for this, we should have done it within the framework if this caused issues.

From my testing, we just needed to add a scope to keep msal.js happy in this case.

**Comment by guardrex** [comment]
Ok .... I'll just run a quick test in the morning to make sure that my test app doesn't :boom: on me and make the update first thing ... *~5am!* 🐓 ... thanks to the family :cat2: waking me up daily. *Rotten 😼!*

**Comment by guardrex** [comment]
@javiercn I'm not seeing this requirement (**_yet_**) ...

<img width="743" alt="Capture" src="https://user-images.githubusercontent.com/1622880/98113226-f9b8c500-1e68-11eb-8f79-3e24326ce7df.PNG">

My test app doesn't have `User.Read` permission, either in the app as a default scope or in the portal as an app scope. It only has `openid` and `offline_access`. Also, when a B2C app is created in the portal, Azure doesn't give it `User.Read` by default. Therefore, I'm a bit confused on why it would be added to the app when the app isn't (apparently) doing anything with it on the Azure side in the base case ... i.e., just logging someone in and **not** trying to do read/use user profile data.

If you're saying that it should be added to the doc for cases where they are going to need the scope, then I think we should add it to the *Default token scopes* section as an example/mention ... something like the following, which also tells the reader that it must be configured in the portal, too .........

> For example, an app that's configured in the Azure portal with Graph API `User.Read` scope to read the user's profile or company data includes the `User.Read` permission in its default access token scopes:
>
> ```csharp
> options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/User.Read");
> ```

... **_OR_** ... I'm just missing something here and it **_must be added_** to the base case instructions at the top of the doc for some reason that I'm not seeing here. In which case tho, clarify this for me ...... shouldn't if we're going to require them to add this to the default token scopes of the app they should also provide the scope in the app's registration manually because Azure doesn't add it by default? It seems like we'll have to tell them to do it in the portal, too.

**Comment by javiercn** [comment]
@guardrex you are right, I believe is AAD that does this (give access to graph automatically), I think we need to cover this in the migration for 5.0 (the fact that we have to add an additional scope).

This should have been in the template all together, so I'll file an issue on the product to track it.

Also I played yesterday with upgrading to the latest msal version, and that seems to remove the need for this, so while more investigation is needed, it might be an option.

**Comment by guardrex** [comment]
Yes, in the AAD case (for 5.0), we have it at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-5.0

... that text reads ...

> Add a MsalProviderOptions for `User.Read` permission with `DefaultAccessTokenScopes`:
>
> ```csharp
>  builder.Services.AddMsalAuthentication(options =>
>  {
>      ...
>      options.ProviderOptions.DefaultAccessTokenScopes
>          .Add("https://graph.microsoft.com/User.Read");
> });
> ```

I'll make this issue about the migration topic then. I'll call out both of those little bits that I added for 5.0 to the Blazor security topics about the scope requirements of each type of app. For the AAD case, it's the `User.Read` scope. In the AAD B2C case, it's the `openid` and `offline_access` scopes.

I'll take care of this within the next few hours.
