### ISSUE TITLE
Document not make clear how to Implement a custom AuthenticationStateProvider In Topic Implement a custom AuthenticationStateProvider

### ISSUE THREAD

**Issue by uopeydel** [dotnet/AspNetCore.Docs#20429]
Document not make clear how to Implement a custom AuthenticationStateProvider In Topic Implement a custom AuthenticationStateProvider

This [Linkl](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-3.1#implement-a-custom-authenticationstateprovider) show topic name   **Implement a custom AuthenticationStateProvider** Not show anyplace to make me know how to authen with username and password.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75d9405-19a5-a14b-3a09-a3605b240750
* Version Independent ID: 1247ee64-fbc9-ce29-0710-f6e59380f5ee
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @uopeydel ... That's right. We don't currently have a simple explanation/example/sample of how to do that. The product unit only provided the OIDC/OAuth approaches in the Blazor WebAssembly node (Auth lib, AAD, B2C, Identity Server).

I've marked this issue for triage, and they'll let us know if they want to provide this coverage and what/how to cover it. There will likely be a delay before we hear a response because 5.0 GA is about to be released, and everyone is 🏃😅 working hard to get that release done and out. Then, the holidays ⛄ will arrive, so I'm not sure when they'll get to this. They may say *Yes!* ... that they do want to provide the coverage ... but not be free to produce the content for it until next year.

In the meantime, we recommend that you look on the Net for community examples/samples. Try the usual public support channels ...

* [Stack Overflow](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Blazor)

... and of course via just searching around the Net. There might be something at [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor), too.

**Comment by guardrex** [comment]
I'm going to close out this ancient issue 👴 as a *won't-fix* at this point. We don't support this scenario AFAIK. Seek support for it on the usual public forums (*at your own risk, of course!* 😉).

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)
