### ISSUE TITLE
"System.Security.Cryptography.X509Certificates is not supported on this platform" Error

### ISSUE THREAD

**Issue by pjgpetecodes** [dotnet/AspNetCore.Docs#20443]
Running this sample gives the following error in the browser console.

"System.Security.Cryptography.X509Certificates is not supported on this platform".

**Framework Version:** .NET 5 RC2
**Browser:** Chrome and Edge

Same issue whether run from the CLI or the latest VS.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by pjgpetecodes** [comment]
Ah... The SignalR package needs updating when using .NET 5...

```
dotnet add Client package Microsoft.AspNetCore.SignalR.Client --version 5.0.0-rc.2.20475.17
```

**Comment by guardrex** [comment]
Yes, @pjgpetecodes ... The docs are package-version agnostic in that regard. We don't place the actual versions (preview versions) into the preview docs because we would need to update ALL of them for each preview release and then at GA. There would be many, many to update each time a pre-release came out and then again when we reached GA. We just don't have the staffing to do it. We rely upon the dev to *magically know* a bit about preview packages for each pre-release period. I'm sorry that it slowed you down a bit. The good news is that we're close to 5.0 GA, and we'll be able to put this behind us soon for 5.0 ....... until the next pre-release period, of course. :smile:

**Comment by pjgpetecodes** [comment]
Sounds perfectly fair @guardrex ... Thanks!
