### ISSUE TITLE
Bind Across more than two components section is confusion

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/AspNetCore.Docs#20479]
I am struggling to follow the example give for ParentComponent/ChildComponent/GrandChildCompoment.

In general, it is a great example, but the naming conventions used in the code make it difficult to follow:

From ChildComponent
1. public string Property: "Property" is not a good property name as it is too generic.  Even "MyProperty" or "Message" would be less confusing.  
2. public EventCallback<string> PropertyChanged is not a good name. "MessageChanged" or even MyPropertyChanged would be better. 
3. private string BoundValue: Not so bad, but a concrete example would still be better.

These same property names are then used again in GrandChildComponent further mudding the waters.

I would use `ChildProperty` in the child and 'GrandChildProperty' in the GrandChild.

This may seem niggling, but after several hours of trying to follow it and write my own sample to ensure I follow it, I felt compelled to pass this on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gregoryagu ... Thanks for the feedback. *Yes!* on moving it away from `Property`/`PropertyChanged`. I think `Message`/`MessageChanged` is a good approach. *Oh ... plz NO on `My`.* :smile: I've moved completely away from `My`-named things in code examples/samples. WRT changing the property name between Child and GrandChild, that would be a reversion back to the way that I had it before. I don't mind. I really think it's ok either way; but since we're changing it anyway, let's go ahead and revert it back. I'll go with `ChildMessage`/`ChildMessageChanged` and `GrandchildMessage`/`GrandchildMessageChanged`. I'll also go with `parentMessage` var in the `Parent` component.

**Comment by gregoryagu** [comment]
Awesome!

Here is my version that I came up with:
Parent.razor
```
<h1>Parent Component</h1>

<p>Value in Parent: <b>@parentValue</b></p>

<p>
    <button @onclick="ChangeValue">Change from Parent</button>
</p>

<ChildComponent @bind-ChildValue="parentValue" />

@code {
    //This value flows DOWN to the child and grandchild.
    private string parentValue = "Initial value set in Parent";

    private void ChangeValue()
    {
        parentValue = $"Set in Parent {DateTime.Now}";
    }
}
```
ChildComponent.razor:
```
<div class="border rounded m-1 p-1">
    <h2>Child Component</h2>

    <p>Child Property: <b>@ChildValue</b></p>

    <p>
        <button @onclick="ChangeValue">Change from Child</button>
    </p>

    <GrandchildComponent @bind-GrandChildValue="IntermediaryProperty" />
</div>

@code {
    [Parameter]
    public string ChildValue { get; set; } //parentValue is bound to ChildValue, so ChildValue will always reflect the parentValue.


    [Parameter]
    public EventCallback<string> ChildValueChanged { get; set; } //The parent view registers a callback here.

    //Because you cannot bind the grandchild directly to a Parameter, an intermediary property is needed.
    //So when the GrandChild property is changed, it is sent directly to the parent, and then flows down again through the bound parameter.
    private string IntermediaryProperty
    {
        get => ChildValue;
        set => ChildValueChanged.InvokeAsync(value);
    }

    //By invoking the callback, it flows the change to the Parent (any subscribers);
    private async Task ChangeValue()
    {
        await ChildValueChanged.InvokeAsync($"Set in Child {DateTime.Now}");
    }
}
```
GrandChild.razor:
```
<div class="border rounded m-1 p-1">
    <h3>Grandchild Component</h3>

    <p>Grandchild Property: <b>@GrandChildValue</b></p>

    <p>
        <button @onclick="ChangeValue">Change from Grandchild</button>
    </p>
</div>

@code {
    [Parameter]
    public string GrandChildValue { get; set; }

    [Parameter]
    public EventCallback<string> GrandChildValueChanged { get; set; }

    private async Task ChangeValue()
    {
        await GrandChildValueChanged.InvokeAsync($"Set in Grandchild {DateTime.Now}");
    }
}

```

**Comment by guardrex** [comment]
Close enough :smile: to what I have on the PR ... I agree with the improvements that we've made.

btw -- Just so you know. We can't put code comments into examples any longer in most cases because they don't machine translate into other languages.

also btw -- There's almost no text in this case to explain the example. I'm performing UE (user experience) updates on docs over the holidays ⛄. When I reach this topic for updates, I'll add some explanatory text to help explain it out. For now, this should be sufficient.

**Comment by gregoryagu** [comment]
Excellent, thank you so much!
