### ISSUE TITLE
Two App Registrations?

### ISSUE THREAD

**Issue by taylorchasewhite** [dotnet/AspNetCore.Docs#20512]
I'm a bit confused as to the overall architecture here. So with Blazor WASM Hosted using AAD for Auth, are we saying that we need to create two different app registrations, one for the server API and one for the client?

I understand the desire not to explain/re-explain an app registration in a Blazor web doc, but I think some explanation of the overview/background behind all of the steps involved here would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3039ff79-ee86-20b1-0082-d3899a84c823
* Version Independent ID: af4a3a75-ae52-5f6d-2120-737bc2fefb07
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by taylorchasewhite** [comment]
Even just like an end state set of images showing what is configured in Azure would be helpful (food for thought).

**Comment by guardrex** [comment]
Hello @taylorchasewhite ... These are considered *advanced* topics for these scenarios, so we do assume (and cross-link in Azure docs) a number of basic concepts. I probably will try to improve the introductions of these topics when I reach this topic for a UE (user experience) pass this ⛄ *holiday* 🎁 when I have more time on https://github.com/dotnet/AspNetCore.Docs/issues/19286. 

WRT the two registrations ... The product unit recommends that the client (one AAD registered app) authenticates the user for the client app, and the user/client is configured to authz for access to the server API (a different AAD registered app). It's a general security best practice notwithstanding any technical barriers to using one registration.

btw ... We avoid images, especially because the portal changes every 7.5 minutes :smile:. We can't keep up.

I'll cross-link this to my tracking issue so that I review your suggestion when I reach these topics. Thanks for commenting.

**Comment by taylorchasewhite** [comment]
Sounds good. FWIW, following the steps correctly in .net 5 I had no issue linking everything up. It just surprised me because I didn't remember creating two app registrations the first time around way back when I first created an app. So from an accuracy standpoint, it looks good! 

And makes sense on screenshots. 

My only critique is that I just wish I knew _why_ I was doing what I was doing, but I suppose that's more of an assessment of my understanding than this Blazor doc :)

**Comment by guardrex** [comment]
They'll say that it's a security best practice. Different apps should always have *separate registrations* in AAD/B2C.

It also hampers some flexibility in terms of pointing a client app at a different server API and/or making changes to either app's registration ... you can't customize anything by-app if they're sharing a registration.

> two app registrations the first time around way back when I first created an app

I'm not saying it wouldn't work ... just that it isn't recommended.
