### ISSUE TITLE
Anchor links does not work in docs website

### ISSUE THREAD

**Issue by dsychin** [dotnet/AspNetCore.Docs#20529]
The links under "Where to persist state" does not work.

It seems that the id in the html has `-1` appended to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae14b3e3-3271-b919-9e0a-6f317a6b2d2d
* Version Independent ID: e5e1273b-195e-5da1-b4aa-66bbcff1425b
* Content: [ASP.NET Core Blazor state management](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/state-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dsychin ... The cause is covered here :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/17491; except in this case, it isn't version sections of the topic with the same headings, it's the doc pivot between WASM and Server that have the same headings. I'll fix it up ... I have a decent workaround for this scenario that's working well in the Blazor Server-EF Core topic. Thanks for reporting this.
