### ISSUE TITLE
Unmarshalled JavaScript Isolation Code sample is incorrect

### ISSUE THREAD

**Issue by sps014** [dotnet/AspNetCore.Docs#20598]
Unmarshalled JavaScript Isolation Code sample is incorrect
```cs
var unmarshalledRuntime = (IJSUnmarshalledRuntime)js;
var jsUnmarshalledReference = unmarshalledRuntime
    .InvokeUnmarshalled<IJSUnmarshalledObjectReference>("unmarshalledInstance");

string helloWorldString = jsUnmarshalledReference.InvokeUnmarshalled<string, string>(
    "helloWorld");
```

Error
```
There is no argument given that corresponds to the required formal parameter 'arg0' of 'IJSUnmarshalledObjectReference.InvokeUnmarshalled<T0, TResult>(string, T0)'
```
incorrect line 👇
```cs
string helloWorldString = jsUnmarshalledReference.InvokeUnmarshalled<string, string>(
    "helloWorld");
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aada0049-99a8-2f91-5d60-6970474e2371
* Version Independent ID: c29fb1a8-028f-6efd-f1bc-e889fb362311
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#blazor-javascript-isolation-and-object-references)
* Content Source: [aspnetcore/blazor/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @sps014 ... This was one of the examples that came in directly from the product unit. Let me take a look and get by to you either later today or on Monday morning.

**Comment by guardrex** [comment]
@pranavkm ... I was playing around with this, and what I found in the framework tests [here](https://github.com/dotnet/aspnetcore/blob/master/src/Components/test/testassets/BasicTestApp/InteropComponent.razor#L198-L204) and [here](https://github.com/dotnet/aspnetcore/blob/master/src/Components/test/testassets/BasicTestApp/wwwroot/js/jsinteroptests.js#L222-L242) with [this](https://github.com/dotnet/aspnetcore/blob/master/src/Components/test/testassets/BasicTestApp/InteropTest/InteropStruct.cs) works. Could/should the example be more like that (example below :point_down:), or can you fix the example that we're showing? I couldn't make the existing example work on a first pass.

Whatever the case with that, there are a few more points on unmarshalled interop ...

1. Do we need to say that `int[]` and `string` between .NET and JS don't match and can't be passed back (?) without additional work per https://github.com/dotnet/aspnetcore/issues/21492#issuecomment-637201926. I say "back" because when I did a test trying to pass back a string, it didn't break but didn't work either. Passing back a `bool` or an `int` worked fine.
1. Do we need to call out that this scenario really isn't relevant for these types of examples ... that the perf difference is trivial for small bits of data and that this scenario would shine when moving large, complex objects?
1. The framework example has a JS `dispose`. Should that be included, as I have below?
1. Don't we need to call out that this scenario is strictly for WASM?
1. Given that this is an advanced scenario for perf-critical scenarios, it seems like it should be **_in its own section_**. Should I add a section heading right above where this shows up in the doc?

Here's an idea based on the framework tests ...

Inside the closing `<body>` tag of `wwwroot/index.html` ...

```javascript
<script>
  function returnJSObjectReference() {
    return {
      dispose: function () {
        DotNet.disposeJSObjectReference(this);
      },
      unmarshalledFunction: function (fields) {
        const name = Blazor.platform.readStringField(fields, 0);
        const year = Blazor.platform.readInt32Field(fields, 8);

        return name === "Brigadier Alistair Gordon Lethbridge-Stewart" && 
          year === 1968;
      }
    };
  }
</script>
```

`Pages/Hello.razor` ...

```razor
@page "/hello"
@using System.Runtime.InteropServices
@using Microsoft.JSInterop
@inject IJSRuntime JS

<h1>Say Hello</h1>

<p>
    @message
</p>

<p>
    <button @onclick="SayHello">Say Hello</button>
</p>

<p>
    <a href="https://www.doctorwho.tv">Doctor Who</a> 
    is a registered trademark of the <a href="https://www.bbc.com/">BBC</a>.
</p>

@code {
    private string message;

    private void SayHello()
    {
        var unmarshalledRuntime = (IJSUnmarshalledRuntime)JS;

        var jsUnmarshalledReference = unmarshalledRuntime
            .InvokeUnmarshalled<IJSUnmarshalledObjectReference>(
                "returnJSObjectReference");

        message = jsUnmarshalledReference.InvokeUnmarshalled<InteropStruct, bool>(
            "unmarshalledFunction",
            new InteropStruct
            {
                Name = "Brigadier Alistair Gordon Lethbridge-Stewart",
                Year = 1968,
            }).ToString();
    }

    [StructLayout(LayoutKind.Explicit)]
    public struct InteropStruct
    {
        [FieldOffset(0)]
        public string Name;

        [FieldOffset(8)]
        public int Year;
    }
}
```

**Comment by sps014** [comment]
Thanks @guardrex

**Comment by guardrex** [comment]
> Most people would be happy if they do no require to reference js in index.html

I was just taking the simplest approach to demonstrate the **_Blazor_** concept.

> ideal way code to import 

We have a little bit of coverage at, which I think you saw there above the unmarshalled interop coverage ...

https://docs.microsoft.com/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#blazor-javascript-isolation-and-object-references

... and I'll leave that to Pranav to remark further.

**Comment by sps014** [comment]
thanks once again @guardrex

**Comment by guardrex** [comment]
Ping @pranavkm ... Sorry for the double-ping (or perhaps ur OOF right now). This is a live topic doc bug 🐞. I can fix it, but it's best if we discuss it first ... https://github.com/dotnet/AspNetCore.Docs/issues/20598#issuecomment-727663432. I can ask Safia to help if ur busy/out.

**Comment by sps014** [comment]
How do you return Byte[] to C# side

i am trying this but always getting null c# side , even though js side i have UInt8Array

js side 
```js
readFileFFmpeg: async (obj) => {
            const h = Blazor.platform.readInt32Field(obj, 8);
            const p = Blazor.platform.readStringField(obj,0);
            const buffer = await ffmpegObjectInstances[h].FS('readFile', p);
            console.log(buffer);
            console.log(typeof (buffer));
            return buffer; //Uint8Array array
        },
```
c# side
```cs
         public byte[] ReadFile(string path)
        {
            var res= reference.InvokeUnmarshalled<FileConf,byte[]>("readFileFFmpeg",new FileConf() 
            {   
                Hash=Hash,
                Path=path
            });

            return res;
        }

        [StructLayout(LayoutKind.Explicit)]
        internal struct FileConf
        {
            [FieldOffset(0)]
            public string Path;
            [FieldOffset(8)]
            public int Hash;
        }
```

when i am calling this method from JS and returning unmarshalled array as `UInt8Array` and receiving as `byte[]`,
c#  side i get null, even though buffer is valid  `UInt8Array` js side
