### ISSUE TITLE
Use OnParametersSet instead of OnIntialized to set Parameter default value

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/AspNetCore.Docs#20602]
The correct place to set a default Parameter values is in OnParametersSet, not OnInitialized.

OnInitalized does not always run after parameters are set, so in those scenarios, the default will not be set, resulting in a null parameter.  OnParametersSet, however, always runs after parameters are set.

This sample shows the issue. Uncomment OnParametersSet and it will work correctly.

```
@page "/{text?}"

<h1>Blazor is @Text!</h1>
Click the following links:
<ul>
<li><a href="cool">Navigate to /cool</a></li>
<li><a href="awesome">Navigate to /awesome</a></li>
<li><a href="/">Navigate to /</a>  Default Value is not set from this link when using OnInitialized. Does work if OnParametersSet is used instead.</li>
</ul>

@code{
    [Parameter]
    public string Text { get; set; } = "fantastic";

    protected override void OnInitialized()
    {
        Text = Text ?? "fantastic";
    }

    //protected override void OnParametersSet()
    //{
    //    Text = Text ?? "fantastic";
    //}
}
```
Suggest:

Changing the sample to use OnParametersSet method instead of OnInitialized for setting Parameter default value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Ah ... I think that was a cut and paste error this weekend. I was (as usual) going **_VERY_** (too) **_FAST_**. 🏃

I'll patch that right now before anyone sees it. Nobody will ever know. 😉 lol

**Comment by guardrex** [comment]
Well ... at least I got it right in the sample apps ...

https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/common/samples/5.x/BlazorWebAssemblySample/Pages/RouteParameter.razor#L9

I didn't totally blow it. :smile: 🙈😄🙈😄

**Comment by guardrex** [comment]
Hold on a sec @gregoryagu ... I read that exactly backwards.

It doesn't work? Are you sure?  We always documented this (i.e., 3.x) as `OnInitialized`), and when I ran my local test it worked that way.

**Comment by guardrex** [comment]
I'll check again locally shortly. I'm completely buried in WASM security at the moment. 😨

**Comment by guardrex** [comment]
@gregoryagu ... I can't repro what you're saying here, and we always documented this for `OnInitialized` ... since the inception of Blazor IIRC. I checked both of the 5.x common sample apps (WASM and Server), and it seems to work here. I'm going to close this but ping @captainsafia in passing in case I'm missing a **_gotcha_** 😈 or something that changed for 5.x that I'm not aware of.

<img width="525" alt="Capture" src="https://user-images.githubusercontent.com/1622880/99268932-629a2880-27eb-11eb-96de-aef6ebae983f.PNG">

**Comment by guardrex** [comment]
**RE-POST** ... My head is out of WASM security, so I tested a bit more.

@gregoryagu ... I can't repro what you're saying here [for a non-index/non-default (landing) page]. We always documented this for `OnInitialized` ... since the inception of Blazor IIRC. I don't think it was ever considered that it doesn't run for the index (landing) page. I checked both of the 5.x common sample apps (WASM and Server). Ping @captainsafia on ...

> does not always run after parameters are set, so in those scenarios, the default will not be set, resulting in a null parameter. OnParametersSet, however, always runs after parameters are set.

> Default Value is not set from this link ...

"this link" refers to ...

```html
<a href="/">Navigate to /</a> 
```

> ... when using OnInitialized. Does work if OnParametersSet is used instead.

When not using the app's index (landing) page, it works ...

**With a param** ...

<img width="525" alt="Capture" src="https://user-images.githubusercontent.com/1622880/99268932-629a2880-27eb-11eb-96de-aef6ebae983f.PNG">

**Without a param** ... (btw - this also works if reaching the page from `Index.razor` with `<a href="/RouteParameter">Navigate to /RouteParameter</a>`) ...

<img width="600" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/99280634-2b317900-27f7-11eb-897c-da35ca23090b.PNG">

@captainsafia ... If we do need to make a change, please clarify it for 3.x vs. 5.0, too, as we'll need to keep the non-optional-parameter coverage until 3.1 reaches EOL ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-3.1#route-parameters

I'm thinking of the possibility that we would keep the `OnInitialized` coverage for 3.x because it **_was_** the correct choice for that version but go with `OnParametersSet` for >=5.0, if `OnParametersSet` is the right thing to show.

**Comment by guardrex** [comment]
More ...

I'm not sure that that's a viable test @gregoryagu. If you set an optional param on the index (landing) page of the app, the Blazor router chokes the navigation (i.e., it won't navigate anywhere ... it just takes the segment as a value for `Text` on the `Index` component and displays it). Even if I do navigate away from such an `Index` component (e.g., `/RouteParameter/xxx` to avoid choking the navigation) and then back to `Index` with a `<a href="/">Index</a>`, it does work as described ...

<img width="565" alt="Capture3" src="https://user-images.githubusercontent.com/1622880/99282680-a136df80-27f9-11eb-88a7-f5d9ef492f71.PNG">

**Comment by captainsafia** [comment]
AFAIK, we haven't changed anything with the way route parameters are set in 5.0 so using `OnInitialized` to set default parameters is the right call. `OnInitialized` is always called once before the component is rendered, so default parameters should be set there. `OnParameterSet` is called whenever parameters change, so you might end up overriding parameters inadvertently if default parameters are set there.

**Comment by gregoryagu** [comment]
@GaurdRex, I tested again on an inner page, and it works the same way.  The parameter is null on the third link.  If you use OnParametersSet, then it is set to 1 correct.

@page "/counter"
@page "/counter/{CurrentCount:int}"
<h1>Counter</h1>
<p>Current count: @CurrentCount</p>
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
<ul>
    <li><a href="/counter/42">Navigate to /counter/42</a></li>
    <li><a href="/counter/123">Navigate to /counter/123</a></li>
    <li><a href="/counter/">Navigate to /counter</a></li>
</ul>
@code {
    [Parameter]
    public int? CurrentCount { get; set; }
    void IncrementCount()
    {
        CurrentCount++;
    }

    protected override void OnInitialized()
    {
        base.OnInitialized();
        CurrentCount = CurrentCount ?? 1;
    }
    //protected override void OnParametersSet()
    //{
    //    base.OnInitialized();
    //    CurrentCount = CurrentCount ?? 1;
    //}

}

[Blazor University](https://blazor-university.com/routing/route-parameters/) makes the same point I am trying to make.

**Comment by guardrex** [comment]
@gregoryagu ... We don't document ...

```razor
@page "/counter"
@page "/counter/{CurrentCount:int}"
```

The following should work (*should* because I haven't used the constraints in testing ... *yet*) ...

```razor
@page "/counter/{CurrentCount?:int}
```

**Comment by guardrex** [comment]
You might need to open a product unit issue to discuss it further and then they/you can let me know what behavior(s)/example(s) would be best.

I really shouldn't guess, and @captainsafia doesn't have additional info .... and she knows a lot more is is a lot smarter than *green dinosaurs!* :smile: lol

**Comment by javiercn** [comment]
You should use on OnParameterSet if you have transitions in your app that render the same component (for example, go from "/customer" to "/customer/5" or vice versa.

**Comment by guardrex** [comment]
I'll add it to the coverage.
