### ISSUE TITLE
[Blazor][Server] Docs about how to avoid reliance on HTTP Context need to be in a more prominent place

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#20649]
Despite the fact that we have docs [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-5.0#pass-tokens-to-a-blazor-server-app), we keep getting issues about this.

I believe the problem is the topic is too specific to auth, and I would like us to have a separate topic in a different area that is more general. Something like:
Differences between Blazor Server apps and MVC apps, things to account for when developing blazor server apps, ASP.NET Core features you should avoid when developing blazor server apps or something like that.

And provide a more general guidance on things like HttpContext in addition to specific solutions on how to tackle the problem.

/cc: @danroth27

**Comment by guardrex** [comment]
Additional remarks ...

> I want to avoid talking about tokens specifically and have a topic about integration between ASP.NET Core and Blazor Server, and as part of that. The problem we have is that people end up using HttpContextAccessor because they don't find the current guidance, because is very specific to tokens.
> 
> My suggestion is that we create a new section about integration between ASP.NET Core and Blazor Server and we talk about these things in there. (Things from ASP.NET Core that people shouldn't use in their Blazor server apps and alternatives).
>
> Using the sample with tokens for this is unnecessary complicated and distracts from the main key learnings that we want people to get from here, which are what things they should avoid and how to solve the problem in a different way.
>
> So my proposal is to have a new topic on the index about integration between ASP.NET Core and Blazor server and discuss these topics there.

No real time wasted by reverting our approach on this to working off of the issue: I'll keep the branch and work it forward into a new PR later. It seems that we should adopt the approach where you provide the content in an issue comment with title and ToC location and then I'll work it into the branch with grammar/style nits and bits.

**Comment by javiercn** [comment]
Just keep in mind that when I file issues most of the time is so that I can track something for later, if you are unsure about what to do with any of them, ping me on it and we can discuss.

**Comment by MarvinKlein1508** [comment]
I want to point out this section on MSDN
https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0#implement-a-custom-authenticationstateprovider

I was having the same problem here before because I was not able to get required user data within `GetAuthenticationStateAsync`. With @javiercn 's example it is way easier to understand how to implement a CustomAuthenticationStateProvider.

The example shows it in a hardcoded way which always results in the user being authenticated as mrfibuli but not how to do it in a custom manner. 

I did many research on how to implement this correctly but couldn't find any reliable source to achive this, until I saw the example from javier.

**Comment by guardrex** [comment]
@MarvinKlein1508

> until I saw the example from javier.

I assume you mean in an engineering issue ... can you link that example/issue here for reference?

>  in a hardcoded way

The base coverage is only meant to introduce the concept ... the bare bones. Yes, it might be better as a more specific, common example, or it might be better to **add** a second, common, more specific example.

**Comment by MarvinKlein1508** [comment]
@guardrex 

> can you link that example/issue here for reference?

https://github.com/javiercn/blazor-server-aad-sample

Yes. I would really appreciate a more specific example here.

**Comment by guardrex** [comment]
That's not an auth state provider example. It's obtaining the access token in the Blazor Server app to make requests to secure resources. It's covered (in this somewhat buried and not easily seen 👀 spot) ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-5.0#pass-tokens-to-a-blazor-server-app

**Comment by MarvinKlein1508** [comment]
@guardrex what I‘m trying to say is that I need to get the data from HttpContext in my scenario for my AuthentificationStateProvider. 

It is possible to achive this with the mentioned example. Hope this males my point more clear for you.

**Comment by guardrex** [comment]
Did you try using the `TokenProvider` **pattern**?

AFAIK, anything can be assigned from `HttpContext` in `_Host.cshtml` to any property that you set up for `InitialApplicationState`. Then, they get assigned in `App.razor` to the `TokenProvider` properties that you set up. Then, you have them via `TokenProvider` (in theory 🤞) in the Blazor Server app just by injecting the service.

I've only personally used this code with the access token in testing the scenario for the doc. I haven't passed through other `HttpContent` data, but it should work in the same way following the same pattern.

There could be **_gotchas_** and edge cases that I'm not aware of.

**Comment by mkArtakMSFT** [comment]
@guardrex the ask here is to emphasize this in an existing documentation through some UI highlighting mechanism (box, bold, ...). What is the specific ask that you need our input on?

**Comment by guardrex** [comment]
@mkArtakMSFT ... I like Javier's idea, namely a topic dedicated to ...

> Differences between Blazor Server apps and MVC apps

The *Pass tokens* section is fine for addressing that specific scenario, but he's saying that it's too specific to help devs with all of the things that they need to keep in mind between the frameworks. It's also buried as a security detail back in the security group of topics.

I think this is a high-level/early subject to cover. I know from prior chats with Dan that he'd prefer to keep the *Hosting Models* article just focused on the hosting models, so that's **not** a good spot for something like this. I think that there are three potential locations for this new content ...

* If the content is somewhat short and not considered a top-level focus, it could be a section in the [Blazor *Fundamentals Overview* topic](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/).
* If there's more than a section's worth of content ...
  * If not a top-level focus, a **new topic** in the *Fundamentals* node of topics.
  * If this is a top-level focus, a **new topic** in the root. I recommend placing it early in the ToC, say immediately after the *Hosting Models* article in the ToC, noting that we need to be careful about discussing aspects of Blazor that haven't been covered that early. I've taken great pains over the years to stack coverage **general to specific** and **top to bottom** so that devs can read down the ToC (and top-to-bottom within individual topics) and not encounter concepts that first appear later in the ToC (or later in an article). Alternatively if Blazor concepts do need to be covered for this, I recommend placing the root-level **new topic** somewhere below the **Components** node of topics, below wherever the last dependent subject is covered. 

WRT content for this ...

* I'm aware of `HttpContextAccessor`, which is currently covered with an [INCLUDE file](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/includes/blazor-shared-state.md) that's injected at ...
  * The Blazor *Threat Mitigation* topic: https://docs.microsoft.com/aspnet/core/blazor/security/server/threat-mitigation#blazor-and-shared-state
  * The ASP.NET Core *Advanced* node `HttpContext` topic: https://docs.microsoft.com/aspnet/core/fundamentals/http-context#blazor-and-shared-state
* There's some content pertaining to deltas for Identity at https://docs.microsoft.com/aspnet/core/blazor/security/server/#blazor-server-uses-aspnet-core-identity.
* There's the passing tokens piece at https://docs.microsoft.com/aspnet/core/blazor/security/server/additional-scenarios#pass-tokens-to-a-blazor-server-app.
* State management specifics at https://docs.microsoft.com/aspnet/core/blazor/state-management?pivots=server.

Anyway ... you get the picture ... things are a bit scattered around **by subject matter** and not listed with cross-links in a central spot (e.g., an early section near the top of the ToC). It would be helpful for me if we could get a full list together of everything that the PU is getting issues on and then create a new topic that has:

* Its own guidance for things not currently covered.
* Some content perhaps moved to the new topic from where it currently exists elsewhere ... or perhaps content posted in two spots with an INCLUDES file, leaving it in its original location and placing it into the new topic.
* Cross-links to existing coverage where we'd like to leave what we have in place and not duplicate with an INCLUDES file.

I recommend we **start with a list** and figure out **where the new topic should appear**.

BTW ... WRT ...

> Just keep in mind that when I file issues most of the time is so that I can track something for later

I hope we avoid that as much as possible. I hope they'll open the issue on the PU repo first (and by itself initially). When the PU member gets to it and is ready for docs work, they then open the docs issue, assign me (if they didn't open the issue from the **This page** feedback form for an existing topic), and provide the content in an issue comment. The PU doesn't track on the issues here, so many of them end up lying around for over a year without action and without my ability to work them. Then, I need to pester them down the road for help to proceed.

**Comment by guardrex** [comment]
This has improved quite a bit over time on multiple PRs. Recently, I'll worked it further on [Additional IHttpContextAccessor coverage (dotnet/AspNetCore.Docs #28016)](https://github.com/dotnet/AspNetCore.Docs/pull/28016), where remarks were added in the Blazor *Fundamentals* > *SignalR* overview.

I think the final solution will come when ...

**[SignalR][Blazor] HttpContext and IHttpContextAccessor**
https://github.com/dotnet/AspNetCore.Docs/issues/14974

... is fixed. That will probably place content into either an existing SignalR doc or a new SignalR doc.

I'll cross-link the Blazor doc remarks to the new section (or new doc) when it appears. To track the Blazor work, I'm not going to leave this issue open. I'm going to place this on a general tracking issue that I use to monitor external work in the background.

**Comment by guardrex** [comment]
Note @javiercn that your opening comment states ...

> Differences between Blazor Server apps and MVC apps, things to account for when developing blazor server apps, ASP.NET Core features you should avoid when developing blazor server apps or something like that.

... so if you want a ***topic*** that doesn't only pertain to the `HttpContext`/`IHttpContextAccessor` but addresses other items that we should re-open this. However ... note that this issue has been here *forever* without PU content for any such article. I need at least a list of subject areas, then I can seek to research and write from there.

WRT a topic mostly focused on `HttpContext`/`IHttpContextAccessor`, let's let the newer issue track it ...

**[SignalR][Blazor] HttpContext and IHttpContextAccessor**
https://github.com/dotnet/AspNetCore.Docs/issues/14974
