### ISSUE TITLE
Duplicate heading: 'H2 'SQLite'

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#20648]
Any doc build produces the following error. 

Duplicate heading: 'H2 'SQLite'(tutorials/razor-pages/sql.md(392,1) -> includes/RP/sqlite.md)'. Each second level heading (H2) in an article must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.

![image](https://user-images.githubusercontent.com/3605364/99477292-4e8f1d80-28f6-11eb-8733-166f6a200beb.png)

**Comment by wadepickett** [comment]
@Rick-Anderson, thanks for the catch.   I thought where we are keeping multiple topic versions within one .md file, that we are not avoiding the H@ warning, but I must not be up on how we handle that.   What is the proper way I should fix this?
1. Use a different H2 for different versions in the same doc.   So the 5.x version has an H2 of  ## SQLite and the 3.x version has a different variation of the H2 so it is unique?
2. Move the RP/sqlite.md include contents into the topic, but don't change the H2?  We would still of course get a warning since it is duplicated across versions, but perhaps the issue is that we must not duplicate use of includes that would generate duplicate H2's?
Thanks for any insights.

**Comment by Rick-Anderson** [comment]
Open a bug on this. It's a bogus warning.
