### ISSUE TITLE
insufficient instructions to get B2C working

### ISSUE THREAD

**Issue by azahran007** [dotnet/AspNetCore.Docs#20663]
After creating the app and adding the additional options as instructed, I was unable to login still and getting: 

AADB2C90057: The provided application is not configured to allow the Auth Implicit flow

until I went to the manifest and switched oauth2AllowImplicitFlow  to true as per this document
https://docs.microsoft.com/en-us/skype-sdk/websdk/docs/troubleshooting/auth/aadauth-enableimplicitoauth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce89fc06-2c18-fbf8-0ac5-f50d41a67d8a
* Version Independent ID: 490b7aec-0d31-9032-cb1d-ffcdfea5c976
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @azahran007 ...

This is sounds like a similar scenario to when the `allowPublicClient` property is set to `false` ... it didn't matter under 3.x with Identity v1.0; but now under 5.0 with Identity v2.0, it will :boom: an app if it's set to `false`. I added a *Troubleshoot* entry for that one.

However, setting `oauth2AllowImplicitFlow` doesn't sound right to me. Implicit flow isn't what should be in use, so that being set to `false` should work. I just checked one of my B2C test app registrations, and it's set to `false`.

You are looking at the 5.0 version of the topic correct? ... which indicates that implicit flow should be disabled in the app's portal registration.

**Comment by guardrex** [comment]
@azahran007 I'm going to close this because it sounds like you're looking at the 3.1 version of the topic. Select the 5.0 version and set `oauth2AllowImplicitFlow` to `false`. If you did follow the 5.0 version of the topic, you can put up the app in a GH repo for me to inspect (removing any sensitive data/configuration) and snap an image of your app registration in the portal (hiding anything sensitive) and place it into an image here for me to inspect.
