### ISSUE TITLE
Had to enable Implicit Flow to get this to work

### ISSUE THREAD

**Issue by azahran007** [dotnet/AspNetCore.Docs#20685]
Hello,

I am not able to get this working unless I enable Implicit flow. Apparently it is confusing others too.
 

https://stackoverflow.com/questions/61563293/why-does-blazor-net-server-visual-studio-2019-set-up-aad-b2c-to-use-oauth-impli

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @azahran007 ... I think this is only the second such issue to arrive here.

The product unit is taking feedback ... for example :point_right: https://github.com/dotnet/aspnetcore/issues/27769. If that issue (or a different one) matches your scenario, you can add a :+1: to it with any relevant details in a comment or open a new issue with them for framework support.

In passing, note that I have two WASM security apps (standalone and hosted) based on B2C and Identity v2.0 following the current guidance for code+PKCE that both work.

This is likely going to be some kind of app or Azure configuration problem. At this time, I'm not aware of what the problem is, so there's nothing to document at this time. If you're able to determine what's breaking your app, please do write back on this issue so that I can possibly re-open this issue and work some additional content into the *Troubleshoot* section or the setup steps/migration topic.
