### ISSUE TITLE
Would it be too much to ask to properly explain this

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet/AspNetCore.Docs#20708]
There is a big problem with Microsoft. Seems like you guys don't like to explain how stuff can be done with your technology, kind of a way of feeling superior because you can and others don't. Well, let me tell that i'm getting a bit sick with that attitude. Sorry, but i must be harsh here. I'm spending a lot of time in things that should be straightforward. Why do you bother improving the technology if the no one or very few people are able to use it? To just to brag about that you can use it and other don't? Is it to fill up your ego?
I changed the Pizza Blazor Tutorial successfully to login in with google(the first one), but i cannot do it from scratch as i don't understand nothing about it and this page excels in not helping at all....

Why don't you make a web page for the community put in their doubts, subscribe to other doubts, so the major doubts get answered, and your answer get voted by us?
Many as i do, have doubts in many aspects of Microsoft technology. And we are completely alone. Scatered. And scatered doubts here and there. Many over Stackoverflow, getting explained by some more experienced programmers, and those doubts could and should be answered by those who make the technology. I think the current situation is a shame!!

I would just like to CLEARLY understand how the authentication works on Blazor WebAssembly, so i can make a direct authentication with Google at the click of a button, as i made in my repo of the pizza blazor tutorial(https://github.com/Ricardoaraujo00/Pizza-Blazor-Client) but from scratch!
Just that for now.
Sure there will be more doubts along the way, but for know it's that.

Take in consideration my suggestion of the page for doubts with votings on doubts and answers.
My entrance would be: How blazor WebAssembley atuhentication works and how to login with third party identity providers, with single button click, or using the custom users login "template"

I'm done.
Thanks
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75d9405-19a5-a14b-3a09-a3605b240750
* Version Independent ID: 1247ee64-fbc9-ce29-0710-f6e59380f5ee
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Ricardoaraujo00 ... I understand your frustration. I've been frustrated by docs in the past, too. I agree with several of your specific documentation points, but I can't address the general feedback in your opening remarks. I'm just a third-party vendor working on the Blazor docs. To express general feedback and to reach the right folks at Microsoft, open an issue in the general MS docs feedback repo at ...

https://github.com/MicrosoftDocs/feedback/issues

With regard to this topic (and this whole node of Blazor security topics), let me get back to you in the morning. I'm in Florida, and it's late here 🌙🥱🛌💤. I'll explain what's going on here ... why these docs are in this mediocre condition ... and I'll tell you more about upcoming improvements the security topics.

I'll get back to you in the morning ---

**Comment by guardrex** [comment]
This topic isn't the one that explains Blazor WebAssembly security concepts. This topic is high-level overview that covers all of Blazor (*Blazor Server* and *Blazor WebAssembly*). The more specific topic for Blazor WebAssembly is at ...

https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/?view=aspnetcore-5.0

If you want in-depth coverage on OAuth, OIDC, and the Microsoft Identity Platform, that information is in external doc sets. Start with their landing page at ...

 https://docs.microsoft.com/azure/active-directory/develop/

Below our Blazor WebAssembly overview topic, there are topics that pertain to Blazor WebAssembly. There are standalone and hosted scenarios for Active Directory and Identity Server followed by additional scenarios.

There's an existing work item for me to improve these topics ...

https://github.com/dotnet/AspNetCore.Docs/issues/19286

I've been too busy with basic feature coverage up until now (for example, .NET 5 just released) to perform full topic overhauls, but we're headed into the ⛄ *holiday season* 🎁, and my schedule tends to open up and provide more time to work on docs at the end of each year. 

With regard to a topic dealing with external providers (e.g., Google), there's an existing issue for that, too ...

https://github.com/dotnet/AspNetCore.Docs/issues/20175

... so management will consider it, and *Yes!* ... I think they will agree to add coverage to this doc set. Up to this point, there was at least one problem with providing such coverage. These external providers seem to work better with **_redirects_** to the Identity Provider for sign in ... not the **_pop-up_** approach that was available in 3.x. However, .NET 5.0 with a redirect option just came out last week. Now that we have that option, the other providers should work well with Blazor apps. I don't think that I'll get to that issue until early 2021. I only have a few weeks left before I leave on an extended vacation 😅. 

Given that I can't address your opening remarks and your following two requests are covered by existing issues, I'm going to close this issue. I'll cross-link your issue to my tracking issue so that I don't lose track of your remarks when I reach the Blazor auth node of topics. I will attempt to make it clearer where the Blazor WebAssembly overview is located from the landing topic and improve the cross-links to the external doc sets for in-depth coverage of basic concepts (i.e., OAuth, OIDC, and MS Identity v2.0 in particular). Also, there are new Blazor auth samples in the Azure docs repo (again, an external doc set) that I'd like to cross-link into our docs.

Thanks for your feedback. I assure you that I will act on your comments when I reach this group of topics.
