### ISSUE TITLE
404 /BlazorServerSample.styles.css for BlazorServerSample project 

### ISSUE THREAD

**Issue by DerekLiang** [dotnet/AspNetCore.Docs#20712]
# Issue description

When run the sample from the following folder `/aspnetcore/blazor/common/samples/5.x/BlazorServerSample`. Navigate to `https://localhost:5001` in the browser. The style is not correct. In the dev console of the browser, there is an 404 error for `https://localhost:5001/BlazorServerSample.styles.css`.

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.811 [/usr/share/dotnet/sdk]
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
# step to reproduce error

1. clone the master branch, 
2. enter to folder `/aspnetcore/blazor/common/samples/5.x/BlazorServerSample` of the repo
3. run `dotnet run`
4. navigate to `https://localhost:5001`
5. open devtool of the browser
6. it shows an 404 error for `https://localhost:5001/BlazorServerSample.styles.css`

**Comment by guardrex** [comment]
Hello @DerekLiang ... I can't repro that here ...

<img width="506" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/99887532-c5842900-2c0a-11eb-86b1-14dac02c9b1d.PNG">

<img width="515" alt="Capture" src="https://user-images.githubusercontent.com/1622880/99887536-c917b000-2c0a-11eb-80e3-c798545dfadb.PNG">

Open an issue for the product unit to investigate at ...

https://github.com/dotnet/aspnetcore/issues

Please add a `cc: @guardrex` to your opening comment there so that I can follow along.
