### ISSUE TITLE
What is the namespace or assemble for CustomValidator?

### ISSUE THREAD

**Issue by VR-Architect** [dotnet/AspNetCore.Docs#20724]
Using the example for CustomValidator on 5.0 preview but I am not able to find the namespace or assemble for it. Please add it to the example. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @VR-Architect ... As the topic indicates, your app creates it from `ComponentBase`. It isn't part of the framework, so there is no namespace other than one you provide it.

**Comment by guardrex** [comment]
The example in the topic uses the `BlazorSample.Client` namespace because that's the sample app that I used to test it. However, that's not typical of the examples that I place into the docs. I almost always remove the namespace because apps will cut-'n-paste the code right into their own app. Having something like `BlazorSample.Client` there often breaks an app, so I usually avoid them. I'll do that here when I get to this topic for a UE pass ("user experience", i.e., an overhaul) at some point.

**Comment by guardrex** [comment]
Actually, it's bothering me so much that I need to remove that right now. :smile: lol .... *I won't sleep easy tonight if I don't!* lol
