### ISSUE TITLE
Suggested Clarification 

### ISSUE THREAD

**Issue by CincySteve** [dotnet/AspNetCore.Docs#20722]
I'm not certain I'm thinking the right way about the relationship between a layout and the component(s) that are related with it.  As I understand it, this "relationship" can be made via the Default Layout routing, the _imports.razor Centralized Layout selection, or an explicitly Specified selection within the component(s).  This reads to me as though a (related) component "uses a layout" to provide surrounding markup that is always rendered when the related component is rendered, with the specific point of integration being determined by the layout's @Body reference.  If that's right, then saying something along those lines near the start of the article would help in my view..

Assuming this is a reasonable way to think about the relationship, then explaining how the Default Layout and MainLayout get connected with the main page (@page "/") would be helpful.  Does the main page (which is a component) become related to the MainLayout via the Default Layout routing?  If so, I think it would help to say something like that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d64b8062-f910-a918-c5db-b2b67708602c
* Version Independent ID: 56c6cc6e-be94-d164-947c-cb14dbe91a19
* Content: [ASP.NET Core Blazor layouts](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/layouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @CincySteve for this feedback ... I'll take a look at this, but it won't be addressed until 2021. I'm swamped with work 🏃😅 for the next couple of weeks and then out for an extended holiday vacation. I'll return in January to take a look.

**Comment by guardrex** [comment]
Hello @CincySteve ... I'm back from vacation now.

> Default Layout routing, the _imports.razor Centralized Layout selection, or an explicitly Specified selection within the component(s)

The guidance on these aspects is here:

* The *Default layout* section shows how to supply the layout in `App.razor`.
* Specifying the layout in the component is covered in the next section, *Specify a layout in a component*.
* Centralizing layouts via `_Imports.razor` files is in the section after that, *Centralized layout selection*.

Therefore, I don't see how we're lacking coverage or have poor organization. I don't think introductory remarks are required because the opening comments and example are short and thus quick to consume.

However, there will be work on this topic as part of [UE (user experience) updates](https://github.com/dotnet/AspNetCore.Docs/issues/19286), so I'll take another look when I circle back around to this. One of the things that I'm focusing on for these UE passes is how each topic structures its content ... ordering of sections ... section titles ... internal cross-links ... etc. I'll take another look when I circle back around to this later. I'm also aware of another issue that was opened in engineering to cover some additional details on how nested components and layouts behave. I'll work [that issue](https://github.com/dotnet/AspNetCore.Docs/issues/21126) before I get to the UE pass, and that update might require introductory remarks along the lines of what you're suggesting here.

> This reads to me as though a (related) component "uses a layout" to provide surrounding markup that is always rendered when the related component is rendered, with the specific point of integration being determined by the layout's @Body reference. 

I might work a bit more on this aspect when I reach this for the UE pass, but I don't think that there's much difference between what you said and what the topic covers. The topic just happens to use common examples of where reducing boilerplate code would be beneficial to make the same point.

> ... explaining how the Default Layout and MainLayout get connected with the main page (@page "/") would be helpful. Does the main page (which is a component) become related to the MainLayout via the Default Layout routing? If so, I think it would help to say something like that.

I might be touching this on https://github.com/dotnet/AspNetCore.Docs/issues/21126, where nesting seems to have led to confusion. I'll address this on that issue because the engineering issue (IIRC) speaks to a specific point of confusion about it.

Specifically WRT "the main page (which is a component) become related to the MainLayout via the Default Layout routing" ...

That's covered AFAICT via how the topic describes (and shows) the `Router` component in the `App` component. It says it and shows it with the example in the *Default layout* section.

Thanks for your feedback. I'll work on this topic and review your guidance again for possible updates on the two other issues that I mentioned.
