### ISSUE TITLE
Documentation misleading for net5.0 - Importing Component Library

### ISSUE THREAD

**Issue by srpeirce** [dotnet/AspNetCore.Docs#20726]
This is now misleading for `net5.0`.

You no longer need to add the css manually to your `Index.html` or `_Host.cshtml` for imported razor class libraries. 

The referenced libraries are added as `@import` statements to the `{BlazorDeployableProjectName}.styles.css`.

Many thanks,
Steve
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b709f5-e04e-fee3-7eea-1364893ab997
* Version Independent ID: a92c88d3-6ee8-1e69-f4c3-49eb82909746
* Content: [ASP.NET Core Razor components class libraries](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/class-libraries.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srpeirce** [comment]
![image](https://user-images.githubusercontent.com/12847647/99915297-cac0a100-2cfa-11eb-902a-ae2cc06cc904.png)

To confirm: ASP.NET Core 5.0 is selected in docs

**Comment by guardrex** [comment]
Thanks @srpeirce ... Javier said something about this IIRC. I thought I asked him what changed about static assets from RCLs, and IIRC he said that *nothing changed*. I'm trying to find his remarks now.

**Comment by guardrex** [comment]
The blog post isn't quite what I was looking for; but for reference, I quoted it here ...

https://github.com/dotnet/AspNetCore.Docs/issues/17191#issuecomment-597369447

**Comment by srpeirce** [comment]
Thanks for the link @guardrex 👍.

I think the dedicated page on [CSS Isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0) adds some clarity.

The `CSS Isolation` page tells you the generated path for the css, e.g. `_content/Experiment/Experiment.bundle.scp.css`.
It doesn't (unless I've overlooked it) tell you that you do not necesarily need to import each libraries css, through my observations they are automatically added to `{BlazorDeployableProjectName}.styles.css`.

I hope this helps.

**Comment by guardrex** [comment]
> I think the dedicated page on CSS Isolation adds some clarity.

Yes ... and that might be what @captainsafia was referring to in the presentation with Dan where this subject caught my :ear:.

Actually, it wasn't Javier ... it was Pranav whom I was chatting with about this. It wasn't RCLs, per se, it was packages created from RCLs.

My question ...

> We might be missing something pertaining to how NuGet packages supply static content ✨ auto-magically ✨ to the consumer in 5.0

His response ...

> The mechanisms haven't changed here since 3.1, there's nothing new to report here.

https://github.com/dotnet/AspNetCore.Docs/issues/20480#issuecomment-725592178

@captainsafia, @pranavkm ... I think I'll need help on this one because there are *perhaps* overlapping or narrowly distinct scenarios for any of the following ...

* RCLs vs. RCLs supplied by packages
* 3.1 vs. 5.0 scenarios
* standalone WASM vs. hosted WASM vs. Server scenarios
* CSS isolation interactions

Short of running a bunch of tests, I don't know how to change the doc (*if it requires changes*). Idk under what conditions `@import` statements take care of static asset references [and thus manual `<link>` statement(s) aren't required].

If you want me to work thru this on my own, that's cool ... I can do that ... but it will need to wait until early 2021 short of a *bug* 🐞 scenario with the doc because I've got a lot of work ahead over the next few weeks, then I'm taking an extended vacation over the ⛄ *holidays* 🎁.

**Comment by guardrex** [comment]
**_UPDATE_** ... I'm going to work through the scenarios on my own for this. I'll mark this high priority; but given that we need UE passes on https://github.com/dotnet/AspNetCore.Docs/issues/19286 performed asap, work on this issue will occur mixed into continuing UE passes. I'll try 🏃😅 to get to this within the next couple of weeks ... 🙏 *I hope!* 🏃🏃🏃🏃 ... and given time constraints, I'm going to focus the updates on 5.0 scenarios and assume that the 3.x content is satisfactory.

**Comment by guardrex** [comment]
Hello @srpeirce ... I finally made it to the RCL topic on the [UE passes](https://github.com/dotnet/AspNetCore.Docs/issues/19286).

Yes ... at the time, you were correct about this. At some point on a PR somewhere, it was updated. It now reads ...

> For library components that use CSS isolation, there's no need to explicitly link the library's individual component stylesheets in the app that consumes the library. The component styles are automatically made available to the consuming app.
>
> To provide additional library component styles from stylesheets in the library's `wwwroot` folder, link the stylesheets in the consuming app's `wwwroot/index.html` file (Blazor WebAssembly) or `Pages/_Host.cshtml` file (Blazor Server):

... the key word there is "*additional*," and I'll probably work on that bit for the updates.

**_What I'm about to describe isn't what you were calling out for a fix, but I'll just place it here for possible further discussion ..._**

When a separate stylesheet is used, then it must be linked. Here's the setup ...

1. Add a new background to the RCL's `wwwroot` folder that will be used for a style that will be used for a `<div>` later (`extra-background.png`) ...

   ![extra-background](https://user-images.githubusercontent.com/1622880/113288139-28ba5200-92b4-11eb-93ea-f5bd59ca21ba.png)

1. Add an extra stylesheet to the `wwwroot` folder (`extra-stylesheet.css`) with an `extra-style` for the upcoming `<div>` ...

   ```css
   .extra-style {
       border: 2px dashed blue;
       padding: 1em;
       margin: 1em 0;
       background-image: url('extra-background.png');
   }
   ```

1. Add the `<div>` with the style to the OOB `Component1` component (`Component1.razor`) ...

   ```razor
   <div class="my-component">
       This Blazor component is defined in the <strong>TestRCL</strong> package.
   </div>

   <div class="extra-style">
       This <code>&lt;div&gt;</code> is styled by the <code>extra-style</code> style<br>
       in a different stylesheet, <code>extra-stylesheet.css</code>.
   </div>
   ```

1. Of course, we'll consume that from the app (`Index.razor`) ...

   ```razor
   @page "/"
   @using TestRCL

   <h1>Hello, world!</h1>

   <p>Placing the <code>Component1</code> component from the RCL here ...</p>

   <Component1></Component1>
   ```

1. Run it ....... **_Yikes!_** 💥 ...........

   <img width="581" alt="Capture" src="https://user-images.githubusercontent.com/1622880/113288906-2278a580-92b5-11eb-81a0-a87c76b444f3.PNG">

1. Add a `<link>` for the stylesheet to the app's `wwwroot/index.html` ...

   ```html
   <link href="_content/TestRCL/extra-stylesheet.css" rel="stylesheet" />
   ```

1. *Lick'ed IT!* 🐄👅 .....

   <img width="577" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/113289040-4b009f80-92b5-11eb-80d2-80a2aa3a6d39.PNG">

......... soooo .............

I'll double-check the earlier fix for what you were calling out, and I'll work on the rest of the text and examples. If you have any further feedback, I'm :ear: here. However, I'll leave this issue closed given that I think this issue is fixed. Otherwise, thanks again for calling it out.

Also, I called out a bunch of 😨 **_worry wart_** 😨 things in the prior comment's list. I actually think that most of those are **_non-concerns_**. I'll check a few things ... run a few tests and whatnot ... confer with @daveabrock on CSS Isolation if I hit a snag with those aspects ... but at the end of the day, I don't think that most/all of those things are going to require special coverage. We'll see tho ... I'm just getting into this now. I'll try to remember to ping u on the PR in case you want to take a look at it later.

**Comment by guardrex** [comment]
OH! lol ... it was the PR for **_THIS ISSUE_** 🤦‍♂️ ...

https://github.com/dotnet/AspNetCore.Docs/pull/21197/files

Ok. I guess I cross-linked for my laundry list of **_probably non-concerns_** to address. :smile:

**Comment by srpeirce** [comment]
Awesome thanks, just out at the moment but I'll read your comments properly in a bit. Many thanks for looking at this 👍

**Comment by guardrex** [comment]
Very well ... I think what you were asking about is ok. I'll ping u on the PR in a day or next week.

I'm finding other things to fix. For example, there's coverage in the *Host and deploy* area that should be moved to this topic and fleshed out further.
