### ISSUE TITLE
Additional Blazor SignalR tutorial updates for 5.0

### ISSUE THREAD

**Issue by pmready** [dotnet/AspNetCore.Docs#20752]
I get a exception and I think it is due to loading version 5.0 of SignalR Client. But does that mean I need to either use an earlier version of the package or update the sample to .NET 5 overall
FileNotFoundException: Could not load file or assembly 'System.Text.Encodings.Web, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with a hosted Blazor WebAssembly app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@pmready ... I don't follow ... what did you do? ... update an existing 3.1 app to 5.0? ... start with a new 5.0 app?

**Comment by pugwonk** [comment]
I have this same issue (brand new app I created yesterday). I fixed it by manually adding the System.Text.Encodings.Web package, so I think there's a dependency missing somewhere.

**Comment by guardrex** [comment]
I see. I'll check and call it out. I can't get to this today, but I will look soon ... hopefully on Tuesday. 🏎

**Comment by guardrex** [comment]
I can't repro this scenario. I did find two tiny nits elsewhere, and I'll use this issue to fix those, but I followed the topic and didn't need to add a namespace or package reference for `System.Text.Encodings.Web`.

If you walk the the whole topic again from scratch and still see the need for an explicit package ref (and/or a namespace), then you would need to open an issue for the product unit to investigate why it's a requirement for you but not others following the tutorial (i.e., many have followed this tutorial and not reported this problem). 

If you do open an issue for engineering, tell them exactly what part of the **_sample app_** requires the **_that API_**. The error that you've both mentioned isn't specific enough ... provide a full stack trace or screenshot.

Also, you can tell them at the bottom of your opening comment (and this will cross-link me into the discussion so that I can see what they say) ...

> `@guardrex couldn't repro this problem on docs issue https://github.com/dotnet/AspNetCore.Docs/issues/20752.`

Open here ...

https://github.com/dotnet/aspnetcore/issues

Leave this docs issue open tho ... I'll use it to fix those two tiny nits, and it will close automatically when the PR merges later.
