### ISSUE TITLE
Clarify Scoped Service lifetime in Blazor Server

### ISSUE THREAD

**Issue by endintiers** [dotnet/AspNetCore.Docs#20777]
"In Blazor Server apps, a scoped service registration is scoped to the connection. For this reason, using scoped services is preferred for services that should be scoped to the current user"

I assume by "connection" you mean "circuit"? It appears (by observation) that there is a circuit per page (this does not appear obvious to me from the documentation though). If all the above is true then the second sentence should be "using scoped services is preferred for services that should be scoped to the current **page**"

In that case I'd appreciate some guidance for storing state for the current **user** - in session storage or protected session storage???

It is not clear to me I guess and does not work in code as the documentation seems to indicate. If I define a Scoped object in startup and then inject it into (say) a shared navbar in a Blazor Server app I see its constructor being called once for every page I have in the app...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7683690c-e3aa-4a00-152a-e44cfd7fc789
* Version Independent ID: d9aabe95-69e9-0a03-81ff-429914137f9d
* Content: [ASP.NET Core Blazor dependency injection](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @endintiers ... Yes, "connection" is the SignalR connection/circuit.

> circuit per page

Only if opened in a different browser window or if the page is refreshed. The circuit is shared across tabs but not across separate browser windows. The circuit drops when the last tab or the browser is closed ... or when the refresh button is hit in the browser.

> storing state for the current user 

There's a topic on that subject ...

https://docs.microsoft.com/aspnet/core/blazor/state-management?view=aspnetcore-5.0&pivots=server

> If I define a Scoped object in startup and then inject it into (say) a shared navbar in a Blazor Server app I see its constructor being called once for every page I have in the app

I can't explain that behavior. I've not seen that happen here. There must be some other factor at play. You can open an issue for engineering and see what they say about it. Please add a `cc: @guardrex` to the issue so that I can follow along. We might need a docs adjustment based on what you/they determine about what you're seeing. Explain out what you're doing (showing code is good) and what you're seeing (screenshots are good) ... anything to help them digest quickly 🏃 what's going on because they're all *very busy* 🏃 and *very tired* 😅 being end of year and after the .NET 5 release :point_right: 

https://github.com/dotnet/aspnetcore/issues

WRT to this docs issue, I would like to address it with one or a few updates where the connection/circuit is discussed. Leave this issue open, as it will close when the PR merges. Thanks for commenting!

**Comment by endintiers** [comment]
Yes, I was wrong.
For PAGES it works exactly as you say. I create a Scoped Service in startup, that service instance is shared by all pages (and other components).
The foible I was seeing is that, if you use a scoped service in a COMPONENT (navbar say) rather than just in a page, it is constructed twice for some reason. I was breaking in the constructor and seeing two constructions of the object.
https://github.com/endintiers/Unearth.Experiment.BlazorState shows this (see the different guids in output debug).

**Comment by endintiers** [comment]
This causes problems because if in startup I have two classes: State1 and State2 (which depends on State1) and I reference State1 in the NavBar, the State1 instance injected into the NavBar and Pages is State1-Instance2, while the State1 instance referenced by the Scoped State2 instance is State1-Instance1.

**Comment by guardrex** [comment]
@endintiers ... Yes, I understand what you're saying now (*"pages" is an overloaded term*! :smile:). Hybrid Blazor Server/Razor Pages/MVC exhibit that behavior because the RP/MVC part of the app is running on the normal HTTP request-response model and the service is constructed for **_each request_**, which is normal behavior for scoped services in an RP/MVC app. However, the Blazor part of the app isn't making HTTP requests as you go component-to-component ... it's communicating over the SignalR connection/circuit and the scoped service isn't treated as if SignalR messages among components are separate requests.

I'll use this issue to make improvements to clear that up along with a few other clarifying remarks on component-to-component behavior and the browser (i.e., refresh, tabs, and closing). Leave this issue open ... it will close when the PR merges later.

If you want a stable user state via a service across Blazor and Razor Pages, then access the guidance in the [State management (for Blazor Server)](https://docs.microsoft.com/aspnet/core/blazor/state-management?view=aspnetcore-5.0&pivots=server) topic.

As for any particular set of behaviors that you're trying to achieve for your app, contact devs on one of the usual support channels. You're certainly aware of SO, but there are great chats for immediate feedback that you might not be aware of ...

* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/) - ASP.NET Core general Slack chat
* [ASP.NET Gitter](https://gitter.im/aspnet/Blazor) - Blazor-specific Gitter chat
