### ISSUE TITLE
Docs not available for 3.1

### ISSUE THREAD

**Issue by JohnCOsborne** [dotnet/AspNetCore.Docs#20902]
Why aren't these docs available for 3.1? Asking for in and out process hosting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f99cd387-53b0-8b37-4f2c-fc4edd1ed080
* Version Independent ID: a1fcfbef-c5f0-c0f4-4246-8aee6ac72aea
* Content: [Out-of-process hosting with IIS and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/out-of-process-hosting?view=aspnetcore-5.0&viewFallbackFrom=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/iis/out-of-process-hosting.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/out-of-process-hosting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @JohnCOsborne ... I think the docs were targeted at >=5.0 in order to scale back duplication of coverage across versions and thus lighten the maintenance load and to avoid breaking links across versions of the doc ...

* https://github.com/dotnet/AspNetCore.Docs/issues/19982#issuecomment-697902470
* https://github.com/dotnet/AspNetCore.Docs/pull/19987#issuecomment-700207392

It's true that 3.x is supported by the product unit out to December 3, 2022 ...

https://dotnet.microsoft.com/platform/support/policy/dotnet-core

... but we're only required to keep documentation for the latest release, in this case 5.0.

Much of the guidance does apply back to 3.1, so you should be able to apply it as written from the 5.0 doc.

**Comment by JohnCOsborne** [comment]
Roger that. I was hoping that I wasn't studying up on things to troubleshoot my 3.1 app that may not be implemented in 3.1

I found other in and out of process docs in 3.1 so I figured the 5.0 docs were relevant as well...

**Comment by guardrex** [comment]
I wish the volume and complexity of coverage hadn't become so challenging to maintain. I think ... just an educated guess and some wishful thinking :pray: on my part ... that 5.0 marks a level of stability to the framework. I think there will be less churn and a reduced need to drop supported content going forward ... *I hope* :pray::smile:.

Very little changed tho when Justin refactored the docs. I hazard a guess that the vast majority of it that you see marked now for 5.0 is also applicable to 3.1.

**Comment by JohnCOsborne** [comment]
I hope you're right :) Glad to know very little has changed. I imagine our organization will upgrade our app soon :)
