### ISSUE TITLE
Enhance Blazor Lifecycle topic example for SetParametersAsync

### ISSUE THREAD

**Issue by dumaisf** [dotnet/AspNetCore.Docs#20921]
I don't find the documentation about custom route constraint (IRouteConstraint) for a Blazor Page.

`@page "/{name:myconstraint}"`

Where **myconstraint** would be a _custom route constraint_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the feedback! I'm buried in work ⛏️⛰️ for the next couple of days then out for an extended ⛄ *holiday vacation* 🎁. I've added this to my **Post-holiday Triage** issue list and will take a look when I return. Sorry for the delay, but I must get some long-standing priorities resolved before leaving, so only bug fixes will usually be addressed before I get some *much needed* rest 😅. I assure you that this issue won't get lost.

**Comment by guardrex** [comment]
@dumaisf ... Ok, I'm back from vacation now.

@captainsafia ... I don't think that custom constraints exist at this time, and I see they certainly don't exist in the form of  `RouteConstraint` classes per https://github.com/dotnet/aspnetcore/issues/28938.

We could show an approach using `SetParametersAsync`. I might do this by merely expanding [the existing example of `SetParametersAsync` in the *Lifecycle* topic](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0#before-parameters-are-set) and cross-link to that from the *Fundamentals* > *Routing* topic's *Route constraints* section with a little blurb of text. We need a better example over in the *Lifecycle* topic anyway (probably). Let me know if there is some other way to go. :ear: Otherwise, I'll consider floating something like the following. I'll ping u on the PR.

```csharp
[Parameter]
public string Param { get; set; }

public override async Task SetParametersAsync(ParameterView parameters)
{
    if (parameters.TryGetValue<string>(nameof(Param), out var value))
    {
        ...
    }

    await base.SetParametersAsync(parameters);
}
```

**Comment by guardrex** [comment]
@pranavkm ... Can you spare a tip on this one? I don't think that custom constraints exist at this time ... not in the form of `RouteConstraint` classes per dotnet/aspnetcore#28938 anyway.

btw - We could flesh-out our example of `SetParametersAsync` in the *Lifecycle* topic to cover this. Currently, the example doesn't actually do anything with `parameters`. Is what I show in my last comment **_sane_** 😵? That would be easy/quick to show and cross-link from *Routing* for this.

**Comment by dumaisf** [comment]
I have _no idea_ how you would use `SetParametersAsync` to constraint the route. If you could provide a sample, it would be _appreciated_.

**Comment by guardrex** [comment]
I'm asking if it's sane to take a value from the `ParameterView` (`value` :point_up: in that code snippet that I showed) in `SetParametersAsync` and manually perform a parse on it. If it parses to the type required, assign it. If not, throw or navigate away (error page). The framework route constraint parses can be seen here ...

https://github.com/dotnet/aspnetcore/blob/master/src/Components/Components/src/Routing/RouteConstraint.cs

I don't know if this approach idea (🙈 *maybe another RexHack*:tm: 🙈) is the right way to address this scenario. I'm asking. We'll have to hear back from Pranav or Safia on the right way to address your ask.

**Comment by guardrex** [comment]
@dumaisf ... We discussed this offline, and we're not going to work the route constraint aspect as a current by-design **won't fix**. However, they may in a future release address it. At that point, **_Yes!_** ... we will add coverage.

I **_DO_** want to use this issue tho to update the *Lifecycle* topic with that one helpful line in the example for `SetParametersAsync` :point_up:. That's a helpful thing to show in passing because that's a common use case for that lifecycle event ... messing around with the parameter values in various ways.

WRT to my 🙈 *RexHack!*:tm: 🙈 idea for parsing types in `SetParameterAsync` as a workaround to constrain routes (i.e., if a parameter doesn't parse into the type you're seeking, redirect back, throw, or send the user to the Error page), we didn't discuss that aspect offline. Don't go by my **_hack suggestion_**. Take your question to the community for discussion. You'll probably receive much better developer advice ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

Leave this issue open ... it will close automatically when the PR merges.
