### ISSUE TITLE
Links should include the ASP.NET version user has selected

### ISSUE THREAD

**Issue by brgrz** [dotnet/AspNetCore.Docs#20937]
When I'm here 

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/request-features?view=aspnetcore-3.1

I expect the links in the document to include the `?view=aspnetcore-3.1` query string part to open the correct version of the API.

**Comment by guardrex** [comment]
Hello @brgrz ... This is intractable for us to resolve via the cross-linking that we use in content, which is mandated outside of our repo.

There are two factors at play ...

1. Our content often isn't versioned multiple times, once for each framework release. We **_could_** do that way, but it would lead to a large amount of unnecessary content duplication, generally up to three or four copies of each topic at any given time would be required. When we version content at 3.1 **_or later_**, which would include 5.0 ... 5.1 ... etc., we really don't know if the reader is actually on 3.1. They might be on 5.0 or anything after that. Therefore, we usually must place API links into content as versionless links.
1. Whatever version of the doc that the reader has selected in the browser, the links don't update in any kind of automatic way merely based on the selected version of the document. It would be possible for docs engineering to build such a system, but it doesn't exist today.

Therefore, we aren't able to address this using the cross-linking features that we have today.

**_However_**, it's a great suggestion for the folks who do build and manage the entire docs system Microsoft-wide. They take feedback on another repo ...

https://github.com/MicrosoftDocs/feedback/issues

You can search there for similar feedback (recommend searching open **_and closed_** issues). If you don't find anything, you can open a new issue with them.

I'll close here, since this isn't actionable for us.
