### ISSUE TITLE
Add a doc section to Blazor Virtualize that talks about all of the requirements for using Virtualize

### ISSUE THREAD

**Issue by pranavkm** [dotnet/AspNetCore.Docs#20978]

**Comment by pranavkm** [comment]
/cc @SteveSandersonMS could you fill in details?

FYI @guardrex

**Comment by guardrex** [comment]
Current coverage is in the following two topics ...

* https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-5.0
* https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0#virtualization

IIRC, the coverage is in two topics because it came in that way from two authors at different times. I put the topic up, and Steve put the section into the perf topic some other time.

There's a reader comment about either combining the sections or merely cross-linking `@key` guidance into them at ...

Combine Virtualization Sections #20965

I'll look at that when I get back from vacation 🏖️ in January.

**Comment by guardrex** [comment]
**UPDATE**: `Virtualize` component coverage has been combined into one spot and now resides in the *Component virtualization* topic at ...

https://docs.microsoft.com/aspnet/core/blazor/components/virtualization

@SteveSandersonMS ... Can you provide the requirements for using the `Virtualize` component?

**Comment by SteveSandersonMS** [comment]
This is already done at https://docs.microsoft.com/en-gb/aspnet/core/blazor/components/virtualization?view=aspnetcore-6.0#advanced-styles-and-scroll-detection
