### ISSUE TITLE
https://github.com/guardrex/HostedWASM50AADGroupsAndRolesSample

### ISSUE THREAD

**Issue by manasimahajann** [dotnet/AspNetCore.Docs#20980]
Following https://github.com/guardrex/HostedWASM50AADGroupsAndRolesSample
When i log in the page just hangs in on Completing login... with url https://localhost:5001/authentication/login-callback# in the browser.
I have made sure that api app has GroupMember.Read.All with admin consent
In expose api -- in our case we see "api://" url which i have put it in "https://tenantname. .. " as suggested in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896be20d-1321-0e2f-3efb-d0ce8f1e631a
* Version Independent ID: f5e2b80f-9478-7500-2bc5-930237274f4b
* Content: [Use Graph API with ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/graph-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/graph-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
### OOF for the :gift: *holidays* :snowman:

This issue has been marked for triage on the Blazor.Docs project, and I'll respond as soon as I return in 2021.

We only work on documentation on this repo. If you need product support, close this issue and seek assistance through one or more of the following support channels:

* [Stack Overflow (tagged: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [General ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

If you think that you found a potential bug in the framework or have product feedback, close this issue and open a new issue for the ASP.NET Core product unit at [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore).

For problems or feedback on Visual Studio or Visual Studio for Mac, close this issue and use the [**Report a Problem**](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) or [**Suggest a Feature**](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) processes from within VS, which open internal issues for the VS team. For more information, see [Visual Studio feedback options](/visualstudio/ide/feedback-options) or [How to report a problem in Visual Studio for Mac](/visualstudio/mac/report-a-problem).

For problems with Visual Studio Code, close this issue and ask for support on community support forums. For bug reports and product feedback, open an issue on the [microsoft/vscode GitHub repo](https://github.com/microsoft/vscode/issues).

⛄🎁 **_Happy Holidays! :dancer::man_dancing::partying_face: Happy New Year!_** :balloon::champagne::tada:

**Comment by guardrex** [comment]
That sample app might not be *completely* up-to-date. You can see the latest guidance, which is merely under review, on the PR at ...

https://github.com/dotnet/AspNetCore.Docs/pull/20856

As I pasted in my OOF message above ☝️, I'm actually out on vacation until 2021. I wouldn't be able to provide product support until I return.

**Comment by manasimahajann** [comment]
Sure @guardrex Thank you for your help, as always. Happy holidays and a very happy new year!! :) 👍  Enjoy your vacation.

**Comment by guardrex** [comment]
That 'completing login' problem on the callback has usually been traced to some kind of app or Azure configuration problem (or violating the general guidance on lingering cookies breaking an app). You'll probably have to go back over the config again on both sides to see if you can figure out where the problem is.

As you know, we don't really handle product support here. We need devs to tell us that they found a specific problem in a topic in order to make it actionable.

At the time that I put that sample app up on my repo, it was working. However, it's not latest ... e.g., `Microsoft.Identity.Web` is at 1.4.1. Idk if that will solve it, but it's one thing to look at.

**Comment by guardrex** [comment]
@manasimahajann ... I don't have anything further that I can add to my last set of remarks on this one. There's probably a configuration problem somewhere within your app or Azure config. Because we're so short handed and 🏃😅 all the time, we aren't able to provide product support to find a configuration problem within a developer's app when the guidance is correct (*if* it is correct).

My recommendation is to work back through the entire app, groups/roles setup, and Azure config to confirm configuration is correct. If you find out what the problem is and there's something wrong with the guidance on the PR or elsewhere, then open a docs issue (or note it back on this one ... I'll re-open this) for analysis and work.
