### ISSUE TITLE
Super Complex and not Working

### ISSUE THREAD

**Issue by toorajhelmi** [dotnet/AspNetCore.Docs#21055]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by toorajhelmi** [comment]
I have tried this 3 times and still not able to get it to work. Doing so much to enable signing up/in is really a killer and scare many developers away. I use Google Firebase most of the time and setting it up is much much easier than this. This seems to be over-engineers in not useful

**Comment by guardrex** [comment]
Hello @toorajhelmi ... On the docs side, there isn't anything we can do to make app scenarios (or Azure) less complex outside of improving the guidance generally and covering more *gotcha* scenarios. Specific feedback is actionable, so feel free to add detail when you discover what the problem is with the app or Azure config.

You can open an issue for the product unit to provide general feedback on the scenario, but they will need something more specific to react to than just 'it's too complex' ... you'll have to explain specifically *what you find complex* about the scenario ...

https://github.com/dotnet/aspnetcore/issues

WRT 'not working' ... Currently, we don't have any other open issues on problems with the guidance in this node. Given that the cause of the problem is unknown, there isn't much that we can do ... especially right now ... I'm on ⛄ *holiday vacation* 🎁 for another couple of weeks.

We recommend the usual support channels for product support that we aren't able to offer ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

If you find out the problem, please add a comment back here. If I can improve the doc to cover it in some way, I'll re-open this issue and work on the topic to cover what was causing your app (or Azure config) to fail.

**Comment by toorajhelmi** [comment]
Hi,
Thanks for the response. There are couple of points:
1. Microsoft is a big enterprise so if one person is on vacation there should other people who provide support in his absence. Telling me you were on vacation for a couple of weeks was fine if I was working with a startup not with Microsoft.
2. You have closed the issue but rather you should have done two things: first had somebody from your org work with me to find the problem and potentially update this document accordingly and two escalate to responsible azure PMs to find ways to simplify the overall flow. Offering a product which cannot be easily used by customers is worse than provide nothing. I have spent around 30 hours at this point trying to make it work which I would have spent on other important features of my project.
3. Happy holidays and don’t take this personally but rather an opportunity to improve things at your organization.
Regards,Tooraj 

Sent from Yahoo Mail for iPhone


On Sunday, December 27, 2020, 3:10 PM, Luke Latham <notifications@github.com> wrote:




Hello @toorajhelmi ... On the docs side, there isn't anything we can do to make app scenarios (or Azure) less complex outside of improving the guidance generally and covering more gotcha scenarios. Specific feedback is actionable, so feel free to add detail when you discover what the problem is with the app or Azure config.

You can open an issue for the product unit to provide general feedback on the scenario, but they will need something more specific to react to than just 'it's too complex' ... you'll have to explain specifically what you find complex about the scenario ...

https://github.com/dotnet/aspnetcore/issues

WRT 'not working' ... Currently, we don't have any other open issues on problems with the guidance in this node. Given that the cause of the problem is unknown, there isn't much that we can do ... especially right now ... I'm on ⛄ holiday vacation 🎁 for another couple of weeks.

We recommend the usual support channels for product support that we aren't able to offer ...
   
   - Stack Overflow (tag: blazor)
   - ASP.NET Core Slack Team
   - Blazor Gitter

If you find out the problem, please add a comment back here. If I can improve the doc to cover it in some way, I'll re-open this issue and work on the topic to cover what was causing your app (or Azure config) to fail.

**Comment by guardrex** [comment]
> Microsoft is a big enterprise so if one person is on vacation there should other people who provide support in his absence. Telling me you were on vacation for a couple of weeks was fine if I was working with a startup not with Microsoft.

There are only about two others here (three really, but two have many responsibilities elsewhere), and they are also out on vacation. There are no active ... non-vacationing 🏖️ ... doc authors here right now. Everyone will be back working in a couple of weeks. Notwithstanding our staffing right now, my role is ~95% Blazor docs ... I'm literally *THE* Blazor docs 🐈 here. I jump in for critical updates and to answer messages, but that's about it right now.

> You have closed the issue but rather you should have done two things: first had somebody from your org work with me to find the problem and potentially update this document accordingly and two escalate to responsible azure PMs to find ways to simplify the overall flow. Offering a product which cannot be easily used by customers is worse than provide nothing. I have spent around 30 hours at this point trying to make it work which I would have spent on other important features of my project.

Some of your comments are product feedback, which we don't take here. That's why I gave you the product unit issues link ...

https://github.com/dotnet/aspnetcore/issues

... so you could tell them what you find complex and provide any ideas you have for making the framework less so. That's their responsibility, and they don't monitor issues here. You have to open an issue with them to discuss that aspect.

WRT the guidance failing ...

Often, I do work with devs to narrow the scope of a problem, sometimes just to determine if opening an issue with the product unit is warranted (at the link that I provided). 
In this case thus far, you've provided no actionable information ... no errors or specific behaviors ... no notes on tooling in use ... SDK and framework versions ... or anything really. All you've said is 'this is complex' and 'the app doesn't work.' nothing that I can hoep I closed the issue and said that if you add detail and if I can hel
