### ISSUE TITLE
Getting Authorization failed error when upgrading Blazor to 5.0 with Azure ADB2C #20447  Closed

### ISSUE THREAD

**Issue by KevinLandgrave** [dotnet/AspNetCore.Docs#21062]
[EDIT by guardrex to add the metadata]

This issue is not fixed for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @KevinLandgrave ... Please use the **This page** feedback button and form to open a new issue on this repo. I'll add the metadata to your opening comment, which would have been added automatically when using the button and form.

**Comment by guardrex** [comment]
@KevinLandgrave ... Unfortunately, we don't have the staffing to provide product support. For one thing, the entire docs team is out on vacation 🏖️ until January. For another, we just don't have the capacity to walk though every configuration required to sort out general auth errors. Your best bet is to use the *Troubleshoot* section guidance, re-walk the topic carefully looking for mis-configuration in the app and Azure, and working with devs on one of the usual support forums (assuming that you don't have a Microsoft Support agreement). Currently, we don't have any specific open issues for identified errors in this topic. Usually, these sorts of auth errors come down to a misconfigured app or Azure registration(s). If you find the problem and it's something that we can cover as a *gotcha* scenario or if you find a specific 🐞 in the doc, then please comment back so that I can re-open and work this issue.
* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

**Comment by guardrex** [comment]
... and this ...

> #20447 Closed

... missed that because it wasn't in the opening comment. I don't have any additional information on that. You can open an issue for the product unit if you've already checked the Azure app manifest and found a correct value or set a correct value ...

https://github.com/dotnet/aspnetcore/issues
