### ISSUE TITLE
Ambiguous reference to Razor Components in Blazor

### ISSUE THREAD

**Issue by lukos** [dotnet/AspNetCore.Docs#21106]
This page links to Razor components, "When considering if view components meet an app's specifications, consider using Razor Components instead." but the link lives underneath Blazor and the Blazor page reads very much like "Blazor only". 

This page needs to make it clear that Razor components only apply to Blazor apps or if they don't, the Razor component page needs either moving out of the Blazor menu or needs clarification e.g. "Blazor components were invented for Blazor apps but are available in non-Blazor apps too"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
### OOF for the :gift: *holidays* :snowman:

This issue has been marked for triage on the Blazor.Docs project, and I'll respond as soon as I return in 2021.

We only work on documentation on this repo. If you need product support, close this issue and seek assistance through one or more of the following support channels:

* [Stack Overflow (tagged: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [General ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

If you think that you found a potential bug in the framework or have product feedback, close this issue and open a new issue for the ASP.NET Core product unit at [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore).

For problems or feedback on Visual Studio or Visual Studio for Mac, close this issue and use the [**Report a Problem**](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) or [**Suggest a Feature**](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) processes from within VS, which open internal issues for the VS team. For more information, see [Visual Studio feedback options](/visualstudio/ide/feedback-options) or [How to report a problem in Visual Studio for Mac](/visualstudio/mac/report-a-problem).

For problems with Visual Studio Code, close this issue and ask for support on community support forums. For bug reports and product feedback, open an issue on the [microsoft/vscode GitHub repo](https://github.com/microsoft/vscode/issues).

⛄🎁 **_Happy Holidays! :dancer::man_dancing::partying_face: Happy New Year!_** :balloon::champagne::tada:

**Comment by guardrex** [comment]
Hello @lukos ... I'm still out on vacation 🏖️ for a few more days, and I'll take a closer look when I get back.

It's challenging to cleanly address this and similar scenarios because we're dealing with gray areas of thinly differing, often flexible, and overlapping app frameworks and features **_by design_**. Therefore, some ambiguity may always be present.

When an MVC or Razor Pages app is set up to host routable Razor components, a Blazor Server app has been created, but one may not think of that way (or call it that) if the components aren't routable or if the vast majority of the app remains MVC/Razor Pages. One may continue call such an app an MVC or Razor Pages app (with some Razor components in it).

Indeed ... one day, we may re-organize all of the content so that Razor components is moved out of the Blazor node into a more general location, such as how *Razor syntax* is placed in the *Web app* node because it applies generally to programming models/patterns (i.e., views of MVC and pages of Razor Pages).

I think I can make a few small changes to this passage that will help, and we probably want to link the [Razor component integration content](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-5.0&pivots=server) in addition to the Razor component overview. I'll take a closer look when I get back and see what can be done to improve this bit.
