### ISSUE TITLE
spa.UseAngularCliServer(npmScript: "start"); still doesnt work for me 3rd Jan 2021

### ISSUE THREAD

**Issue by donkeybrains** [dotnet/AspNetCore.Docs#21102]
[Enter feedback here]
Hi Guys

This started when I was tasked with working on an Anuglar/dotnet core 3.1 application. Out of the repo it didnt work for me yet did for others. Im working  on a VPN and behind a corporate proxy.

So back to basics check the environment with a basic Angular/Dotnet core app from the weather template. If I get this to work then the rest will fall into place.

I create the basic  Anugular app on the work PC over the VPN and run it the CLI timesout, no matter how long I give it.

-  Copy it to my home PC it works.

- Looked at the IIS permissions to node modules; added text to ng serve trick; 

- Ive tried specifying the localhost method

                    spa.UseAngularCliServer(npmScript: "start");
                    //spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
                    spa.Options.StartupTimeout = new TimeSpan(0, 0, 80);

- Ive set up the proxy in npm, it downloads ok.

- Ive deleted the node_modules as suggested

Damned if I can see what the issue is.

Before I do one of them numb from the neck up lists, Ill do a quick list for you. If you need more let me know.

**VS 2019 update 16.8.3**
//===================
PS C:\WINDOWS\system32> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
PS C:\WINDOWS\system32>
//===========================

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Use the Angular project template with ASP.NET Core #18074

**Comment by MackinnonBuck** [comment]
The SPA proxy startup can timeout on slower machines, and increasing the timeout usually fixes the issue. I see that the timeout is being set to 80 seconds - I've seen it take longer than that (2+ minutes) on very slow machines. I wonder if setting the timeout to something absurd (e.g. an hour) would work?

If there is a docs fix for this, it's probably not Angular-specific. It would probably be covered in #18405.

**Comment by jpeckham** [comment]
> The SPA proxy startup can timeout on slower machines, and increasing the timeout usually fixes the issue. I see that the timeout is being set to 80 seconds - I've seen it take longer than that (2+ minutes) on very slow machines. I wonder if setting the timeout to something absurd (e.g. an hour) would work?
> 
> If there is a docs fix for this, it's probably not Angular-specific. It would probably be covered in #18405.

it worked for me with angular 12. i deleted the clientapp and did a new app with ng 17 now it times out even with a 5 minute timeout.
app.UseSpa(spa =>
{
	// To learn more about options for serving an Angular SPA from ASP.NET Core,
	// https://learn.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-3.0&viewFallbackFrom=aspnetcore-6.0

	spa.Options.SourcePath = "ClientApp";

	if (env.IsDevelopment())
	{
		spa.Options.StartupTimeout = TimeSpan.FromMinutes(5);
		spa.UseAngularCliServer(npmScript: "start");
		//spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
	}
});

**Comment by ali-kashanian** [comment]
I think the people having this problem might have moved on via another solution instead of fixing the problem with `.UseAngularCliServer()` or maybe they fixed it and forgot to put it here.

The `.UseAngularCliServer()` leverages a combination of running the Node script and starting the Angular CLI developer server, then using the proxy connection to it. The approach later on moved to having a separate `.esproj` for Angular project and running it separately and having the .NET project using proxy connection to it.

The latter works in general, but if you have been on the old template and leveraged middlewares to setup and configure your host, you would have a tough time migrating to the express or Angular CLI dev server.

The problem with `.UseAngularCliServer()` timing out is basically an unexpected bug in the internal class `NodeScriptRunner` where it starts a process and waits until it detects the output that matches `"open your browser on (http\\S+)"` regex, which will be the `** Angular Live Development Server is listening on https://localhost:4200, open your browser on https://localhost:4200 **` or the port that you're using in your project (`AngularCliMiddleware.cs:80`)

Since Angular v17 or v18, the developer server now utilizes vite.js that is more suitable for its performance and superior hot reload capabilities. The result is that the message is different in the process output, hence the timeout due to getting stuck. (`➜  Local:   https://localhost:4200/`)

One way to fix this is to force push the old message in the console if the new one was received, so the middleware continues to work. For that I created the `dev-server-wrapper.js` file to listen to `ng serve`, forward the input argument, and push an the extra message. Then I replace the `"start"` or any other script that `.UseAngularCliServer()` calls in package.json with `node dev-server-wrapper.js`. You can also add your own arguments after the JS file.

This approach worked for me and I'm now on Angular v19. The only problem I have is that for some reason, the TS debugger won't attach to the browser after launch. It must be some Typescript SDK mismatch or something.

[dev-server-wrapper.js](https://github.com/user-attachments/files/20665082/dev-server-wrapper.txt)
