### ISSUE TITLE
Blazor SPA PWA offline auth

### ISSUE THREAD

**Issue by Eweol** [dotnet/AspNetCore.Docs#21100]
[EDIT by guardrex to add the metadata. @Eweol ... Please in the future use the **This page** feedback button and form at the bottom of the topic to open an issue here.]

Hey guys,

I had a look hole 2 days to find a solution for my problem regarding offline authentication of a user in my Blazor Standalone PWA.

With .Net 5.0 I changed the Authentication scenario from Web to SPA.
After that change, my PWA was not able to login the user in offline mode.
I work on Program.cs with AddMsalAuthentication and save the tokens and ID's in local storage with help of MSAL.

If I'm online everything works like expected and I can login with the users and the tokens will be stored in local storage.
After changing the online state the PWA try to get the openid-configuration data from azure.
I tried to also serve this request with the service worker, which worked quiet fine but the token request after that fail also.

I searched and found the [CarChecker](https://github.com/SteveSandersonMS/CarChecker) app and the [docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio#interaction-with-authentication) as well but this didn't solve my problem.
Did I missed something or is there really no way, to make offline auth workable on Blazor standalone PWA's?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8c235e-1ce4-046f-e848-294096361922
* Version Independent ID: 6240f626-97d4-ace0-5e34-20e1c3592f86
* Content: [Build Progressive Web Applications with ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/progressive-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/progressive-web-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
### OOF for the :gift: *holidays* :snowman:

This issue has been marked for triage on the Blazor.Docs project, and I'll respond as soon as I return in 2021.

We only work on documentation on this repo. If you need product support, close this issue and seek assistance through one or more of the following support channels:

* [Stack Overflow (tagged: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [General ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

If you think that you found a potential bug in the framework or have product feedback, close this issue and open a new issue for the ASP.NET Core product unit at [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore).

For problems or feedback on Visual Studio or Visual Studio for Mac, close this issue and use the [**Report a Problem**](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) or [**Suggest a Feature**](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) processes from within VS, which open internal issues for the VS team. For more information, see [Visual Studio feedback options](/visualstudio/ide/feedback-options) or [How to report a problem in Visual Studio for Mac](/visualstudio/mac/report-a-problem).

For problems with Visual Studio Code, close this issue and ask for support on community support forums. For bug reports and product feedback, open an issue on the [microsoft/vscode GitHub repo](https://github.com/microsoft/vscode/issues).

⛄🎁 **_Happy Holidays! :dancer::man_dancing::partying_face: Happy New Year!_** :balloon::champagne::tada:

**Comment by guardrex** [comment]
I'm back from vacation.

I haven't received any additional info from the product unit outside of what we have published at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio#interaction-with-authentication

There is an open issue that I'll follow-up on at ...

https://github.com/dotnet/AspNetCore.Docs/issues/20742

... that pertains to PWAs and auth. I don't think that it's the same problem, but you should look that over (and the product unit issue on it) to confirm that it's not related/helpful for your scenario.

I think if you're hitting problems with basic auth outside of the minimal doc coverage and in CarChecker, you have two courses of action that you can take. If you think the community can help out because others have developed PWA-auth apps successfully, especially CarChecker, you can hit up the community on the usual support channels ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

Second, you can ask the product unit directly by opening an issue on their repo with the problems/errors that you're seeing ...

https://github.com/dotnet/aspnetcore/issues

Of course, they'll need specifics ... error messages ... behaviors ... versions of everything in use ... and perhaps a small repro project that demonstrates the problem(s).

What I'll do for that doc section is give it my own go when I reach this topic for it's UE ("user experience") pass, which is when I'll be testing everything in the doc and updating/overhauling it, on https://github.com/dotnet/AspNetCore.Docs/issues/19286. I'll mark that tracking issue with a cross-link to this issue to remind me about your issue.

If you do open an issue for the product unit, please put a `cc: @guardrex` at the bottom of your opening comment so that I can follow the discussion.
