### ISSUE TITLE
Swashbuckle library neglect

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [dotnet/AspNetCore.Docs#21135]
There are ASP.NET documents and templates which treat Swashbuckle as if it were a Microsoft-owned library. Lately, the library has been neglected and the (seemingly only) owner, who has been sponsored by @dotnet-at-microsoft, hasn't been active on his account. Why is this library recommended without any warning about this risk? Should there be some minimum requirements for Microsoft recommending a library, like that there should be at least 3 people with write access or that the repo owner needs to add some Microsoft team as collaborators? I'm not sure what the right forum for this complaint is, but this docs page makes no indication that Swashbuckle is a third-party library with a single point of failure/bottleneck. I have no idea if the owner hasn't been around because he lost interest or if he's having personal problems or what, but life happens so there should be a backup plan in those cases. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Swashbuckle #21141

**Comment by bradygaster** [comment]
This is a very good point and one that we discussed at length with the owner, @domaindrivendev. He has been *rather* active, in fact, and has been making tweaks and resolving issues as recently as October/November, when he helped support features we were requesting. And Microsoft does have an agreement with the owners of the project that we can contribute to it in the case that our customers need something that his team lacks the time to do. 

Please let us know if the language in the document fails to properly convey that the package is an open-source package and not shipped by Microsoft. FWIW, there are other items in the OpenAPI space that fall into this category as well, such as the OpenAPI client-generation tools, which make use of some of the NSwag components. We also have a fantastic relationship with that project's owners as well. 

We appreciate your concern, but I can advise you that much vetting has been done, and agreements put in place around our ability to support our customers.

**Comment by Blackbaud-ChristiSchneider** [comment]
I'm sorry if I offended you. I'm not sure if this exists but is there any transparency to this process and the agreement between the owners of open source projects and Microsoft?

I will say this document does not mention that the project is open source or that it's supported only by a third party. Someone who isn't familiar with the project would have to dig into the repository and the owner to see that they are not a Microsoft employee. Compare this to projects like James Montemagno's [Xamarin plugins](https://github.com/jamesmontemagno/ConnectivityPlugin) which are owned by a Microsoft employee and so presumably have Microsoft support behind them.

**Comment by bradygaster** [comment]
No offense whatsoever. I totally understand your perspective. Swashbuckle is indeed an open-source project and maintained by the owners of the project itself. Microsoft does not provide day-by-day maintenance of the package. That said, we are contributors to the project, and we did forge a partnership by which Microsoft developers can push code into this project if we find something that needs repair in the case where the owners are unable to help. We make use of NSwag, too, as a dependency in the client-generation process, and that project is wholly maintained by the NSwag team, who accept contributions from our team just like the Swashbuckle maintainers. Many projects outside of the .NET community thrive on this sort of interaction and partnership, and we're excited to be able to work with open-source authors to get features into customers' hands rapidly.

Since Swashbuckle is also supported by the swagger-codegen project, which is used throughout the OpenAPI tooling community for things like SwaggerHub. This was one of the contributing factors, as well as Swashbuckle's popular standing in the community already, for using it on the description-generation side of the experience.

I do agree with you - the doc needs to be updated to reflect that Swashbuckle is an open-source package, and I will personally initiate the process of getting the doc updated myself to reflect that. Adding @ChrisSfanos if he has anything to add.
