### ISSUE TITLE
User-Agent header is set to "grpc-dotnet/2.34.0.0" in Safari

### ISSUE THREAD

**Issue by LukasReschke** [dotnet/AspNetCore.Docs#21178]
https://docs.microsoft.com/en-us/aspnet/core/grpc/services documents how to access the HTTP request headers, and gives an example of the User-Agent:

```csharp
public override Task<ExampleResponse> UnaryCall(ExampleRequest request, ServerCallContext context)
{
    var userAgent = context.RequestHeaders.GetValue("user-agent");
    // ...

    return Task.FromResult(new ExampleResponse());
}
```

The userAgent will however be `grpc-dotnet/$version` when running on Safari in Blazor (as described at https://docs.microsoft.com/en-us/aspnet/core/grpc/browser) seemingly from https://github.com/grpc/grpc-dotnet/blob/3518cd757002f5a685f34d277e876850b7637ecc/src/Grpc.Net.Client/Internal/GrpcProtocolConstants.cs#L64-L81. Whilst other browsers actually send the user agent of the browser.

I'm curious what the right behaviour here is. My feeling here is that it should be the Browser UA (and possibly should be fixed in grpc-dotnet or Safari). But as I am not sure, I'm filing this here :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d988d24b-1a4d-d1ab-4a2a-f85156b4ea84
* Version Independent ID: a770adda-2001-c26e-62c5-5957baba3bb7
* Content: [Create gRPC services and methods](https://docs.microsoft.com/en-us/aspnet/core/grpc/services?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by guardrex** [comment]
Hello @LukasReschke ... Since this appears to be about the framework/browser behavior, it's best if you open it for the product unit to address. If you/they find out something that should change in the doc, then we can re-open this issue (or you can open a new one from the bottom of the topic again) with the cross-linked product unit issue. Feel free to add a cross-link to this docs issue at the bottom of the new product unit issue so that this doesn't get lost in the discussion over there.

Open your issue (you can probably just cut-'n-paste that :point_up:) at ...

https://github.com/dotnet/aspnetcore/issues.
