### ISSUE TITLE
Size limits on JSInterop

### ISSUE THREAD

**Issue by MarkStega** [dotnet/AspNetCore.Docs#21208]
The section labeled "Size limits on JSInterop calls" fails to document whether or not there is a size limit on Blazor Server JSInterop calls for inputs. It is written as showing the size limit on the return value but doesn't mention the inputs. I suspect that the same limit exists but it would be nice if documentd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aada0049-99a8-2f91-5d60-6970474e2371
* Version Independent ID: c29fb1a8-028f-6efd-f1bc-e889fb362311
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> written as showing the size limit on the return value

It's not written for and doesn't pertain to the return value AFAIK. The setting is defined as (emphasis added) ...

> Gets or sets the maximum message size of a single **_incoming_** hub message.

API cross-ref: https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.signalr.huboptions.maximumreceivemessagesize

cc: @javiercn

**Comment by guardrex** [comment]
Sorry about that ... forgive my confusion (and distraction ... I'm buried in something else at the moment) both about your question and about the inner workings of SingalR limits. I thought of "return value" in the wrong context. I was thinking of a JS interop call to .NET with .NET returning data, which is covered in the other topic. Compounding the problem is that I'm just a docs :cat2: and need product unit support for deeper framework concepts, such as this one.

The original topic contained both .NET to JS and JS to .NET. It was split. This section on limits was left in the *Call JS from .NET* topic, and a similar section wasn't included in the other topic. The opening line that pertains to Blazor WASM applies, but the Blazor Server remarks **_are of concern_** here.

It's best for @javiercn to look and suggest the course of action on how to describe the limits for Blazor Server ...

* Don't we need a similar limits section in the *Call .NET methods from JS* topic, or should the entire section just move to the other topic?
* Is the SignalR limit `MaximumReceiveMessageSize` bi-directional for messages, or is the limit only for messages that the hub receives?

After we hear back, I'll seek to improve the coverage.

**Comment by guardrex** [comment]
I knocked up some *RexHax*:tm: to perform a little test ...

```javascript
function dec2hex(dec) {
  return dec.toString(16).padStart(2, "0")
}

function getString(len) {
  var arr = new Uint8Array((len || 40) / 2);
  window.crypto.getRandomValues(arr);
  return Array.from(arr, dec2hex).join('');
}

function jsFromDotNet(largeString) {
  alert(`Length: ${largeString.length} Text: ${largeString}`);
}

function dotNetFromJs() {
  var largeString = getString(20000);
  DotNet.invokeMethodAsync('BlazorServerSample', 'DotNetMethod', largeString);
}
```

```razor
@page "/JSInterop"
@inject IJSRuntime JS

<h1>JavaScript Interop</h1>

<h2>Call JavaScript from .NET</h2>

<button type="button" class="btn btn-primary" @onclick="CallJsFromDotNet">
    Call JavaScript From .NET
</button>

@code {
    public async Task CallJsFromDotNet()
    {
        Random rand = new Random();

        var largeString = new string(Enumerable.Repeat("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", 20000)
            .Select(s => s[rand.Next(s.Length)]).ToArray());

        await JS.InvokeAsync<string>("jsFromDotNet", largeString);
    }
}

<h2>Call .NET from JavaScript</h2>

<button type="button" class="btn btn-primary"
        onclick="dotNetFromJs()">
    Call .NET from JavaScript
</button>

<div style="margin-top:10px">
    <textarea style="width:800px;height:800px;word-wrap:break-word">
        @message
    </textarea>
</div>

@code {
    private static Action<string> action;
    private string message = string.Empty;

    protected override void OnInitialized()
    {
        action = UpdateMessage;
    }

    private void UpdateMessage(string largeString)
    {
        message = $"Length: {largeString.Length} Text: {largeString}";
        StateHasChanged();
    }

    [JSInvokable]
    public static void DotNetMethod(string largeString)
    {
        action.Invoke(largeString);
    }
}
```

```csharp
services.AddServerSideBlazor()
    .AddHubOptions(options => options.MaximumReceiveMessageSize = 32000);
```

Change the `32000` to something like `18000` and it's the call to .NET that breaks. Therefore, it seems that the limit is as I thought ... for the **_incoming message to the hub_**.

**Comment by MarkStega** [comment]
How about something simple in each section and then a common doc fragment about mitigation strategies?

Call JS From .Net:
```
In Blazor WebAssembly, the framework doesn't impose limits on the size of inputs and outputs of JS interop calls.

In Blazor Server, the framework doesn't impose limits on the size of inputs, however the output of a JS interop call is limited by the maximum payload size enforced by SignalR (xref:Microsoft.AspNetCore.SignalR.HubOptions.MaximumReceiveMessageSize), which defaults to 32 KB.

(xref: NewCommonSection explaining mitigation)
```

Call .Net from JS
```
In Blazor WebAssembly, the framework doesn't impose limits on the size of inputs and outputs of JS interop calls.

In Blazor Server, the framework doesn't impose limits on the size of inputs, however the output of a JS to .Net interop call is limited by the maximum payload size enforced by SignalR (xref:Microsoft.AspNetCore.SignalR.HubOptions.MaximumReceiveMessageSize), which defaults to 32 KB.

(xref: NewCommonSection explaining mitigation)

```

NewCommonSection:
```
Applications that attempt to respond to a JS interop call or make a JS Interop call to .Net with a payload larger than xref:Microsoft.AspNetCore.SignalR.HubOptions.MaximumReceiveMessageSize throw an error. A larger limit can be configured by modifying xref:Microsoft.AspNetCore.SignalR.HubOptions.MaximumReceiveMessageSize. The following example sets the maximum receive message size to 64 KB (64 * 1024 * 1024):

services.AddServerSideBlazor()
   .AddHubOptions(options => options.MaximumReceiveMessageSize = 64 * 1024 * 1024);
Increasing the SignalR limit comes at the cost of requiring the use of more server resources, and it exposes the server to increased risks from a malicious user. Additionally, reading a large amount of content in to memory as strings or byte arrays can also result in allocations that work poorly with the garbage collector, resulting in additional performance penalties. One option for reading large payloads is to consider sending the content in smaller chunks and processing the payload as a xref:System.IO.Stream. This can be used when reading large JSON payloads or if data is available in JavaScript as raw bytes. For an example that demonstrates sending large binary payloads in Blazor Server that uses techniques similar to the InputFile component, see the Binary Submit sample app.

Consider the following guidance when developing code that transfers a large amount of data between JavaScript and Blazor:

Slice the data into smaller pieces, and send the data segments sequentially until all of the data is received by the server.
Don't allocate large objects in JavaScript and C# code.
Don't block the main UI thread for long periods when sending or receiving data.
Free any memory consumed when the process is completed or cancelled.
Enforce the following additional requirements for security purposes:
Declare the maximum file or data size that can be passed.
Declare the minimum upload rate from the client to the server.
After the data is received by the server, the data can be:
Temporarily stored in a memory buffer until all of the segments are collected.
Consumed immediately. For example, the data can be stored immediately in a database or written to disk as each segment is received.
```

**Comment by guardrex** [comment]
The problem is one-way ... **_incoming to the hub_**, so it's mostly when a large message goes from JS to .NET. It's probably content for the *Call .NET from JS* topic. I think I'll only cross-link the other way for this.

Also, overloaded words like "**_inputs_**" are part of the problem here. The language is tricky, and I'll need to work with it a bit to get it just right.

**Comment by MarkStega** [comment]
Minor disagreement - It is just as relevant to "Call JS from .Net" if the value attempting to be returned is big (say a file or a graphic image, etc). But I'll step back and let you wordsmith appropriately...

**Comment by guardrex** [comment]
> value attempting to be returned

That's a good example of the phrasing problem ... "returned" is overloaded when communication goes both ways and methods **_can_** (but aren't required to) return values in both directions. It's easy to discuss such a scenario and *not know which way the large message is going* ... to the hub or away from it. It will need to be worded carefully. I'm working on it now, and we can see on the PR if I worked it out or *screwed it up even further* 😝.

AFAICT, the focus is on what the framework/dev is controlling, which is the message size **_incoming to the hub_**, not when messages go out of the hub. I expect the coverage should go in the *Call .NET from JS* topic with a cross-link from the existing (but revised) *Size limits on JS interop calls* section in the *Call JS from .NET* topic. The cross-link can explain the scenario but not go into all of the juicy details. We'll see how it composes and modify further on the PR. Javier may agree to cover equally from both sides, then we can do exactly what you suggested with an INCLUDES file.

Let's see how it turns out. I should have the PR up shortly.
