### ISSUE TITLE
Missing information from the article.

### ISSUE THREAD

**Issue by hasmm** [dotnet/AspNetCore.Docs#21265]
Hello, 
It would be great if you can add the below details:

1- For every new project we create using visual studio, do we have to create an app in ADFS? Different projects will have different URLs, so perhaps suggest a way to avoid this issue would be great.
2-Perhaps expand the article to show how to assign custom user roles to users after they have authenticated with ADFS.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d6d442-8d46-3f9e-e75a-ad9d900fc117
* Version Independent ID: d07c4058-452f-cdac-c59d-8f09e70a43f3
* Content: [Authenticate users with WS-Federation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/ws-federation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/ws-federation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @chlowell
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.

See https://github.com/dotnet/AspNetCore.Docs/issues?q=%22d07c4058-452f-cdac-c59d-8f09e70a43f3%22
