### ISSUE TITLE
markdown errors

### ISSUE THREAD

**Issue by AndrewTriesToCode** [dotnet/AspNetCore.Docs#21290]
There are over 3 dozen markdown errors on this page. The text looks like:
```
[@page][9]
[@attribute][7]
```

I believe in each case the second set of brackets should be parenthesis instead. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0#additional-resources)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @AndrewTriesToCode ... Looks like a markdown regression. I'll investigate and see what's up. It's not totally uncommon for there to be build system regressions that we need to surface to the MS docs engineers for work. Thanks for reporting this.

**Comment by guardrex** [comment]
Ok ..... it wasn't a build system regression. It was this recent update .......

https://github.com/dotnet/AspNetCore.Docs/pull/21196/files

What happened was that the metadata title for a topic changed in such a way that the title could no longer be automatically pulled into topics ... it was given a lowercase first letter.

btw @wadepickett ... I didn't hear back on why that Razor syntax topic received a lowercase title, but I think it was due to a localization issue, right?

... anyway ........ so what I did was try to specify the link text explicitly. Let me study the markdown rules for this type of link list and get back here with the answer. I believe that there is a way to do it. Back in a bit ................ stand-by.

🙈 lol @Rick-Anderson @wadepickett ... **_Exactly_** what I was saying earlier about moving on 🏃 and forgetting to check the live topic. The [build report is clean on that PR](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C332f35cd-658d-4914-0f85-907e40ee89f0%5CPullRequest%5C202101121138494033-21196%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=103Aah6ZVYXjoAWQXNFFm9tY4XF3lPOVq3XBHw%2BUkOo%3D&st=2021-01-12T11%3A34%3A43Z&se=2021-02-12T11%3A39%3A43Z&sp=r), but I have to tie a string around my finger now to remember to look :eyes: because many markdown features don't work with a local DocFx build (this might be one), don't show up on a build report, and then :boom: when it goes live.

**Comment by AndrewTriesToCode** [comment]
I'm impressed with your quick response and action. Cheers.

**Comment by guardrex** [comment]
Indeed ..... I'll get this sorted out right now, merge a fix, and take it live.

We know that this sort of thing happens. We were joking about this on another issue earlier today. 😈 *Rotten gremlins!* 😈 get into the docs because this is a complex process with a lot of moving parts and we're all working fairly fast 🏃.

**Comment by guardrex** [comment]
Oooooooooooooooo-K ...

```
[1]: <https://en.wikipedia.org/wiki/Hobbit#Lifestyle> "Hobbit lifestyles"
```

... that format *should* 🤞 *in theory* 🍀 *do the right thing* 🙏.

**Comment by guardrex** [comment]
Ok ... https://github.com/dotnet/AspNetCore.Docs/pull/21293

We'll give that a few minutes and see what happens. 🤞

**Comment by guardrex** [comment]
# 🍻 Success! 🕺

https://docs.microsoft.com/aspnet/core/blazor/components

You may need to hit the refresh button in your browser to get the updated page. Thanks again @AndrewTriesToCode for reporting on that. I'll look at that other issue that you opened tomorrow morning.

**Comment by AndrewTriesToCode** [comment]
Confirmed, looks good now. Thanks.
