### ISSUE TITLE
Create a NavMenu component section

### ISSUE THREAD

**Issue by AndrewTriesToCode** [dotnet/AspNetCore.Docs#21294]
The `NavMenu` entry in the docs nav for ASP.NET Core / Blazor / Built in Components links to the same page as the `NavLink` one above it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-5.0#navlink-component)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
You're finding **_all the bugs_** 🐞.

I'll take care of that, too, right now. I hate 🐞 ... 😠.

**Comment by guardrex** [comment]
Ok ... This one is actually **not** quite a 🐞. This is by-design because that section **_IS_** our coverage for the `NavMenu` component. It's described here and not elsewhere.

However, I don't really care for that. I think we should have a short `NavMenu` section to cross-link. That would certainly fix this confusion.

I'll get this done, but this is a lower priority issue, so it will be push back a bit. I have a number of high priority things that I need to work through first.

Thanks again for the reports.
