### ISSUE TITLE
Attach tokens to outgoing requests using other header

### ISSUE THREAD

**Issue by connor-ww** [dotnet/AspNetCore.Docs#21334]
Is there a way to attach tokens to outgoing requests using a header other than "Authorization"?

I am deploying my Blazor app to Azure Static Web Apps and calling the Azure Functions within my solution.  The issue is, Static Web Apps overrides the Authorization header in these requests with their own.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f3209c-2414-9b35-6245-383c9b7c6338
* Version Independent ID: cc8dfcd6-8d93-5aa3-c381-2b613e88cdbe
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @connor-ww ... They've marked the behavior as a 🐞 bug for resolution, and there's even an issue asking specifically about Blazor ...

* https://github.com/Azure/static-web-apps/issues/34
* https://github.com/Azure/static-web-apps/issues/275

It looks like one of the devs there has a workaround using a `X-Custom-Authorization` header instead. I don't personally have experience with the scenario, so I think you should ask that dev on the issue for additional info. Perhaps, they'd be willing to share an example project in a GH repo.

I don't think this will be actionable for us since they intend to fix it.

cc: @javiercn ... in case he has anything that he wants to add.

**Comment by guardrex** [comment]
AFAICT since we won't address in a doc a 🐞 that they'll resolve for the service, we should close. If more readers remark on this in the meantime, then we might add a temporary NOTE. Let's see how it goes. Hopefully, they'll fix the service soon 🤞.

**Comment by connor-ww** [comment]
Thanks for your replies!  Yes, hopefully the header conflict is resolved by the Static Web Apps team.

In the meantime I've implemented a CustomAuthorizationMessageHandler such that it inherits from DeligatingHandler and implements setting authorized URLs and scopes (as mentioned in the doc) as well as adding the auth token to a custom header.
