### ISSUE TITLE
Provide a working example using the standard weather forecast using Azure Authentication

### ISSUE THREAD

**Issue by jerdobi** [dotnet/AspNetCore.Docs#21348]
Just providing snippets of code is difficult to follow.  You should provide the working example in GitHub that was the basis for this guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3039ff79-ee86-20b1-0082-d3899a84c823
* Version Independent ID: af4a3a75-ae52-5f6d-2120-737bc2fefb07
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jerdobi ... We don't do that due to churn in the framework. We don't have the staffing to keep up with having samples for all of these scenarios (there would be perhaps **_six samples_** here) and for each release, which come fairly rapidly in .NET these days. There are only a few of us here with over 400 topics, over 100 samples, and over 500 issues ... *you get the picture!* lol 😅

The way that the topics in this node are designed to work is that you create a sample app from the SDK following the CLI guidance at the top of the topic. As you read down the sections of the topic, you can refer to the sample app that you created locally. In this way, we don't need to maintain a sample app with the topic that we would need to keep updated for each release.

I'll close as a *wont' fix* ... at least for the time being. Management might change their mind one day; but for now, we're going to continue with the current approach. Thanks for your feeback.
