### ISSUE TITLE
Unregister event delegates in Blazor components

### ISSUE THREAD

**Issue by aaronhudon** [dotnet/AspNetCore.Docs#21355]
Re: topic: #validator-components

Isn't it a best practice to unregister event delegates in the blazor component when it's being disposed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#validator-components)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @aaronhudon ... I didn't think to ask at the time when we put this up on [Blazor form validation updates (dotnet/AspNetCore.Docs #19459)](https://github.com/dotnet/AspNetCore.Docs/pull/19459), and unhooking them in this scenario doesn't match one of Steve's examples ([`FluentValidator.cs`](https://gist.github.com/SteveSandersonMS/090145d7511c5190f62a409752c60d00#file-fluentvalidator-cs)). Let's discuss it so that we can see about improving the coverage.

@SteveSandersonMS @RemiBou ... Can you provide guidance for this scenario?

Cross-references:

* [*Component disposal with IDisposable* section in the *Lifecycle* topic](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0#component-disposal-with-idisposable)
* [*Validator components* section in the *Forms and Validation* topic](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#validator-components)

... and **_note to self_** ...

In addition to the event handler question at hand, let's use this issue to also check on and possibly improve the organization our disposable coverage. Consider placing new content for this scenario in the *Component disposal with IDisposable* section and then cross-link to that section from various spots around the docs where we implement `IDisposable`, including from the *Forms and Validation* topic.

**Comment by guardrex** [comment]
@javiercn ... TL;DR ... When it comes to the need to unsubscribe event handlers on disposal, it should be done for delegate methods but not for anonymous functions ... if IIRC and am reading C# guidance correctly.

We currently demonstrate disposal for assigned event delegates :+1: ...

```csharp
editContext.OnFieldChanged += HandleFieldChanged;

...

public void Dispose()
{
    editContext.OnFieldChanged -= HandleFieldChanged;
}
```

... but we **_don't explicitly guide devs_** to not sweat disposal for anonymous functions. We don't have the following example in our docs&mdash;I'm just showing a SxS example of an analogous approach that doesn't require disposal (I think 🤔) ...

```csharp
editContext.OnFieldChanged += (s, e) => HandleFieldChanged((editContext)s, e);
```

In this topic, the examples in one code block are just expressions ...

```csharp
CurrentEditContext.OnValidationRequested += (s, e) => messageStore.Clear();
CurrentEditContext.OnFieldChanged += (s, e) => messageStore.Clear(e.FieldIdentifier);
```

What's the best practice way to compose our examples? Do you favor **_Lambda all the things_**&trade;? If so, I can change our examples, such as our `HandleFieldChanged` assignment ...

* Drop disposal in those cases and not implement `IDisposable`.
* Cover both approaches in our [*Component disposal with IDisposable* section in the *Lifecycle* topic](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0#component-disposal-with-idisposable).
* Make sure that everywhere we address event handlers in the docs that we cross-link to the *Component disposal with IDisposable* section.

**Comment by guardrex** [comment]
I'll leave our current example coverage alone then but take a stab at calling the scenario out in our *Component disposal with IDisposable* section.

I'll confirm/add cross-links to that section in spots where event handler disposal is shown.

Given the delicate nature of this scenario, I'll ping u to review the PR.
