### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by curelom** [dotnet/AspNetCore.Docs#21394]
Thank you this page is helpful, but falls short.  I speaks of Authentication, but nothing of Authorization and B2C.  This is a big issue as I can find very little on the subject and how many websites use authentication, but don't need Authorization?  Very few.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#access-token-scopes)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @curelom ... If you look at the 5.0 topic for B2C, the AAD groups and roles topic shows up in the sidebar ToC ...

https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-5.0

Were you working in 3.x? If so, I have a copy of the prior document in PDF format for 3.x apps that use MS Identity 1.0. I think I can post that PDF to you, and I might put it on the repo and cross-link it into the topic. I didn't do that when we put up the 5.0 updates because MS is keen to move devs to 5.0 and Identity 2.0 asap. We're leaning on it. :smile: ... but perhaps a *bit too much*.

**Comment by guardrex** [comment]
I'll try to drop it in here, and we can see what happens ...

[AAD Groups and Roles 3-1.pdf](https://github.com/dotnet/AspNetCore.Docs/files/5906338/AAD.Groups.and.Roles.3-1.pdf)

Leave this issue open. I think I want to cross-link this into the coverage ... *maybe*.

**Comment by curelom** [comment]
Thank you.   That is for AAD and not B2C.  Very different.

**Comment by guardrex** [comment]
They aren't different client-side, and I'm not aware of any different approaches for B2C service-wise either; although, that might be the case. Our documentation support for B2C has been more limited than for AAD. For one thing in 3.x, the Blazor framework had several rough edges with B2C. It wasn't until 5.0 and Identity 2.0 that those edges were smoothed out or eliminated by Blazor framework and MS Identity updates. I'm thinking, for example, of using B2C with third party Identity Providers (we have redirect and popup mechanisms now for auth, and IIRC it was the lack of a redirect flow that was breaking people) and perhaps one or two of the B2C user flow scenarios became workable.

On the authorization side for components in the app, there's no difference to how you permit and deny access than what's covered at ...

https://docs.microsoft.com/aspnet/core/blazor/security/?view=aspnetcore-5.0#authorization

... with the first step being to establish claims (and/or authz policies based on claims) from the service for user app roles, Azure Admin Roles, and security groups. The claims, authz policies, and/or procedural code permit or deny access to users of the app. I'm not aware of any differences between AAD and AAD B2C in these contexts on the service side. There might be some **_gotchas_** tho. I haven't seen readers writing in lately to inquire on B2C problems.

My plan is that when I reach the Groups and Roles topic within a few months for an update to set up and try all of the techniques with a B2C app to see **_if_** and **_how well_** they work. If everything works 🤞, then I'll merely (perhaps) change the title of the topic ("perhaps" because B2C really is "AAD B2C," so we might leave it alone on that basis) and make a few text updates. If some parts fail, I'll still perhaps change the title and text a bit but provide guidance for B2C users for the **_gotchas_** 😈. If things don't go well at all, I'll need to confer with either or both the Blazor product unit engineers and Azure product unit engineers to resolve problems.

I suggest that you try the approaches in the topic, either the 5.0 live topic if you're working in 5.0 or using the 3.1 PDF if you're working in 3.x. If you hit a snag, I can try to help. I'm not sure about moving the overhaul work on the topic up in priority tho. That might not be possible given the workload right now.

**Comment by guardrex** [comment]
I should also add that ... you know this probably, I'll just link in case others see this ... I'll add that the usual product support forums can be of help for breaking apps and Identity cases when we can't currently provide a lot of product support. We recommend the usual forums ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

... of course, there are others. I'm **NOT** saying that that's the end goal for general guidance. We **DO** want whatever B2C base use case coverage that we need here, barring content that Azure docs provide and that we can cross-link to from here. I'm just saying that it's still early days for Blazor, the framework and coverage are rapidly evolving right now (especially Identity), and the external forums can be helpful.

**Comment by guardrex** [comment]
@curelom ... I slept on it 🛌. I think it's best if we follow what Azure and MS Identity docs have done and try to move devs to Identity v2.0 asap. v1.0 is supported (as is Blazor in ASP.NET Core 3.1), but they're removed all ... or almost all ... of their prior coverage. That's why it isn't published here. I'm happy to provide the 3.1 PDF to anyone who wants it, but I'm not going to publish it.

To recap ...

* Blazor authz is covered generally here :point_right: https://docs.microsoft.com/aspnet/core/blazor/security/?view=aspnetcore-5.0#authorization
* Procedural logic is in the same topic (btw - I'll be moving this section UP in that coverage later) here :point_right: https://docs.microsoft.com/aspnet/core/blazor/security/?view=aspnetcore-5.0#procedural-logic
* AAD (hopefully AAD B2C, too) groups and roles coverage (only for 5.0/Identity v2.0) is here, including authz techniques in the app (I'll perform B2C testing when I reach it on https://github.com/dotnet/AspNetCore.Docs/issues/19286) :point_right: https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-5.0
* If you need product support, we recommend the usual support channels ...
  * [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
  * [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
  * [Blazor Gitter](https://gitter.im/aspnet/Blazor)

If you hit an error trying to use the *AAD Groups and Roles* topic, you can open an issue on this repo using the **This page** feedback button and form at the bottom of that topic, and I'll try to help.
