### ISSUE TITLE
Error: The issuer 'https://login.microsoftonline.com/{TENANT-ID}/v2.0' is invalid"

### ISSUE THREAD

**Issue by ClimberBear** [dotnet/AspNetCore.Docs#21417]
I have followed the instructions in the document.

When I try to run the example
- I'm able to to login to the sample application
- I have checked the returned authorization token, and in the issuer field contains https://login.microsoftonline.com/xxxxxxxxxxx/v2.0 (where xxxxxx is my tenantid)
- But, when I try to call the Wheather page, I get the error 
401 The issuer 'https://login.microsoftonline.com/{TENANT-ID}/v2.0' is invalid"

I have checked in internet, and I have found similar issues in other scenarios (e.g. Angular), but I don't understand the root cause of the error

UPDATE:
I have workarounded the issue forcing the validate issuer in Server application
- Edit Startup.cs
- Add the IssuerValidator option to ConfigureServices (change xxxxxxx for your tenantid)
```
		public void ConfigureServices(IServiceCollection services)
		{
			services.AddAuthentication(AzureADDefaults.BearerAuthenticationScheme)
					.AddAzureADBearer(options => Configuration.Bind("AzureAd", options));

			services.AddControllersWithViews();
			services.AddRazorPages();
			services.Configure<JwtBearerOptions>(
				AzureADDefaults.JwtBearerAuthenticationScheme, options =>
				{
					options.TokenValidationParameters.NameClaimType = "name";
					options.TokenValidationParameters.ValidIssuer = "https://login.microsoftonline.com/xxxxxxxxxx/v2.0";
				});
		}
```

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 3039ff79-ee86-20b1-0082-d3899a84c823
* Version Independent ID: af4a3a75-ae52-5f6d-2120-737bc2fefb07
* Content: [Protección de una aplicación hospedada Blazor WebAssembly de ASP.NET Core con Azure Active Directory](https://docs.microsoft.com/es-es/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1#access-token-scopes)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ClimberBear ... We don't have the staffing to provide much product support, especially right now due to a high volume of priority issues. We can only react to specific doc issues at this time, and there are no reported **_specific_** problems with the topic. I recommend that you re-walk the steps carefully creating a new sample app and compare that along with the topic's sections that show the app's configuration to your app. Usually, a difference in the configuration can be found. If you need product support, you can reach out to devs on the usual support forums for help ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

**Comment by ClimberBear** [comment]
Good morning. I cannot agree with your decision of closing the issue. I can understand triage it, down priority, postpone or ask for clarification or simple sample, but closing a bug with the comment "we don't have resources to investigate" is, imho, no professional. Why? Because now the other people will no able to find it with standard filters or, worse, will think it is solved. And now, more clarification if you decide to diagnose/solve. If you check the workaround (and now I understand how OAUTH2 works), the problem is that the default implementation (with no customization) is not expanding the variable {TENANT-ID}.

**Comment by guardrex** [comment]
> closing a bug

We only work bugs in the topics, not in developer applications or in the framework.

> the problem is that the default implementation (with no customization) is not expanding the variable

**_Ah!_** ... That sounds like you found a bug in the framework. There are two buttons at the bottom of the topics, one to open for us for the document ... one to open a product issue, where they show their repo issue forums (https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md#bugs-and-feature-requests). If you select the button for a product issue, it gets you to the right spot to report a problem with the framework. Open your issue here .......

https://github.com/dotnet/aspnetcore/issues

The reason that I didn't recommend this in the first place was that I misinterpreted your issue. I thought that you were just reporting a configuration problem with the app. **_Sorry that I didn't pick up on that._** 🙈 Open your issue with the product unit, and they'll investigate. Give them steps to reproduce the issue.

**Comment by ClimberBear** [comment]
Thank you for the quick answer. I will do this way. In my own defense, I have to say that I opened the issue in generic, and the bot moved/tagged. I'l try the link you tell me. Thanks again for your patiente.

**Comment by ClimberBear** [comment]
Open as framework bug in https://github.com/dotnet/aspnetcore/issues/29874
