### ISSUE TITLE
ConsoleLoggerOptions.IncludeScopes is obsolete

### ISSUE THREAD

**Issue by DoomerDGR8** [dotnet/AspNetCore.Docs#21469]
This is not an error but a warning: An API is deprecated under the Scopes article:

`logging.AddConsole(options => options.IncludeScopes = true);`

CS0618
'ConsoleLoggerOptions.IncludeScopes' is obsolete: 
'ConsoleLoggerOptions.IncludeScopes has been deprecated. Please use ConsoleFormatterOptions.IncludeScopes instead.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
I just ran into this one, too. It looks like the following change is needed:

```csharp
logging.AddSimpleConsole(options => options.IncludeScopes = true);
```

-instead of-:

```csharp
logging.AddConsole(options  => options.IncludeScopes = true);
```

The change to the topic might not be so simple, though, because this would be the first mention of `AddSimpleConsole`. I haven't seen any guidance that `AddSimpleConsole` _replaces_ `AddConsole`, but it looks to me like that could be the way to go.

There's more information in the .NET Docs: https://docs.microsoft.com/en-us/dotnet/core/extensions/console-log-formatter, which also includes information on how the `appsettings.json` configuration looks.

**Comment by Rick-Anderson** [comment]
I recommend we remove

> The following code enables scopes for the console provider:

And the sample that follows which uses `options.IncludeScopes = true`

@serpent5  let me know if you want to PR that, no hurry.

We should change the top from

> For information on logging in console apps, see .NET Logging.

to something like:

see .NET Logging, which contains detailed information on Logging.

**Comment by serpent5** [comment]
> @serpent5 let me know if you want to PR that.

Sure, will do. Shall I have a go at removing the content that's replicated in the .NET version of this topic while I'm in here?

**Comment by Rick-Anderson** [comment]
> Sure, will do. Shall I have a go at removing the content that's replicated in the .NET version of this topic while I'm in here?

That would be fantastic.
