### ISSUE TITLE
The Option to add razor pages with Entity Framework Models went missing on 16.9.0 Preview 4

### ISSUE THREAD

**Issue by tkrasinger** [dotnet/AspNetCore.Docs#21547]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Where did you get that information?

**Comment by tkrasinger** [comment]
From my VS 16.9 Preview 4:

![image](https://user-images.githubusercontent.com/32831936/107972201-c8957800-6fb3-11eb-8aea-b2a10de1a455.png)

![image](https://user-images.githubusercontent.com/32831936/107972222-d1864980-6fb3-11eb-9ff3-47687f86967b.png)

**Comment by Rick-Anderson** [comment]
That's because you created the wrong project. Compare your image to the tutorial.

**Comment by tkrasinger** [comment]
@Rick-Anderson OK, but here's a side by side comparison on the same newly created blazer server app. Left: Visual Studio 16.8.5, Right: Visual Studio 16.9.0 Preview 4:

![image](https://user-images.githubusercontent.com/32831936/108017830-2eb2e700-7016-11eb-94d5-81a3e8cb3f27.png)

So the option to work with models in blazor (which uses razor pages) is not there any more.
I'm sorry when I used/linked the wrong page from the docs, but thats the only doc I found for working with models in blazor using razor pages.

**Comment by Rick-Anderson** [comment]
@guardrex ?

**Comment by guardrex** [comment]
@tkrasinger ... I think those entries are made available as a scaffolded items; and as seen in the screenshot, 16.9.0 Preview 4 VS is missing the **Add** > **New Scaffolded Item** entry. I don't think that this is a major concern during preview because VS doesn't always offer every bell and whistle or have every feature working properly during preview using preview packages (when they're in play).

I see that you said "the same newly created blazer server app." If you created the app for this comparison inside of 16.9.0 Preview 4, I'd suggest a quick test of creating a new app from the CLI (`dotnet new blazorserver`) and then opening it from its project file (`.csproj`) in 16.9.0 Preview 4 VS to see if that makes any difference. It might make no difference and certainly won't if that's what you did in the first place (or you created it in current release VS).

You can open an issue for the VS team using the [**Report a Problem**](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture from within Preview VS. I assume that they're looking very closely as those issues as they come in. Make sure you open it from the **16.9.0 Preview VS** and not the current release VS.

btw - I did a little search on this. I see devs saying at various times that scaffolded items disappeared during a preview VS release. I see devs hacking around it to bring them back by adding package and CLI tooling references to an app's project file to bring the scaffolding features back. I'll let you explore that further on your own if you want. Of course, such hacks can lead to various 💥 and aren't supported.
