### ISSUE TITLE
Add example images

### ISSUE THREAD

**Issue by CutlerSheridan** [dotnet/AspNetCore.Docs#21544]
[Enter feedback here]
It would be helpful if screenshots of the web page were added throughout the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-5.0)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @CutlerSheridan ... We prefer to use as few images as possible because they're too time-consuming for us to maintain given the workload and staffing. Another problem with images is that we can't rely upon them for anything. The text must cover all of the behaviors of the app created in the tutorial to make the framework accessible to developers with vision impairments. If you feel that any of the textual descriptions aren't clear enough, I would like to hear about those cases so that I can make improvements to the text. Please open new issue(s) for those cases.
