### ISSUE TITLE
ASP.NET Core Identity > App Register action not sending confirmation email

### ISSUE THREAD

**Issue by jconrey** [dotnet/AspNetCore.Docs#21554]
I followed the steps listed in this page, ran the project, registered as a new user, and applied migrations, but I never received a confirmation email after registering as a new user, giving me the impression that the built-in email function for ASP.NET Core Identity is not working out of the box.

Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
That might be the case @jconrey. I can't say because I haven't had a chance yet to explore that Identity scenario. Search the product unit issues first to see if they're working on it. If you don't find an open relevant issue, then you can open your own issue there to ask about it ...

https://github.com/dotnet/aspnetcore/issues

Please add a `cc: @guardrex` and a cross-link to this doc issue to your opening comment so that I can follow the discussion. I have a feeling on this one that there will be something that we can do in the topic to either call out that this scenario isn't supported or how to support it. If discussion with them leads to an actionable doc issue, I'll re-open this and address it asap, or I'll add it to my [UE ("user experience") tracking issue](https://github.com/dotnet/AspNetCore.Docs/issues/19286) (i.e., topic overhauls) for work when I reach this topic.
