### ISSUE TITLE
Protos\greet.proto: No such file or directory

### ISSUE THREAD

**Issue by SogoGolf** [dotnet/AspNetCore.Docs#21657]
followed https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-5.0&tabs=visual-studio#create-a-grpc-service

created template gRPC prod in VS 2019, both with .net 5 and .net 3.1. neither worked and project won't build.

named project "GrpcGreeter".

the services class has multiple ref errors. (nb: the SSL security popups did not appear) 

<img width="767" alt="image" src="https://user-images.githubusercontent.com/19580787/109574705-8daf4a80-7b44-11eb-9576-1a844c985965.png">

<img width="281" alt="image" src="https://user-images.githubusercontent.com/19580787/109574655-75d7c680-7b44-11eb-8149-c49bd8e459b3.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
@wadepickett  can you verify the tutorial works?

**Comment by wadepickett** [comment]
Thanks #SogoGolf for taking the time to show us what you were running into.

I followed the tutorial using  Visual Studio 2019 version 16.8.5 and the latest .NET SDK.  The resulting new project includes [Grpc.AspNetCore 2.34.0](https://www.nuget.org/packages/Grpc.AspNetCore/).

#SogoGolf you were getting Grpc.AspNetCore package version 2.27.0.  I would guess you might be using an earlier version of Visual Studio than 16.8.5. In the tutorial the client instructions install the latest of the tools, which are also a newer version.  So there is some potential for version mismatch headaches.

For me the server app and the client console app compiled as expected and ran as expected for .NET 5 using those versions I mentioned.

That said this content does need help:  It has never been updated for version 5 and needs to point to the latest Visual Studio and SDK for starters.  I last updated this topic for 3.1 and then it has been updated by a few folks since but not for a 5.0 update.

There was an issue around renaming the namespace in the greet.proto to "GrpcGreeterClient" which was fixed in the doc but was not updated in the current client downloadable sample: The namespace inside the `greet.proto` file for the client sample project's namespace should be:
  *option csharp_namespace = "GrpcGreeterClient";*
but incorrectly, the client sample was showing the original namespace for the server app greet.proto:
 *option csharp_namespace = "GrpcGreeter";*

I will:
* Update the topic for version 5 and fix the client app sample.
* Clarify the instruction for the  SSL security popups.  You will not get those if they were set previously, but the instruction assumes you always would.
* Fix the Client downloadable sample.

**Comment by wadepickett** [comment]
The client sample that doesn't run is a bit of blocker, along with the the mismatch between the 3.1 pre reqs being specified while the latest tooling is still installed.  So I set this to P1 in my queue.

**Comment by wadepickett** [comment]
The client sample namespace issue I mentioned above has been fixed with JamesNK's PR #21732 and merged to main today.

**Comment by SogoGolf** [comment]
Brilliant thanks for quick turnaround
