### ISSUE TITLE
Add some diagrams!

### ISSUE THREAD

**Issue by qlxh** [dotnet/AspNetCore.Docs#21667]
There is a lot of class names and constructs, most of which are very similar. One or two diagrams showing the architecture would help tremendously!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @qlxh ... We won't be able to provide diagrams to go with this topic. Diagrams are difficult for us to maintain due to the high volume of priority issues. When the framework changes, images change, and they're not nearly as easy to update as document text and code examples. As you can see, we have close to 600 issues here ... over 400 topics ... and over 100 sample apps. We just don't have the staffing to support images broadly in the docs at this time. We'll keep an :ear: open for more feedback. If there's feedback from the community that this topic is confusing without visual representations, we'll consider adding diagrams to it. Alternatively, we're open to accepting a submission from the community.
