### ISSUE TITLE
Nuget package references to upgrade are incorrect

### ISSUE THREAD

**Issue by kjhughes097** [dotnet/AspNetCore.Docs#21742]
This page instructs a reader to upgrade all instances of package references to `Microsoft.AspNetCore.*` to version `5.0.0` or later. That seems to be incorrect. Nuget has no knowledge of `Microsoft.AspNetCore.Hosting` version 5. It is still on version 2.2.7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#update-package-references)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @kjhughes097 ... They're no longer tracked by NuGet as a standalone packages because they're part of the shared framework now. See :point_right: https://github.com/dotnet/aspnetcore/issues/3756 (and the cross-linked issues) ... and keeping in mind that that the `.App` package is implicitly referenced when you set the TFM these days, so there's no `.App` package ref required. I believe that if go back to the earlier 3.0 migration topic, you'll see the guidance for the changes that were put out by the doc team at that time.
