### ISSUE TITLE
'Server' keyword exception

### ISSUE THREAD

**Issue by topweeradet** [dotnet/AspNetCore.Docs#21887]
VSCode - Window tutorial

The problem only occurs when open https://localhost:5001/Movies. I guess in the scaffolding step miss '-sqlite' for generating the correct connection string.

Without -sqlite
`"ConnectionStrings": {
    "RazorPagesMovieContext": "Server=(localdb)\\mssqllocaldb;Database=RazorPagesMovieContext-6d928de8-07d6-40a3-aac5-0282c61ff5a2;Trusted_Connection=True;MultipleActiveResultSets=true"`

After add -sqlite
`"ConnectionStrings": {
    "RazorPagesMovieContext": "Data Source=RazorPagesMovieContext-7736068c-1c78-4f01-943c-6ab74a71edfc.db"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, sounds like you missed that.

**Comment by Balonich** [comment]
@Rick-Anderson but the '-sqlite' param is missing in the documentation. And for some reason without it the connection string in the appsettings.json file looks like:
`"ConnectionStrings": { "RazorPagesMovieContext": "Server=(localdb)\\mssqllocaldb;Database=RazorPagesMovieContext-6d928de8-07d6-40a3-aac5-0282c61ff5a2;Trusted_Connection=True;MultipleActiveResultSets=true"`
And because of this after opening https://localhost:5001/Movies or after performing `dotnet ef database update` command "'Server' keyword exception" error occurs. I've changed this line manually to `"ConnectionStrings": { "RazorPagesMovieContext": "Data Source=RazorPagesMovieContext-7736068c-1c78-4f01-943c-6ab74a71edfc.db"` and now everything works fine. It this okay or not?
P.S.: I'm using VSCode
