### ISSUE TITLE
ASP.NET Core Module compatibility

### ISSUE THREAD

**Issue by avendel** [dotnet/AspNetCore.Docs#21910]
_This question might be more related to the actual library rather than the documentation, but the answer should probably be available in the documentation, so I'm creating the issue here._

There is a new version of the ASP.NET Core Module v2 binaries made available with every .NET release. Does this mean that the only supported way of running ASP.NET applications in IIS is via the version of the ASP.NET Core Module released with a particular .NET release?

Some smoke testing indicates that it is possible to run e.g. NET 5.0 apps with the hosting bundle released with 3.1. This is in line with what is mentioned here: https://docs.microsoft.com/en-us/answers/questions/176303/net-core-31-apps-with-the-net-5-hosting-bundle-are.html

There are two major reasons this compatibility is important:

1. Being able to host multiple applications in IIS on the same server, but using different versions of .NET/.NET Core.
2. Avoid having to restart IIS and take down other applications when installing an application/service using a newer .NET version.

Both these points are important for installations where different services/applications have their own release cycle, and making other services unavailable during the upgrade of one service is highly undesirable. It can be especially problematic forcing IIS or server restarts for on-premise installations where the application developer is not in control of the hosting environment. 

So I'm hoping for an answer that the ASP.NET Core Module v2 is compatible with multiple versions. It would great if e.g. the ASP.NET Core Module released with 3.1 could host applications using .NET 6. No matter the answer, I suggest adding that information to the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @avendel ... They're backwards-compat for supported framework releases but not necessarily forward compatible ... and very probably **_not safe to use_** forward in some cases. Features might be absent, and that's its own concern, but there have been security updates to the ANCM along the way, so using an old one is likely 💀 *dangerous* 💀 in some cases. It's true, as you say, that the ANCM and Hosting Bundle topics don't provide guidance. 

Ping @jkotalik ... Would u like me to add a section? If so, what guidance would u like in it and which topic do you favor for it, here or the Hosting Bundle topic?

@Rick-Anderson ... This is a quick fix. I can knock it out. 🏃 Otherwise, please re-assign if that's best.

Note to self: Cross-link from the other two spots among the docs at play depending on where the coverage lands ...

* Here, the ANCM topic.
* https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/hosting-bundle
* https://docs.microsoft.com/aspnet/core/host-and-deploy/web-farm

**Comment by jkotalik** [comment]
@guardrex ANCM is forward compatible, and is safe to use. Because of the design on ANCM, most of the feature development happens in a component tied to the dotnet runtime.

So having a 3.1 hosting bundle and 6.0 .NET app will be totally fine.

**Comment by guardrex** [comment]
@jkotalik ... I see ... it looks like that goes all the way back to the 2.x era. I was only concerned because at least one security advisory called out a version and told devs to update ...

https://github.com/aspnet/Announcements/issues/352

... and it wasn't clear if that scenario would ever happen again.

**_"That scenario"_** being that there is no automated notice or update for a security problem **_in the future_**. Today, the docs (by not saying anything) imply that a dev is in good shape *forever* without a concern.

We could cross-link to the *Announcements* repo issues from these three topics with link text that indicates security advisories pertaining to the ANCM are posted there.

**Comment by jkotalik** [comment]
> We could cross-link to the Announcements repo issues from these three topics with link text that indicates security advisories pertaining to the ANCM are posted there.

Do we do that anywhere else in the docs? Posting security advisories in docs isn't common from what I can tell.

I think documenting that ANCM is forwards and backwards compatible is fine.

**Comment by guardrex** [comment]
Not "posting" or linking anything specific, just cross-linking to the repo issues. Let me try it and show you what I mean on the PR. We can 🔪 the draft cross-link easily enough if it turns out to be a bad idea.

> I think documenting that ANCM is forwards and backwards compatible is fine.

Ok ... I'll do that. I should be able to do it within a few hours and ping u from the PR.
