### ISSUE TITLE
Why samples still using .net version "1.0.0-preview2-003131"

### ISSUE THREAD

**Issue by babula38** [dotnet/AspNetCore.Docs#21971]
# Issue description

Just need to understand why these samples need .net core [1.0.0-preview2-003131], I guess which Out of support versions now. reference https://dotnet.microsoft.com/platform/support/policy/dotnet-core

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

* [ ] .NET Core
* [ ] .NET 5.0 or later
* [ ] .NET Framework
* [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by babula38** [comment]
Refer the screen shot below.
![docs](https://user-images.githubusercontent.com/4153708/113473353-be0d4000-9486-11eb-82eb-54358b05919e.PNG)

**Comment by guardrex** [comment]
Hello @babula38 ... We're aware of it, but we can't resolve it quickly due to the volume of high priority issues that need to be addressed. Which sample(s) are you looking at?

@Rick-Anderson ... I meant to update [*ye olde sample tracking issue* (dotnet/AspNetCore.Docs #5495)](https://github.com/dotnet/AspNetCore.Docs/issues/5495) to provide insight on where things stand, but I've been busy for quite a while and couldn't get to it. The last update was 6/27/2019. *_Yikes!_* It got way under the radar. I'll try to update that when I get some time, but I'm not sure when that will be.

**Comment by babula38** [comment]
@guardrex I was wondering if .net 1 is the requirements. Otherwise I can open a PR for this change. Another question  what is the lowest version of C# the code is compiled? I.e. it is only C# 8 above or less than 8.0 version.

**Comment by guardrex** [comment]
> I was wondering if .net 1 is the requirements.

It's **_way_** out of support, so it shouldn't be used, including for docs+samples here. I'll need to run through the repo and identify where it's lingering so that management can decide what to do in each case. Some samples might be dropped entirely, others upgraded. They'll need to be addressed by management on a case-by-case basis.

https://dotnet.microsoft.com/platform/support/policy/dotnet-core

> I can open a PR for this change

That can be rather difficult to pull off without a lot of prior knowledge (unfortunately). The docs often are paired to their sample apps, so concurrent changes are required in topics for sample updates. The changes often involve versioning the content in the topic and the sample. You still haven't said which sample(s) you're seeking to use. I can't advise further until I know which one(s) you're focused on.

>  what is the lowest version of C# the code is compiled? I.e. it is only C# 8 above or less than 8.0 version.

I think so ... research it further in the C# docs :point_right:

* https://docs.microsoft.com/dotnet/csharp/whats-new/csharp-8
* https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

**Comment by Rick-Anderson** [comment]
Where is the sample? Provide a link.

**Comment by babula38** [comment]
@Rick-Anderson  below is the link https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/mvc/controllers/application-model/sample/src/AppModelSample/Conventions

**Comment by guardrex** [comment]
That one is on the [sample tracking issue](). It's for ...

https://docs.microsoft.com/aspnet/core/mvc/controllers/application-model

**Comment by guardrex** [comment]
Idk @Rick-Anderson if you prefer these marked as a *bug* 🐞 or a *docs experience*. I'll set future labels accordingly after I hear back. :ear:

**Comment by Rick-Anderson** [comment]
Bug.
