### ISSUE TITLE
Working Razor component drag events example

### ISSUE THREAD

**Issue by Jarek300** [dotnet/AspNetCore.Docs#21992]
Could you provide working example of using drag events i.e. ondragstart, ondragover and ondrop? Example should show how to put data into DataTransfer and DataTransferItem .NET objects and how data is received in ondrop event.

The problem was discussed [here](https://github.com/dotnet/AspNetCore.Docs/issues/19913) and postponed until .NET 5 was released.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa724f22-3a49-c7f6-1500-ac2d8dde5894
* Version Independent ID: 5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0
* Content: [ASP.NET Core Blazor event handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Jarek300 ... We might be able to add such an example, but it will take a long time to reach this issue due to many high priority issues in the queue over the next several months. In the meantime if that cross-linked issue doesn't help, reach out to the community for assistance. We recommend the usual community support forums ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

**Comment by Jarek300** [comment]
I'm afraid that you don't understand.

Working example is not needed to better understand how to use 'DataTransfer and DataTransferItem that hold dragged item data.'

Working example is needed because there is **no information at all**  about DataTransfer and DataTransferItem classes. 

DataTransfer and DataTransferItem are part of Blazor from the beginning (almost two years) and in that time nobody in the community  has figured out how to use them. Honestly, I suspect that DataTransfer and DataTransferItem classes do not work at all and never did.

**Comment by guardrex** [comment]
It looks like they're going to address at least some drag+drop functionality on https://github.com/dotnet/aspnetcore/issues/18754. You can provide feedback on the work that they're doing on that issue. WRT having JS interop examples, I think we'll have to see what they come up with for 6.0. There's no point in showing JS interop approaches that their new built-in features will address with C#. In theory, we'll have the new features, whatever they are, documented by 6.0's release.

**Comment by guardrex** [comment]
Leave this issue open ... I'll use this issue to track the work for 6.0.

**Comment by guardrex** [comment]
I'm going to move this to P3 ("Priority 3") and mark it for the PU ("product unit") ...

* Eventually, they'll schedule work at https://github.com/dotnet/aspnetcore/issues/18754. If they say tho that they plan to build something into the framework for .NET 7, that's too far out to maintain an issue for here. We'll place a new issue mid-2022.
* When they have a chance to run down the doc issues either in December or 22Q1, they might provide a sample/example for this sooner than providing built-in framework feature. In that case, we'll use this issue to track the work. Stand-by a bit longer because they can't be pinged about this right now. They're all 🏃😅 on the mop-up of the 6.0 release.

**Comment by guardrex** [comment]
We're going to go with **_Option 1_** ...

> Eventually, they'll schedule work at https://github.com/dotnet/aspnetcore/issues/18754. If they say tho that they plan to build something into the framework for .NET 7, that's too far out to maintain an issue here. We'll place a new issue mid-2022.

I usually generate doc issues for upcoming framework releases in Q2 each year from the new features tracking issue that will appear on the PU repo. We'll open a new issue for this when that tracking issue appears for .NET 7. As I mentioned earlier, everyone is welcome to provide feedback to the PU on their open issue for the new feature.

**Comment by puschie286** [comment]
well they mentioned that they will NOT implement this feature [source](https://github.com/dotnet/aspnetcore/issues/18754#issuecomment-1071573160)
