### ISSUE TITLE
Blazor DynamicComponent

### ISSUE THREAD

**Issue by daveabrock** [dotnet/AspNetCore.Docs#22005]
Good morning,

I'm not sure your timeline in documenting the `DynamicComponent` released with .NET 6 Preview 1, but I can lend a hand if you'd like (I [wrote about it](https://daveabrock.com/2021/04/08/blazor-dynamic-component) just now and it seems to be straightforward).

**Comment by guardrex** [comment]
We usually hold off a bit on new coverage because ...

* PU churn in the past has caused problems: Before features settle into a close-to-final form, we end up having to revise docs (sometimes more than once) during the preview/RC phase. It's generally been less costly 💰 to wait a bit longer. Things don't change much at or after RC1 ... *usually* 🤞.
* I've been very busy with UE passes, so it's just as well. If I had to sweat a lot of 6.0 coverage right now, it would have radically slowed down the UE passes, which are desperately needed imo.
* Also, we haven't had major time crunches documenting a release when starting most of the coverage just before or at RC1's release. It's especially been the case because PU engineers provide a lot of the content, so I have material to edit and polish up for the coverage. I haven't had to draft a lot of content from scratch each release. We usually get ... er ... say 90% (or more) in place for the GA.

Yes ... AFAIK, you're welcome to provide the content. Let me get back to you later today on location for it. I'm ⛏️⛰️😅 right at the moment. I'll get back to u soon. 🏃

**Comment by guardrex** [comment]
Still buried in work ... let me get back to you @daveabrock early next week. 🏃🏃🏃🏃🏃🏃😅

**Comment by daveabrock** [comment]
Appreciate the follow-up ... no rush on my end. Just putting it out there, and makes sense with the timing as it's still early. It can wait.

**Comment by guardrex** [comment]
Ok ... I'm *BACK*. There are two ways to go ...

* Section in the *Components* overview topic: It would have to be considerably shorter (text and example) than what's in your post. The example would probably roll both with and without params. It would probably be more *bare bones*, similar to what DR did in the blog post ... minimal example code ... quick explanation.
* New topic: Could be long and written out similar to your post with the larger example and separate section for optional params. You can use your post text as the basis of the whole thing if you like.

I don't have a preference between those two options. I'll leave it up to you.

WRT sample code, I'll leave it up to you on whether or not it goes into the topic (triple backtick code blocks) or into the new snippet sample apps. I can always roll the code from the topic into those apps later, which would simplify what you need to do. I'll provide more guidance depending on your decision. 

WRT metadata and whatnot, let me know which approach you prefer for coverage :point_up:. I'll provide more guidance based on your decision.

**Comment by guardrex** [comment]
btw - I'm going to ping Artak and DR offline to ask about location for this. If they don't respond, we'll go with your preference.

**Comment by guardrex** [comment]
We'll also get an answer on https://github.com/dotnet/aspnetcore/issues/31754 before proceeding here.

**Comment by daveabrock** [comment]
Personally, I would prefer the second approach. I've already got most of the content and I think the parameters section should help iron out some lingering questions.

**Comment by guardrex** [comment]
Fine with me. I pinged them offline. Let's give them a few days to react. I'll get back to you .... errrrrrrrr 🤔 ... Friday ... probably 🤞.

It will be called `DynamicComponent`, so the doc text will appear as ".... `DynamicComponent` component ..." ("... \`DynamicComponent\` component ..."). Steve isn't keen on "Dynamic" alone (or a substitute word). I understand his reasoning for keeping it the way that it is. It's just good to confirm that they're happy with the naming before both framework GA and the doc content is created.

I'll put the rest of the nitbits on metadata and whatnot here on Friday.

**Comment by guardrex** [comment]
Ok ....... I'm *BACK!* 🏃

Let's discuss further where needed. Here are my *off-the-top-of-my-head* 🧠 ideas ...

* Physical location and filename: `blazor/components/dynamic-component.md`
* ToC (`toc.yml`): Place it between *Component virtualization* and *Templated components* ...

  ```yml
  - name: Dynamic component
    uid: blazor/components/dynamic-component
  ```

* Metadata: I recommend that we try to avoid localization problems (i.e., having to code-fence things) as much as possible in the title and description ...
  
  ```
  ---
  title: ASP.NET Core Blazor dynamic component rendering
  author: daveabrock
  description: Learn how to dynamically render components in ASP.NET Core Blazor apps.
  monikerRange: '>= aspnetcore-6.0'
  ms.author: riande
  ms.custom: mvc
  ms.date: 04/16/2021
  no-loc: [appsettings.json, "ASP.NET Core Identity", cookie, Cookie, Blazor, "Blazor Server", "Blazor WebAssembly", "Identity", "Let's Encrypt", Razor, SignalR]
  uid: blazor/components/dynamic-component
  ---
  ```

  If you want me to get the pings on it, put `guardrex` in as the `author`.

* We won't be able to cross-link to the API docs until GA, so use inline code-fencing for now. The API is here ...

  https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/DynamicComponent.cs

  ... and there are some tidbits in the API comments of interest.

* They're going to go with `DynamicComponent`, but it's painful to see a noun repeated as it's own adjective. *Yuck!* 😄 ... but let's have your examples not use the word "Component" in their names. For example, use `Rent` (`Shared/Rent.razor` ... but I understand that you won't need to use the path/filename in the topic) over `RentComponent` and refer to it as "... the \`Rent\` component ..." ("... the `Rent` component ...") in the text. Otherwise, docs end up with the 🙈 phrasing "... the `RentComponent` component ..." for localization purposes (i.e., the word "component" should be in text and translated). I've been avoiding the word "Component" in component type names for a while now with success. :+1:
* Because this is a reference doc, I recommend reducing the blog's introduction down to just the key points: What is it? What problem(s) does it solve?
* WRT sample code, use code blocks in the doc. Although we **_might_** start building snippets for preview, I kind'a think that's a bit much right now to roll into this. I'll *possibly* circle around later after GA and update the topic by moving the sample code into the snippets apps. If I do that, I'll ping u on it.
* WRT to images, we generally avoid them: They're too time-consuming to keep up with 🏃😅 and in light of possible Blazor style changes for UI shots. They aren't accessible for screen readers. I've had success in a few spots just showing the rendered HTML in code block. It makes the point well enough and is super easy to change when needed.

I think that's about it. Let me know if you have any ❓. **_Thanks again for helping with this, @daveabrock!_ 🎷**

**Comment by daveabrock** [comment]
What, you don't want it to be called "Dynamically render components with the DynamicComponent component"?

This all sounds good. I imagine there's no rush on your end, as it's still early-ish preview days. I should be able to get to this in the next month or two (maaaybe three).

**Comment by guardrex** [comment]
Yes ... unless DR/Artak ask for early coverage. In the meantime, I can always respond to a community ask with "*Yo! Check out this killer blog post by Dave!*"

**Comment by guardrex** [comment]
@daveabrock  👌 **_Ok! Ready for this one._** 👌 

I think the notes that I provided above ☝️ https://github.com/dotnet/AspNetCore.Docs/issues/22005#issuecomment-821130971 are good. Let me know if any of that seems off or if u have any ❓.

Confirm that the `no-loc` metadata is up-to-date ... that gets updated occasionally. Any topic on the repo will have the latest.

You can go ahead when ready. There's no giant rush ... we have several weeks.

Feel free to use as much of your blog content as you like. I like your example there.

BTW ... I've been thinking and working on hybrid reference-tutorial style topics and improving my approaches in general. The hybrid approach seems to be working well with readers.

I've adopted either of two approaches ...

* The topic describes the objects, members, and approaches (the reference content) as it also offers the reader the option of dropping example code directly into a sample app on more of a per-section basis. This works best when there isn't a lot of demo code for the subject ... a single, short example component does the trick ... the reader click-copies from the doc into their local test app ... it runs ... it works ,.. they get it ... all good.
* The other approach is for where there's a lengthy setup with several interacting parts or where the whole topic is describing the feature. The opening sections only have (generic) reference material on the framework aspects (C#, Razor, components, etc.) and then have a *Complete example* section that's like a mini-tutorial that the dev can run down step-by-step for a live experience. With this *Complete example* approach, the earlier reference content can make liberal use of placeholders ... like ......

  > The \`@typeparam\` directive *blah blah blah*. The following example *blah blah blah*.
  >
  > \`\`\`razor
  > @typeparam {TYPE}
  > \`\`\`
  > 
  > The `{TYPE}` placeholder is the generic type parameter to apply to the component.

  ... and then the *Complete example* section would have a fully working example ... the type would be specified ... the locations of things are specified ...

  > The following example *blah blah blah*.
  >
  > \`Shared/TypeParamExample.razor\`:
  >
  > \`\`\`razor
  > @typeparam TItem
  >
  > ...
  > \`\`\`

I haven't thought too much about this particular subject on `DynamicComponent`. It kind'a looks like the initial part of your blog post is reference content ... and the end piece on *Pass in parameters* is also reference material (maybe). Those might be the opening reference sections with placeholders (`{...}`). There then might be a *Complete example* section with the rest. Anywho ... I'll yield to you to see what you want to do with it.

**Comment by guardrex** [comment]
@daveabrock ... There's a big shakeup in Blazor docs going to version-by-files (groups) from whole-topic-versioning. Signal me here when you're ready to start working on this.

Alternatively if you won't have time to address this issue, I can take your blog content, turn it into a doc, and give you full credit. Let me know ... I'd try to work it up in a week or so ... **_maybe_** 🏃🏃🏃🏃🏃🏃🏃😅.

**Comment by guardrex** [comment]
@daveabrock ... Did you still want to make a topic out of your blog post? ... or do you want to permit me to make a topic out of it and slap your name on it? The version-by-file setup is in place. We're still wringing the final bugs out of it, but it's 90% working. I can provide the easy guidance now for setting up the topic if you plan to do it. :ear:

**Comment by daveabrock** [comment]
Hey @guardrex - I apologize for the delay. I am incredibly swamped for the next month or so, so if you'd like it done by then I sadly won't be able to get to it by then, sorry. No issues with you making a topic out of my post, if you wish.

**Comment by guardrex** [comment]
Great ... I'll take care of it. You can have the credit. I'll put you on there as author in text. Do you also want the the topic pings (as `author` in metadata)? If not, do you want to remain on the CSS isolation topic for pings ... you are currently `author` on that one?

**Comment by daveabrock** [comment]
Hey Rex, no issues on having the pings.

**Comment by guardrex** [comment]
Ok ... I'll update that on the next commit.
