### ISSUE TITLE
Doesn't run as written

### ISSUE THREAD

**Issue by jmfullerton** [dotnet/AspNetCore.Docs#22027]
Was unable to complete the sample as written because it doesn't use the "--no-https" flag.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-5.0)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jmfullerton ... That's not the typical use case. Generally, we intend devs to learn how to build apps that run securely. Then if they absolutely must run with insecure endpoints, they can explore that as a separate use case using the HTTPS docs that we've posted.

**Comment by jmfullerton** [comment]
The desire for everyone to use HTTPS doesn’t change the fact that the example doesn’t run as written.

**Comment by guardrex** [comment]
I can't interpret that. Either ...

* You're asking for a version of the tutorial that works OOB without secure endpoints because you have to run that way for some reason.
* You're having trouble getting the ASP.NET Core development certificate installed/configured.
* You can't get the tutorial to work at all, even with an insecure endpoint.

Error reports have to have more information to be meaningful. We can't guess what's going wrong from such little info.

WRT the tutorial requiring secure endpoints, we aren't going to change it. Although I happen to agree with their decision, this isn't my call anyway ... this was management's decision. You can configure any ASP.NET Core app to run without secure endpoints at your discretion.

If you're having trouble with development certificate installation and configuration, see ...

https://docs.microsoft.com/aspnet/core/security/enforcing-ssl#troubleshoot-certificate-problems

We're unable to provide very much product support here. We only work on docs here, and we have a giant backlog of work all the time. You can reach out to an active community on the usual support channels who are generally eager to help devs resolve problems, such as ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

Of course, bug reports are a different matter. We do respond to those; however, there's nothing wrong with the tutorial AFAIK. A bug report for the tutorial would have to be more specific to understand and take action on. I suspect thus far that you have a development certificate install/config issue, not a bug report for the doc ... but again ... I'm just guessing at this point based on your remarks.
