### ISSUE TITLE
please add a section to this tutorial about "How to deploy to a local IIS".  You have links to other articles, but they do not work.  

### ISSUE THREAD

**Issue by synapsys11** [dotnet/AspNetCore.Docs#22090]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @synapsys11 ... This topic cross-links to the *Host and deploy* node at ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-5.0

... which includes a section on IIS. We don't include IIS deployment guidance across the doc set in sections because it would duplicate the content and be very difficult to maintain.

**Comment by synapsys11** [comment]
yes, I agree with your response.  I finally got my IIS deployment to work,
even with swagger.  Kind of annoying day to get that working!  ha ha.  Now
onto Blazor!
