### ISSUE TITLE
"Client Id", "Client Secret ID", "Application (client) ID" confusing

### ISSUE THREAD

**Issue by prekel** [dotnet/AspNetCore.Docs#22206]
"Client Id" may be a little confusing because when obtaining "Client Secret", there is also "Client Secret ID" obtained. But "Client Id" is actually  "Application (client) ID".

There is a comment on a related issue: https://github.com/MicrosoftDocs/azure-docs/issues/37847#issuecomment-760544779

Maybe the article could have a warning about needing exactly "Application (client) ID"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@01binary we've never had a problem with this. Can you review this issue?

**Comment by 01binary** [comment]
This is an issue with UX in Azure Portal. The App Registration in Azure Active Directory has these basic properties:

* Client ID
* List of Client Secrets

I would say this is somewhat unusual because other social authentication providers like Facebook, Google and Twitter only let you have one Client Secret. You can re-generate it any time but you can't have multiple.

Since Azure lets you associate more than one Client Secret with the same Client ID, each Client Secret has its own ID. Essentially that's AppRegistration.ClientSecrets[n].ID as opposed to AppRegistration.ClientID.

Here's a screenshot with Client ID (this is displayed up front on the Overview page for the App Registration):

![image](https://user-images.githubusercontent.com/19985964/117400390-5d26bc80-aeb7-11eb-8d29-1a2410e0f23c.png)

Notice it's labeled "Application (client) ID", and that's probably because the UX designer didn't want it to be confused with all the other IDs.

Here's a screenshot with Client Secret ID (this is on the Certificates & secrets page):

<img width="1290" alt="Client Secret ID" src="https://user-images.githubusercontent.com/19985964/117400440-79c2f480-aeb7-11eb-99ca-10d375822463.png">

Notice it's on the very bottom right - even though I only have a single secret there, there is one row for each secret and the last field in each row is "ID" which could be misconstrued as Client ID, since it appears right next to the secret itself.

The proposed change here is to mention that by Client ID we mean the read-only field on the App Registration Overview page labeled "Application (client) ID", which makes sense.

**Comment by Rick-Anderson** [comment]
> The proposed change here is to mention that by Client ID we mean the read-only field on the App Registration Overview page labeled "Application (client) ID", which makes sense.

Fantastic work. Do you want to PR this or should I?

**Comment by 01binary** [comment]
I don't have the docs repo cloned/recently forked, but I might be able to PR this weekend if you don't get to it first.
