### ISSUE TITLE
Missing documentation for the `view` argument

### ISSUE THREAD

**Issue by avisser** [dotnet/AspNetCore.Docs#22227]
The docs cover the `area`, `controller`, and `razorpage` args, but not `view`. Please complete the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517fdd63-f70b-a52b-56fa-e5051a13ae00
* Version Independent ID: 754e1c4d-4742-a83b-7f2d-5dead439e569
* Content: [dotnet aspnet-codegenerator command](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Need to add the following

Selected Code Generator: view

Generator Arguments:
  viewName     : Name of the view
  templateName : The view template to use, supported view templates: 'Empty|Create|Edit|Delete|Details|List'

Generator Options:
  --model|-m                          : Model class to use
  --dataContext|-dc                   : DbContext class to use
  --referenceScriptLibraries|-scripts : Switch to specify whether to reference script libraries in the generated views
  --layout|-l                         : Custom Layout page to use
  --useDefaultLayout|-udl             : Switch to specify that default layout should be used for the views
  --force|-f                          : Use this option to overwrite existing files
  --relativeFolderPath|-outDir        : Specify the relative output folder path from project where the file needs to be generated, if not specified, file will be generated in the project folder
  --controllerNamespace|-namespace    : Specify the name of the namespace to use for the generated controller
  --partialView|-partial              : Generate a partial view, other layout options (-l and -udl) are ignored if this is specified
  --useSqlite|-sqlite                 : Flag to specify if DbContext should use SQLite instead of SQL Server.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson I can update the doc if you want

Thanks
