### ISSUE TITLE
sample for Blazor Server

### ISSUE THREAD

**Issue by olaf-lange** [dotnet/AspNetCore.Docs#22422]
Hi,
It'd be very useful to have an equivalent sample for Blazor server; quite a few of the referenced types don't exist for Blazor Server and mixing both worlds doesn't seem to be the right approach.

Regards
Olaf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896be20d-1321-0e2f-3efb-d0ce8f1e631a
* Version Independent ID: f5e2b80f-9478-7500-2bc5-930237274f4b
* Content: [Use Graph API with ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/graph-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/graph-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @olaf-lange ...

Blazor Server should use the same guidance that MS Graph API docs show for ASP.NET Core apps (*in theory* 🤞) ...

https://docs.microsoft.com/graph/overview

... and there's at least one AAD docs example at ...

https://docs.microsoft.com/azure/active-directory/develop/tutorial-blazor-server#retrieving-data-from-microsoft-graph

I only worked the content up for WASM because it works like an SPA with regard to Graph access ... it's a bit trickier to get it set up and running. Also, they didn't have anything for WASM at the time. They now have a tutorial for it ...

https://docs.microsoft.com/en-us/graph/tutorials/blazor

... so I'm not sure if we'll even carry Graph API for WASM in the future. This topic might go away if they keep coverage and example(s) over in Graph API and/or ADD docs and that coverage is good.

What's missing is better cross-linking (at least), especially for new docs/examples/tutorials. I'm about to reach the security node of Blazor topics on https://github.com/dotnet/AspNetCore.Docs/issues/19286. I've marked this issue on that topic.

I'll review all of the docs (ours and theirs) and see what we need to do. If I'm ultimately unhappy with their docs/examples, then I'll pitch to our management over here the idea of carrying a full working example/tutorial similar to the WASM doc for Graph. I'll probably even re-open this issue for the work, since creating a Blazor Server version of this doc isn't really a UE ("user experience," i.e., total overhaul) pass work item ... it's a standalone issue that would be worked separately from https://github.com/dotnet/AspNetCore.Docs/issues/19286.
