### ISSUE TITLE
upgrade-assistant upgrade something.csproj

### ISSUE THREAD

**Issue by Alearian** [dotnet/AspNetCore.Docs#22466]
Instructions omit the 'upgrade' keyword

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0591f873-94fa-c678-a905-e002e4f2c902
* Version Independent ID: a84e5712-2926-7e6d-d913-54743070e9e8
* Content: [Learn to migrate from ASP.NET MVC to ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/migration/mvc?view=aspnetcore-5.0)
* Content Source: [aspnetcore/migration/mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by guardrex** [comment]
Hello @Alearian ... That's a bit vague. Can you paste in the line that you're referring to?

**Comment by Alearian** [comment]
Apologies for vagueness.
On the page: https://docs.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-aspnetmvc
The section "Run upgrade-assistant" contains the instruction:
upgrade-assistant .\AspNetMvcTest.csproj

I think its missing the command keyword: ie
upgrade-assistant upgrade .\AspNetMvcTest.csproj

**Comment by guardrex** [comment]
@Alearian ... Re-open that from the bottom of that topic. That explains why the metadata didn't reflect the line you were referring to. When opened from the page, metadata indicates the right location **_and_** pings the author of that topic. In this case, it won't quite ping the right author because Steve doesn't work the docs any longer. However. *someone* will respond on the new issue.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  can you test this?

**Comment by fiyazbinhasan** [comment]
Well, there is no issue with this doc as it does a manual upgrade from ASP.NET MVC to ASP.NET Core MVC.

However, the upgrade-assistant docs are missing an `upgrade` command. Created a pull request https://github.com/dotnet/docs/pull/24505. We can close this one

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson we can close this.
