### ISSUE TITLE
[ResponseCompressionDefaults] Add `application/wasm` to default MIME types list

### ISSUE THREAD

**Issue by mmarinchenko** [dotnet/AspNetCore.Docs#22479]
Source commit: https://github.com/dotnet/aspnetcore/commit/2d3ad1cb0f9872da40c6d143ce4554563971ae04
Doc: https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression#mime-types

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9795b92f-db24-8f1f-88c0-c36666d3526f
* Version Independent ID: 2d56d9b6-3d7b-0204-6c08-8e584fccecc2
* Content: [Response compression in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-5.0)
* Content Source: [aspnetcore/performance/response-compression.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/response-compression.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mmarinchenko** [comment]
`text/javascript` - another entry added to default MIME types list. As far as I can see this relates to **ASP.NET Core 7.0**.

Source commit: https://github.com/dotnet/aspnetcore/commit/b6000f88e22f6bb82a58479992a8860adc4f75a3

**Comment by guardrex** [comment]
Ok ... I'm back ... for a bit. I don't understand the ask. What's the concern here?

I only spotted a couple of points of interest:

* The new 7.0 content is at the **top** of the article's markdown, so it didn't get your, Rick, workaround for broken links until we get to November. With your, Rick, approval, @mmarinchenko could simply cut-'n-paste the entire 7.0 block from the top of the article to the bottom of the article until November, then we'd rotate it back to the top. @mmarinchenko, wait and see if Rick wants to do that because there might be a reason in this case not to do so.
* It might be best to link to the `main` branch of the defaults file and use our INCLUDE under it ...

  ```markdown
  [!INCLUDE[](~/includes/aspnetcore-repo-ref-source-links.md)]
  ```

   Which places the following into the content ...

  https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/includes/aspnetcore-repo-ref-source-links.md

  ... and then do **NOT** list out the default MIME types. The product unit can change them for any release going forward, and the doc will never need an update to cover the changes.
