### ISSUE TITLE
INCORRECT Instructions

### ISSUE THREAD

**Issue by rifarina** [dotnet/AspNetCore.Docs#22493]
The instructions for Publish and deploy an app using "Visual Studio for Mac" is INCORRECT.

I have downloaded:
Visual Studio Community 2019 for Mac
Version 8.9.10 (build 4)

And there is no PUBLISH menu anywhere to be found under the Solution menu or otherwise.

There is absolutely no way to PUBLISH a .Net project using Visual Studio for Mac Community.

![image](https://user-images.githubusercontent.com/36393398/120723329-8713d480-c49f-11eb-8840-fe2b0ff38983.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f92a99a8-6ffa-e5f9-b7ef-f13fa1e0f17b
* Version Independent ID: 51273790-5178-875b-010e-15d7725da535
* Content: [Publish an ASP.NET Core app to IIS](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/publish-to-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/publish-to-iis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @rifarina ... That looks to be the solution's folder. Is the next folder down the project's folder? Can you right-click one folder below ... which should be the project's folder ... which then is consistent with the guidance ...

> Right-click on the project in Solution and select Publish > Publish to Folder.

**Comment by guardrex** [comment]
@Rick-Anderson ... No answer from @rifarina. I think going one folder down resolves this, and that would be consistent with the doc. I recommend closing this. I've made a note here for the next time that I fire up the iMac ... I'll confirm it for sure later.

**Comment by rifarina** [comment]
I can check when I get back to my MacBook.  I'm 99% certain there is no
publish feature no matter at what level you right-click from.

Secondly, once you build a project there is no place to find your built
projects to deploy.  I've looked thru the file system and it's also nowhere
clear or intuitive to be found.  What is the default folder a build goes
to??

Compiler says project compiled successfully.

**Comment by guardrex** [comment]
I'm OOF ... I'll get back to you when I get home in perhaps four hours.

**Comment by guardrex** [comment]
@rifarina ... The guidance is correct. Here's what I see ...

![screenshot](https://user-images.githubusercontent.com/1622880/121450887-2a625f00-c962-11eb-9dc2-1d0be2360682.png)

You can't use built compiler assets for direct use under IIS. You must publish the app and go from there per the guidance.

Just for full disclosure tho in spite of not being able to use the built assets, the built assets are in the `bin` folder. To see the VS folders, including `bin`, it's a right-click on the solution followed by **Display Options** > **Show All Files**.

I don't think there's anything actionable for us here. If you need to report a problem to the VS4Mac team, see ...

https://docs.microsoft.com/visualstudio/mac/report-a-problem?view=vsmac-2019

... and just one more little thing ... you said "no way to PUBLISH a .Net project" ... you mean .NET **Core** project, right? .NET Framework projects aren't supported on macOS/VS4Mac IIRC, so that might explain why you can't find a **Publish** item in the menu if that's what you're trying to do.

**Comment by guardrex** [comment]
Ah ...... is that an `unauthorized.aspx` file that I see in your app??!! ...... .NET Framework ...... no can do. Only .NET Core is supported on macOS, since I think SDK 2.1 (and goes out of support in August).

Yeah ... we can close this. You're not seeing a publish option because it *can't publish a .NET Framework app*.

**Comment by rifarina** [comment]
Let me be crystal clear.

I opened an existing .Net web application previously built using Visual
Studio for Windows 10.

I expect Microsoft intended to support previously built .Net applications
built, designed and compiled on Windows 10.  Did they??

If you can't open and modify existing Windows built .Net web applications
please let me know.

Look forward to clarification and guidance.

I definitely don't see that menu option.

**Comment by guardrex** [comment]
Indeed, that's way, **_WAY_** above our pay grade here. :smile: We just write docs ... we don't dictate to management anything about supporting NetFX on VS. Take that up with them via the VS4Mac *Suggest a Feature* process built into VS4Mac (**Help** > **Send Feedback** > **Suggest a Feature**). You can also look at their Developer Page to see if someone has already put up such a suggestion that you can add a :+1: to ...

https://developercommunity.visualstudio.com/search?entry=problem&space=41

WRT this entire doc set, it's ASP.NET **Core** only.

**Comment by guardrex** [comment]
Also, I'll mention in passing that I'm not sure about [targeting the .NET Framework with a TFM](https://docs.microsoft.com/en-us/dotnet/standard/frameworks) in a .NET Core app for what you have. You can research that further in the .NET Core doc set. For example: https://docs.microsoft.com/en-us/dotnet/core/porting/ ... but there will likely be challenges ... there are NetFX technologies that aren't available in .NET (Core) ... they're dropping "Core" btw these days, so you'll probably just see ".NET" going forward.

**Comment by rifarina** [comment]
This is the article that lays out the differences between .Net Core and
.Net Framework and when to use each:
https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server

.Net Core doesn't support native UI web application development.  No native
designer, no native UI components.
