### ISSUE TITLE
hide implementation details?

### ISSUE THREAD

**Issue by jagercode** [dotnet/AspNetCore.Docs#22504]
I wonder why the implementation details of the backend are part of the public api (url-scheme). 

Since a lot of folks (the majority?) use online tutorials as a basis for their design it is absolute paramount EVERY article MUST adhere to and promote common naming conventions, style and demonstrate good design. 

Imho, it's best to rely on an automatic conversion of internal details like C#'s PascalCase to web's kebab-case? Analoguous to database's Singular table names to Entity Framework's plural. I am not sure whether database object naming is still PascalCase or snake_case nowadays, which would require the appropriate conversion to the universal payload convention which is camelCase in JSON I guess. 

Did I miss something and has the world beyond ASP.NET moved to PascalCase? If not, can you please upgrade this example by demonstrating the configuration of this two-way conversion to keep technology conventions at their respective position. ORM and C# for the code behind: PascalCase, URL naming scheme: kebab-case and Payload naming scheme (JSON: camelCase)
Of which the public api (URL naming) is uttermost important as this is the only thing clients uses and should be a universal convention. Clients should not be aware of the code in which an endpoint is written. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c31071a6-97f2-d0ae-22a7-10e461a3c679
* Version Independent ID: d3227595-fe2a-7630-0379-8da3b1dba2ee
* Content: [Tutorial: Call an ASP.NET Core web API with JavaScript](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-javascript?view=aspnetcore-5.0)
* Content Source: [aspnetcore/tutorials/web-api-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/web-api-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan please respond

**Comment by fiyazbinhasan** [comment]
IMHO, naming conventions are specific to a platform/framework. Indeed in dot net, PascalCasing naming conventions have huge footprints. However, `conventions are not rules`.  Rules are mostly imposed by an organization that you work for (e.g. you should go with camelCased method name instead of PascalCased one whether or not you are writing C# or JAVA code)

By default, a Web API will expose JSON in camelCased format whether or not your properties are in PascalCase or camelCase. The framework adopted this convention because it's a web standard (everyone agrees on a common term). You can of course override this default behavior,

```
var options = new JsonSerializerOptions
{
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
};
```

As for the URL scheme, there is no standard. 

> Only when you read about designing a good restful API, you came to realize that it is good to apply kebab-case for URL-scheme (only for readability purpose)

In Web API, you can override the default PascalCased URL-scheme by doing the following,

```
services.AddControllers(options =>
{
    options.Conventions.Add(new RouteTokenTransformerConvention(
                                 new SlugifyParameterTransformer()));
});
```

```
public class SlugifyParameterTransformer : IOutboundParameterTransformer
{
    public string TransformOutbound(object value)
    {
        return value == null ? null : Regex.Replace(value.ToString(), "([a-z])([A-Z])", "$1-$2").ToLowerInvariant();
    }
}
```

Code snippets that come with an article really focus on `How to represent stuff with the minimum effort possible.` Discussing how to design a full-fledged API for a todo app would be overkill. There is always room for improvements, however. If the Web API design team thinks that it is a good practice to go with kebab-case naming for the URL scheme, then they would certainly enable it by default

Like the URL scheme, EF Core follows PascalCasing for naming a database table. Again that is overridable, 

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<OrderItem>()
        .ToTable("orderItems");
}
```

@jagercode

**Comment by Rick-Anderson** [comment]
Thanks for the great answer @fiyazbinhasan

**Comment by jagercode** [comment]
@fiyazbinhasan thanks for your 4.5-star answer. 

I'd like to discuss further on "minimum effort possible" and also on a single decent Open API url mark-up convention - which may have become obsolete if there are libraries doing this trick for you. 

What would be a great place to discuss these topics further?

**Comment by fiyazbinhasan** [comment]
We can continue the discussion here. 

By "Minimum effort possible", I meant not to bombard a user with a lot of information upfront.

Services/API discovery tool/library like swagger is kind of baked into every ASP.NET WEB API template. You use it only to document your APIs. You can take a quick peek at it and find out whether the API is using kebab-case or PascalCase naming convention for URL segment (change client code appropriately). 

https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-5.0&tabs=visual-studio
