### ISSUE TITLE
Setting up web.config for IIS to connect to service process.

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/AspNetCore.Docs#22538]
I've ran into a brick wall; the documentation is clearly lacking but I think there's more than that as well.

We have this already very large web application written in .NET 5; and it currently hosts itself directly on a service process and really should operate that way. It's not designed to recycle worker processes; but rather gets its best performance if its process runs forever. It was always the plan however to run it from a subtree under IIS; that is accessed by `https://hostname/path` rather than `http://hostname:highport/`; and we're looking to update our own setup instructions to set this up. For cloud installs we handle this in the fan-out application gateway on azure; but some customers host themselves.

What I can't find is documetation for the `<aspNetCore` node; particuarly I believe it should be able to connect to `http://localhost::highport` rather than launch a new process but I can't figure out how. I have been unable to find the reference document on the `aspNetCore` node so I don't know what the true extent of its capabilities are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f99cd387-53b0-8b37-4f2c-fc4edd1ed080
* Version Independent ID: a1fcfbef-c5f0-c0f4-4246-8aee6ac72aea
* Content: [Out-of-process hosting with IIS and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/out-of-process-hosting?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/iis/out-of-process-hosting.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/out-of-process-hosting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jhudsoncedaron ... The guidance that the product unit reviewed and improved recently is here ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/web-config?view=aspnetcore-5.0#attributes-of-the-aspnetcore-element

WRT your scenario: We aren't going to be able to support you from the docs side. You can ask the product unit for advice by opening an issue on their repo at ...

https://github.com/dotnet/aspnetcore/issues

... but be **_forewarned_** 💀 that they're awfully busy and can only offer limited product support for edge case scenarios. They may comment and help you with your scenario, or they may not be able to help and close your issue as a support request that's outside of ASP.NET Core. Closing an issue usually happens when they feel that the question is too far afield of the ASP.NET Core Module's interaction with IIS and the issue is more of a pure IIS hosting question.

As a last resort, you know that you can reach out to pros on public support channels who have worked with similar scenarios. We recommend the usual channels ...

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)

... but, of course, there are others, including IIS-specific channels.
