### ISSUE TITLE
Some problems about `Upload large files with streaming`

### ISSUE THREAD

**Issue by GadHao** [dotnet/AspNetCore.Docs#22541]
I want to upload one large file(about 4GB) via http and save it on disk, so I read the guid and follow the document.

I tried the code [Upload large files with streaming](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0#upload-large-files-with-streaming), but I found I still can't upload a single large file. Because the code try to copy `section.Body` to `MemoryStream` in the `FileHelpers.ProcessStreamedFile`  method. Obviously, this approach is not suitable for uploading a single large file.

This code try to upload multiple files to the serve, and there were multiple files in the request body, so it read every section of request body. Files may be large when they together.

So I think the document is not inaccurate, because it has not provided the method to upload large file, at least not a single large file.

The document description should adjust to `Upload multiple files with streaming` to avoid misunderstandings, and if want to upload a single large file, the stream should copy directly to a `FileStream`

PS：If the author of the document thinks that a large file is a file that does not exceed the size of the MemoryStream , it may be noted in the document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @GadHao ... We don't cover *every* scenario in doc examples, but this is good feedback on this edge case ... **_the super-really-BIG file upload_**  😄. It's apparently not too common ... at least not among devs who work out that they should just adopt a different approach and not report feedback to us. The article has been up in this form for a few years now, and you're the first dev to ask about this.

@Rick-Anderson ... 'The stream should copy directly to a FileStream' is a good idea, and there's the possibility of even merely calling it out in the [*Server and app configuration* section](https://docs.microsoft.com/aspnet/core/mvc/models/file-uploads#server-and-app-configuration) because that's where we keep the various limits that come into play when dealing with large files (e.g., body length limit, Kestrel limit, etc.). I can work on this issue if you want, but it will probably take me until after 6.0 GA to reach it due to its low priority.

@GadHao ... The good news here is that even your issue will help other readers because they'll see it attached to this doc (unless it's closed as a *won't fix*) or we can refer a reader to it who creates an issue about this scenario. Thanks for commenting on it. Rick will decide the best course of action to take.

**Comment by GadHao** [comment]
@guardrex @Rick-Anderson Thank you for considering the issue, I just think that because everyone thinks that Microsoft Docs is best practice, at least close to best practice. Therefore, it is necessary to remind them that when uploading particularly large files, memory consumption should be considered. When they have to do that, they can use a method similar to directly copying to FileStream to avoid possible difficulties.

I'm gald to do something helpful, such as providing relevant code examples.

**Comment by Rick-Anderson** [comment]
@GadHao  if you can write a sample and PR it to https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/mvc/models/file-uploads/samples/5x/largeFiles that would be great. I'll get the development team to review the sample and help you update the doc.

**Comment by andrew-vdb** [comment]
what the point doing streaming (in context of sample code, because you copy the whole thing to memory in the end), why not just use the buffered model (which also support multipart)

its also a bit lazy to ask someone else to write documentation for you, i don't think this is the purpose of open source, its abusing good intent of people

- In the first version (years ago) of that sample code, there was no FileHelper
- Upload large files with streaming --> Rename --> Upload files with streaming/multi part content
- [ValidateAntiForgeryToken] ---> this is not needed in web api (without view) scenario?
- When handling real big file, IsValidFileExtensionAndSignature --> this method is not feasible anymore, just write the file first and validate later?
