### ISSUE TITLE
How do health checks work for Blazor ServerSide?

### ISSUE THREAD

**Issue by chrisbuttacavoliadec** [dotnet/AspNetCore.Docs#22550]
I've set up HealthCheck endpoints for many ASP.NET Core applications. When I try to do this for Blazor, it does not seem to work. This page doesn't address anything about using Health Checks with Blazor - is it even supported? If not, then it should be documented here, because I can't seem to find information about this anywhere.

Thanks for the help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guardrex

**Comment by guardrex** [comment]
@chrisbuttacavoliadec ...

> When I try to do this for Blazor, it does not seem to work. 

As an ASP.NET Core app, a Blazor Server app should (*in theory* 🤞) be able to use the Health Checks API as the topic describes. I haven't heard anything from the PU otherwise; however, there might be some 😈. Explain further 'does not seem to work.' What happens when you make a request to a health check endpoint for a Basic Health Probe after following the guidance in the topic?

https://docs.microsoft.com/aspnet/core/host-and-deploy/health-checks#basic-health-probe

**Comment by chrisbuttacavoliadec** [comment]
I must apologize my friends, I tried the basic probe again and it is now working. I have done this with **many** other ASP.NET Core apps, so I'm not exactly sure what went wrong! I'll close this issue!
