### ISSUE TITLE
aadB2c Hosted Document outdated

### ISSUE THREAD

**Issue by Alienroid** [dotnet/AspNetCore.Docs#22578]
Hi, 

NOTE: If I follow the instructions in this document, it works perfectly here. 

Latest VS2019 and VS2022 preview, the identity that scaffold to use Microsoft Identity Platform (aad and aadb2c) are using this reference: https://aka.ms/dotnet-template-ms-identity-platform  or https://github.com/AzureAD/microsoft-identity-web/blob/master/tools/app-provisioning-tool/vs2019-16.9-how-to-use.md.  The project following that new document doesn't work.

ASK1: maybe add some comment in the page to reference the new reference I listed above. (or have some timeline when the  switch might happens?)

ASK2: Can we have some insight for roadmap into aadb2c features/maturity? I really love the idea and want to move all my identity solutions into aadb2c.

ASK3: Can we discuss how to make aadb2c more blazor friendly. I think having a popup signin process is a challenge these day as users might disable popup. Furthermore, signinsignup page have terrible mobile user experience. Maybe there's more customization I haven't  done, but would be nice to have sample ready (because mobile should be same class as desktop and not an after thought).

ASK4: Not really sure how we can file requests on the new reference link. Do we  just put it in issues (I've  seen lots of feature requests there).

I've did multiple edits, so original questions might be lost already. I guess the request isn't directly to this document after all, so feel free to close. Just like to understand the future roadmap, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Alienroid** [comment]
I can see lots of issues with the new reference that's not listed. Like msidentity-app-sync tool documentation on that page is different than the msidentity-app-sync tool page. and msidentity-app-sync tool behave differently in cli vs visual studio. The list goes on... Just would like to know what's a good timeline to adopt aadb2c. It's a lot of random asks, but I think there's enough interests from others.

**Comment by guardrex** [comment]
Hello @Alienroid ...

1. I'll review the links and update when I reach this topic on my UE ("user experience") passes on https://github.com/dotnet/AspNetCore.Docs/issues/19286.
2. That's not in our area. Azure is a separate product from ASP.NET Core, so even the product unit here wouldn't have much information on that. You'd have to get in touch with the Azure folks through Azure channels.
3. Blazor uses the MS Identity Platform features that are available. This is also an Azure area, so we can't address this generally here. WRT popup vs. redirect: Popup is the default option, but you can use the redirect flow if you want, [as the docs call out](https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c#login-mode).
4. Yes, but it would have to be an Azure docs issues. We're a separate docs group from them.
5. Can't answer on the last (separate) question: We don't provide advice like that here.

The links in the current topics will be reviewed and updated on the existing issue, so there's nothing actionable for us on this one. Put your Azure questions to Azure folks through whatever means that they make available. For example ...

* https://feedback.azure.com/forums/34192--general-feedback
* https://feedback.azure.com/forums/169401-azure-active-directory?category_id=160596
* https://docs.microsoft.com/azure/active-directory/develop/developer-support-help-options (This one is a good because it lists out various channels for support.)
