### ISSUE TITLE
Running all commands as indicated in the tutorial does not automatically update Startup.cs

### ISSUE THREAD

**Issue by NegativeFriction** [dotnet/AspNetCore.Docs#22631]
System: Windows 10
Environment: VS Code
DotNet version: 5.0.301

Action taken to recreate the bug: Install all programs as listed in the tutorial, line by line:

dotnet tool install --global dotnet-ef
dotnet tool install --global dotnet-aspnet-codegenerator
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet add package Microsoft.EntityFrameworkCore.SQLite
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries -sqlite

Result: Startup.cs is not changed by running any of these commands. It can be updated by copying and pasting, but it will not default to the correct data.

Desired outcome: Running these commands should update Startup.cs to be identical to the code shown in the tutorial. 

Note: There's a chance that I just don't recognize that I was supposed to copy and paste the code all along. I don't think that that's the case, but if it is, I don't feel that it is clearly conveyed in the tutorial. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@wadepickett  just tested this and we haven't had any other reports of this problem and lots of folks reporting success. Were all the other files updated/created?

**Comment by NegativeFriction** [comment]
Yes, all other files were updated.

**Comment by Rick-Anderson** [comment]
@wadepickett when can you get this tested?

**Comment by wadepickett** [comment]
@Rick-Anderson,  I will re-test today.  Maybe I unconsciously added something while testing.  I remember being very careful about it at the time though, but I must have missed something.

**Comment by Rick-Anderson** [comment]
For this a simple test is OK. When testing installing global tools, etc, It's best to run through the tutorial on Windows Sandbox. That gives you a clean machine. For MacOS/Linux, create an Azure VM

**Comment by Rick-Anderson** [comment]
My guess is that it works since no-one else has reported the problem. Be sure to use GitHub/VS integration so you can see all the changes.

**Comment by wadepickett** [comment]
Thanks.  I know for sure I uninstalled the global tools and reinstalled, I put it in my notes at the time.  I will do a clean test.

**Comment by Rick-Anderson** [comment]
no need to do a clean test. Just add the model and scaffold.

**Comment by wadepickett** [comment]
I think I found the issue.

If I go through the instructions exactly, but run the package install commands individually, it all works, and startup.cs is updated properly.

However, if I copy the install commands using the copy button in the tutorial, it installs the tools and packages as soon as you paste in the commands on the command line but the last command (dotnet add package Microsoft.EntityFrameworkCore.SqlServer)  sits there waiting for a  return key to execute it.  So unless you noticed, you are moving on from there in th

**Comment by wadepickett** [comment]
Sorry, I meant to comment, not close with comment.  Reopened.

**Comment by wadepickett** [comment]
@Rick-Anderson, for the issue of the last add package command not running when copy/pasting the list of commands from the doc to the command line: I am not finding a solution.  Do you happen to know a solution?    

It is not a problem for Bash since Bash does not run what you past in until you hit the enter key.
It is a problem if you are using PowerShell.  I tried 5.1, Core 6 and 7.1.   In those cases the last command in the list sits there waiting for the enter key, and if you don't notice the last one didn't run in that long list, you are off on the wrong foot with the next step, that package is missing.

If you deal with it how normally would in HTML, the publishing system will error.  
If you try using " && /" at the end of each command  to tie the commands together that works for Bash but not PowerShell.
If you a backtick (line continuation character in powershell) that doesn't work either, dotnet trips on it.
We could add a comment after the last line such as REM or ::  but it feels a bit odd.
Any ideas?

**Comment by Rick-Anderson** [comment]
Keep it consistent with all our tutorials. Don't worry about edge cases.
