### ISSUE TITLE
Several question related to this page

### ISSUE THREAD

**Issue by hanslai** [dotnet/AspNetCore.Docs#22657]
1.  [GraphClientExtensions](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?view=aspnetcore-5.0&preserve-view=true#graph-sdk) this class's default request url is` https://graph.microsoft.com/v1.0/me`, which does not work for Azure China, and there is no doc on how to change the base URI.

Updated the code as below in `GraphExample.razor` for Azure China

```
<h3>Graph Client Example</h3>

@if (user == null)
{
    <p><em>Loading...</em></p>
}
else
{
    <p>Mobile Phone: @user.MobilePhone</p>
}

@code {
    private User user;

    protected async override Task OnInitializedAsync()
    {
        GraphClient.BaseUrl = "https://microsoftgraph.chinacloudapi.cn/v1.0/";
        var request = GraphClient.Me.Request();
        var user = await request.GetAsync();
    }
}
```
Where is the best place to change the base url?

2. Confused about the where to add the scope placeholders
```
public async Task AuthenticateRequestAsync(HttpRequestMessage request)
        {
            var result = await TokenProvider.RequestAccessToken(
                new AccessTokenRequestOptions()
                {
                    Scopes = new[] { "{SCOPE 1}", "{SCOPE 2}", ... "{SCOPE X}" }
                });

            if (result.TryGetToken(out var token))
            {
                request.Headers.Authorization ??= new AuthenticationHeaderValue(
                    "Bearer", token.Value);
            }
        }
```
and 
`builder.Services.AddGraphClient("{SCOPE 1}", "{SCOPE 2}", ... "{SCOPE X}");`

Do I need to put the scopes in both places or one of the two places is good enough?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896be20d-1321-0e2f-3efb-d0ce8f1e631a
* Version Independent ID: f5e2b80f-9478-7500-2bc5-930237274f4b
* Content: [Use Graph API with ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?view=aspnetcore-5.0&preserve-view=true)
* Content Source: [aspnetcore/blazor/security/webassembly/graph-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/graph-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hanslai ...

On 1 ... The code shown here is a general guideline for the developer to further modify for their specific use cases.

One approach might be to set the base URL where the `GraphServiceClient` is returned in `GraphClientExtensions.AddGraphClient`. Instead of what the topic shows for .....


```csharp
services.AddScoped(sp =>
{
    return new GraphServiceClient(
        sp.GetRequiredService<IAuthenticationProvider>(),
        sp.GetRequiredService<IHttpProvider>());
});
```

... you might try something like ...

```csharp
services.AddScoped(sp =>
{
    var client = new GraphServiceClient(
        sp.GetRequiredService<IAuthenticationProvider>(),
        sp.GetRequiredService<IHttpProvider>());

    client.BaseUrl = "https://microsoftgraph.chinacloudapi.cn/v1.0/";

    return client;
});
```

... and even that URL might be something that you load from app settings and not hardcode into the service registration.

I've added your issue to my [UE ("user experience" ... i.e., total overhaul) tracking issue](https://github.com/dotnet/AspNetCore.Docs/issues/19286) so that I can take a closer look at this when I reach this topic for updates. What I might do is make the approach of setting the base URL either a new section or refactor the code so that one explicitly sets it via app settings. I'm going to close this issue, but I will review this issue when I reach the topic for work later.

On 2 ... **_BOTH_** (as the topic states and shows [in the first section](https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/graph-api#graph-sdk)) ...

Here .......

```csharp
Scopes = new[] { "{SCOPE 1}", "{SCOPE 2}", ... "{SCOPE X}" }
```

... and here ...

```csharp
builder.Services.AddGraphClient("{SCOPE 1}", "{SCOPE 2}", ... "{SCOPE X}");
```

**Comment by guardrex** [comment]
FYI @hanslai ... I've ***finally*** reached this topic for work 😅. This was the soonest that I could reach the topic. We've been ***VERY*** busy around here for a long time. I'm actually working over and enhancing all of the Blazor security guidance right now EOY, perhaps even into early January.

I had marked your issue on my tracking issue to make sure that I would address your concerns. I just found out something that will become part of the updates, and I'm going to leave it here, too, in case anyone searches and finds this issue.

You were asking about setting the base URL in the Graph SDK scenario. Consider this approach ...

`appsettings.json`:

```json
"MicrosoftGraph": {
  "BaseUrl": "https://graph.microsoft.com",
  "Version: "v1.0",
  "Scopes": [
    "user.read"
  ]
}
```

For the `GraphServiceClient`, pass in a `baseUrl` (along with the scopes, which I'm also going to take from configuration for the upcoming updates to the topic) ...

```csharp
public static IServiceCollection AddGraphClient(
    this IServiceCollection services, string? baseUrl, List<string>? scopes)
{
    services.Configure<RemoteAuthenticationOptions<MsalProviderOptions>>(
        options =>
        {
            scopes?.ForEach((scope) =>
            {
                options.ProviderOptions.AdditionalScopesToConsent.Add(scope);
            });
        });

    services.AddScoped<IAuthenticationProvider, GraphAuthenticationProvider>();

    services.AddScoped<IHttpProvider, HttpClientHttpProvider>(sp =>
        new HttpClientHttpProvider(new HttpClient()));

    services.AddScoped(sp =>
    {
        return new GraphServiceClient(
            baseUrl,
            sp.GetRequiredService<IAuthenticationProvider>(),
            sp.GetRequiredService<IHttpProvider>());
    });

    return services;
}
```

... and then in `Program.cs`, the `baseUrl` holds the concatenated `BaseUrl` and the `Version` from the configuration. I also take the scopes from config. These are passed to `AddGraphClient`.

```csharp
var baseUrl = string.Join("/", 
    builder.Configuration.GetSection("MicrosoftGraph")["BaseUrl"], 
    builder.Configuration.GetSection("MicrosoftGraph")["Version"]);
var scopes = builder.Configuration.GetSection("MicrosoftGraph:Scopes")
    .Get<List<string>>();

builder.Services.AddGraphClient(baseUrl, scopes);
```

You can see there how the `baseUrl` is going right into one of the overloads of `GraphServiceClient` at ....

```csharp
return new GraphServiceClient(
    baseUrl,
    sp.GetRequiredService<IAuthenticationProvider>(),
    sp.GetRequiredService<IHttpProvider>());
```

That seems to be the cleanest way (with config) to get a base Url into this Graph SDK approach.

I'll ping you on the PR later so that you can see all of the updates that I'm working on.
