### ISSUE TITLE
Controller or scoped service as a state in IMemoryCache entry - bad practice?

### ISSUE THREAD

**Issue by AccessViolator** [dotnet/AspNetCore.Docs#22693]
Shouldn't this be considered a bad practice?
[https://github.com/dotnet/AspNetCore.Docs/blob/05b7c5370f0d23db025671224dcc64dd2286eff8/aspnetcore/performance/caching/memory/sample/WebCache/Controllers/HomeController.cs#L95](https://github.com/dotnet/AspNetCore.Docs/blob/05b7c5370f0d23db025671224dcc64dd2286eff8/aspnetcore/performance/caching/memory/sample/WebCache/Controllers/HomeController.cs#L95)
Controllers are essentially scoped objects and may inject scoped services.
This is at least a memory overuse issue - state object can't be garbage collected until cache entry is removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-5.0)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Hello! Thanks for contacting us. This sounds like a general question about using ASP.NET Core. While we try to look at and respond to all issues, for questions like this we recommend posting to a community support group like [Stack Overflow](https://stackoverflow.com) with the `asp.net-core` tag.

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)

Potential bugs in the ASP.NET Core framework and product feedback can be reported at [dotnet/aspnetcore issues](https://github.com/dotnet/aspnetcore/issues) (include full repro steps and cross-link to a repro project in GH when appropriate). For Visual Studio, use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture or [Suggest a Feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019) gesture within VS, which open internal issues for the VS team. For Visual Studio Code, you can open an issue at [microsoft/vscode issues](https://github.com/Microsoft/vscode/issues).

**Comment by AccessViolator** [comment]
Cache entry's state property keeps a reference to the controller

**Comment by serpent5** [comment]
Yeah, the controller lives on because it's referenced by the post-eviction callback state. This could be problematic because:

1. As already pointed out, it won't be GCed until the callback completes.
1. If the controller instance uses e.g. a scoped service that implements `IDisposable`, it'll have been disposed by the time the callback runs.

The sample could be updated to pass the singleton `_cache` service as the `state`, instead of `this`, to make things slightly better. That doesn't really stop the reader from passing a scoped service in as `state`, though. The sample only does it this way to demonstrate that the callback was invoked, so it might be something that should just stay as-is for demo purposes.
