### ISSUE TITLE
Please add a note how to enable CSS isolation if it isn't working

### ISSUE THREAD

**Issue by BieleckiLtd** [dotnet/AspNetCore.Docs#22728]
Please add a note to stress out that below line is required to enable CSS isolation. 

`<link href="{ASSEMBLY NAME}.styles.css" rel="stylesheet">`

For us migrating from .net core 3.1 it is not added by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @BieleckiLtd ... It's covered by the *Migration* topic ...

https://docs.microsoft.com/aspnet/core/migration/31-to-50#update-blazor-webassembly-and-blazor-server-projects

We don't place migration content into the reference topics because it's a point-in-time problem that would literally **_FILL_** the docs with little migration notes and tidbits 😨. Besides in this case, what you're asking for is already plainly called out in the current text at ...

https://docs.microsoft.com/aspnet/core/blazor/components/css-isolation#css-isolation-bundling

What we'll do on this tho is keep an :ear: open for devs hitting this. If it becomes a regular problem and several issues get opened on it, then we'll add a *Troubleshoot* section to the end of the topic and call out the 😈 *Tricky Gremlin* 😈 there.

cc: @daveabrock
