### ISSUE TITLE
Authentication Library question

### ISSUE THREAD

**Issue by arthurochoa** [dotnet/AspNetCore.Docs#22744]
[**The documentation is under Blazor WebAssembly**. But, can I implement the same Authentication Library (and steps) in a **Blazor Server project**? If not, can you provide me an example or point me to the right direction as to how to implement Authentication Library (**OAuth**, **OpenID** or **custom library**)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985b834f-534a-aba6-80a0-d8845adbfc25
* Version Independent ID: d2b5a556-82a4-e939-be68-2357a3d4408f
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @arthurochoa ... No, it's only for Blazor WebAssembly. As the [Blazor Server overview topic](https://docs.microsoft.com/aspnet/core/blazor/security/server/) calls out ...

> Blazor Server apps are configured for security in the same manner as ASP.NET Core apps. For more information, see the articles under [Overview of ASP.NET Core Security](https://docs.microsoft.com/aspnet/core/security/).

The only additional guidance that we maintain for for Blazor Server in the Blazor docs node is in the two articles under the *Overview* ...

* https://docs.microsoft.com/aspnet/core/blazor/security/server/threat-mitigation
* https://docs.microsoft.com/aspnet/core/blazor/security/server/additional-scenarios

Additional guidance for OAuth with external providers (that apply to a Blazor Server app because Blazor Server uses the approaches as a regular ASP.NET Core app) is at https://docs.microsoft.com/aspnet/core/security/authentication/social/.

If you require product support, we recommend the popular public channels ...

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)

**Comment by arthurochoa** [comment]
Hi @guardrex , thanks very much for your reply.  As I'm new to Blazor learner, my challenge is in navigating to right resource and instructions. Appreciate your feedback and time.
