### ISSUE TITLE
Lifecycle events incomplete / misleading

### ISSUE THREAD

**Issue by GiffenGood** [dotnet/AspNetCore.Docs#22742]
From the text and diagram of the lifecyle events section it says that "Call OnInitialized{Async}. If an incomplete Task is returned, the Task is awaited and then the component is rerendered."

Although it is true that the component is rerendered after the await, it is also rendered prior to the await, because StateHasChanged is called prior to the task being awaited.  IMO, this should be stated explicitly.  If a user doesn't know this they may be confused as to why they are getting null exceptions from rendering when, according to the docs, it should not have taken place yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Razor component lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @GiffenGood ... These descriptions and diagrams have been challenging. I refer you to the last round of discussions and work at https://github.com/dotnet/AspNetCore.Docs/issues/21385. That wasn't the first time we worked the content, either. There was at least one other shakeup here.

I think it's fine to have engineering get involved in another look and discussion to address your remark and review the guidance for further improvement opportunities. Unfortunately, we can't engage with them at the moment. The engineers are focused on high priority work for the 6.0 release, so I can't ping them now. I assure you that this won't get lost, but there will be a delay ... perhaps even a long delay for several months until they get the majority of the 6.0 work done.

**Comment by guardrex** [comment]
Sorry for the delay @GiffenGood. We're well past the .NET 6 release, and the PU is more available these days to help here. I've pinged Steve offline to respond to your concerns.

**Comment by guardrex** [comment]
Sorry again, @GiffenGood! My messages are getting lost in a **_sea of pings_**. Given that I've emailed *twice* on this without a response, open an issue for the product unit. Ask your question about the lifecycle diagram(s)/guidance here ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/22742
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.

Bear in mind that the content on this subject (the diagrams and the text) has had about three full rounds of work that included engineering. They **_were_** happy with what this says/shows the last time that we worked on it. Steve admitted at one point that they are an oversimplification meant to merely capture the general concepts. They might end up telling you that on the issue that you'll open.

**Comment by guardrex** [comment]
@GiffenGood ... Update received from Steve (via email) this morning (3/17) ... Indeed, he confirmed his earlier remarks on this. These diagrams are an oversimplification by design. The general concepts are displayed, and he's happy with what they show in this form. To further explore the behaviors, you'd need to get into the reference source and study when and where the lifecycle methods are called.

**Comment by joostvz** [comment]
Thanks @guardrex, consider it done: https://github.com/dotnet/AspNetCore.Docs/issues/26132.
