### ISSUE TITLE
Client App Registration - Implicit Grant 

### ISSUE THREAD

**Issue by AndrewM114** [dotnet/AspNetCore.Docs#22812]
In the "Register a client app" section on this page, in the list under the line that says:
> In **Authentication** > **Platform configurations** > **Single-page application (SPA)**:

Item number 2 states:

> For **Implicit grant**, ensure that the checkboxes for **Access tokens** and ID tokens are **not** selected.

However, I can only get authentication to work when I leave those checkboxes selected, not unselected.

Furthermore, it seems that the description in Azure specifies the opposite, that for implicit flows they need to be **checked**, not **unchecked**:

![image](https://user-images.githubusercontent.com/19786456/126658225-7861ec3f-c5a6-49c0-90a2-4b0c9860242a.png)

I am following this documentation very closely to configure my apps, my main departure from the documentation is that I am adding authentication to an existing hosted blazor webassembly app (with client and server apps), instead of creating them as shown in the documentation.

Am I missing something, or this documentation incorrect?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3039ff79-ee86-20b1-0082-d3899a84c823
* Version Independent ID: af4a3a75-ae52-5f6d-2120-737bc2fefb07
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
What version are you on @AndrewM114?

If ASP.NET Core 5.0, then implicit grant is **not supported** because 5.0 uses authorization code flow. WRT to the Azure content that you cited, it states "... doesn't use the authorization code flow ..." ... so that's not a contradictory statement. Implicit grant should be disabled.

If you're using 3.1, then flip the doc over to the 3.1 version ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1

... 3.1 does use Implicit Grant, so the checkboxes are selected when registering the client app in the portal.

**Comment by guardrex** [comment]
The docs aren't incorrect AFAIK. This scenario tho ...

> adding authentication to an existing hosted blazor webassembly app

... has always been a bit tricky. The way we wrote the docs, each section of the doc has to be followed carefully, which is likely what you're doing. The whole config is sensitive to one tiny thing being misconfigured. It 💥 ... and often without a clear indication of exactly what the problem is.

What you might want to do is try a separate setup following the topic's steps exactly. Create a fresh test app ... a separate Azure config ... deploy that. If that goes well, then you can SxS compare that setup to your updated app to perhaps locate where the config isn't right.

We occasionally have time to look at dev repro projects, but we also get slammed with work and find it difficult to provide support. That's kind'a the case right now. I'm 🏃 on 6.0 coverage for the upcoming 6.0 release. We recommend reaching out to devs on the usual community support channels for help ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

**Comment by AndrewM114** [comment]
Thanks for the quick response. I was on the 5.0 docs when my app was 3.1. I will follow your recommendations and set up a test app and compare configs, as well as ensuring I am following the 3.1 docs. Thanks again.

**Comment by guardrex** [comment]
Sure thing @AndrewM114 ... yes ... that would explain it. When you drop back and configure for 3.1 via the 3.1 doc, you will see Implicit Grant in use, and it *should* 🤞 ✨ **_Just Work!_**&trade; ✨.
