### ISSUE TITLE
Update typed client registration guidance

### ISSUE THREAD

**Issue by johndhunter** [dotnet/AspNetCore.Docs#22842]
In points 7 & 8 of "Update Blazor WebAssembly" projects you provide guidance for transient http client registration, but not specifically for typed clients eg:

```
builder.Services.AddHttpClient<IMyService, MyService>(
                client => client.BaseAddress = new Uri(MyServiceApi))
                .AddHttpMessageHandler<MyServiceApiAuthorizationMessageHandler>();
```
which would be useful for those using same

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#changes-to-blazor-app-routing-logic-in-501-and-further-5x-releases-up-to-60)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @johndhunter ... That's because there are no default typed clients registered in a default WASM app scenario. However, there's nothing at all wrong with calling it out. I won't be back until Monday. If you want to add that to the topic, select the **Edit** button and submit a PR that has "`Fixes #22842`" in the opening comment. Add the code to a step (`1. XXXXX`) in the list with triple-backticks around it ... you'll see the other examples there when you edit the topic. You can ping me for review. Otherwise, I'll add it on Monday.

**Comment by Rick-Anderson** [comment]
At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by guardrex** [comment]
@johndhunter ... Come to think of it 🤔 ... typed-client registrations didn't change between 3.1 and 5.0 generally. What are you saying changed?

**Comment by guardrex** [comment]
@johndhunter ... I'm closing because I'm not aware of a 3.1-to-5.0 change for typed-client registrations. If you clarify it, I'll re-open this issue.
