### ISSUE TITLE
url of aspnet/core/blazor docs for zh-cn is wrong

### ISSUE THREAD

**Issue by bushuosx** [dotnet/AspNetCore.Docs#22975]
example:
right url for en-us 
https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-5.0
wrong url for zh-cn，（code 404）
https://docs.microsoft.com/zh-cn/aspnet/core/5.0/blazor/hosting-models?view=aspnetcore-5.0
should be
https://docs.microsoft.com/zh-cn/aspnet/core/blazor/hosting-models?view=aspnetcore-5.0

**Comment by guardrex** [comment]
Where does the incorrect URL appear @bushuosx?

**Comment by guardrex** [comment]
Thanks for this report @bushuosx. We've been trying to get the Blazor docs on a new doc versioning system ("DocFX groups"). We ran into a couple of minor problems getting sidebar ToC links to highlight correctly. Engineers who work on the docs build system were looking at the highlighting issue for the sidebar links, and we hoped to have a fix in place quickly. However, none of us knew that the localized docs were using a **_different logic_** for building the links with regard to DocFX groups such that the DocFX groups (versions ... 3.1, 5.0, 6.0 folders) were ending up as URL segments in the links. Indeed, that's just plain wrong.

I'm free this afternoon in about six hours to work on this. I'm going to revert the Blazor docs over to the prior versioning system so that by end-of-day we have everything back to normal.

Thanks again for this report.

**Comment by guardrex** [comment]
@JasonCard ... I've merged https://github.com/dotnet/AspNetCore.Docs/pull/22981 to live, and the problems with Version by File (aka DocFX groups) are resolved for the **English-US** doc set. We're fully back on *whole-topic versioning* now. However, I see that the loc docs will get the updated in the usual delayed fashion. For example, the Chinese ToC still has DocFX group (version) segments in the URLs (the `5.0` shouldn't be in here) ...

```
https://docs.microsoft.com/zh-cn/aspnet/core/5.0/blazor/hosting-models?view=aspnetcore-5.0
```

I feel bad about the loc doc ToCs not working at the moment.

Is it possible for you (or someone) to trigger an 🚒🚑🚓 **_emergency loc doc build_** 🚒🚑🚓? ... or will it happen very quickly on its own ... within hours perhaps?

**Comment by JasonCard** [comment]
@guardrex Thank you for the updates. We actually have a new loc owner for DevTools content @khoiph1 who will help to follow up on this. I'll ping him and explain the situation.

**Comment by guardrex** [comment]
Thanks @JasonCard ... I was told that loc might only build once a week. If that's the case, loc docs will be broken for quite a while 🤦‍♂️. (I wish I would've caught this problem in testing! 🙈). If @khoiph1 can trigger builds up to the latest repo here (current docs state), the loc doc problem should 🤞 be resolved.

**Comment by guardrex** [comment]
@JasonCard ... Just curious while chatting with @khoiph1 offline: Do you know if the European languages (Azure regional datacenters in Europe) for languages like French, German, and Italian build and deploy localized docs on a longer schedule ... like a full week. I ask because a number of languages/data centers have had deployments to fix this, such as Chinese, Arabic, and Spanish. Other languages ... the ones I mentioned ... they still haven't received a loc build/deploy. Rick thought that some of them take a full week. If so, then I made the updates last Sunday ... this Sunday is when these remaining languages will get a build/deployment.

**Comment by JasonCard** [comment]
@guardrex Yes, some languages take longer to localize than others, but it's based on whether we human-translate or machine-translate the language. Machine-translation should be done within the same day, but human-translation is usually on weekly cadence.
