### ISSUE TITLE
Elaborate on "connection string per DbContext" Identity use case?

### ISSUE THREAD

**Issue by TheRealDuckboy** [dotnet/AspNetCore.Docs#22985]
In the [New DbContext instances](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0#new-dbcontext-instances-1) section on this page, following the purple 'Note' box an example is given showing how to create new `DbContext` instances _"with a factory that allows you to configure the connection string per `DbContext`, such as when you use ASP.NET Core's Identity model"_.

Sorry if I'm missing something obvious, but I can't think of the use case indicated for this, or what specifically this is referring to with regards to the Identity model scenario. Can this be elaborated on?

Whilst the example given shows how to create a new `DbContext` via the registered `DbContextFactory` using the connection string named "DefaultConnection", the 'direct' approach of registering a `DbContext` also allows the connection string to be specified:

```
services.AddDbContext<ApplicationDbContext> (options =>
    options.UseSqlServer (Configuration.GetConnectionString ("DefaultConnection")));
```

So, how is the factory approach shown different in allowing 'per `DbContext`' connection strings? Finally, if this means 'per `DbContext` _instance_', can you elaborate on a use case for this?

TIA,
Philip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EFCore)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0#new-dbcontext-instances-1)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by guardrex** [comment]
Hello @TheRealDuckboy ... Stand-by ... @JeremyLikness will come on at some point and explain further. I'll then perhaps take his remarks and attempt to enhance the doc (or he'll submit a PR to do it).

**Comment by JeremyLikness** [comment]
@guardrex and @TheRealDuckboy thanks for calling this out. I can see why it looks confusing. What the note is trying to convey is that you can have a factory per _`DbContext` impementation`_ meaning you might have `ProductsDbContext` that would need a different connection string than `ApplicationDbContext`. Does that make sense? 

Let me know if you have more questions or need any other details to update the docs appropriately.

**Comment by guardrex** [comment]
Thanks @JeremyLikness.

@TheRealDuckboy ... I can improve the coverage, but we're all 🏃😅 for the 6.0 release at the moment. Given that this isn't a significant doc bug, I'll have to schedule it for after the 6.0 release. Don't worry tho about this getting lost ... it won't. It's on my tracking project now, so it will be addressed as soon as I can get to it. If you want to submit a PR to fix it, you're welcome to do so.

**Comment by TheRealDuckboy** [comment]
Thanks, both, for the quick responses even whilst scrambling for the 6.0 release.

@JeremyLikness thanks for the clarification but again I'm failing to see how that differs from just registering two separate `DbContext` implementations.

For example in several Blazor apps we have an app data context and a separate auth context each pointing at different databases and don't need to use the factory pattern as they each have their own connection string anyway.

(That's separate from the unit-of-work design for Blazor server side apps which use the factory pattern for that reason.)

Anyway, thanks again, and leaving this open as requested.

**Comment by JeremyLikness** [comment]
@TheRealDuckboy the difference is mainly important for Blazor server apps. The factory always provides new instances, whilst the direct registration depends on lifetime configuration and doesn't play well with the "scoped" nature of server. A separate article explains this in more detail: [ASP.NET Core Blazor Server with Entity Framework Core](https://docs.microsoft.com/aspnet/core/blazor/blazor-server-ef-core).

**Comment by TheRealDuckboy** [comment]
@JeremyLikness Yup, I completely grok the Blazor Server use case, and it's well-documented, which is why the article mentioning using the factory approach to provide separate connection strings specifically for an Identity scenario got me a-wondering how that's any different from just registering two separate contexts.

It's not really that big a deal so I'll shut up now and let you get back to the important .NET 6 work! :-)

**Comment by guardrex** [comment]
@JeremyLikness ... We're not spelling it out in detail in ...

* https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core
* https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/#using-a-dbcontext-factory-eg-for-blazor

... like you do for the multi-tenancy scenario in ...

**Multi-tenancy with EF Core in Blazor Server Apps**
https://blog.jeremylikness.com/blog/multitenancy-with-ef-core-in-blazor-server-apps/

I don't see that in official docs ... not to that degree of clarity, especially in regard to a code example (`BlazorEFCoreMultitenant` sample app) or specific use case.

Here are some options ...

1. Remove the code example from the Blazor-EF Core doc (this doc set) and add instead to the end of that paragraph ...

   > For more information, see \[Multi-tenancy with EF Core in Blazor Server Apps](https://blog.jeremylikness.com/blog/multitenancy-with-ef-core-in-blazor-server-apps/).

2. Add a cross-link to https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core, and the EF Core doc gets a more info on this subject later. I could go ahead and do that now for this doc and open an issue for EF Core docs to enhance the coverage over there on this subject.

3. Enhance the coverage in this doc on this subject, probably by creating a dedicated section. Pump up the coverage to something more like the blog post coverage.

If you feel that the blog post coverage is complete and stable, I believe that we've met DR's call for "authoritative" blog cross-linking because **_you wrote it_**, not a community member. I feel that we can just cross-link (Option 1 :point_up:) if you think the coverage is good and stable in that blog post.

Also, didn't `AddDbContextFactory` show up at 5.0? If that's right, then I do need to kill that for the 3.1 content here ... a 😈 **_rotten sneaky devil_** 😈 got into the doc! 😄

... and a final tiny *NIT* note on the use of the abbreviation of "e.g." (e.g., :smile: in that EF Core doc section title) ... it apparently doesn't localize well, so [they asked us not to use it](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/e/eg).

**Comment by JeremyLikness** [comment]
@guardrex I'm fine with (1), however let me loop in @ajcvickers to ask if we want to repurpose the blog post into an EF Core docs page? I think that makes the most sense, then this could link over.

**Comment by guardrex** [comment]
Thanks @JeremyLikness ... Yes, that sounds great. It would yield the options of ...

* Go ahead for now and cross-link the blog post with a follow-up issue on HOLD in the Blazor project to relink from the blog post to the new doc in EF Core docs. This approach would surface the content to devs in the meantime.
* Or ... just wait. We can leave this sit here and then link directly to a new EF Core doc later.

I don't have a strong preference, but I do like to close out issues ASAP, and I think we meet the bar for DR's concern about blog post content ... i.e., 'it must come from an authoritative source' and 'it must be up-to-date.' I think we check those boxes with your post, so cross-linking to the blog post seems fine. *"It seems fine."* ... 😄 ... We can put that on my ⚰️ **_tombstone_** ⚰️ if DR orders my immediate execution 🔪💀😨 after cross-linking! 😆 lol

**Comment by ajcvickers** [comment]
@JeremyLikness I'm in favor of making that a docs page.
