### ISSUE TITLE
The name 'Host' does not exist in the current context - .NET 5.0

### ISSUE THREAD

**Issue by angieto** [dotnet/AspNetCore.Docs#23017]
Run:
- dotnet --version // 5.0.303
- dotnet --info
![image](https://user-images.githubusercontent.com/42507452/129282724-4a115f7a-143f-4618-b3e4-7ec3232edd9f.png)

I also went over related threads on this issues but those mainly caused by an older version of net core. Any idea why this happens?

Thanks

**Comment by wadepickett** [comment]
@angieto, is this related to an ASP.NET Core tutorial or document of some kind? If so, please provide a link to the doc.  The issue you created here is for an ASP.NET Core documentation repo.  

Occasionally the 'Host" does not exist issue turns up when folks have an older project designed to run on early SDK versions such as 2.1 but are trying to make that work with 3.1 or higher tutorials.  If you do happen to be following a tutorial, verify which version you are following by looking at the version selector on the left.  Normally a 5.0 version would be selected rather than and older topic, unless you really specifically need to use an earlier one.

Here is a related stackoverflow thread to consider without knowing much about your situation:
[The name Host does not exist](https://stackoverflow.com/questions/59364482/the-name-host-does-not-exist-in-the-current-context)

**Comment by wadepickett** [comment]
Closing this issue.  Feel free to reopen if this is related to a specific document issue, in which case let us know which doc. See my previous note and thread link.
