### ISSUE TITLE
Default Hosting Model is wrong - related to 22766

### ISSUE THREAD

**Issue by EsraShrouf** [dotnet/AspNetCore.Docs#23025]
Please refer to the fixed issue here: https://github.com/dotnet/AspNetCore.Docs/issues/22766

the default hosting model in the page https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-5.0&viewFallbackFrom=aspnetcore-3.1 I am writing about now, needs to have the default hosting model changed from in process to out of process. 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52491d2-5493-260a-41cf-f6f8732738c1
* Version Independent ID: bc7f1ef8-0ccc-1233-a4eb-d9dc26ac9529
* Content: [In-process hosting with IIS and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-5.0&viewFallbackFrom=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/iis/in-process-hosting.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/in-process-hosting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Rick-Anderson ... I made the change in the right spot for when the `hostingModel` property isn't present. I don't have any information about the default hosting model changing to out-of-process. Note that 3.1 isn't supported in docs ... only >=5.0. @jkotalik will need to remark further on this.

**Comment by EsraShrouf** [comment]
@Rick-Anderson I used 3.1
but @guardrex reproduced the same using both 3.1 and 5.0 (if I am not mistaken) as mentioned in the fixed github issue I pointed to in my main post above.
If this is the case, I don't think this needs further investigation, rather to only fix the other doc I mentioned

**Comment by guardrex** [comment]
I don't think it's the *right fix* tho ... The default as far as the PU is concerned is in-process because the template-generated apps configure the module to run that way. It's true that the config will "default" without the attribute to out-of-process, but they (AFAICT) say something "defaults" a certain way based on what a project template produces. This is why I chose that language in the other topic very carefully to say 'when the attribute isn't present.' I don't think are any further changes required. Again tho, @jkotalik should probably confirm my assumptions. It's been a few years since I worked on docs for these bits. I'm a bit rusty on these aspects.
