### ISSUE TITLE
Blazor Server Sizing Requirements

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#23055]
I was reading the section 
https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-3.1#deployment-server-2

It does mention to identify the actual memory usage at development time but does not guide on how to actually do it ?
Can we include steps on finding out actual Memory usage for Blazor Server App?
I need to estimate the Cost of APP server and SignalR Service Required, the article helps in estimating SignalR service but not on how to estimate the state memory required for App

Also, since one has to first develop the Blazor Server App to find out actual memory requirement is very late step to switch to say go for Blazor Web assembly, there should be some guidance on rough estimation like the one made available for SignalR Service(ie. 273K per connection)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b20b470-161a-8723-b66d-c0c1804874f0
* Version Independent ID: 2712f7a2-90e7-0012-f7d9-f3a7e7e345d7
* Content: [Host and deploy ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @nssidhu ... I don't think we'll be able to cover all of the scenarios, but I think we should ask the product unit if they want to try and address this. ASP.NET Core generally is hosted by so many development and server hosting platforms ... and **_versions_** of those platforms ... that we probably won't be able to offer stable, full-landscape guidance on this. We might be able to say *something* for Kestrel and IIS tho.

IIRC 🤔 for IIS, you can get the instantaneous memory demands for app pools (thus for an app) with the **Worker Processes** panel at the server level in the **IIS Manager** console. You can also set up counters (i.e., logging) via **Performance Monitor**. I wouldn't want to carry a lot of guidance on these subjects here in the Blazor guidance, but I think a few valuable cross-links to IIS docs that pertain to monitoring app pool memory (and other perf) demands might make sense.

Generally speaking ... **_Yes!_** *... This is the correct approach ...*

> one has to first develop the Blazor Server App to find out actual memory requirement is very late step to switch to say go for Blazor Web assembly

... that's a *virtual necessity* because the range of memory demands is highly app dependent. Stating general values is *very challenging* ... well ... it's really just about *impossible*. The product unit did the best that they could in the *Deployment server* section of this topic, where it states the minimal *Hello, world!* app (i.e., project template-based app) general demands.

Unfortunately, the product unit can't be asked about this at this time due to *very high priority work for the upcoming 6.0 release* 🏃😅. I'll reach out to them after 6.0 comes out later this year for feedback on this issue (... and upgrade the priority of the issue when the time comes). Leave this issue open ... it won't get lost or go into an *issue black hole* ⚫😄. I carefully track Blazor docs issues on a GitHub project here to keep us moving coverage forward.

In the meantime if you don't find good guidance on memory monitoring for your server of choice (e.g., IIS), ask the community. These product support channels are full of devs doing this kind of monitoring all the time. They'll have the best tried-and-true methods for various server platforms and are often online 24/7/365 to provide quick feedback, especially the chat rooms ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

**Comment by guardrex** [comment]
btw @nssidhu ... Your ask at the end is covered by ...

> budgeting at least 1.3 GB of server memory to the app (or ~273 KB per user).

... that is the baseline for **_server memory for the whole app_**.

Truly tho, you'll have to test. I don't recommend trusting that for developed production apps.

**Comment by nssidhu** [comment]
That just covers SingnalR side of it. 
Blazor Server also has to maintain **State for the rendered page on the server for each client**.  
That is what i am trying to find.
_The article does mention that this can be found  but stops short of on how to to find that._
Checking on IIS or Kestrel would provide overall memory usage, i just want to find out how much memory is being used for managing state for each client.

**Comment by guardrex** [comment]
Emphasis added ...

> The size of a circuit depends on the app's code **_and the state maintenance requirements associated with each component_**. 

I think we agree not to trust the baseline *Hello, World!* scenario tho. They were asked about that several times so that devs would have some feel for the bare minimum requirements.

From the *Threat Management* doc pertaining to *Memory* demands (emphasis added) ...

> During development, a profiler can be used or a trace captured to assess memory demands of clients. A profiler or trace won't capture the memory allocated to a specific client. **_To capture the memory use of a specific client during development, capture a dump and examine the memory demand of all the objects rooted at a user's circuit._**

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-5.0#memory-1

That's what Steve wrote. He didn't remark on profiling in a more traditional way via a load test of some number of automated users and looking at the memory demands of the app. I'll ask him later about it when I reach this issue.

For the time being, I recommend that you converse with gurus on community chat. I'm sure you'll be able to find some devs who work with very large apps and thus deal with memory demands.

**Comment by bradygaster** [comment]
Agreed with @guardrex that this is something the community would be open to discussing. We've also published benchmarks and performance improvements along the development of .NET Core so if there are telemetry you're missing, we'd be willing to address that but I think that'd be more a topic for the engineering repo's issue tracker.
