### ISSUE TITLE
Add small bit that explains how to access certificates on a Linux App Service

### ISSUE THREAD

**Issue by niem94** [dotnet/AspNetCore.Docs#23180]
On Linux App Services, you cant access the certificate from My\CurrentUser. A solution to this is to point IdentityServer directly to the file path certificates are saved to on the Linux App Service:

```json
{
    "IdentityServer": {
        "Key": {
            "Type": "File",
            "FilePath": "/var/ssl/private/{thumbprintGoesHere}.p12",
            "Password": ""
          }
    }
}
```

Can you add a disclaimer of sorts that highlights this solution? I've had so much trouble finding out that it was this simple to fix, and from google searches, I can see I am not alone in having a hard time making this work with Linux App Services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @niem94 ... I have a concern about cert security 😨 in that scenario. Devs get into trouble real fast with permissions/private keys/etc. without additional explanation that we don't generally want to carry. *There be 🐉 **dragons** 🐉 in these cert management scenarios!* Our preferred approach is to only support (in docs anyway) use of Azure Key Vault/Managed Identity scenarios ... as much as we can anyway ... as the topic shows and explains. AKV should work well 🤞 with Linux App Service ... and Windows, of course.

cc: @blowdart ... Do you concur?

**Comment by guardrex** [comment]
btw tho --- @niem94 ... before I close this issue out and after we hear back from 🎯 ... I'll take a look and see if a cross-link to an authoritative source is possible. I can't promise anything tho on that. Whatever we would link to would need to cover all of the security concerns for cert management on Linux platforms in addition to showing the approach that you suggest here.

**Comment by guardrex** [comment]
@blowdart ... Do you think a cross-link (for >=6.0 coverage) to ...

https://docs.duendesoftware.com/identityserver/v5/fundamentals/keys/

... would be ok?

**Comment by guardrex** [comment]
*Nevermind* on my last remark: That Duende resource doesn't cross-link or maintain anything on cert security or address Linux App Service.

**Comment by niem94** [comment]
So it might not be clear from my description. But the recommended approach of setting the appsettings.json config to:

```json
"IdentityServer": {

  ...

  "Key": {
    "Type": "Store",
    "StoreName": "My",
    "StoreLocation": "CurrentUser",
    "Name": "CN=IdentityServerSigning"
  }
},
```

does not work on Linux App Services. Linux App Services have cant locate certificates with these settings. My suggestion above still relies on having both the HTTP Certificate and the SigningKey certificate in the Azure Key Vault. They are both copied to '/var/ssl/private/' when the app setting key is WEBSITE_LOAD_CERTIFICATES has been set. So even though my suggestion implies that a local certificate is used, this is not really the case. The only thing I reckon should be added to docs is to suggest this approach in the 12th step in the 'Host in Azure App Service with a custom domain and certificate' section of the article.

Right now readers using a Linux App Service will encounter this problem, and this is why I think it would be nice to point them in the right direction, that does not require a huge amount of work.

**Comment by guardrex** [comment]
Ah, I see what you mean now, @niem94. Thanks for explaining it out. Let me get back to you Wednesday morning. I'd like to research it a bit further in Azure KV docs.

@blowdart might see this in the meantime. He's our *Security Hero* 🦸‍♂️, and he may remark on your proposed config ... either signing off on it here or letting us know the best practice for this scenario. 

@blowdart TL;DR ... @niem94 is suggesting that we place app cert settings config for IdS's token signing key of ...

```json
"IdentityServer": {
  "Key": {
    "Type": "File",
    "FilePath": "/var/ssl/private/{thumbprintGoesHere}.p12",
    "Password": ""
  }
}
```

... SxS with our current, working Windows App Service config of ...

```json
"IdentityServer": {
  "Key": {
    "Type": "Store",
    "StoreName": "My",
    "StoreLocation": "CurrentUser",
    "Name": "CN=IdentityServerSigning"
  }
}
```

**Comment by blowdart** [comment]
Do we have anyone in app service we can ask about it? It seems fine, if that's where app service places then.

**Comment by guardrex** [comment]
Thx @blowdart ... I'll research further in the morning, as it's late here 🛌💤. I'll be shocked if Azure docs for KV don't cover this.

If I can't confirm it in the morning, then I'll ask Rick for a referral. He has a list ... *somewhere* ... of our contacts for each MS technology.

**Comment by niem94** [comment]
@guardrex happy that my explanation made the issue more clear. Looking forward to a resolution on Wednesday :-)

**Comment by guardrex** [comment]
@niem94 ... I'm going to start by asking at Duende docs. I'd like to see if perhaps Dominick and/or Brock would remark on this given the switch over to Duende IdS for many scenarios at 6.0 GA. There's a chance that Duende docs would host coverage and then ASP.NET Core docs could link to that. After all, this is a rather general scenario for the token signing cert going far wider in scope than just for Blazor framework scenarios.

Next, I might ping Jeremy Barton. I might also reach out to one of the Azure docs 🐈 who writes AKV cert topics.

**Comment by guardrex** [comment]
Cool ... so Brock said that Key Vault Client with Linux App Service and a cert-based signing cert is a viable approach ... **_BUT_** he also referred me to automatic signing credentials ...

https://docs.duendesoftware.com/identityserver/v5/fundamentals/keys/#automatic-key-management

I need to figure out the best way to handle this section's coverage ...

* I don't want to document single scenarios in detail when there are several valid approaches. I'd rather list a few options with cross-links to authoritative content (i.e., the external framework/API docs for whatever external tech we're using/showing).
* I don't want to duplicate general coverage in Blazor docs, especially when external docs already cover it. Again, cross-links are best. This includes for Azure scenarios, where Azure docs cover managed certs in AKV, Key Vault Client, etc.
* I don't want to end up with **_constantly-going-stale_** docs 🤦‍♂️ that require frequent updates ... too much 🏃 to keep up. We're always crazy busy enough around here as it is, and the doc set is an ever-expanding 🌌 *galaxy* 🌌.

Having said that tho, I found the same thing that you did. *Coverage is hard to come by here!* At least one problem is that one community/team/company/*Borg Collective* :smile: doesn't want to document much of anyone else's bits. For example, I want to link to an Azure doc from the Blazor docs for some Azure-specific guidance. I don't want to have to write a lot of 'how to do such-and-such in Azure' into the Blazor docs and then be required to maintain that ... and Azure churn breaks me 💥 regularly, too.

I'm going to come up with an approach to resolve this issue. Leave this open, and I'll get back to it asap. We're working on 6.0 coverage, and resolving this issue might be delayed a bit. This issue is attached to the doc, so your suggestion is something that I can reference if anyone asks in the meantime. This won't get lost. It's tracked well by my [Blazor Project](https://github.com/dotnet/AspNetCore.Docs/projects/35).

btw @niem94 ... Did you adopt the certificate-AKV signing token approach **_merely because the doc called for it_**? ... or did you have a special reason to avoid an automatic key management strategy?

**Comment by niem94** [comment]
@guardrex Okay so that is perfectly reasonable, and I'm happy you will look into it when time allows :-)

To answer your question, a year ago I had never set up AKV signing before, and in trying so I ended up just adding a certificate to my repo to get on with other tasks as I could not figure out how to set it up with AKV due to the same issue resolved in this thread. I knew adding my keys to the repo was insecure, but I also knew I would revisit it when I had more time to find a solution I was content with. 
Continue on to the present time the certificate was about to expire, so I wanted to revisit the issue and find a proper solution that allowed for automatic key management in Azure (i do just now realize this is probably not the case though as the thumbprints might change when AKV rerolls the certificate). Therefore I fell upon the AKV signing method and found that was what I wanted to do. I then found these docs detailing exactly that and found my workaround to make it work with the Linux App Service. 
So no I did not follow the guide, but I found that the docs supported the solution I was looking to implement.

More specifically I was not interested in handling this in the code, as all the examples I was able to find seemed overly complex compared to the approach provided for the Windows App Service in the docs. I felt that approach was really straightforward and to my liking.

However looking at the first link (Duende) this seems like a better solution, and I would not be surprised to have tried this if I had stumbled upon that in my searches. I am unsure how to make this work with the App Service though. Would it require setting the `IdentityServer__Key__Type` to something specific or nothing at all? And how would one make it work with App Services? The link you sent doesn't really cover this, so I would be very interested in knowing this.
Also if using the default Automatic key management is possible with App Services I would definitely change my implementation to utilize that instead of the AKV for the Signing Key, as such an approach would lessen the hosting-related task to host a .NET Web App on Azure, which is something that is already a bit alienated to the workflow of a young dev like me.
