### ISSUE TITLE
Connection Change state Events not firing

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#23190]
I have created sample app 
https://github.com/nssidhu/SignalRTest

What am i missing here or not configured correctly ?

None of the events are firing even though i see lots reconnects on the browser. 
I am not doing any interaction with the App, it just sitting idle and those events are happening on their own.

![image](https://user-images.githubusercontent.com/3267605/131761191-45dcac9c-05fa-4db5-b149-b1f96820bee5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
@BrennanConroy ... Should this be referred to public support forums?

**Comment by mbeiranvand** [comment]
Change#23190

**Comment by guardrex** [comment]
@nssidhu ... With the upcoming release of 6.0, engineers and doc authors aren't able to provide a great deal of general product support. Your best bet is to consult with community devs ... ask a few SignalR gurus to look at your app ... to see if this is due to a framework bug (then open a found bug for engineering) or a doc problem (comment back on this issue or open a new issue from the topic stating explicitly what's wrong with the doc).

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)
