### ISSUE TITLE
Linked GitHub Issue on Azure Platform Support has been updated and closed.

### ISSUE THREAD

**Issue by jacobestell** [dotnet/AspNetCore.Docs#23259]
Link to gRPC github issue seems to be closed. The moving target of supported platforms seems due for an update to include new windows server versions to clear some confusion in the linked aspnetcore issue.

Maybe link to this article to funnel people here instead of a dead ticket?

https://github.com/dotnet/AspNetCore/issues/9020

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d3f0ff-f65f-97d2-940f-4509b0d425bd
* Version Independent ID: ea62de0b-d7e5-e543-b892-a587d6e9dc84
* Content: [gRPC on .NET supported platforms](https://docs.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
@jacobestell, I may be misunderstanding which issue and which topic you are referring to, or it may already be fixed.

Currently, the topic this issue is filed on ( [gRPC on .NET supported platforms](https://docs.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-5.0) ) links to this currently open issue https://github.com/dotnet/aspnetcore/issues/9020.  

When you say "..link **this** article to funnel people here instead of a dead ticket", which article are you referring to that should link to what topic?  Sorry to ask, it isn't clear to me.

**Comment by wadepickett** [comment]
Closing this issue as already fixed, but will reopen if it turns out we are referring to another article here than I understand.
