### ISSUE TITLE
Blazor HostedService

### ISSUE THREAD

**Issue by ogiepogi** [dotnet/AspNetCore.Docs#23274]
I've encountered an issue regarding the hosted service being used in our Blazor Server App.

Before we ported our .net core 3.1 and .net 5.0 web apps to Blazor, the hosted service is working fine, it runs on the background even if there's no more users connected for minutes or even hours. Unfortunately with the Blazor server app, when we ported the exact same hosted services, once there's no more connected users for few minutes, the hosted service will also stop working from the background, and will only resume once a user has accessed the web app. Is the setup/configuration different if you're using blazor?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ogiepogi ... First, check this engineering issue to see if this mirrors your scenario ...

https://github.com/dotnet/aspnetcore/issues/7213

If that's what you're facing, you can chat there with the product unit about it. There are one or two asks for Blazor WASM, but I don't see any other reports there related to Blazor Server. Otherwise, open a new issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

... and put up and cross-link to a minimal repro Blazor Server app with a hosted service so that they can see how you have it set up. Sometimes, a feature works but has to be wired up a particular way. Even if something is broken, they can sometimes suggest a workaround to tide you over to a fix.

If you open a new issue, either ...

* Add a `cc: @guardrex` to your opening comment so that I can follow the discussion.
* Come back to this issue after you chat with them and leave a comment here on how it turned out.

If we need coverage, I'll re-open this issue and work it forward from here.
