### ISSUE TITLE
Cannot Understand how to Download Example Files

### ISSUE THREAD

**Issue by Johnvan** [dotnet/AspNetCore.Docs#23363]
# Issue description

**I take it that I type here, this GIT stuff is so hard to understand!**

My issue is when I Click Download from the **Tutorial for ASP.NET Core MVC** I am directed to the Git page which doesn't have any way of downloading anything.

Please advise me on how to do the downloading of the current Tutorial that I am doing.

# Software versions
* [ ] .NET Core
* [ ] .NET 5.0 or later
* [ ] .NET Framework
* [ ] .NET Standard

**Comment by guardrex** [comment]
Hello @Johnvan ... Guidance for downloading samples is at ...

https://docs.microsoft.com/aspnet/core/introduction-to-aspnet-core#how-to-download-a-sample

**Comment by Johnvan** [comment]
You need to explain what is happening, the description is also confusing and I dont know what it is supposed to do. I know you are just saying that I am an idiot but if you want to succeed in this computer world you have to make these things much more user friendly with descent explanations. I have been to the explanation page before, but you seem to think I am just being stupid. Wake up.

**Comment by guardrex** [comment]
From the repository's home page at https://github.com/dotnet/AspNetCore.Docs, select the **Code** button and then download the ZIP archive of the whole repository ...

<img width="409" alt="Capture" src="https://user-images.githubusercontent.com/1622880/134267521-f2b73cb7-dd9b-496b-af02-ea3c75e70ee6.PNG">

Extract the ZIP. It's a full copy of the entire repo. Then, you can navigate within the folders of the repo to locate any sample app that's referenced by any topic here.

Most of the sample apps have a link at the top of the topic that show their code. It usually says, "View or download sample code".  When you follow that link on the repo here (online), you'll see the path to the sample app for that topic. Then, just navigate to that exact path in the local repo that you downloaded and extracted from the ZIP archive. Then, you can build that sample locally from there with VS ... or run it from the command line with the .NET CLI.

There was going to be an effort to make sample apps easier to obtain than this process by placing the sample apps at https://docs.microsoft.com/samples/browse/. Unfortunately, there are only a few doc authors working here, and we've been very busy for the last few years with high priority coverage of the ASP.NET Core framework. It also turns out that obtaining the full sample apps isn't very popular with readers. Many devs use the code from the topics by copying that code into their own apps without actually obtaining and running the full samples. For now, the ZIP archive is the best that we can provide.

**Comment by guardrex** [comment]
Oh ... and I did just recall that you don't even have to do that step of using the **Code** button.

There's a direct download link of the whole repo right there :point_right: https://docs.microsoft.com/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-5.0#how-to-download-a-sample ... click that ... you get the whole repo.

**Comment by Johnvan** [comment]
I can see that you have a big job looking after ASP.NET Core, but please don't use abbreviations in descriptions. 
Now, I understand that the whole Example file system is downloaded and I would then work from there, but the description page dose not say anything like that, all I'm saying is adjust the description page to describe that the file contains all the example files which are downloaded, un-zipped into a directory set aside for them and then look for the file you want, load it into Visual Studio and start working. The link says nothing. 
Thank anyway for your response to my query, I think I have been doing Xamarin programming too long and missed the goings on with ASP.
