### ISSUE TITLE
Documentation is not clear at all.

### ISSUE THREAD

**Issue by Duelbat** [dotnet/AspNetCore.Docs#23376]
This is not a clear tutorial on this subject at all ! Too many assumptions are made about the user here.
**Detailed steps are needed.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985b834f-534a-aba6-80a0-d8845adbfc25
* Version Independent ID: d2b5a556-82a4-e939-be68-2357a3d4408f
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Duelbat ... This is a reference topic, not a tutorial. However, we do show a Google configuration example. The topics that lean more in the direction of a tutorial with step-by-step instructions leading to fully working/deployed apps are here for AAD, AAD B2C, and Identity Server. Those are the only scenarios that management has decided to cover here at this time. Azure docs maintain a couple of more Blazor-specific topics for Azure AAD ...

* https://docs.microsoft.com/azure/active-directory/develop/tutorial-blazor-server
* https://docs.microsoft.com/azure/active-directory/develop/tutorial-blazor-webassembly

Search the Net ... several providers have been blogged by the community. Also, see if [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor) lists a tutorial for your provider of choice. If you run into trouble and need product support, we recommend the usual public support channels ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

Most providers should only require minimal configuration, as you can see by the Google example here. You should be able to use non-Blazor examples and reference docs from the Net for any given OIDC provider to get a Blazor app up and running with OIDC auth.

I'm going to close this issue, but if you want to leave a comment back here to me as to which OIDC provider you were seeking a tutorial for, I will let management know about your request. They might decide to add a configuration example for the provider that you're interested in using, like we have today for Google OIDC.

I'll also mention based on your remark ...

> This is not a clear tutorial on this subject at all ! Too many assumptions are made about the user here.

... that this topic isn't even really meant to cover all of the general aspects of OIDC. I might be reading a bit too far into your "subject" and "assumptions" language there, so forgive me if I've misinterpreted your request. I'll mention this just in case it is part of your ask: This topic is only designed to cover the bare bones basics of how to configure the Blazor app for OIDC. Of course, Microsoft carries docs pertaining to Microsoft's own providers for Azure AAD, MS Identity Platform docs and *some* general content that certainly applies to any OIDC provider. This isn't meant to be a complete list, but topics over there like the following exist that should be helpful ...

* https://docs.microsoft.com/azure/active-directory/develop/active-directory-v2-protocols
* https://docs.microsoft.com/azure/active-directory/develop/v2-protocols-oidc

Microsoft doesn't carry too much in the way of general OIDC docs. Indeed, Microsoft doesn't generally recommend specific non-Microsoft docs (e.g., blogs, docs for non-Microsoft providers). They cross-link directly to the spec ...

https://openid.net/specs/openid-connect-core-1_0.html

If part of your motivation for this issue was general OIDC content outside of what Microsoft maintains, we recommend a general web search for reference topics, tutorials, and blog posts dealing with OIDC. Those chat rooms that I mentioned :point_up: can come in handy when you want to chat directly with other devs.
