### ISSUE TITLE
Add guideline for combining ChildContent and template (not allowed)

### ISSUE THREAD

**Issue by leotsarev** [dotnet/AspNetCore.Docs#23467]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 698a8824-7a38-70d6-c041-0dca4c040217
* Version Independent ID: ae663e33-6a08-0b24-aa19-3fc3c9edccfc
* Content: [ASP.NET Core Blazor templated components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/templated-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/templated-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @leotsarev ...

> not allowed

We don't usually cover scenarios that the framework can't handle, nor can I understand from your report what the problem is. Also, we can't cover every conceivable combination of features.

If you're having trouble with a `RenderFragment` and templates that **_looks like it should work_**, you can first ask the community ... for example at ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

... and then if you determine that there might be a framework bug or perhaps you would like to make a feature request, then ask the product unit at ...

https://github.com/dotnet/aspnetcore/issues

For now, I'm going to call this a support request that we won't address in the docs at the moment. You can come back here and note more information and/or with an engineering issue (put a `cc: @guardrex` on it please) where a bug is found or a feature request is approved for a future release. I'll re-open this if it becomes actionable for the docs.
