### ISSUE TITLE
Is ViewBag available in Razor Pages?

### ISSUE THREAD

**Issue by hillin** [dotnet/AspNetCore.Docs#23505]
This page keeps saying `ViewBag isn't available in the Razor Pages`, which does not seem to be true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e47828-6da8-2323-053f-dcbf7475b1b6
* Version Independent ID: 62d4c2be-4233-64e1-2a3d-8a5e98d9d941
* Content: [Views in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/views/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hillin ... IIRC, this just means that a `ViewBag` property doesn't exist for the `PageModel` class. However, you can use `ViewBag` to reference `ViewData` content in a RP. From the topic ...

> The ViewBag property is a wrapper around ViewData that provides dynamic properties for the underlying ViewData collection. 

It's been discussed here and there in PU issues. For example ...

https://github.com/aspnet/Mvc/issues/6754

... and there are other issues floating around the PU issues. Try some searches, and you should be able to locate other discussions on it.

I'll leave open for a sec because @Rick-Anderson may want to make a change or provide other feedback.
