### ISSUE TITLE
Too little information about regions?

### ISSUE THREAD

**Issue by fterrani** [dotnet/AspNetCore.Docs#23521]
Hi,

Even if I'm determined to convince my colleagues (and myself) to prefer Razor files over manual `RenderTreeBuilder` logic, such cases can sometimes happen. I did my best to understand what this page is describing, however I think some additional questions about regions (and sequence numbers) could be answered in it, such as the following:

- Are there implicitly-defined regions? For example:
    - Does a Razor file implicitly delimit a new region?
    - Much more importantly, does a `RenderFragment` member (method or property) called in a Razor file implicitly delimits a new region for its code? (if not, how can we choose sequence numbers that won't collide/mismatch with the ones generated by the compiler? do we have to open a new region?)
- If a method somewhere else than in a component returns a `RenderFragment`, since the `RenderTreeBuilder` will probably come from a component whose sequence numbers are unknown/unpredictable, is it recommended/required to delimit a new region ourselves with `OpenRegion()`/`CloseRegion()` in the body of this method's returned `RenderFragment`?
- Documentation says long pieces of code using `RenderTreeBuilder` should be split into smaller regions. Well, how long is long? :) And what is the recommended size of such regions, approximately?
- Finally, weirdest but not least, since the only constraint for sequence numbers in a given region is to increase in value, could we start with a negative number?

Thanks in advance for your feedback!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a84b780b-ca41-c255-9fbf-12e9af990c8a
* Version Independent ID: 8d522def-5710-f0ec-97aa-9ac636785f12
* Content: [ASP.NET Core Blazor advanced scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/advanced-scenarios?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/advanced-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/advanced-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Ok ... I'm **_BACK_**. Sorry it took so long to reach this, @fterrani. I've pinged Steve offline to look at this.

**Comment by SteveSandersonMS** [comment]
@fterrani Manual rendertree logic isn't something we encourage developers to write. Razor syntax should suffice for almost any reasonable case, and if you have something that doesn't, it would be great to describe that scenario since we might either be able to suggest how to use Razor, or consider adding further Razor syntax to enable it.

Your various questions about the internals of diffing/regions/etc are part of why we recommend the use of Razor. In short, the inclusion of a child component is equivalent to inclusion of a region around it. When not using a child component, any code A that calls any other code B should put a region around it, since A can't trust that B has any particular sequence numbers. The length of code is unlimited (and I don't know why the docs say otherwise). The sequence numbers could be negative but the more weird stuff you do, the more chances there are of being broken in the future (for example, int.MinValue already has a special meaning, and we might add other numbers with speciam meanings in the future). If possible, just don't do any of this, and use Razor.

@guardrex In terms of docs, I don't recommend adding anything.
