### ISSUE TITLE
Clarify Sticky Session guidance

### ISSUE THREAD

**Issue by runtimeware** [dotnet/AspNetCore.Docs#23590]
Would be great to be very specific on this page about ARR Affinity (sticky session) guidance for Blazor Server applications leveraging Azure SignalR.

Although this document makes it very specific, the ASP.Net Core documentation states otherwise and is generally confusing:
https://docs.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-5.0

Not sure if this comment should be directed at the product group supporting *this* page, but want to make sure the docs across both ASP.Net Core + this specific doc are clear/consistent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b20b470-161a-8723-b66d-c0c1804874f0
* Version Independent ID: 2712f7a2-90e7-0012-f7d9-f3a7e7e345d7
* Content: [Host and deploy ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-5.0#configuration-1)
* Content Source: [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @runtimeware ... In that case ... i.e., "the ASP.Net Core documentation states otherwise and is generally confusing" ... open the issue from the bottom of that page using it's **This page** feedback button+form. These two topics map to **_different maintainers_** for most work items, and the metadata attached to that issue will ping that author to take a look.

If this topic (*Host and deploy ASP.NET Core Blazor Server*) has one or more specific problems, then let me know what those problems are. I'll re-open this issue to work on it. *Please be specific.* I'm 🏃🏃🏃🏃⛰️⛏️😅 on many issues as far as the 👁️ can see ... well into 2022 at this point. It's easier/quicker for me to work out doc updates when the dev can report the exact problem.

They'll probably say the same thing for the other topic. You'll probably need to tell them how that topic is confusing in your opening remarks.
