### ISSUE TITLE
implementing IHandleEvent stops click action when stopPropagation=true

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#23641]
[EDIT by guardrex to code-fence the code. @omuleanu, use triple-backticks above and below code blocks.]

doing this:

```csharp
Task IHandleEvent.HandleEventAsync(
        EventCallbackWorkItem callback, object arg) => callback.InvokeAsync(arg);
```

in a component will prevent the onclick method `myAction1` from working here:

```razor
@onclick="() => myAction1(itm.Key)" @onclick:stopPropagation="true"
```

and it will execute later, after the state changes

`Pages/HandleSelect1.razor`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a29eb861-e8eb-e54c-b441-e1f14d7e6a7f
* Version Independent ID: 40361d5d-c806-9c9b-c7f7-ad317a06bb4f
* Content: [ASP.NET Core Blazor performance best practices](https://docs.microsoft.com/en-us/aspnet/core/blazor/performance?view=aspnetcore-6.0&pivots=server)
* Content Source: [aspnetcore/blazor/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/performance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @pranavkm
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @omuleanu ... I'm looking over issues to triage work just before we break for the 🎁 *holidays* ⛄. The best bet here really is not to wait all the way until we triage these doc issues but instead to ask the product unit directly. Could you open your ask about this on their repo at ...

https://github.com/dotnet/aspnetcore/issues

When you open an issue there, show them a complete component that reproduces the behavior, and surround your component code with triple-backticks above and below to make it a code block. At the bottom of your opening comment, add the following:

```
* https://github.com/dotnet/AspNetCore.Docs/issues/23641
* cc: @guardrex 
```

That way, I can follow the discussion and then re-open this issue if there's something for us to document. If it turns out to be a framework bug 🐛, they'll keep your issue to track work to fix the framework. We probably won't document anything if they're going to fix a bug.
