### ISSUE TITLE
Document how to setup callbacks for native dependencies in Blazor WebAssembly

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#23661]
[EDIT by guardrex to add the metadata]

See https://github.com/dotnet/runtime/issues/60824#issuecomment-953035187.

@lewing @radical @lambdageek 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#native-dependencies-support)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by GeorgeS2019** [comment]
@guardrex @danroth27 

Currently the section Blazor WebAssembly: [Use (native) libraries](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#use-libraries) which uses SkiaSharp as an example


The mentioned [SkiaSharp.Views.Blazor](https://www.nuget.org/packages/SkiaSharp.Views.Blazor) has the following dependencies
![image](https://user-images.githubusercontent.com/49812372/140244043-d77d8338-3720-47b1-91f4-9567058ad5e4.png)

one of the dependencies: [SkiaSharp.NativeAssets.WebAssembly](https://nuget.info/packages/SkiaSharp.NativeAssets.WebAssembly) packs a static library **libskiasharp.a**
![image](https://user-images.githubusercontent.com/49812372/140244219-131dbd41-7fba-4863-b55b-fb79a0737645.png)

## Questions1
**==>** for users who are interested to use **other** native libraries (e.g. `TorchSharp.NativeAssets.WebAssembly`) in Blazor WebAssembly, we  need <font size=5><strong>elaboration</strong></font>  on **how to create** such nuget and **what files to be included and how to organize them**.

## Question2

The TorchSharp native assets are huge. Is there **size limit** of currently implementation of Blazor WebAssembly for using native libraries?

**Comment by Alan-FGR** [comment]
Hey guys, I came across this problem in which having a C#9 function ptr in the `[DllImport]`-decorated definition won't work, so I've instead used just a normal pointer (thanks so much @lambdageek for pointing that out). However, I'm quite confused since all related threads are closed. Is that the proper way to do it or is that going to be fixed at some point? I wish that stuff was better documented and more discoverable as I spent a ton of time assuming I was doing things wrong, and then searching the internet to no avail :(
In any case, keep up the good work! I'm resurrecting an old game engine of mine and it's been a joy to rewrite bits in modern C# and also make it run on the web too :D... I'm also using source generation for a lot of stuff and it scratches all my itches for the lack of templates, and in a much better fashion than template metaprogramming I must say! :)
