### ISSUE TITLE
Blazor Server subapp guidance: Can't find the fallback endpoint

### ISSUE THREAD

**Issue by cmedianu** [dotnet/AspNetCore.Docs#23695]
[Enter feedback here]

The instructions for setting up a Blazor Server application under /CoolApp/ are wrong and don't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e07aaa4d-4ad4-778f-f74a-60d8f05d9075
* Version Independent ID: c82cf121-831d-75dd-a796-c735aad3b3e9
* Content: [Host and deploy ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@cmedianu ... We're unable to provide product support, and your report has no specific information about why/how the guidance is incorrect. Reach out to devs on public support forums for assistance. We recommend the usual places ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

**Comment by cmedianu** [comment]
@guardrex Thanks Luke. Here's an example of adding the 2 lines from the instructions to a fresh generated project, the application crashes with:

_InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /CoolApp/{**path:nonfile}, area: }._

https://dev.azure.com/cmedianu0603/publicProject/_git/BlazorServerPathChangeSoln/commit/c6e135c91ed8f2430d6a6af208bac222500bffeb?refName=refs%2Fheads%2Fmaster

**Comment by guardrex** [comment]
Thanks for the additional info. I'll see if I can repro that behavior on Monday.

**Comment by cmedianu** [comment]
Awesome!

**Comment by guardrex** [comment]
Yep @cmedianu ... There is a regression with the guidance. At 3.1 IIRC, this worked; but today it 💥. For one thing, extra segments popped up similar to a product unit repo issue at https://github.com/dotnet/aspnetcore/issues/34252, except that the revised fallback path didn't come into their discussion.

Try the following .......

1. Set the base path. Two options here ...

   * Option 1:

     Leave the default  `<base>` tag in place with a `~/` path:

     ```cshtml
     <base href="~/" />
     ```

     Set the path base using the API in `Startup.Configure` (<6.0) or `Program.cs` (>=6.0 preview) ...

     ```csharp
     app.UsePathBase("/CoolApp");
     ```

   * Option 2 (the converse of Option 1):
   
     Set the base path using the `<base>` tag but note that there is **no tilde (`~`)** on it:

     ```cshtml
     <base href="/CoolApp/" />
     ```

     Do **not** set the path base using the API with :x: ~`UsePathBase`~ :x:.

1. Use the default fallback .......

   ```csharp
   app.MapFallbackToPage("/_Host");
   ```

   Do **not** use the topic's recommended fallback :x: ~`/CoolApp/{**path:nonfile}`~ :x:.

   I found the same thing that you did. It chokes and claims that it can't find that path.

   IIRC, that guidance came in part of a PU ("product unit") recommendation that I never tested, and it might be for a different use case.

For now, try the config that I mention above 👆. If that works for you, too, then I'm going to patch the guidance along those lines for now until I can reach out to Javier. Everyone, including myself, is buried in 6.0 work ⛰️⛏️😅 right now for the upcoming release less than two weeks away. There will be a period after that for 6.0 mop-up activities. Then, we'll have reached the 🎁 *holiday break* ⛄ for some much-needed R&R ⛱️. I'll make an update to the guidance, but I'll end up having the discussion with the PU in early 2022.

Also, I'm going to check the guidance against a WASM subapp to see if it works out the same way. If so, then I'll make similar changes for the WASM subapp coverage.

**Comment by cmedianu** [comment]
Hi @guardrex I tried both options, I commited them as branches based on the generated project here: 

https://dev.azure.com/cmedianu0603/publicProject/_git/BlazorServerPathChangeSoln?path=%2F&version=GBoption1&_a=history

They both fail.... They don't crash, the stuff is just in the wrong place.

Thank you so much for looking into this!

**Comment by guardrex** [comment]
I can't quite grok that. You have to use `UsePathBase` if you don't change the `<base>` tag, and your app doesn't seem to do that.

Also, this all only works if it's literally hosted as a subapp. My tests use local IIS with published apps. I can't tell if that's (or something similar) is what you're doing. btw- I'm not a "DevOps guy," so idk what the hosting scenario is with that approach.

**Comment by guardrex** [comment]
Are you actually subapp-hosting that somehow? That's the only way that it's going to work.

Like I said ... I'm not into Azure DevOps, so I can't remark too far on that. I'm more of an IIS :cat2:. :smile:

**Comment by cmedianu** [comment]
Hi @guardrex ,

I would expect the app to move to the new path in Visual Studio, but it does not. That is, it should be at http://localhost:24771/CoolApp/ instead of http://localhost:24771/ when I hit the run button. I don't think it has anything to do with deployment.

I may be able to get option 1 to work by tweaking it on the server, but this is not what's supposed to happen.

Thanks again,

Calin

**Comment by guardrex** [comment]
I see. So, you're angling not to have a subapp but to host **in Kestrel** at a different path ... and in development. That's not what the scenario was intended to cover here. This guidance is for formal **subapps** for published apps, IIS subapps in particular as the most common use case, where the app lives as a subapp of the main app but has no idea on its own where it resides in host/request paths.

Let me check a little further because I don't necessarily disagree with you on it being something that could be configured (e.g., via launch settings). It's not a common request as far as I know to set up the app the way, especially in development.

**Comment by cmedianu** [comment]
I want to host it in Kestrel both in development and in production, behind
a reverse proxy under /CoolApp, for that, it must be able to run the whole
application under /CoolApp Kestrel to begin with.

Thank you

**Comment by guardrex** [comment]
It might be similar to WASM in that the local run on Kestrel has you pass the pathbase to the `dotnet run` command.

I'm researching it now ... but it's fighting me a little at the moment 😈. I'll get back to you.

**Comment by guardrex** [comment]
Thus far, it's quite happy with ...

```csharp
app.UsePathBase("/CoolApp");
```

The paths do form correctly ... no SignalR problems or foul behaviors.

I think launching would be via launch settings, and it's not too happy with that at the moment 💥😈.

**Comment by guardrex** [comment]
Try adding a `launchUrl` to the `launchSettings.json` file and see if it sucks that in and opens the browser to the right endpoint ...

```xml
"launchUrl": "https://localhost:7279/CoolApp",
```

Only use the `UsePathBase` approach ... just that one change in the app ...

```csharp
app.UsePathBase("/CoolApp");
```

... and don't change the `applicationUrl` in the launch settings ... leave that as whatever the default is. In my app, it's ...

```xml
"applicationUrl": "https://localhost:7279;http://localhost:5279",
```

**Comment by guardrex** [comment]
If that works, we're good. It's not really a "Blazor thing," per se. That's all just normal ASP.NET Core stuff covered by the main doc set .... *somewhere* :smile: lol.

I'm glad tho that I took a look at the **subapp** piece. That is broken at this point, probably just due to churn. I'm going to go with the updates on the PR, which are confirmed working. I'll get up with Javier later on a couple of the finer points and the fallback path mapping piece.

**Comment by guardrex** [comment]
I've made an update to the PR that highlights the use of Option 2 (`UsePathBase`) with a `launchUrl` in the launch settings. I can't get the launch to work for Option 1, so I'll recommend in the topic that the dev go with Option 2 when they also want to run locally.

**Comment by guardrex** [comment]
Next, I'll see what happens in a nested Kestrel app scenario; but fair warning, this isn't (or at least it wasn't) a supported scenario.

**Comment by guardrex** [comment]
Now that I think about it ... this very well might be where that fallback path comes into play.

**Comment by cmedianu** [comment]
Option 2 does not work for me, it can't find the styles.
for example, It's 404ing on https://localhost:7279/CoolApp/css/bootstrap/bootstrap.min.css
because that file is actually here:
https://localhost:7279/css/bootstrap/bootstrap.min.css

How did you make the css and js files also be under /CoolApp ?

**Comment by guardrex** [comment]
For Kestrel-based hosting, I haven't had a completely running app. I'm still still trying reason about the fallback path mapping. This is a case where the product unit gave me the code for the topic but I didn't have time to test it at the time. The coverage is even missing a remark that the fallback path code goes in the host app, not the Blazor Server app ... AFAICT.

For IIS, I only set the path base with `UsePathBase`. I'm running my tests tho using the CLI. I don't use VS during the late preview stages of release because VS isn't updated to adopt 6.0 at this time. Therefore, I can't detect yet if VS will launch the app at the correct URL. I can only say that running the Blazor Server app directly works from the CLI and running it as a proper subapp under IIS works with only the `UsePathBase` setting. That's good thus far. It's probably worth my reproducing it under 5.0 so that I can use my local VS to study the behaviors.

I'll need to stop here for the day and return to this tomorrow morning (Tuesday). I'll work further with the Kestrel scenario and research it further on the product unit repo (and elsewhere). There's probably something simple that I'm missing ... *I hope* 🤞. I'll also try a 5.0-based app pair with VS to see how that goes.

**Comment by cmedianu** [comment]
Thank you so much!  Just so you know, the problem is not that it doesn't automatically open to that URL, the problem is that when I type in the URL, it doesn't work. Same failure for dotnet run and for running it inside VS.

$ dotnet --version
5.0.402
Visual Studio 2019 latest

**Comment by guardrex** [comment]
Yes, but in Kestrel, correct?

I'm having good results with IIS. I think what we'll have for IIS will be fine. There's just that one (**major** ❗) problem with the `<base>` `href` path for IIS that must be corrected: The tilde (`~`) in that scenario has to come off ... that should lead to a working Option 1 with IIS. In the Option 2 case with IIS, it also runs directly; however, I just can't say tho what happens in IIS at this point given that I haven't dropped down to 5.0 yet. AFAICT, I think that the `launchUrl` will spawn the app correctly in VS. I understand that this isn't what you're asking about, but I do need to know to make the coverage better. There's running the subapp for IIS, and there's running that exact app in VS locally. The coverage has to deal with both.

For Kestrel, I'll try again on Tuesday morning. Ideally, whatever config runs the subapp will become clear for both as well ... running as a subapp (e.g., in a published app/subapp scenario) **_and_** does that subapp run directly (VS or CLI). Same questions as for IIS but in the Kestrel scenario. *Indeed!* It is fighting with me a bit 😈; but even if I don't figure it out, I'll be able to tell Javier what problems we're hitting so that he can clarify or figure out that something really did break in the framework. It's been a busy morning ... my 🧠 is a bit 🥘 at the moment. 😵 I'll get back to you tomorrow on this. That PR that I opened can sit for now.

**Comment by cmedianu** [comment]
Thank you so much Luke! What I want is this:
- If I run dotnet publish, I transfer the app to the linux server,  run _dotnet CoolApp.dll_ , it should run the app under /CoolApp/ - This is Kestrel.
- The app should also run in visual studio when I hit the run button (not sure if this is kestrel), as well as when I run dotnet run from the command line. This does not work with option 1 or option 2, it doesn't find the static resources.

This all works fine, as long as it's under /, but you can't deploy the app at the root of the webserver...



Thanks again!

**Comment by guardrex** [comment]
@cmedianu ... Did you try setting the static files path? Like this along with the base path ...........

```csharp
app.UsePathBase("/CoolApp");
app.UseStaticFiles("/CoolApp");
```

I seem to recall this coming up on an issue in ancient times 👴. Now that I understand better what you're doing, that might load the static assets correctly in that scenario.

Even if that works tho, leave this issue open. I still need to fix up the subapps guidance. This issue will close automatically when the PR merges later.

**Comment by cmedianu** [comment]
That is great progress, yet a bit weird.

**on http://localhost:5000/** 
The application still looks on and works ok. Weird, but whatever.
I see: 
Normalizing '_blazor' to 'http://localhost:5000/_blazor'.
Information: WebSocket connected to ws://localhost:5000/_blazor?id=JAHA4KoO4ma0H2gU1n1Pag.

**on http://localhost:5000/CoolApp/**
The application looks OK  all the styles are loaded OK. However, the counter does not increment, the WS is not connected.

I see:
Information: Normalizing '_blazor' to 'http://localhost:5000/CoolApp/_blazor'.
http://localhost:5000/CoolApp/_blazor/negotiate?negotiateVersion=1 - 400 Bad Request
Failed to complete negotiation with the server: Error: Bad Request
Failed to start the connection: Error: Bad Request
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.

I tried both Kestrel and IISExpress, both from VS.

**Comment by guardrex** [comment]
> The application looks OK all the styles are loaded OK. However, the counter does not increment, the WS is not connected.

The Blazor Script didn't load correctly due to the path segment in the URL. This situation with the script not loading is why the following was provided by the product unit ...

https://docs.microsoft.com/aspnet/core/blazor/fundamentals/static-files

See if that last bullet is helpful.

I do want to cross-link this *Static files* topic into the *Host and deploy* topic on the PR to help surface it. I'll do that soon.

**Comment by guardrex** [comment]
I'm researching all of those PU issues to see what, if anything, applies. I'm trying to find out more about the use cases for the fallback path that they provided so that I can say in that section exactly what it applies to. I also need to run a few more local tests.

It's turned out that several small tasks are being addressed for this document section. When you get a final working approach for your reverse proxy and the non-root path, please post back in an issue comment the final, complete configuration that you ended up using.

**Comment by guardrex** [comment]
Oh, I forgot about one static asset path setting option that I was just reminded about in a PU issue. The PU issue doesn't pertain to what we're discussing here, as it has to do with a WASM debugging scenario.

As an alternative to passing the path to `UseStaticFiles`, you could try the following in the project file in a property group ...

```xml
<StaticWebAssetBasePath>CoolApp</StaticWebAssetBasePath>
```

That config is currently covered for CSS isolation and hosting multiple Blazor WASM apps that each need to know where their static assets are located. It might make sense in your scenario and have a different effect that doesn't require you to make further changes to get the Blazor script to load properly. I recommend trying that **_without_** the call to `UseStaticFiles` to see what happens.

**Comment by guardrex** [comment]
I'll keep a few notes here for myself to review (that include references that don't pertain to our discussion but that I don't want to lose track of) ...

* https://github.com/dotnet/aspnetcore/issues/19744
*

**Comment by guardrex** [comment]
I'm going to circle back around on the `MapFallbackToPage` scenario later. I've almost reached critical mass for coverage, but I need to consult with the PU to resolve one pesky 😈 in my implementation. Everything else works for mapping to a different root page for a different "area" (e.g., Admin) of the app with a separate layout, stylesheets, JS files, components, etc. The Blazor script is fouling it up. It has a 💥 when linked from the alternative (Admin) root page ...

> Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data

@cmedianu ... I'm going to merge what I have on the PR now, but I'll be back to work on this by the end of the year. If you work out that final hosting piece for Linux and the Blazor script, please go ahead and post a comment on this (closed) issue later. I'll see it, and add a note to my tracking issue to possibly call it out in the topic later. Please provide the exact, full configuration for any of the following as required ...

* `<base>` tag setup.
* `UsePathBase`
* `UseStaticFiles` (and/or `MapWhen` for the Blazor script ... and note https://github.com/dotnet/AspNetCore.Docs/pull/23724 just came in for a syntax error on what was provided by the PU originally)

**Comment by guardrex** [comment]
Last note ... be sure to just try a different order, too, for the `UseStaticFiles` calls.

Per ... https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#hosted-deployment-with-multiple-blazor-webassembly-apps-1

I noticed that the call without the path is **_first_** ...

```csharp
first.UseStaticFiles();
first.UseStaticFiles("/FirstApp");
```

Try it in that order ......

```chsarp
app.UsePathBase("/CoolApp");
app.UseStaticFiles();
app.UseStaticFiles("/CoolApp");
```

... in hopes that the Blazor script is found with the first one and the static assets are found with the second one.

**Comment by cmedianu** [comment]
Thank you very much for the help, I will give that a try as well.

**Comment by zedpentium** [comment]
Hi. A Wall of text post.

I just started to try get a Blazor Server SPA to work beside/in my .net core 3.1 mvc project/system.
To hopefully not have to use the javascript based SPA. VUE, angular, React and more.

But have huge problems getting Blazor Server SPA to work in/from a SUB-URL (and from a subfolder),
without messing up my mvc view. (Adminpanel AND customer & front views)

Im using Visual Studio 2022. and develop locally iis-express.
(will publish to my development iis server when its working, for futher testing and building of functions).
My MVC Project is using core 3.1.
Have my Blazor Server files in "projectroot"/Blappserv .
Started by trying to get blazor server template SPA to work from sub-url.
So under Blappserv is Pages and Shared
App.razor is in the root of project.

I want this simple thing to work in sub-url as "startpoint" for my comming bigger SPA-stuff.

I tried so many combinations and paths of:
_Host file base href and its @page (and changed page in index etc also to see)
from base with ~ and not .. with trailing slash and not.

with / and /Blappserv/ 

And in startup the :
 
services.Configure<RazorPagesOptions>(options => options.RootDirectory = "/Blappserv/");
app.UsePathBase("/Blappserv");
app.UseStaticFiles();
app.UseStaticFiles("/Blappserv");
endpoints.MapFallbackToPage("/Blappserv", "/_Host");
 
And getting errors like:
"Cannot find the fallback endpoint specified by route values: { page: /_Host, area: }."
And razorscript not loading and connection.. and lots of other issues that breaks my MVC.

And when i get a blazorpage to work.. it reloads the page instead of SPA when changing "view/page".

Been working with this for 3 days. 8 hour and more each day... just can't get it to work.
NOT from a sub-url. Only works out of the box.

Have read and googled ALOT on internet, tested others projects.
But none seams to have it working from/in a "sub-page"
when rest of it is MVC.

Have read this thread, hoped for solution to the "path" problem.
And also this over and over:
https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-3.1&tabs=visual-studio

option 1 or 2 for blazor server do not work.. and as i said.. tested alot of combinations of the stuff written above here..

Could someone help to get the simple template of Blazor Server SPA to work in sub-url/folder to start with=?
And then, hopefully, it also will work in my MVC  without messing that up.


I do not want to redo/replace the whole frontend (AdminPanel and "customer" front-views) with blazor server.
At this point. Will take to much time. I want to gradually be able to redo parts later.
Which Blazor Server also should/seams to fit very nicely.

So i can use c# and DI, servicelayer and repos. Coz i allready like Blazor Server ALOT .
and not have to use javascript VUE, Angular, React etc for this.
Blazor Wasm are also in need of API and Json like them JS libraries/framworks...

I also/first made a new project to test with. Blazor Server template with counter etc.. and moved most files into a subfolder named Blappserv, and changed all them setting and combinations. and i STILL did not get it to work.
Having all the same issues in both my huge projekt/system and the test-blazor app.
no page found, and "Cannot find the fallback endpoint"
and many other odd stuff messing with my MVC, and like counter stopped working (button click)
etc.

I am at a loss. Have no more ideas.
Can u get Blazor Server template working, by creating a new folder in root (for example blappserv, or app or CoolApp).
And move the folder "Pages" and "Shared" and there files into that new folder?

Then change the needed namespaces in imports and other files.
And lasty config _Host and startup. to get this to work?
I can not. 

I wanted to have endpoints.MapFallbackToPage("/Blappserv", "/_Host");  to control that
ONLY under /Blappserv it will run the Blazor SPA.. while any other "url-path" that i use, is the usual mvc.

Seams i can NOT "only" use components and build SPA.. coz i then lack the routing-part (app.razor)
so get no SPA.

Am i forced to redo all my mvc frontend/views and partial views in blazor server SPA, to get this frontend working?

In my Blazor Server part, I have allready written some working parts and CRUD from/to my mssql database, and stores it in a viewmodel. that works correctly when using "root" url - "default" settings.
Using successfully the viewmodel in all that SPA views. For displaying info, updating etc and for "state store" onchange.
So i now know Blazor Server will work for my purposes. If i only can get it to co-exist with mvc by running correctly from a sub-url, and not mess with rest of the mvc.


IF this is not possible, well, then i am forced to use/go back to some javascript-lib/framework to get SPA.
VUE or angular.
(i am no longer fond of React.. coz that needs React Router.. that needs webpack and node.js.
And that is very easy to "break". And very annoying to fix/revert.
Also i never got Redux to work with React in c# , mvc and VS.

Thank you, for reading all of my text.
Hopefully you or someone can make it work / co-exist with mvc.

Regards and hopes
/Eric - Sweden

**Comment by guardrex** [comment]
Hello @cmedianu ... We don't have the ability to troubleshoot individual projects, especially general 'it doesn't work'-types of issues. I recommend that you place a minimal repro project on GH for discussions with the community. We recommend the usual channels for product support ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

Note btw that there were upgrades to the latest version(s) of the topic over 3.1 that you might want to analyze. The newer coverage might be helpful even if I didn't provide it back for 3.1.

We're not currently aware of any problem with the guidance. When you find out what's wrong, I would like to hear about it. Please don't comment on a closed issue/PR ... go ahead and open a new issue using the **This page** feedback button+form at the bottom of the topic ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-6.0&tabs=visual-studio#app-base-path
