### ISSUE TITLE
Missing code which is generated from project template

### ISSUE THREAD

**Issue by johndhunter** [dotnet/AspNetCore.Docs#23696]
[App component](https://docs.microsoft.com/en-gb/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-6.0&tabs=visual-studio#app-component) needs 
            ```<FocusOnNavigate RouteData="@routeData" Selector="h1" />```
and maybe an explanation (i.e. the tooltip)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985b834f-534a-aba6-80a0-d8845adbfc25
* Version Independent ID: d2b5a556-82a4-e939-be68-2357a3d4408f
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-gb/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @johndhunter ... To harden this doc (and in other places), we're going to try **_not_** to show code that doesn't apply to the scenario at hand. It's too hard to keep up with the churn otherwise. Thanks for reporting this ... I'll take care it quickly. Leave this issue open, as it will close automatically when the PR merges.

**Comment by johndhunter** [comment]
Cool but I thought this was the scenario at hand (https://docs.microsoft.com/en-gb/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-6.0&tabs=visual-studio) - in other words that was the self-same set of instructions I followed and it generated that code (VS Version 17.0.0 Preview 7.0 and 6.0.0-rc.2.21480.10)

**Comment by guardrex** [comment]
I mean that it's not relevant to the coverage of the concepts of the section. `FocusOnNavigate` is for another purpose/goal, having to do with setting nav focus to the top-level header after navigation. It doesn't bear on the security concepts that the section calls out (in the bullet list).

However, I don't really want to drop **_all_** of the code. In these cases, I usually make a strategic use of an ellipsis (`...`) to cover things that changed across versions but that aren't relevant to the section/example. It does have a downside tho: I mostly favor cut-'n-paste examples so that devs can just take the whole thing ... whatever it is ... the `App` component in this case ... and drop it into an app (e.g., they might be doing an app upgrade) and it will ✨ **_Just Work!_**&trade; ✨. Obviously, my ellipsis approach isn't suitable for that.

I need to get past the 6.0 release tho and some much needed R&R 🏖️ on the 🎁 *holiday break* ⛄ before I engage with the whole security node. Use of ellipsis is a reasonable compromise at this time with 6.0 about to release while we're all 🏃 ⛰️⛏️😅. I'll reach this node on https://github.com/dotnet/AspNetCore.Docs/issues/19286 for more work. I'm going to cross-link this discussion to that issue to make sure that I review this when the time comes.
