### ISSUE TITLE
ChildBind component doesn't work without bind-Year set

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#23701]
in Shared/ChildBind.razor:
the ChildBind component button only works if you use with bind-Year set like this:
`<ChildBind @bind-Year="year" />`
if you use it like this:
`<ChildBind />`
the "Update Year from Child" button does nothing 
it needs to be changed like this:
```
    private Random r = new();
    private int year;

    [Parameter]
    public int Year
    {
        get => year;
        set => year = value;
    }

    [Parameter]
    public EventCallback<int> YearChanged { get; set; }

    private async Task UpdateYearFromChild()
    {
        year = r.Next(1950, 2021);
        await YearChanged.InvokeAsync(year);
    }
```
to make it work, 
it would be shorter if we do `Year = r.Next(1950, 2021);` 
but I've read that we shouldn't set to component's own parameters so I've added the backing field

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-5.0#binding-with-component-parameters-1)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It already binds that way, and this is an example of one-way binding.

The next example binds across components ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-5.0#bind-across-more-than-two-components-1

Overwritten params are covered at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0#overwritten-parameters-1

All of this content has been reviewed by the product unit, and I think this is the way that they want to cover it ... at least for now. We'll review it again in 2022.

**Comment by omuleanu** [comment]
@guardrex my comment was not about binding, 
the surprise for me was that the component is not working at all if it isn't bound to a Parent's property

**Comment by guardrex** [comment]
Ok, but I can't really address that. It's a framework design subject/consideration. Feedback/questions on the framework can be opened for the engineers ...

https://github.com/dotnet/aspnetcore/issues

... but you might want to hold off opening an issue unless this is very important because they're all 🏃😵 like mad trying to get the 6.0 release out ... and then mopping-up after that for a few weeks. If it's not critical and can wait, I recommend waiting until late November/early December ... but 😄 lol **_don't wait too late_**. They tend to bug out for the 🎁 *holiday break* ⛄ and not return until January.

**Comment by omuleanu** [comment]
don't think it's a framework issue, I didn't expect the component in the docs to work this way, 
but I guess it makes sense since the docs are focusing on showing the binding parent to child and nothing else.
just for me as a learner it was a surprise

**Comment by guardrex** [comment]
Yes, that's right ... and AFAIK, the structure of these components, the structure of the markup+code, for this binding is **by convention** based on their design. *And ... they don't do random things!* 😄 lol ... I think that there is **_a reason_** .... **_an answer_** ... to your question about this. That's why I think that you could chat with the PU about it. I just caution that this isn't quite the best time given the 6.0 release and recommend late November/early December. They're truly 🏃 at the moment.
