### ISSUE TITLE
I've tried to follow these directions as faithfully as possible but they aren't working on my app.

### ISSUE THREAD

**Issue by OkilyDokily** [dotnet/AspNetCore.Docs#23764]
[Enter feedback here]
 AccessToken = await HttpContext.GetTokenAsync("Discord", "access_token") will usually return an empty string.
The only time that I'm able to get the access token is when I register a User with the Identity framework.

I don't know if that was intended but I need the access token more often than that.

In the instructions you don't need to specify an authentication scheme ("Discord")  in the GetTokenAsync method, but this is the only way I am able to get the access token - but again only after registering a user. Not in other subsequent logins after I've logged off, although the access token remains accessible on subsequent reuse/reruns of the app If I don't log off after I've registered a user.

I'd like to at the very least get these access tokens after a login callback with oauth, although I don't see why I shouldn't be able to access them any time I want.

 I've suspected that I may need to explicitly save tokens in the right callback function in externallogin.cshtml.cs but have not had any success in that direction. I've noticed that only create new user portion of this file contains these lines related to saving tokens.
```
  var props = new AuthenticationProperties();
  props.StoreTokens(info.AuthenticationTokens);
  props.IsPersistent = true;
```
That might seemingly explain why I can only access the tokens when I've registered the app. Yet I have not been successful in solving this problem by adding similar lines of code where I think it's appropriate in other parts of this file.
Here is my externallogin.cs.html.cs file as it is now. 
https://wtools.io/paste-code/b78i

When I do login am able to see my access token in the oncreatingticket event.
   ```   OnCreatingTicket = ctx =>
                    {
                        Console.WriteLine("creating !!!!!!!!");
                      
                        List<AuthenticationToken> tokens = ctx.Properties.GetTokens().ToList();
                        Console.WriteLine(tokens.Count);
                        foreach (AuthenticationToken t in tokens)
                        {
                            Console.WriteLine(t.Name);
                            Console.WriteLine(t.Value);
                        }

                        ctx.Properties.StoreTokens(tokens);

                        return Task.CompletedTask;
                    },
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8acbbf-c9d4-7041-c1a7-ec9ce8f0981b
* Version Independent ID: c98be365-408d-7ee6-cb74-14c44d01b0b8
* Content: [ASP.NET Core Blazor Server additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/server/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/server/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @OkilyDokily ... First, check the issues in the product unit's repo for Discord. The following search for open and closed issues and "Discord" seems to have turned up some issues that might be of interest ...

https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+discord+

You can ask the product unit for assistance, but they're extremely busy and might not be able to help and/or might claim that they can't support Discord users. Also note that you'd be asking on the eve of the ASP.NET Core 6.0 release next week. They're **_slammed_** 🏃 ... and will be for a while longer. Even if they don't close the issue outright, it might take some time for them to get back to you.

Your best bet is to address it to the community on general support forums or any support forums where Discord devs hang out. We recommend the following for Blazor ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

Sorry that we can't be of greater help, but this isn't really a general support forum. We only work on documentation here for the supported providers and scenarios specified by management, and there are only about three of us working here at any given time with >400 topics, >100 samples, and >500 issues ... and in this case, no Discord experience AFAIK among us ... *you get the picture* ⛰️⛏️😅.

I would like to provide one small piece of advice in passing based on your remarks. Testing can lead to unpredictable behavior with identity scenarios due to lingering cookies and cached data between test runs. See the guidance at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-5.0&tabs=visual-studio#cookies-and-site-data

... for some tips. It might smooth out some variability in your test runs as you change the app/users.
