### ISSUE TITLE
What are the differences in Blazor for .net 6 from .net 5 requiring a new project?

### ISSUE THREAD

**Issue by kevingates** [dotnet/AspNetCore.Docs#23818]
You mention here: https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio#blazor

> To adopt all of the new 6.0 features for Blazor apps, we recommend the following process:
> 
> Create a new 6.0 Blazor project from one of the Blazor project templates. For more information, see Tooling for ASP.NET Core Blazor.
> Move the app's components and code to the 6.0 app making modifications to adopt the new 6.0 features.

But you never mention what is lacking if we don't update the project. So if we change the dotnet version on our blazor serverside project from .net5.0 to .net6.0, are we still lacking? And if so, what and why? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bec61f9-7298-170d-5e12-abb27cde584e
* Version Independent ID: 27a43e3f-149d-9058-f937-0eda1d6dd4f2
* Content: [Migrate from ASP.NET Core 5.0 to 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/50-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, the app doesn't receive most new features without developer intervention automatically when you merely update the target framework. The new features are listed in the *What's New for 6.0* doc and will be listed in the 6.0 GA release blog post when it comes out.

* https://docs.microsoft.com/aspnet/core/release-notes/aspnetcore-6.0#blazor
* https://devblogs.microsoft.com/dotnet/

We used to describe how to migrate an app from one release to the next for Blazor step-by-step, but it's just too much churn/work to cover this time around. Devs can adopt each feature using the docs and by looking at an app created from a new 6.0 app or by creating a 6.0 app and migrating their components, code, etc. to the new app.

What I'll do here to help surface the new features is cross-link the *What's New* topic to this. It wasn't possible before because the *What's New* topic wasn't available until recently, but I can make the cross-link now.

Thanks for commenting on the guidance. Leave this issue open, as it will close automatically when the PR merges.
