### ISSUE TITLE
About component's render from Razor Page

### ISSUE THREAD

**Issue by dlyltm** [dotnet/AspNetCore.Docs#23948]
[EDIT by guardrex to fix the code blocks. @dlyltm ... Use triple-backticks above and below to create code blocks in GH issue/PR comments.]

I created a asp.net core web project(Razor Pages). Then I created a Razor Component `StScnBtnCompt.razor` as follows:

```razor
<div>
    <input id="Scan" class="btn btn-danger btn-lg" @onclick="@(e=>ToScan(e))" type="button" value="Start" />
</div>

@code{
   [Parameter]
    public int ParentYear { get; set; } = 1987;

    public void ToScan(MouseEventArgs e)
    {
        ParentYear = 1986;
    } 
}
```

In the corresponding cshtml file, add the following statement:

```razor
<component type="typeof(StScnBtnCompt)" render-mode="WebAssemblyPrerendered" />
```

Run the project, the above component shows, but it's `@onclick` is unresponsive. Clicking the component, the `ToScan` isn't invoked. Setting `render-mode` to `ServerPrerendered` is the same.

If I set the `render-mode` to `Server` or `WebAssembly`, the component doesn't be shown.

In additionthere are statements in my project file as follows:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

<PropertyGroup>
  <TargetFramework>net5.0</TargetFramework>
  <CopyRefAssembliesToPublishDirectory>false</CopyRefAssembliesToPublishDirectory>
</PropertyGroup>
```

After building the project,prompt the following warnings:

警告	NU1701	已使用“.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8”而不是项目目标框架“net5.0”还原包“Microsoft.AspNet.Razor 3.2.7”。此包可能与项目不完全兼容。

警告	NU1701	已使用“.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8”而不是项目目标框架“net5.0”还原包“Microsoft.AspNet.WebPages 3.2.7”。此包可能与项目不完全兼容。	

警告	NU1701	已使用“.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8”而不是项目目标框架“net5.0”还原包“Microsoft.Web.Infrastructure 1.0.0”。此包可能与项目不完全兼容。

警告	NU1701	已使用“.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8”而不是项目目标框架“net5.0”还原包“Microsoft.Web.Infrastructure 1.0.0”。此包可能与项目不完全兼容。

Please tell me what's wrong with this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c1a41f-0615-ef27-f9a3-032b9db702a3
* Version Independent ID: 8ac3492b-34dd-d94e-e661-c3028ca2acdb
* Content: [Component Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/component-tag-helper?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dlyltm ... There's a bit more configuration that is cross-linked in the Component Tag Helper topic at the top ...

<img width="317" alt="Capture" src="https://user-images.githubusercontent.com/1622880/142199658-14087afc-1882-4eee-8532-f6baa35f624d.PNG">

See the following article ...

https://docs.microsoft.com/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=server#solution-configuration

... and make sure that you are looking at the **Blazor Server** version.

**_Leave this issue open._** I think that cross-link should be more specific for the Blazor Server entry and say that it's for integrating for Razor Pages/MVC apps. I think you would have noticed it and found the guidance. This issue will close automatically when the PR merges. Thanks for your comment here.

**Comment by guardrex** [comment]
... and note that since you're rendering non-routable components into a Razor Page, you want to follow the **Configuration** steps first ...

https://docs.microsoft.com/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=server#configuration

Then, follow the guidance in ...


https://docs.microsoft.com/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=server#render-components-from-a-page-or-view

**Comment by guardrex** [comment]
Leave this open. I'm going to make an update to the cross-link to help get readers to the right spot.

**Comment by guardrex** [comment]
AFAIK, this is known working, but I don't mind giving it a quick run thru myself in the next day or two to confirm.

**Comment by dlyltm** [comment]
My development environment is vs2019,and the browser is ie11.

**Comment by guardrex** [comment]
IE isn't supported, so that very likely explains it. Try with Chrome, Firefox, Edge,  or Opera.

**Comment by dlyltm** [comment]
I've tried with Edge,but it still didn't work.

**Comment by guardrex** [comment]
The guidance works here ...

<img width="378" alt="Capture" src="https://user-images.githubusercontent.com/1622880/142396982-7b25d034-dcd5-4554-8358-5b230aa0497e.PNG">

Try again with a new app created from the Razor Pages project template that uses the default `Counter` component, as the guidance shows in the *Configuration* section. Don't use your own code, just follow the section exactly. If it still doesn't work, open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

* Tell them that you followed the guidance here ... https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=server#configuration ... and that the doc author checked it and found it working (I just checked with 6.0, but I also checked it earlier with 5.0). Explain what's happening for you (e.g., the button doesn't increment the counter).
* They will need you to put that project up on GitHub so that they can inspect to confirm that everything is correct. Provide any error messages that you receive in the logs, and show any screenshots that you think might help (e.g., screenshots of any errors in the browser's Developer Tools console and/or VS Output panel).
* They'll then work with you to get more information from the app as to why it's failing (e.g., they might ask you for [additional logging on the SignalR connection](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#configure-signalr-client-logging-blazor-server) ... "debug" level, perhaps). They'll let you know what they need you to do.
* It's best to speak with them in terms of it not working in Edge. If you mention IE, they'll probably say the same thing I did about IE not being supported.
* Please add a `cc: @guardrex` to your opening issue comment so that I can follow the discussion. It might turn out to be something that we need to add to the article.

I'm going to close this because there's nothing actionable for the document (*yet*) and keep an eye 👁️ on your engineering issue. I'll re-open this issue if they work out that we're missing some coverage.

**Comment by dlyltm** [comment]
OK,I'll do it following the guidance.I think maybe my app type is wrong.I should select to create a Blazor Server app.

**Comment by guardrex** [comment]
It's for a Razor Pages or MVC app, not Blazor Server.

**Comment by dlyltm** [comment]
![1637369017(1)](https://user-images.githubusercontent.com/33916145/142707896-60b990a1-ea4a-411b-ba21-53baeef5601f.png)
What does that mean?

**Comment by guardrex** [comment]
It means that the RP/MVC app is being converted into a RP/MVC-Blazor Server hybrid app ... a blend of the technologies. The wording there probably needs a touch more work for improved clarity. I'll work on it when I reach the topic again for updates.

**Comment by guardrex** [comment]
Note that when I wrote "not Blazor Server" that I meant this guidance isn't starting from a project created from the Blazor Server project template. It starts with a RP/MVC project and then adds the bits to make it also a Blazor Server app.

I do think the language of that line is a bit hard to grasp. I will get back to this topic soon to address it. I'll leave a message for myself so that I don't forget.

**Comment by dlyltm** [comment]
![1637372111(1)](https://user-images.githubusercontent.com/33916145/142709685-a182557a-b8f6-4347-93e8-a7b373a3d399.png)
Does that mean vs2019 doesn't support .Net 6 developping?

**Comment by dlyltm** [comment]
![1637375769(1)](https://user-images.githubusercontent.com/33916145/142711613-4eeec121-0e4d-470d-acf0-53153866a989.png)
I create a new app with Blazor Server,it's target framework is .Net Core 3.1,the browser is Edge,then OK.
