### ISSUE TITLE
IdentityServer Appsettings.json settings for Linux

### ISSUE THREAD

**Issue by dajma00** [dotnet/AspNetCore.Docs#24008]
The appsettings.json settings shown on this page seem to be geared towards Windows OS. For example what should be the values for Type, StoreName, StoreLocation on Linux? There needs to be clarity on the IdentityServer settings for Linux.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-5.0#example-deploy-to-a-non-azure-web-hosting-provider)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @dajma00 ... We must defer to [3rd party docs](https://docs.microsoft.com/aspnet/core/security/authentication/community) in many cases for 3rd party configuration because it depends on the flavor of IdS that you're adopting. For example pertaining to DP/signing key management for Duende ...

https://docs.duendesoftware.com/identityserver/v5/fundamentals/keys/

They favor automatic DP filesystem config, but they also have a section right after that on static key config.

In any case, consult the docs of the IdS provider for details, Duende or otherwise. If you run into problems and require product support, we recommend the usual public forums, such as ...

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)

**Comment by guardrex** [comment]
... and I'll add in passing that they (and probably other 3rd parties) link back to the ASP.NET Core DP coverage for details on the framework DP API ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-6.0#data-protection

... and that might be relevant depending on what you're trying to configure (e.g., you might wish to use something other than Duende's automatic DP with filesystem-stored signing keys).
