### ISSUE TITLE
.NET 6: Background tasks with hosted services 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#24024]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@Rick-Anderson It looks like this has [already been done](https://github.com/dotnet/AspNetCore.Docs/pull/23286).

**Comment by Rick-Anderson** [comment]
What's up with
![image](https://user-images.githubusercontent.com/3605364/143276824-3d0ce708-0dee-4f29-b30a-998de563e018.png)

**Comment by serpent5** [comment]
I think that's because this article mostly uses the worker service template, which doesn't use `WebApplication`. [It uses the `Host` and its `ConfigureServices`](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services/samples/6.0/BackgroundTasksSample/Program.cs#L3-L4).
