### ISSUE TITLE
It should be clear IHostedService.StartAsync() should be short lived.

### ISSUE THREAD

**Issue by gklittlejohn** [dotnet/AspNetCore.Docs#24038]
Under BackgroundService  is states StartAsync should be limited to short running tasks, however this comment also applies to IHostedService .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@gklittlejohn  are you saying it should change to the following?

`IHostedService.StartAsync` should be limited to short running tasks because hosted services are run sequentially, ...

Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by gklittlejohn** [comment]
Yes, I'll do this when I have time.
