### ISSUE TITLE
Blazor standalone WASM env variable config with CI/CD to Azure Apps

### ISSUE THREAD

**Issue by buzzluck68** [dotnet/AspNetCore.Docs#24041]
On the documentation page ([here](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-6.0#set-the-environment-for-azure-app-service)) instructing how to set the environments for Blazor WebAssembly applications, it has a note that if the application is standalone (not hosted), then these instructions do not apply.

Instead it recommends using a JS Initializer in conjuction with a build environment variable in the CI process, in order to get a specific environment as part of the build.  But it provides no instruction on how to accomplish this, and the link provided for JS Initializers is very generic, providing no real assistance regarding this scenario for developers new to web development such as myself.

Please provide environment "how-to" documentation for standalone Blazor WebAssembly applications, similar to what is provided for hosted Blazor WebAssembly applications, so developers of those applications will have the same CI/CD capabilities as the other Blazor developers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8bc6ab-a440-d860-e40c-8f18aa1eafb3
* Version Independent ID: 8a5b47e7-b29c-b049-30e8-5b405a5086b6
* Content: [ASP.NET Core Blazor environments](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @buzzluck68 ... I doubt that we can do that broadly and explicitly because there are so many CI build systems out there. However, we might be able to use one common system that MS would feel good about ... *cough* *cough* Azure Pipelines *cough* :smile: ... as an example and then it would serve as a general guide for others, especially as you suggest for the JS initializer piece.

@mkArtakMSFT to comment further on the feasibility of covering something. If so, what? If so, who? I've only dabbled lightly with CI over the years, so it might better for an experienced PU member to write it up. If me, I probably can work it out ... it will just take longer. Also note that my schedule is kind'a full with high priority work through the end of the year unless you let me know that this is a high priority item; in which case, I'd try to get it done within the next few weeks before *the holidays* 🎁⛄.

**Comment by buzzluck68** [comment]
Thank you @guardrex, using Azure Pipelines will be perfect for me, since that is what we are using for our CI builds and deployments.  If that is possible to get done, it will open the door for many of us using standalone Blazor Wasm to be able to have proper environments in Azure Web Apps.

**Comment by buzzluck68** [comment]
That is perfectly understandable, it has been a big year for all of you.

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up, @buzzluck68.
As @guardrex has pointed out, this is a very wide topic and we don't have a guidance which will fit all the cases perfectly. Hence, we're debating in the team whether we should come up with a feature to simplify this or not. We know that some community members have come up with their own solutions so it's doable for sure. If this is urgent, you can ask on [StackOverflow](https://stackoverflow.com) about ways to do it.

That said, we'll pause on this for now to see what should be our path forward on this based on our conversations as well as the feedback we receive from the community.

**Comment by buzzluck68** [comment]
Thank you mkArtakMSFT, I will see if StackOverflow has any good information on this already, and if not, then I will created a post myself. So far the results I have come across the past year or so have not worked for our situation.

**Comment by guardrex** [comment]
@buzzluck68 ... Did you make progress with this?

I tried setting an environment-specific JS initializer for the environment as Javier recommended ...

```js
export function beforeStart(options, extensions) {
    options.environment = "Staging";
}
```

Cross-ref: https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Platform/WebAssemblyStartOptions.ts#L16

... No 🎲🎲 ... it doesn't throw, but it doesn't work either. It does **_briefly_** seem to set the option, seen when reading it back to the UI using his [`BasicTestApp` JS initializer](https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/testassets/BasicTestApp/wwwroot/BasicTestApp.lib.module.js). However, it goes back to the environment set by the header `blazor-environment` when the app loads.

<img width="803" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/146551537-5759dffd-060a-45b9-b14f-5bf00b60cce2.PNG">

<img width="803" alt="Capture" src="https://user-images.githubusercontent.com/1622880/146551568-4add2df4-8251-4dbc-9bbb-926b8da5022f.PNG">

With `autostart` set to `false` in `wwwroot/index.html` ...

```
<script src="_framework/blazor.webassembly.js" autostart="false"></script>
```

... the app won't start, so there's no way to get our current guidance to work that pitches `Blazor.start({environment: "{ENVIRONMENT}"});` for `wwwroot/index.html` moved to `beforeStart` in the JS initializer.

**_Indeed!_** ... *Javier's recommendation is cryptic!* 😄

**Comment by buzzluck68** [comment]
@guardrex unfortunately no, I was not able to get anything to work. Similar to you, anything I tried to do either didn't make any difference, or it completely broke the Blazor client from starting up.  Since this is completely new territory for me (been a desktop developer for 20+ years, and just now getting into web), I am fairly certain I am missing critical pieces to this puzzle that I just don't understand and/or don't know I am missing.
I have not tried the JS initializer because I was not understanding anything about it so far, but I did try all the suggestions in the previous post, which all ended without success. Your post did provide me with some good information that I can work with to see if I can find anything else out, though, so that is definitely a plus!

**Comment by guardrex** [comment]
The engineering 🐈🐈🐈 are mostly out on vacations now through the end of the year. We'll need some help from Javier when he gets back to figure out the JS Initializer approach that he mentioned. It **_seems like_** 🤔 it would work along one of those approaches :point_up:, but I'm probably misinterpreting his suggestion. Rarely, he'll mention something that's just an idea. Since he had me place that text into the doc, I think he has a *real solution* in mind for this and that there just isn't enough guidance yet to implement it.

If you want to explore it further before he gets back, you could ping the community to see if anyone has a working approach or did interpret his remarks correctly for the use of a JS Initializer ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor) 

Otherwise, stand-by into '22. I hope we'll get an answer 🤞. I'll document whatever gets figured out here when we know for sure what to do.

**Comment by buzzluck68** [comment]
Thank you @guardrex, any official documentation about it that comes out in '22 would be awesome and greatly appreciated. But in the meantime, I'll reach out to see if anyone has any working implementations of this that can be tried.
Thank you again, you have been really helpful with this.

**Comment by tomadj** [comment]
Hello, 

I try to deploy standalone Blazor wasm application on many environments with azure devops pipeline.  

Did you make progress with this ? 

Thank's

**Comment by guardrex** [comment]
No new info yet @tomadj ... and the only issue that I see in the PU repo is ...

https://github.com/dotnet/aspnetcore/issues/25152

I can't say if that applies to your exact scenario. You'll have to read through all of the content there. For now ... while the PU works out what to do ... the doc issue here is **blocked**. I tried a few things that I thought Javier might be suggesting :point_up: https://github.com/dotnet/AspNetCore.Docs/issues/24041#issuecomment-996723081 ... but **no** 🎲🎲 ... I couldn't make it work.

You can reach out to devs on support forums to see if someone has a workaround in the meantime ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

If you find a modification to what I was doing ... i.e., along the lines of Javier's suggestion ... please do post back here what works, even if it's just a temporary hack. We might call something out temporarily in the article. At least, this issue is cross-linked to the live topic, so devs might find this issue (or I can point them to it).

I'm on stand-by for the PU to respond with further details on what they decide to do. 👂

**Comment by tomadj** [comment]
OK thank you @guardrex. 

[Maybe here a solution of @ViRuSTriNiTy](https://github.com/dotnet/aspnetcore/issues/28573#issuecomment-892831842)

I will try !

**Comment by guardrex** [comment]
I'm **_baaack!_** 🏃 I'm trying to close out backlogged issues.

In a non-CI/CD, non-Azure scenario, the guidance is correct for standalone WASM ... Use the manual code, along the lines of ...

```html
<script src="_framework/blazor.webassembly.js" autostart="false"></script>
<script>
    if (window.location.hostname.includes("localhost")) {
        Blazor.start({
            environment: "Staging"
        });
    }
    else {
        Blazor.start({
            environment: "Production"
        });
    }
</script>
```

... or set the environment var. The doc does call this out. **_However,_** I do want to make a small update to the doc's example to look more like what I just posted. I think the check on `localhost` is nice to show.

WRT Azure, that's a known pain point (apparently) for a number of devs and the PU. The issue for it in the PU repo is still open for work at ...

https://github.com/dotnet/aspnetcore/issues/25152

... and there are a few approaches for dealing with it explained by the community.

I can't cross-link that tho into the Blazor doc without leading to more unhelpful community complaints from angry devs 😠. The PU is well aware of the issue and the complaints. I'll keep the PU issue in mind so that I can respond to doc issues that pertain to environments and Azure.

Leave this open. It will close shortly when I touch up the doc in a few minutes.
