### ISSUE TITLE
I can't PUT "secret"

### ISSUE THREAD

**Issue by BOBOfra** [dotnet/AspNetCore.Docs#24110]
[EDIT by guardrex to add the metadata]

Before implement the TodoItemDTO class I've tested the Todo class adding the Secret field. As it turns out, I can get the secret field, and I can post it. But i can't PUT an already existent item in order to change the secret field. If i try to do it, only Name and isComplete fields changes, but Secret is still the same.
That's normal? How can I fix it?

Visual studio 2022, .NET 6.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@BOBOfra ... What topic are you looking at? I closed your earlier issue and asked because we need to triage this to the right doc author. When you open an issue using the **This page** feedback button and form, it adds metadata for tracking and pings the author. I can add it manually tho ... what topic are you looking at (provide the link)?

**Comment by Rick-Anderson** [comment]
Start debugging. No reason you can't PUT that field.
