### ISSUE TITLE
Tutorial does not work out of the box for me

### ISSUE THREAD

**Issue by taylormleigh** [dotnet/AspNetCore.Docs#24205]
This tutorial does not work out of the box for me.
I am unable to successfully build after the first steps adding the code to Program.cs. For example:

`using RazorPagesMovie.Data;`

throws an error for me.

if I create a folder called Data or comment out the line it solves the initial error, but then I run into an error with this line:

```
builder.Services.AddDbContext<RazorPagesMovieContext>(options =>
       options.UseSqlServer(builder.Configuration.GetConnectionString("RazorPagesMovieContext")));
```

If I comment it out it builds. However, moving forward I'm unable to successfully create a new scaffolded item or move through the tutorial in any meaningful way.

***Note:** I've started over from scratch several times, without altering any folder structure or anything. Still, every time I get to the very first step of adding code to Program.cs it prevents me from building.

The errors I am getting are:

```
'IServiceCollection' does not contain a definition for 'AddDbContext' and no accessible extension method 'AddDbContext' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)

The type or namespace name 'Data' does not exist in the namespace 'RazorPagesMovie' (are you missing an assembly reference?)

The type or namespace name 'EntityFrameworkCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

The type or namespace name 'RazorPagesMovieContext' could not be found (are you missing a using directive or an assembly reference?)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by taylormleigh** [comment]
Hmm, I've double and triple checked - I didn't skip any steps. Unless there was something that was implied that I was supposed to do but wasn't explicitly stated ?

**Comment by Rick-Anderson** [comment]
Create an app with individual user accounts and compare that to your code. 
![image](https://user-images.githubusercontent.com/3605364/146088563-7fda2bf3-7abc-4966-b49b-0035388bed51.png)

**Comment by taylormleigh** [comment]
The Program.cs file is totally different in that case! If I change the code per the first steps of the tutorial, I get build errors, but if leave the code as is I'm finally able to successfully "Add Scaffolded Item" without issue! 

The tutorial shows what the Program.cs file should look like after adding a scaffolded item, and out of curiosity I pasted that code into my Program.cs file and it actually builds just fine now, but the browser displays error message:
```
An unhandled exception occurred while processing the request.
InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.AspNetCore.Identity.IdentityUser]' has been registered.
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
```
Leaving the program file unaltered from the default, though, hopefully I can continue through the tutorial without problems! Thanks for your help! 

By the way, if you have any information/docs on why changing the authentication type had that effect please feel free to drop any links, as I am very curious about it. The tutorial specifically shows the authentication type as "none" so I never would have thought to play around with that!

**Comment by Rick-Anderson** [comment]
The authentication code is different, but it makes calls `AddDbContext`. 

Does you project file look like the following?

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
```

It's like you're missing `    <ImplicitUsings>enable</ImplicitUsings>`. That wasn't included in early prereleases.

**Comment by Rick-Anderson** [comment]
> if I create a folder called `Data`

You should start over. The scaffolder creates that folder. We have about 10,000 people/month tell us this works so we're confident it works (and we test too). 


> if I create a folder called Data or comment out the line it solves the initial error,

That's the wrong approach.

**Comment by Rick-Anderson** [comment]
You can also try the [Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio-code) instructions. You can still use Visual Studio, just run the commands in a command window.

**Comment by taylormleigh** [comment]
> The authentication code is different, but it makes calls `AddDbContext`.
> 
> Does you project file look like the following?
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk.Web">
> 
>   <PropertyGroup>
>     <TargetFramework>net6.0</TargetFramework>
>     <Nullable>enable</Nullable>
>     <ImplicitUsings>enable</ImplicitUsings>
>   </PropertyGroup>
> 
> </Project>
> ```
> 
> It's like you're missing ` <ImplicitUsings>enable</ImplicitUsings>`. That wasn't included in early prereleases.

The file looks exactly like the one you pasted, including the enabled ImplicitUsings. The one where I changed the Authorization to "Individual Accounts" also has UserSecretsId plus:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-RazorPagesMovie-7E09E493-57E7-4C84-AE5D-A90EC2CA9F7D</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.0" />
  </ItemGroup>

</Project>
```

**Comment by taylormleigh** [comment]
> > if I create a folder called `Data`
> 
> You should start over. The scaffolder creates that folder. We have about 10,000 people/month tell us this works so we're confident it works (and we test too).
> 
> > if I create a folder called Data or comment out the line it solves the initial error,
> 
> That's the wrong approach.

Yes I am well aware. That is why I started this issue.

**Comment by taylormleigh** [comment]
I can screen record a video of me setting up the project exactly as the tutorial says and it not working as soon as I get to step one?

I'm not doing anything to the files until the step asks me to paste the first block of code, I'm not "skipping a step." I haven't had any troubles with any of the other Blazor tutorials.

**Comment by idobrodushniy** [comment]
Hello @Rick-Anderson .

Just ended up with having the same issue Taylor described above and it looks like there is some confusion in this tutorial. (At least I have encountered it on MacOS, not sure whether Taylor used the same OS.)

Basically, in the doc [here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-6.0&tabs=visual-studio-code#programcs-2) it is mentioned:
"""
The following lines of code in this file create a WebApplicationBuilder with preconfigured defaults, **add Razor Pages support to the Dependency Injection (DI) container, and build the app:**
"""
Code from snippet ⬇️ 
```
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using RazorPagesMovie.Data;
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();

builder.Services.AddDbContext<RazorPagesMovieContext>(options => 
       options.UseSqlServer(builder.Configuration.GetConnectionString("RazorPagesMovieContext")));

var app = builder.Build();
```
As far as I understand, this tutorial was created for newcomers, therefore I don't think posting the whole snippet of the final file is a good idea at this step, since a person doesn't understand a single word yet. (This snippet I mentioned above isn't exactly what command `dotnet new webapp -o RazorPagesMovie` scaffolded. Doc is referring to the final state of the file from [here](https://github.com/dotnet/AspNetCore.Docs/blob/c7a879e00e0d3ee3edffe4afde935b1debcf8ec1/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie60/Program.cs#L11) I guess, while scaffolded `Program.cs` doesn't have those lines at all) 
If we wanna onboard newcomers, we would probably need to highlight specific lines of code they need to add in particular to `Program.cs` which was scaffolded by the command they had executed at the first step.

As a result of this confusion, people add both lines `builder.Services.AddRazorPages();` and `builder.Services.AddDbContext<RazorPagesMovieContext>(options => 
       options.UseSqlServer(builder.Configuration.GetConnectionString("RazorPagesMovieContext")));`, while `RazorPagesMovieContext` still doesn't exist, they are supposed to do it in the step 2.
       
That, I believe, is the moment when the mess begins in the tutorial:
In the step [two](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio-code#scaffold-the-movie-model), we ask people to run `dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries -sqlite`. 

** ⚠️  Since they had already added line referring to `RazorPagesMovieContext` in `Program.cs` because they were confused by snippet in step 1, it is gonna throw a build error that type/namespace doesn't exist during execution of model scaffolding command.**


Also, there is another mistake in doc I believe:
```
Open a command shell to the project directory, which contains the Program.cs, Startup.cs, and .csproj files. Run the following command:
```
I believe file `Startup.cs` isn't supposed to be there. (ofc, probably it is for Windows/Linux, but at least in my case I don't see it scaffolded after step 2, moreover I don't see this file in code samples repo - https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie60).

Please, lemme know if I was supposed to create a PR to fix docs instead of explaining this here, but I believe this is the reason why Taylor were getting errors during builds.

**Comment by Rick-Anderson** [comment]
> (This snippet I mentioned above isn't exactly what command dotnet new webapp -o RazorPagesMovie scaffolded. 

It is.

> I believe file Startup.cs isn't supposed to be there.
Fixed in #24205

**Comment by idobrodushniy** [comment]
@taylormleigh please let us know if things I mentioned above is an actual problem you faced.

**Comment by Rick-Anderson** [comment]
@taylormleigh  @idobrodushniy  Part 1 fixes will be live soon.  I reviewed part 2 when this was opened but it turned out the problem was the previous page. @idobrodushniy  thanks for reporting the problems came from part 1.

**Comment by taylormleigh** [comment]
> @taylormleigh please let us know if things I mentioned above is an actual problem you faced.

That looks to be exactly the problem, thank you so much for actually helping me!!!!

**Comment by Rick-Anderson** [comment]
Fixes are live.

**Comment by idobrodushniy** [comment]
Just checked and it seems much more clear now. Thank you @Rick-Anderson for this quick reaction!
