### ISSUE TITLE
Anchor links are broken

### ISSUE THREAD

**Issue by mshwf** [dotnet/AspNetCore.Docs#24275]
Please review and fix the anchor links:
for example: 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#jcp (find: "in this document for information on adding" among other occurrences)
Should be:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#json-configuration-provider-1

and:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#getvalue (find: "If a configuration value must be guaranteed")
Should be:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#getvalue-1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#add-configuration-from-an-external-assembly-1)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mshwf ... Currently, we store multiple versions of content in the same markdown file due to rapid framework churn as releases roll out. This results in duplicated headings, thus it leads to having these auto-numbered `id`s for bookmarks.

In 2022, we'll adopt a versioning system that places each version of a topic into its own markdown file. Therefore, there will be no duplicated headings and no auto-numbered `id`s.

We don't have an ETA for when the switchover will take place. It's just in the planning stage at this point. Until then, we don't plan to update individual cross-links in each doc. Most readers use the latest release.
