### ISSUE TITLE
docker healthcheck example fails due to curl missing

### ISSUE THREAD

**Issue by fusyd** [dotnet/AspNetCore.Docs#24341]
according to [this](https://github.com/dotnet/dotnet-docker/issues/2379), `curl` is not included in runtime docker images, therefore the example docker healthcheck command will always result in `unhealthy`.

```
HEALTHCHECK CMD curl --fail http://localhost:5000/healthz || exit
``` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0#docker-healthcheck)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mthalman should we remove [**Docker HEALTHCHECK**](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0#docker-healthcheck)

@fusyd  thanks for reporting.

**Comment by mthalman** [comment]
@Rick-Anderson - I don't think the HEALTHCHECK content necessarily needs to be removed. It does need to be revised given that curl is no longer included by default. As I see it, there are three options available for sending HEALTHCHECK requests:
1. Use a web request tool that is included in the aspnet base image. Now that curl is no longer included by default in the .NET Linux container images, some of these images have no existing tool to make a web request. However, in the case of the .NET container images based on Alpine Linux, [wget](https://www.gnu.org/software/wget/) can be used because it is included by default in the base Alpine container images. This is likely sufficient for most people that are using Alpine.
2. Explicitly install the necessary Linux package that adds the tool. If curl is desired, it's just a matter of installing the curl package in the Dockerfile.
3. For those that are concerned about installing additional packages, the last remaining option would be to author your own tool that just relies on the packages that are already included by the aspnet container image. For example, you could author a simple .NET app uses `HttpClient` to send the health check request to your service and include that app in the container image.
