### ISSUE TITLE
Missing connector to an actual OIDC server

### ISSUE THREAD

**Issue by Rhywden** [dotnet/AspNetCore.Docs#24374]
This page is all fine and well but it's missing one detail: How to connect to an actual, real-world and existing OIDC-Server which is not running on localhost.

It would be even greater if you could implement a **general** OIDC-page and not one which is so tightly coupled to Identity-Server.

Also, regarding this part:
```
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlite(
        Configuration.GetConnectionString("DefaultConnection")));
```
It should be mentioned here that for `options.UseSqlite()` you need to install the NuGet Package Microsoft.EntityFrameworkCore.Sqlite and that for `Configuration` to work you need to do `var Configuration = builder.Configuration;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
### 🍂 **_OOF for the holidays_** 🍂

This issue has been marked for triage on the Blazor.Docs project, and I'll respond as soon as I return in 2022. I'll be back working on issues around Wednesday, Jan. 5. It will take a little while to dig out ⛰️⛏️ from holiday issues. I'll get back to you *ASAP* 🏃. 

We only work on documentation on this repo. If you need product support, close this issue and seek assistance through one or more of the following support channels:

* [Stack Overflow (tagged: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [General ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

If you think that you found a potential bug in the framework or have product feedback, close this issue and open a new issue for the ASP.NET Core product unit at [dotnet/aspnetcore issues](https://github.com/dotnet/aspnetcore/issues). Bug reports require a clear explanation of the problem, usually including a minimal repro project placed on GitHub for the product unit engineers to download and run. If you determine with the product unit that it isn't a bug but merely requires documentation, please re-open this docs issue and place a cross-link to your engineering issue discussion. I'll take it up with you when I return from vacation.

For problems or feedback on Visual Studio or Visual Studio for Mac, close this issue and use the [**Report a Problem**](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) or [**Suggest a Feature**](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) processes from within VS, which open internal issues for VS teams. For more information, see [Visual Studio Feedback](https://developercommunity.visualstudio.com/home) or [How to report a problem in Visual Studio for Mac](https://docs.microsoft.com/visualstudio/mac/report-a-problem).

For problems with Visual Studio Code, close this issue and ask for support on community support forums. For bug reports and product feedback, open an issue on the [microsoft/vscode GitHub repo](https://github.com/microsoft/vscode/issues).

💃🕺🥳 **_Happy New Year!_** 🎈🎆🍾🥂🎉 **_See you in 2022!_**

**Comment by guardrex** [comment]
Hello @Rhywden ... Ok, I'm back and responding to issues opened over the holidays. Your suggestions are a duplicate of an existing issue in part and aren't actionable in part ...

* WRT connecting to a general page, the guidance is in the article ...

  https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library

  Noting that ...

  * These aren't security framework/feature articles. They're merely *How-To* / basic info articles. Blazor authn/authz is based on working group specification docs and MS framework articles in other doc sets, especially MS Identity security docs for MS-provided frameworks. We cross-link for further details, and the external docs should be accessed by devs looking to work with OAuth 2.0, OIDC, and MS Identity.
  * We've been asked to adopt more specific Blazor guidance with one or more specific OAuth 2.0 frameworks. The product unit ("PU") management has resisted the request and said thus far that we won't take it on. There are many official and unofficial docs and blogs on the Net to support various OAuth 2.0 frameworks and services. The PU doesn't want to take on the cost of duplicating good content that can be found elsewhere, and we really don't have the staffing here to support it anyway. If you want to discuss the subject with devs and get additional info beyond what we cross-link, we recommend chatting with the community and checking Awesome Blazor: [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor), [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/), [Blazor Gitter](https://gitter.im/aspnet/Blazor), [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor).
  * For the one specific external OAuth 2.0 framework that we do cover (and indeed, it's only a basic, introductory level of coverage ... we do get issues asking for more coverage) ... *Identity Server* ... specifically *Duende IdS* ... that's management's choice and recommendation. They set the depth of our coverage where you see it today and don't want to get into further advanced coverage or into covering other frameworks at this time. Again, we recommend consulting with external docs and the community for other frameworks.

* WRT SQLite, enhancing the content to call out namespaces, updates for Minimal APIs (since these mini-tutorials are based on project templates that now adopt them by default), and any missing, required code ... it's a duplicate of an existing issue to update the entire node of Blazor *Security and Identity* topics at https://github.com/dotnet/AspNetCore.Docs/issues/19286. If you scroll down to the *UE pass tracking* section, you'll see that this whole node couldn't be reached in 21H1 ... I had to stop working on these "user experience" passes in favor of the .NET 6.0 release docs. Now, we've mostly put the 6.0 work in the rear-view mirror (see the [6.0 docs tracking issue](https://github.com/dotnet/AspNetCore.Docs/issues/22045) and scroll down to the tables at the bottom of the opening comment). The 🐘 in the room on https://github.com/dotnet/AspNetCore.Docs/issues/19286 is the security set of docs, and it's something that I hope management will continue to support for work in 22H1. I'll endeavor to fully overhaul and update the entire node by the end of June. If I'm still working here in 22H2, I'd then need to drop UE passes at that point in favor of the upcoming .NET 7.0 release at the EOY. The reason I mention the possibility of not finishing by June is that you've probably heard of .NET MAUI by now ... and .NET MAUI coverage could take quite a bit of time and effort. It will take priority over all UE passes, and it could disrupt an overhaul of the security node by June.

Thanks for writing in. I hope I was able to address your concerns. I **_DO_** want to get at least the 2nd part of your ask addressed. As for the first part, I doubt they'll take on a greater scope given the workload, but I think you'll be happy to see a growing amount of quality guidance on the Net ... Blazor is becoming quite popular! 🎉

**Comment by Rhywden** [comment]
Yeah, the _guidance_ is in the articles but it's only a very rough outline. I actually was only able to figure out where the problem was actually lying because I overrode some part of the authentication routines - because the SignalR server was simply silently swallowing all authentication issues even when set to "debug" log level. It simply did not work and did not give any indications as to why.

Because it turns out that for Keycloak to work you merely need to add this one little line to the options:

```
options.Audience = "ForExampleYourAppIdHere";
```

and then of course set Keycloak to provide this audience property in its JWT as well.

So, the underlying issue was not so much a "Cannot get this to work" than more of a "The Server does not provide enough clues even when in production and at debug log level". I can understand if such error / warning messages are dropped when in production but in development it **really** should provide such hints.

**Comment by guardrex** [comment]
That's cool ... I don't disagree ... cryptic or missing errors are a pain point 😡. It's more of a product unit issue to improve the error message/logging behavior than a docs issue. **_Which product unit tho?_** Is Keycloak doing something unusual with their response, or is .NET not revealing something that it should via framework logging? I think you could ask the product unit about it. If you open an issue there, I recommend as much clear detail as you can provide on the behavior of the Keycloak server and the logging that you're seeing ...

https://github.com/dotnet/aspnetcore/issues

They might redirect you tho to another team or to Keycloak ... or even just to the community. They have limited resources, so they might not be able to help much with something that doesn't directly pertain to ASP.NET Core framework API.

> And, by the way, I contest that there are many blogs and articles about this.

I can only relay management's position generally. What we have here today is all that they can support at the moment, but I think they agree with my suggestion that the entire node could use a *total overhaul and update*. What little that we do cover here (and cross-link) on OAuth 2.0/OIDC specific to Blazor can be improved. I'll try to make that happen with their blessing 🙏😄.
