### ISSUE TITLE
Update VS guidance

### ISSUE THREAD

**Issue by genifycom** [dotnet/AspNetCore.Docs#24523]
"Select Individual User Accounts with the Store user accounts in-app option to use ASP.NET Core's Identity system. This selection adds authentication support and doesn't result in storing users in a database. The following sections of this article provide further details."

There is no such option. There is only "Individual Accounts"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985b834f-534a-aba6-80a0-d8845adbfc25
* Version Independent ID: d2b5a556-82a4-e939-be68-2357a3d4408f
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
They changed the UI for the latest release of VS. The **Store user accounts in-app** option has been removed. The UIs of both VS and the Azure portal change regularly and without warning. I must walk doc myself, usually while working on something else, or have a UI change pointed out to me, as you have here, in order to catch them. I'll update this right now.
