### ISSUE TITLE
lifecycle diagram is misleading regarding SetParametersAsync

### ISSUE THREAD

**Issue by pm100** [dotnet/AspNetCore.Docs#24522]
It suggests that SetParamtersAsync is only called on first render (In fact it shows it quite clearly). This is not correct, params are set on every render

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Razor component lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#when-parameters-are-set-setparametersasync)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @pm100 ... The diagrams and text were provided by the framework engineers and signed off by management. I think this is going to come down to a clarification on "first render" versus "rerender." I'll schedule this for the product unit to take a look, along with an existing issue on this topic for an unrelated aspect of lifecycle processing. I'll wait a week ... several of the product unit engineers are only back a few days from the holiday break. *They're no doubt buried in email at the moment* ⛏️⛰️📧😅.

**Comment by guardrex** [comment]
**UPDATE (1/19)**: I'll be inquiring with the PU at the end of the week on issue triage. This will be addressed *ASAP*.

**Comment by guardrex** [comment]
**UPDATE (3/7)**: @pm100, I've asked twice offline about this, but I'm not getting a response. It could be because the product unit is just too crazy busy at the moment to respond here ... or they're missing my messages in a **_VAST SEA_** 🚢 of messages that they get daily over there. You'll probably have better luck asking directly on their repo and adding me as a ping to your issue there.

Open an issue on their repo at ...

https://github.com/dotnet/aspnetcore/issues

Provide the cross-link to the section of the doc that has the diagram that you're referring to ...

https://docs.microsoft.com/aspnet/core/blazor/components/lifecycle#lifecycle-events

... with your remark/question ☝️ from your opening comment here.

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/24522
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.

Be prepared tho for Steve or Javier to say that the framework is way more complicated than what a simple diagram can show. Steve has said that at least once when we were working on updates to this topic's content and diagrams ... and we've made updates here about three times I think over the years. What you see here today is what they're happy with AFAIK. However, your question might prompt them to add something.
