### ISSUE TITLE
Disposing Scoped Services in Blazor

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/AspNetCore.Docs#24534]
In this page, it is said that:
"When a circuit ends because a user has disconnected and the framework is cleaning up the circuit state, the framework disposes of the circuit's DI scope. Disposing the scope disposes any circuit-scoped DI services that implement System.IDisposable."
Does this quote is correct? 
I think, every scoped service should be disposed and IDisposable only required for unmanaged codes. Am I wrong?
Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0969556b-b77e-bdb8-8e20-fd6971be0c25
* Version Independent ID: d17e4c28-ea82-0dd8-295d-19f6ada147ea
* Content: [ASP.NET Core Blazor SignalR guidance](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @abdollahkahne ... Yes, the text is correct. The remark doesn't specify anything about what the developer implemented `IDisposable` for. It just states that for whatever circuit-based services are disposable, they will be disposed when the circuit is cleaning up. This has to be distinguished from HTTP-request-based services that are scoped because they continue to work the same way ... recreated per HTTP-request and not per circuit. For more information, see the Blazor Server remarks for Scoped services in the table at ...

https://docs.microsoft.com/aspnet/core/blazor/fundamentals/dependency-injection#service-lifetime

Let's do this for this issue ... I'd like to make that cross-link in the topic. Leave this issue open, as it will close automatically when the PR merges. Thanks for commenting on the article.
