### ISSUE TITLE
Blazor Security node Azure portal guidance updates

### ISSUE THREAD

**Issue by OliverRC** [dotnet/AspNetCore.Docs#24594]
I have followed this article in detail and gone through it with a fine-toothed comb but I cannot find where I am going wrong.
I've done it 3 times over and cannot get the login to work.

I get the error:

````AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type.````

Some things I have noticed are strange. 

1. I am on an unverified published domain however my Application ID URI defaults to the format `api://{CLIENT APP CLIENT ID}` not https://

I am building on the .NET 6 in Visual Studio 2022

````dotnet --version 6.0.101````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3039ff79-ee86-20b1-0082-d3899a84c823
* Version Independent ID: af4a3a75-ae52-5f6d-2120-737bc2fefb07
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-6.0#server-app-configuration)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by OliverRC** [comment]
So it turns out that the article is incorrect in the setup of the Client App Registration. 

One needs to select **Single Page application (SPA)** when creating a new Client App Registration.
Or you need to configure the App Registration to use **Authentication** blade -> **Add platform** -> **Single-page application**

**Comment by guardrex** [comment]
Hello @OliverRC ...

> I am on an unverified published domain however my Application ID URI defaults to the format

It's covered in the article in a purple NOTE box. See that NOTE for more info.

As for the steps guidance that you pointed out, it doesn't surprise me. I've often joked that the Azure portal UI changes every *7.5 minutes!* 😆 ... Of course, I don't mean that literally. It changes quite a bit as they make regular improvements. We don't get advanced notice on such changes here. We often find out when a reader writes in to say that a topic doesn't match what's shown or when we're walking a topic's steps for other reasons ... to update other things ... and then notice that it has changed.

I'll work on this first thing tomorrow (Friday) morning ... and include checking on the Azure portal UI for the rest of the topics. Thanks for writing in on it.

**Comment by OliverRC** [comment]
Hi @guardrex 

If you are referring to the following note, then this is why I raised it as strange. The article implies that if you are on an unverified publisher domain that the App ID Uri will default to something in the `https://contoso.onmicrosoft.com/41451fa7-82d9-4673-8fa5-69eff5a761fd/API.Access` format, which in my experience it does not. 
It still defaults to the typical `api://41451fa7-82d9-4673-8fa5-69eff5a761fd/API.Access` and everything works 100% like this as long as the Authentication platform is setup for SPA.

![image](https://user-images.githubusercontent.com/1888486/149329668-df94a924-1e1e-48d7-8ac3-ac6e2ae3b976.png)

**Comment by guardrex** [comment]
I'll have to check further on that. What the NOTE says was true in prior years. There were a number of issues opened on the subject of these scope values. I created apps under both trusted and untrusted publisher domains, and this was (at the time) the way that app registrations were configured. Azure ... I'm sure you know ... changes **_fairly regularly_** over time. They're constantly making improvements. They know when devs are having trouble from issues and feedback and then they set about trying to improve things. This business of the API scope for trusted versus untrusted scopes has clearly been a pain point: We had several issues opened here, and they probably have had a number of other issues on it elsewhere. I couldn't even figure out the reason why these alternative scopes existed until Jean-Marc (of the Azure docs repo ... he's a sort of Azure/security pro over there who writes a lot of the Azure tutorials) ... he explained it out to me at the time.

This whole node of the Blazor docs is up for a total overhaul on https://github.com/dotnet/AspNetCore.Docs/issues/19286. I might be addressing some issues separately before overhauling entire topics in this node, but I need to check with management first. Early on, there were no Blazor-Azure docs in the Azure docs repo. Now, there are such articles. We have duplicate coverage now. I think management is interested in dropping the duplicate coverage in favor of devs using the Azure docs to cover these Blazor scenarios. If so, this topic and the other Azure articles in this node will be deleted. The URLs will be redirected to the Azure articles. I should learn what they want to do within a couple of weeks.

In the meantime, I'll take a look. These should be fairly *quick-ish* updates to make if things have changed. If they're quick, I'll take care of it now-ish 😄. (Notice how I have to qualify everything around here when it comes to timelines. LOL ... The 🧀 can move quite a bit on issue priorities. 😄) If the updates look like they would take a larger hunk of time, then I need to hear back from management first on possibly dropping these articles entirely.

Leave this issue open for now. It will close after I hear back or when a PR merges later. Thanks again for pointing out these deltas for the doc versus the portal.

**Comment by guardrex** [comment]
@OliverRC ... I can't repro the scenarios that you describe ...

1. WRT the App ID URI, my untrusted publisher domain yields the `https://`-prefixed scope ...

   <img width="363" alt="Capture" src="https://user-images.githubusercontent.com/1622880/149511241-206ccef6-67e2-468e-965c-f73d7a1295d1.PNG">

   Although I'm not going to check it, I'm fairly confident if I switch over to one of my trusted pubs that I'll get the `api://` prefix. It was always that way, and I don't think they would change that. I was more concerned about them changing the process in some way for the untrusted scenario. That's what seemed the most strange to me from the beginning. I expected `api://` as a general prefix but was shocked initially at `https://`. One thing that Jean-Marc didn't explain to me at the time was **_exactly why_**. I'm sure that there is a sound reason for it. I just don't know what it is. There's a cross-linked doc for trusted/untrusted publisher domains, but I didn't think it even explained exactly why the scheme changes.

1. On the second part WRT SPA, the topic's guidance is to ...

   > Set the Redirect URI drop down to Single-page application (SPA) and provide the following redirect URI: https://localhost:{PORT}/authentication/login-callback.

   ... which yields the correct SPA registration ...

   <img width="310" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/149511402-86706a71-60ec-44f9-9af7-30363c41bf00.PNG">

Admittedly, I can't really walk the entire topics at this time. However, the screens haven't changed much. I did spot a tiny NIT in one of the instructions for one of the drop-downs. They don't default to **Web** for **Select a platform** for the **`Server`** registration, but the article does tell devs that that's what they should select. The rest of it matches (I think ... I'm going kind'a quick 🏃 here ... a quick look 👁️). Anyway ... I need to consult with management on **_if we're even going to keep this topic_** in this doc set because Jean-Marc has nice resources over in the Azure docs. They may decide that we can drop these articles now and redirect over to those articles. If so, we wouldn't expend 💰 **_Hunter's Treasure_** 🏴‍☠️ maintaining this doc.

I don't have anything to change thus far based on the discussion. I'll leave this open for a sec in case you have any other remarks to add, but I think we'll end up closing this as a won't-fix and leaving the overhaul effort for #19286. I will make a number of changes and improvements to the doc if we keep it, including the little Azure portal UI updates, but it doesn't look like there's a significant doc 🐛 bug at the moment to squash.
