### ISSUE TITLE
14th January Not Working

### ISSUE THREAD

**Issue by newNoobie1** [dotnet/AspNetCore.Docs#24610]
On 14th Jan 2022 it is not working. The error i ger is on this line   hubConnection = new HubConnectionBuilder() where hubconnectionbuilder is not found. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097456af-6293-8c24-3991-fc815b94dcbf
* Version Independent ID: 978264ac-18f8-e937-30db-7050e53ac7d1
* Content: [Use ASP.NET Core SignalR with Blazor](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio&pivots=webassembly)
* Content Source: [aspnetcore/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @newNoobie1 ... Since the namespace that contains the extension method is present, this is likely only caused by the `Microsoft.AspNetCore.SignalR.Client` package not being added to the client project. Double check that you followed that step ...

https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio&pivots=webassembly#add-the-signalr-client-library

**Comment by newNoobie1** [comment]
I think i got the namespace name differently thats why it searches for another name instead of _BlazorWebAssemblySignalRApp.Server.Hubs_
