### ISSUE TITLE
Documentation does not work.  

### ISSUE THREAD

**Issue by RobertFinger** [dotnet/AspNetCore.Docs#24717]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097456af-6293-8c24-3991-fc815b94dcbf
* Version Independent ID: 978264ac-18f8-e937-30db-7050e53ac7d1
* Content: [Use ASP.NET Core SignalR with Blazor](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio&pivots=server)
* Content Source: [aspnetcore/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by RobertFinger** [comment]
System.InvalidOperationException: 'Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddSignalR' inside the call to 'ConfigureServices(...)' in the application startup code.'

**Comment by guardrex** [comment]
Hello @RobertFinger ... I'm not seeing a problem here with 6.0. Are you saying that you're trying to use the tutorial for 5.0? If so, then you'll need to use the doc version selector to select the 5.0 version of the topic ...

<img width="622" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/150695249-27c84273-1806-4ae1-b482-5ac4124f3539.PNG">

As for the current (6.0) guidance, it looks good here ...

<img width="458" alt="Capture3" src="https://user-images.githubusercontent.com/1622880/150695126-45d9a11d-3b56-4ec2-a02c-e028d78acd68.PNG">

Edge ...

<img width="527" alt="Capture" src="https://user-images.githubusercontent.com/1622880/150695135-efba2cb3-cf41-40b0-af8b-929e28711cee.PNG">

FF ...

<img width="526" alt="Capture2" src="https://user-images.githubusercontent.com/1622880/150695141-dfb03b82-d6fe-4a8e-b761-d10aa53762f9.PNG">


If you're hitting a bug or strange behavior, open an issue for the product unit for investigation at ...

https://github.com/dotnet/aspnetcore/issues

Add the following to the bottom of your opening comment so that I can follow along. If we need to make updates to the doc, then I'll re-open this issue and work it from there.

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/24717
```
