### ISSUE TITLE
Description of "Default Caching" Functionality?

### ISSUE THREAD

**Issue by taylorchasewhite** [dotnet/AspNetCore.Docs#24748]
I've read through a number of Docs, GitHub issues and StackOverflow questions but I have not been able to identify the logic for caching (DLL caching I suppose to be more specific) in Blazor. 

My overall feedback (in the form of a request) is to put a description of how to cache-bust the cached runtime DLLs? In the below passage, you mention the default behavior of caching the .dll & .wasm files, but I don't know what that behavior is:

> `BlazorCacheBootResources` also disables Blazor's default behavior of caching the .dll, .wasm, and other files based on their SHA-256 hashes because the property indicates that the SHA-256 hashes can't be relied upon for correctness. Even with this setting, the browser's normal HTTP cache may still cache those files, but whether or not this happens depends on your web server configuration and the cache-control headers that it serves.

Essentially, if I publish / deploy a new version of the application, what is the mechanism to trigger redownload of the runtime code (.wasm/.dll)s. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#troubleshoot-integrity-powershell-script)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @taylorchasewhite ... After confirming that an issue hasn't already been created (open **_or closed_** ... search both), open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

I don't think that the remark is too cryptic ... browsers are going to honor cache-control headers. Fine. Your question is an excellent follow-up: What does the PU recommend for cache-busting approach(es)? Can we enhance this coverage with further guidance on it?

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/24748
```

... to the bottom of your opening comment so that I can follow along. Normally, I close these until I hear their response. In this case tho, I'm almost certain that we can improve the guidance. I'll set it up as a P2 - Medium Priority issue for the time being. I'll take care of this if you'll add my ping line ☝️ to your opening issue over there ... or if you find an existing open issue that you can comment on (add me to your comment). They might already be planning something. I'd like to follow that if you find such an open issue.

**Comment by taylorchasewhite** [comment]
Sounds good--I will take these steps. Thanks Luke!

**Comment by guardrex** [comment]
That's perfect. I think that they'll provide helpful guidance 🤞, then I'll likely be able to turn it into a doc update. I'll keep an 👁️ on it, and you can let this docs issue close automatically when the docs PR merges later.

**Comment by taylorchasewhite** [comment]
Sounds good, thanks!

**Comment by guardrex** [comment]
Ok ... that's what Javier recommends. I'll see if I can work something up from his notes on the PU issue. I'll get to this as soon as I can, but it could take anywhere from a few weeks to a few months given the workload. Until then, this open issue is available to doc readers from the "View all page feedback" link at the bottom of the topic. Thanks for asking about this scenario.

**Comment by taylorchasewhite** [comment]
For sure! Thanks @guardrex -- I'm going to deep dive through the comments on that other thread and I'll post back if I figure anything else out. Thanks!
