### ISSUE TITLE
Checkbox interaction slow, even with 400+ rows

### ISSUE THREAD

**Issue by Grandizer** [dotnet/AspNetCore.Docs#24745]
Great article! Totally improved the UI scrolling no matter how many rows I have.
However, I have a 16 column table where 2 columns have check boxes and 2 columns have text boxes. There are 4 types of "rows" which show different things in these columns. My main question is, even when I only have 416 rows and then click a checkbox, it takes 1 second to show the change. This is totally compounded when there are many other rows. My main reason for virtualization is because many times, there will be thousands of rows.

So my question is, is there something I can do to improve the interaction speed?
Alternate question, it was initially designed to collapse and expand "child" items (because this is a hierarchical set of data but tree view clearly cannot work since we have more columnar data. But, with virtualization, when I collapse a set, the items disappear as they should but the space they took up still exists and is thus blank.

```
<Virtualize ItemsProvider="LoadMeasurements" Context="measurement" ItemSize="40">
  <ItemContent>
    <tr class="@RowColor(measurement)" @key="measurement.UniqueId" height="40px">
      @if (measurement.IsVisible)
    {
      <!-- Visgrade columns -->
      @if (measurement.RecordType == MeasurementRecordTypes.Visgrade)
      {
        <td class="text-center">
          <div @onclick="() => SwapVisgradeExpansion(measurement)">
            @if (measurement.IsExpanded)
            {
              <Icon Name="IconNames.Minus" Title="Collapse this Visgrade" height="16" />
            }
            else
            {
              <Icon Name="IconNames.Plus" Title="Expand this Visgrade" height="16" />
            }
          </div>
        </td>
        <td class="text-center">
          <button type="button" class="btn btn-sm btn-link p-0" @onclick="() => SwapVisgradeInclusion(measurement)" title="Include/Exclude All Measurements in Claim">
            <Icon Name="@VisgradeIconState(measurement)" />
          </button>
        </td>
        <td>
          <button type="button" class="btn btn-sm btn-link p-0 text-danger" @onclick="() => DeleteVisgrade(measurement)" title="Remove this Visgrade">
            <Icon Name="IconNames.Trash" Title="Remove this Visgrade" />
          </button>
        </td>
        <td>@measurement.VisgradeSource @measurement.VisgradeName</td>
        <td colspan="12">
          @if (measurement.IsExpanded)
          {
            <button type="button" class="btn btn-sm btn-outline-success" @onclick="() => { addTestsToVisgradeId = measurement.Id; addChildTestsToTestId = 0; ImportTestsModal.Open(); }">
              <Icon Name="IconNames.Plus" height="16" />
              Import Tests
            </button>
            <button type="button" class="btn btn-sm btn-outline-success ms-3" @onclick="() => { addTestsToVisgradeId = measurement.Id; addChildTestsToTestId = 0; AddTestsModal.Open(); }">
              <Icon Name="IconNames.Plus" height="16" />
              Add Additional Tests
            </button>
          }
        </td>
      }
      <!-- Test columns -->
      @if (measurement.RecordType == MeasurementRecordTypes.Test)
      {
        <td colspan="4"></td>
        <td class="text-center">
          <div @onclick="() => SwapTestExpansion(measurement)">
            @if (measurement.IsExpanded)
            {
              <Icon Name="IconNames.Minus" Title="Collapse this Claim" height="16" />
            }
            else
            {
              <Icon Name="IconNames.Plus" Title="Expand this Claim" height="16" />
            }
          </div>
        </td>
        <td class="text-center">
          <button type="button" class="btn btn-sm btn-link p-0" @onclick="() => SwapTestInclusion(measurement)" title="Include/Exclude All Measurements in Claim">
            <Icon Name="@TestIconState(measurement)" />
          </button>
        </td>
        <td>
          <button type="button" class="btn btn-sm btn-link p-0 text-danger" @onclick="() => DeleteTest(measurement)" title="Remove this Test">
            <Icon Name="IconNames.Trash" Title="Remove this Test" />
          </button>
        </td>
        <td style="max-width: 12vw; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
          <Icon Name="@Utilities.GetTestTypeIcon(measurement.TestTypeName)" Title="@measurement.TestTypeName" height="20" class="me-2" />
          @TestsNameDisplay(measurement)
        </td>
        <td colspan="8">
          @if (measurement.IsExpanded)
          {
            <button type="button" class="btn btn-sm btn-outline-success ms-3" @onclick="() => { addTestsToVisgradeId = 0; addChildTestsToTestId = measurement.Id; AddTestsModal.Open(); }">
              <Icon Name="IconNames.Plus" height="16" />
              Add Additional Child Tests
            </button>
          }
        </td>
      }
      <!-- Child Test columns -->
      @if (measurement.RecordType == MeasurementRecordTypes.ChildTest)
      {
        <td colspan="8"></td>
        <td class="text-center">
          <div @onclick="() => SwapChildTestExpansion(measurement)">
            @if (measurement.IsExpanded)
            {
              <Icon Name="IconNames.Minus" Title="Collapse this Test" height="16" />
            }
            else
            {
              <Icon Name="IconNames.Plus" Title="Expand this Test" height="16" />
            }
          </div>
        </td>
        <td class="text-center">
          <button type="button" class="btn btn-sm btn-link p-0" @onclick="() => SwapChildTestInclusion(measurement)">
            <Icon Name="@ChildTestIconState(measurement)" />
          </button>
        </td>
        <td>@measurement.TestDescription (@measurement.TestName)</td>
        <td colspan="5"></td>
      }
      <!-- Marker columns -->
      @if (measurement.RecordType == MeasurementRecordTypes.Marker)
      {
        <td colspan="11"></td>
        <td class="text-center"><input type="checkbox" class="form-check-input me-0" title="Include in Claim" checked="@measurement.IncludeInClaim" @onclick="() => IncludeInClaimSwap(measurement)" /></td>
        <td class="text-center"><input type="checkbox" class="form-check-input me-0" title="Include in Program Map" checked="@measurement.IncludeInProgramMap" @onclick="() => IncludeInProgramMapSwap(measurement)" /></td>
        <td>@measurement.MeasurementName (@measurement.MarkerName)</td>
        {
          var editable = EditableLimits(measurement);
          <td><input type="text" class="form-control form-control-sm" disabled="@(!editable)" @bind="measurement.LowerLimit" @oninput="(e) => AlterLimit(true, measurement, e)" /></td>
          <td><input type="text" class="form-control form-control-sm" disabled="@(!editable)" @bind="measurement.UpperLimit" @oninput="(e) => AlterLimit(false, measurement, e)" /></td>
        }
      }
    }
  </tr>
</ItemContent>
<Placeholder>
  <tr><td colspan="16">Please wait...</td></tr>
</Placeholder>
</Virtualize>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f4ab8b4-4d2e-9e1b-793e-dbb17f6d694d
* Version Independent ID: 26ed2425-63ec-e206-edcb-e51f17edb844
* Content: [ASP.NET Core Blazor component virtualization](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/virtualization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/virtualization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Grandizer ... That's good news on the first part. WRT your questions, we only work on the docs here and don't have the staffing to provide product support. We're just about buried in docs issues most of the time ⛰️⛏️😅. We recommend in a situation like this where you're working with improving performance for a given app's UI (and not really reporting a bug in the framework) that you **_first_** take it to the community for discussion. We recommend the usual spots ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

After that and your own further investigation, you may end up feeling that the lag in the UI and/or the spacing problems with the `Virtualize` component really shouldn't be present ... that perhaps there really is a bug (or multiple bugs 🐛🐛) haunting you. In that case, then open an issue for the product unit for investigation at ...

https://github.com/dotnet/aspnetcore/issues

They will need a minimal repro project put up in GH for them to pull down and test. Screenshots and relevant code are useful in the opening comment to explain/show what you're doing and what the problems are. Bascially, try to make it as easy as possible for them to understand exactly what's going wrong.

If you end up opening an issue with them, please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/24745
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say. Sometimes, they're like, 'Oh! It will work if you just make this one line change.' Those types of gotchas 😈 are often easy to call out in the doc if they look like they might be happening to many devs. I'll keep an 👁️ on your issue if you open one. Still tho, I think chatting with the community first is the best course of action. Besides perhaps this just being an approach problem that the community can address and not related to a real bug or feature request, you might get a much faster response on SO or a chat.

**Comment by guardrex** [comment]
One other quick note on PU contact. Make sure that you search open **_AND CLOSED_** issues for similar reports. They may have provided info to someone else that solved one or both of your problems, or they may have an open issue with exactly the same problem ... in that case, you'll see when/where they are in the investigation.
