### ISSUE TITLE
SignalR Blazor turorial

### ISSUE THREAD

**Issue by georgait** [dotnet/AspNetCore.Docs#24740]
Describe the bug
I have copied this sample https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr-blazor/samples/5.x/BlazorServerSignalRApp and i can't compile it properly. Everytime i run it i get back this exception: System.ObjectDisposedException: 'Cannot process pending renders after the renderer has been disposed.
ObjectDisposed_ObjectName_Name'. This exception was originally thrown at this call stack:
[External Code]
Messenger.Pages.Index.OnInitializedAsync.AnonymousMethod__5_0(string, string) in Index.razor
[External Code]

If i run it in release mode it works fine. Am i missing something or it's a bug?

**Comment by guardrex** [comment]
Hello @georgait ...

When you open an issue for us, please use the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**... and WRT to the error,** I haven't seen that one for this sample app. Yes, open it for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/24740
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.
