### ISSUE TITLE
Using Services in RCL (Razor Class Library)

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/AspNetCore.Docs#24889]
A matter that I encounter personally and may need more description (to make it more clear and standard) is using Services in Razor Class Library(RCL). 
To use them in components inside the RCL, we should add them to services. Using services may not be a good practice since developer should have an assumption that they get registered in main app that uses the component but It helps in case of developing RCLs for personal use specially. For example consider the class of` ExampleJsInterop.cs` inside template RCL which requires adding to services to use it in Component1.razor.

Another issue, which is not very related to this but I think it requires clarification too, is adding services for pre-rendering in hosted web assembly. For example in case of `HttpClient` in the template example (Weather Forecast) and also other services we made through the documentation, it throw an error in case of pre-rendering if they do not added to both of `Client` (Which is used in Web Assembly Host) and `Server` (Which is used in Web Host). I think this is also true for configuration to add them in both of assemblies. 

At the end, Thanks to your full responding to issues always and I feel not easy about multiple issue creation. I do not know any other tool for sharing my ideas about the documentation. If it is annoying please let me know. Thanks again

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b709f5-e04e-fee3-7eea-1364893ab997
* Version Independent ID: a92c88d3-6ee8-1e69-f4c3-49eb82909746
* Content: [Consume ASP.NET Core Razor components from Razor class libraries](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/class-libraries.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @abdollahkahne ... Good questions. Open it for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

... and please add the following to the bottom of your opening comment ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/24889
```

... so that I can follow the discussion. As you say, the topic currently is very focused on static assets and components. I'd like to hear what they say about services ... for example, services that might be used in the RCL's components and code. Usually, I close these while the discussion is taking place and then re-open it later. However, I think **_we should leave this issue open_**. I have a feeling that they are going to provide some good guidance that will go into the topic.

**Comment by guardrex** [comment]
Ok ... I'm on this ... finally 🏃😅. On the first point, there's nothing that I can do about that in docs. There's no opportunity to register services via the RCL AFAIK, and we don't document features that don't exist. You can [open an issue for engineering](https://github.com/dotnet/aspnetcore/issues) if you want to send in a feature request.

WRT the 2nd point ... **_Yes!_** ... and we do have something like that, but it's rather buried and specific to the particular case  ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-6.0#support-prerendering-with-authentication

What I need to do is create a general version of that in a new section for the DI topic **_and_** either use an INCLUDE file for it or just cross-link so that the *Prerendering and Integration* topic surfaces it, too.
