### ISSUE TITLE
The javascript Component instance example is obtuse and difficult to understand

### ISSUE THREAD

**Issue by bar10dr** [dotnet/AspNetCore.Docs#24902]
The component instance example do not use real world examples, where does dotNetHelper come from and how do I use it in a javascript function?

Why would I want to send static information back to a blazor function? How do I use this with dynamic data?

Should I use dotNetHelper.invokeMethodAsync(), or does that not work with component instance calls?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2964d558-cd6d-7421-f7b9-cb939792c2cf
* Version Independent ID: a3517e56-69fc-1ec7-b55a-dbb54d68a807
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#static-net-method-call)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bar10dr ... We feel that our C# examples (**_contrived to be simple, I admit_**) are "real world" examples. I mean devs won't call .NET methods in any other way than this topic shows for production app purposes. However, I would like to hear more feedback from you on what you mean by "real world." What did you have in mind? Whatever they might be, they would use the same approaches that you see here, but we can consider further examples or using other examples than these.

> where does dotNetHelper come from

The `DotNetObjectReference` is created at `objRef = DotNetObjectReference.Create(this);` as `objRef` to pass via `JS.InvokeAsync` in the example. In the topic, it states ...

> When the **Trigger .NET instance method** button is selected, the JS function `sayHello1` is called with the `DotNetObjectReference`.

On the JS side, you don't need to call it "dotNetHelper" ... you can name the variable anything u wish.

I generally need to work thru these descriptions again and be a bit more careful that the example code is connected to the text's concepts. Because of a little bit of complexity in these examples, it looks like the text should be a bit more detailed. I'll work on that for this issue.

> how do I use it in a javascript function?

I'm a bit confused by the question. It's just `dotNetHelper.invokeMethodAsync('{METHOD}');` It's described there. Of course, I'll take another look 👁️ and work on the text a bit more. Further if the object reference doesn't dispose itself, you should call `dotnetHelper.dispose();` to take care of the disposal from the JS-side. There's content and examples on that, too.

> Why would I want to send static information back to a blazor function?

Instead of "Blazor function," we just refer to the JS function. It's a bit confusing because these are ordinary JS functions. Anyway, that's up to you for any purpose really. Perhaps, the JS must perform some other processing ... perhaps to make another .NET method call after that ... or perhaps to log something for the console.

> How do I use this with dynamic data?

You'd have to clarify the scenario.

> Should I use `dotNetHelper.invokeMethodAsync()` ... component instance calls?

Yes, that's covered in the text+examples at ...

https://docs.microsoft.com/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#component-instance-net-method-helper-class

**Leave this open, @bar10dr._** I would like to work on these descriptions a bit more. I know you probably find this hard to believe, but the topic has had perhaps two rounds of prior work to improve the text and example ... like about once a year over the past few years. They were **_much worse_** than what you see today. 🙈 However, I certainly will make another pass on this. Note that we have a lot of high priority work going on right now. It can take a while to get to an issue like this. It won't be lost ... it's on the Blazor.Docs tracking project, so it won't disappear into a black hole! 😄 Anyway ... leave this issue open ... it will close automatically later after the PR merges. Thanks for commenting on the topic.

**Comment by bar10dr** [comment]
Thank you for a great response @guardrex .

I'm misunderstanding how it works I think 😋

Specifically for the component instance examples, it seems to me like I have to trigger it from blazor by passing DotNetObjectReference<> to a js function from within blazor and bring back data; but I need the call to originate from a custom javascript so there is no DotNetObjectReference<> available.

I guess I can make a call to the script at page load, pass DotNetObjectReference<> and store it in the js for later use, or is that not recommended?

Thank you for your great work, I love Blazor.

**Comment by guardrex** [comment]
**_Ah!_** Yes, I see what you mean now. For the instance case, any given JS function requires the `DotNetObjectReference`, but you want it to be available for JS functions by, for example, creating and passing it from `OnAfterRenderAsync` (the lifecycle method) ... noting also that you'd make sure to dispose of it, probably on the .NET side when the component is disposed. Very good. I have an idea how it would be done, but let me send my idea to the product unit and get back to you. I agree with you ... we're missing the example of how to do this ... **_whatever it is_** 😄. Let me verify either my concept or get the correct approach. I'll message you back here, then I'll work this issue forward on two counts ...

* Some of the descriptions that tie text to code examples need a little more descriptive detail to clarify concepts.
* We don't have an instance `DotNetObjectReference`-approach for JS functions that avoids passing the reference directly from a .NET method (e.g., we don't show an approach passing it via `OnAfterRenderAsync`). We should have an example and explanation.

Stand-by ... I'll get back to you as soon as I chat with Steve about this. Hopefully, you'll hear back from me early this week.

**Comment by guardrex** [comment]
@bar10dr ... **_Great!_** Yes, you were correct, and here's my concept with some code updates that Steve recommended. I'll use the following as the basis for a doc update later ...

```javascript
class MyHelpers {
  static dotNetObject;

  static setDotNetObjectReference(value) {
    MyHelpers.dotNetObject = value;
  }

  static async sayHello() {
    const msg = await MyHelpers.dotNetObject.invokeMethodAsync('GetHelloMessage');
    alert(`Message from .NET: "${msg}"`);
  }
}
```

`Pages/NewJSExample.razor`:

```razor
@page "/new-js-example"
@implements IDisposable
@inject IJSRuntime JS

<PageTitle>New JS Example</PageTitle>

<h1>New JS Example</h1>

<p>
    <label>
        Message: <input @bind="name" />
    </label>
</p>

<p>
    <button onclick="sayHello()">
        Trigger JS function
    </button>
</p>

@code {
    private string? name;
    private DotNetObjectReference<Index>? objRef;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            objRef = DotNetObjectReference.Create(this);
            await JS.InvokeVoidAsync("MyHelpers.setDotNetObjectReference", objRef);
        }
    }

    [JSInvokable]
    public string GetHelloMessage() => $"Hello, {name}!";

    public void Dispose()
    {
        objRef?.Dispose();
    }
}
```

WRT calling `await base.OnAfterRenderAsync(firstRender);`, which I see some devs doing, he said ...

> We try to avoid making people call base on `ComponentBase` virtual methods. They can call it if they want, but it’s a no-op.

I'll probably check and see what we say in the *Lifecycle* doc about that and possibly add/change text on that as part of this work.

WRT disposal ... Steve mentioned how important it is to dispose, so I think we'll want to re-iterate the importance of doing it after the new example and cross-link to the text that speaks to disposal.

WRT when I can get to this for doc work ... I'm **_VERY_** 🏃😅 at the moment, so it will likely take a little while to reach this. However, this issue is attached to the topic. Doc readers can find it via the link at the bottom of the topic to issues for the doc.

**_Leave this issue open._** It will close automatically later when the PR merges. Thanks for your issue, @bar10dr. I'm glad that we'll cover this approach and look forward to making a general round of text updates to clarify the scenarios further.
