### ISSUE TITLE
Could you please add an example or a guidance to implement "Make API calls from the client to the server API in order to call third-party APIs"

### ISSUE THREAD

**Issue by en237** [dotnet/AspNetCore.Docs#24901]
Hi,

Could you please add an example or a guidance on how to implement the scenario in the section 
[Make API calls from the client to the server API in order to call third-party APIs](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-6.0#make-api-calls-from-the-client-to-the-server-api-in-order-to-call-third-party-apis)

I would like to use Cookies auth on a hosted blazor WASM and secure external API calls from the server using OIDC access token, the scenario described seems to be what I'm looking for but I don't know how to implement it.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f3209c-2414-9b35-6245-383c9b7c6338
* Version Independent ID: cc8dfcd6-8d93-5aa3-c381-2b613e88cdbe
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-6.0#options-for-hosted-apps-and-third-party-login-providers)
* Content Source: [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @en237 ... Probably not an exact example because outside of making a raw HTTP client requests it depends on the external, 3rd party API, and we already cover general `HTTPClient`/factory requests in the *HTTP Requests* doc in the main doc set. We would leave it to the external (non-Microsoft) API provider docs and the community (e.g., blogs, videos, etc.). Even for MS services, like AAD/B2C/Graph API, there's some question at this point if we even need to maintain Blazor docs (or as much content as we do) because Azure docs have come a long way on covering Azure with Blazor.

Given that it's just an ASP.NET Core app (I'm referring to the the **`Server`** app of the hosted WASM app), `HttpClient`/factory requests are covered outside of Blazor. When you don't have a really nice package from a 3rd party provider, you end up making manual requests ...

https://docs.microsoft.com/aspnet/core/fundamentals/http-requests

... and attaching headers for tokens to the `HttpRequestMessage`. For example, we show that when the **`Client`** makes a direct request at ...

https://docs.microsoft.com/aspnet/core/blazor/call-web-api?view=aspnetcore-6.0&pivots=webassembly#httpclient-and-httprequestmessage-with-fetch-api-request-options

... see how the `Bearer` token is set up there for that request? That's a common pattern for a client that obtains the web API access token from the identity provider. It's a similar pattern for server API.

In your case ... if you asking about a 3rd party API ... the user is already authenticated (we just show provider docs for AAD, B2C, and IdS), so the first request is to a controller in the server API app (the **`Server`** app in the hosted WASM solution) and that app is first going to make sure they're authorized to even run the controller's methods ... **_and then_** the controller will obtain a 3rd party API access token and call the API with it ... that's the part where you hope for a nice package to drop into your **`Server`** app that only requires you to make a couple of calls (a couple of lines of code) and it just ✨ *takes care of the ceremony for you* ✨. You might need to tap into a database on the **`Server`** side to get some additional data for that user to make a web API call; but whether or not that's required, the controller makes the 3rd party web API call. Then, it has to return whatever the result is, possibly data, back to the client. Even if you don't have a nice NuGet package that helps you, you can compose an `HttpRequestMessage` with any token(s) or data required. For example ... in the simplest case ...

https://docs.microsoft.com/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0#basic-usage

btw ... I'm not sure where the "Cookies auth" comes into it ... it's SPA and token-based between the client and the server as far as Blazor is concerned. For more info, see :point_right: https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/?view=aspnetcore-6.0#authentication-library

What API were you trying to call for user's via the server app? ... can you say here pubicly? Have you had little luck finding a specific example where an SPA calls an ASP.NET Core backend and then that app calls that web API? You know we recommend the usual places to ask for support, so I recommend asking the community to see about help with a specific 3rd party API.

For ASP.NET Core ...

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)

For Blazor specifically ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)
* [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor) (Community-maintained collection of Blazor resources)

**Comment by en237** [comment]
Thanks for the complete explanations.

Based on them and with some trial and errors I ended up using [Duende.BFF](https://docs.duendesoftware.com/identityserver/v5/bff/) and [Yarp](https://github.com/microsoft/reverse-proxy) which work very well for my use case.
