### ISSUE TITLE
Blazor Hosting Models topic SEO updates

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#24923]
Follow-up discussion for SEO updates after https://github.com/dotnet/AspNetCore.Docs/pull/24878 and https://github.com/dotnet/AspNetCore.Docs/pull/24920. All of the updates are live in the doc set now at ...

https://docs.microsoft.com/aspnet/core/blazor/hosting-models

cc: @v-mepa

> should I use blazor server or blazor wasm

... and similar wording: sometimes with "versus"/"vs" instead of "or" and sometimes with "webassembly" instead of "wasm" in the search string.

The primary expression is placing the page 3rd (at Google). We'd like to eventually reach *First Place* 🥇.

https://www.google.com/search?q=should+i+use+blazor+server+or+blazor+wasm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by v-mepa** [comment]
I went through the article and the very first thing we must update is the page title. I looked at the page titles of the other 2 sites which are ranking 1 & 2 on SERP  for  ‘should i use blazor server or blazor wasm’:

Rank 1 Website: [RoundTheCode](https://www.roundthecode.com/dotnet/blazor/blazor-server-vs-blazor-webassembly-four-ways-in-which-they-differ#:~:text=If%20you%20want%20an%20application,be%20looking%20at%20Blazor%20WebAssembly.)
Page Title: _Blazor Server vs. Blazor WebAssembly: Four Ways In Which They Differ_ 

Rank 2 Website: [Programmingwithwolfgang](https://www.programmingwithwolfgang.com/blazor-server-vs-blazor-webassembly/)
Page Title: _Blazor Server vs. Blazor WebAssembly | Programming With Wolfgang_

Rank 3 Website: Microsoft Docs
Page Title: **ASP.NET Core Blazor hosting models | Microsoft Docs**

Though Google is creating its own page title based on the relevancy and content of the page now, I will still highly recommend updating the page title which definitely helps in ranking higher on SERP. . Here is an article on how starting August 2021 [Google generates web page title ](https://developers.google.com/search/blog/2021/08/update-to-generating-page-titles) which definitely helps in ranking higher on SERP.

**Comment by guardrex** [comment]
You mean something like this? ...

> ASP.NET Core Blazor Server and Blazor WebAssembly hosting models

**Comment by v-mepa** [comment]
After conducting competitor analysis it is clear that top-ranking websites have used more words & images in explaining and showcasing “why” & ”how” should I use blazor server vs/or blazor webassembly with a secondary focus on “what” blazor server or/vs blazor webassembly is.

And our content primarily focuses on “what” blazor server or/vs blazor webassembly is with secondary focus on “why & how” ‘should I use blazor server or blazor webassembly’. And that's why [Hosting page ](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-6.0) is ranking top for keywords like 'Blazor server', Blazor Webassembly/wasm' and others. 

Looking at the other top-ranking content their prime focus is on giving a detailed explanation on the difference between 'Blazor Server vs. Blazor WebAssembly' related to features, pros & cons and others which is more relevant to search engines & users for the given query ‘should I use blazor server or blazor webassembly’. Adding more content or creating a separate page for the below section will help improve our rankings.
![image](https://user-images.githubusercontent.com/42360097/153292739-61e57da0-496a-45a6-a018-f9845e850922.png)

**Comment by guardrex** [comment]
> Adding more content or creating a separate page for the below section will help improve our rankings.

It was an item on the initial discussion ... bullet point 5 under *Notes* on https://github.com/dotnet/AspNetCore.Docs/pull/24878. I think it's a good idea.

I'm going to be 🏃 for the next five days on another set of tasks, so I plan to return to this mid to late next week. I'll seek to write a compare-and-contrast paragraph on each feature listed in the table. I think we should leave the table as a useful summary.

**Comment by v-mepa** [comment]
Sounds good.

I agree with your point on leaving the table as a useful summary.
