### ISSUE TITLE
head tag sign not showing properly on a section, please check screenshot attached

### ISSUE THREAD

**Issue by chinmay-trivedi** [dotnet/AspNetCore.Docs#24996]
Head tag shows &lt;head&gt;  instead of <head>
![2022-02-14_14h21_45](https://user-images.githubusercontent.com/20231926/153932656-a7e91dbd-e6be-4e98-8821-23a70d24f6a9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8bc6ab-a440-d860-e40c-8f18aa1eafb3
* Version Independent ID: 8a5b47e7-b29c-b049-30e8-5b405a5086b6
* Content: [ASP.NET Core Blazor environments](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @chinmay-trivedi ... I'll patch that up.

**Comment by guardrex** [comment]
It's a bit of an internal problem because they're using the title raw ... i.e., they're using the HTML-encoded angle. It's actually correct for the topic itself ...

https://github.com/dotnet/AspNetCore.Docs/edit/main/aspnetcore/blazor/components/control-head-content.md

... and renders correctly for the doc ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/control-head-content?view=aspnetcore-6.0

I think the best way to address this is to encode it as \`head\` (code fenced) so that it doesn't localize and **_don't_** use the angle brackets. I'll inspect the topics after it goes live to confirm that it all works out ok.
