### ISSUE TITLE
Documentation on how to create a blazor server and a blazor webasm projects

### ISSUE THREAD

**Issue by dhaanpaa-lab0** [dotnet/AspNetCore.Docs#25006]
How do I create a blazor webasm or blazor server project without the layout files or the extra pages? I want to be able to create either a webasm project or a blazor server project from scratch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d31248d7-d2c2-1a17-3173-889a0d9bb6e8
* Version Independent ID: 6f27ff37-6b3a-57f5-353a-5cf5aabba7cf
* Content: [ASP.NET Core Blazor project structure](https://docs.microsoft.com/en-us/aspnet/core/blazor/project-structure?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/project-structure.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dhaanpaa-lab0 ... You can't using the project templates. Everything is baked into them.

**Comment by dhaanpaa-lab0** [comment]
What I was looking for was how to create either a blazor web assembly app or a blazor server app without using the project templates?

**Comment by guardrex** [comment]
There's no feature that matches your request that's built into the framework. You can **_create your own project template_** ...

https://docs.microsoft.com/dotnet/core/tutorials/cli-templates-create-project-template

Otherwise, you'd just have a local folder with a base project in it and copy that when you want to create a new app. 

It sounds like you're looking for a feature here that isn't offered at this time ... I mean if you're asking for something other than a custom template. The product unit would like to hear feedback on subjects like this. Open an issue on the product unit's repo as a feature request for what you're seeking and explain why you need it ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/25006
```

... to the bottom of your opening comment so that I follow the discussion.
