### ISSUE TITLE
Nested models, collection types, and complex types: I think this section already is included by default

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/AspNetCore.Docs#25013]
In section Nested models, collection types, and complex types, for me validation for complex objects works without any special or further attempts. I think it is already included by ASP.Net version 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-6.0#nested-models-collection-types-and-complex-types)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @abdollahkahne ... They haven't rolled the package into the framework yet, but they plan to do so for .NET 7 ...

https://github.com/dotnet/aspnetcore/issues/28640

If you have a concern about what you're seeing ... like it seems like the guidance is incorrect, then I recommend asking them directly because they haven't indicated to me that anything has changed in these regards. Open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Reference this article/section:

https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-6.0#nested-models-collection-types-and-complex-types

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/25013
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.
