### ISSUE TITLE
Rollback the ASP.NET Core 2.X content

### ISSUE THREAD

**Issue by vernou** [dotnet/AspNetCore.Docs#25171]
Hi,

In my company, we have a lot of dependencies incompatible with .NET Core. Then we use .NET Framework with ASP.NET Core 2.1.

After a lot of work, we eliminated this problematic dependencies and are preparing the migration from ASP.NET Core 2.1 to ASP.NET Core 6. Last week, I read interesting about the automatic validation return on this documentation page. But today, all that interesting content is gone...

The removal of this content is voluntary as the ticket #24695 reveals. But I don't understand the reason.

ASP.NET Core 2.1 is always supported on .NET Framework as indicated in this page :
https://dotnet.microsoft.com/en-us/platform/support/policy/aspnet#dotnet-core

> To help facilitate migrating applications to ASP.NET Core on .NET Core, the following ASP.NET Core 2.1 (latest patched version only) [packages](https://dotnet.microsoft.com/en-us/platform/support/policy/aspnetcore-2.1) will be supported on the .NET Framework and follow the [support cycle](https://support.microsoft.com/en-us/lifecycle/search?alpha=.net%20framework) for those .NET Framework versions. ASP.NET Core 2.1 is defined as "Tools" in the Microsoft Support Lifecycle Policy. A "Tool" requires a minimum of 12 months notification prior to the end of support

A lot of company continue to use ASP.NET Core 2.1 and will migrate. This documentation with ASP.NET Core 2.X notes is a welcome help.

Can you rollback the deleted content about ASP.NET Core 2.X?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You can see the deleted content [here](https://github.com/dotnet/AspNetCore.Docs/pull/24694/files). It's almost identical to the 3.1 version.

**Comment by Rick-Anderson** [comment]
Coded deleted in #24697 and no easy way to restore that code. cc @guardrex

**Comment by guardrex** [comment]
> ASP.NET Core 2.1 is defined as "Tools" in the Microsoft Support Lifecycle Policy.

That doesn't seem to be an accurate remark ...

https://docs.microsoft.com/en-us/troubleshoot/developer/webapps/aspnet/development/support-lifecycle-web-stack

The support policy AFAIK is ...

https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core

I'll talk to Dan and Artak about it tonight. WRT restoring all of the 2.1 content over this, I gravely doubt that (**_but don't know that_**) they'll want **_all_** such content restored. I recommend waiting for an answer before proceeding to restore this content.

**Comment by guardrex** [comment]
Confirmed by Artak. In spite of that funky statement about ASP.NET Core 2.1 being a "Tool," they want to **_KEEP_** the 2.1 content ... **_as in restore all of it_**.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson @serpent5 @wadepickett Do you think that the PRs that removed the content can just be reverted ... **_at this late date_**? Is it felt that it might ✨ **_Just Work™_** ✨?

No, I've saved an old repo snapshot. We'll restore them on a case by case basis. I'll restore this one today.

**Comment by guardrex** [comment]
Ok ... that sounds better, but Artak was clear that they want it all restored ... as in like **_ALL of IT_** 🙈😄.

You know, my *early retirement* was coming up here! ⛱️🍹 *This might be a good time to consider **_extra early retirement_**. 🤔😆

**Comment by Rick-Anderson** [comment]
@vernou 2.1 will be live in 10 minutes.

**Comment by vernou** [comment]
Thank @Rick-Anderson 

@guardrex write :
> That doesn't seem to be an accurate remark ...

I think the support of ASP.NET Core 2.1 ended at 21/08/2021 for .NET Core, but the support is maintained for .NET Framework.
Do I lack of understanding about the ASP.NET Core 2.1 support?

**Comment by guardrex** [comment]
The entries listed for "Tools" don't include "ASP.NET Core 2.1" as the original post copied from the first doc. However, support will be maintained per PU management regardless of the incorrect remark in the doc.

**Comment by vernou** [comment]
Glad to read this.

@guardrex : What is "PU management"?

**Comment by guardrex** [comment]
"PU" = "product unit"

**Comment by WillGunn** [comment]
Does ASP.NET Core 2.2 have the same support policy as 2.1 when run on .NET Framework?

**Comment by guardrex** [comment]
Yes, @WillGunn ... that's correct.

**Comment by vernou** [comment]
ASP.NET Core 2.2 packages aren't deprecated, but they haven't a recent version unlike ASP.NET Core 2.1 packages.

ASP.NET Core 2.1 has a [branch on GitHub](https://github.com/dotnet/aspnetcore/tree/release/2.1) that continue to be developed with this recent PR that fix some governance alerts to ASP.NET Core 2.1 packages :
[Update references to System.IO.Pipelines #46360](https://github.com/dotnet/aspnetcore/pull/46360)

And the PR has this [comment](https://github.com/dotnet/aspnetcore/pull/46360#issuecomment-1411171850) :
> Since 2.1 still has support for full framework, we're stuck having to fix the alerts.

I'm sorry to have some doubts.
@guardrex, can you link a reference that confirm ASP.NET Core 2.2 has a support policy on .NET Framework?

**Comment by guardrex** [comment]
My understanding was that all versions of ASP.NET Core on .NET Framework adopt the .NET Framework support policy. I was perhaps mistaken in that only the LTS release is going to be supported, and that would be 2.1, ***not 2.2***.

In [.NET and .NET Core Support Policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core), there's a section on 2.1, *ASP.NET Core 2.1 on .NET Framework* with a link to "ASP.NET Support" that's broken, but the page shows up by removing a link segment at [ASP.NET Support Policy](https://dotnet.microsoft.com/en-us/platform/support/policy/aspnet). That page indicates that ...

> To help facilitate migrating applications to ASP.NET Core on .NET Core, the specified [ASP.NET Core 2.1 packages](https://dotnet.microsoft.com/en-us/platform/support/policy/aspnet/2.1-packages) (latest patched version only) will be supported on the .NET Framework and follow the [support cycle](https://support.microsoft.com/en-us/lifecycle/search?alpha=.net%20framework) for those .NET Framework versions.

My current thinking is now, ***no*** 🎲🎲 on 2.2 on .NET Framework.

If could've made one suggestion to management, it would've been to ***NOT*** comingle them in the section heading of [.NET and .NET Core Support Policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#lifecycle) because that's very confusing to see past dates in the *Out of Support* area that map to 2.1/2.2 under that section heading. I suggest breaking out .NET (Core) and .NET Framework into two pairs of tables (*Supported versions* and *Out of support versions* for each) to make it clear exactly what's supported when.

cc: @mkArtakMSFT ... Will know for sure and can correct me if my assessment is incorrect.

**Comment by WillGunn** [comment]
Yeah I don't remember seeing anywhere that specified 2.2 as not LTS for 2.x targeting Framework, let alone EOL.  The quoted sentence only says that the latest patch of 2.1 is supported, but the lack of any mention of 2.2 doesn't indicate that it is EOL, its state is ambiguous/undefined if that is the only reference.  A clarification in the docs would be helpful.  

We went to 2.2 a while back due to the improvements as listed: https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-2.2 and while we're working on getting off of Framework, its an ongoing project.  

Is there any discussions on why 2.1 was selected over 2.2 (if that is indeed that case) for LTS on Framework?  2.2 is what introduces HTTP2 support as well as improved performance.

**Comment by guardrex** [comment]
> its state is ambiguous/undefined

I agree that it's confusing.

> Is there any discussions on why 2.1 was selected over 2.2 (if that is indeed that case) for LTS on Framework?

I can't say outside of the fact that 2.2 was never an LTS release in it's own right.

I think @mkArtakMSFT will be along in a bit to assist.

**Comment by dahlbyk** [comment]
Glad to post a new Issue if you prefer, but I posted a 2.1-on-Framework question on Learn that now seems unlikely to get a qualified response: https://learn.microsoft.com/en-us/answers/questions/1327232/microsoft-aspnetcore-dataprotection-2-1-1-dependen
