### ISSUE TITLE
metadata in docfx.json seems a solid solution,

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#25187]
See details in #25066
Internal issue [here](https://ceapex.visualstudio.com/Engineering/_workitems/edit/571334)
previous [internal issue]( https://portal.microsofticm.com/imp/v3/incidents/details/290559630/home)

Per @guardrex 

1. Create a fake doc that isn't in the ToC (`testdoc.md`) and doesn't have a `no-loc` metadata entry that just has a single paragraph sprinkled with a few common words ... "computer" ... "cat" ... whatever.
1. Add `fileMetadata` for it in `docfx.json` ...

   ```json
   "fileMetadata": {
     "no-loc": { "testdoc.md": "[ computer, cat ]" },
     ...
   }
   ```
1. Given the MT runs on a post-publish schedule, go ahead and take it live.
1. Check back in a few weeks ... did the "computer" and the "cat" words escape MT?

Even if that works tho, HT might not catch it because translators might not be looking at the `docfx.json` file for the string of words to avoid. The whole translation system is opaque to the community AFAIK ... it's ✨😄.

**Comment by Rick-Anderson** [comment]
> , HT might not catch it because translators might not be looking at the docfx.json 

We have very few HT doc's. If they miss our exclude list, we'll point that out.

**Comment by guardrex** [comment]
The no-loc test is now underway 🤞🍀. 

I'll report back when I've confirmed the result of this test.

**Comment by guardrex** [comment]
@khoiph1 ... We're running a test to see if we provide `no-loc` metadata via the `docfx.json` file if translation of some test words is prevented. Instead of waiting on the natural MT to run on the repo, can you trigger a MT for the repo manually?

It doesn't matter what non-English languages we check for this test. I just need to check any language that would normally translate the words "cat" and "computer" in the following test document ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/no-loc-test?view=aspnetcore-6.0

* If after MT, "cat" and "computer" are translated, we know that this approach doesn't work.
* If after MT, "cat" and "computer" aren't translated and the normal list (the first list in the top of the page) is translated, then we know that we have a viable approach here that we can apply to the whole repo ... *well* ... 🤔 ... 🙏 ... *we hope, anyway* 😄.

**Comment by guardrex** [comment]
@Rick-Anderson ... Who is @khoiph1's manager?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson ... Who is @khoiph1's manager? I'd like to find out if @khoiph1 is on vacation ... or even still in the role. There's no response here or via email.

@HyunKSong

**Comment by guardrex** [comment]
Khoi ... I've been waiting to see if MT would run and translate my test doc, `no-loc-test.md`, but it doesn't look like it has run ... or run *yet*.

If you know that this whole approach is going to fail, that's cool ... I'll revert this (🔪 the test doc), and that's the end of this.

If you aren't sure tho ... can you trigger a MT on the repo so that my test doc will get translated so that I can study the behavior of the localization? We can finish the test and see what happens here.

**Comment by guardrex** [comment]
I see. I'll move the test doc this morning.

**Comment by khoiph1** [comment]
@guardrex our loc tool is having an issue with querying the files in the repo https://portal.microsofticm.com/imp/v3/incidents/details/294390177/. I will trigger a HO as soon as the issue is mitigated.

**Comment by guardrex** [comment]
@Rick-Anderson @wadepickett @serpent5 

The MT ran (thx @khoiph1), and this approach failed 😢. I'll 🔪 the test doc and `docfx.json` entry on Monday morning.

**Comment by guardrex** [comment]
btw @khoiph1 ... These seem like poor translations according to Google Translate.

> El equipo tiene diez años.

... is ...

> The team is ten years old.

... but the word is "computer," so that seems *very wrong*.

> Die Katze, die mit der Maus aschen soll.

... is ...

> The cat that should ash with the mouse.

So, that looks incorrect. Also, the comma seems wrong, too. In German, shouldn't it be ...

> Die Katze hat die Maus gefressen.

For French ...

> Le chat a la souris.

... is ...

> The cat has the mouse.

Google thinks that ...

> Le chat a mangé la souris.

... would be the correct French equivalent.

These are such simple sentences. Either I'm missing something, Google translate is wrong, or the MT is wrong.

**Comment by khoiph1** [comment]
Thanks, @guardrex. I will share this feedback with the MT engine team.

**Comment by guardrex** [comment]
cc: @serpent5 @Rick-Anderson @wadepickett 

Actually, let's re-open this and work PRs from here. I'm moving my remarks over from the PR ..............

cc: @khoiph1 ... Khoi, I'm going to try this again now that Kirk got me straight on what a JSON array is! 🙈😆 DUH! I told them ... I just told Dan and Artak that I'm exhausted 😩 and must take a vacation 🏖️🍹 within the next couple of weeks to recharge.

Here's the live English-US doc ...

* https://docs.microsoft.com/en-us/aspnet/core/migration/no-loc-test?view=aspnetcore-6.0

... and then after MT runs, I'll check on ...

* https://docs.microsoft.com/es-es/aspnet/core/migration/no-loc-test?view=aspnetcore-6.0
* https://docs.microsoft.com/de-de/aspnet/core/migration/no-loc-test?view=aspnetcore-6.0
* https://docs.microsoft.com/fr-fr/aspnet/core/migration/no-loc-test?view=aspnetcore-6.0

... and see what happens. If it works this time, I'll change the `docfx.json` to reflect our need for a global **_ARRAY_** 😄 of `no-loc` entries.

Use of `fileMetadata` is fine for the test because we want to scope the test to just the `no-loc-test.md` file. For the full repo tho, we should use `globalMetadata` if this ends up working out. I propose to use the following ...

```json
"globalMetadata": {
  ... existing entries ...
  "no-loc": [ "entry1", "entry2," ... "entryX" ],
  ... existing entries ...
}
```

We also want to keep doc-specific `no-loc` words. When I make the full repo update, I plan to filter those `no-loc` entries and leave them with only the doc-specific entries. It does lead to a BIG ❓ tho ... Are they going to merge cleanly into the final doc? If nobody knows if that's going to happen, then I need to run a follow-up test: I'll add our existing `no-loc` metadata entry to my `no-loc-test.md` doc and then see if the test `fileMetadata` entry and the doc's metadata list combine and prevent localization of the list at the top of the doc AND prevent loc of my "computer" and "cat" words.

UPDATE: Actually, I think we should test `globalMetadata` separately, too. Let's make sure that every aspect of this looks 👀 good before proceeding. There will be two more tests to perform, and I think they can be performed simultaneously ...

* `globalMetadata` works as well as `fileMetadata`: I'll place an existing `no-loc` word there from our file-based metadata (a duplicate).
* File-based no-loc merges with `globalMetadata`: I'll place our normal string, less the one word that I move to `globalMetadata`. I'll also include my "computer" and "cat" test words.

**Comment by PaulDempsey-ms** [comment]
Rick wrote:
> Even if that works tho, HT might not catch it because translators might not be looking at the docfx.json file for the string of words to avoid. 

That's not how no-loc and the docs translation system works. For translation, markdown is parsed to XLIFF. No-loc items are marked up in a way that the translator's editor does not allow modification of so-marked text. Depending on the precise context, they may not see that text at all.  Translators have no need to be aware of docfx.json, or any such word list. They only work in XLIFF.

**Comment by guardrex** [comment]
> Even if that works tho, HT might not catch it because translators might not be looking at the docfx.json file for the string of words to avoid.

I wrote that at https://github.com/dotnet/AspNetCore.Docs/pull/25066#issuecomment-1047707508. Rick copied it over.

That's great news, @PaulDempsey-ms! 😄 I'm glad that aspect isn't blocking the use of this approach.

Thus far, I'm still waiting on MT to run. If the approach survives the first test, I'll keep going with the follow-up test.

**Comment by guardrex** [comment]
@khoiph1 ... It's been 10 days since the latest PR went up for testing, and MT apparently still hasn't run.

https://github.com/dotnet/AspNetCore.Docs/pull/25438

* https://docs.microsoft.com/es-es/aspnet/core/migration/no-loc-test?view=aspnetcore-6.0
* https://docs.microsoft.com/de-de/aspnet/core/migration/no-loc-test?view=aspnetcore-6.0
* https://docs.microsoft.com/fr-fr/aspnet/core/migration/no-loc-test?view=aspnetcore-6.0

These topics are in the *Migration* node, so they should be MT automatically AFAIK. However, it still isn't clear to anyone here **_when_** MT runs on our MT docs. After a doc goes live, is there a set schedule for MT to run?

**Comment by guardrex** [comment]
Khoi replied offline: It did run. I had a local doc caching problem of some sort.

**_Good news!_** 🎉 It seems to have ✨ **_Just Worked!_**&trade; ✨.

I'll proceed to the next round of testing tomorrow, Wednesday.

**Comment by guardrex** [comment]
@Rick-Anderson @serpent5 @wadepickett 

Unfortunately, no 🎲🎲 on `globalMetadata` 😢. Here's a screenshot from the Spanish doc ...

<img width="415" alt="Capture" src="https://user-images.githubusercontent.com/1622880/162181493-ddac5c8f-a0ac-469a-8ba1-c1a947843703.PNG">

However, we know thus far that `fileMetadata` will work on its own with a repo-wide wildcard (i.e., `"**/*.md"`).

I'm setting up **_Test 3_** now: We need to see if the wildcard `fileMetadata` will merge with a topic-specific `no-loc` list.

**Comment by guardrex** [comment]
Unfortunately, the two `no-loc` entries **_do not merge_** 😢. It's not so bad tho: It takes the topic-specific `no-loc`. For topics that have topic-specific `no-loc` entries, the full array would need to be present along with the topic-specific entries. We could do well with that because there are few topics that need topic-specific entries.

 Last test (4) will be to just confirm that the wildcard works correctly.

**Comment by guardrex** [comment]
# 🎉 

**_Greeeat!_** It works ...

https://docs.microsoft.com/es-es/aspnet/core/migration/no-loc-test?view=aspnetcore-6.0

... so .............

* We can use a wildcard `fileMetadata` entry in `docfx.json` for the main repo-wide array.
* We can place a `no-loc` in a topic that includes topic-specific words. The only catch is that the `no-loc` in the topic must have the array that's used in `fileMetadata` because they do ***NOT*** merge. This will apply to very few topics, if any at all.

@Rick-Anderson ... I'll set up the next one for the full repo changeover, but do you want to get executive approval? *This one ain't in the book!*

Also ... WRT timing ... I don't think this is the best time because there are so many open PRs right now. Probably best to wait until we drop down to just a few. I'll keep an 👁️ out for a good time.

I'll ping for PR review when it goes up.

**Comment by Rick-Anderson** [comment]
Fantastic work and congradulations.

> @Rick-Anderson ... I'll set up the next one for the full repo changeover, but do you want to get executive approval? _This one ain't in the book!_

Approved. We can back out if there's unforeseen problems.

**Comment by Rick-Anderson** [comment]
The Dev Ops guys want to know if we can close their issue. Is everything working?

**Comment by guardrex** [comment]
I think so.

WRT this issue and wrapping this up, I'm only waiting for the open PR list to drop to cut the number of merge conflicts that will need to be resolved.
