### ISSUE TITLE
Missing Blazor WebAssembly hosting info 

### ISSUE THREAD

**Issue by Domonion** [dotnet/AspNetCore.Docs#25205]
# Issue description

Current Blazor WebAssembly templates implicitly relies on either ```Microsoft.AspNetCore.Components.WebAssembly.DevServer``` for standalone and  ```Microsoft.AspNetCore.Components.WebAssembly.Server``` for hosted version. There was dotnet/aspnetcore#15927 about that, and related info was merged with aspnet/Blazor.Docs#153, but current docs does not have that infomation. 
Suspecting related info was lost by the time ```aspnet/Blazor.Docs``` was merged into this repo.

**Comment by guardrex** [comment]
Hello @Domonion ... Yes, that's rather ancient, and that package doesn't exist these days. The framework (and docs) have churned quite a bit since then ... three years is *forever* in tech terms these days 😄.

We don't focus on framework implementation details, which change quite a bit over time. Devs have access to the [API docs](https://docs.microsoft.com/dotnet/api/) and to the [reference source](https://github.com/dotnet/aspnetcore/tree/main/src), which includes the [project templates](https://github.com/dotnet/aspnetcore/tree/main/src/ProjectTemplates). We're focused on features. If you have a feature scenario that you think requires more framework implementation information, please open an issue using the **This page** feedback button and form at the bottom of the relevant **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
