### ISSUE TITLE
Yet Again Websocket .net core detect when client looses internet connectivity #9053

### ISSUE THREAD

**Issue by dscaravaggi** [dotnet/AspNetCore.Docs#25256]
Hi all,
sorry to ask again about: [https://github.com/dotnet/AspNetCore.Docs/issues/9053](https://github.com/dotnet/AspNetCore.Docs/issues/9053) , but I'm experiencing the following scenario

1. if for any reason I got a primary issue in Layer 3 core switches or maintenance I got mor or less 2.5K websocket clients disappearing at once.
2. even if we deployed a ws PING/PONG strategy with 60 seconds timeout, the application server (.Net 6 linux) is unresponsive and beging starving, even NLOG traces are interrupted, but the process is not crashing (and maybe a crash will raise a systemd restart)
3. with lesser connections (about 500 - 800) the application come back to life after 90 seconds and begin tracing again all forced disconnect plus emitting ton of exceptions (up to 20k)

another interesting note: in the test dev lab we discarded httplistenser websocket and we tried the obsolete: https://github.com/statianzo/Fleck , Fleck is behaving better we got diconnections on timeout, without starvation.

Thanks in advance for your feedback
Diego

**Comment by guardrex** [comment]
Hello @dscaravaggi ... Open your issue here ...

https://github.com/dotnet/aspnetcore/issues

... and you can cross-reference that docs PR. If the product unit issue leads to the need to update documentation, then either leave a comment here cross-linked to your product unit issue ... someone here will re-open this ... **_or even better_**, open a new docs issue using the **This page** feedback button and form at the bottom of the English-US topic ...

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by dscaravaggi** [comment]
@guardrex ok, I will move in correct page, I use this thread becuase from my point of view is a chapter of [: https://github.com/dotnet/AspNetCore.Docs/issues/9053](https://github.com/dotnet/AspNetCore.Docs/issues/9053)

**Comment by guardrex** [comment]
If it's opened for the product unit, then you'll get a response directly from the engineers who build the framework. We try to keep the issues here focused on the documentation and avoid many product support requests. The product unit engineers don't monitor most of the issues here. They mostly work on issues on their repo. We can re-open this issue or work a new documentation issue after you discuss it with them on their repo and find out that there is something that we need to change or add to the documentation. The best approach tho is not to just open an issue directly here ... use the **This page** feedback button+form on the topic (the English-US topic). That will ping the author and indicate the topic to us. It speeds things up on our side.
