### ISSUE TITLE
Failure of login popup

### ISSUE THREAD

**Issue by ordinaryorange** [dotnet/AspNetCore.Docs#25274]
[EDIT by guardrex for code-fencing. FYI ... surround code with backticks or use triple-backticks above and below code blocks.]

Just tried the steps in this documentation.
Visual Studio 2022 17.1.1
The popup login mode begins to render then fails and causes the balzor app to refresh.

Changing the Authority in appsettings.json from `/common` to `/<mytennantid>` resolved the problem.
Unsure if this is a documentation or engineering issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9adb06ae-6ca0-9e47-1061-4458d807c770
* Version Independent ID: 2f556d47-42e8-8b09-e0cb-9d169acd6aa6
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with Microsoft Accounts](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-microsoft-accounts?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/standalone-with-microsoft-accounts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ordinaryorange ... We haven't had any reports in over two years of this, and it worked the last time I checked (but that was *quite a long time ago ... over a year at this point*). The guidance is ~2 years old. Here's the original bit that Javier referred me to for MS Accounts ...

https://gist.github.com/javiercn/85a6d4ce46a78239ccb427baad3a66da#authenticating-standalone-applications-with-microsoft-accounts

I note that in the Azure portal there is a configuration for the app's tenant named "Personal Microsoft Accounts," but that wasn't what Javier indicated in his guidance.

I'll open an issue on the product unit repo for this shortly. I'll ping you on it, and we'll see what Javier thinks.

**Comment by guardrex** [comment]
Actually, it is best if you open the issue because they might need to work with you more directly on it.

Open an issue here ...

https://github.com/dotnet/aspnetcore/issues

Cite the doc ...

https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/standalone-with-microsoft-accounts

... and cite the source material ...

https://gist.github.com/javiercn/85a6d4ce46a78239ccb427baad3a66da#authenticating-standalone-applications-with-microsoft-accounts

Add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/25274
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.
