### ISSUE TITLE
using MessagePack on SignalR Blazor Server Side  

### ISSUE THREAD

**Issue by sebastianolafhandjojo** [dotnet/AspNetCore.Docs#25303]
This is working for SignalR using Blazor Wasm Hosted 
But not working for Blazor Server Side
And I tried to follow this [article] (https://github.com/dotnet/aspnetcore/issues/9627) mentioned by @BrennanConroy  
it doesn't work either 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e807e138-f84c-e63e-ab37-eec0d554d3bb
* Version Independent ID: 3ac41883-3bc2-30ba-a47f-462196850c12
* Content: [Use MessagePack Hub Protocol in SignalR for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/messagepackhubprotocol.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/messagepackhubprotocol.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @sebastianolafhandjojo ... This is a product unit support request until/unless Brennan and/or Brady say that it's a doc issue. I recommend that you open it for the product unit ...

https://github.com/dotnet/aspnetcore/issues

... and please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/25303
```

... to the bottom of your opening comment so that I can follow along. We'll re-open this for doc work depending on what they say.
