### ISSUE TITLE
[Blazor] Does this example have a memory leak?

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/AspNetCore.Docs#25330]
[EDIT by guardrex ... Just a quick note on the question: This refers to "**_Razor components_**," not Razor Pages pages, which I'm sure is what is meant by the question. I'm just noting it for the future in case a dev finds this issue and isn't sure exactly what this question is about.]

The "/reference-parent-3" surely has a memory leak because it never clears the list? Should it clear it out at the top of the razor page **_[sic]_**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0#capture-references-to-components-1)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's not static and is managed AFAIK, so I wouldn't think so. When these are sent over by the PU, I'm not usually too concerned about foul code. When I put them in myself, sometimes things don't go so well 😈. For this particular example, it was derived from several remarks and examples ...

* Steve: https://github.com/dotnet/aspnetcore/issues/17361#issuecomment-558138782
* Steve, Javier, and Tanay all saw 👁️ and didn't remark on the example at: https://github.com/dotnet/aspnetcore/issues/13358#issuecomment-582057368
* Artak approved the cross-link to the PU issue where it was discussed, and the PU issue led to the coverage here: https://github.com/dotnet/AspNetCore.Docs/pull/17453

However, just because they didn't say anything doesn't mean that it isn't a concern. Let's ask Tanay to look.

@TanayParikh TL;DR ... For the example below, do we need to sweat clearing the (non-static) list of `ReferenceChild` components in the `ReferenceParent3` component?

... **_AND_** ... This isn't just a good specific example question. It's also a great general question for this concept. It's rare for our doc examples to make `List<T>`/`Dictionary<TKey, TValue>` of components. I actually can't think of another spot off the top of my head. I'd like to place a general remark in this section. In addition to that specific ❓, is there anything else we can say? For example, should we say that if the list/dict is static, the dev should be mindful of GC? ... and also cross-link to [Cleaning up unmanaged resources](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/unmanaged) as we currently do over in the *Lifecycle* topic for a `System.Timers.Timer` example. 

`Shared/ReferenceChild.razor`:

```razor
@using Microsoft.Extensions.Logging
@inject ILogger<ReferenceChild> logger

@code {
    public void ChildMethod(int value)
    {
        logger.LogInformation("Received {Value} in ChildMethod", value);
    }
}
```

`Pages/ReferenceParent3.razor`:

```razor
@page "/reference-parent-3"

<ul>
    @for (int i = 0; i < 5; i++)
    {
        var index = i;
        var v = r.Next(1000);

        <li>
            <ReferenceChild @ref="childComponent" />
            <button @onclick="@(() => callChildMethod(index, v))">
                Component index @index: Call <code>ReferenceChild.ChildMethod(@v)</code>
            </button>
        </li>
    }
</ul>

@code {
    private Random r = new();
    private List<ReferenceChild> components = new();
    private Action<int, int> callChildMethod;

    private ReferenceChild childComponent
    {
        set => components.Add(value);
    }

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            callChildMethod = CallChildMethod;
        }
    }

    private void CallChildMethod(int index, int value)
    {
        components.ElementAt(index).ChildMethod(value);
    }
}
```

**Comment by mrpmorris** [comment]
I am using it to show a UI for multiple IBrowserFile instances selected by the user. The user can click a button to select multiple files which are added to the list, and can also click that button multiple times.

In addition, the user an click X on the item to remove it from the list..

If I clear the list then only new items are added. If I don't clear the list then it keeps hold of references to disposed components.

I think I will have to add more code so that when the source list changes it looks for a component that references that IBrowserFile and removes it from the component list.

I think this would need to be mentioned.

**Comment by guardrex** [comment]
> keeps hold of references to disposed components

But that's still managed AFAIK. We don't sweat GC for automatically-manged resources. **_We don't cover it by-design._**

If there seems to be a problem with GC and components (and it has to be **_in production code_** and **_without the debugger_** running), then the PU would have to address it on their repo. Due to how costly it is for them to research it in a specific use case/example, I'm certain that they need a really complete repro.

We'll leave it to @TanayParikh to suggest if ...

* There's a problem with the specific example in the doc.
* If a general remark about managing disposal for unmanaged types (e.g., statics) should be added.

Outside of those, I don't think we'll cover anything else, but he'll have to say.

I'm just a **_silly_** 🦖 **_here_** 😆. I leave the ✨ **_Magical .NET GC Stuff_**&trade; ✨ to the PU to sort out for coverage. 

I'll also mention on the side that this isn't quite the best spot (or the only spot, perhaps) if we do address something pertaining to `IBrowserFile` use in components, given that we have the [*File upload* topic](https://docs.microsoft.com/aspnet/core/blazor/file-uploads). If something for that specific case is covered, we'd probably put it there and then cross-link from here perhaps. Still tho, I kind'a think that we won't cover it unless there's an important *gotcha* 😈 to cover given that GC should still take care of these managed resources ... again, AFAMLUP ..... "*As Far As My Limited Understanding Permits*" 😄.
