### ISSUE TITLE
The final step of the article

### ISSUE THREAD

**Issue by iboxenT** [dotnet/AspNetCore.Docs#25355]
Great Article!

Done all the steps and it works!
I test it locally in debug and int works fine. 

BUT how do I deploy it to an Azure App?
To the created Server Application and its registration, I assume.
Updating client redirect URI to point at the Azure App URI.
Then authentication does not work!
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3039ff79-ee86-20b1-0082-d3899a84c823
* Version Independent ID: af4a3a75-ae52-5f6d-2120-737bc2fefb07
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @iboxenT ... Deployment is beyond the scope of the topic, and Azure has it's own doc set. The coverage that we maintain here is at ...

* https://docs.microsoft.com/aspnet/core/blazor/host-and-deploy/
* https://docs.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly#hosted-deployment-with-aspnet-core
* https://docs.microsoft.com/aspnet/core/host-and-deploy/ &mdash; This is the general hosting topic for ASP.NET Core, which is appropriate because a hosted WASM app is an ordinary ASP.NET Core app set up to serve the Blazor WebAssembly app. Just make sure that you're deploying the content of the `publish` folder, as the Blazor docs instruct.
* https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-apps/ &mdash; The general guidance that we keep on working with Azure App Service applies.
* https://docs.microsoft.com/aspnet/core/tutorials/publish-to-azure-webapp-using-vs &mdash; A basic tutorial for ASP.NET Core apps.

Azure docs are at https://docs.microsoft.com/azure/app-service/, and they have their own tutorials and reference docs.

Beyond that if you have other questions that aren't answered by the Azure docs, you'd need product support for Azure. We recommend the usual public support forums ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

**Comment by iboxenT** [comment]
Yes I know how to deploy an an application to an Azure App. Done many times!

But as I wrote; if I deploy the example in the article "server application and hosted client app" to an Azure App, connected to the server app registration in the example, and change client redirect URI to the new Azure App. I get authentication failure and it does not work from Azure, still works when I run it from localhost...

So any one who has taken the last "5" steps, to actually deploy this example to a functioning application in Azure, not just to test on you own local machine?

**Comment by guardrex** [comment]
It should work ... we have thousands of devs using this Blazor guidance (and the Azure guidance we maintain and the Azure docs maintained by the Azure docs division) to successfully deploy Blazor apps to Azure Apps. I think you have a configuration or deployment problem, but I have no way to know what the problem is from here. As I said, we don't provide Azure deployment support. If you don't have a MS Support Agreement, then I recommend accessing the docs that I cross-linked for troubleshooting guidance and reach out to the community for support on the usual support forums ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

I realize that you'd like me to figure out what's wrong with your app or deployment process, but it's not within the scope of my contract duties to offer product support to that degree. We just don't have the staffing to provide that level of product support. I will address a problem that you've discovered with the documentation. At this point, we don't know what the problem is, so there's nothing actionable for me to address at this time. When you find out what the problem is, you can leave a comment back here or open a new issue for something that you think the doc should mention about an Azure deployment if it isn't already covered here or in Azure docs.
