### ISSUE TITLE
nuget package failure

### ISSUE THREAD

**Issue by robindewitte** [dotnet/AspNetCore.Docs#25414]
When trying the tutorial for blazor in windows forms I found I had to use the package  [Microsoft.AspNetCore.Components.WebView.WindowsForms](https://nuget.org/packages/Microsoft.AspNetCore.Components.WebView.WindowsForms)

I had to use a webview tool in the windows forms design but this gave several errors (probably version related) I cannot show this error because of another weird quirk of that package. When trying to unistall/reinstall in an attempt to fix the problem I discovered that after reinstalling said pacakage the tool no longer appears... forever. After several reinstalls I have given up and I will now advance my project by making a datatable by more traditional means in blazor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0b88d48-74df-8dc4-446d-121e65b552ab
* Version Independent ID: b0b88d48-74df-8dc4-446d-121e65b552ab
* Content: [Build a Windows Forms Blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/windows-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/windows-forms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @robindewitte ... I'm not clear what you mean by, "I found I had to use the package." That's what the topic says that you **must** do ...

> Use [NuGet Package Manager](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio) to install the [Microsoft.AspNetCore.Components.WebView.WindowsForms](https://nuget.org/packages/Microsoft.AspNetCore.Components.WebView.WindowsForms) preview NuGet package.

As for the error tho, I can't assist in troubleshooting from here. The steps of the tutorial work here, and this content was approved by the PU ("product unit"). It's best for you to open an issue on the PU repo for assistance with this.

Open an issue here ...

https://github.com/dotnet/aspnetcore/issues

**NOTE**: They will need you to put up a minimal repro project in GitHub that demonstrates the error that they can pull down and run themselves (or even just inspect so that they can see how you have the app set up). You might need to add some VS screenshots to describe what's happening with your VS. Of course, provide all of the versions of everything ... the version of your VS preview, your .NET install, and the packages in use in the app.

At the end of your opening comment, please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/25414
```

I might re-open this for doc work depending on what they say. There might be something additional that we need to call out in the topic ... like a sneaky *gotcha* 😈 that we don't currently cover that would help devs get their app up and running. I'll close this for now and keep an 👂 open for your PU issue and follow the discussion there.
