### ISSUE TITLE
How to perform eager validation with IValidateOptions for complex validation

### ISSUE THREAD

**Issue by golfalot** [dotnet/AspNetCore.Docs#25431]
In the section [IValidateOptions for complex validation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-6.0#ivalidateoptions-for-complex-validation)

It is not documented how to properly do Eager Validation before app.Run() where configuration is critical, and cannot be delayed until DI.
I don't know the proper way of doing this, but I can get what I want this way

```
using Microsoft.Extensions.Options;
using OptionsValidationSample.Configuration;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllersWithViews();

builder.Services.Configure<MyConfigOptions>(builder.Configuration.GetSection(
                                        MyConfigOptions.MyConfig));

builder.Services.AddSingleton<IValidateOptions
                              <MyConfigOptions>, MyConfigValidation>();

var app = builder.Build();

// try to make option validation fail early
try
{
    _ = app.Services.GetRequiredService<IOptions<MyConfigOptions>>().Value;
}
catch (OptionsValidationException e)
{
    Console.WriteLine(e.Message.Replace("; ","\r\n"));
}

// don't know how to exit properly either (before app.Run())

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-6.0#additional-resources)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
You can use `ValidateOnStart`, being tracked in #24282.

**Comment by jibbers42** [comment]
@serpent5 I'm not sure #24282 answers this question. It deals with an `OptionsBuilder` from `AddOptions<TOptions>()`. This issue is about eager validation when using `IValidateOptions`. Unless I'm missing it, I don't see how to do eager validation when registering an `IValidateOptions`.

As an aside, `ValidateOnStart()` is attached to an `OptionsBuilder` from `AddOptions<TOptions>()` - does that mean `ValidateOnStart()` only applies to that particular `TOption`?

**Comment by Kizmar** [comment]
@jibbers42 That's currently what I'm trying to figure out as well. We are using services.ConfigureOptions<> with a configurer class that implements IConfigureOptions and IValidateOptions. I was trying to figure out how to force validation on startup instead of when they're injected. Ran into this ValidateOnStart, but can't figure out how to use it in conjunction with ConfigureOptions because it only exists on the OptionsBuilder.
