### ISSUE TITLE
Tutorial results in an error on first run

### ISSUE THREAD

**Issue by bradygaster** [dotnet/AspNetCore.Docs#25584]
Upon following the tutorial through to the end, the article has an error on the F5 experience. When the `StateHasChanged()` method fires in `Index.razor`, there's a threading issue resulting with the error message:

```
System.InvalidOperationException: 'The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.'
```

I'm working on a resolution to this issue and a resolution to the continuing issue related to following this tutorial in the context of an authentication-enabled version of the Blazor Server project as reported in [this tweet](https://twitter.com/ChrSandoy/status/1511334485786349587). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Version Independent ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Content: [Use ASP.NET Core SignalR with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio&pivots=server)
* Content Source: [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I assigned myself in case you just want to post the update information in a comment. Otherwise, please re-assign if you plan to work it to a PR.

btw ....

> to the continuing issue related to following this tutorial in the context of an authentication-enabled version of the Blazor Server project

Per MS tutorial guidelines, the fix for an auth-enabled scenario that isn't within the scope of the tutorial's learning objectives probably should go into one of the SignalR reference topics and then is cross-linked from this tutorial topic in its additional resources. They like to keep the tutorials focused on the scenario at hand ... minimal extra info ... minimal extra links ... minimal notes ... etc.

![joe_friday](https://user-images.githubusercontent.com/1622880/162518951-1c8f5da6-609d-473a-932d-fd03cf4be231.png)

  &mdash; **_"All we want are the facts, sir."_** Sgt. Joe Friday ([Jack Webb](https://www.imdb.com/name/nm0916131/)), [*Dragnet*]() &copy;1949-59 [NBCUniversal](https://www.nbcuniversal.com/)

**Comment by bradygaster** [comment]
Whilst I generally concur with you on this one, I'd almost argue that for a "next step" article beyond this one that would teach customers how to add the auth layer using the tools or CLI and then how to implement the naming provider to use the authenticated user's username. 

Seems like a great opportunity to carry on from this article. 

BTW, i think the fix for this is simply:

```csharp
InvokeAsync(StateHasChanged);
```

Instead of 

```csharp
StateHasChanged();
```

**Comment by bradygaster** [comment]
@guardrex I adore the giffery btw. thanks for being awesome. 

![stay-awesome-im-out](https://user-images.githubusercontent.com/41929050/162523734-71679326-bba4-4e52-b645-481add5ab1b6.gif)

**Comment by guardrex** [comment]
I recommend an issue for a new tutorial if you'd like it. Then DR/Artak can figure out how to proceed ... who writes it ... when ... etc.

I'll see if I can square this issue away first thing Monday morning.

**Comment by bradygaster** [comment]
Groovy! Quick intro to @jcjiang, who will be leading the charge on SignalR things with me over the next few months and beyond.
