### ISSUE TITLE
Blazor Webapp behind Azure Front Door

### ISSUE THREAD

**Issue by rupeshshet** [dotnet/AspNetCore.Docs#25603]
# Before you open an issue

If the issue is with an ASP.NET Core document:
 I am having to setup Blazor Webapp behind Front Door using AspNetCore. Is any one experience similar issue?

**Comment by guardrex** [comment]
Hello @rupeshshet ... Please use the **This page** feedback for a specific doc issue, if that's what this pertains to. However, it seems like you're asking about a general support problem. We only work on docs here, ***BUT*** let me provide what I know at this time for Front Door WRT Long Polling configuration.

https://docs.microsoft.com/aspnet/core/blazor/security/server/threat-mitigation#client-connections

Azure Front Door only supports Blazor Server at this time with **_Long Polling_**. Normally, WebSockets is the default transport. You'll even get a console warning if you use Long Polling. AFAIK tho, you'll need to use Long Polling until Front Door supports WebSockets.

Switch it off in the Azure Portal. I think there's guidance here ... https://docs.microsoft.com/aspnet/core/signalr/publish-to-azure-web-app#configure-the-app-in-azure-app-service

I think you set **WebSockets** to OFF or NO ... whichever the UI provides for.

I think the app configures it along the lines of ...

```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapHub<ChatHub>("/chathub", options =>
    {
        options.Transports = HttpTransportType.LongPolling;
    });
});
```

... but search in the SignalR docs in the main doc set to confirm that.

I'm going to close this as resolved with the only info that I have to convey :point_up:. If you require further assistance, open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/25603
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.
