### ISSUE TITLE
How do we console.log to the Browser developer tools for NET MAUI Blazor 

### ISSUE THREAD

**Issue by Assassinbeast** [dotnet/AspNetCore.Docs#25625]
[[Enter feedback here]](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/developer-tools?view=aspnetcore-6.0&pivots=windows)

The image at the bottom shows we can see error/exception logs.
But how do we add our own logging to the developer tools console?

I tried adding `builder.Logging.AddConsole();` and `builder.Logging.AddDebug();`, but it didn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48e7c079-a7e4-e0a4-ed19-935436113b70
* Version Independent ID: 48e7c079-a7e4-e0a4-ed19-935436113b70
* Content: [Use browser developer tools with ASP.NET Core Blazor Hybrid](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/developer-tools?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/developer-tools.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/developer-tools.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Assassinbeast ... A member of the product unit just added some additional content to this topic that might help.

After the call to `AddMauiBlazorWebView`, add the following code:

```csharp
#if DEBUG
    builder.Services.AddBlazorWebViewDeveloperTools();
#endif
```

If that doesn't work, open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/25625
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.

**Comment by KieranDevvs** [comment]
I raised this issue and was told that its not an issue and was by design: https://github.com/dotnet/maui/issues/4066

Kind of getting tired, of the team replying to issues and instantly closing them without waiting for a reply.

Glad we can now use the browser console to log though!

**Comment by guardrex** [comment]
> Kind of getting tired, of the team replying to issues and instantly closing them without waiting for a reply. HINT: you might not have understood the ticket correctly. Wait for all parties to be on the same page before you slam the the door shut.

I can't tell if you're referring to *me or them*. We have special rules here on the docs repo, which I can explain out if you want, but I think you might be referring to them.

This is a case where the behavior is confusing generally for Blazor Server/WASM. For example, I think the Blazor Server logging guidance should say (similar to the case here for .NET MAUI) that **_NOT_** logging to the dev tools console is by-design. I assume that in the Blazor Server case that the dev can either use a third-party package (*if any such package exists*) or use JS interop.

Getting back to your request: You asked about proper ASP.NET Core logging messages via a Razor component getting piped through to the dev tools console for .NET MAUI apps. Is the following discussion basically your ask here:

https://github.com/dotnet/maui/discussions/6091

That still looks unresolved because the dev tried Tanay's suggestion and it didn't work.

> So where is `System.Console` intended to flush to under Blazor MAUI?

I think the implication of Artak's response is that it only goes to the .NET console, which would be the case for normal ASP.NET Core logging.

I at least see **_HALF_** of what docs need to address (Blazor Server/WASM), and I think for Blazor Hybrid that we'll need to do some work in the *Dev Tools* topic to cover these behaviors.

**Comment by KieranDevvs** [comment]
> I can't tell if you're referring to me or them. We have special rules here on the docs repo, which I can explain out if you want, but I think you might be referring to them.

I was referring to the issue I raised but its more of a general consideration really. I've raised the issue because I expected certain behavior, and essentially all you get back is "This isn't an issue... issue closed.". 

This is a community, maybe a community member has a work around, or there's information to provide more guidance, or discussion can be had about the issue to gain traction for a new feature, etc. But it feels more like a first line support help desk.

I've been told multiple times that the .NET team gauge priority of work by community input by them thumbing up posts and engaging with them, yet I've had several issues instantly closed. How is anyone supposed to engage with such a blunt system and unproductive? (I don't expect you to answer that personally)

Your reply also goes to show that there was more information and clarification that could have been provided and maybe someone could have given that if it was left open for a while.

**Comment by guardrex** [comment]
Right, I hear you on that feedback, but it's out of my area of responsibility. The PU ("product unit") has to receive that feedback for it to be actionable. We're more *compartimentalized* than many think.

WRT the scenario, my guess on this looks like it might be correct: JS interop will work. It's on the discussion now from Tanay's answer.

**Comment by guardrex** [comment]
Ok, we're going to close this after all.

Yes ... if it's a design spec for your app ... try the JS interop approach that Tanay calls out in that discussion. We'll continue to take feedback. They might even develop a bonafide framework feature for this scenario.

I'll just wrap up the docs side of ...

> could have been provided and maybe someone could have given that if it was left open for a while

That's not the way that we triage issues here for work. Generally, it either gets scheduled and gets worked, gets held because it's blocked by something, or it gets closed. For general discussion (and general support for that matter), it would be something for a public support channel. We recommend the usual places, such as ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)
* [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor) (Community-maintained collection of Blazor resources)

I'll direct devs to the discussion issue if it comes up again here, and I'll keep an 👂 and an 👁️ open for the PU possibly making a real feature out of dev tools console logging from ASP.NET Core logging.
