### ISSUE TITLE
Lack of clarity with redirect Uri

### ISSUE THREAD

**Issue by ordinaryorange** [dotnet/AspNetCore.Docs#25696]
A lot of the documentation on AAD authentication such as this page, specifies a redirect uri of `https://localhost:{PORT}/authentication/login-callback`

However after much time fighting it, I discovered that a pure WASM client side only Blazor app served from a static HTTP source (such as Azure storage static website) won't work with this redirect Uri.

If the Uri is updated to just "https://localhost:{PORT}/" then the login process will complete successfully.

A lot of the documentation is not clear on the purpose of the redirect Uri (other than specifying that it is needed), and in this page in particular there are no details for statically served blazor apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92b9c5cb-0e48-25bc-2b7e-e7354bafbe2d
* Version Independent ID: b1e8aedc-b46b-41f1-55c1-e293bc6c93db
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ordinaryorange ... We don't cover that specific scenario ... just running locally is all we address, nor can we cover *every* scenario here ... and I can't even confirm that you are correct about that in the first place. We link out to MS Identity docs for specifics on settings and configuration. For example ...

https://docs.microsoft.com/azure/active-directory/develop/msal-client-application-configuration#redirect-uri

We don't maintain the Microsoft Identity AAD docs here. We're **_highly compartmentalized_** ... more so than most people think. If they're deficient in covering something for MS Identity, then you'd need to open an issue for them using the **This page** feedback on their topic. That's a whole different docs team made up of different folks.

The Blazor security topics in this repo are just here to get devs started with a basic AAD scenario running the app in the debugger. We're even considering dropping some or all of the topics in this node because these were put up at a time when there were NO topics over in MS Identity for Blazor. Now, they have tutorials of their own, so MS is now maintaining **_duplicate coverage_**, which is *costly* 💰. For example ...

https://docs.microsoft.com/azure/active-directory/develop/tutorial-blazor-webassembly

You can try that one to see if they do a better job of covering the redirect URL. If not, I'd recommend telling them (specifically, I think it will be Jean-Marc Prieur) about the lack of coverage (or request to cross-link to helpful coverage). If we do drop coverage here, that tutorial ☝️ is the one that we'll point to (and redirect to) as **_THE_** tutorial for this experience.

Thanks for writing in on the topic. We take every request very seriously.
