### ISSUE TITLE
Hosted deployment with multiple Blazor WebAssembly apps on different subdomains

### ISSUE THREAD

**Issue by lonix1** [dotnet/AspNetCore.Docs#25723]
A lot of effort went into the ["Hosted deployment with multiple Blazor WebAssembly apps"](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#hosted-deployment-with-multiple-blazor-webassembly-apps) section. It shows how to host two blazor apps for separate domains.

There's another (more common) scenario:

|subdomain|user|tech|
|-|-|-|
|api.example.com or<br/>www.example.com/api|-|web API (that supports Blazor apps)|
|www.example.com|visitors|server rendered (MVC, RazorPages) or SPA (Blazor)|
|app.example.com|customers|SPA (Blazor)|
|admins.example.com|staff|SPA (Blazor)|

Those are multiple blazor apps, on different subdomains (rather than different paths).

Is this possible? If so, it would make a great addition to this document. I'm struggling with this, and by the looks of it on StackOverflow this is a common use case. Please provide guidance?

Thanks! (BTW the quality of this document series is excellent!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#hosted-deployment-with-multiple-blazor-webassembly-apps)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @lonix1 ...

> It shows how to host two blazor apps for separate domains.

... or subdomains. That's not a blocker for this approach, IIRC. The paths are just for routing the requests **_after they hit the ASP.NET Core app hosting the Blazor WebAssembly apps_**. My recollection is that these apps can be accessed at `firstapp.com` and `secondapp.com`, which also could include subdomains. The port is a factor in the example because hosting locally without messing with your `hosts` file or other local network gymnastics is a nice way to demo this. AFAIK, this code/approach can be configured to use subdomains. I admit that the 😈 is in the details on doing it, but I think someone would need to open an issue showing how this approach won't work for what you're requesting before we proceed to take any **_immediate_** action. I think you mentioned the right approach in working with devs on public support channels. We recommend the usual spots ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](http://tattoocoder.com/aspnet-slack-sign-up/)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)
* [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor) (Community-maintained collection of Blazor resources)

I'll schedule this for a look on my UE tracking issue, but no promises on reaching it in the near-term with all of the high priority work going on through the end of the year ⛰️⛏️😅. This issue will be closed, but the tracking issue will keep a reference to this issue. If it is worked, it will be worked from there. We do this on the low priority/optional issues to help keep the backlog clean.

**Comment by guardrex** [comment]
... and btw ... yes, it's more complicated if you want to integrate MVC/RP as the hosting app per ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly

Yes. I agree with you on that point. Perhaps, a cross-link at least for the scenario is the low-hanging fruit. However, I think if you start with the hosted Blazor WebAssembly app (the ASP.NET Core app that's serving the client apps) configured for mulitple apps ... then roll in the integration aspects for MVC/RP into that app that it should ✨ **_Just Work!_**&trade; ✨. I haven't done it. In theory, there's no blocker that I'm aware of.

I'll consider this when I reach it on the tracking issue. I can't look further in the near-term given the workload right now. It won't get lost tho.

**Comment by guardrex** [comment]
I think I **_WILL_** do that. I'd like to cross-link with a remark that the hosting app can integrate MVC/RP. That's at least a temporary fix.

Leave this issue open. It will close automatically when the PR merges.

**Comment by lonix1** [comment]
Thanks for the tips, I think they'll help crack this problem. If (when!) I succeed, I'll post back here with some working code.

BTW what is "UE"?

**Comment by guardrex** [comment]
"UE" = "User Experience" ... just jargon we use for improving docs.

**Comment by lonix1** [comment]
FYI (see, I can also do acronyms :smile:)

I haven't decided yet, but I'm gravitating towards completely separate apps, albeit in a single monorepo. I've opened a question [on StackOverflow](https://stackoverflow.com/q/72007750) for other devs' experiences in this matter.

I know this is a tricky use case - so it's not a criticism at all - but the config required to implement **and maintain** multiple apps in a single server app is quite scary. In fairness, it's hard in Node and other tech stacks too.

**Comment by guardrex** [comment]
This isn't going to be a long wait. I have time right now to see if I can address it further with a PR. I'll ping you on the PR when it goes up.

**Comment by lonix1** [comment]
Wow that was a lot of work! When do the new docs go live?
