### ISSUE TITLE
asp-append-version only works for StaticFiles in wwwroot

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet/AspNetCore.Docs#25744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I am adding a new `AddStaticFiles` middleware, the asp-append-version attribute only works if the file is in **wwwroot**.  My repro case has two AddStaticFiles:

```csharp
app.UseStaticFiles();
app.UseStaticFiles(new StaticFileOptions()
{
  FileProvider = new PhysicalFileProvider(
    Path.Combine(builder.Environment.ContentRootPath, @"Other"))
});
```

Then my index.cshtml has:

```razor
  <script src="~/js/site.js" asp-append-version="true"></script>
  <script src="~/site.js" asp-append-version="true"></script>
```

- The first script works fine (it is in `wwwroot/js/`).
- The second script renders without a version (it is in `/Other/`);

I suspect that this line in the DefaultFileVersionProvider is at fault:

https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Mvc/Mvc.Razor/src/Infrastructure/DefaultFileVersionProvider.cs#L72

### Expected Behavior

Both .js files should have versions (or at least a console message explaining why it isn't).

### Steps To Reproduce

See the repro here:

https://github.com/shawnwildermuth/AppendVersionRepro

Should see that the second .js file doesn't not get version appended.

### Exceptions (if any)

None.

### .NET Version

6.0.202

### Anything else?

Just using default ASP.NET Core version with .NET 6:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Other\site.js">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>

```

**Comment by boggye** [comment]
I would like to re-open this. In .Net 8.0 I have a case where I want to serve  JavaScript files from a different static folder than wwwroot in order to protect them as per this [doc](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-8.0#static-file-authorization). That documentation suggests to place the UseStaticFiles after UseAuthorization and use a different folder as the root of the files, which is what followed only to discover now that `asp-append-version="true"` doesn't work anymore.

**Comment by shawnwildermuth** [comment]
@boggye Does this make it work for you:

https://github.com/dotnet/AspNetCore.Docs/issues/25744#issuecomment-1110171884

**Comment by boggye** [comment]
Hi Shawn - it doesn't work because I have to have the web assets (images, css) in wwwroot and I also want to protect some JavaScript files used in different pages that can be accessed only by authenticated users. Initially I had these JS files under wwwroot, but it turns out that they can be accessed by anonymous users. So, to protect them, as per the Microsoft documentation (the link is in my previous message) I have to place these files in a folder that is outside wwwroot and serve them via another UseStaticFiles which has to be placed _after_ UseAuthorization. When I do that, `asp-append-version="true"` ceases to work. Imo, this issue that you reported should be fixed properly.
