### ISSUE TITLE
Add _taskQueue snippet to document

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#25758]
@fiyazbinhasan  see [Add `IBackgroundTaskQueue`](https://github.com/dotnet/AspNetCore.Docs/pull/25701#pullrequestreview-955642679)  and [this comment](https://github.com/dotnet/AspNetCore.Docs/pull/25701#discussion_r860307618)

Can you add `_taskQueue` to your sample?
Take a look at all the comments by `@halter73` in #25701

See #25759 for an implementation. 
code written in  #25787, just need to update doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc35621-ae53-cfb5-5eb1-07aefdc5342f
* Version Independent ID: 79cb05f8-9ac0-26a8-8434-15de071160c3
* Content: [Access HttpContext in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/http-context.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-context.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @coderandhiker
* Microsoft Alias: **riande**

**Comment by fiyazbinhasan** [comment]
`huan086`'s https://github.com/dotnet/AspNetCore.Docs/issues/25759 queue implementation is quite different from https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio#queued-background-tasks

Is there anything wrong with the existing implementation that is in the [doc](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio#queued-background-tasks)? If yes, maybe I'm missing the core details. @Rick-Anderson need your feedback.

**Comment by Rick-Anderson** [comment]
Take a look at all the comments by @halter73 in https://github.com/dotnet/AspNetCore.Docs/pull/25701 esp Take a look at all the comments by @halter73 in https://github.com/dotnet/AspNetCore.Docs/pull/25701

**Comment by fiyazbinhasan** [comment]
If I understood this comment,

> Unfortunately, doing background processing the right way is a lot more complicated. Really we should be doing something like what's shown in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio#queued-background-tasks. Can we just reference the BackgroundTaskQueue from there?

We could just use the queue implementation available in the doc which uses a `Channel<Func<CancellationToken, ValueTask>>` as a queue whereas in https://github.com/dotnet/AspNetCore.Docs/issues/25759 we have a `ConcurrentQueue` with a `SimaphoreSlim`. Is there any issue with one of the implementations? 

I would rather use the implementation that is in the doc since it's quite readable and easy to understand.

@huan086 @halter73 any thoughts?

**Comment by huan086** [comment]
I wasn't aware that we have Channel now. Channel is awesome stuff and we should definitely be using it instead of ConcurrentQueue.

Years ago I looked at the ConcurrentQueue implementation and it contained a spin lock, which is not suitable for web applications. So let's use Channel.

As for Channel<Func<CancellationToken, ValueTask>> specifically, we should test for whether capturing request scoped service would result in ObjectDisposedException.  I strongly suspect it would. The solution would be to only put POCO in the Channel and create a new scope to resolve services in the BackgroundService

**Comment by Rick-Anderson** [comment]
Fixed in #25787
