### ISSUE TITLE
Why does @Body have an upper-case B, when @code is lower-case C?

### ISSUE THREAD

**Issue by LordScree** [dotnet/AspNetCore.Docs#25817]
Just learning Blazor (loving it btw). I received an error when messing about with Layouts for the first time, and realised I had used `@body`, not `@Body`. I was surprised, because `@code`, `@inherits`, `@page` and all other @ declarations seem to start with a lower-case letter, except `@Body`. Why is this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 251fbc5f-ce3e-4036-ba2b-f641d7de4e27
* Version Independent ID: 58e0022a-ac6c-9bf8-380a-40b7d068a887
* Content: [ASP.NET Core Blazor layouts](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/layouts?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/layouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @LordScree ... I can only guess that it's the only directive that directly renders the HTML tag of of the same name; whereas for the others, they don't render a tag of the same name. That's really a *wild guess* tho. I note in passing that `@RenderBody` is uppercase, so that seems kind'a like it's leaning in the same direction as `@Body` on this point.

Please open this question for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/25817
```

... to the bottom of your opening comment so that I follow along.

I see two things that we'll probably eventually do on the docs side after they answer your question on this ...

* I think the docs at https://docs.microsoft.com/aspnet/core/mvc/views/layout (for `@RenderBody`), https://docs.microsoft.com/aspnet/core/mvc/views/razor (probably needs entries for both `@Body` and `@RenderBody`), and this [Blazor topic on layouts](https://docs.microsoft.com/aspnet/core/blazor/components/layouts) should have additional coverage.
* The coverage here and in the Razor syntax/layout docs can state the reason for the use of uppercase for `@Body`/`@RenderBody` ... and for anything else in the Razor syntax world that uses uppercase that I might discover later.

I'm going to leave this open for work based on the feedback that you receive from the product unit. This issue will close automatically later when the PR merges. Until then, I look forward to seeing what the product unit tells you. Thanks for inquiring on this subject.

**Comment by LordScree** [comment]
@guardrex thanks for your quick reply! I'm not sure the `@Body` declaration renders the HTML `<body>` tag. The layout in the [Microsoft Learn tutorial example](https://docs.microsoft.com/en-gb/learn/modules/use-pages-routing-layouts-control-blazor-navigation/6-build-reusable-component-using-layouts) starts with a `<div>`.

I think the _Host.cshtml file contains the `<body>` tag, and the Blazor app is rendered wherever this element is added:

`<component type="typeof(App)" render-mode="ServerPrerendered" />`

Like I said though, I'm still working through the basics.

Looking back at the [Blazor docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/layouts?view=aspnetcore-6.0), there is a mention of `Body` being a property of `LayoutComponentBase`, which I missed before asking this question. As the convention for C# public properties is for them to start with an upper-case letter, I suspect this might be the reason. Whereas `@page`, `@code`, etc. are purely syntactic, `@Body` references the content of the `Body` property... something like that?

This section:

> Inherit the component from [LayoutComponentBase](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.layoutcomponentbase). The [LayoutComponentBase](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.layoutcomponentbase) defines a [Body](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.layoutcomponentbase.body#microsoft-aspnetcore-components-layoutcomponentbase-body) property ([RenderFragment](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.renderfragment) type) for the rendered content inside the layout.

I'm happy to still add an issue to the product unit, if you like, but I now feel silly for not spotting this myself before asking!

**Comment by guardrex** [comment]
Oh, yeah ... that makes more specific sense than what I was thinking. It also matches other properties, which would be uppercase in C# and uppercase in the Razor syntax. ...... and `@RenderBody` is like that, too ...

https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Mvc/Mvc.Razor/src/RazorPage.cs#L29

**Comment by guardrex** [comment]
That seems reasonable. I don't think you need to open a product unit issue after all now. I think you have come up with the correct answer. I will get a review on the PR so that we can confirm it.

Leave this open, as it will close automatically later when the PR merges. I'll ping u on the PR when it goes up.

**Comment by guardrex** [comment]
Hummmmm ... It's not listed in the docs as a formal, built-in Tag Helper, **_BUT_** ...

https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Razor/src/TagHelpers/BodyTagHelper.cs

... and that would explain it 🤔.

**Comment by guardrex** [comment]
I see now ... it **_IS_** `LayoutComponentBase.Body`.

So, yes for Blazor on that one ... it's the `Body` property there.

In RP, it's the `RenderBody` property.

Ok ... I think I'm clear enough to float the PR next week. We'll have the product unit take a look at the language to make sure that I'm not fouling it up!

**Comment by LordScree** [comment]
I'm not that familiar with Tag Helpers, but `[HtmlTargetElement("body")]` suggests the purpose of this Tag Helper is to create an HTML `<body>` element, am I right? But I don't think that's what's happening when `@Body` is called.

**Comment by guardrex** [comment]
Yeah ... that was a 🤔🐠 *thinking outload* dead end. 😄

**Comment by LordScree** [comment]
That's awesome, thank you for your help and the discussion :smile: 

This is certainly clearer to me now, and if my question helps to clear this up for anyone else, it wasn't in vain!

**Comment by guardrex** [comment]
Note to self ... the two spot to 👁️ in Components overview are ...

* https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0#markup
* https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0#component-parameters
