### ISSUE TITLE
Why do we need to purchase a product (Duende Identity Server) to add any authentication?

### ISSUE THREAD

**Issue by sy-huss** [dotnet/AspNetCore.Docs#25832]
The documentation states that we need to purchase Duende Identity Server to add any authentication to Web API created; why is there a need to purchase a Third-Party product in order to authenticate with Azure AD?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio#add-authentication-support-to-a-web-api)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
@Rick-Anderson,

There are three solutions options suggested, Duende is not presented as the only option.  Duende being listed last, but it is the only one we center on after mentioning those three.  Maybe this is just a matter of a better introductory sentence for Duende so we don't give the impression it is weighted more to look like "the" option?  (I don't know this area as well, which is why I am asking.) 

<img width="610" alt="image" src="https://user-images.githubusercontent.com/10985336/167926919-2a0f6f4a-8fad-4831-9f6b-56c16d16a9c1.png">

**Comment by guardrex** [comment]
Cross-referencing the related PU remarks on the subject:

* https://github.com/aspnet/Announcements/issues/464
* https://github.com/dotnet/aspnetcore/issues/32494

**Comment by guardrex** [comment]
@sy-huss ... Are you being forced to purchase tho? Do meet the threshold? ...

> The license requires [a fee](https://duendesoftware.com/products/identityserver#pricing) to be used in used in a commercial setting if the entity or organization makes more than 1M USD/year.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
