### ISSUE TITLE
How does a Blazor circuit work?

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#25855]
Is it a websocket connection? If I call e.g. EF Core's `SaveChanges()`, is that sent via JavaScript or a websocket API call?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@mrlife ... I'm slammed at the moment. I'll get to this sometime next week ... *stand-by* 🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️😅

**Comment by guardrex** [comment]
**UPDATE (5/16)**: I've pinged management to respond. I know that they don't want to get into **_shifting implementation details_**. However, they might want to provide a bit more detail on circuit design/functioning. Let's see what they say. *Stand-by!*

WRT ...

> Is it a websocket connection?

Yes, SignalR that defaults to a WebSockets transport. We cover that later down the ToC (e.g., Fundamentals > SignalR and in hosting coverage).

> is that sent via JavaScript or a websocket API call?

That's part of why I wanted to ping management. To date, they've been resistant to describing circuit design and functioning at that level, at least partially because the implementation in the framework is a moving target as advances occur.

**Comment by guardrex** [comment]
@mrlife ... Management says that we don't want to get into further implementation details on circuits.

For one thing, the framework implementations change quite a bit release-to-release. We don't want to document in detail rapidly changing, evolving tech. We don't have the cycles 🏃 to keep up, and ...........

The other thing is usefulness for the general LOB devs out there. Most devs don't need to be aware of the complex underlying framework aspects in order to resolve the LOB specs for their apps. If a dev is working on a deeper level with the framework, they have access to the ref source and should research further there. After all, we don't place internal bits in the API docs. Devs need to look at the ref source even for the internal API PU comments. Of course, PU repo issues/PRs fill in quite a bit on design and details that don't appear in ref source. Further, there are devs who have delved into the framework details and written in-depth blog posts on how aspects of Blazor circuits work at a low level.

Leave this open tho. Dan would like me to make a small change to the hosting topic's remarks on circuits. It's just a NIT, but I'll use this issue to close out his ask. As part of that, I'm going to try and add a quick 'it's a WebSocket transport' remark to where it says SignalR is used, and I might cross-link that, too.

**Comment by mrlife** [comment]
@guardrex Thank you for all of this! It's helpful to read. The very last sentence of the quoted part, I don't quite understand.

> I think we already say in this doc that your code in a Blazor Server app is executed from the server.

Doesn't C# code in a Blazor Server app get converted to JavaScript that runs in the browser?

**Comment by guardrex** [comment]
No ... it runs on the server. I think Dan is right that we say it in a few spots. I'll check everything to see how the hosting models topic handles remarks on that, too.

There will be a short delay tho ... perhaps only to tomorrow. Today is **_RELEASE DAY_** 🎉🕺💃🍾. I'll have quite a bit of Blazor Hybrid work to do today. Soon tho, I'll be free to work on this.
