### ISSUE TITLE
Manage environment settings for MAUI Blazor apps

### ISSUE THREAD

**Issue by robertwood62** [dotnet/AspNetCore.Docs#26020]
[EDIT by guardrex to update the content and change the issue title]

Could you add a section on how to manage environment settings for MAUI Blazor apps?

**Comment by guardrex** [comment]
@robertwood62 ... Ok, yes. I was told that my hunch is correct that this is a general MAUI framework scenario. Please open an issue to add guidance to the MAUI docs at ...

https://github.com/dotnet/docs-maui/issues

Use the **New issue** issue button to open it because I don't see an obvious topic for using a **This page** feedback issue.

**Comment by robertwood62** [comment]
Thanks Luke.

I've opened a new issue for the MAUI guys.
