### ISSUE TITLE
An issue found in Get Started -> Add the database exception filter EF 5 Tutorial

### ISSUE THREAD

**Issue by kaczma1x** [dotnet/AspNetCore.Docs#26123]
Hi Mates,
I found an issue in the section mentioned above:
https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-5.0#add-the-database-exception-filter
Trying to use AddDatabaseDeveloperPageExceptionFilter there is an error:
 "Error CS1061 'IServiceCollection' does not contain a definition for 'AddDatabaseDeveloperPageExceptionFilter'..."
 I also found a solution on the stack:
 https://stackoverflow.com/questions/65007086/services-adddatabasedeveloperpageexceptionfilter-error-code-cs1061
 Installation of:
 https://www.nuget.org/packages/Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore/5.0.17?_src=template
 Solved the problem as mentioned in the stack thread. 
 I think it would be very helpful for a quite fresh beginner inASP.NET to solve the issue. Of course, if it is not a planned bug to force beginners to learn how to solve similar problems in the future ;) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
Thanks very much @kaczma1x for taking the time and effort to file this issue and providing details.

The topic this issue is against is for version 5.0.  The 5.0 versions as you point out should specify the earlier 5.0 compatible versions of packages rather than pointing to the latest ones.  

Outside of the scope of this issue is that the 6.0 version of the topic is still 5.0 instruction.  It has not been updated.  But I believe that is already been tracked as separate issue and will verify.
