### ISSUE TITLE
onpointerenter, onpointerleave doesn't support currently at blazor.

### ISSUE THREAD

**Issue by pkostaki** [dotnet/AspNetCore.Docs#26194]
Blazor (server hosted) doesn't support events onpointerenter, onpointerleave, but documentation mentioned it as supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa724f22-3a49-c7f6-1500-ac2d8dde5894
* Version Independent ID: 5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0
* Content: [ASP.NET Core Blazor event handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @pkostaki ... Those should be supported ...

https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Web/EventHandlers.cs#L75-L76

Open this for the product unit for investigation. Be sure to show your code tho ... either post the Razor component code in the issue or place it into a repro app in GH that they can pull down and run. 

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/26194
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.
