### ISSUE TITLE
Disposing a component section could include more details

### ISSUE THREAD

**Issue by Owenll66** [dotnet/AspNetCore.Docs#26192]
In `Component disposal with IDisposable and IAsyncDisposable` section, could this article explain a bit more about why a component doesn't implement the [dispose pattern](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose) in the given examples?

For a component base such as [InputBase](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputBase.cs) (Sourced from aspnetcore source code). Since it is a non-sealed class, can it explain a bit more why it doesn't call `GC.SuppressFinalize(this);` in the `Dispose()` method:
```csharp
void IDisposable.Dispose()
{
    // When initialization in the SetParametersAsync method fails, the EditContext property can remain equal to null
    if (EditContext is not null)
    {
        EditContext.OnValidationStateChanged -= _validationStateChangedHandler;
    }

    Dispose(disposing: true);
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Razor component lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Owenll66 ... I don't think we want to expand this further because devs only need to be concerned about disposal of **_unmanaged resources_**, which are fully described in the cross-linked content and aren't present in the component examples that I think you're referring to that don't call `Dispose`/`DisposeAsync`. I think all we need to show here is how to do it in a Razor component with the few extra remarks that the product unit felt like were important to state. Devs should access the linked content in the memory management docs for all of the *juicy details* 😄.

If you come up with a special case or some scenario that's somehow unique to Blazor that isn't covered, then we could ask the product unit about covering that aspect, but nothing jumps to mind outside of what the product unit wanted to cover here.

WRT `SuppressFinalize` ... If the type has no finalizer, it no-ops. Again, I'd leave this to the memory management docs ... it's covered there ... which we cross-link.
