### ISSUE TITLE
Sample project for Blazor Hybrid authentication and authorization would be great help

### ISSUE THREAD

**Issue by Dukenware** [dotnet/AspNetCore.Docs#26258]
As the title suggests, the article in itself is a great help but sample project would be of great use as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb3ca917-28cc-126f-a7ff-3ff00ad30677
* Version Independent ID: cb3ca917-28cc-126f-a7ff-3ff00ad30677
* Content: [ASP.NET Core Blazor Hybrid authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Dukenware ... We don't want to maintain sample apps for those scenarios here at this time. For one thing, it's difficult for us to maintain very many sample apps with all of the churn and with only one doc author here to maintain all of the Blazor docs ... **_ME!_** 🦖😆. Such samples might be available via the cross-linked primary framework docs for MAUI, WPF, or WinForms, MS Identity Platform docs, or Azure-specific tutorials/samples in the Azure docs. Those are all external doc sets to this one, so any requests for more docs/samples on the authn/z subject should be submitted to those doc teams via the **This page** feedback button+form on their topics. We're rather highly compartmentalized, and you can think of those doc sets as being independently managed to a great degree.

However ... having said all of that ... I will mention this to management on our next Blazor meeting, possibly as early as this Friday just to confirm that this is all of the coverage that they currently wish to carry. It might take another week or two tho to discuss it, as several of us ... *including myself!* ... are out on vacation this week ⛱️🍹. Then, we have the three-day 🧨 *July 4* 🎆 holiday weekend.

Let's leave this open until I can get a firm answer. I'll respond back here within a few weeks, or management will respond directly here.

**OK** 😄 ... *back to my vacation!* 🎉🕺💃

**Comment by guardrex** [comment]
We're not going to provide samples at this time. It's unlikely that we would ever provide such samples due to the high maintenance costs relative to the worker-hours available to maintain the documentation here and the fact that these technologies are actually covered by external doc sets to this one (Identity for security aspects, Azure for Azure hosting scenarios, .NET MAUI docs for that framework) ... we only focus on Blazor aspects here. Even if we did provide such samples here, it wouldn't be anytime soon given that the work for .NET 7 has started, and that work will keep us quite busy right through the end of '22. Management has a constant 👂 open for community feedback, and they'll let me know if one or more samples for these scenarios becomes a priority.
