### ISSUE TITLE
Official stance on comments in appsettings.json

### ISSUE THREAD

**Issue by kimjamia** [dotnet/AspNetCore.Docs#26254]
Given that comments work in appsettings.json and it's a pretty [common](https://github.com/dotnet/AspNetCore.Docs/issues/11114) [question](https://github.com/dotnet/runtime/issues/27761#issuecomment-434113532) too, it would be useful to clarify the official stance on [this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#appsettingsjson) page.

One very helpful possibility would be to instruct how to configure the [JSON configuration provider](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#jcp) to explicitly [support comments](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-invalid-json?pivots=dotnet-6-0#allow-comments-and-trailing-commas).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#appsettingsjson)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 33225](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33225)

**Comment by JamesNK** [comment]
Comments are intentionally allowed in appsettings.json. You can add that to the docs.

**Comment by guardrex** [comment]
What are the rules for use so that the parser doesn't choke?

1. Must they be on their own line? ... or can they appear at the ends of lines, too?
1. Is /* ... */ syntax also supported? ... or only //?
1. Should they avoid JSON delimiters (e.g., {, }, [, ], /)? ... or any other chars?

**Comment by JamesNK** [comment]
JSON comments behave like JS (or C#). Both styles are supported.

https://www.w3schools.com/js/js_comments.asp

**Comment by JamieLaing** [comment]
> Comments are intentionally allowed in appsettings.json. You can add that to the docs.

BTW... to get Visual Studio Code to stop complaining, do this: https://stackoverflow.com/questions/47834825/in-vs-code-disable-error-comments-are-not-permitted-in-json/47834826#47834826

**Comment by lukas-shawford** [comment]
Another option is to rename your `appsettings.json` to `appsettings.jsonc` (and your environment specific config files as well, so `appsettings.Development.json` becomes `appsettings.Development.jsonc`, and so on).

Then add this near the top of Program.cs:

```
var builder = WebApplication.CreateBuilder(args);
IHostEnvironment env = builder.Environment;

builder.Configuration
    .AddJsonFile("appsettings.jsonc", true, true)
    .AddJsonFile($"appsettings.{env.EnvironmentName}.jsonc", true, true);
```

Then right click on each appsettings file and make sure to set **Copy to output directory** to **Copy if newer**, as otherwise these files no longer automatically get copied if you change the extension.

Now you can add comments to all of your jsonc files, and not have to instruct other developers to change their editor settings to get the file to show up without syntax highlighting errors.

**Comment by german-diago-codeleap** [comment]
I did some cleanup and merged again.

Instead of removing the keys from appsettings.json I commented them out for better discoverability since appsettings.json supports comments. If this is concerning ping me and I will remove directly, but I think it is the better way to do it since this way just by scanning appsettings.json you know the possible keys.

**Comment by nadirvishun** [comment]
Why not add support for `yaml` format? Just like any other language

**Comment by guardrex** [comment]
@nadirvishun ... We only work on documentation on this repo. Product feedback goes to the product unit's repo.

This PR is collecting feedback, and we don't work from closed issues/PRs. I'll lock it now. Open a new issue for doc feedback from the bottom of any article.
