### ISSUE TITLE
Microsoft.JSInterop.JSException: triggerFileDownload is not defined

### ISSUE THREAD

**Issue by frankleib** [dotnet/AspNetCore.Docs#26298]
Microsoft.JSInterop.JSException: triggerFileDownload is not defined

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4ad584d-0d9a-da8c-1296-b2d186e437ad
* Version Independent ID: e4ad584d-0d9a-da8c-1296-b2d186e437ad
* Content: [ASP.NET Core Blazor file downloads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-downloads?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/file-downloads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-downloads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **taparik**

**Comment by guardrex** [comment]
Thanks @frankleib ... I just overhauled this but didn't catch that because my JS functions from both sections were in the same sample app. Let's replace that call in the JS FN with the lines from the `triggerFileDownload` FN in the next section. The final FN will be ...

```javascript
window.downloadFileFromStream = async (fileName, contentStreamReference) => {
    const arrayBuffer = await contentStreamReference.arrayBuffer();
    const blob = new Blob([arrayBuffer]);
    const url = URL.createObjectURL(blob);
    const anchorElement = document.createElement('a');
    anchorElement.href = url;
    anchorElement.download = fileName ?? '';
    anchorElement.click();
    anchorElement.remove();
    URL.revokeObjectURL(url);
}
```

I'll make that change now in the topic and in the sample apps of the `dotnet/blazor-samples` repo.

**Comment by frankleib** [comment]
@guardrex  it doesn't work correctly in my case (but it can be my mistake...)
My first target was to export a excel file with openxml from
`byte[] WriteExcel()
        {
            MemoryStream ms = new();
            
            SpreadsheetDocument spreadsheetDocument = SpreadsheetDocument.Create(ms, SpreadsheetDocumentType.Workbook);

            WorkbookPart workbookpart = spreadsheetDocument.AddWorkbookPart();
            workbookpart.Workbook = new Workbook();

            WorksheetPart worksheetPart = workbookpart.AddNewPart<WorksheetPart>();
            worksheetPart.Worksheet = new Worksheet(new SheetData());

            Sheets sheets = spreadsheetDocument.WorkbookPart.Workbook.AppendChild<Sheets>(new Sheets());

            Sheet sheet = new Sheet()
            {
                Id = spreadsheetDocument.WorkbookPart.GetIdOfPart(worksheetPart),
                SheetId = 1,
                Name = "mySheet"
            };
            sheets.Append(sheet);

            workbookpart.Workbook.Save();

            spreadsheetDocument.Close();

            byte[] data = ms.ToArray();

            return data;
        }`

My second was 
`private Stream GetFileStream()
        {
            string txt = "test";
            byte[] data = Convert.FromBase64String(txt);
            var fileStream = new MemoryStream(data);

            return fileStream;
        }

        private async Task DownloadFileFromStream()
        {
            var fileStream = GetFileStream();
            var fileName = "test.txt";//"test.xlsx";

            using var streamRef = new DotNetStreamReference(stream: fileStream);

            await JS.InvokeVoidAsync("downloadFileFromStream", fileName, streamRef);
        }`

In the first case I was not able to open the file after download, in the second is "µë-" in the file instant of "test"

**Comment by guardrex** [comment]
@frankleib ... Side-note that it's triple backticks above and below code blocks on GitHub to get the code to render properly (I'll edit your last remark to fix it). Anyway, I can't troubleshoot that scenario in that format, and I wouldn't be able to ping the product unit to look at that in that form. Do this ......

1. Put up a minimal repo in GitHub that demonstrates the problem.
1. Open a new issue from the bottom of the topic at https://docs.microsoft.com/en-us/aspnet/core/blazor/file-downloads.

   Link the GH repro project into your issue comment.

   I think the best way to demo it would be to have both the Excel file and the text file in a folder in the app, not generated by the app. The generation part probably isn't important. If the file opens after generation, then your code that generates the file fine. The part that needs to be looked at is after the file is generated and the app/client attempts the download following the topic's guidance.

I'll review your app first. If I can't see a problem, then I'll ping Tanay to take a look. Note that Tanay is **_super busy_** right now with .NET 7 work,  so there might be a delay until he can look at it. 

A alternative to waiting is to post your example app to GH and ask the community for assistance ... or to help you identify the doc bug exactly so that you can report it to us if the doc is at fault. Reach out to devs on the common support channels ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](https://join.slack.com/t/aspnetcore/shared_invite/zt-1b60h73p0-PZPq3YCCaPbB21RcujMSVA)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

If the doc's code is at fault in an analysis with the community, then definitely open a new issue from the topic ... Tanay will need to take a look.

**Comment by guardrex** [comment]
I'll be up in the early hours (here ... Florida) on Sunday ... ~4-5am CST if the 🐱 wakes me up as usual, and I'll try a few tests of the code and see what happens, including with an Excel file. I'll report back here if you don't open a new issue by then.

**Comment by guardrex** [comment]
Ok ... my tests were successful 🎉, but I agree with you on providing a **_more_** fully-featured cut-'n-paste example. I opened ...

https://github.com/dotnet/AspNetCore.Docs/issues/26377
