### ISSUE TITLE
using Microsoft.Extensions.Hosting is required in order to user IsDevelopment Method

### ISSUE THREAD

**Issue by cocoa-dev008** [dotnet/AspNetCore.Docs#26305]
Hi, I'm happy to migrate to .Net6, this page was very helpful.

By the way, there is a stumbled point when I migrated my .Net Core 3.1 code, so I would like to inform it. Is is that IsDevelopment method became an Extentions Method.

When I rewrote my Startup.cs according to [this instruction](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio#new-hosting-model), a compile error indicating "IsDevelopment method is not contained". I'm happy if it is described that using Microsoft.Extensions.Hosting to use the extensions method.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bec61f9-7298-170d-5e12-abb27cde584e
* Version Independent ID: 27a43e3f-149d-9058-f937-0eda1d6dd4f2
* Content: [Migrate from ASP.NET Core 5.0 to 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/50-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @cocoa-dev008 ... It's already covered because the namespace appears in the example ...

```csharp
using Microsoft.Extensions.Hosting;
```

I think this is indirectly covered by the 3.1 to 5.0 migration topic's cross-link to the breaking changes doc, which then leads to ...

https://docs.microsoft.com/dotnet/core/compatibility/aspnet-core/5.0/extensions-package-reference-changes

It's a bit buried, but it's also challenging to cover that many package/namespace changes. One option is to add that link to the 3.1 to 5.0 doc, perhaps along with the API browser to help devs find API ...

https://docs.microsoft.com/dotnet/api/

Rick, I'll add that and ping u for review.
