### ISSUE TITLE
Passing EventCallback, Action...etc

### ISSUE THREAD

**Issue by jwu-dharmo** [dotnet/AspNetCore.Docs#26324]
It will be really helpful to cover how to pass Action and EventCallback to the DynamicContent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36513a62-bad8-c724-c8e5-2d3aad7913ec
* Version Independent ID: 3cefd835-d898-6486-607e-01f42ebb4b6e
* Content: [Dynamically-rendered ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/dynamiccomponent?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/dynamiccomponent.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/dynamiccomponent.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jwu-dharmo ... **_Yes!_** ... this wasn't exactly "fun" to work out! 😆

*Note to self*: We might want to add an example (or expand the current example) for child content, too, because `RenderFragment`s are supported.

@TanayParikh ... Is the following the (*rough*&dagger;) correct approach for event callbacks with the `DynamicComponent` component?

**_rough_**&dagger; = The following is just a *Rex Hack-up*&trade; 🙈, not what we'd actually show in the topic. I just want to make sure that I have the gist of the concept correct that passing the dictionary object value as `EventCallback.Factory.Create<T>` is the right way to go. If so, I'll make it nice when it comes time to add guidance to the topic. Even if crudely correct, please let me know if you have anything in particular to call out. I think we can avoid PU review on this one if this is the correct approach.

@jwu-dharmo ... I'm not sure when I'll get back to this. I'll try to get to it soon, but we have higher priority issues to address in the near-term. This issue is cross-linked to the topic by way of the topic's *View all page feedback* link at the bottom, and I'll certainly call it out to anyone else who asks. It might take me a day, a week, or a month to reach it ⛰️⛏️😅. When I get to it, I'll ping you on the PR.

`Shared/SpaceX.razor`:

```razor
<h2>SpaceX®</h2>

<p>
    SpaceX is a registered trademark of
    <a href="https://www.spacex.com/">Space Exploration Technologies Corp.</a>
</p>

<p>
    <button @onclick="OnClickCallback">
        Trigger a Parent component method
    </button>
</p>

@code {
    [Parameter]
    public EventCallback<MouseEventArgs> OnClickCallback { get; set; }
}
```

`Shared/RocketLab.razor`:

```razor
<h2>Rocket Lab®</h2>

<p>
    Rocket Lab is a registered trademark of
    <a href="https://www.rocketlabusa.com/">Rocket Lab USA Inc.</a>
</p>

<p>
    <button @onclick="OnClickCallback">
        Trigger a Parent component method
    </button>
</p>

@code {
    [Parameter]
    public EventCallback<MouseEventArgs> OnClickCallback { get; set; }
}
```

`Pages/DynamicComponentExample.razor`:

```razor
@page "/dynamiccomponent-example"

<h1><code>DynamicComponent</code> Component Example</h1>

<p>
    <label>
        Select your transport:
        <select @onchange="OnDropdownChange">
            <option value="">Select a value</option>
            <option value="@nameof(RocketLab)">Rocket Lab</option>
            <option value="@nameof(SpaceX)">SpaceX</option>
        </select>
    </label>
</p>

@if (selectedType is not null)
{
    <div class="border border-primary my-1 p-1">
        <DynamicComponent Type="@selectedType" 
            Parameters="@(new Dictionary<string, object>() { { "OnClickCallback", EventCallback.Factory.Create<MouseEventArgs>(this, ShowDTMessage) } })" />
    </div>
}

<p>@message</p>

@code {
    private Type? selectedType;
    private string? message;

    private void OnDropdownChange(ChangeEventArgs e)
    {
        selectedType = e.Value?.ToString()?.Length > 0 ?
            Type.GetType($"BlazorWASMGlobTest.Shared.{e.Value}") : null;
    }

    private void ShowDTMessage(MouseEventArgs e) => message = $"The current DT is: {DateTime.Now}.";
}
```

**Comment by guardrex** [comment]
@jwu-dharmo ... FYI, there's a delay on this for a bit due to high priority work on the .NET 7 framework. We'll get back to this *ASAP* 🏃😅. In the meantime, you can use the `EventCallback.Factory.Create<T>` approach as described above; albeit, it will be a bit *at your own risk* ⚠️ at the moment until we get confirmation from the product unit that that's sound code.

**Comment by jwu-dharmo** [comment]
no problem, buddy....whenever you can get to it.

JWu

**Comment by jwu-dharmo** [comment]
Luke:

How do I see the change?  I lost track of which article I posted the
feedback.

JWu

**Comment by guardrex** [comment]
It's not live yet, but you can look at the PR ...

https://github.com/dotnet/AspNetCore.Docs/pull/26432

It will probably go live within 24 hours.

**Comment by guardrex** [comment]
I didn't address `Action`. I'm not sure about `Action` use in this context. I know `EventCallback` would be popular here ... I would think 🤔 so. I think if `Action` is something that doesn't follow the same or similar pattern that this would need to be re-opened for more work. If you can explain out a use case for `Action` in this context, let me know. Otherwise, I'm trying to close out issues *as fast as possible* because the workload for .NET 7 is picking up here, and I need to get on the doc work for .NET 7 *ASAP* 🏃🏃🏃🏃🏃.
