### ISSUE TITLE
Paragraph is confusing - needs clarification

### ISSUE THREAD

**Issue by nkatz01** [dotnet/AspNetCore.Docs#26330]
The Blazor Server hosting model **supports the Scoped lifetime** across HTTP requests _[i.e. IT KEEPS IT A SINGLETON, ONLY FROM ONE HTTP CONNECTION TO ANOTHER]_ but not across SignalR connection/circuit messages among components that are loaded on the client. The Razor Pages or MVC portion of the app **treats scoped services normally and recreates the services on each HTTP request** when navigating among pages or views or from a page or view to a component. _[SO, IT DOESN'T SUPPORT 'SCOPED' ON HTTP CHANGES?]_ **Scoped services aren't reconstructed when navigating among components on the client**, where the communication to the server takes place over the SignalR connection of the user's circuit, **not via HTTP requests** [WHICH IS GOOD?! I.E. WHAT'S INTENDED?!]. In the following component scenarios on the client, scoped services are reconstructed because a new circuit is created for the user:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7683690c-e3aa-4a00-152a-e44cfd7fc789
* Version Independent ID: d9aabe95-69e9-0a03-81ff-429914137f9d
* Content: [ASP.NET Core Blazor dependency injection](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @nkatz01 ... On a *quick look* at what you wrote, I think you're reading too much into the remarks. They should be taken at face value and not interpreted beyond what the text strictly states.

Let me circle around ... probably in a week or two ... to look in detail at the remarks for possible improvements. I'm buried ⛰️⛏️ at the moment in some high priority work that must be completed *ASAP*. I'll take a look at this as soon as I can get free of the current work.

**Comment by guardrex** [comment]
Also note that this topic can't be consumed independently by-design, which is something that I can address at the top of the topic. Devs should read the main DI/services article in the main doc set first. It's cross-linked, but there's no suggestion that reading the main doc first will be helpful with the concepts/examples in this article.

https://docs.microsoft.com/aspnet/core/fundamentals/dependency-injection

**Comment by guardrex** [comment]
Ok ... I'm back ... for a minute 😄 ... until another doc 🚨🚑🚒🚓 hits. 

Let's break that down ......

> The Blazor Server hosting model supports the Scoped lifetime across HTTP requests [i.e. IT KEEPS IT A SINGLETON, ONLY FROM ONE HTTP CONNECTION TO ANOTHER] but not across SignalR connection/circuit messages among components that are loaded on the client.

> IT KEEPS IT A SINGLETON, ONLY FROM ONE HTTP CONNECTION TO ANOTHER

No, you're reading too much into the remark. It's only remarking that scoped services behave as expected for HTTP requests. It doesn't say that the type of registration changes.

> The Razor Pages or MVC portion of the app treats scoped services normally and recreates the services on each HTTP request when navigating among pages or views or from a page or view to a component. [SO, IT DOESN'T SUPPORT 'SCOPED' ON HTTP CHANGES?] 

Supporting the topic sentence, this focuses on the exact parts of the app that routinely recreate scoped services ... RP and MVC HTTP requests. I don't understand where you're drawing the conclusion that scoped isn't supported. The sentence says the exact opposite of that for the conditions it lists.

> Scoped services aren't reconstructed when navigating among components on the client, where the communication to the server takes place over the SignalR connection of the user's circuit, not via HTTP requests [WHICH IS GOOD?! I.E. WHAT'S INTENDED?!]. In the following component scenarios on the client, scoped services are reconstructed because a new circuit is created for the user:

Contrasts how scoped services behave on the SignalR connection for components. Because this is a contrast, it *might* 

> WHICH IS GOOD?! I.E. WHAT'S INTENDED?!

The intention is only to explain the behaviors.

I detect important update to make: The main doc set DI topic is a good background topic for this topic. However, the cross-link to that is just the link text "Dependency injection (DI)" in the sentence ...

> Dependency injection (DI) is a technique for accessing services configured in a central location:

I don't think it's clear that readers probably should consume that general ASP.NET Core doc first. Therefore, I'll do something at the top of the topic ... perhaps a NOTE ... to call that out to readers.

I'll also take a look at the structure and phrasing of the paragraph on the update.

If you didn't get a chance to read the main DI topic, it's at ...

https://docs.microsoft.com/aspnet/core/fundamentals/dependency-injection

Leave this issue open, it will automatically close when the PR merges.
