### ISSUE TITLE
.NET 7: Document dark mode for developer exception page 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26356]
See https://github.com/dotnet/aspnetcore/pull/39676

@poke  how do you enable dark mode?

**Comment by poke** [comment]
@Rick-Anderson Dark mode is enabled automatically if your browser detects that you prefer dark mode for websites. By default, this happens when your system preference is set to dark mode but browsers will usually also allow you to override this in their settings.

If you want to test this, you can also switch to dark mode with the browser developer tools, e.g. in Firefox:

![Switching to dark mode in Firefox](https://user-images.githubusercontent.com/132240/177986366-bc7a9d3e-41f2-4fa0-8d0d-2d40237c17fb.png)

Or in Chrome:

![Switching to dark mode in Chrome](https://user-images.githubusercontent.com/132240/177990277-bd4b9716-4c19-42d6-9829-637555788af2.png)

**Comment by Rick-Anderson** [comment]
FF
![image](https://user-images.githubusercontent.com/3605364/178082215-7bd1dfbe-3f11-421c-9918-fa11d8b99736.png)

Chrome
![image](https://user-images.githubusercontent.com/3605364/178082535-7719b77f-563a-4d0d-b70a-267801bb6526.png)

**Comment by Rick-Anderson** [comment]
Added to What's new
Thanks @poke
