### ISSUE TITLE
Improve Blazor DI article 'OwningComponetBase' example

### ISSUE THREAD

**Issue by nkatz01** [dotnet/AspNetCore.Docs#26385]
I think that under heading: Utility base component classes to manage a DI scope, you mean to have Settings class implement the two interfaces underneath it: 

```
 public class Setting
    {
        public string? SettingName { get; set; }
        public string? SettingValue { get; set; }
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7683690c-e3aa-4a00-152a-e44cfd7fc789
* Version Independent ID: d9aabe95-69e9-0a03-81ff-429914137f9d
* Content: [ASP.NET Core Blazor dependency injection](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the note @nkatz01 ... I'll get back to you *ASAP*, as I'm just about to go OOF for a few hours.

![image](https://user-images.githubusercontent.com/1622880/178293696-f1ee214f-b508-4ddb-8e54-a94df8a08740.png)

&mdash; **_"I'll be back."_** - Cyberdyne Systems T-800 Series Model 101 ([Arnold Schwarzenegger](https://www.imdb.com/name/nm0000216/))
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[*The Terminator*](https://www.imdb.com/title/tt0088247/) ©1984 [Skydance Media](https://skydance.com/)

**Comment by guardrex** [comment]
Ok ... **_I'm baaaaaaaaaaaack!_** ... from the 💪 *gym* 🏋️. *Arnold would be proud!* 😄

I'm looking at the context on this. I didn't write this code, but I did review it and its updates over the past few years. Looking at it right now, I don't really like it very much. It's not utterly clear as an example. I'd rather have something like a service that can be clearly distinguished **with** and **without** `OwningComponetBase` that shows the difference, namely that you get component-scoped behavior **with it** and you get (e.g., Blazor Server, scoped) circuit-scoped behavior **without it**. I think that would be a *better* demo, and I'd like to make it cut-'n-paste, too.

Anyway, let's get back to the matter at hand. This originally came in on ...

https://github.com/dotnet/AspNetCore.Docs/pull/17064

... without the classes. The classes were added later, **_and I think I see where the gremlins got in here!_** 😈 ...

https://github.com/dotnet/AspNetCore.Docs/blob/7d2473eaf51a22d7e7948051ae2e20e07b55e418/aspnetcore/blazor/common/samples/3.x/BlazorSample_Server/Pages/dependency-injection/Preferences.razor

There was an effort ... *briefly* ... to have all of the documentation code examples be in apps that would compile as part of the build. That way, PRs will blow up 💥 if someone ... us, a community cat, a PU member ... changes something that breaks the code of the example. This was meant to control bad code getting into doc examples. In order to pull that off in many cases, we needed to mock up quite a few API members in Razor component examples so that the component would compile without  breaking when the docs build engine tried to build the sample apps that were supplying the code. We don't do that any longer ... we don't build the examples for every PR. It was only briefly done and stopped because it resulted in way, **_WAY_** too many things breaking across the docs to do it in practice.

*These classes* have escaped from being hidden in the rendered example for that purpose of successfully building the component **_INTO THE WILD_** ... i.e., these classes are now surfacing in the document due to a later update ... *and they shouldn't be visible!*

So, the fix is for me to just hide those classes.

Anyway ... going back to my earlier analysis ... I still think 🤔 that we need a better example of this whole scenario for this section. Therefore, I'm going to "address" this issue with a PR now to fix the problem that you called out, then I'm going to circle around later to build out a new *sweet* example of this in my usual cut-'n-paste demo style, where readers will be able to just snip a few bits for a test app and see it work in action.

Leave this issue open. The issue will remain open after my "addresses" PR goes in, and I'll get back to this issue at some point in the future. That future work could take a while tho. We're ramping up .NET 7 docs work now, so I can see this getting "fixed" in a PR late this year. This would make a good 🎁 holiday PR ⛄ or something for 23Q1.

Thanks again, @nkatz01 for calling it out. I'll ping u on the PR shortly.
