### ISSUE TITLE
maxFileSize is defined differently in the example

### ISSUE THREAD

**Issue by mo2eharrington** [dotnet/AspNetCore.Docs#26405]
It would make more sense to keep the maxFileSize calculation the same through all the examples.  I believe it is defined as `15*1024` once and `15*1024*1024` in other places.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=server)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the shout on this, @mo2eharrington. I'll see about getting that fixed up right now 🏃.

**Comment by guardrex** [comment]
Yeah, let's go with the smaller 15K size. I say so because these examples are meant to be cut-'n-paste experiences that devs can drop right into a test app. Many files lying around a system go beyond 15K for a test experience ... you know ... just to see something 💥 on purpose while playing with code to learn more about how things work.

**Comment by mo2eharrington** [comment]
Thanks!
