### ISSUE TITLE
IJSRuntime

### ISSUE THREAD

**Issue by bertramdryan** [dotnet/AspNetCore.Docs#26404]
[EDIT by guardrex to change the target topic for the update.]

IJSRuntime cannot be simply injected into any .cs class.  It can be injected into a razor.cs, but injecting it into another service doesn't work. 

Something like this:
``` csharp
var jsRuntime = host.Services.GetRequiredService<IJSRuntime>();

builder.Services.AddSingleton<IAuthorizationService, AuthorizationService>(
    service => new AuthorizationService(
        service.GetService<IUserAuthClient>(),
        jsRuntime
        )
);
```

Or something like:

``` csharp
builder.Services.AddSingleton<IAuthorizationService, AuthorizationService>(
    service => new AuthorizationService(
        service.GetService<IUserAuthClient>(),
        service.GetService<IJSRuntime>()
        )
    );
```

The error is that that this cannot be scoped.  I'm wondering what other solutions might work, and perhaps an example of how to inject this into other services might be useful on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7683690c-e3aa-4a00-152a-e44cfd7fc789
* Version Independent ID: d9aabe95-69e9-0a03-81ff-429914137f9d
* Content: [ASP.NET Core Blazor dependency injection](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by bertramdryan** [comment]
> Hello @bertramdryan ... Thanks for the ask on this. Let's get assistance or a further ping to a product unit engineer on this one ...
> 
> 📞 _Paging Mr. @mkArtakMSFT ......... Mr. @mkArtakMSFT, please pick up a red courtesy telephone._ ☎️😄

I realize that this wasn't an asp.net question but a blazor question, but this README doc was the closest example, yet not exactly how to inject things like iJSRuntime into something other than a razor.cs partial.

**Comment by guardrex** [comment]
That's fine, @bertramdryan. We'll figure that out after the PU ("product unit") comments on it. Sometimes, they say not to take something in a given direction and provide an alternative that we already cover somewhere ... or sometimes they say that what the dev is trying to do just isn't supported, which can lead to a PU issue on the PU repo for PU work (they might move this issue over to their repo) or something being closed as a `won't-fix` scenario.

btw tho ... `IJSRuntime` can be injected into classes generally. But ... *yeah* ... the `Program` class can present some challenges in extraordinary service registration/configuration/use scenarios. Some of the scenarios have been tricky to work out based on current guidance, but we cover them as they come in on questions like this. If this turns out to be a general scenario (beyond just Blazor), then it might get added to the Minimal APIs doc at ...

https://docs.microsoft.com/aspnet/core/fundamentals/minimal-apis

btw ... They're very busy 🏃😅 with .NET 7 work at this time, so there might be a delay on hearing from them. If you want to take it up with the community in the meantime, we recommend the usual public support forums ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](https://join.slack.com/t/aspnetcore/shared_invite/zt-1b60h73p0-PZPq3YCCaPbB21RcujMSVA)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)

Otherwise, *stand-by* ... Artak or one of the PU 🐈 will be along to help with this.

**Comment by bertramdryan** [comment]
The problem I'm running into, is injecting it into another service.  Because IJSRuntime is added by default, it should be available in the `service.GetService<IJSRuntime>(). 
I should also mention that this is a Blazor Server app not a Webassemble App. 

![image](https://user-images.githubusercontent.com/6075464/178538647-25f7a3c9-9632-4ec3-b2b5-9b66c19619f9.png)

The above image shows the exception I'm getting from it.

**Comment by guardrex** [comment]
Did you try an approach where you build **first**. Like this way ....

```csharp
...
var host = builder.Build();

var weatherService = host.Services.GetRequiredService<WeatherService>();
...
```

**Comment by bertramdryan** [comment]
> Did you try an approach where you build **first**. Like this way ....
> 
> ```cs
> ...
> var host = builder.Build();
> 
> var weatherService = host.Services.GetRequiredService<WeatherService>();
> ...
> ```

I see that, but does the `host` need to take the place of the `app`?  Or is it ran separately? Feels like a bit of a hack. 🤣

**Comment by guardrex** [comment]
Not a hack for merely tapping the registered service ... in for example an initialization scenario. I don't recall a dev asking about the scenario you laid out in your opening comment. It seems like one would create a custom auth service ... and then `IJSRuntime` (and anything else you want) is injected into that.

**Comment by bertramdryan** [comment]
@guardrex I'm writing an outlook plug-in, and storing a refresh token in the limited Office 365 storage so that the token can persist between sessions.  So, the authorization service does an initial sending of a 6 digit code sent by the API, once that code is received, it then gets an access token object from the API, which is the object I'm trying to store.  
Also, Outlook provides a user profile only available via JavaScript.

**Comment by guardrex** [comment]
I see. Yeah, that's beyond me as a *simple minded* 🦖 *docs dino!* 😄 Let's let the PU respond and/or you can reach out to community gurus on that. It's definitely an advanced scenario as far as docs would be concerned. I have a feeling that they might give you a direction to take but that we wouldn't cover it in the docs. We'll see tho. Artak should be around in a bit to help further.

**Comment by bertramdryan** [comment]
@guardrex  Thanks.  Blazor isn't 'officially' recommended for this type of app. But aside from the DI issues with IJSRuntime, its worked really well.  Hopefully something can solve this. 👍

**Comment by guardrex** [comment]
I'm going to email offline, too. We might get a quicker response that way. They get slammed with GH pings.

**Comment by guardrex** [comment]
@bertramdryan ... Artak says to open it for the PU on their repo. Open it here ...

https://github.com/dotnet/aspnetcore/issues

Explain out the Outlook scenario and show the code concepts in your opening comment. 

Please add the following to the bottom of your opening comment so that I can follow along ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/26404
```

I might re-open this for doc work depending on what they say.

**Comment by bertramdryan** [comment]
@guardrex was there a solution? Looks like it was moved to done?

**Comment by guardrex** [comment]
😄 ... "Done" *here* ... as far as docs are concerned. Open it for the PU ... read my last comment ☝️.

**Comment by bertramdryan** [comment]
There it is. : Thanks.

**Comment by guardrex** [comment]
Good ... yes ... I think Javier's response is worth documenting. I'll determine *where* and *how to phase it*.

I'll ping u on the PR.
