### ISSUE TITLE
Add 'dotnet/blazor-samples' cross-link to all docs and move 3.1+5.0 samples

### ISSUE THREAD

**Issue by gnnsekhar** [dotnet/AspNetCore.Docs#26418]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-6.0#example-form)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gnnsekhar ... *Indeed!* I made a small mistake closing a duplicate request. My remarks are at ...

https://github.com/dotnet/AspNetCore.Docs/issues/26376#issuecomment-1179705652

I put in some updates but marked the PR as "fixes," while it should've been "addresses." Therefore, we'll use your issue here to do the work on this. Thanks for opening this issue.

Note the remarks in the [`dotnet/blazor-samples`](https://github.com/dotnet/blazor-samples) README and published in the docs at ...

https://docs.microsoft.com/aspnet/core/blazor/fundamentals/#sample-apps

The snippet sample apps that provide code samples for the docs are **_only for obtaining code_**. They'll compile (*maybe!* 😄, probably with at least warnings) but never be runnable apps due to the reasons that I call out in the README. However, they are good for grabbing code and grabbing components and dropping them into a local, runnable test app.

I'll see about placing a cross-link to that repo **_in all of the Blazor docs_** to resolve this issue *ASAP* ... not sure exactly when given that I'm ⛰️⛏️😅 most of the time, but I think I can knock this one out today or tomorrow (Thursday).

*Thanks again for the request!*

**Comment by guardrex** [comment]
I think I'll piggyback one more thing on this issue. I've already moved the 6.0 sample apps to the `dotnet/blazor-samples` repo. I'd like to do that for the 3.1 and 5.0 samples, too.
