### ISSUE TITLE
Migration overview ASP.NET to ASP.NET Core still refers to 2.x version (= EOL)

### ISSUE THREAD

**Issue by Styxxy** [dotnet/AspNetCore.Docs#26416]
The migration overview page for moving from ASP.NET to ASP.NET Core still refers to dotnet core 2.x version, which is already end-of-life for a while.

Shouldn't this be updated to the latest LTS (.NET 6) version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1133d6d1-7801-654c-2b7c-dad2bb342501
* Version Independent ID: a7ccce22-f905-06f4-8847-b9eeaf534e1f
* Content: [Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/migration/proper-to-2x/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/proper-to-2x/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @isaacrlevin
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @Styxxy ... I think you're referring to the *Prerequisite* section, correct? @Rick-Anderson will advise further. For example, it might be best to drop that section because it might be confusing to have it at all, either way ... listing 2.x or listing the current release. The doc is about migration, so I'm not sure that there's a good reason to list a "prereq" for migration ASP.NET to ASP.NET Core.

btw ... WRT maintaining older guidance generally, we're going to maintain all of the current coverage for the .NET Framework with ASP.NET Core because the .NET Framework has a much longer lifetime. For example, you'll see that when 3.1 reaches it's EOL as an ASP.NET Core framework on 12/13/2022 that we'll **_keep the coverage on it anyway beyond that date_**. Since you're presumably embracing ASP.NET Core and dropping ASP.NET, you'll want to stick to those ASP.NET Core lifecycle dates. When 3.1 reaches EOL, the product unit does want devs to upgrade their exclusively-3.1 ASP.NET Core apps to at least 5.0, if not 6.0 (or the 7.0 release scheduled for this November, just inside the EOL of 3.1). Anyway ... don't be surprised to see 3.1 (and later) ASP.NET Core doc coverage around for quite a long time after a strict ASP.NET Core EOL date.

**Comment by guardrex** [comment]
I see. Thx for the note on that. Rick will be along in a bit to triage this.
