### ISSUE TITLE
Hosted WASM deployment to IIS

### ISSUE THREAD

**Issue by psimler** [dotnet/AspNetCore.Docs#26464]
Want to deploy an ASP.NET Core hosted Web Assembly on IIS. After more than 4 hours still haven't found a proper documentation on how to do it. Microsoft documentation is useless. It's like a plate of spaghetti. Useless things everywhere ordered in a chaotic manner. This gets worse year after year

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @psimler ... In the base case (without subapp config or hosting at a different base path), there's no difference between hosting a hosted WASM app and an ASP.NET Core app. That's why you don't see more information beyond what's in the *Overview* article ...

https://docs.microsoft.com/aspnet/core/blazor/host-and-deploy/#publish-the-app

If you use a "Folder" publish profile, publish from the **Server** project, deploy the `publish` folder assets, and point IIS's physical path to that deployment, it should work. We recommend the "Folder" publish profile over Web Deploy (the "Web Server (IIS)" profile), but you can use Web Deploy if you prefer and it should still work.

If you need further assistance, we don't provide much product support here, as we primarily just work on the documentation. If you don't have a MS support agreement, we recommend the usual public support channels ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](https://join.slack.com/t/aspnetcore/shared_invite/zt-1b60h73p0-PZPq3YCCaPbB21RcujMSVA)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)
