### ISSUE TITLE
canot understand nothing nothing works json patch

### ISSUE THREAD

**Issue by GG-Creations** [dotnet/AspNetCore.Docs#26481]
i am noob i know but i think that nothing work in json patch documedation, can anybody build a video that explain how works?

**Comment by guardrex** [comment]
@GG-Creations ... I asked yesterday if you would please open issues here from the **This page** feedback form at the bottom of the topic. We need readers to use our workflow because we're very busy these days. When you use that process, it will add metadata to the issue for tracking and ping the author of the topic.

Also note that this isn't a general discussion forum. It's a working repo for the documentation. If you need general product support, we recommend the usual public support channels ...

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](https://join.slack.com/t/aspnetcore/shared_invite/zt-1b60h73p0-PZPq3YCCaPbB21RcujMSVA)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)
