### ISSUE TITLE
Transient Scope for Custom AuthorizationMessageHandler class

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [dotnet/AspNetCore.Docs#26528]
Hello! The document contains the following code snippet:

```cs
builder.Services.AddScoped<CustomAuthorizationMessageHandler>(); // 1

// AddHttpClient is an extension in Microsoft.Extensions.Http
builder.Services.AddHttpClient("WebAPI",
        client => client.BaseAddress = new Uri("https://www.example.com/base"))
    .AddHttpMessageHandler<CustomAuthorizationMessageHandler>(); // 2
```

where `CustomAuthorizationMessageHandler` is registered as a `Scoped` service (`// 1`). However, the documentation for [`AddHttpMessageHandler<THandler>(IHttpClientBuilder)`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientbuilderextensions.addhttpmessagehandler?view=dotnet-plat-ext-6.0#microsoft-extensions-dependencyinjection-httpclientbuilderextensions-addhttpmessagehandler-1(microsoft-extensions-dependencyinjection-ihttpclientbuilder)) (`// 2`) specifies that `CustomAuthorizationMessageHandler` must be registered as a `Transient` service:

> THandler
> The type of the DelegatingHandler. The handler type must be registered as a **transient** service.

There seems to be a difference in the lifetime (`scoped` vs `transient`) across the above documentations. Might this be an error in the documentation, or am I understanding the docs incorrectly?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f3209c-2414-9b35-6245-383c9b7c6338
* Version Independent ID: cc8dfcd6-8d93-5aa3-c381-2b613e88cdbe
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-6.0#custom-authorizationmessagehandler-class)
* Content Source: [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
cc: @javiercn ... This one requires your help 🚓🚑🚒.

Thanks for the issue, @Zhiyuan-Amos. It was transient prior to the release of 3.2.1. We changed it at the same time that `HttpClient` registrations went to scoped on ...

**Blazor scoped service registrations**
https://github.com/dotnet/AspNetCore.Docs/pull/19231

... which came about via docs issue ...

**[3.1.6] Incorrect HTTPClient registration**
https://github.com/dotnet/AspNetCore.Docs/issues/18359

... which was based on the PU issue ...

**[Blazor] HttpClient is registered incorrectly**
https://github.com/dotnet/aspnetcore/issues/21655

... with @javiercn's PR at ...

**[Blazor] Register HttpClient as a scoped instance**
https://github.com/dotnet/aspnetcore/pull/22770

> The fix is to register the HttpClient instance in the container as Scoped instead, which in the context of Blazor WebAssembly is equivalent to Singleton, ensuring that only one instance is used across the app.

I would've thought for a sec that the docs PR was overzealous because I noticed that even today that `BaseAddressAuthorizationMessageHandler` is [registered by the framework as transient](https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/WebAssemblyAuthenticationServiceCollectionExtensions.cs#L43) (as is `AuthorizationMessageHandler` right under it).

So, we'll need a ruling on this one, and then ...

* If it turns out that that because WASM is a *special case* for this registration and it should remain scoped, I think an added sentence to the explanation makes sense.
* If we change it, there's one other spot that we also need to change. The `GraphAPIAuthorizationMessageHandler` in `graph-api.md` is also transient at this time: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?view=aspnetcore-6.0#named-client-with-graph-api

**Comment by Jhstvf4t** [comment]
I don't have money anymore to go out to the workshop, I want to eat, let alone me

**Comment by guardrex** [comment]
**UPDATE (8/11)**: *Very sorry for the delay!* There's a delay due to the work going on for the upcoming .NET 7 release. We'll get to this *ASAP*, but I don't have an ETA.

**Comment by guardrex** [comment]
New information on this that resolves it ...

https://github.com/dotnet/aspnetcore/issues/43234

Leave this open, @Zhiyuan-Amos, as I plan to clarify it in the docs based on Javier's remarks there.

**Comment by Jhstvf4t** [comment]
does this delay really matter?

Pada tanggal Kam, 11 Agu 2022 21:54, Luke Latham ***@***.***>
menulis:

**Comment by Jhstvf4t** [comment]
Got it.

Pada tanggal Jum, 12 Agu 2022 17:21, Luke Latham ***@***.***>
menulis:

**Comment by Jhstvf4t** [comment]
does this delay really matter?



Pada tanggal Kam, 11 Agu 2022 21:54, Luke Latham ***@***.***>
menulis:

**Comment by guardrex** [comment]
This was resolved by https://github.com/dotnet/AspNetCore.Docs/pull/26755.
