### ISSUE TITLE
Make note that the example here will not work with minimal api

### ISSUE THREAD

**Issue by DrewBrasher** [dotnet/AspNetCore.Docs#26538]
It would be helpful if this page had a note that the example only works with a controller api because the minimal API does not natively support binding from form values (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0#explicit-parameter-binding).

This Stack Overflow answer has some was to do it  with minimal api: https://stackoverflow.com/questions/71047077/net-6-minimal-api-and-multipart-form-data#answer-71048827

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=webassembly)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @DrewBrasher ... Yes, I think that's going to be a .NET 7 feature released later this year (or now via preview).

I think I'll try to work this into the first round of .NET 7 Blazor updates:

* Place a NOTE for the 5.0 and 6.0 versions of this doc.
* No comment for the 7.0 version of the doc, since it doesn't show the Minimal API approach and will bind from a form (*in theory* 🤞🍀) if a dev converts the controller code over on their own (we won't show that).
