### ISSUE TITLE
.NET 7: MapGroup support for more extension methods

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26549]
[MapGroup support for more extension methods](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#mapgroup-support-for-more-extension-methods)

source code created in  #26476

@fiyazbinhasan modified it for testing in #26801 see [this comment](https://github.com/dotnet/AspNetCore.Docs/pull/26801#discussion_r970272291) where I give permission to modify the code. We may want to have two samples if the testing adds additional complexity .

**Comment by sammychinedu2ky** [comment]
I think adding more extension methods to the Todo would be nice to have. Would make some updates

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky  what's the status on [MapGroup support for more extension methods](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#mapgroup-support-for-more-extension-methods) Was this ever done?

**Comment by sammychinedu2ky** [comment]
> @sammychinedu2ky what's the status on [MapGroup support for more extension methods](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#mapgroup-support-for-more-extension-methods) Was this ever done?

https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/minimal-apis/7.0-samples/todo-group

I wrote this a month ago.

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson I think it would be less confusing if I keep the `todo-group` sample as it is. For the unit/integration testing task, I've created another project `WebMinRouteGroup`, which is pretty much similar to @sammychinedu2ky sample (but updated)

@sammychinedu2ky you might want to update your `todo-group` sample since it's not working. Some of the APIs has changed e.g. `AddRouteHandlerFilter` has been renamed to `AddEndpointFilter`

once you update the sample, that could be used for showcasing the `Route Group` feature in the doc.

**Comment by sammychinedu2ky** [comment]
Ooh thanks. Let me check it out @fiyazbinhasan

**Comment by sammychinedu2ky** [comment]
done 🥂

**Comment by Rick-Anderson** [comment]
> done 🥂

PR that updated the code?

**Comment by sammychinedu2ky** [comment]
> > done 🥂
> 
> PR that updated the code?

Yh
