### ISSUE TITLE
Bug creating scaffolding in VS 2022

### ISSUE THREAD

**Issue by hcprobst** [dotnet/AspNetCore.Docs#26592]
[Enter feedback here]
Whenever I try to add a scaffold to my controllers I get an error message and am unable to add the needed items

Finding the generator 'controller'...
Running the generator 'controller'...
Minimal hosting scenario!
Generating a new DbContext class 'TuitionWaiver.Data.TuitionWaiverContext'
Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

I had the same issues trying to do this in the RazorPagesMovie60  tutorial.

I need this to work please

Suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
@hcprobst, it sounds like either one of the packages that are required are not there, the wrong version or you might have an outdated gobal tool that you have to actually remove, before updating.

Try the following:

Verify the tool versions by running the following at the command line:
`dotnet tool list -g`

You should see the following result:
`dotnet-aspnet-codegenerator      6.0.6        dotnet-aspnet-codegenerator`
`dotnet-ef                        6.0.6        dotnet-ef`

Before installing the latest of the dotnet tool dotnet-ef you need ot first uninstall it:
`dotnet tool uninstall dotnet-ef --global`

Verify your list of installed packages and their version for your MvcMovie project, at the project directory, with the following command:
`dotnet list MvcMovie.csproj package --verbosity d`

It is possible you might need to start over with a new project in the tutorial since we don't know what state it is in, but try what I suggested above first.

I will close this issue.  For more troubleshooting you can try the community at stackoverflow.com.  Feel free to reopen this issue if you have more information and feel there is a change that needs to occur in the doc instead.  Thanks very much for your feedback. Always appreciated.

**Comment by wadepickett** [comment]
I updated the instruction above with version information.
