### ISSUE TITLE
Solution for Blazor WebAssembly does not work

### ISSUE THREAD

**Issue by Cage-e** [dotnet/AspNetCore.Docs#26648]
I tried the solution for blazor wasm (ASPNET core hosted) and I still get the unauthorized response on connecting to a hub with Authorize attribute. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0969556b-b77e-bdb8-8e20-fd6971be0c25
* Version Independent ID: d17e4c28-ea82-0dd8-295d-19f6ada147ea
* Content: [ASP.NET Core Blazor SignalR guidance](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Cage-e ... Please open for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

You will need to put up a minimal repro project that demonstrates the failure.

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/26648
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.
