### ISSUE TITLE
Please update for latest release

### ISSUE THREAD

**Issue by jimgit** [dotnet/AspNetCore.Docs#26726]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e66171ce-7dca-bf91-36be-f02e38c00678
* Version Independent ID: e66171ce-7dca-bf91-36be-f02e38c00678
* Content: [Build a .NET MAUI Blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/maui.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/maui.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jimgit ... If by "latest release" you mean the upcoming release for 7.0, that's tracked separately. If you mean "latest release" as in 6.0, this is current. If you're having trouble with implementation, you can mention here what you're seeing, but we might end up having you open an issue for the product unit.

**Comment by guardrex** [comment]
@jimgit ... I'm going to go ahead and close, but feel free to write back more detail on what you mean by "latest release," especially if you're having a 6.0 problem with the current guidance, which is for 6.0. Based on that, I may direct you to open an issue for the product unit. If you mean for 7.0, we don't guarantee that docs will be ready until General Availability (GA), which is scheduled for November. There are many things that we can't document at all right now for 7.0 because the first release candidate (RC1) hasn't come out yet. The developers are still working on the engineering issues for RC1. We must wait until they finish their work to even consider rolling out docs on many upcoming features.
