### ISSUE TITLE
Is storing circuits in the circuit handler thread safe?

### ISSUE THREAD

**Issue by derth** [dotnet/AspNetCore.Docs#26740]
The singleton circuit handler stores the circuits in a hashset, shouldn't we use a thread safe collection instead?

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#blazor-server-circuit-handler

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0969556b-b77e-bdb8-8e20-fd6971be0c25
* Version Independent ID: d17e4c28-ea82-0dd8-295d-19f6ada147ea
* Content: [ASP.NET Core Blazor SignalR guidance](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#blazor-server-circuit-handler)
* Content Source: [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @derth ... This came in directly from the product unit on ...

https://github.com/dotnet/AspNetCore.Docs/pull/16702

You can ask the product unit at ...

https://github.com/dotnet/aspnetcore/issues

If you do, you can let them know that Pranav (not on their team any longer) added the code on that PR ☝️ back in 2020. You can give them this link ...

```
https://github.com/dotnet/AspNetCore.Docs/pull/16702
```

Also, please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/26740
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.
