### ISSUE TITLE
zsh: command not found: libman

### ISSUE THREAD

**Issue by Cetins** [dotnet/AspNetCore.Docs#26776]
The command on below is not working.

libman install @microsoft/signalr@latest -p unpkg -d wwwroot/js/signalr --files dist/browser/signalr.js --files dist/browser/signalr.js

I can confirm libman has been globally installed, the command has been executed in the correct folder, and lot's of people having the same issue on stackoverflow yet I couldn't found a valid answer but lots of theories on comments :) sorry if I couldn't be more help, I'm just a beginner.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

---
[Associated WorkItem - 60045](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60045)

**Comment by wadepickett** [comment]
@Cetins, thanks very much for taking the time to bring this up.  There may have been an update that needs to be accounted for.  I'll look into it.

**Comment by wadepickett** [comment]
Blocking issue, set to Pri 1.

**Comment by wadepickett** [comment]
@Cetins, I tested this tutorial out for both the VSC and the VS for Mac instruction.
It worked fine, however, I could generate failures by running early versions of the global tool.
When a global tool is installed, such as LibMan with the following command, it will not install the latest.  It will check to see if you have any version installed globally, and if you do, it leaves it, but reports back what version is already there:
```dotnetcli
dotnet tool install -g Microsoft.Web.LibraryManager.Cli
```

The current version of `Microsoft.Web.LibraryManager.Cli` right now is 2.1.175

You can see what version if global tools you have installed by running the following command:
```dotnetcli
dotnet tool list -g
```

You can also verify you have any previous version of the tool uninstalled before installing the latest by running both of the following commands:
  ```dotnetcli
  dotnet tool uninstall -g Microsoft.Web.LibraryManager.Cli
  dotnet tool install -g Microsoft.Web.LibraryManager.Cli
  ```
I will add that `dotnet tool uninstall` command to the tutorial to ensure folks are getting the latest tool.

It is possible you might need to start over with a new project in the tutorial since we don't know what state it is in but try what I suggested above first.

Thanks again for the heads up. I am getting that change in the tutorial right now...
