### ISSUE TITLE
Please include screenshots

### ISSUE THREAD

**Issue by Korporal** [dotnet/AspNetCore.Docs#26886]
The examples and explanatory text are insufficient. The simple examples should be accompanied by some screenshots showing how a default Blazor Server app created from the template, looks as and when the various changes are made and exceptions are thrown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adbc1392-92dc-c42e-ba48-a722cffa9b6d
* Version Independent ID: 66a0b1c2-c45c-98ca-9808-6f340a861c44
* Content: [Handle errors in ASP.NET Core Blazor apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Korporal ... We avoid that *by-design* because we don't have the staffing to keep the images current under the rapid churn of the framework. In particular, VS and the Azure portal are the most challenging to keep up with. Also, app styles change  frequently in the project templates. On those grounds, we won't be able to include screenshots. One would just implement the examples as shown in a test app locally to see how the markup renders.

**Comment by Korporal** [comment]
> Hello @Korporal ... We avoid that _by-design_ because we don't have the staffing to keep the images current under the rapid churn of the framework. In particular, VS and the Azure portal are the most challenging to keep up with. Also, app styles change frequently in the project templates. On those grounds, we won't be able to include screenshots. One would just implement the examples as shown in a test app locally to see how the markup renders.

While I can understand that challenge, it does leave a problem. Because we don't know what to actually expect to _see_ we can't bs sure we are achieving what what we think we are achieving.

**Comment by guardrex** [comment]
In most cases, devs can trigger exceptions on purpose for anything that they aren't sure about. In the simpler cases where fragments of markup (`RenderFragment` to be exact) are rendered, it's obvious what will display, except perhaps with styling applied from the default stylesheet.

We don't have the staffing to keep up with images if they aren't critical. To put that into context, there are over 500 articles here ... hundreds of sample apps ... and ~550 issues on the repo ... **_and only three doc authors_** 😅 ... yeah ... *job security!* LOL 🤣. We're doing the best we can. We did use screenshots much more liberally in the reference content 4-5 years ago when ASP.NET Core was new. As the repo grew and grew ... **_and grew_** 🐘🐘🐘 ... we fought stale images constantly, especially for the areas that I mentioned, such as app styling due to project template changes, the Azure portal UI, and the VS UI. These days, we mostly avoid them outside of tutorials.

I recommend triggering errors on purpose in your code to see how the error guidance examples behave outside of what the topic states and the markup that it shows. There's an example here in the *Error boundaries* section that takes that approach to demo behavior/rendering ...

https://docs.microsoft.com/aspnet/core/blazor/fundamentals/handle-errors#error-boundaries

... and you can add buttons to trigger such failures in your code to see the rendering behavior in other scenarios.

If you ultimately find one or more specific scenarios where the code/text in the article are really quite different than the rendered behavior, then we could look at that specific case (or cases) for possible screenshots. Outside of that tho, I want to keep the screenshots in the reference topics to an **_absolute minimum_**. It's all good at first. They look very nice. I agree that they can be helpful. However, they break ... *sometimes badly* 😈 ... as releases roll out from the product unit every year. *Images are very time consuming to keep up to date*, so we'd only consider them for specific cases and only when they really are needed.

**Comment by Korporal** [comment]
@guardrex - Thanks, I appreciate the helpful explanation, that sounds like a great deal of work! Good luck!
