### ISSUE TITLE
Description of first render lifecycle seems wrong

### ISSUE THREAD

**Issue by glatzert** [dotnet/AspNetCore.Docs#26989]
Regarding our experiences and BlazorComponent Code, the description about the lifecycle is wrong regarding rendering during initialization. Especially the note itself contradicts the statement above.

It says the task is awaited, then it's rendered.
Truth seems to be: the task is NOT awaitet and the component is rendered.

> Component lifecycle events:

> If the component is rendering for the first time on a request:
> Create the component's instance.
> Perform property injection. Run [SetParametersAsync](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#when-parameters-are-set-setparametersasync).
> Call [OnInitialized{Async}](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#component-initialization-oninitializedasync). If an incomplete [Task](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task) is returned, the [Task](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task) is awaited and then the component is rerendered.
> Call [OnParametersSet{Async}](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#after-parameters-are-set-onparameterssetasync). If an incomplete [Task](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task) is returned, the [Task](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task) is awaited and then the component is rerendered.
> Render for all synchronous work and complete [Task](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task)s.
>  Note
> 
> Asynchronous actions performed in lifecycle events might not have completed before a component is rendered. For more information, see the [Handle incomplete async actions at render](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#handle-incomplete-async-actions-at-render) section later in this article.
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Razor component lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by glatzert** [comment]
Code Reference: https://github.com/dotnet/aspnetcore/blob/daa53bd09504ab02560f1deefb16970924edcf11/src/Components/Components/src/ComponentBase.cs#L228

**Comment by guardrex** [comment]
Hello @glatzert ... This area of the docs has been approved by the product unit, specifically by Steve Sanderson, the chief engineer of the Blazor framework. Any apparent contradiction between what is written and specific lifecycle processing implementations in the Blazor framework must be chalked up to the fact that these diagrams and the text can't capture the full logic and processing of the complexities of the framework. That's what Steve told me on several occasions when similar issues were opened in the past, including (I think 🤔) this *exact question* that you ask here.

If you run into processing in practice that's totally unexpected ... totally strange 👽😄, you can open an issue on their repo to ask them about it at ...

https://github.com/dotnet/aspnetcore/issues

You'd probably need to put up a GH repro project that demonstrates the behavior and explain out in detail what lifecycle processing that you expected and what actually happened.

If you open an issue for them, please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/26989
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.

**Comment by glatzert** [comment]
Description of the process:
> Call OnInitialized{Async}. If an incomplete Task  is returned, the Task is awaited and then the component is rerendered.

Notice (like three lines later, that questions the above statement):
> Asynchronous actions performed in lifecycle events might not have completed before a component is rendered.

Also there's advice how to handle that situations: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#handle-incomplete-async-actions-at-render

A comment in the code states:
```
// Call state has changed here so that we render after the sync part of OnInitAsync has run
// and wait for it to finish before we continue. [...]
```

So - Approved or not, I think it's at least confusing and needs some clearification.

**Comment by guardrex** [comment]
Except that I've already spoken with Steve about this on multiple occasions, and I always get the same answer.

I can't ping him again ... and again ... *and again* 😄 ... to look at issues on these remarks because he's going to get 😠 with me 😨.

When this has come up in the past on the exact passages that you've asking about, he has declined to make any changes to this text and to these diagrams. He told me that this is the best we can do here. These are *oversimplifications* and *general behaviors* of the framework.

I was just thinking perhaps that the lead-in text should say that this content is an oversimplification. Currently, the topic makes it sound like this is **_THE exact way_** the framework processes lifecycle events. I'll think about that a bit more for perhaps an update in that vein.

If you want to open an issue on the product unit repo to ask about these aspects, that's cool. Please add that cross-link/ping for me so that I can follow along 👂👀. I'll react to his (or Javier's ... or Tanay's) orders for any changes that they want. I just can't ping him again myself to probably get the same answer that he's given me three times in a row ... in each case with him giving me the same answer and without change orders for the content/diagrams.

btw --- I would say one more little thing about asking them about this at this time. As you're probably aware, 7.0 RC1 is due out *any second now* ⏱️. It might be best to wait until Monday to open an issue over there. I'm fairly certain that they're all 🏃‍♂️ like mad at the moment to get the RC1 release out.

**Comment by glatzert** [comment]
I understand. Thanks for your time :)

(Are you trying to send me to the lions den here? :D)

**Comment by guardrex** [comment]
# 😆

**_Yes!_** ..... *Let's NOT get the docs guy SHOT today!* 🦖🔫⚰️🤣

They won't mind if you ask, but I've already asked this question multiple times. I will be 👂 and 👀 on the discussion. It might lead to an update of some sort.

**Comment by guardrex** [comment]
... I also think that this text should say that these remarks and the diagram are an oversimplification. I'm going to add a note on this to a tracking issue for future work. It's for things that don't quite rise to the level of backlogging an issue for several months. It won't get lost there. You can see that I work those regularly when I get time.
