### ISSUE TITLE
Lazy-loading CSS files

### ISSUE THREAD

**Issue by Michael-Ziluck** [dotnet/AspNetCore.Docs#26994]
This page does a great job explaining how to LazyLoad DLLs in a project. What it doesn't touch on however is how you lazy-load static assets from within said DLLs.

Say my RCL has a reference to another project (in my case MatBlazor). How would I go about loading the necessary CSS and JS files into my app without needing to eager load the CSS.

I'm not sure if this is better presented as a feature request but I would be surprised if such functionality does not already exist.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690632ad-f357-161f-217b-faba56e90f36
* Version Independent ID: 626c5ed9-6424-7940-56e2-a19989b6de38
* Content: [Lazy load assemblies in ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/webassembly-lazy-load-assemblies.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/webassembly-lazy-load-assemblies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Michael-Ziluck ... For JS, the product unit recommends [collocated JS files](https://docs.microsoft.com/aspnet/core/blazor/javascript-interoperability/#load-a-script-from-an-external-javascript-file-js-collocated-with-a-component) and [JS modules](https://docs.microsoft.com/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet#javascript-isolation-in-javascript-modules) ... although we don't use these approaches in article examples because they take up too much space ... we just go ahead and use global JS bits in the `index.html` or `_Host.cshtml` page for expediency. For CSS, you can use [CSS isolation](https://docs.microsoft.com/aspnet/core/blazor/components/css-isolation), which is essentially collocation of CSS. Other possible options include alternative [layouts](https://docs.microsoft.com/aspnet/core/blazor/components/layouts) and [control of `<head>` content (`HeadContent`)](https://docs.microsoft.com/aspnet/core/blazor/components/control-head-content).

... and this all depends on what you mean by "lazy," too. Much of what Blazor has built-in ☝️ is about deferred loading to the component requested, as is the case with lazy-loading DLLs. However, "lazy" can also mean in the component/page lifecycle itself. Everything Blazor can do is covered by the docs today ☝️. If you wanted to explore more advanced techniques and third-party approaches, we recommend discussing with devs on public chat and seeing what devs are showing at Awesome Blazor ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](https://join.slack.com/t/aspnetcore/shared_invite/zt-1b60h73p0-PZPq3YCCaPbB21RcujMSVA)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)
* [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor) (Community-maintained collection of Blazor resources)

If you have a new feature idea that would like to float to the product unit, open a feature request on their repo ...

https://github.com/dotnet/aspnetcore/issues

I'm going to close because I don't think that there's anything actionable. However, I am going to note your issue on a tracking issue that I keep for things to look at later because I think cross-linking the techniques that I described at the bottom of the lazy-loading DLLs topic might be a good idea. We're all 🏃‍♂️ at the moment on the 7.0 stuff, but that will be done and out in November. I'll have time to circle back to this for a look see 👀 at EOY. Thanks for the issue.

**Comment by Michael-Ziluck** [comment]
Thanks for the push in the right direction! I had skimmed through those docs but it took until your reply for me to put 2 and 2 together. For anyone who may want this functionality and stumbles across this issue, here's what ended up working for me.

In your `App.razor` file, include the following block outside of the `@code` section:
```razor
<HeadContent>
  @foreach (var styleSheet in lazyLoadedCss)
  {
    <link href="@styleSheet" rel="stylesheet"/>
  }
</HeadContent>
```

Within the `@code` section, I used the following:
```c#
private List<string> lazyLoadedCss = new();

  private async Task OnNavigateAsync(NavigationContext args)
  {
    try
    {
      foreach (var bundle in AppLazyLoader.AssemblyBundles)
      {
        // TODO add this as a where clause above
        if (!bundle.RoutePatterns.Any(pattern => Regex.Match(args.Path, pattern).Success))
        {
          continue;
        }

        lazyLoadedAssemblies.AddRange(await AssemblyLoader.LoadAssembliesAsync(bundle.Assemblies));

        // load the script files
        foreach (var scriptFile in bundle.ScriptFiles.Concat(bundle.ExternalScriptFiles ?? Array.Empty<string>()))
        {
          await JS.InvokeVoidAsync("import", scriptFile);
        }

        // load css
        lazyLoadedCss.AddRange(bundle.CssFiles);
        lazyLoadedCss.AddRange(bundle.ExternalCssFiles ?? Array.Empty<string>());
      }
    }
    catch (Exception ex)
    {
      Logger.LogError("Error: {Message}", ex.Message);
    }
  }
```

`AppLazyLoader` is a static class that contains the following property:
```c#
public static readonly LazyLoadedBundle[] AssemblyBundles = ...;
```

Lastly, `LazyLoadedBundle` is a model that looks like:
```c#
public class LazyLoadedBundle
{
    public IEnumerable<string> RoutePatterns { get; set; }

    public IEnumerable<string> Assemblies { get; set; }

    public IEnumerable<string> CssFiles { get; set; }
    public IEnumerable<string>? ExternalCssFiles { get; set; }

    public IEnumerable<string> ScriptFiles { get; set; }
    public IEnumerable<string>? ExternalScriptFiles { get; set; }
}
```

This was for a POC I was doing so it could probably use a bit more design though like how best to load the values and then also unloading CSS/Scripts once a user navigates away from a route. That being said, this works perfectly for what I was looking for in my original ask.
