### ISSUE TITLE
DotNetObjectReference multiple instances created, only last one disposed

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#27036]
Hi,
in this code:
```
@page "/call-dotnet-example-2"
...
    <button @onclick="TriggerDotNetInstanceMethod">
        Trigger .NET instance method
...
@code {
  ...
    public async Task TriggerDotNetInstanceMethod()
    {
        objRef = DotNetObjectReference.Create(this);
        result = await JS.InvokeAsync<string>("sayHello1", objRef);
    }
    public void Dispose()
    {
        objRef?.Dispose();
    }
}
```
You're calling `DotNetObjectReference.Create` on each button click, so `Dispose` will only execute on the last created instance. 
Is that an issue ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2964d558-cd6d-7421-f7b9-cb939792c2cf
* Version Independent ID: a3517e56-69fc-1ec7-b55a-dbb54d68a807
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @omuleanu ... 

I don't think that's a concern because I think it will point to the same object instance. However, I'm not knowledgeable enough on the ✨ *Magic Blazor Bits*&trade; ✨ to know for sure or provide further details, as I'm just a silly doc dinosaur 🦖. There have been several PRs with product unit approvals of this **_pattern_**. For example, I found the following example in a quick search that Pranav looked at and signed off on back in 2020. This particular example has been updated over the years; but in it's original form, it looked like this ...

```razor
@page "/JSInteropComponent"
@using BlazorSample.JsInteropClasses
@implements IDisposable
@inject IJSRuntime JSRuntime

<h1>JavaScript Interop</h1>

<button type="button" class="btn btn-primary" @onclick="TriggerNetInstanceMethod">
    Trigger .NET instance method HelloHelper.SayHello
</button>

@code {
    private DotNetObjectReference<HelloHelper> _objRef;

    public async Task TriggerNetInstanceMethod()
    {
        _objRef = DotNetObjectReference.Create(new HelloHelper("Blazor"));
        await JSRuntime.InvokeAsync<string>(
            "exampleJsFunctions.sayHello",
            _objRef);
    }

    public void Dispose()
    {
        _objRef?.Dispose();
    }
}
```

Cross-reference: https://github.com/dotnet/AspNetCore.Docs/pull/16828/files

😆 ... and that was back in the day that I was still putting underscores on fields. We ended up dropping that since then and don't recommend it any longer.

Anyway ... Pranav looked right at it 👀 and said on the PR ...

> This looks fine btw 👍

Cross-reference: https://github.com/dotnet/AspNetCore.Docs/pull/16828#issuecomment-586003135

There have been several reviews of the pattern and approvals of this nature over the years for the text in these sections and the examples shown. If you want to ask the product unit about this, they'll probably provide more information. If you open an issue with them at ...

https://github.com/dotnet/aspnetcore/issues

... here are a couple of helpful cross-links for your issue (these are cut-'n-paste) ...

* \[Call .NET from JS: *Pass a DotNetObjectReference to an individual JavaScript function* section](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#pass-a-dotnetobjectreference-to-an-individual-javascript-function)
* \[`DotNetObjectReference.Create<TValue>(TValue) Method`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.jsinterop.dotnetobjectreference.create?view=aspnetcore-6.0#microsoft-jsinterop-dotnetobjectreference-create-1(-0))

... and I recommend showing them the code from your opening comment ☝️.

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/27036
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.

**Comment by omuleanu** [comment]
@pranavkm could you please have a look.
is it ok to only dispose the last created instance of `DotNetObjectReference` ?
or is it ok to not call dispose on any of them

**Comment by guardrex** [comment]
Ah! ... Actually, he's no longer on that team, so he won't be able to respond. Also, I don't want to ping on the product unit from here. Please open an issue on the PU repo to ask. This falls more under a "support request" at this point. We'll re-open the doc issue and work it if they provide something juicy for the content.

**Comment by guardrex** [comment]
... and btw ... 

> is it ok to not call dispose on any of them

You *must* call dispose on it. The *one* that I think exists here. Otherwise, it won't be GCed ... at least not for a while.

**Comment by guardrex** [comment]
We'll be working this forward per https://github.com/dotnet/aspnetcore/issues/44064#issuecomment-1259783238.

The `Create` call will be moved to component init so that it will only be called once.

**Comment by guardrex** [comment]
@MackinnonBuck ... Let me run one update by you in advance for this (TL;DR ... this is for the JS interop updates that don't dispose properly because `DotNetObjectReference.Create` creates new instances in button click scenarios).

The original example for a class instance example is at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#class-instance-examples

It goes like this ...

```javascript
<script>
  window.sayHello1 = (dotNetHelper) => {
    return dotNetHelper.invokeMethodAsync('GetHelloMessage');
  };
</script>
```

`HelloHelper.cs`:

```csharp
using Microsoft.JSInterop;

public class HelloHelper
{
    public HelloHelper(string? name)
    {
        Name = name ?? "No Name";
    }

    public string? Name { get; set; }

    [JSInvokable]
    public string GetHelloMessage() => $"Hello, {Name}!";
}
```

`JsInteropClasses3.cs`:

```csharp
using Microsoft.JSInterop;

public class JsInteropClasses3 : IDisposable
{
    private readonly IJSRuntime js;
    private DotNetObjectReference<HelloHelper>? objRef;

    public JsInteropClasses3(IJSRuntime js)
    {
        this.js = js;
    }

    public ValueTask<string> CallHelloHelperGetHelloMessage(string? name)
    {
        objRef = DotNetObjectReference.Create(new HelloHelper(name));

        return js.InvokeAsync<string>("sayHello1", objRef);
    }

    public void Dispose()
    {
        objRef?.Dispose();
    }
}
```

`Pages/CallDotNetExample4.razor`:

```razor
@page "/call-dotnet-example-4"
@implements IDisposable
@inject IJSRuntime JS

<h1>Call .NET Example 4</h1>

<p>
    <label>
        Name: <input @bind="name" />
    </label>
</p>

<p>
    <button @onclick="TriggerDotNetInstanceMethod">
        Trigger .NET instance method
    </button>
</p>

<p>
    @result
</p>

@code {
    private string? name;
    private string? result;
    private JsInteropClasses3? jsInteropClasses;

    private async Task TriggerDotNetInstanceMethod()
    {
        jsInteropClasses = new JsInteropClasses3(JS);
        result = await jsInteropClasses.CallHelloHelperGetHelloMessage(name);
    }

    public void Dispose()
    {
        jsInteropClasses?.Dispose();
    }
}
```

I would like to preserve passing the name in the ctor in this example, as opposed to refactoring the `GetHelloMessage` method in `HelloHelper` to take a `name` parameter. I think this use case where creating a class instance with some properties set is a better example.

I propose to change this example to the following, which will dispose in the JS ...

```javascript
window.sayHello3 = (dotNetHelper) => {
  var message = dotNetHelper.invokeMethodAsync('GetHelloMessage');
  dotNetHelper.dispose();
  return message;
};
```

**NOTE**: I'm changing the JS FN name from `sayHello1` to `sayHello3` because `sayHello1` is used in an earlier example in this article. That earlier example will maintain use of `sayHello1`, and I'll go with `sayHello3` for the updated example.

`HelloHelper.cs`: **_Unchanged_**

`JsInteropClasses3.cs`:

```csharp
using Microsoft.JSInterop;

public class JsInteropClasses3
{
    private readonly IJSRuntime js;

    public JsInteropClasses3(IJSRuntime js)
    {
        this.js = js;
    }

    public ValueTask<string> CallHelloHelperGetHelloMessage(string? name)
    {
        return js.InvokeAsync<string>("sayHello3", 
            DotNetObjectReference.Create(new HelloHelper(name)));
    }
}
```

`Pages/CallDotNetExample4.razor`:

```razor
@page "/call-dotnet-example-4"
@inject IJSRuntime JS

<h1>Call .NET Example 4</h1>

<p>
    <label>
        Name: <input @bind="name" />
    </label>
</p>

<p>
    <button @onclick="TriggerDotNetInstanceMethod">
        Trigger .NET instance method
    </button>
</p>

<p>
    @result
</p>

@code {
    private string? name;
    private string? result;
    private JsInteropClasses3? jsInteropClasses;

    protected override void OnInitialized()
    {
        jsInteropClasses = new JsInteropClasses3(JS);
    }

    private async Task TriggerDotNetInstanceMethod()
    {
        if (jsInteropClasses is not null)
        {
            result = await jsInteropClasses.CallHelloHelperGetHelloMessage(name);
        }
    }
}
```

### How does that look?

**Comment by MackinnonBuck** [comment]
@guardrex That's definitely an improvement!

I think the slightly confusing part about this change could be that it's not obvious just by looking at the `CallHelloHelperGetHelloMessage()` method that the `DotNetObjectReference` will be disposed. That's more of a subtle implementation detail in `sayHello3`, whose name doesn't really imply that its job is to dispose the `dotNetHelper` passed to it.

I wonder if we could remove the `dotNetHelper.dispose()` line and change `JsInteropClasses3` to the following:

```csharp
using Microsoft.JSInterop;

public class JsInteropClasses3 : IDisposable
{
    private readonly IJSRuntime js;

    public JsInteropClasses3(IJSRuntime js)
    {
        this.js = js;
    }

    public async ValueTask<string> CallHelloHelperGetHelloMessage(string? name)
    {
        using var objRef = DotNetObjectReference.Create(new HelloHelper(name));
        return await js.InvokeAsync<string>("sayHello1", objRef);
    }
}
```

Note the `using` keyword in `CallHelloHelperGetHelloMessage`, which will automatically dispose `objRef` when it falls out of scope. This keeps the creation and disposal of `objRef` all in one place and (imo) makes it slightly more obvious that disposing `DotNetObjectReference`s is recommended.

What do you think?

**Comment by guardrex** [comment]
*Perfect!* I'll go that way with it. *Thanks!*
