### ISSUE TITLE
Clarify IIS App Pool pipeline mode recommendation

### ISSUE THREAD

**Issue by Siphonophora** [dotnet/AspNetCore.Docs#27135]
Hi, the doc here are clear about `No Managed Code` setting for an App Pool. In a few places, like the picture below you can see 'Integrated' has been chosen, but I don't see commentary about what's recommended for this setting.

![image](https://user-images.githubusercontent.com/32316111/193107338-ef515cd8-9ffa-468c-9dd8-11a599c1269d.png)

A note about which to chose and why, or a linkout would be nice because both seem to work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d172b69-845d-739a-742c-617b9eed04fe
* Version Independent ID: 79d553f1-9112-b61a-0ad0-dfbb11e5071a
* Content: [Advanced configuration](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/iis/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/advanced.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
Thanks @Siphonophora.  It would be helpful to explain why **No Managed Code** is recommended and what it does right where it is recommended with that screen shot showing it was set.

That said, the **No Managed Code** option is mentioned in a previous section of the topic with the following:

"To host an ASP.NET Core app as a sub-app under another ASP.NET Core app:

Establish an app pool for the sub-app. Set the .NET CLR Version to No Managed Code because the Core Common Language Runtime (CoreCLR) for .NET Core is booted to host the app in the worker process, not the desktop CLR (.NET CLR)."

**Comment by Rick-Anderson** [comment]
https://learn.microsoft.com/en-us/iis/application-frameworks/building-and-running-aspnet-applications/how-to-take-advantage-of-the-iis-integrated-pipeline
https://learn.microsoft.com/en-us/archive/blogs/tmarq/iis-7-0-asp-net-pipelines-modules-handlers-and-preconditions

**Comment by Siphonophora** [comment]
Took some more looking, but this is what I was hoping to find:

> You should only add an application to an application pool in Classic mode if the application fails to work in Integrated mode. 

from https://learn.microsoft.com/en-us/iis/get-started/introduction-to-iis/introduction-to-iis-architecture
