### ISSUE TITLE
httprepl -c|--content syntax error

### ISSUE THREAD

**Issue by mcurros2** [dotnet/AspNetCore.Docs#27235]
The docs state:

> Provides an inline HTTP request body. For example, -c "{"id":2,"name":"Cherry"}"

In order to work, the double quotes should be escaped, if not you get http error 400.

It sould be corrected to:

-c "{\\"id\\":2,\\"name\\":\\"Cherry\\"}"

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b76f907-1815-d4d3-c04b-8df935941d8b
* Version Independent ID: 8426ee38-422d-6286-70eb-f7f38cca0dd0
* Content: [Test web APIs with the HttpRepl](https://learn.microsoft.com/en-us/aspnet/core/web-api/http-repl/?view=aspnetcore-6.0&tabs=windows#test-http-post-requests)
* Content Source: [aspnetcore/web-api/http-repl/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/http-repl/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

---
[Associated WorkItem - 60874](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60874)

**Comment by Rick-Anderson** [comment]
Yes, I remember that, in general testing Web API's depends to on the testing tool. What happens when you use

`-c "{d:2,name:\"Cherry\"}"` ?
What about single quotes?

Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by tdykstra** [comment]
> What happens when you use
>
> `-c "{d:2,name:\"Cherry\"}"` ?
> What about single quotes?

400 in both cases
