### ISSUE TITLE
Complete working sample For Blazor Maui Authentication with Identity4

### ISSUE THREAD

**Issue by hgirma** [dotnet/AspNetCore.Docs#27404]
It would be helpful to have a working sample. 

For example, The experience of a brand new project ( File | New project) to create a Blazor WebAssembly App wires up the authentication with Identity4, and it works out of the box, something similar like that, but for MAUI Blazor App would be helpful.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb3ca917-28cc-126f-a7ff-3ff00ad30677
* Version Independent ID: cb3ca917-28cc-126f-a7ff-3ff00ad30677
* Content: [ASP.NET Core Blazor Hybrid authentication and authorization](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/?view=aspnetcore-6.0&pivots=maui)
* Content Source: [aspnetcore/blazor/hybrid/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hgirma ... Management (***and I*** 😄) aren't keen on hosting sample apps here because they're challenging to maintain release-to-release and the options are wildly variable.

The first problem is that takes a lot of time ... ***thus 💰💰💰*** ... to keep up with many sample apps. What happens is that one or two samples are added, which seems trivial ... but then you add one or two more later ... then a little more time goes by, and you add one or two more. After a year or two, you find yourself with ***dozens of out-of-date samples every release***. Devs then get very upset 😡 and send us a lot of 💀 ***death threats*** ⚰️🤣 LOL about old broken samples for the current release, just in time for 🧛 ***Halloween*** 🎃, right??!! 😆

The second problem is the wildly variable technologies in this area that can be used. For example, there are several auth providers out there; and as you point out WRT the backing stores, there are many of those, too. There are many permutations of technologies in this area. Even if we hosted such a tutorial/sample app, we'd need to narrow it down to a specific combination of technologies, which is BAD for innovation IMO ... picking "winners" and promoting them with official MS docs and samples over other equally fine choices from other third-parties and up-and-commer *NEW* technology from additional third-parties that might be better than what we picked and what has been available in the past.

For those reasons, we're not going to create/host such a sample app(s) here. They may change their mind at some point in this case; but near-term, we won't do it.

BTW ... Note that IdS4 isn't described/implicitly recommended by MS at this time for any IdS scenario. They selected/implicitly recommend [Duende IdS](https://duendesoftware.com/products/identityserver). Even if we did host such a sample app/tutorial, it would be based on Duende, not IdS4.

***However***, I'm glad you asked because I found resources in this area in the MAUI docs ... either new content or content that I missed when we put the MAUI docs up on this repo. See the following resources over in MAUI docs ...

* https://learn.microsoft.com/dotnet/maui/platform-integration/communication/authentication
* https://github.com/dotnet/maui/tree/main/src/Essentials/samples/Sample.Server.WebAuthenticator

I ***definitely*** need to cross-link those resources to this topic. I'll do that right now. Leave this issue open, as it will close automatically when the PR is merged.
