### ISSUE TITLE
The target "CompileTypeScript" does not exist in the project.

### ISSUE THREAD

**Issue by StevenTCramer** [dotnet/AspNetCore.Docs#27509]
Following the instructions on this page fail when trying to add TypeScript support with the following message:

Error	MSB4057	The target "CompileTypeScript" does not exist in the project.	TypeScript	C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	1154	

the 
```csproj
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <TypescriptOutDir>wwwroot</TypescriptOutDir>
    <PrepareForBuildDependsOn>
      CompileTypeScript;
      GetTypeScriptOutputForPublishing;
      $(PrepareForBuildDependsOn)
    </PrepareForBuildDependsOn>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="6.0.10" />
  </ItemGroup>
  
</Project>
```

There is no mention of adding `Microsoft.TypeScript.MSBuild` to the project.  Isn't that required?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-6.0&tabs=visual-studio#typescript-integration)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @StevenTCramer ... Yep! That's probably an oversight on my part. Try adding it to the project file like this ...

```xml
<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="4.8.4">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
```

... btw ... `4.8.4` is the latest stable release.

If that works out, then the guidance will need that bit ... ***AND*** it should just link to NuGet (`https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild/`) to both name the package reference package and ***how to reference it (i.e., don't show the package ref XML markup in the topic ... let NuGet show it).*** The churn can get you on something like that 😈😨...😄.

Rick ... since I likely screwed this one up 🙈, I'll take on the fix.

@StevenTCramer, let me know here if that works out.

**Comment by guardrex** [comment]
Yeah ... I just confirmed it here. I'll patch that up right now.
