### ISSUE TITLE
Mention limitations of pre-render size

### ISSUE THREAD

**Issue by Bouke** [dotnet/AspNetCore.Docs#27531]
I was debugging an issue with a page that rendered, but started showing the "reconnecting" dialog after ~20 seconds or so. There was no error server-side and the client-side contained rather unhelpful traceback:

> [Error] [2022-11-08T09:44:35.259Z] Error: Error: Circuit host not initialized.
	log (blazor.server.js:1:115822)
	(anonymous function) (blazor.server.js:1:122515)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob

After some investigation I've found a similar issue with this message: https://github.com/dotnet/aspnetcore/issues/44280#issuecomment-1266747939. This is a severe problem in our situation, as we don't know beforehand the pre-rendered size of certain data. The failure mode here is completely wrong: when you go over the limit, the client will fail to initialize and you have no way of detecting this nor recovering. State preservation should fail server-side when trying to persist data that will be over the limit.

In any case: this limitation should be included in the documentation as it will cause serious problems for users.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 329a19ef-fb46-1f6b-a734-fa1c1334b1e5
* Version Independent ID: 3fa4318a-3c11-c1d8-bf24-ddc6d8441ca2
* Content: [Prerender and integrate ASP.NET Core Razor components](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0#persist-prerendered-state)
* Content Source: [aspnetcore/blazor/components/prerendering-and-integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/prerendering-and-integration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @Bouke ... I'll get this into the prerendering coverage, cross-linked to our SignalR coverage for the message size limit, which is minimal because we cross-link for the most part to the SignalR docs ...

https://learn.microsoft.com/aspnet/core/blazor/fundamentals/signalr#circuit-handler-options-for-blazor-server-apps

... and I'll add a warning to the prerendering coverage about the risk of DoS increasing when increasing the size limit.

For anything else that pertains to the framework's behavior, such as the concern about how the error isn't helpful, please open those aspects for the product unit to address at ...

https://github.com/dotnet/aspnetcore/issues

**Comment by Bouke** [comment]
Thank you! I've filed this at https://github.com/dotnet/aspnetcore/issues/44935.
