### ISSUE TITLE
Improve coverage of Blazor JS interop disposal patterns

### ISSUE THREAD

**Issue by lonix1** [dotnet/AspNetCore.Docs#27536]
Hey @guardrex, here's another important corner case.

The blazor docs  cover js module disposal [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#javascript-isolation-in-javascript-modules).

However if javascript event handlers are registered, they should (probably?!) be [released](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener), else they're liable to cause hard to debug problems.

An interesting solution can be found [on SO](https://stackoverflow.com/a/70614374/9971404) by @jessegood. In summary:

`MyComponent.razor.js`
````cs
export function dispose()
{
  _myElement.removeEventListener("mousedown", handleMouseDown);
}
````

`MyComponent.razor`
````cs
@implements IAsyncDisposable
@code {
  private IJSObjectReference? _module;
  public async ValueTask DisposeAsync()
  { 
    if (_module != null)
    {
      await _module.InvokeVoidAsync("dispose");        // <---------------
      await _module.DisposeAsync();
    }
  }
}
````

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7ea38a-649b-303d-bebf-c701e216ba25
* Version Independent ID: 9e197a8b-2616-8363-0a15-38cac802e82e
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
AFAIK per https://github.com/dotnet/AspNetCore.Docs/pull/27439, which Steve reviewed, that can't be called if a circuit is being disposed.

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#javascript-interop-calls-without-a-circuit

The alternative to JS interop during disposal is to use the `MutationObserver` pattern in client code.

If you need additional support on these scenarios, you can open a product unit issue at ...

https://github.com/dotnet/aspnetcore/issues

If you inquire on it, please add the following to your opening comment ...

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/27536
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.

**Comment by guardrex** [comment]
Yes, that should be fine. Actually, I think I'll work on this in the near-term, so let's let this issue track it. I'll probably be able to reach this within a few weeks.

**Comment by guardrex** [comment]
***NOTE TO SELF***: Double-check cross-linking because the JS interop approach for placing JS code in an app doesn't look like it received a cross-link to the new guidance for Blazor Server where it speaks to disposal without a circuit, and this new bit for Blazor WASM will also need cross-linking from the same location.

**Comment by guardrex** [comment]
@lonix1 ... Moving back over here now that Javier provided information for this.

Just for completeness here ... as a bit more ***NOTE TO SELF*** so that I don't forget ...

On the *Call JS* side, disposal of `IJSObjectReference` appears in the example at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-7.0#javascript-isolation-in-javascript-modules

... ***BUT***, the disposal example that uses a module's FN doesn't appear until the reader reaches Steve's Mapbox example at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-7.0#javascript-libraries-that-render-ui

... along with the new guidance on disposal without a circuit at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-7.0#javascript-interop-calls-without-a-circuit

JS-side disposal isn't currently covered in the *Call JS* article, so I'll see about working that in.

Overall, I think ***dedicated sections with disposal examples on each side (JS and .NET) SxS*** will clear all of this up.

I have at least a week of .NET 7 release work to do, so I hope to reach this by the middle of next week. I'll ping u on the PR when it goes up. If I run into problems/concerns, I'll ask Javier to review the PR. If I can base it directly on prior approved guidance and his latest remarks, I won't need his review. This will mostly end up being a re-organization and enhancement of coverage based on what he just said ... no need to bug him further if all goes well.

**Comment by guardrex** [comment]
During a release, it's pretty much .......

# ⛰️⛏️😅 

... followed by a lot of ...

# 🏃🏃🏃🏃🏃🏃🏃🏃🏃🏃😅 

... and then things will calm down in a week ... or ***THREE!!!*** 😆

I'll try to get back to this by the end of next week; but if you don't hear from me by then, it will slip one more week. I definitely want it resolved by 🦃 Day tho. I'd like to get a restful 🦃 weekend break before a big security docs push through EOY. I'll ping u on the PR later.

**Comment by guardrex** [comment]
I ***almost*** made it back to this 😅. It's the next item on the regular workload list.

I'm kind'a 🧠 ***fried*** at the moment to take it on the last day prior to the 🦃 weekend holiday. Then, I have a feeling that given the high priority Blazor *Security* node work that needs to be addressed in the 🦃 to *New Years* 🎆 period that this will get pushed back to early January.

I would've preferred to square this away prior to the *Security* node work, but there was a large amount of work to do for .NET 7's release and a mop-up of a bunch of issues lying around prior to reaching the *Security* node. I literally just got caught up to reach this issue this morning. I will get to this one as soon as I can, and I think it will be early January. It's a top priority ***after*** the *Security* node work is complete.
