### ISSUE TITLE
Blazor Virtualize Docs Are Confusing

### ISSUE THREAD

**Issue by richward1** [dotnet/AspNetCore.Docs#27537]
[Here](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-6.0) are the docs for Blazor Virtualize.

Some of the examples around the items provider delegate feel very disjointed, and are confusing.
For example, the following block:

```csharp
private Virtualize<FetchData>? virtualizeComponent;

protected override void OnInitialized()
{
    WeatherForecastSource.ForcecastUpdated += async () => 
    {
        await InvokeAsync(async () =>
        {
            await virtualizeComponent?.RefreshDataAsync();
            StateHasChanged();
        });
    });
}
```

Doesn't explain where `virtualizeComponent` is assigned, or how to hook it up (to presumably a `<Virtualize />` component?);

Neither does it explain where the type `FetchData` has come from (it's only referenced that one time in the entire document), and doesn't seem to follow on from the previous examples.

### Context

I'm trying to figure out how to get a virtualized component to show only the items that I've scrolled into view, while the source item list is constantly growing - the default implementation seems to scroll the container when a new item is added. But I'm stuck just trying to follow this bit of the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f4ab8b4-4d2e-9e1b-793e-dbb17f6d694d
* Version Independent ID: 26ed2425-63ec-e206-edcb-e51f17edb844
* Content: [ASP.NET Core Razor component virtualization](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/virtualization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/virtualization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by richward1** [comment]
Of course, I figured it out just minutes after opening the issue.
I needed an `@ref`...

**Comment by guardrex** [comment]
Yes, that's right, @richward1. The reason is that this doc came over directly from the product unit ... directly from Microsoft engineers who aren't too keen on showing full examples. What happens in these cases is that I take their doc, go ahead and publish it, and then as soon as possible dig into it with a set of extensive updates to include ***fully-working, cut-'n-paste examples***. That's what this topic needs. I'm going to add this to a tracking issue shortly for a doc that needs the 🦖 ***Rex Treatment***&trade; 🦖 to make sure that it gets scheduled for 23Q1.

**Comment by richward1** [comment]
Perfect, thanks for the swift response!
