### ISSUE TITLE
What are Tag Helpers?

### ISSUE THREAD

**Issue by Loophole62ndFF** [dotnet/AspNetCore.Docs#27551]
After reading the section "What are Tag Helpers", I am still left with the question "What are Tag Helpers?".  The section tells a lot about what "tag helpers" do, but I still have no idea how to recognise one if I see it in some HTML.  What does a "tag helper" look like?  How do I tell if I am looking at a "tag helper" in some random chunk of HTML I am trying to debug?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62cdbf88-1fff-6999-f75a-26fbe730b911
* Version Independent ID: bc48b5cb-d500-f75d-8e48-be4d069a9198
* Content: [Tag Helpers in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-7.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Loophole62ndFF ... Part of the answer ... unfortunately tho not accessible for all devs because it's based on color vision ... is at ...

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-7.0#intellisense-support-for-tag-helpers

An accessible approach that I don't think the topic describes is that you can rollover the tag and see that it uses the TH namespace, such as this example for the Cache TH ...

![image](https://user-images.githubusercontent.com/1622880/200827433-8775549c-fcd9-4916-bd1a-1f126ff579cf.png)
