### ISSUE TITLE
Meaning of note: "Insecure gRPC services must be hosted on a HTTP/2-only port"

### ISSUE THREAD

**Issue by codezerox86** [dotnet/AspNetCore.Docs#27682]
What does this mean: "Insecure gRPC services must be hosted on a HTTP/2-only port" ?

Does this mean we can not listen on port 80 as HTTP/2 endpoint without TLS ? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c730b5f9-031e-beab-b838-6e2f8befde30
* Version Independent ID: 84ddcb67-03be-655c-470a-f43a5152606f
* Content: [Troubleshoot gRPC on .NET Core](https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-7.0)
* Content Source: [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
@JamesNK, is the point the following?: That if the endpoint is not configured with TLS (insecure), then rather than having the option of HTTP/1.1 or HTT/2 which negoatiated by TLS, you only have HTTP/2 as an option and therefore that must be set explicitly in the endpoint's ListenOptions.Protocols?  So it does not matter if you listen on port 80 (http), but it does matter that the endpoint is set to HTTP/2.  In, other words, you can listen on port 80 as an HTTP/2 endpoint without TLS, but that's how.  If so, maybe I can reword it a bit to clarify.  If not, a good learning opportunity for me here as well.

**Comment by JamesNK** [comment]
@codezerox86 Please read the linked document that is immediately after that sentence with more information: https://learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-7.0&tabs=visual-studio#protocol-negotiation
