### ISSUE TITLE
Hi. I saw thar calling StateHasChanged() from SignalR thread throws an exception

### ISSUE THREAD

**Issue by meirkr** [dotnet/AspNetCore.Docs#27737]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Version Independent ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Content: [Use ASP.NET Core SignalR with Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
### ***We're back!*** ⛏️😄 

Hello @meirkr ... Please open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

You'll probably need to explain it out a bit more for them, especially exactly what the error is and a stack trace/client log. Clarify if you're using an app exactly per [this Blazor tutorial article](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0&tabs=visual-studio&pivots=webassembly), and clarify for them that you're using the Blazor WebAssembly hosting model or the Blazor Server hosting model. You could show some code for exactly where/how you're calling `StateHasChanged`. Be prepared for them asking you for a GH repro sample app that demonstrates the problem. They might not need it initially and immediately see the problem. I'm just saying to be mentally prepared that they might ask for it in case they aren't sure what's happening.

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/27737
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.
