### ISSUE TITLE
What about refreshing the token

### ISSUE THREAD

**Issue by tomkuijsten** [dotnet/AspNetCore.Docs#27745]
The documentation is quit clear about storing the access/refresh tokens and make an API request, but the hard part, refreshing the token is left out.

Refreshing the token is not that hard, storing it back into the cookie of the user is! Please, add a section here with an implementation for refreshing the token and store it in the cookie. That last bit is crucial, otherwise it won't work if you close the browser tab and reopen one.

If you won't document this, then at least give a pointer to a SO / blog.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8acbbf-c9d4-7041-c1a7-ec9ce8f0981b
* Version Independent ID: c98be365-408d-7ee6-cb74-14c44d01b0b8
* Content: [ASP.NET Core Blazor Server additional security scenarios](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/security/server/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/server/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
### ***We're back!*** ⛏️😄 

Hello @tomkuijsten ... This has been a fairly regular ask, but keep in mind that there is no HTTP request/response for components, just a WebSocket. 🤔 I believe that there is a JS interop workaround approach from the client that will trigger a cookie refresh server-side that ***might*** work, but it isn't something that the product unit wants to call out in the docs. There might be some nasty risks involved 😈😨 ... not sure. I do know that the product unit has avoided providing me with any approach outside of having users sign-in into the app again to refresh the tokens. What you might do is search the open ***AND CLOSED*** product unit issues on this to see what they've told devs in the past at ...

https://github.com/dotnet/aspnetcore/issues

You can't (***shouldn't***) comment on closed issues. Only open a new issue if there isn't an existing issue that pertains to this subject and hasn't already been answered. Of course, please feel free to chime in on any open issues that pertain to this subject. IIRC, there is a Blazor Server auth updates IDEAS issue over there for .NET 8 coming up next year, and that might be a spot ... if it isn't already discussed ... to ask about this subject again to see if something would be considered for .NET 8. I do know that ***they know*** devs have asked about this in the past. I recall Javier discussing it on several issues over the years. You can probably get all of the background that you need from those discussions. Just remember that you have to look at the ***closed*** issues, too, and that you can't comment on them when they're closed. They don't (just like we don't here for docs) work on closed issue. If they come up with something for the next release (.NET 8) next year, I will hear about it and work up whatever docs they need to cover new API and/or new approaches.

You can also reach out to the community to see what they've been doing for refresh token management in these cases. There might even be some NuGet packages with API that will help you manage it (e.g., the aforementioned JS interop approach). Try the usual channels ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](https://join.slack.com/t/aspnetcore/shared_invite/zt-1b60h73p0-PZPq3YCCaPbB21RcujMSVA)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)
* [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor) (Community-maintained collection of Blazor resources)

I'm going close because this isn't actionable at this time. The product unit expressly doesn't want to document anything outside of just having the tokens passed through to the Blazor part of the app. Anything beyond that ... ***what you do with them*** ... is for developers to research and address on their own with their own code.
