### ISSUE TITLE
Run in Docker?

### ISSUE THREAD

**Issue by AlfredBr** [dotnet/AspNetCore.Docs#27752]
[EDIT by guardrex to change the metadata]

Any idea how to get this to run in Docker?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
### ***We're back!*** ⛏️😄 

Hello @AlfredBr ... Currently, the product unit hasn't wished to support specific coverage on it. I don't think there's anything particuarly complicated ***from what I can see*** 😄 ... *I hope* 🤞🍀😆. I just performed a quick search and found this Q&A ...

https://learn.microsoft.com/en-us/answers/questions/508093/blazor-client-in-docker-container.html

... and that's nice. I'm not a Docker 🐈 myself, but I'm glad to see that it looks fairly straight-forward and that the answer there isn't very old, merely being a 5.0-era answer. It looks like it would apply to ***any version*** of Blazor WASM with Docker, owing to the concept that it's just Docker configured as a static file web server. I have a feeling that there are quite a few public resources in the Docker world about that for virtually any static file serving purpose ... Blazor or any similar hosting scenario.

I think it would be fine to have a section on this. I'm booked right through the EOY on Blazor security work. This will be a lower priority issue. I'll see about it for 23H1. Leave this open so that it can remain tracked on the Blazor.Docs GH project. It won't get lost, and I'll circle around to it next year. Thanks for the issue.

**Comment by guardrex** [comment]
Actually, I'm going to ***squeeze this in here*** 🏃 and knock it out. I'm trying to keep the backlog low for my security work.
