### ISSUE TITLE
missing a reset to position 0 in "Blazor file downloads" page

### ISSUE THREAD

**Issue by senhtry** [dotnet/AspNetCore.Docs#27762]
There should be a reset to position 0 before streamRef

```
var fileStream = GetFileStream();
var fileName = "log.bin";

fileStream.Position = 0;
using var streamRef = new DotNetStreamReference(stream: fileStream);

await JS.InvokeVoidAsync("downloadFileFromStream", fileName, streamRef);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4ad584d-0d9a-da8c-1296-b2d186e437ad
* Version Independent ID: e4ad584d-0d9a-da8c-1296-b2d186e437ad
* Content: [ASP.NET Core Blazor file downloads](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-downloads?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/file-downloads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-downloads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **taparik**

**Comment by guardrex** [comment]
### ***We're back!*** ⛏️😄 

Hello @senhtry ... Hum ... 🤔 ... I thought that I ran that bit at some point since this went up. Maybe not ... I don't recall for sure. We've been in 🏃 ***SUPER SPRINT MODE***&trade; 🏃😄 for a while getting the .NET 7 docs out. My head is still buzzing a bit from all of that.

@TanayParikh ... This came in on your PR at https://github.com/dotnet/AspNetCore.Docs/pull/23690. Do I need to reset that position, as @senhtry suggests here?

**Comment by guardrex** [comment]
@senhtry ... I can't repro a problem locally. Please open this for the product unit for them to take a look and advise ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/27762
```

... to the bottom of your opening comment so that I can follow along. If they indicate that the position reset is required, I'll re-open this issue and work it forward.
