### ISSUE TITLE
Blazor WASM validation problem

### ISSUE THREAD

**Issue by CashPJ** [dotnet/AspNetCore.Docs#27795]
Hi,

I have some strange case during use of ValidateComplexType and ObjectGraphDataAnnotationsValidator.

When i change value in InputText I am getting this
![image](https://user-images.githubusercontent.com/80749332/204801387-08de7cfb-bcdc-4103-89f3-3988048b37fb.png)

While when I trigger EditContext.Validate(), it validates form as expexted.
![image](https://user-images.githubusercontent.com/80749332/204803058-f32039c7-e9c4-49e7-b914-dc0eba195b6d.png)

Razor
```
<EditForm EditContext="EditContext">
    <ObjectGraphDataAnnotationsValidator />
    <ValidationSummary />
    
    <p>
        <InputText @bind-Value="ViewModel.TestDto.Name" />
        <ValidationMessage For="()=>ViewModel.TestDto.Name" />
    </p>
    

    <p>
        <button @onclick="()=>ViewModel.ValidateForm?.Invoke()">Validate form</button>
    </p>

</EditForm>
```
On OnInitialized 
Creating view model which holds empty (new) dto model and setting EditContext with view model.
```
protected override void OnInitialized()
{
    ViewModel = new TestViewModel();
    ViewModel.TestDto = new TestDto()
    {
        Name = string.Empty //fails validation
    };
    ViewModel.ValidateForm = () => EditContext.Validate();

    EditContext = new EditContext(ViewModel);

    base.OnInitialized();
}
```
OnAfterRender 
Loading "real" dto model data and setting it on existing view model property.
```
protected override void OnAfterRender(bool firstRender)
{
    if(firstRender){
        ViewModel.LoadTestDto();
        StateHasChanged();
    }

    base.OnAfterRender(firstRender);
}
```
View model
```
public class TestViewModel
{
    public string PageTitle => "Test page";
    public Func<bool> ValidateForm { get; set; }

    [ValidateComplexType]
    public TestDto TestDto { get; set; }

    public void LoadTestDto()
    {
        TestDto = new TestDto(InstanceIdId)
        {
            Name = "Loaded name" // pass validation
        };
    }
}
```
Dto model
```
public class TestDto
{
    [Required(ErrorMessage = "Name fieild is required.")]
    public string Name { get; set; }
}
```

When I was trying to debug on focus out validation behaviour, it seems first call of TestDto.Name getter is made on old instance of object which is created during OnInitialized and which should be replaced during OnAfterRender  life cycle event..

In case when i removed creating of new empty instance during OnInitialized, everything works as expected, but, in my case, that is not desired scenario.

Any suggestion?

Best regards

[BlazorApp1.zip](https://github.com/dotnet/AspNetCore.Docs/files/10123804/BlazorApp1.zip)

**Comment by guardrex** [comment]
Hello @CashPJ ... First off, please use the **This page** feedback form at the bottom of a topic to open issues here. It cross-links and pings the author (***ME*** 🦖 in this case 😄) that you opened the issue and applies all of the correct labeling to the issue.

WRT your app, we don't troubleshoot dev issues here with their apps. We recommend that you take it up with the community on a public support channel. We only work on the docs here. We just don't have the staffing to troubleshoot app problems. If you have a clear doc bug report 😈 to file, we ***DO*** want to hear about those here. You need to call out exactly what the problem is with the document tho.

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](https://join.slack.com/t/aspnetcore/shared_invite/zt-1b60h73p0-PZPq3YCCaPbB21RcujMSVA)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)
