### ISSUE TITLE
Clarify how static web assets work in Blazor Hybrid apps

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#27819]
We need to clarify a bit how static web assets work in Blazor Hybrid apps.

In a Blazor Hybrid app you have one or more `BlazorWebView` controls with a configured host file (typically `wwwroot/Index.html`). The host file path is relative to the project. All static web assets (scripts, CSS files, images, etc.) that are then referenced from that `BlazorWebView` are then relative to its configured host file. 

Static web assets from libraries get special generated paths: `_content/{PACKAGE ID}/`. These paths are logically sub paths of the apps wwwroot folder, even though they are actually coming from other packages or projects. The component specific CSS stye bundle will also be built at the root of the wwwroot folder (@javiercn is there any way to change or configure this location that we should document?).

If you configure a host file for a `BlazorWebView` that is in a subdirectory of the wwwroot folder (like `wwwroot/foobar/Index.html`) then you'll need to account for this when specifying relative paths to static web assets from libraries, as those will still be rooted in the wwwroot folder. Similarly, if you try to configure a host file to come from a library, or from a location other than the wwwroot folder, then this will make relative paths to other static web assets even more awkward. For most apps we recommend that the host file be at the root of the wwwroot folder of the app. 

@javiercn @MackinnonBuck @Eilon Please chime in if I got any of this wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b14a096-b1a3-2270-e57f-8238a25601cd
* Version Independent ID: 1b14a096-b1a3-2270-e57f-8238a25601cd
* Content: [ASP.NET Core Blazor Hybrid static files](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/static-files?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/hybrid/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by danroth27** [comment]
Related issue: https://github.com/dotnet/maui/issues/8613

**Comment by Eilon** [comment]
Mostly right, but I think there's a stronger statement to make regarding this:

> Similarly, if you try to configure a host file to come from a library, or from a location other than the wwwroot folder, then this will make relative paths to other static web assets even more awkward. For most apps we recommend that the host file be at the root of the wwwroot folder of the app.

You _cannot_ reference static assets from outside of the folder that contains the HostPage. So if your have `HostPage="wwwroot/sub/folder/index.html"` then your app can _only_ use static assets under `wwwroot/sub/folder/**`, and would use relative paths in the form of `**` (that is, within that deep folder).

I'm not certain exactly how this affects referenced RCLs in terms of relative paths, but the general idea is the same: if a static asset is outside of the folder containing the HostPage, it cannot be used in the app.

**Comment by Eilon** [comment]
> I'm not certain exactly how this affects referenced RCLs in terms of relative paths

I poked around in a sample app, and even in that case, the "web root" of the app determines entirely which subset of static assets are available.

Examples:

1. `HostPage="wwwroot/index.html"` --> all assets in the app's `wwwroot` folder, and every RCL's static asset are available.
2. `HostPage="wwwroot/sub/folder/index.html"` --> all assets in the app's `wwwroot/sub/folder` folder are available. RCL static assets are _not_ available because they would be in a theoretical location such as `../../_content/MyRCL/asset.png`, but that is not a supported relative path.
3. `HostPage="wwwroot/_content/MyRCL/index.html"` --> all assets in the RCL's static assets are available using relative paths (for example, `my_rcl_image.png`). The app's static assets in `wwwroot/...` are _not_ available because they would be in a theoretical location such as `../../asset.png`, but that is not a supported relative path.

So, indeed, it seems that once you use a sub-folder for the `HostPage` that is different from `wwwroot`, things get at a minimum tricky, but usually _impossible_, especially if you want to use RCLs.

I suspect two things being causes for this:

1. The BlazorWebView logic that assumes that the HostPage's containing folder is the folder for all static assets. This was a deliberate design decision we made because it was simpler, but even at the time we were open to changing it in the future (and we are).
2. I noticed that in the MSBuild targets for static assets we also make various assumptions about the `wwwroot` folder. I'm not quite sure what effect that has on things, but it probably plays some problematic role: https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/build/Microsoft.AspNetCore.Components.WebView.Maui.targets#L29

**Comment by guardrex** [comment]
@danroth27 @Eilon ...

* Are you ready for me to proceed with coverage on this?
* What's the priority? Should I take care of this now (Monday), or should I address it in early January?

**Comment by danroth27** [comment]
@guardrex I don't want to push this off for too long. This issue tripped up one a major customer that was trying to integrate some existing JS libraries into their .NET MAUI Blazor app. But early January should be fine.

**Comment by guardrex** [comment]
I'll take care of this now. The 🦷🤕 broke my rhythm anyway on the MS Graph article updates 😄. I'll ping everyone for review on the PR when it goes up.
