### ISSUE TITLE
using BlazorServerSignalRApp.Server.Hubs;  gives error

### ISSUE THREAD

**Issue by cestes0001** [dotnet/AspNetCore.Docs#27831]
This line in program.cs
Gives error

Error	CS0234	The type or namespace name 'Server' does not exist in the namespace 'BlazorServerSignalRApp' (are you missing an assembly reference?)	

It works fine in the git hub code, but not in the solution I created following the directions on this page.

Was I supposed to create a folder, 'Server' in this project into which the 'Hubs' folder goes?

Most frustrating when you have very little confidence in what you are doing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Version Independent ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Content: [Use ASP.NET Core SignalR with Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @cestes0001 ... Sounds like you didn't create a hosted Blazor WebAssembly app (or created a Blazor Server app by mistake) and are following the Blazor WebAssembly version of the article.

If you are trying to use the Blazor WebAssembly instructions, make sure that you check the **ASP.NET Core hosted** checkbox on app creation in VS ... or if using the .NET CLI to create the Blazor WebAssembly app, make sure that you pass the `-ho|--hosted` option to the `dotnet new blazorwasm` command.

For the Blazor WebAssembly version of this article, your solution should have three folders in it: `Server`, `Client`, and `Shared`.

I'm going to close this because I think you'll get it straightened out fairly fast. Please feel free to leave a follow-up message on this issue if you're still having trouble.
