### ISSUE TITLE
Changes Role Example to Uppercase

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/AspNetCore.Docs#27886]
This:

`<AuthorizeView Roles="admin, superuser">`

Should be:

`<AuthorizeView Roles="Admin, Superuser">`

because roles ARE case sensitive.  Unless you create a role in the aspnetroles table with a lowercase "admin" the above code is not going to work. (Which I think is not the typical case).

Also, if you look at the example [here](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-7.0), they are all uppercase. So I would recommend consistence and make them all uppercase.

I ran into this trying to get roles to work, and it took me a while to figure out the issue was the case on the roles.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f75d9405-19a5-a14b-3a09-a3605b240750
* Version Independent ID: 1247ee64-fbc9-ce29-0710-f6e59380f5ee
* Content: [ASP.NET Core Blazor authentication and authorization](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @gregoryagu ... 

> Which I think is not the typical case

I can't make such an assumption for sure tho. The casing of the app role values are up to the developer. For example, the app roles values in Azure can be all lowercase and end up in the app that way. I'll add remarks to this topic on it, and I'll also call it out over the WASM Groups and Roles topic at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-7.0#app-roles

These scenarios were tested with Azure under the conditions of lowercase role values, and I thought that the work with IdS also used (or I made it use) lowercase role values. Anyway ... no matter ... I ***DO*** agree that this point ***should be clarified***.

I'm performing a big node-wide set of updates to the *Security* node on https://github.com/dotnet/AspNetCore.Docs/issues/24615, but this doesn't need to wait. It's a quick fix. I'll try to knock this out tomorrow (Monday) morning.

Thanks for the heads-up on this. I'll ping u on the PR when it goes up.

**Comment by guardrex** [comment]
I did further investigation on this. I agree with you. I think the examples should be cased after looking across MS and external doc sets. Fortunately, that is the way that I was treating policy names (cased), so those are fine. IIRC, I did that because they present well relative to the Azure portal AAD built-in role names. However, Azure uses template IDs for built-in AAD role claim checks ... if I remember correctly 🤔. Anyway, I'm going to add some remarks about casing generally with the Pascal casing updates to the examples.

I see ***several*** things that I need to do in the areas of roles, claims, and policies, but I am going to knock this one out right now 🥊😵. I pick back up with other improvements when I reach the *AAD Groups and Roles* topic and the *Overview* topics in due course later.
