### ISSUE TITLE
OnInitialized called after or at the same time as containing components's OnInitialized 

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#27894]
Hi,
I would like to know/clarify, how is it supposed to work.

If 1 component contains other child components (e.g. Page has a ListComp), and they all have code in `OnInitialized/Async`,
Which of the method(s) will execute first ?
Should I expect that `OnInitialized` on the child components has started before the `OnInitialized` on the parent starts to execute ? 

(I was assuming that the children will start and finish before the parent starts and having some issues now because of that)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Razor component lifecycle](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @omuleanu ... I agree that we should address this subject in the topic. I think the best way to capture the right guidance for this issue is to have @SteveSandersonMS address it with a few remarks that I can place into the topic. In addition to this ping here, I'll try to email him, too. *Stand-by* ............

**Comment by guardrex** [comment]
Keep in mind that the order of calling the methods is different from when they complete for a discussion on this subject.

Init ***CALLS*** should go ***parent first, then child***.

If synchronous, I think the parent init is guaranteed to complete first. If async, it can't be determined which will complete first, as it depends on the code running.

Yeah tho ... we need Steve to say if that's correct and provide additional information before I can place guidance on this.

**Comment by omuleanu** [comment]
@guardrex I was assuming the other way around, so if you have a page with 3 buttons, first the buttons will start to initialize and after the page

**Comment by guardrex** [comment]
**UPDATE**: I think Steve is OOF at this point ... as I will be very soon 😄 for the ⛄ holiday season, so we'll need to wait and address this in early '23.

**Comment by SteveSandersonMS** [comment]
> Yeah tho ... we need Steve to say if that's correct and provide additional information before I can place guidance on this.

Yes you are correct. It's inevitable that it has to be this order:

 * Parent's OnInitialized/Async starts
 * Parent renders, which determines which children exist
 * Child's OnInitialized/Async starts
 * Child renders
 * etc. with grandchildren

It's clear that the parent has to render before its children, because rendering is what determines which children are present (especially if, for example, you have `@if`/`else` in your rendering logic).

**Comment by guardrex** [comment]
Thanks @SteveSandersonMS.

@omuleanu ... I'll need to dig out from a few things before I can reach this issue. I'm still working on the Blazor *Security* node and other issues. I'll get back to this issue *ASAP* 🏃😅 ... hopefully in a few weeks.
