### ISSUE TITLE
Integration with Circuit Breaker

### ISSUE THREAD

**Issue by torumakabe** [dotnet/AspNetCore.Docs#27930]
Are there any guidelines or recommendations regarding integration with Circuit Breaker?

For example, the number of database connections reaches a limit and new connections repeatedly succeed and fail. Even though the service is unstable, the health checks sometimes return successes, causing the load balancer to send traffic to the unstable instance. Therefore, I would like to integrate circuit breaker to make the health check fail until it stabilizes.

In [an article written four years ago](https://devblogs.microsoft.com/dotnet/asp-net-core-2-2-0-preview1-healthcheck/), it is stated as follows, but I cannot find what has happened since then.

> We’re working with the authors of Polly to try and integrate health checks for Polly’s circuit breakers.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-7.0)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 63344](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63344)

**Comment by Rick-Anderson** [comment]
@JuergenGutsch @glennc

**Comment by torumakabe** [comment]
@Rick-Anderson Thanks. If I should not combine circuit breakers with health checks in ASP.NET Core, please tell me so.

Indeed, as in the example I mentioned, excluding instances with failed health checks from the load balancer from the traffic forwarding destination could affect all instances in the event of a dependent service failure. Under some conditions, circuit breakers may be best used exclusively in the data plane, not in health checks.

If this is not recommended, developers would be happy to see a reason in the documentation.

**Comment by JuergenGutsch** [comment]
@torumakabe I'm so sorry, I missed that mention completely :-(

I'm sure there is no recommendation not to implement circuit breakers in health checks. 

You are right, some kind of resilience and transient-fault-handling should be installed every time you connect to a resource that might not accessible. On the other hand, this implementation is completely decoupled from health checks.  This means, there is no reason not to implement circuit breakers.

To try to use Polly’s circuit breakers makes absolute sense. The only difficulty is registering an instance CircuitBreakerPolicy as a singleton within the application that hosts the health checks because the checks are executed on demand or periodically and the state of the circuit breakers needs to be tracked over multiple scopes. See: https://github.com/App-vNext/Polly/wiki/Circuit-Breaker

@Rick-Anderson I'm not sure if this topic needs a section in the docs because it is really specific and the sample will be more complex than the usual topics. If you like to have a doc about it, I would be happy to create one or at least I write a blog post and you add a link to it instead of the comment mentioned above.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson I'm not sure if this topic needs a section in the docs because it is really specific and the sample will be more complex than the usual topics. If you like to have a doc about it, I would be happy to create one or at least I write a blog post and you add a link to it instead of the comment mentioned above.

@JuergenGutsch  Thanks, I think this issue is all we need for now.

**Comment by torumakabe** [comment]
@JuergenGutsch @Rick-Anderson Thanks!
