### ISSUE TITLE
Consider mentioning how to display the number of attempts for re-connection

### ISSUE THREAD

**Issue by VorTechS** [dotnet/AspNetCore.Docs#27949]
[Enter feedback here]

The documentation shows how to implement a Custom UI, but does not mention elements that might be useful.

For example, implementing my own Custom UI I still wanted to show how many connection attempts had been made, but the documentation doesn't show how this can be achieved.

There should be mention that you can add an element with the appropriate Id in order to achieve this, for example:

`<span id="components-reconnect-current-attempt">Number of Attempts appears here...</span>`

Similarly there's no mention of: components-reconnect-max-retries

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0969556b-b77e-bdb8-8e20-fd6971be0c25
* Version Independent ID: d17e4c28-ea82-0dd8-295d-19f6ada147ea
* Content: [ASP.NET Core Blazor SignalR guidance](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-3.1#reflect-the-connection-state-in-the-ui)
* Content Source: [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @VorTechS ... Yes, this makes good sense to do. It's not here merely because I took what was posted publicly on release and placed that into the topic. The rest of them are here ...

https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Platform/Circuits/UserSpecifiedDisplay.ts

I'll reach this in 23Q1. We're all kind'a out now for the holidays ⛄❄️, and the little bit of time I have left this year is dedicated to Blazor security topic updates. I'll get back to this as soon as I can. Thanks for the issue! 🍻
