### ISSUE TITLE
What are the downsides for Blazor?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/AspNetCore.Docs#27981]
There arent any listed, but there are for other sections.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21671480-fba7-3692-1a20-e71843864b60
* Version Independent ID: 68d5aab0-63ce-de7a-0c56-341c2eef623d
* Content: [Choose an ASP.NET Core UI](https://learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-7.0)
* Content Source: [aspnetcore/tutorials/choose-web-ui.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/choose-web-ui.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by guardrex** [comment]
Hi @StingyJack ... Primarily, they're the same for the lists here for server- and client-rendered UI in the early sections of the topic. The two drawback lists apply: Blazor Server in the server-rendering case, Blazor WebAssembly in the client-rendering case. However, two aspects are worth a look ...

* It's been a while ... several years ... since we put this content up. It's time for a quick review of it as it pertains to Blazor apps.
* I do see one thing here that I'd like to fix. Blazor is in the "client" area, but Blazor Server is server-rendered. I think we should have *Blazor WebAssembly* under client-rendered and *Blazor Server* under server-rendered.

I have some time to take a look tomorrow (Thursday) morning, so I think I'll be able to touch this coverage up then. I'll ping u on the PR when it goes up. Leave this issue open, as it will close automatically when the PR merges later. Thanks for the issue and *Happy Holidays!* 🍾🎆
