### ISSUE TITLE
How to enable Cors for Blazor WebAssembly app created by VS2022, the project does not have app (app.UseCors)

### ISSUE THREAD

**Issue by LimingRenPA** [dotnet/AspNetCore.Docs#28004]
For example,  how do we do 

`app.UseCors(MyAllowSpecificOrigins);`

 in a VS2022 WebAssembly app. It does not have Startup.cs and app.

![image](https://user-images.githubusercontent.com/74560586/210457756-fdb0b01f-5037-4946-b77b-95f599e1a01b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @LimingRenPA ... CORS is enabled for server-based web APIs, not for a client-side Blazor WebAssembly app. You can control the request aspects for the `HttpClient` of the Blazor WebAssembly app per the guidance at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-7.0&pivots=webassembly#httpclient-and-httprequestmessage-with-fetch-api-request-options

... but the server app has to issue the correct headers to make CORS work. That's where the `UseCors` call is made.

Our CORS section that addresses the server CORS requirements in the Blazor docs is at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-7.0&pivots=webassembly#cross-origin-resource-sharing-cors

... which points out that in the default case a ***hosted Blazor WebAssembly app's*** **Server** project doesn't need special config because the client and server are on the same origin. If they differ in origin, then yes ... the **Server** project requires CORS config to permit its **Client** app on a different origin to make requests to it (or any other client for that matter).
