### ISSUE TITLE
Crosslink Blazor state mgmt article

### ISSUE THREAD

**Issue by baktay** [dotnet/AspNetCore.Docs#28093]
No matter what I tried to register Isession  to Blazor Server .Net7 -  according to this page I got this error on 
There is no registered service of type 'Microsoft.AspNetCore.Http.ISession'.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @baktay ... You won't be able to use traditional session state with Blazor because SignalR doesn't have a stable HTTP context. We have a state management article that explains ways in which you can store state in Blazor Server apps ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/state-management
