### ISSUE TITLE
Well Done 😊 nice to have a tutorial work first time right 

### ISSUE THREAD

**Issue by akenel** [dotnet/AspNetCore.Docs#28120]
Good job, you should extend the tutorial to further customize and add feature - juice it up with 12 more steps and options.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Great to hear the feedback! Thanks go to @bradygaster.  Extending this might work as a next step, separate tutorial since the original is designed for quickly moving on getting one going in the time folks usually dedicate for checking something new out.

Next steps would be the collection of docs here:
[Samples](https://github.com/aspnet/SignalR-samples)
[Hubs](https://learn.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-7.0)
[SignalR client features](https://learn.microsoft.com/en-us/aspnet/core/signalr/client-features?view=aspnetcore-7.0)
[Host and scale](https://learn.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-7.0)
[SignalR with Blazor WebAssembly](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0)

There are some great videos where Brady Gaster covers some advanced concepts:
https://www.youtube.com/watch?v=wZnHMa0V0kg

**Comment by wadepickett** [comment]
Great to hear the feedback! Thanks go to @bradygaster.  Extending this might work as a next step, separate tutorial since the original is designed for quickly moving on getting one going in the time folks usually dedicate for checking something new out.

Next steps would be the collection of docs here:
[Samples](https://github.com/aspnet/SignalR-samples)
[Hubs](https://learn.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-7.0)
[SignalR client features](https://learn.microsoft.com/en-us/aspnet/core/signalr/client-features?view=aspnetcore-7.0)
[Host and scale](https://learn.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-7.0)
[SignalR with Blazor WebAssembly](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0)

There are some great videos where Brady Gaster covers some advanced concepts:
https://www.youtube.com/watch?v=wZnHMa0V0kg

(Closing the open issue for this specific doc.)
