### ISSUE TITLE
POST Form Data

### ISSUE THREAD

**Issue by skwzrd** [dotnet/AspNetCore.Docs#28144]
It would be good to see how to POST form data to the server - the code for the client and server (Blazor WASM). I haven't been able to find a simple demonstration of this yet. This comes close https://stackoverflow.com/a/58546525/9576988

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3128506-d228-35ca-e34a-183a881acdec
* Version Independent ID: c3128506-d228-35ca-e34a-183a881acdec
* Content: [ASP.NET Core Blazor forms and input components](https://learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms-and-input-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @skwzrd ... It's covered by the Blazor web API article ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-7.0&pivots=webassembly

It's based on the ToDo List tutorial at ...

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-7.0&tabs=visual-studio

... but be warned that the tutorial has undergone some changes over time. I have a work item to check the Blazor web API guidance against the tutorial to make sure that churn hasn't broken any of the examples. If any of them have broken over time, I'll either fix them ***OR*** create a standalone, dedicated server-based web API for the Blazor web API topic so that the Blazor topic doesn't rely upon the guidance in the ASP.NET Core web API topic for its examples. Still tho ... the examples will show how to perform CRUD ops against a web API in general even if some of them are broken.
