### ISSUE TITLE
Deployment details to IIS are missing

### ISSUE THREAD

**Issue by GerardFR** [dotnet/AspNetCore.Docs#28189]
This page gives many details on how to deploy an app to Azure, but it doesn't explain how to publish to an IIS server.
It would be great to add a section on that topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the request, @GerardFR. True, devs at this time would piece it together from IIS and Windows cert management docs. It should be a bit easier to work out than the Azure case, which is why we've only been carrying Azure coverage. Devs were particularly tripped up by the exact Azure config to make it work.

@mkArtakMSFT ... This is a reasonable request. Devs unfamiliar with configuring the custom domain with the certificate for Identity Server's token signing key would benefit from a 🦖 *Rex Mini-tutorial*&trade; 🦖. It would speed up the dev experience considerbly over piecing it together from other docs. Shall I proceed to get this scheduled?

**Comment by guardrex** [comment]
I'll go ahead and schedule this. I think it's a good idea. Docs for this exist indirectly in two other doc sets, but I can whip up a section that will make it quick and easy for readers to implement.
