### ISSUE TITLE
MongoDB.Driver.Core  - Myabe update instriuctions to use this nuget package now?

### ISSUE THREAD

**Issue by plppp2001** [dotnet/AspNetCore.Docs#28372]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 63808](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63808)

**Comment by wadepickett** [comment]
Thanks for the heads up @plppp2001.  Very appreciated.  Added to list to update.

**Comment by plppp2001** [comment]
Hey,

Actually I needed both Nuget packages. Never mind…..


PaulAstramowicz.com

**Comment by wadepickett** [comment]
OK, I will verify and review the topic for any needed updates.

**Comment by wadepickett** [comment]
The MongoDB .NET Driver is built on MongoDB.Driver.Core.   MondgoDB .NET Driver provides a high-level API for the low-level and verbose MongoDB.Driver.Core.   That said, MongoDB and its shell mongosh are different enough now since this tutorial was last updated, that the tutorial instructions do not actually work entirely.  So I am making some corrections so that the .NET 6.0 version works for this tutorial, and in a separate issue I will update the tutorial to .NET 7 and 8.
