### ISSUE TITLE
A kestrel configuration section for ASP Net Hosted Blazor either in this doc or in the kestrel doc would be very helpful

### ISSUE THREAD

**Issue by ScottPeabody** [dotnet/AspNetCore.Docs#28382]
I struggled to figure out how to set up kestrel for my blazor app and there was not a lot of specifics on the syntax for it causing me to need to deep dive into docs and external forum resources to figure out how to configure it. 

A potential feature that would be nice would be to have the option to choose either IIS or Ketral when creating the templates that have hosted servers. I eventually got it working but I am not exactly sure why it works and any changes I want to make are fragile and prevents me from making updates confidently.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e07aaa4d-4ad4-778f-f74a-60d8f05d9075
* Version Independent ID: c82cf121-831d-75dd-a796-c735aad3b3e9
* Content: [Host and deploy ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ScottPeabody ...

>  set up kestrel for my blazor app

That's the by-default config for a hosted Blazor WebAssembly app, and all of the normal Kestrel config shown in the Kestrel doc apply, so I'm not sure what specifically you're asking about that wasn't working that pertains to Blazor. You would need to be more specific. If the config was only related to your custom hybrid Kestrel-IIS setup, we probably won't be covering it at this time. I will ask management tho to take a look at this issue to confirm my suspicion.

> deep dive into docs and external forum resources

You did the right thing, especially if by "deep dive into the docs" you meant accessing the Kestrel resources in the ASP.NET Core doc set. Blazor docs are an ***add-on*** doc set to the ASP.NET Core docs, especially in the area of hosting fundamentals. We only try to call out the most common developer use cases and ***gotchas*** 😈 for hosting in the Blazor *Host and deploy* node. Uncommon and advanced scenarios do require the dev to research and implement their custom solutions on their own with community support (forums, chats, etc.).

WRT ...

> have the option to choose either IIS or Ketral when creating the templates that have hosted servers

That's a framework feature request. You'd have to open that suggestion for them on their repo at ...

https://github.com/dotnet/aspnetcore/issues

**Comment by ScottPeabody** [comment]
I appreciate the quick feedback! We are not using iis at all and use kestrel on linux, so not a hybrid solution. I was just not sure how I was supposed to configure both the the launchSettings.json files on the client and server side with https redirect and how they interact if at all with the program.cs file since there is also the config for kestral that is put in place there as well. I will keep reading the docs on kestrel and blazor to get this precise and understood on my end here.

I will definitely put in the framework feature request, my apologies for being out of scope with that suggestion in the docs issues.

**Comment by guardrex** [comment]
>  I was just not sure how I was supposed to configure both the the launchSettings.json files on the client and server side

Ah, I see. Yes, I think since the project template provides both files, one in the **Client** project and one in the **Server** project, that it is worth calling out where the docs address running the app from the **Server** project of the hosted solution that ***it's the Server app's `launchSettings.json` file at play*** for `dotnet run` and VS debugger runs. That's a good point to add to that content. If you never intend to run the client app directly, you can trash the file in the **Client** project. It would never be used.

Otherwise WRT general hosting guidance, it's the same config for any ASP.NET Core web app, which is covered in more detail over in the main doc set's [*Host and deploy* topic on Linux](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx). You would have some extra work if the [app base path requires configuration](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-7.0&tabs=visual-studio#app-base-path) on the Blazor side to get paths in Blazor routing and URL generation/navigation to work properly, but that's only if you need to configure it. When the app is hosted at a root app base path (`/`) no special config is required.  This is per the remarks that I just reviewed at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0#hosted-deployment-on-linux-nginx

Leave this issue open, as it will close automatically when the PR merges.
