### ISSUE TITLE
Can this be done with a single registered app?

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/AspNetCore.Docs#28384]
I want to create an ASP.NET hosted Blazor WASM app. The ASP.NET app will serve the WASM content for the browser and also service API calls from it.

I see this as fundamentally one app. Is there a way to do this by only registering one Registered App on Azure AD B2C?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory B2C](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-7.0#create-the-app)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yeah ... let me reinforce that last point. You may see things like slight changes in wording between the Azure portal UI and the topic or between what VS shows and the topic. Don't sweat those sorts of things. I'll have all of that stuff updated when I reach this. Overall tho, I expect the process here to work as described.

**Comment by mrpmorris** [comment]
@guardrex I've worked out some steps for authenticating against a multitenant AAD, and it only uses one Registered Application.

https://peterlesliemorris.com/azure-active-directory-multitenant-integration-with-blazor-wasm-part-1/
https://peterlesliemorris.com/azure-active-directory-multitenant-integration-with-blazor-wasm-part-2/

- If there is anything you can take from it, feel free to copy anything you like.
- If you spot anything wrong, please let me know.
- And if you can tell what I have to change to have the scopes included in the token, I'd appreciate it very much!

**Comment by guardrex** [comment]
Thanks @mrpmorris ... I'll leave the email ping for your comment in my email Inbox so I don't lose it. I'll try to look at it sometime next week.

**Comment by guardrex** [comment]
@mrpmorris ... I took a *quick* 🏃‍♂️ look.

That's all good, but there's nothing wrong (*YET* 😄) with the current coverage. I'm not sure yet because I've been working in the Blazor Server security node recently. I'm only just now getting into the weeds in the Blazor WASM security node. I'll be working through all of the node over the next week or two making updates and fixing any problems that I find.

We're not going to cover the use of VS because many devs aren't using the IDE, especially outside of Windows/MS devs. We wanted (and still want) the lowest common denominator, which is the use of the .NET CLI.

I'm not sure what you mean about "scopes included in the token," as ***they are*** 👍. If you decode the access (bearer) token for requests to the server API, you should see them in the "scp" (i.e., scopes) entry of the token. For example, the scope for the documentation examples shows up as `"scp": "API.Access"` (i.e., the scope is "`API.Access`" for the example).

Anyway ... getting back to your original post ...

> I see this as fundamentally one app. 

I was reminded by the section in the topics that speaks to that point that we don't recommend using a single registration for both projects/apps of a hosted solution. You can do that, of course, we just don't recommend it. The coverage is at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/?view=aspnetcore-7.0#use-one-identity-provider-app-registration-per-app

WRT your blog, you could see about getting it listed at [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor) (Community-maintained collection of Blazor resources), since we can't cross-link dev blogs in the documentation. We refer readers to Awesome Blazor.

WRT covering multitenant, we can't cover every permutation of hosting generally ... or even for Azure. These aren't the "Azure docs" really, they're the Blazor docs. That's a separate doc set written by a different group of doc authors and managed by a different group of doc managers. We provide these reference/tutorial materials via the ASP.NET Core product unit (the group that I belong to) to help devs get started because we feel that the Azure docs don't cover everything that we'd like to show in the way that we we'd like to show it. These are just starting points, not meant to be comprehensive coverage. We refer readers to the Azure docs for more information on other use cases, which is where the multitenant Azure scenarios are covered.

**Comment by mrpmorris** [comment]
I worked out the problem with scopes. 

If I recall correctly, it only wouldn't send scopes if I set my Application ID URI to something that was not a guid in "Expose an API" on portal.azure.com. Whenever I set the URI to something like "myapp-dev-guid" I wouldn't get scopes, whereas just "guid" would work.

**Comment by guardrex** [comment]
Your examples don't indicate a scheme. Hyphens are unreserved characters; so in theory, they should be permitted. I've been wondering if any nonsensical scheme would work, and I might test one ... like ... 🤔 ***`rex://...`*** 🦖😜

**Comment by mrpmorris** [comment]
It certainly accepts anything after the // but IME seems not to return the scopes :)

Is there a section somewhere explaining *why* MS recommend having a separate app for the client?

**Comment by guardrex** [comment]
> why MS recommend having a separate app for the client?

Yes, I think that they've moved that content around over time. Right now, I see it at ...

> Don't use the same application registration for multiple applications.

https://learn.microsoft.com/en-us/azure/active-directory/develop/zero-trust-for-developers#assume-breach

... but I think they say that in a few spots. I'm not going to try and search further tho due to time constraints.

**Comment by guardrex** [comment]
They're fundamentally *TWO* apps. The host ASP.NET Core app (server API) might need access to all kinds of things that the client registration shouldn't have. We recommend this in cases where 3rd party API is going to be used ... client hits the host app ... the host app calls out to the 3rd party API.

**Comment by mrpmorris** [comment]
Thanks!
