### ISSUE TITLE
Part 2, add a model - unhandled exception

### ISSUE THREAD

**Issue by BraPil** [dotnet/AspNetCore.Docs#28449]
Getting this error. I have done the tutorial a few times and keep getting it. The migration does not appear to be the issue and I cannot find a 'UseSqlServer' call

_________________________

An unhandled exception occurred while processing the request.

SqlException: Cannot open database "RazorPagesMovieContext-29719c11-9703-491e-8622-5977620ecd2a" requested by the login. The login failed.
Login failed for user 'DESKTOP-QJ1SJMV\brand'.
Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)

InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure' to the 'UseSqlServer' call.
Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync<TState, TResult>(TState state, Func<DbContext, TState, CancellationToken, Task<TResult>> operation, Func<DbContext, TState, CancellationToken, Task<ExecutionResult<TResult>>> verifySucceeded, CancellationToken cancellationToken)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Hi @BraPil.  I'm not sure what has gone wrong here exactly.  I do know we just tested out this tutorial series.

The first thing I would check is to see if you currently have a database named "RazorPagesMovieContext-29719c11-9703-491e-8622-5977620ecd2a" that was successfully created.

It is also easy to get a mismatch of package versions or an outdated global tool that can start to mess things up as you go.

Some possibilities to check:

Verify what is currently installed in the project for the complete list of packages, that they are the latest, and not mismatched between versions. 

Run the following in command line at your project directory, specifying your project name to see a list:
```text
dotnet list YourProjectNameHere.csproj package --verbosity d
```

Get a list of outdated packages:
```text
dotnet list package --outdated
```

Verify the related tools are not out of date and/or mismatched versions. The global tools used here do not automatically update if you install but had an existing older one.  You must uninstall them first.

Verify what versions of tools you have:
```text
dotnet tool list -g
```
Uninstall and reinstall the latest version of the related tools:
```text
dotnet tool uninstall dotnet-ef --global
dotnet tool install --global dotnet-ef
dotnet tool uninstall dotnet-aspnet-codegenerator --global
dotnet tool install --global  dotnet-aspnet-codegenerator
```

It is possible you might need to start over with a new project in the tutorial since we don't know what state it is in but try what I suggested above first.

I will close this for now, unless you are able to get more information that might point to a change needed in the doc. In which case feel free to reopen.
