### ISSUE TITLE
JavaScript Colocation for Razor Pages

### ISSUE THREAD

**Issue by lonix1** [dotnet/AspNetCore.Docs#28456]
There's extensive documentation for JavaScript Colocation in Blazor. But not in Razor Pages.

Apparently it's possible, see [here](https://github.com/dotnet/aspnetcore/issues/26145#issuecomment-889813856) and [here](https://github.com/dotnet/sdk/pull/19270#issue-952896832).

For the life of me, I can't figure out how to get it to work. And there's nothing on StackOverflow.

Please consider exposing this functionality, because right now most people don't even know it exists! :smile: 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio-code#css-isolation-configuration)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 65410](https://dev.azure.com/msft-skilling/Content/_workitems/edit/65410)

**Comment by guardrex** [comment]
I think you're right, @lonix1 ... I made an INCLUDE file for it that covers pages and views, along with Blazor that was used for my purposes in the Blazor node. I think I thought it would get picked up and placed into one or more topics in the main doc set. There might be an existing issue to do it that is floating around the repo issues here.

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/includes/js-collocation.md

@Rick-Anderson ... I placed that out in the main doc set `includes` folder for general use. If you come up with a different version, let m know 👂... if so, I'll move that to my `includes` folder in the Blazor node and strip out the "pages and views" parts (probably). Otherwise tho, it can be modified, and I'll keep using whatever you decide to go with in the Blazor node from that file.
