### ISSUE TITLE
does not declare @inject ILogger<FileUpload1>

### ISSUE THREAD

**Issue by jorgearana** [dotnet/AspNetCore.Docs#28452]
The examples in this page does not work because, VS does not recognize @inject ILogger<FileUpload1>.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-7.0&pivots=webassembly)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jorgearana ... It sounds like you didn't name the component `FileUpload1.razor`. The name "`FileUpload1`" is the classname of the component. Change that to whatever you named it. For example, it you named it `MyFileUploader.razor`, then make that line `@inject ILogger<MyFileUploader> Logger`.

This aspect of Blazor is covered at https://learn.microsoft.com/aspnet/core/blazor/components/#markup, and namespaces for components are covered at https://learn.microsoft.com/aspnet/core/blazor/components/#namespaces.

**Comment by guardrex** [comment]
... and FYI ...

When I pulled up those cross-links, I think a smidgen of work on the content layout is in order. I think the classname remarks perhaps should be rolled into the *Namespace* section remarks with a section heading name change to *Class name and namespace*. It feels a little out of place where I currently have it in the *Markup* section. I have a work item coming up to split some sections of out the *Components* overview topic because it's getting too long. I added a note on this to that work item, and I'll address it in the topic with those updates coming in about a month or so.
