### ISSUE TITLE
Compilation error in code sample

### ISSUE THREAD

**Issue by hakondale** [dotnet/AspNetCore.Docs#28529]
In the code sample for NavigationLock, in the OnBeforeInternalNavigation method, the isConfirmed variable gets an error in VS 2022 (v17.5.0):

`An object reference is required for the non-static field, method, or property 'JSRuntime.InvokeAsync<bool>(string, object?[]?)'`

It is complaining about the second argument with the confirmation message.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing and navigation](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hakondale ... thanks for the report ... and sorry for the delay getting back to you today. I was on the road all day in a UHAUL 🚚  moving across the state of Florida. 😄  Anyway ..... 

Let me research this a bit further after I get some sleep 🛌 💤. I'll get back to you in the morning. If I can reproduce the behavior, then I'll have you open a product unit issue for it. If I can't reproduce it, then I'll ping the product unit engineer who helped me with the content of this section. Stand-by ...... I'll get back to you soon! 🏃

**Comment by guardrex** [comment]
Ok ... back. Sorry again for the delay. Moving across the state is a pain! 😄 

I can't see a problem here with compilation or running that example ...

<img width="921" alt="Screen Shot 2023-03-02 at 12 11 54 PM" src="https://user-images.githubusercontent.com/1622880/222502242-93ce4f6d-9626-41b3-a2c3-c8bee33630c3.png">

Open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/28529
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.
