### ISSUE TITLE
Nested AuthorizeView doesn't work as in the example.

### ISSUE THREAD

**Issue by carlsixsmith** [dotnet/AspNetCore.Docs#28530]
If you create a nested AuthorizeView as in the example, it doesn't compile.

`
<AuthorizeView Roles="Admin">
    <AuthorizeView Roles="Superuser">
        <p>You have both 'Admin' or 'Superuser' role claims.</p>
    </AuthorizeView>
</AuthorizeView>
`

This will give you a compilation error.

**_The child content element 'Authorized' of component 'AuthorizeView' uses the same parameter name ('context') as enclosing child content element 'ChildContent' of component 'AuthorizeView'. Specify the parameter name like: '<Authorized Context="another_name"> to resolve the ambiguity_**	

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f75d9405-19a5-a14b-3a09-a3605b240750
* Version Independent ID: 1247ee64-fbc9-ce29-0710-f6e59380f5ee
* Content: [ASP.NET Core Blazor authentication and authorization](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the report, @carlsixsmith ... and sorry for the delay today getting back to you. I was on the highway in a UHAUL 🚚  most of the day moving across the state of Florida 😄. Anyway ...

IIRC, it ***used to*** work ... perhaps a few versions ago. I thought that I tested it when the guidance was first placed, back in the 3.1 (or 5.0) era.

Let me research this a bit further tomorrow (Thursday) morning ... *actually it's 1:45am Thursday where I am!* 🙈 ... I'll get back to you after I some sleep 🛌 💤.

**Comment by guardrex** [comment]
Ok ... I'm sorry again for the delay. I'm normally *much FASTER*. Moving across the state is a giant ***PAIN POINT!*** 😆 

So, I see what you mean now. IIRC, I tested every scenario when this was written, but perhaps I didn't test this one. I do see the error message and the suggestion to set the `Context` to resolve it ...

```razor
<AuthorizeView Roles="Admin">
    <AuthorizeView Roles="Superuser" Context="SecondCheck">
        <p>You have both 'Admin' or 'Superuser' role claims.</p>
    </AuthorizeView>
</AuthorizeView>
```

I'd like to take a closer look at adding that `Context` parameter.

Were you able to use that approach or list the roles together in the `Roles` argument? If you're having trouble due to this, then I'd like to ping the product unit for assistance. Otherwise if you're ok at the moment, I'd like to research this a bit further this weekend. I should be fully ... well ***mostly*** 😄 ... moved into my new house and have some time to dig into this further.

Don't close this issue either way. You are correct ... today ... at least in this version of the framework ... we have a doc bug 🪲 here that I need to address in the doc. I'll use this issue to track that work, and this issue will close later automatically.

Thanks again for the shout-out on this!

**Comment by guardrex** [comment]
**Note to Self** 🦖: The `Context` attribute is covered in the templated components doc ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-7.0

**Comment by guardrex** [comment]
It seems that the context can get a claims principal for the user inside both `AuthorizeView` components. For example ...

```razor
<AuthorizeView Roles="Admin">
    <p>@context.User</p>
    <AuthorizeView Roles="Superuser" Context="innerContext">
        <p>@innerContext.User</p>
        <p>You have both 'Admin' or 'Superuser' role claims.</p>
    </AuthorizeView>
</AuthorizeView>
```

* `@context.User` for the outer one.
* `@innerContext.User` per the `Context` param/attribute `innerContext` argument.

No conflict on the context that way. I'll get this written into the doc this weekend.

**Comment by guardrex** [comment]
No, I think it's going to be required. It's true for the render fragment ... the `context` really is a collission in this format of the nested components. That example that I just put up seems good tho. What I'll do is ping Mackinnon on the PR. I should have that up shortly. I'm working forward to this issue right now through stuff that piled up this week while I was moving across the state of Florida.

**Comment by guardrex** [comment]
I'm going to work this right now 🏃 ... I don't think it will take very long. I'll ping you on the PR shortly. *Stand-by .........*
