### ISSUE TITLE
Published feature which not working

### ISSUE THREAD

**Issue by scatman255** [dotnet/AspNetCore.Docs#28571]
You publish features that have not been going for months.
You read the documentation and are happy that you can use it, only to spend hours to find out that it doesn't work at all.
bind:get / bind :set
No info, no workaround.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @scatman255 ... Those features should work for 7.0. Open an issue for the product unit on their GitHub repo. Explain out with your code example what's not working, and they probably need you to put up a minimal project on GitHub that demonstrates the problem that you're having.

If you are using Visual Studio, there's a known problem in the UI described at https://github.com/dotnet/aspnetcore/issues/44957, but that should ***only apply to*** `@bind:after`, not `get`/`set` for `@bind`.

Here's their repo issues where you can open a support request with them ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/28571
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.

**Comment by FLAMESpl** [comment]
I confirm that with 7.0.200 SDK @bind:set does not work
