### ISSUE TITLE
scaffolding tool is not working.

### ISSUE THREAD

**Issue by rohithmp2000** [dotnet/AspNetCore.Docs#28584]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-7.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by rohithmp2000** [comment]
no data file or controller are made with scaffolding tool command.

**Comment by wadepickett** [comment]
@rohithmp2000, thanks for taking the time to let us know.    Could you provide more detail on what is happening?

This is a point in the doc where if there is a mismatch of tool or package versions that it is possible for the scaffolding to not be created.

Some possibilities to check:

Verify what is currently installed in the project for the complete list of packages, that they are the latest, and not mismatched between versions:

Run the following in command line at your project directory, specifying your project name to see a list:
```text
dotnet list YourProjectNameHere.csproj package --verbosity d
```

Get a list of outdated packages for your project, again, running this at the directory location of your project:
```text
dotnet list package --outdated
```

Verify the related tools are not out of date and/or mismatched versions. The global tools used here do not automatically update if you install but had an existing older one.  You must uninstall them first.

Verify what versions of tools you have:
```text
dotnet tool list -g
```
Uninstall and reinstall the latest version of the related tools:
```text
dotnet tool uninstall dotnet-ef --global
dotnet tool install --global dotnet-ef
dotnet tool uninstall dotnet-aspnet-codegenerator --global
dotnet tool install --global  dotnet-aspnet-codegenerator
```

Another possibility is that when running the commands to install packages at the command line, if you paste in a several commands to install at once and hit return, you can still need to hit return one more time for the very last line to run, otherwise you are missing that last package. It is easy to miss.

It is possible you might need to start over with a new project in the tutorial since we don't know what state it is in but try what I suggested above first.

I will close this for now, unless you are able to get more information that might point to a change needed in the doc. In which case feel free to reopen.
