### ISSUE TITLE
Troubleshooting gRPC: HTTP/3 support can be enabled but not default v6-7

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28597]
What about .NET 7?
See https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/#http-3-enabled-by-default

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c730b5f9-031e-beab-b838-6e2f8befde30
* Version Independent ID: 84ddcb67-03be-655c-470a-f43a5152606f
* Content: [Troubleshoot gRPC on .NET Core](https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-7.0)
* Content Source: [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

---
[Associated WorkItem - 69094](https://dev.azure.com/msft-skilling/Content/_workitems/edit/69094)

**Comment by wadepickett** [comment]
This issue is referring to section [Configure gRPC client to use HTTP/3] https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-7.0#configure-grpc-client-to-use-http3

This line of text should have been updated to indicate HTTP/3 support can be enabled for v6-7, and "preview" removed.

"HTTP/3 support is in preview in .NET 6, and needs to be enabled via a configuration flag in the project file."

The eventual 8.0 of the doc needs to indicate this is available by default in 8.0 per the [preview 1 devblogs announcement](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/#http-3-enabled-by-default)

**Comment by wadepickett** [comment]
Related to PR #28876 which updates the statement on HTTP/3 for .NET 8, but not for 6-7.
