### ISSUE TITLE
More examples please

### ISSUE THREAD

**Issue by dunxz** [dotnet/AspNetCore.Docs#28618]
The pages is informative and a highly linked resource from stackoverflow + numerous others, but it does not answer my question.

Q. How do you pass parameters from javascript element to blazor?. In other words can this help article include an example with parameters?

`<button onclick="returnArrayAsync('Example argument')" />`

```
    <script>
        window.returnArrayAsync = (?) => {
            debugger;
            DotNet.invokeMethodAsync({ASSEMBY NAME}, 'ReturnArrayAsync', ??))
                .then(data => {
                    console.log(data);
                });
        };
    </script>

```
```
[JSInvokable]
public static async Task<int[]> ReturnArrayAsync(**object args**)
{
    return await Task.FromResult(new int[] { 1, 2, 3 });
}
```

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2964d558-cd6d-7421-f7b9-cb939792c2cf
* Version Independent ID: a3517e56-69fc-1ec7-b55a-dbb54d68a807
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-5.0#component-instance-method-call)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dunxz ... It's covered further down the doc for ***instance methods*** ...

```javascript
dotNetHelper.invokeMethodAsync('GetHelloMessage', name);
```

```csharp
[JSInvokable]
public string GetHelloMessage(string passedName) => $"Hello, {passedName}!";
```

It's the same principle for static methods. I'll see about adding a static example, but this is going to be a low priority item due to all of the Blazor security updates right now ... ***and*** we have .NET 8 documentation tasks just starting to to hit now. I'll see if I can squeeze it in here sometime soon. This would be good for a Friday task. 😄

**Comment by dunxz** [comment]
Hi @guardrex  - thanks for your swift reply. While the major source of problems are my impatience and dumbness... 
* The examples are confusing as CallDotNetExample2 calls the script sayHello1, CallDotNetExample3 calls the script sayHello2 etc.
* The example under the heading "Create JavaScript object and data references to pass to .NET" (ReceiveWindowObject) seems to imply the method can be called by reference. It seem if it will only work as a static ie 
```
[JSInvokable]
public **static** void ReceiveWindowObject(IJSObjectReference objRef)
{
    ...
}
```

FWIW - i hope I'm helpful (rather than a pedantic #**!wit) but the article is valuable - and it does ask for feedback!

**Comment by guardrex** [comment]
No, that's cool 👍 ... I do want to know where you're having trouble with it.

I'm not too concerned about the numbering just because they're numbered to avoid naming collisions on each side of the interop; ***however***, I'm more concerned about keeping the Razor components numbered than I am the JS FNs. I'll see about renaming those `sayHello` FNs to avoid the numbers.

> seems to imply the method can be called by reference. It seem if it will only work as a static

Yes, I think you're correct about that ... that's a sneaky 😈 *gremlin* in the example. It's in the correct section of the doc under the static approaches, but it's missing the `static` modifier.

I'm going to elevate this one to ***BUG*** 🐞 status and address it tomorrow (Thursday) morning.

**Comment by guardrex** [comment]
> more concerned about keeping the Razor components numbered

The Razor components come from sample apps in [another repo](https://github.com/dotnet/blazor-samples), and the samples need to compile. Since Razor components take their class names from their file names, the apps will 💥 if there are C# naming collisions.

**Comment by dunxz** [comment]
many thanks for help.

> I do want to know where you're having trouble with it.

Actually, I think the final example (call-dotnet-example-one-helper) is clearest. The setup is done as part of the initial page render (which is what I'd expect). In earlier examples, the setup is done as part of the element ` @onclick="...` - for an example that is trying to show how to handle click events from 3rd party JS, on first look, it's a little weird - though I _think_ I get it now.

Many thanks for your efforts, much appreciated.
