### ISSUE TITLE
Need to install Microsoft.EntityFrameworkCore.Tools to scaffold controller and views

### ISSUE THREAD

**Issue by yosuaputra1** [dotnet/AspNetCore.Docs#28637]
I'm following the tutorial here https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model using my Mac.
But when I ran the command to scaffold CRUD operations for the Movie model, I got the following messages in the terminal:

```To scaffold controllers and views using models, install Entity Framework core packages and try again: Microsoft.EntityFrameworkCore.Tools```

So I run this command to add the package:
```dotnet add package Microsoft.EntityFrameworkCore.Tools```

Now the error is gone and I managed to scaffold it.

So maybe this section https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio-code#add-nuget-packages-and-ef-tools needs to be updated to add this package?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by Rick-Anderson** [comment]
@wadepickett  make sure I review any fix to this PR.

**Comment by wadepickett** [comment]
Tested the tutorial on VS Code on Mac.   I cannot replicate the issue, it runs as expected with all tools and packages accounted for.  However, in the step for running the commands to install the required tools and packages, the very last command is for adding Micorosoft.EntityFrameworkCore.Tools. Since it takes some time for the first 8 commands to run, it can be easy to miss hitting return to ensure the very last command runs and Tools is installed, all the rest run as they are pasted in.  I suspect that may be what occurred.
