### ISSUE TITLE
Clarify syntax for specifying component parameter values

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#28694]
I find the language about how to specify component parameters a bit confusing. The section on component parameters currently says: "Assign a C# field, property, or result of a method to a component parameter as an HTML attribute value using [Razor's reserved @ symbol](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-7.0#razor-syntax)." But `@` isn't actually needed. Component parameter attributes are parsed as a C# context (unless the parameter is of type `string`) so a transition isn't typically necessary. Stylistically some people prefer to specify a leading `@` to clarify that the context is C# but doing so is generally optional. The currently language makes it sound like the leading `@` is required when it isn't.

Later the doc says: "The @ prefix is required for string parameters. Otherwise, the framework assumes that a string literal is set." This phrasing seems to contradict itself. Is the leading @ required or not? The answer is it isn't required, but the value of string parameters are treated as string literals by default. If you want a C# context instead you need to lead with an `@`.

The doc recommends leading with an `@` prefix when specifying nonliteral parameters values. This guidance contradicts the default behavior. If we really wanted everyone to specify a leading `@` then we would have made it required.  The C# context is unambiguous from a language perspective and is general evident when reading the code. There is some potential to confuse C# expressions with string literals if you don't know the parameter type, but it's not clear to me that justifies always including the `@`. I think we should remove this guidance and instead clarify that including the leading `@` is optional. Users can then make their own stylistic choice. Stylistic guidance is of course always up for debate, so adding @mkArtakMSFT in case engineering feels strongly about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I think somewhere along the way over the years of edits to this content, this lost the initial "by convention" language that was originally part of the remark. However, the following remark (*emphasis added*) ...

> Outside of string parameters, we recommend the use of the `@` prefix for nonliterals, ***even when they aren't strictly required***.

... remains present. Further down for what the docs will adopt, it states (*emphasis added*) ...

> Nonliterals always use the `@` prefix, ***even when it's optional***.

@SteveSandersonMS signed off on the text and examples at ...

**Add component parameter assignment guidance**
https://github.com/dotnet/AspNetCore.Docs/pull/21555

... without remarking on this specifically. He only said that splitting out field, property, and method cases didn't seem necessary from the framework's perspective at ...

https://github.com/dotnet/AspNetCore.Docs/pull/21555/files#r576368429

... and he provides an example with the `@` prefixes on the component parameter values. It's unrelated to the subject here, but I ended up keeping the example that I had just because I was trying to teach readers about the parameter assignment equivalency among fields, properties, etc.

We didn't discuss the `@` prefix convention on that PR because the discussion took place elsewhere ... an issue, PR, or email chain. I know that it was discussed, and the PU signed off on this convention for doc text and examples. The convention was to adopt the following ...

* Component parameter values always get the `@` prefix.
* Directive attribute values never get the `@` prefix (except for Razor expressions).

Note for updates, that we can update the section quickly 🏃; ***however***, all of Blazor docs and sample code for all versions of Blazor have used this convention from the product's release (IIRC 🤔). Therefore, it will take some time get everything adjusted after the description here is updated to match the new convention.

**Comment by danroth27** [comment]
To be clear, I'm not asking us to change the style we use for specifying component parameters in the docs. We are free to make that stylistic choice and I know various folks on the Blazor engineering team prefer it. I am however suggesting that this shouldn't be recommended guidance for our users. Users should feel free to make the stylistic choice that best suits their needs. 

But before we engage in a stylistic debate, I think it's more important is clarify the supported syntax and behavior. A leading @ is not required for component parameters of any type. It is completely optional for non-string parameters and it is only needed for string parameters if you want a C# context instead of a string literal.
