### ISSUE TITLE
Missing information about Expression-type parameters

### ISSUE THREAD

**Issue by Timores** [dotnet/AspNetCore.Docs#28785]
[EDIT by guardrex to update the metadata]

When @binding-Xxx is used, there is a also a "hidden" parameter, named XxxExpression (of Expression type).
Please document this one also, including the nested component binding. Should the parent set the Expression parameter of the child with its own value?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3128506-d228-35ca-e34a-183a881acdec
* Version Independent ID: c3128506-d228-35ca-e34a-183a881acdec
* Content: [ASP.NET Core Blazor forms and input components](https://learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms-and-input-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Timores ... Sorry for the delay. I'm OOF for a few days and will get back to you by the end of the week.

**Comment by guardrex** [comment]
Hello @Timores ... Sorry for the delay. I'm OOF for a few days and will get back to you by the end of the week.

**Comment by guardrex** [comment]
Hello @Timores ... I'm back.

There's no "`@binding`" directive in Blazor. I also don't know about any "hidden" expression parameter. No such content/guidance ever arrived for me to document. It's probably best if I direct you to open an issue directly for the product unit. Please open a new issue at ...

https://github.com/dotnet/aspnetcore/issues

You'll probably need to give them more information than you stated here. Can you point to what you're talking about in reference source or provide them an example in your new issue? I'm not sure if they will know what you're referring to without additional details.

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/28785
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.

**Comment by Timores** [comment]
OK, it's @bind-Xxx, not @binding-Xxxx, my bad. I am surprised that such a simple error causes one to dismiss a comment.
Guess it's not worth commenting.

**Comment by guardrex** [comment]
I didn't close the issue on that basis. I literally have no personal knowledge of any hidden parameter for binding. You didn't explain out what this "hidden" parameter is or where it is (i.e., reference source). Because I have no understanding of it, it falls more under the "support request" type of issue as far as the docs repo is concerned, so it should go to the product unit for now. If you add the line that pings me to your issue over there and cross-links this issue, I'll follow along until I understand what content should be added or updated. Then, I'll re-open this issue for work. That's just the way that we work here. We try to keep the backlog as clean as possible and as focused on actionable work items as we can.

**Comment by Timores** [comment]
When you use @bind-Value on a component, it expects the Value property and ValueChanged callback, but it also sets a ValueExpression property of type Expression.
See https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputBase.cs, lines 32 to 49 (at the time of writing).
And the SetParameterAsync method, lines 191 to 232 I quote a small part:
            if (ValueExpression == null)
            {
                throw new InvalidOperationException($"{GetType()} requires a value for the 'ValueExpression' " +
                    $"parameter. Normally this is provided automatically when using 'bind-Value'.");
            }
If you want to create your own component which uses, say, InputNumber, while providing the binding ability (which is nicely explained in the docs), you also need to forward the ValueExpression property to InputBase.
This is something that took me a long time to figure out and I thought that it could help others.

**Comment by Timores** [comment]
By "hidden", I meant that it seems to happen automagically and I could not find any mention of it in the docs. 
There was no intent of saying that anyone is trying to hide information. Apologies if it was unclear.

**Comment by guardrex** [comment]
I see ... so this pertains to built-in forms components' binding scenarios. I didn't pick up on that from your opening post.

We keep the general subject matter on forms components over in ...

https://learn.microsoft.com/aspnet/core/blazor/forms-and-input-components

... and you're correct that we don't cover `ValueExpression` in that scenario, probably because it's dependent on a framework implementation for the built-in components that's subject to change at any time.

I'll update the metadata for this issue because if we did cover anything like this it would be for the forms topic. I'll take a closer look at this later today or tomorrow morning. I probably will need to consult with the product unit to see how deep into the weeds that they want to get with the framework implementations for those components. They often say that they don't want to cover API aspects that are entirely up to arbitrary design decisions made at a point in time for them.

**Comment by Timores** [comment]
Other components like the Telerik Blazor suite seem to depend on this... 
Don't know if this is the right thing to do for them, but this is how it is.

**Comment by guardrex** [comment]
I read a bit on that parameter that [Chris published](https://chrissainty.com/creating-bespoke-input-components-for-blazor-from-scratch/). The product unit decided not to show/explain how to build components from `InputBase`, so it wouldn't be expected to see this coverage without additional coverage on the whole scenario. Since the product unit ruled it out, we don't need to address it in the article. I'm sure that they'll keep an 👂 open on requests tho going forward. If enough developers ask them, they might agree to cover it. I'll ...

cc: @mkArtakMSFT 

... so that he's aware that a request came in.

Artak ... TL;DR ... @Timores is asking for coverage on building bespoke `InputX`-type of components from `InputBase`, but the PU ruled that out a long time ago.

**Comment by Timores** [comment]
I am not asking for specific documentation on building components out of InputX classes. Using this classes was just an example.
I am asking to document the fact that the Value and ValueChanged properties are not the only ones being magically set when using the @bind syntax. I think that other developers would benefit from knowing about ValueExpression (again using 'Value' as an example)
The doc page linked to this discussion is quite good but is, IMHO, missing the explanation of the Expression property.

**Comment by guardrex** [comment]
I hear you, but the product unit (PU) doesn't agree (*yet* anyway 😄 ... they might change their mind at some point in the future). The most likely reason (AFAICT) that a dev would need to read about this param in the doc is for (as you said) advanced use cases working directly with `InputBase`, which the PU (product unit) ruled out right from the start. When these articles go up, the PU reviews them and calls out if they feel anything is missing. They didn't flag this param for coverage at the time.

Besides, it's documented via the API docs ...

https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.inputbase-1?view=aspnetcore-7.0

... and all of the built-in components in the *Built-in input components* section cross-link to the API docs, where devs can see that they all either inherit from `InputBase` or `ComponentBase` ... and then they can research from there and study how the PU composed these.

As I said right from the start ... and as I still suspect ... the PU may feel that `InputBase` is an internal framework implementation for these `InputX` components and subject to change at any time without notice. They often decide ***not*** to cover such aspects in the articles because there are too many of these internal implementations churning away over the years to keep up with in docs and for advanced use cases. For this type of param, they *may* just need to ***not document it*** 😄 in order to be able to efficiently change the framework on-the-fly without the fear of breaking articles.

Of course, the reference source is also available and considered "documentation" of sorts for how the PU designed `InputBase` to work. It's also covered in any number of blog posts on the subject, including Chris's blog, which comes up early in search results. The articles in the Blazor docs node are considered introductory coverage for the most common use cases. This one falls outside of that scope ... *for today* ... we'll see if they change their mind in the future on it.
