### ISSUE TITLE
There was an error in the Razor Page tutorial due to missing material. 

### ISSUE THREAD

**Issue by ANIZA15** [dotnet/AspNetCore.Docs#28823]
Visual Studio Codeのサンプルにて
[Razpr Page Tutorial ASP.NET Core 7.0](https://learn.microsoft.com/ja-jp/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio-code#add-nuget-packages-and-ef-tools)の
`NuGet パッケージと EF ツールを追加します。`
```
dotnet tool uninstall --global dotnet-aspnet-codegenerator
dotnet tool install --global dotnet-aspnet-codegenerator
dotnet tool uninstall --global dotnet-ef
dotnet tool install --global dotnet-ef
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet add package Microsoft.EntityFrameworkCore.SQLite
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
```
の箇所ですが、` Microsoft.EntityFrameworkCore.Tools`が不足していた為、
```
To scaffold controllers and views using models, install Entity Framework core packages and try again: Microsoft.EntityFrameworkCore.Tools
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:06.68
```
のようなエラーでました。

そこで、
```
 dotnet add package Microsoft.EntityFrameworkCore.Tools --version 7.0.3
```
を実行し、その後に続くチュートリアルの
```
 dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovie.Data.RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries -sqlite
```
が実行できるようになりました。

現在だと資料に追記されていない為、
```
 dotnet add package Microsoft.EntityFrameworkCore.Tools --version 7.0.3
```
の追記をお願いします。

- Visual Studio Code 1.75.1

<!-- - なぜこの記事が必要なのかを説明してください - 目次の中にその記事を入れる場所を提案してください - アブストラクトを書いてください。短い**段落で、この記事が何をカバーするのかを記述してください。私たちはこのアウトラインを確認し、誰かが記事を書く前にそれを承認します。

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio-code#add-nuget-packages-and-ef-tools)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Thank you @ANIZA15 for taking the time to let us know.
Unless I misunderstand the details, I think what has happened here is that a return was not hit after copy pasting in the the add package commands.  It takes a while for all of them to run and it is easy to forget to hit the return key so that the very last line of commands runs as well.

The above list of commandsyou show that were run, is missing MIcrosoft.EntityFrameworkCore.Tools.  However the tutorial does actually include it in both the jp and en versions.
Here is a screenshot of the current version:
![image](https://user-images.githubusercontent.com/10985336/228971902-ef1d7c8d-8bb0-4bfc-9042-c4cc75a53376.png)

I will close this issue, however if you think I have missed something and you have more information that might lead to a change in the tutorial, please feel free to reopen.  Again, thanks for letting us know.

**Comment by ANIZA15** [comment]
Thanks @wadepickett. 
Thank you for taking the time in your busy schedule to confirm this.

I think the following pull requests were probably issued and confirmed after the commits were merged.
Commit: [Add missing required code generation package](https://github.com/dotnet/AspNetCore.Docs/commit/58d4a1bfccda5ed09d766928d7e716)
Pull requests: [Add missing required code generation package #28809](https://github.com/dotnet/AspNetCore.Docs/pull/28809)

I think I may have delayed your confirmation, because I submitted the issue on Feb 26 in Japanese.
I will submit pull requests in English next time when I judge it to be of high importance.

Thank you very much.

Translated with www.DeepL.com/Translator (free version)
