### ISSUE TITLE
Incomplete example in Blazor documentation "Call JS from .NET"

### ISSUE THREAD

**Issue by Flachdachs** [dotnet/AspNetCore.Docs#28906]
The example at the end of the section ["Reference elements across components"](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-7.0#reference-elements-across-components) is incomplete. The parent component `CallJsExample7` passes `this` to the child component `SurveyPrompt` in parameter `Parent` but the child component has no code to do anything with it. It hasn't even a parameter `Parent`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7ea38a-649b-303d-bebf-c701e216ba25
* Version Independent ID: 9e197a8b-2616-8363-0a15-38cac802e82e
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Flachdachs ... I see what you mean. Yes, it looks like the partial class was accidentally separated from the article [during the updates for .NET 7 last year](https://github.com/dotnet/AspNetCore.Docs/pull/27535/files#diff-b6412a1c2d750575db46dc7a08e70cbd8b29be750886bf17ae847ef105bb5806L418), probably because when I was copying files for the new 7.0 snippet sample app I didn't get the file moved over to the new sample. When the article build later didn't find that file, I guess I assumed that we had changed the example at some point to shed that file ... ***NO!*** 😈 ... We didn't. I merely didn't get that one file moved into the new sample app when I was setting up for the next release.

I'll take care of this right now. All I need to do is move a copy of the file from the 6.0 sample to the 7.0 sample, and then come back over here and replace the two lines that will identify and show the file in the article.

***Thanks for the report!***
