### ISSUE TITLE
missing step in tutorial

### ISSUE THREAD

**Issue by ehardebeck** [dotnet/AspNetCore.Docs#28984]
Following the instructions, this error is reported:

1>C:\Program Files\dotnet\sdk\7.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1004: Assets file 'xxxxx\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
@ehardebeck thanks for letting us now.  I will test through this topic as soon as I have a chance.

**Comment by wadepickett** [comment]
@ehardebeck, I tested through the entire tutorial with the lastest VS 2023 +.NET 7.0 and the latest packages (not previews):
Microsoft.EntityFrameworkCore.InMemory  (v. 7.0.5)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore v. 7.0.5)

I could not recreate the issue you are running into.  It ran as expected.

You might take a look and see what package versions you currently have in the project.  Verify you have both I listed above and both are the same version 7.0.5.  

In Visual Studio, right-click on your **TodoAPI** project, select **Open in terminal**, and and run the following command to get details on the installed packages:
```text
dotnet list TodoApi.csproj package --verbosity d
```
The expected output should be the following:
```text
Project 'TodoApi' has the following package references
   [net7.0]:
   Top-level Package                                           Requested   Resolved
   > Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore      7.0.5       7.0.5
   > Microsoft.EntityFrameworkCore.InMemory                    7.0.5       7.0.5
```
Since it is not clear what state your app is in, you might have to restart with the tutorial and a new project.

There were some minor changes in the UI for the recent Postman app update, which I have an issue for already which I will address in a doc update, but nothing related to your issue here.  Just that the JSON setting is under 

I am going to close this issue, but feel free to reopen if you have a new insight on a change that is needed in the tutorial.  Thanks again for letting us know your experience.
