### ISSUE TITLE
Appsettings keys are not present

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/AspNetCore.Docs#29038]
There is a table showing which values to set to which keys in an appsettings.json file, but they seem to be documentation placeholders that should have been replaced with actual key names.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory B2C](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @mrpmorris ... That's not really workable because some config values are made up of multiple placeholder values from the CLI command that creates the app and at least in one case for the client ID there are two of them, which need to be distinguished for the **Client** and **Server** apps in hosted WASM scenarios.

Adopting my approach, the placeholders can be constants across both the CLI command and the values in the files shown. This was the best way I could think of to do this in a consistent, simple way and avoid confusion about what value goes where ...... and by adding the actual example files with fake values SxS with the placeholder files.

Only a few devs over the years opened an issue with a broken app that turned out to be a mistake in getting the values in the right spots. They were usually suffering from simple 😈 where they did things like ...

* Stuck the client ID for the **Server** app into the **Client** app's config, or vice versa.
* Completely avoided placing a key-value pair in the configuration because they just missed it for some reason or thought it was optional config.
* Didn't faithfully copy something (e.g., a client ID, a scope, a sign-up/sign-in policy name) from the Azure portal into their CLI command and/or app config.

... i.e., they just simply weren't following the guidance.

Thanks for the suggestion, but I'm going to stick with what we have given that only about a half-dozen devs have opened issues in this vein out of thousands of devs who have used these articles over the last five years. I continue to monitor the situation for devs writing in saying that they're confused by something, but such issues are *very* rare with this group of articles.
