### ISSUE TITLE
@using reference doesn't exist in April 2023

### ISSUE THREAD

**Issue by blanthor** [dotnet/AspNetCore.Docs#29048]
There is no Microsoft.Maui.Storage. What should I really be using in a .NET MAUI / Blazor project, if i want to access images in Android?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b14a096-b1a3-2270-e57f-8238a25601cd
* Version Independent ID: 1b14a096-b1a3-2270-e57f-8238a25601cd
* Content: [ASP.NET Core Blazor Hybrid static files](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/static-files?view=aspnetcore-6.0#net-maui)
* Content Source: [aspnetcore/blazor/hybrid/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @blanthor ... It's a *thing* 😄 ...

https://learn.microsoft.com/dotnet/api/microsoft.maui.storage

What exactly are you seeing? What's the error/problem?

**Comment by guardrex** [comment]
I'll check the namespace's use in that first example to confirm that it's meaningful there. I have some local examples in a local test app that don't use the namespace ... I assume because some of my local testing components didn't need it. I'll get back to you shortly.

**Comment by guardrex** [comment]
Ok, well ... I discovered one thing ... that namespace can be dropped from the first example. It no-ops because there's no API in use from it. However, it doesn't break anything. The sample code still works well.

**Comment by guardrex** [comment]
@blanthor ... I'll fix the namespace reference in the first example, but you should be able to use the `Microsoft.Maui.Storage` API in your app ... and you don't need an `@using` for it. The framework makes that namespace available to the app. If you need product support, open an issue with that team at ...

https://github.com/dotnet/maui/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/29048
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.

For now, don't close this. It will close when my PR goes in to fix (remove) the namespace in that first example. I'd also like to add a section on the namespace API calling out its existence. I'll have Mackinnion, one of the product unit engineers, look things over on the PR.
