### ISSUE TITLE
Add MacOS instructions to AOT

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29112]
See https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8839fa1e-7c10-4b22-d03d-669906a2b9ea
* Version Independent ID: 8839fa1e-7c10-4b22-d03d-669906a2b9ea
* Content: [ASP.NET Core support for native AOT](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=pr-en-us-29062&view=aspnetcore-8.0&tabs=netcore-cli)
* Content Source: [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/native-aot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @mitchdenny
* Microsoft Alias: **midenn**

---
[Associated WorkItem - 117425](https://dev.azure.com/msft-skilling/Content/_workitems/edit/117425)

**Comment by wadepickett** [comment]
@Rick-Anderson, are there known differences you are already aware of MacOS or is this issue more a matter of just testing the topic out on MacOS and note any?  It is all CLI and appears that it would not require a MacOS tab version, but of course I will check.  Thanks.

**Comment by Rick-Anderson** [comment]
I don't know.

**Comment by wadepickett** [comment]
Instructions worked the same in CLI on Mac as they did for Win, (thanks to Andy for testing).  However, the original instructions in the tutorial naive-aot-tutorial.md and the overview native-aot.md use the command `--aot` rather than `-aot`.   `--aot` is not a recognized command, `-aot` is and works as expected. So I corrected that in both docs in the PR.
