### ISSUE TITLE
Discussion on multiple hosted Blazor apps

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#29248]
Discussion issue

@philip-reed ... Let's discuss the doc's approach here. Discussion on Javier's approach can stay on the PU discussion issue.

I'm moving the prior convo remarks from the closed issue here ...

> @guardrex Mind pushing your example please, I don't see the latest code in your fork.
I'm curious if the generated @import statement for the css in MultipleAppsRazorClassLibrary is using the correct subpath.

> Yes, I'll put that up now, but I can't get back to discussing this one today due to being buried in another set of updates. I should be free to get back to this on Monday.

> Clarify what you mean by ...

> > generated @import statement for the css in MultipleAppsRazorClassLibrary is using the correct subpath.

> There is no such line. The CSS is bundled. It's applied to the client apps via the guidance at ...

> https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/multiple-hosted-webassembly?view=aspnetcore-7.0&pivots=route-subpath#razor-class-library-rcl-support

> ***UPDATE***: Here's my test app for the subpath approach: https://github.com/guardrex/MultipleBlazorApps_Subpath

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96763362-f8ba-0f11-0070-da8f9f533e21
* Version Independent ID: 96763362-f8ba-0f11-0070-da8f9f533e21
* Content: [Multiple hosted ASP.NET Core Blazor WebAssembly apps](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/multiple-hosted-webassembly?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Per the PU issue ...

> Might also be worth ignoring case in the docs to avoid any confusion:
StartsWithSegments("/SecondApp", StringComparison.OrdinalIgnoreCase)

***Yes!*** ... That's a nice update for this. We'll at least do that.

**Comment by philip-reed** [comment]
> Clarify what you mean by ...
> 
> generated https://github.com/import statement for the css in MultipleAppsRazorClassLibrary is using the correct subpath.
> 
> There is no such line. The CSS is bundled. It's applied to the client apps via the guidance at ...
> 
> https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/multiple-hosted-webassembly?view=aspnetcore-7.0&pivots=route-subpath#razor-class-library-rcl-support
> 
> UPDATE: Here's my test app for the subpath approach: https://github.com/guardrex/MultipleBlazorApps_Subpath

I've managed to run your example now (had to drop back to net7.0 as I'm not set up for net8.0 yet, but I'm sure that won't impact anything).

It looks like you _are_ calling `app.UseStaticFiles()` which is what I was getting at here: https://github.com/dotnet/aspnetcore/issues/47803#issuecomment-1545523021 
but I think that isn't called out in the docs that this needs adding for root, and for each sub path.

Calling `app.UseStaticFiles()` for root means that you don't need to manually add a link to the ComponentLibrary.bundle.scp.css in index.html
![image](https://github.com/dotnet/AspNetCore.Docs/assets/7798175/1c8a61e8-cdfe-4400-9ac5-63f9363d0b06)

However, if you _don't_ call `app.UseStaticFiles()` for root, then you _do_ need to manually add the ComponentLibrary CSS, and this also results in a double request for this CSS, one initiated by the link in index.html, and another initiated by `MultipleBlazorApps.Client.styles.css` (for FirstApp), and this one gets a 404 because it isn't using the sub path:

![image](https://github.com/dotnet/AspNetCore.Docs/assets/7798175/b399736a-4a22-4787-ad7d-808c21081485)

So to round up:
- Your solution works (Thank You 👍)
- The docs might need to mention that `app.UseStaticFiles()` needs to be called for `/`, `/FirstApp` & `/SecondApp`
- Manually adding the RCL's bundles stylesheet (as mentioned below) isn't necessary
 
![image](https://github.com/dotnet/AspNetCore.Docs/assets/7798175/dc0a337d-1d2f-4f1b-a61c-2214957f54d4)

**Comment by guardrex** [comment]
Thanks for the additional information.

> looks like you are calling app.UseStaticFiles()
>
> isn't called out in the docs

Thus far, I've only indicated that it's required outside of the client middleware pipeline if the Server app is working as a Razor Pages or MVC app, but I see what you mean now.

The reason that slipped through 😈 is that there are ***too many permutations going on here*** 😆 ... with the Server app hosting RP/MVC and without it and with the RCL and without it. I never checked with the RCL in the non-Server RP/MVC app case, so I never saw that 404 until just now.

I agree with your conclusions. We should keep the root Static File Middleware and drop the RCL bundled styles ... but I do need to confirm that that works ok in the non-Server RP/MVC app case.

Still tho ... I'm happy with it thus far if that turns out to be the only problem to address (+ the ignore case on the URL segment).

I'll get back to this on Monday. Thanks again for researching that out. :beers

**Comment by guardrex** [comment]
I'm *BACK!* 😄 ... The other thing that I was working on was going OK but not great. I'll pick back up with that on Monday.

I confirmed the planned updates look good for the domain/port approach, too. I'm going to set up the PR now.
