### ISSUE TITLE
HTTP instead of HTTPS

### ISSUE THREAD

**Issue by Bunyod16** [dotnet/AspNetCore.Docs#29266]
While following the tutorial, I noticed that the test link provided for the API endpoint was "https://localhost:<port>/<endpoint>". I believe that this link should be changed to "http://localhost:<port>/<endpoint>" and I would like to suggest this change.

My reasoning for this suggestion is that to use the "https" protocol we need to mess with settings in postman which the user might forget to enable later. However, in the case of this tutorial, we are simply testing a very basic API endpoint, and there is no sensitive information being transmitted. Therefore, using the "http" protocol is more appropriate and avoids any unnecessary overhead associated with setting up an SSL connection.

Furthermore, using the "http" protocol is more straightforward and easier to understand for beginners who may not be familiar with setting up SSL certificates. This change will make the tutorial more accessible and easier to follow, even preventing users from making mistakes by forgetting to disable the "SSL certificate verification" setting in postman which would give a confusing error.

I believe that this change will improve the overall user experience of the tutorial and I would be more than happy to submit a pull request to implement this change. Thank you for your consideration.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio-mac)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
@bunyod16, I see your point, and agree using https makes it a step more complicated.  However, based on feedback I have seen over the years, I believe whenever we made things a step simpler by using HTTP rather than HTTPS, we would get complaints that the example/tutorial is neither secure nor realistic (if I remember correctly).  Hense we are always using HTTPS (or both HTTP and HTTPS).  For an API example like this, HTTPS would usually be expected.  That said, it is cool you offered to do the PR yourself, thanks for the awesome community spirit!

@tdykstra and @Rick-Anderson, who have been involved in this topic longer than I, in case they have some additional thoughts on the matter.

**Comment by wadepickett** [comment]
Closing this issue after additional author feedback and per note  above on the larger scope of customer feedback we have received in the past on avoiding HTTPS and after reviewing past customer feedback history on this topics.
