### ISSUE TITLE
The "Razor syntax reference for ASP.NET Core" should be @key

### ISSUE THREAD

**Issue by wenhx** [dotnet/AspNetCore.Docs#29350]
All the "Razor syntax reference for ASP.NET Core" in this document should be changed to @key. 
This is an obvious error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 990fa811-0222-1acf-bf56-751a451b873f
* Version Independent ID: 990fa811-0222-1acf-bf56-751a451b873f
* Content: [Retain element, component, and model relationships in ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/element-component-model-relationships?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/element-component-model-relationships.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/element-component-model-relationships.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by wenhx** [comment]
The "Razor syntax reference for ASP.NET Core" all over the article was really bothering me.
Thank you for fixing this issue. @guardrex

**Comment by guardrex** [comment]
Sure thing. Sorry that it happened. Markdown supports these cool link lists for our articles, such as in the Components overview ...

```markdown
<!--Reference links in article-->
[1]: <xref:mvc/views/razor#code>
[2]: <xref:mvc/views/razor#using>
[3]: <xref:mvc/views/razor#attributes>
[4]: <xref:mvc/views/razor#ref>
[5]: <xref:mvc/views/razor#key>
[6]: <xref:mvc/views/razor#inherits>
[7]: <xref:mvc/views/razor#attribute>
[8]: <xref:mvc/views/razor#namespace>
[9]: <xref:mvc/views/razor#page>
[10]: <xref:mvc/views/razor#bind>
```

... and then in the topic, you can use abbreviated links, such as ...

```markdown
... doesn't have an [`@page`][9] directive, so the ...
```

... with the `[9]` to identify the link, instead of having to have the full XREF cross links, which would go like this ...

```markdown
... doesn't have an [`@page`](xref:mvc/views/razor#page) directive, so the ...
```

When I was working on breaking up the topic by pulling sections out into new topics, I did a straight find-'n-replace for the links ... and well ... that got the 😈 into my new article! 🙈

I'll be more careful for further pulling sections out of the topic. Thanks again for your issue.
