### ISSUE TITLE
Documentation Unclear

### ISSUE THREAD

**Issue by Sudo-Ale** [dotnet/AspNetCore.Docs#29380]
Hi, I'm a software developer .NET.
I followed this "tutorial" and i said in quotes because it's just a copy and paste nothing else.

- What is SignalR? 
- Why I'm using this and that? 

No answers, no explanation unfortunately...
Ye, of course I can search things by my own, I know that, but still this isn't a tutorial. Just an explanation of how to "copy and paste" this code and it's working!

Please, If you could give explanations during the "tutorial" it would be awesome. 
I don't need a full course on SignalR. But neither just only copy and paste...

Thanks, regards.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Version Independent ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Content: [Use ASP.NET Core SignalR with Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0&tabs=visual-studio&pivots=server)
* Content Source: [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
No problem ... I'm glad to hear the feedback.

One more note on this subject ...

It might be that you hit this problem because you were traversing the table of contents from outside of the Blazor node. The tutorials in the Blazor node appear in the list of articles ***after the introduction*** ...

![image](https://github.com/dotnet/AspNetCore.Docs/assets/1622880/5884ec2b-fb79-4c3e-bef4-b044f2cdc7fb)

I think that might be why I'm not hearing about this more often. Occasionally tho, we do get general feedback that matches what you said, even if the reader had already consumed the reference material. Many readers ***do*** want more tutorial explanations. However, we're somewhat hamstrung here, since the docs management has decided that that's not what they want.

I'll keep an 👂 open for more feedback in this vein. I might move the Blazor *Tutorials* folder down another peg to just after the *Hosting Models* topic, and I might remark at the top of the tutorials what it says in the *Next Steps* section, namely to see the reference topics to learn about the tech.
