### ISSUE TITLE
Errors implementing code to use DTO

### ISSUE THREAD

**Issue by couch-witch** [dotnet/AspNetCore.Docs#29426]
When following this tutorial  (modified to represent a user registration model), everything worked great until I implemented the DTO. Using the code in the tutorial I am getting `error` CS1955: Non-invocable member 'UserDTO' cannot be used like a method. 

From my controller:
```
 // GET: api/Users
        [HttpGet]
        public async Task<ActionResult<IEnumerable<UserDTO>>> GetUsers()
        {
          if (_context.Users == null)
          {
              return NotFound();
          }
            return await _context.Users.Select(x => UserDTO(x)).ToListAsync();
        }
```

From my UserDTO:
```
namespace SymptomTrackAPI.Models
{
    public class UserDTO
    {
        public long Id { get; set; }
        public string? Fname { get; set; }
        public string? Lname { get; set; }
        public string? Email { get; set; }
        public string? username { get; set; }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
There is a great discussion for understanding the error you are running into with your own code to check out here: 
- [stackoverflow: Count cannot be used like a method in an ASP.NET MVC controller] (https://stackoverflow.com/questions/54254383/count-cannot-be-used-like-a-method-in-an-asp-net-mvc-controller).  
- This one on the compiler error itself is also helpful: [Compiler Error CS1955](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1955) 

CS1955 occurs when you try to use a property, field, variable or dynamic type as a method and append brackets to call it: Such as `myObject.MyProperty();`  instead of `myObject.MyProperty`.
Your own code provided is different from the topic's code which works.
