### ISSUE TITLE
Microsoft Edge is not displaying the page content after installing the self-signed certificate. 

### ISSUE THREAD

**Issue by conyg** [dotnet/AspNetCore.Docs#29519]
I followed the instructions in this tutorial:

- I pressed yes on the dialog about trusting the SSL certificate (cheked "Don't ask again")
- I pressed yes on the security warning regarding installation of the certificate

The browser greets me with the message "Your connection isn't private". I know that generally I can click the "Advance" button and then click a link to allow me to navigate to the page despite the warnings. Well, this is not the case. I am stuck with this screen not being able to test and continue my development. And this is just accessing a localhost page... 

I tried going into settings of the Microsoft Edge and set the "Permission for this website" -> Insecure Content -> Allow
but that didn't help either.

It seems that the solution laid out in this tutorial needs to be reviewed to provision for the latest development on browsers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wad
![Capture](https://github.com/dotnet/AspNetCore.Docs/assets/3230679/6e3e0146-0bf6-4115-8168-292296b358ec)
epickett
* Microsoft Alias: **wpickett**

**Comment by conyg** [comment]
It seems that after I restarted Microsoft Edge by closing all open windows (I had a separate window opened with different content) the problem was fixed and i was able to open the project successfully.

**Comment by wadepickett** [comment]
Thanks for the info and the update and what more you found.  Given we don't know what state Microsoft Edge was in before you had to restart it, but it was in a good state and all ran fine after restarting Edge, and I'm able to run through it OK on my end, I will go ahead and close this issue.  Feel free to reopen if there is more information that would indicate the tutorial itself needs to change in some way.

**Comment by carehart** [comment]
I realize this ticket is closed, but **I wanted to share a couple more observations if they may help**, on this problem reported by @conyg , as I experienced the same (when enabling a self-signed cert, where then in Edge I didn't at first get the normal "continue to localhost (unsafe)" message). FWIW this was on the latest Edge (134.0.3124.72) as of mid-March 2025. 

First, while indeed closing and opening the browser would help, I found (before seeing this) that opening a new incognito window worked also. That may help someone not wanting to close the browser entirely. :-)

But second, I'll point out how the error you saw in the browser reported "ERR_CERT_INVALID". I saw that as well.  The difference (when things "work as expected" and we WOULD see the link to "continue") is that the error is reported instead "ERR_CERT__**COMMON_NAME_**_INVALID". Subtle, but perhaps helpful to someone. 

Finally, I had found also on digging into things that the browser feature to display the cert showed that I'd gotten TWO identical certs returned instead of one. This can be seen easiest by just clicking on that "ERR_CERT_INVALID", which causes the browser to show the cert (that was a nice surprise I discovered in this effort). Or of course you can click the "not secure" to the left of the address bar and then click the icon to show the certs that way.

And note how the error shown in the OP (which I got also) indicates, "_You can't visit localhost right now because the website sent scrambled credentials that Microsoft Edge can't process._" My suspicion is that the browser is getting confused by the two certs (rather than any truly "scrambled credentials"--though I realize those messages are for end users, so not too detailed). 

Anyway, hope these details may help someone else who looks for/finds this challenge.
