### ISSUE TITLE
The Tutorial That Explains Nothing

### ISSUE THREAD

**Issue by speschka** [dotnet/AspNetCore.Docs#29737]
This page was listed as one of the Blazor tutorials.  It seems to be nothing more than a copy code and paste exercise.  It gives absolutely no details about what you're doing, why you're doing it, why it's important, other considerations, etc.  In short, it's not really a tutorial at all.  If all you have is a copy and paste exercise, there is about a zero percent chance that you can actually rationalize it's use case and determine where and how it can and should be used when an actual project comes up.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Version Independent ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Content: [Use ASP.NET Core SignalR with Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @speschka ... That's correct and by-design in this case. Microsoft tutorials are often little more than a quickstart experience to get a use case up and running ... not much more than a sample app really. In this case, the tutorial is more useful for someone who has experience with SignalR and is discovering how to use SignalR in a Blazor app, so it assumes prior knowledge and/or access to the reference documentation. The product unit doesn't wish to expand on this particular article at this time. Access the reference documentation and API docs for in-depth coverage of SignalR with Blazor ...

* https://learn.microsoft.com/aspnet/core/signalr/introduction
* https://learn.microsoft.com/aspnet/core/blazor/
* https://learn.microsoft.com/dotnet/api/

For support, we recommend the usual forums/chats. For Blazor, we recommend the following resources ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](https://aspnetcore.slack.com/join/shared_invite/zt-1mv5487zb-EOZxJ1iqb0A0ajowEbxByQ#/shared-invite/email)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)
* [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor) (Community-maintained collection of Blazor resources)

However, leave this issue open. I'd like to explain the audience for this article at the top so that everyone understands the audience for it.
