### ISSUE TITLE
crash on android API 16

### ISSUE THREAD

**Issue by sadegh-q** [dotnet/AspNetCore.Docs#29994]
Android API 16 can't work with **StandardCharsets.UTF_8**, but in version `signalr:7.0.0

>  HubConnection.java Line:174

 it has been used. inside of function `handleNegotiate`

**Comment by wadepickett** [comment]
Thanks @sadegh-q for the heads up.

Correct, StandardCharsets.UTF_8 was not supported until Android API 19.  Before which, folks were having to use workarounds, such as for working with Scandinavian characters.

This issue is not on any particular doc topic, and might be best filed against the product code, (with more detailed information on the code example you are using) here: [ github.com |  /dotnet/aspnetcore/issues](https://github.com/dotnet/aspnetcore/issues)

Source is located here more specifically: https://github.com/dotnet/aspnetcore/tree/main/src/SignalR/clients/java/signalr

**Comment by wadepickett** [comment]
@BrennanConroy, searching around I am not readily finding any issues that pop up for SignalR in particular for this, but there is certainly the known issue of UTF-8 for some characters for Android API < v19.  Is there any mention I should make where we introduce [ASP.NET Core SignalR Java client](https://learn.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-7.0) and mention Android?

**Comment by BrennanConroy** [comment]
We mention API level in https://learn.microsoft.com/aspnet/core/signalr/java-client?view=aspnetcore-7.0#android-development-notes

**Comment by wadepickett** [comment]
Awesome, thanks @BrennanConroy!

**Comment by wadepickett** [comment]
@sadegh-q, don't create an issue on the SignalR source, the answer to your question/issue is covered in the docs at the link Brennan provided: [ASP.NET Core 7.0 : ASP.NET Core SignalR Java client : Android development notes](https://learn.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-7.0#android-development-notes)

- The SignalR Java Client will run on Android API Level 16 and later.

- Connecting through the Azure SignalR Service will require Android API Level 20 and later because the [Azure SignalR Service](https://learn.microsoft.com/en-us/azure/azure-signalr/signalr-overview) requires TLS 1.2 and doesn't support SHA-1-based cipher suites. Android [added support for SHA-256 (and above) cipher suites](https://developer.android.com/reference/javax/net/ssl/SSLSocket) in API Level 20."

**Comment by wadepickett** [comment]
(Added to August since I spent some time this morning verifying this issue in Android API and checking against our source)
