### ISSUE TITLE
Missing instructions?

### ISSUE THREAD

**Issue by chrisxfire** [dotnet/AspNetCore.Docs#30072]
"Configure Swagger to use the XML file that's generated with the preceding instructions."

There are no preceding instructions to reference this file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by timdeschryver** [comment]
@chrisxfire in the `.csproj` file you can enable the generation of the XML file.
This is explained in the [XML Comments section](https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-8.0&tabs=visual-studio#xml-comments).

However, the line "Configure Swagger to use the XML file that's generated with the preceding instructions" is an accidental copy-paste from the swashbuckle example. 
This can be ignored when using NSwag because NSwag renders the XML comments by default.
