### ISSUE TITLE
.NET 5 version needs to brought up to date for latest RazorMVC Template

### ISSUE THREAD

**Issue by maxmin88** [dotnet/AspNetCore.Docs#30131]
Original Program.cs looks nothing like what is stated on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Part 5, work with a database in an ASP.NET Core MVC app](https://learn.microsoft.com/en-gb/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Note: This is filed on .NET version 5 of this series.  Which was the version of the tutorial opened at the time of clicking the option to file an issue.

The prerequisites in the tutorial are set for the Visual Studio and .NET available at the time for that version which also includes the templates available for those versions, not the latest templates available in the latest versions.

For latest version of this tutorial select ASP.NET Core 7.0 or the latest preview select ASP.NET Core 8.0 Preview from the version selector on the top left: https://learn.microsoft.com/en-gb/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-7.0&tabs=visual-studio

Closing this issue since the templates are correct for that .net 5 and VS 2019 version in time.  Feel free to re-open this issue if there is something we missed.  thanks.
