### ISSUE TITLE
Schema has been moved update information.

### ISSUE THREAD

**Issue by pudrik** [dotnet/AspNetCore.Docs#30193]
Hi the Schema http://schemas.microsoft.com/XML-Document-Transform has been moved as displayed by the error message if you try to look at it. 

it would be nice if the sample code has the correct url and if the server could respond with a forward request instead of a dead end message.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c703c55-7ece-6e0d-2518-50786599530a
* Version Independent ID: 7e68f62c-8c84-e7a5-2a74-201fc60b3036
* Content: [Transform web.config](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/transform-webconfig?view=aspnetcore-7.0)
* Content Source: [aspnetcore/host-and-deploy/iis/transform-webconfig.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/transform-webconfig.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @pudrik ... Although it looks like an XML namespace, such as this one, should be a web address that you can navigate to, they aren't required to be a web resource that loads anything directly related to the XML schema. Parsers don't use the value to load any data or resource about the schema. It's in this format because it must be a URI value, which must be unique and have a standardized format. Think of more like just an identifier string than a formal web address. The URI *might* open something when requested, and it might actually load something relevant, but they aren't required to. It's in the W3C namespace spec under *3. Declaring Namespaces* ...

> It is not a goal that it be directly usable for retrieval of a schema (if any exists).

Ref: https://www.w3.org/TR/REC-xml-names/#ns-decl

There's more info in the Wikipedia page at https://en.wikipedia.org/wiki/XML_namespace.

I poked around for a sec, and I couldn't find a good MS document on this subject. When Rick sees this, he'll decide if any action should be taken. After all, this doc isn't really about the nuts and bolts of XML files. He may decide to just close this as an answered question.

**Comment by pudrik** [comment]
@guardrex I realise that most MS tools have a built in parsing of the rules specified on w3.org but normally the point of the schema is to contain rules on how it operates. Since the documentation is a little bit fuzzy i tried to access the XML to have a look at the full Schema to se what arguments there actually are. 

However since this is a dummy endpoint it might still be useful to add a link to the ref (like you did) or the RFC it implements.

and thank you for the link.

**Comment by guardrex** [comment]
Possibly ... but *Vegas odds* 🎲🎲 are that Rick will think that this is off-topic and can be researched by the dev further on the open Net.

Another thing is that if we cross-link in this article, we should cross-link in other articles, too ... up to a half dozen other articles ... and we're swamped with work right now 😅 right into 2024.

The team is 👂 for this type of feedback. If it becomes a recurring issue, I'm sure that the team will take steps to resolve it. I checked, and I only see this question asked one other time in the last six years.

**Comment by Rick-Anderson** [comment]
The value of the `xmlns:xdt`` namespace declaration doesn't need to be a valid URL. The URL is used as a unique identifier for the namespace, and it doesn't necessarily have to point to a real location on the web. It's a common practice to use a URL format for namespaces in XML documents to ensure uniqueness and avoid conflicts with other namespaces.

In the context of XML Document Transformation, the xmlns:xdt namespace is used to associate transformation attributes and elements with the specific namespace, indicating that they are related to transformation operations and not part of the standard XML schema.

For example, consider the following XML snippet:

```
<connectionStrings xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <add name="MyConnectionString"
       connectionString="DevConnection"
       xdt:Transform="SetAttributes"
       xdt:Locator="Match(name)" />
</connectionStrings>
```

In the preceding XML, the xmlns:xdt declaration establishes the http://schemas.microsoft.com/XML-Document-Transform URL as the namespace for the xdt prefix. The xdt:Transform and xdt:Locator attributes use this namespace to indicate that they are related to transformation operations.

The choice of URL is more about providing a unique identifier for the namespace rather than being a functional URL on the internet. It's a way to distinguish the custom namespace from other namespaces in the document.
