### ISSUE TITLE
Revise guidance for .NET 8 to recommend Blazor for web UI

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#30497]
With .NET 8 our guidance for choosing a ASP.NET Core web UI technology gets much simpler: You should just use Blazor. Blazor in .NET 8 can now do static server rendering (like MVC & Razor Pages), interactive server rendering (with Blazor Server), and interactive client-side rendering (with Blazor WebAssembly). So, you can really do it all from within one web UI framework. Blazor also has a rich component model that enables reusability and consistency, and it has new advanced rendering capabilities for progressively enhancing the user experience.

We should revise this topic to lead with Blazor as the recommend web UI approach. We should follow that with mentions of MVC & Razor Pages as mature and supported alternatives. We can mention that Blazor can be integrated with existing MVC & Razor Pages apps if desired. And we should still mention that pairing ASP.NET Core with frontend JavaScript frameworks is also supported. But Blazor should be the hero here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21671480-fba7-3692-1a20-e71843864b60
* Version Independent ID: 68d5aab0-63ce-de7a-0c56-341c2eef623d
* Content: [Choose an ASP.NET Core UI](https://learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-7.0)
* Content Source: [aspnetcore/tutorials/choose-web-ui.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/choose-web-ui.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 164336](https://dev.azure.com/msft-skilling/Content/_workitems/edit/164336)

**Comment by wadepickett** [comment]
Thanks Dan!

**Comment by wadepickett** [comment]
@danroth27, 

I will make the following organizational/section changes, unless you want otherwise:

1. Add a new section at the top recommending Blazor as the web UI approach and why, so it is clear at the start and therefore you will see that lead in old school search and AI search results.
1. Keep the server rendered UI and client rendered UI organization/sections below but lead with Blazor on each.

The current organization of this topic is as follows:
- [Benefits vs. costs of server and client rendered UI](https://learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-7.0#benefits-vs-costs-of-server-and-client-rendered-ui)
- [Choose a server rendered ASP.NET Core UI solution](https://learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-7.0#choose-a-server-rendered-aspnet-core-ui-solution)
- [Choose a client rendered ASP.NET Core solution](https://learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-7.0#choose-a-client-rendered-aspnet-core-solution)
- [Choose a hybrid solution: ASP.NET Core MVC or Razor Pages plus Blazor](https://learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-7.0#choose-a-hybrid-solution-aspnet-core-mvc-or-razor-pages-plus-blazor)

**Comment by danroth27** [comment]
> Keep the server rendered UI and client rendered UI organization/sections below but lead with Blazor on each.

@wadepickett I think we might want to simplify this content or potentially do away with it. We originally structured this doc around the reality that ASP.NET Core had a sort of patchwork quilt of web UI options, where no single offering could do it all. This meant we had to explain the different rendering patterns and their tradeoffs so that users could then map them to specific .NET/JS technologies. But now that Blazor can handle everything it starts to feel like unnecessary detail. We do at least need to describe that MVC & Razor Pages are static server rendering based frameworks and that frontend JS is still a valid alternative to Blazor for client-side rendering. It's probably also worth mentioning that MVC & Razor Pages are lower level stream based programming models that may be useful for highly optimized use cases where you want to control precisely how bits are being sent to the response stream.
