### ISSUE TITLE
unnecessary toArray in action

### ISSUE THREAD

**Issue by mulei2023** [dotnet/AspNetCore.Docs#30615]
### Type of issue

Other (describe below)

### Description

the Get action within `WeatherForecastController` returns` IEnumerable<WeatherForecast>`, no need to call `ToArray` since it leads to overhead of memory consumpion especially when the collection is large.

If some beginners copy these sample codes into their projects which has a large collection, may be introduce performance issue.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/apis?view=aspnetcore-6.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/apis.md

### Version Independent Document ID

4841921d-fe70-1264-88ff-b2f2d067b212

### Article author

tdykstra

**Comment by guardrex** [comment]
Hello @mulei2023 ... Let's discuss this further. I don't have a lot of time at the moment because I'm a bit buried in RC2 updates for Tuesday's release ... *I'm actually working on RC2 content right now!* 🗻⛏️😅 ... but I'm aware in a number of cases that the product unit used the `ToArray` in the project templates. Our docs follow their examples. For example ... just a couple of quick ones that I'm aware of off the top of my head ...

* https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Controllers/WeatherForecastController.cs#L73
* https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Pages/Weather.razor#L60

... and I'm not looking at the thrust of your argument at this point. I'm just identifying the code that they used. What you suggest might be welcome by the product unit as a change to the templates.

I think what you'd need to do is convince them to change the project templates first, then we'd go about matching the change in the docs. Admittedly, I'm most concerned and focused on the Blazor usages, but I suspect if we make a change that it will be across the docs. If that ends up being the right course of action, you would open an issue for the product unit first, they'd make the change (probably .NET 9 next year), and then we'd follow suit over here for that release.

@tdykstra @Rick-Anderson @wadepickett will assist further. I just wanted to get the ball rolling with the discussion and pitch that suggested approach for your recommendation.
