### ISSUE TITLE
Undocumented {PARAMETER NAME}Expression feature in blazor data binding documentation.

### ISSUE THREAD

**Issue by AntMaster7** [dotnet/AspNetCore.Docs#30656]
### Type of issue

Missing information

### Description

I came across a hidden feature with data binding that I could not find anywhere in the documentation. If you have a public parameter of type string for example you can add a _{PARAMETER NAME}Expression_ property and this property will be filled with the actual expression of the bound property. I think this detail is missing from the documentation and comes in handy for people who author their own input controls.

```C#
[Parameter] public string? Text { get; set; }

[Parameter] public EventCallback<string?> TextChanged { get; set; }

[Parameter] public Expression<Func<string?>>? TextExpression { get; set; } // undocumented feature
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md

### Version Independent Document ID

3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc

### Article author

guardrex

**Comment by guardrex** [comment]
Thanks @AntMaster7 ... I've sent a message internally asking about it. It might be something that you *can use* but that they kind'a don't want folks to rely on because it's a framework implementation detail that could 💥 at any time because they might change its behavior in the framework. We'll find out soon enough. I should have an answer on it within a day. *Stand-by ..............................*

**Comment by guardrex** [comment]
No response ... my message when into a ⚫ *black hole* :smile:, which isn't surprising.

We're all absolutely ***BURIED ALIVE in .NET 8 work*** 😨 ... perfect for 🎃 ***Halloween*** 🧟, right?! 😆

Can you open an issue to ask about it on the product unit's repo?

What you basically want to ask them is if that API/approach is considered to be an internal implementation or not. I have a feeling that they'll say that it is and that they don't encourage devs to do it (and don't want docs to cover it). However, it could be something that slipped through the cracks that we do need to cover.

Open the issue here ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/30656
```

... to the bottom of your opening comment so that I can follow along.

***Leave this issue open.*** We'll get back to it after I hear what they have to say.

**Comment by guardrex** [comment]
Thanks @AntMaster7 ... I'll proceed to work on this; but as I said over there, I'm completely ***BURIED***  🗻⛏️😩 until early next year with this *MEGA*-Blazor release for .NET 8. I'll get back to this as soon as I can.

**Comment by AntMaster7** [comment]
Thank you @guardrex I'm glad I can use the feature safely now.
