### ISSUE TITLE
Use of 'var' makes example code much less understandable

### ISSUE THREAD

**Issue by hugovdb1965** [dotnet/AspNetCore.Docs#30667]
### Description

[Enter feedback here]
This is not just for this page, but most examples in the documentation make extensive use of 'var' instead of explicitly naming the type of a variable. This make the code much harder to understand, because you need to look up what the return type for a method is every time. It's also lazy programming, in our company it's forbidden in the standards because of maintainability issues.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/secure-data.md

### Document ID

7c151ed5-fd78-84fd-a08a-88912990c4ca

### Article author

Rick-Anderson

**Comment by guardrex** [comment]
Hello @hugovdb1965 ... We follow the engineering guidelines for the ASP.NET Core framework, and so we're unable to change it. It's not considered by the product unit to be a "lazy" development approach. It's considered by the framework engineers to be the superior approach. Also note that VS shows the type when you use `var` ... just roll your mouse over the variable name.

https://github.com/dotnet/aspnetcore/wiki/Engineering-guidelines#usage-of-the-var-keyword

**Comment by hugovdb1965** [comment]
@guardrex thanks for your clarification

These examples are not in VS, but on a website that does not support rollover. Copy/paste into VS also does not help as most examples are by nature incomplete snippets, so copy paste into VS does not bring a rollover but a series of errors.

While in real world coding these guidelines may be defensible (it's often more an opinion than anything else), in documentation examples using var seriously limits readability and understandability of the example code. It requires much more effort from the person reading it.

**Comment by guardrex** [comment]
I wish there was a way to indicate types in an automated fashion for doc examples, but it's a limitation of the entire documentation system. You could try providing the feedback to Microsoft in general way at ...

https://github.com/MicrosoftDocs/feedback/issues

However, I have a feeling that even if it reached the right 👂👂 in docs management that they'd say it's too technically challenging to resolve because the .NET compiler would have to reason about the types shown in order to add something to the presentation indicating the types ... and as you said ... many examples are just snippets (although in Blazor docs I go to great pains to make examples fully-working, cut-'n-paste examples). However, you could give an issue a shot over there. There might be others asking, and they might be collecting feedback on it.

For this doc set, the `var` guideline is what the product unit has decided docs should adopt, so it won't change. See Artak's response at ...

https://github.com/dotnet/AspNetCore.Docs/issues/29557#issuecomment-1597864827

**Comment by hugovdb1965** [comment]
So the C# coding guidelines and the ASP.NET Core framework  engineering guidelines disagree on this. Nice.

Thanks for your clarification.

**Comment by guardrex** [comment]
... and that's not the only thing they disagree on. MS is a somewhat compartmentalized operation. It's too ***BIG*** to get every team for every product/service to agree on everything, nor do MS engineers always pitch to users/developers the practices that they adopt for framework code. Even the ASP.NET Core docs diverge from the ASP.NET Core framework coding guidelines on some things for some special reasons ... very much an old *'do what we say, not what we do'* situation 😄, and certainly the framework engineers differ across frameworks, product, and service engineering teams. Management would never be able to get everyone in every wing of the company to agree. It would be like *herding 🐈🐈🐈*.

For this particular problem ... the types and `var` ... you're not the only one asking. It needs to reach a critical mass ☢️ for them to take steps to resolve it, and they're just not there yet. I think it's because not enough negative feedback is reaching them. I'm just a contractor here, so I have no personal way to even forward it, which is why I floated a MS docs general feedback issue. If the FTE doc authors feel they're hearing enough about this, they'll probably take it up internally. They are 👂 here now, so your feedback is registering here with this small group of doc authors.

**Comment by Rick-Anderson** [comment]
@hugovdb1965 as @guardrex  indicated, the right place to open this issue is https://github.com/MicrosoftDocs/feedback/issues
