### ISSUE TITLE
Share authentication COOKIES between .NET 6 Core App and .NET 4.8 Application with FormAuthentication

### ISSUE THREAD

**Issue by sohaibameenpk007** [dotnet/AspNetCore.Docs#30695]
Hello Everyone, 

I have a legacy application which is built in .NET 4.8 with FormsAuthentication (Membership) in it and now I need to migrate this to newer .NET 6 version so I have created a new .NET 6 Core App. The idea is to create a COOKIE from  .NET 6 Core API which can be shared with .NET 4.8 application. I have generated the COOKIE successful from .NET 6 and sent it to .NET 4.8 app but it did not work as FormsAuthentication does not seem to work with this. 

I need some guidance to resolve this blocker so that would be great if anybody can help. 

@guardrex  @Rick-Anderson 

Thanks, 
Sohaib

**Comment by guardrex** [comment]
Hello @sohaibameenpk007 ... The only guidance that we keep is ...

https://learn.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-7.0

... in particular, see this section ...

https://learn.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-7.0#share-authentication-cookies-between-aspnet-4x-and-aspnet-core-apps

I'm going to close now because that's all that we have on it. If you run into trouble or have a different situation with your apps to address, we recommend chatting with devs on the usual support forums around the Net ...

* [Stack Overflow](https://stackoverflow.com/questions)
* [ASP.NET Core Slack](https://aspnetcore.slack.com/join/shared_invite/zt-1mv5487zb-EOZxJ1iqb0A0ajowEbxByQ#/shared-invite/email)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)
