### ISSUE TITLE
Asp.Net Core 7 - PasswordHasherOptions.IterationCount wrong default value

### ISSUE THREAD

**Issue by pampua84** [dotnet/AspNetCore.Docs#30774]
As mentioned in the title, on the documentation at the following link:

[https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.passwordhasheroptions.iterationcount?view=aspnetcore-7.0#microsoft-aspnetcore-identity-passwordhasheroptions-iterationcount](url) 

the default number of iterations is **100_000** but in reality it is **10_000**. I believe the current value is for .Net 8 and not 7 and earlier.

**Comment by guardrex** [comment]
Hello @pampua84 ... Please re-open this issue using the **Open a documentation isssue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

**Comment by guardrex** [comment]
... if the problem is an API document, then you must open for the product unit because the API documentation is drawn from the reference source, and they control that. Open it here ...

https://github.com/dotnet/aspnetcore/issues

If it's in one of our articles, we control those ... so open it using the **Open a documentation issue** link/form at the bottom of the article.
