### ISSUE TITLE
BrowserLink NuGet package is deprecated but docs don't explain this

### ISSUE THREAD

**Issue by nogginbox** [dotnet/AspNetCore.Docs#30826]
### Description

The nuget package [Microsoft.VisualStudio.Web.BrowserLink](https://www.nuget.org/packages/Microsoft.VisualStudio.Web.BrowserLink/) that this page is about has been depricated. This page does not show this, or explain what to use instead.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/client-side/using-browserlink?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/using-browserlink.md

### Document ID

78a1947e-dea7-65b4-2376-05c7795e4bf9

### Article author

ncarandini

---
[Associated WorkItem - 239921](https://dev.azure.com/msft-skilling/Content/_workitems/edit/239921)

**Comment by Rick-Anderson** [comment]
Per [.NET Package Maintenance (deprecation)](https://github.com/dotnet/announcements/issues/217)

Many of these packages are legacy or out-of-support already.

As a general principle, packages that are out of support per the [.NET Support Policy](https://dotnet.microsoft.com/en-us/platform/support/policy) will be marked deprecated.

BL is only used in development.

**Comment by lukos** [comment]
I don't understand why these docs take so long to update. Someone has already done the hard work of pointing out where the issue is and the nuget package has been deprecated since dotnet core 3 but despite multiple issues raised here and the fact that afaik the package is no longer needed, the instructions are still based on a very old version of dnc and we are still lacking instructions for more recent versions.

I still get browserlink inserted automatically with no packages required but it 404s. I saw an instruction about `app.UseBrowserLink` but that isn't recognised and the docs don't mention it anyway. I am trying to resolve some performance issues but my network tab is distorted by browser link attempting to make connections so it's really frsutrating.
