### ISSUE TITLE
Please provide an AI trained on Microsoft docs

### ISSUE THREAD

**Issue by Yevhen-Myroshnychenko** [dotnet/AspNetCore.Docs#30848]
### Description

It will be super if AI will answer the questions and provide examples based on the Microsoft docs. Thanks.
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md

### Document ID

86aeab13-1c25-9fc1-4e56-0390cb40c242

### Article author

Rick-Anderson

**Comment by wadepickett** [comment]
@Yevhen-Myroshnychenko, yes working on that.  The docs do show up in models, but of course a trained model specifically centered on the docs and code samples would be the thing as you suggest. :)   I will close this issue since it is not a specific issue on this routing topic but docs in general.   Thanks for letting us know what works best for you.
