### ISSUE TITLE
Clarify can   IOptionsMonitor incur a significant performance penalty?

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [dotnet/AspNetCore.Docs#30891]
### Description

In https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0#use-ioptionssnapshot-to-read-updated-data it is said that IOptionsSnapshot may incur a significant performance penalty.
Then in paragraph about “The difference between IOptionsMonitor and IOptionsSnapshot “ will be correct to  say, that 
	• IOptionsMonitor doesn’t incur a significant performance penalty. ?

	Please add it to clarify the difference 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0#ios

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/options.md

### Document ID

dc7e3449-650b-d117-5eac-69e5ccb250cb

### Article author

Rick-Anderson

**Comment by Rick-Anderson** [comment]
May incur a significant performance penalty because it's a [Scoped service](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#scoped) and is recomputed per request.

IOptionsMonitor is a [Singleton service](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#singleton) t

**Comment by michael-freidgeim-webjet** [comment]
@Rick-Anderson my suggestion was to explicitly add that “ IOptionsMonitor doesn’t incur a significant performance penalty.” 
it is not obvious, that [Singleton service](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#singleton)  doesn’t incur a significant performance penalty. Opposite, someone may decide that “ retrieve current option values **at any time**” is more expensive operation.

**Comment by jmathew** [comment]
Putting a comment on the relative performance impact of both would be useful. I also did not surmise that that IOptionsMonitor was performant solely because of if it being a singleton. And I did consider the primary use of IOptionsMonitor to be for getting the most up to date value at any time instead of just at construction time. Not that it was the preferred option for performance. This was the unfortunate misunderstanding that lead me to using IOptionsSnapshot in the first place. 

Somewhat related, IOptionsSnapshot's performance is much worse than I expected even with the warning of "significant performance penalty". I used OptionsSnapshot on an endpoint and tested with a relatively "production level" load of of about 1000 users making 1 request per second: CPU pegged at 100%, threadpool queue length spiking consistently to 300 (for whatever its worth), response times hovering around 11s for a somewhat complex config (pulls settings from azure) and 6s for a simple config (just what was in appsettings). The endpoint just printed the configuration.

I understand there are differences in use cases, but I think IOptionsSnapshot performance is so bad from my testing the warning should be more along the lines of 
> Only use IOptionsSnapshot if you have these narrow use cases: [explain use cases here]. In all other scenarios IOptionsMonitor is the better choice.  

A warning like that would've saved me many hours of performance profiling (I did not connect our performance drop to IOptionSnapshot initially because a lot of time had passed between when we switched to IOptionsSnapshot and when we did load testing).
