### ISSUE TITLE
Steps are not available in Azure AD

### ISSUE THREAD

**Issue by tacoWanneeJama** [dotnet/AspNetCore.Docs#30975]
### Description

![image](https://github.com/dotnet/AspNetCore.Docs/assets/76042577/e924882b-20a0-478a-ac88-9df3df5d6873)
I tried these alternative steps, but I could not find these options.....

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md

### Document ID

da9c8ac9-4d7a-4b40-56a2-a4bfe7083567

### Article author

guardrex

**Comment by guardrex** [comment]
Hello @tacoWanneeJama ... It's not surprising to me that you're reporting this. I have a (sad) joke that they change the Azure portal ***every 7.5 seconds!*** ... just meaning that they do change the portal quite rapidly, which results in broken documentation quite frequently 😩. It's just the nature of rapidly evolving tech these days. They're always trying to improve the experience, but they break what I write regularly when they do.

I'll take a look at this right now and see if I can spot where they moved it.

**Comment by guardrex** [comment]
@tacoWanneeJama ... No, it's still there. However, I think the first bullet of the NOTE might be incorrect. It says that the publisher domain must be trusted ... that may or may not be true ... I'd need to confirm that because I don't have a trusted publisher app registration in my ***non-Default Directory***. However, I was able to confirm that this pre-authorize UI shows up for apps registered in the Default Directory.

I'll need to return to this issue in a couple of weeks because I'm buried in .NET 8 release work. .NET 8 releases in less than a week, and I have many high priority doc issues to resolve for release.

If you can register your app in your Default Directory, then you should get the option to set the pre-auth ***without a trusted publisher domain***. If you can't register the app in your Default Directory, I recommend going through the process of using a trusted publisher domain and see if that unlocks the UI/setting.

**Comment by guardrex** [comment]
I've re-analyzed the scenario. I went back and looked at the [PR](https://github.com/dotnet/AspNetCore.Docs/pull/25235) and the [issue](https://github.com/dotnet/AspNetCore.Docs/issues/25026). I can't repro the scenario in the Azure portal with an untrusted publisher domain in a non-default directory, and I don't know where the TIP came from. I even performed a free text search of both this repo and the PU repo ... I can't find it. It's lost to the *Land of Wind and Ghosts!*™️- Ryan Nowak, 2019

So ... what to do. Well, the hosted WASM project template is gone. Hosted WASM is still supported, but the project template under 8.0 is in a rather dubious spot. It's not clear to me that we'd sweat this too much given that these remarks were only placed in the hosted WASM doc. It might continue to be a factor for API-based Azure identity. I'd like to leave the remarks here in case they help someone.

I'm going to close this as a *won't fix* for now. I'll keep an 👂 open for any further feedback as we proceed with new Azure coverage for standalone WASM with APIs ... if we host it. Currently, we don't have specific coverage in that area.
