### ISSUE TITLE
Blazor Web App with Azure B2C authentication failure

### ISSUE THREAD

**Issue by tacoWanneeJama** [dotnet/AspNetCore.Docs#31103]
### Description

I created a scaffolded balzor hoisted app (see: [github](https://github.com/tacoWanneeJama/BlazorAppNet8_Auth1117.git)
The application does support logging in to local account.
When adding login to B2C Azure, the login itself is doing ok, but when returning to the application it crashes:
![image](https://github.com/dotnet/AspNetCore.Docs/assets/76042577/650f776c-7016-414f-b78f-6fe0be2c2629)
I guess that I did something wrong while configuring the B2C registration. Maybe the instructions for the Application Registration can be more precise?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/microsoft-logins.md

### Document ID

ce69b990-0b4c-abda-cd2d-68f85cd8031e

### Article author

Rick-Anderson

**Comment by guardrex** [comment]
@JeremyLikness ... Do we have a plan for how we'll address any issues like this one from that are opened for BWA apps?

BTW, @tacoWanneeJama, your app is a "Blazor Web App." A "hosted Blazor app" from <8.0 is still supported but is a different type of app that's no longer recommended for Blazor and no longer a project template.

**Comment by tacoWanneeJama** [comment]
> @JeremyLikness ... Do we have a plan for how we'll address any issues like this one from that are opened for BWA apps?
> 
> BTW, @tacoWanneeJama, your app is a "Blazor Web App." A "hosted Blazor app" from <8.0 is still supported but is a different type of app that's no longer recommended for Blazor and no longer a project template.

It is a freshly created .Net8 templated Blazor app.
![image](https://github.com/dotnet/AspNetCore.Docs/assets/76042577/42f87703-abd0-45cd-a9d8-3a1419b9cb66)
What template do you suggest to use for my purpose?
I make this test app to be able to integrate this security logic to our existing Wasm app (.Net 7 for now, be we will migrate to .Net8 in a few weeks)

**Comment by guardrex** [comment]
That's fine. You wrote in your opening comment ...

> balzor hoisted app

... and I was just making the point that this isn't that type of app. We have a dedicated article for that type of app (for Azure B2C, not social logins) at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-7.0

... which doesn't apply for the new Blazor Web Apps unless it's going to be a client-side WebAssembly-rendered-only BWA app. Even then, I'm not sure if that guidance will work (yet ... I have a long-range plan to test it myself later, but probably in 24Q1).

We don't have a dedicated BWA (Blazor Web App) with B2C article, and it isn't known yet if we will have one. Normally, we defer to the Azure documentation and a tutorial that we keep in our doc set ... I think it's this one (for Azure B2C) ...

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-8.0

Another source of confusion about your issue is that your original post says ...

> login to B2C Azure

... but you didn't open this issue from that B2C doc that I just listed ... you opened it from the ***Microsoft social auth*** article. I'm not really sure what you're trying to do yet ... B2C ... MS social ... both? However, I thought that I'd ping Jeremy first to ask if we have any kind of plan for how Blazor Web App security support is going to be handled by the product unit because he may say that these types of issues need to go directly to the product unit repo for investigation. When there's an error like that, it might mean that there's a real bug in the framework. They work those types of issues from their repo, not from the docs repo.

**Comment by guardrex** [comment]
I just remembered that Jeremy might have a sample app for social providers coming soon-ish. We have an issue for that type of article at ...

https://github.com/dotnet/AspNetCore.Docs/issues/30994

He'll be along in a bit to remark further. Again, note that we're just about to head out for the 🦃 holiday, so he might not get on here until next week. Everyone is exhausted, and folks are probably bugging out as we speak for the long weekend break.

**Comment by guardrex** [comment]
Unfortunately, no response from Jeremy. Let's go for a PU support issue on this one. If you're still having trouble with Azure B2C and BWA configuration, open an issue for the PU here ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/31103
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.
