### ISSUE TITLE
StateContainerExample.razor: missing delegate

### ISSUE THREAD

**Issue by mjhillman** [dotnet/AspNetCore.Docs#31123]
### Description

[Enter feedback here]
The example "StateContainerExample.razor:" seems to be missing the "StateHasChanged" method.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/state-management.md

### Document ID

e5e1273b-195e-5da1-b4aa-66bbcff1425b

### Article author

guardrex

**Comment by guardrex** [comment]
Hello @mjhillman ... That depends on your code. If you load state prior to rendering on initialization or for event callbacks, you wouldn't need to call it. We don't place remarks about calling `StateHasChanged` in cases like this because we'd need to place remarks about it virtually everywhere. We keep the general guidance on it at ...

https://learn.microsoft.com/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#state-changes-statehaschanged
