### ISSUE TITLE
Routing 

### ISSUE THREAD

**Issue by Porkechebure** [dotnet/AspNetCore.Docs#31144]
[EDIT by guardrex to add the metadata and remove the issue template boilerplate]

Now to the issue.
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md?plain=1
Routing system is broken. Fix it or document it.
Even a midschooler could write a better routing system, but whatever.

Now, these routes apparently are ambigous:
```
[HttpGet]

[Route("retrieveInvoicesToPay")]

public async Task<IActionResult> RetrieveInvoicesToPayAsync(

CancellationToken cancellationToken = default

)

```
and

```
[HttpGet]

[Route("retrieveInvoicesToValidate")]

public async Task<IActionResult> RetrieveInvoicesToValidateAsync(

CancellationToken cancellationToken = default

)
```

Now, given that they have the same signature, they have different route attribute. This is totally infuriating.

Not only, I've added

[ActionName()] with the same name given to the Route attribute, so
```

[ActionName("retrieveInvoicesToPay")]

[ActionName("retrieveInvoicesToValidate")]
```

Still nothing. MVC sees them different.

What a lousy ****.

I had to add a prefix to the route like pay/retrieveInvoicesToPay and it's totally ridiculous.

LMAO what a joke.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md

### Document ID

86aeab13-1c25-9fc1-4e56-0390cb40c242

### Article author

Rick-Anderson

**Comment by guardrex** [comment]
We're sorry that the template language wasn't updated. I'll take care of that right now.

What that text should say is to open this issue using the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and indicates the author. For some articles, it will even ping the author automatically for a faster response.

What I'll do here for your issue is get the metadata and manually place it into this issue. The doc author will respond after that. *Stand-by .......*
