### ISSUE TITLE
Sample not working without Interactive RenderMode

### ISSUE THREAD

**Issue by ericbrunner** [dotnet/AspNetCore.Docs#31201]
### Description

In each component to get them work you have to add

`@rendermode InteractiveServer (Server App)`

or

`@rendermode InteractiveWebAssembly (Client App)`

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md

### Document ID

3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc

### Article author

@guardrex

**Comment by guardrex** [comment]
It's in progress now and tracked by https://github.com/dotnet/AspNetCore.Docs/issues/31029. Should be resolved across the doc set by the end of the week 🤞🍀.

**Comment by guardrex** [comment]
BTW @ericbrunner ... I'm not sure yet if we're going to set up the snippets with a render mode. It isn't helpful to those adopting Blazor WebAssembly to have the render mode specified. It's only really for Blazor Web Apps. I'm going to discuss this situation with management today to see what we can work out. We might adopt doc ***pivots***, where readers select either Blazor Web App or Blazor WebAssembly app at the top of the document to load the appropriate snippets from either the new BWA sample app or the WASM sample app.

**Comment by ericbrunner** [comment]
> BTW @ericbrunner ... I'm not sure yet if we're going to set up the snippets with a render mode. It isn't helpful to those adopting Blazor WebAssembly to have the render mode specified. It's only really for Blazor Web Apps. I'm going to discuss this situation with management today to see what we can work out. We might adopt doc _**pivots**_, where readers select either Blazor Web App or Blazor WebAssembly app at the top of the document to load the appropriate snippets from either the new BWA sample app or the WASM sample app.

It would be sufficient to give that hints at the beginning of the document.

**Comment by guardrex** [comment]
That's part of the plan, but it isn't that simple. We have a content versioning system that presents additional challenges, such as when a component is only for BWA client-side and standalone WASM. We don't want to flood the tops of articles with NOTE content.

Also ... just since I responded earlier ... I ruled out pivots because pivots can't be versioned. We can version content inside of pivots, but the pivots themselves can't be versioned. They apply to the whole doc, and we have plenty of docs that need to cover Blazor Server/Blazor WebAssembly from *ancient times* 👴 ... i.e., ***LAST YEAR*** 😆. *Things change fast around here!*

I'm currently leaning towards making the BWA snippet sample adopt ***global Interactive Auto*** rendering. Components that work for BWA server/client and standalone WASM won't receive a render mode, and there will be a NOTE at the top of every article stating that components without a render mode work well in all app types with a cross-link to the *Render Modes* article. If a component is only for BWA server or BWA client, then I can apply a render mode in the snippet that's pulled through to the doc.

The tricky one is for BWA client-only ***and*** standalone WASM. That one probably will pull through from the BWA sample with an Interactive WebAssembly render mode but also have a companion NOTE right next to it saying that if the component is for a standalone WASM app the dev should 🔪 the `@rendermode` directive from the example for use.

That's probably the best we can do these days. If we ever implement ***Version-by-File*** doc versioning, then we can probably get around all of these problems by allowing the dev to select a pivot at the top of the (8.0 or later) article that will then display the code in the article by sample app/scenario. We could have pivots for Blazor Web App (interactive SSR), Blazor Web App (CSR), and Blazor WebAssembly. There would be no need for NOTEs, and devs could use the copy-paste feature to get a correct snippet copied for their app.

You're asking about this subject on the exact week that I'm performing the work, so your issue is very timely! 🕦😄

**Comment by guardrex** [comment]
I ran into a problem ... interactive Auto can't be applied globally ***with*** interactive SSR components the main project. The render mode inheritance rules won't permit it (unfortunately).

It narrows down the options to just having the BWA adopt per-component rendering modes ...

* Components only for interactive SSR get the Interactive Server render mode.
* Components only for CSR and Blazor WebAssembly get the Interactive WebAssembly render mode with a companion NOTE saying that the `@rendermode` directive should be removed for Blazor WebAssembly apps.
* Components that work anywhere won't get an `@rendermode` directive. A NOTE at the tops of articles can say that a render mode must be applied (either to the component definition/instance or globally) to such components to make them interactive.

Fine, but that leaves me in a sad state 😢 on my idea that this would be the first year that a snippet sample app would be a fully working, demonstration sample app ... unless I make two BWA sample apps. One like that :point_up: to cover snippets for articles (non-runnable in many cases if the snippet sample is actually run). A different BWA would need to be created that adopts interactive SSR to demo components (i.e., just run the app and all of the components ✨ ***Just Work!***&trade; ✨).

I'll discuss it with Dan and Artak today, and we'll figure out how to proceed.
