### ISSUE TITLE
.NET MAUI Blazor Hybrid app Reversed like a view in a mirror

### ISSUE THREAD

**Issue by sultanaalyami** [dotnet/AspNetCore.Docs#31254]
### Description

The screen appears completely mirrored when creating a new application

![image](https://github.com/dotnet/AspNetCore.Docs/assets/12185541/b365e9cc-1dac-4437-a3e2-7823a91ac5b4)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/maui.md

### Document ID

e66171ce-7dca-bf91-36be-f02e38c00678

### Article author

@guardrex

**Comment by guardrex** [comment]
***Wow!*** It feels like we've entered a parallel universe here 👽😄.

Can you open this on the MAUI repo at ...

https://github.com/dotnet/maui/issues

... and cross-link another issue that doesn't seem to have reached investigation because the poster disappeared. Cross-link their issue into your new issue ...

https://github.com/dotnet/maui/issues/15556

Here's the link to that for your issue ...

```
https://github.com/dotnet/maui/issues/15556
```

I'd also like to understand why this happened. Please also add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/31254
```

... to the bottom of your opening comment so that I can follow along. If it turns out to be related to something we need to document in the Blazor docs, I'll re-open this issue and add content to cover it.
