### ISSUE TITLE
.isValid() is no longer available on EditContext

### ISSUE THREAD

**Issue by MorneZaayman** [dotnet/AspNetCore.Docs#31311]
### Description

The code referring to `editContext.isValid();`, should be replaced with `!editContext.GetValidationMessages(fieldIdentifier).Any();`.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/validation?view=aspnetcore-8.0#custom-validation-css-class-attributes

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms/validation.md

### Document ID

bcb470e1-c859-0549-b4ef-c6c9b7ef2c72

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @MorneZaayman ... I'll take a closer look when I get back from vacation, but why do you say that? That approach is valid, but it isn't recommended IIRC.

**Comment by MorneZaayman** [comment]
`isValid` is not available on the `EditContext `object.
![image](https://github.com/dotnet/AspNetCore.Docs/assets/25976312/ffb94dc6-e51b-4715-8611-090050f4a787)

**Comment by guardrex** [comment]
It's an uppercase "I" for `IsValid` ... and it will need the field identifier. See if this will work as the body of the `GetFieldCssClass` method ...

```cshtml
return editContext.IsValid(fieldIdentifier) ? "validField" : "invalidField";
```

I also note to myself for an update that the sample app hasn't embraced the `IsValid` approach that the article asks for (apparently). I just opened the BWA 8.0 sample app, and I see that the code is still using the Linq `Any` test.

Let's leave this issue open so that I can take a closer look after I get back from vacation next week. I think sample app needs an update (at least), but I'll also check the topic(s) to make sure that everything is in good order or apply updates.

**Comment by guardrex** [comment]
Yeah ... it's definitely a 😈 in the topic ... it should be an uppercase "I" for `IsValid`. I'll make that change now quickly and take it live, but I'd still like to look things over when I get back from vacation. The sample app should probably use the approach. I'll need to see how the sample is linked in here for the code, etc. to resolve this issue completely.

**Comment by guardrex** [comment]
Ok ... we're good. That will go live in the article in about ten minutes or so. Thanks again for the report. I'll update the sample apps next week as I move the new 8.0 bits into them, which is tracked by another issue.
