### ISSUE TITLE
Microsoft.AspNetCore.Components.WebView.WindowsForms not shown in Toolbox, error installing it

### ISSUE THREAD

**Issue by FilippoBN** [dotnet/AspNetCore.Docs#31333]
### Description

Hi, 
I'm following this tutorial: https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-8.0

I'm stuck at adding a BlazorWebView component, since the necessary tab does not appear. I've added Microsoft.AspNetCore.Components.WebView.WindowsForms as a dependency package using NuGet Package manager, that installs version 8.0.3. I then restarted VS2022 and repeated building the sample project a few times: the necessary component is always missing. 
At component install, I get this error a few times:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	WinFormsBlazor	C:\Repos\TestDev\WinFormsBlazor\WinFormsBlazor\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Counter_razor.g.cs	11	Active

I'm using Microsoft Visual Studio Professional 2022 (64-bit) - LTSC 17.2

Can someone help me understanding what am I doing wrong...?

TIA,
F.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/windows-forms.md

### Document ID

b0b88d48-74df-8dc4-446d-121e65b552ab

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @FilippoBN ... I'll see if I can repro a problem here. I have time this morning, so I'll get back to you soon. *Stand-by ....................*

**Comment by guardrex** [comment]
I walked all of the steps and created the app. I don't see a problem ...

![image](https://github.com/dotnet/AspNetCore.Docs/assets/1622880/50624aab-78ec-4d2c-91e7-4a14b07555dd)

So let's take a look at your process ....

You said ...

> the necessary tab does not appear

You don't see a **Toolbox** tab on the left side at the top of the VS UI?

If not, can you select **View** > **Toolbox** from the toolbar and then get the **BlazorWebView**?

If you don't see it, can you take a screenshot of the Toolbox to show what it's showing and paste that image into a comment here?

**Comment by guardrex** [comment]
You should also walk the tutorial from the top and make sure that you followed every step exactly as described. For example, make sure that the SDK is correct in the project file.

**Comment by FilippoBN** [comment]
Hi @guardrex,
yep,  I've followed the tutorial again, first making sure the workload was set.
![Workload](https://github.com/dotnet/AspNetCore.Docs/assets/155443165/568320ad-ec87-48bd-9489-e0937b470bbc)
Next screenshot contains the SDK setting, the reference to the _WindowsForms_ package and a look at my Toolbox (I've manually added the red-marked Blazor tab, to check creating custom toolbox items). 
![Toolbox](https://github.com/dotnet/AspNetCore.Docs/assets/155443165/d8e5ac37-e00b-4134-98ab-95eae5794d1b)
I've also tried to Choose Toolbox Items, but AspNetCore seems not being there at all (components sorted by Namespace)
![ChooseToolboxItems](https://github.com/dotnet/AspNetCore.Docs/assets/155443165/20841980-5077-4b98-9d20-e23c5295aba5)

It should be all correct, so... what else...? :-(

Thanks for your help,
F.

**Comment by FilippoBN** [comment]
To reply to your last question, I see this...
![DesignerView](https://github.com/dotnet/AspNetCore.Docs/assets/155443165/632399fa-6281-426b-a65d-d0a4670bf284)

F.

**Comment by guardrex** [comment]
Ok ... that's ***NOT*** what we want to see :smile:. Seems like a workload/SDK problem of some sort. For example, I see your target framework in the project file referencing 6.0, but it should be on 8.0 (`net8.0-windows`) for the latest bits.

What is your installed SDK (`dotnet --version` at a command prompt)? If it's earlier than `8.0.100`, use the 8.0.100 installer from https://dotnet.microsoft.com/download/dotnet/8.0 to install the 8.0 SDK. After that, you'll need to create a new WinForms app. You'll know if this step is successful quickly because you'll open the project file and see that the target framework is `net8.0-windows`.

**Comment by guardrex** [comment]
If that doesn't work, we'll take a look at workloads. I wonder if the **ASP.NET and web development** workload is required for this (and the WPF tutorial). I wasn't told so, nor was anything flagged by the PU on review of these topics. We've also had these topics up for several years now, and devs haven't written in with a similar problem. It might be a new workload requirement ... not sure.

@BethMassi will see this convo, too. She probably has more familarity than I do with desktop/mobile dev. I'm mostly ... like 99% ... a web dev. She may have seen this problem before or have some other ideas about what might be going wrong 😈.

**Comment by FilippoBN** [comment]
I'm downloading and installing VS 2022 v. 17.8, 'cause I've seen the 8.0 SDK needs that version.
Meanwhile, is there a way to manage multiple SDK versions side by side (6.0 and 8.0, in my case)? Something like nvm for the node's world...

Thanks a ton,
F.

**Comment by guardrex** [comment]
Ok ... that sounds good.

You (usually†) don't need to worry about SxS installs of the SDKs. They live SxS just fine on a machine. The engineers designed .NET and VS with that in mind. Go ahead after you get the new VS into place and install whatever additional SDKs that you need.

***†usually*** ... However, as you can guess, sometimes things do go sideways 💥. It can be something simple, such as a "hidden" [`global.json` file](https://learn.microsoft.com/dotnet/core/tools/global-json) in some folder above a project that pegs the SDK at a given version that you aren't aware of, or it can be something more complex, such as a VS/SDK problem that results in strange/wrong behavior in VS ... I was just reminded of one this morning ... the **Dock** dropdown is blank in VS for the `BlazorWebView` control ...

<img width="313" alt="empty-dock-selection" src="https://github.com/dotnet/AspNetCore.Docs/assets/1622880/bc235d1e-51e2-4c59-a48a-e5eeba841e0d">

Problems with SxS SDKs are kind'a rare these days. It was more common several years ago to hit problems when .NET (Core) was new. The most problems that I personally see are with the previews. They can ***hose*** VS without the internal preview build of VS, which isn't available to the public. Sometimes, I have to switch over to the .NET CLI to build and test apps for releases because my VS has a meltdown 💥.

**Comment by FilippoBN** [comment]
Luke, success!
![Success](https://github.com/dotnet/AspNetCore.Docs/assets/155443165/577a6a66-673f-45c2-a599-d36fa257939b)
I've both SDKs installed now, with VS 2022 v. 17.8.3 I was able to select 8.0 as SDK and continue with the guide.

Thanks a lot for your help, cheers!
Filippo

**Comment by guardrex** [comment]
# :tada: :beers:

Sure thing ... glad it had a happy ending!
