### ISSUE TITLE
Logout button when user wants to logout in static file located in root directory of asp.net core web.

### ISSUE THREAD

**Issue by PersnalGithubAccess** [dotnet/AspNetCore.Docs#31336]
Hi,
I placed some static file (HTML files) in the root directory (outside of www root folder) of aps.net core web app to provide azure ad authentication to asp.net core web app.
After user login it will redirect to index.html file here, I want to display logout button without changing static file (HTML file) because html files can sometimes be changed or removed, etc...
Suppose we have some html or static file in root directory, after user login, we need to display html file, logout button and web page related URL in address bar without changing html or static file, is it possible?
I tried with Iframe tag but in this scenario, we can't update URL because it works like web page in web page.
Is there any way ?

**Comment by guardrex** [comment]
Hello, @PersnalGithubAccess ... Thanks for contacting us, but that's a general question about how to write some rather custom code. Try posting your question to a community support forum or chat because we only work directly with the doc content here. Not many devs look at our issues, and very little discussion of custom code and custom approaches takes place here. Try the usual public support channels ...

* [Stack Overflow (tag: `asp.net-core`](https://stackoverflow.com/questions/tagged/asp.net-core)
* [ASP.NET Core Slack Team](https://aspnetcore.slack.com/join/shared_invite/zt-1mv5487zb-EOZxJ1iqb0A0ajowEbxByQ#/shared-invite/email)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)
