### ISSUE TITLE
"@typeof(App).Assembly" or "typeof(App).Assembly"

### ISSUE THREAD

**Issue by Masoud-Sal** [dotnet/AspNetCore.Docs#31560]
### Description

In [Handle asynchronous …](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#handle-asynchronous-navigation-events-with-onnavigateasync) and [Handle cancellations …](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#handle-cancellations-in-onnavigateasync) 

A part of the code looks like this (with `@`)

```
<Router AppAssembly="@typeof(App).Assembly" 
    OnNavigateAsync="@OnNavigateAsync">
    ...
</Router>
```
I believe the default Blazor template looks like this (without the `@`)

```
<Router AppAssembly="typeof(Program).Assembly" 
    OnNavigateAsync="OnNavigateAsync">
    ...
</Router>
```

I believe you corrected `(Program)` part in another issue.

Which one should it be?

`"@ToBe" or not "ToBe"`

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#handle-asynchronous-navigation-events-with-onnavigateasync

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md

### Document ID

b6cb2574-6326-a40d-0b6c-d1661328e828

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @Masoud-Sal ... Either way is fine, and it's covered in this section ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0#component-parameters

Leave this issue open because I'd like to add a remark on this to the section on component conventions in the *Fundamentals* overview article. This issue will close automatically when the PR merges later. Thanks for the feedback on this.
