### ISSUE TITLE
Add a remark on ClaimsPrincipal.FindAll to examle

### ISSUE THREAD

**Issue by rouxjonathan** [dotnet/AspNetCore.Docs#31681]
### Description

I think there is a problem in this code :

```
            claims = user.Claims;
            surname = user.FindFirst(c => c.Type == ClaimTypes.Surname)?.Value;
```

Shouldn't it be :

```
            claims = user.Claims;
            surname = claims.FindFirst(c => c.Type == ClaimTypes.Surname)?.Value;
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/index.md

### Document ID

1247ee64-fbc9-ce29-0710-f6e59380f5ee

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @rouxjonathan ... You get a claims collection when calling `FindAll` on the principal ...

https://learn.microsoft.com/en-us/dotnet/api/system.security.claims.claimsprincipal.findall?view=net-8.0#system-security-claims-claimsprincipal-findall(system-predicate((system-security-claims-claim)))

... and we don't want to remove the prior line because `claims` is used in the UI to show the user's claims.

**Comment by guardrex** [comment]
Actually 🤔 .... let's go ahead and cross-link the API for that with a passing remark on it.
