### ISSUE TITLE
Relies too much on Visual Studio specific functionality

### ISSUE THREAD

**Issue by MartinNr5** [dotnet/AspNetCore.Docs#31694]
### Description

Since Visual Studio Code is such an immensely popular editor I think it's a detriment that this article relies on functionality only available in Visual Studio. I can't create a "shared resource files with a Build Action of Embedded resource" in VS Code, and I can't right-click to create a new file. 

Localization is confusing and complicated as it is to get right without having the reader also try to figure out how to perform Visual Studio specific activities in VS Code (or any other editor for that matter).

If localization of a Blazor app isn't possible without Visual Studio then that should be clearly noted at the start of the article.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md

### Document ID

d6f07538-228e-9f96-680f-6c324caf11d6

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @MartinNr5 ... Yes, it's reasonable to look into this and see what we can do. I don't think anything in particular is blocked for VSC ... we just need the alternative guidance on what VSC devs should do. I propose that we pivot the whole topic between the two IDEs.

Note that we're experiencing a ***CRAZY*** 😵 high level of 8.0 doc churn right now. I'll schedule this for work, but I can tell you that it will take months to reach it for work under the current workload. I'm sorry about that, but the 8.0 release that introduced Blazor Web Apps and a focus on *render modes* over *hosting models* is taking quite a lot of work to resolve in the docs. I'm still working 8.0 issues with no end in sight yet 😅. I'll get back to this as soon as I can.

**Comment by MartinNr5** [comment]
Hi Luke.

No worries, I just wanted to add it to the queue. I completely understand that there are a ton of other areas to prioritize and as someone who moved to Blazor with the .NET 8 release I enthusiastically support any and all work done on its documentation. :)


Mvh,
Martin Edelius

**Comment by Rick-Anderson** [comment]
@MartinNr5  see https://github.com/dotnet/AspNetCore.Docs/issues/2501

**Comment by Rick-Anderson** [comment]
@MartinNr5  thanks for bring this up. What do you think of [this comment](https://github.com/dotnet/AspNetCore.Docs/issues/2501#issuecomment-1928574935) ?

**Comment by Rick-Anderson** [comment]
@guardrex @MartinNr5 recommend closing as a dup.

**Comment by guardrex** [comment]
Creating the files can be accomplished manually at  least, if not via 3rd party tooling.

I'd like to study this a bit more. I'll get back to it as soon as I can.

**Comment by MartinNr5** [comment]
@Rick-Anderson @guardrex It's obvious that I'm not the first one to point this out (I should've done a search for this issue before submitting) so feel free to close this as a dup if that works for you.


Mvh,
Martin Edelius

**Comment by guardrex** [comment]
It's a different article, which has to be updated separately by me, so this issue should be left open.

**Comment by MartinNr5** [comment]
@guardrex Ah, apologies, I didn't notice that.

**Comment by guardrex** [comment]
Unfortunately, the MS doc isn't helpful, as it just tells everyone to use VS ...

https://learn.microsoft.com/dotnet/core/extensions/create-resource-files

I noticed that Tim Heuer, a MS PM, has an editor for VSC in the marketplace ...

* https://marketplace.visualstudio.com/items?itemName=TimHeuer.resx-editor
* https://github.com/timheuer/resx-editor

We can recommend it because he's a MS 🐱. There are a few others that devs can explore ...

https://marketplace.visualstudio.com/search?term=resx&target=VSCode&category=All%20categories&sortBy=Relevance

The problem I foresee with these is that not all of them look like they can create the `.resx` file to begin with. I'll load up Tim's extension and see if it can create the base file. He doesn't document it, but it might be there.

One I see has an **Add New Resource** button ...

* https://marketplace.visualstudio.com/items?itemName=PrateekMahendrakar.resxpress
* https://github.com/pmahend1/resxpress

@hishamco ... Do you know what tooling is common for devs to use to create/edit `.resx` files in Visual Studio Code? Seven years ago this SO answer said it couldn't be done in VSC directly ...

https://stackoverflow.com/questions/40953193/vs-code-resx-file-extension

... and BTW ... I'm assuming that the rest of the loc infrastructure works correctly without any other steps (e.g., `resgen.exe` is run on the files to produce the correct binaries, etc.).

**Comment by MartinNr5** [comment]
@guardrex Resgen isn't mentioned in the doc page I'm referring to in this issue, and only as a reference in [the overview of the Globalization and localization of a .Net application](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-and-localization) so I didn't personally know I had to use it.

It's never mentioned as a required step in any of the documentation I read on how to localize a .Net application. It might be mentioned in other documentation, but not in the one I found. Reading up on the subject I guess this is what Visual Studio does when you create a .resx file, maybe?

I generally think that the current approach to localize a .Net application is convoluted and fiddly, but that's not an issue the documentation team can solve. :)

**Comment by guardrex** [comment]
I think `resgen.exe` is built-into the runtime somehow, but I don't know for sure. I don't know if a separate step would be required for VSC devs or not. Hisham probably knows more about that aspect and may have general, direct knowledge on what VSC devs do professionally with VSC and loc.

I'm willing to run a few tests here, but I'm bogged down in 8.0 work right now, so I'll get back to this as soon as I can. I might be able to look later today or tomorrow. For now, I look forward to any information that Hisham can provide.

**Comment by guardrex** [comment]
# Ah, ha!!! 🐮👅 ***LICK'D IT!!!!!!***

So, it turns out that the resource files need to be in the `Pages` folder SxS with the component. When I merely moved the files from the root of the app to the `Pages` folder ...

![image](https://github.com/dotnet/AspNetCore.Docs/assets/1622880/52f8b9ff-3d55-4e60-b873-8692da872c1b)

**Comment by guardrex** [comment]
... and it works in Spanish if the browser's language is changed ...

![image](https://github.com/dotnet/AspNetCore.Docs/assets/1622880/4cdae7ad-51b6-4767-873d-266d7bed0de9)

**Comment by guardrex** [comment]
Ok ... I have enough information now to fix this issue.

I'll recommend Tim's extension SxS with the VS remark. I won't go to the trouble of pivoting the whole article. That's overkill.

@hishamco ... I think it's a false alarm on a basic use case for VSC. I'll ping you for review on the PR when it goes up in a few minutes.
