### ISSUE TITLE
Razor Pages Tutorial: Add new scaffolding item unavailable

### ISSUE THREAD

**Issue by ENSMAN38** [dotnet/AspNetCore.Docs#31881]
### Description

Rough translation to English added by wadepickett: 
"None of this works for me. It doesn't look as expected, the dark theme examples pictured are my project.  I am unable to take the same steps."

![197a4e52-61ff-4eae-b494-0e25f2d01f54](https://github.com/dotnet/AspNetCore.Docs/assets/84675374/9d9507db-9a12-4c7f-bc7c-e92e70c19a04)
![LAZOR](https://github.com/dotnet/AspNetCore.Docs/assets/84675374/079aaa93-85e8-49fb-9f36-16cbd63b22d8)
![IMG_7819](https://github.com/dotnet/AspNetCore.Docs/assets/84675374/322e982d-5221-4236-acca-f3c5d454c06e)

Bende bunların hiçbiri gelmiyor böyle çıkmıyor koyu olan benim projem ama bir türlü yapamıyorum 

[Geri bildiriminizi buraya girin]
![IMG_8043](https://github.com/dotnet/AspNetCore.Docs/assets/84675374/16aed0ae-0519-4a21-8b42-ff898e65c8f1)

### Page URL

https://learn.microsoft.com/tr-tr/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md

### Document ID

5492c641-af15-64b8-beaa-ddf511be73e6

### Article author

@wadepickett

**Comment by wadepickett** [comment]
Hi @ENSMAN38,
Thanks for letting us know this is not working for you.

The images you have provided from the Udemy instruction are for a different application type and would not be correct if you are trying to make an ASP.NET Core Razor Pages application. So you would not follow or compare them to your project.

Your dark theme image you provided shows the correct Asp.NET Web Application (Razor Pages) application type.
The next instructions for adding a *Model* folder, then a `Model.cs` file and then scaffolding are here and seem to be correct in the translated version:
https://learn.microsoft.com/tr-tr/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-8.0&tabs=visual-studio

If you intended to create an MVC applicaton rather than a Razore Pages application, then use this tutorial:
https://learn.microsoft.com/tr-tr/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-8.0&tabs=visual-studio


Rough translation:
"Bunun sizin için çalışmadığını bize bildirdiğiniz için teşekkür ederiz.

Udemy talimatından sağladığınız görseller farklı bir uygulama türü içindir ve ASP.NET Core Razor Pages uygulaması yapmaya çalışıyorsanız doğru olmaz. Böylece onları takip etmez veya projenizle karşılaştırmazsınız.

Sağladığınız koyu tema görüntünüz doğru Asp.NET Web Uygulaması (Razor Pages) uygulama türünü gösterir.
Bir *Model* klasörü, ardından bir 'Model.cs' dosyası ve ardından iskele eklemek için sonraki talimatlar"

**Comment by wadepickett** [comment]
I have retested this tutorial through creating and running the scafolding and compared to the Turkish version tranlated.  The instruction seems good.  Applying to the Feb project since I took a little time to test.
