### ISSUE TITLE
AddDatabaseDeveloperPageExceptionFilter Error

### ISSUE THREAD

**Issue by Jashi18** [dotnet/AspNetCore.Docs#31882]
### Description

[Enter feedback here]

The following has been added by wadepicket after testing the topic:
 The "Add NuGet packages" section has a step to "Select Include prerelease".  The prereease instruction needs to be removed from all three versions of this tutorial:  VS, VSC & VS for Mac.

The following is the original issue provided by the community member:
Hello, I am beginner at ASP.NET Core and started this minimal API practice project. From the first steps in the code I am getting this Error : 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IServiceCollection' does not contain a definition for 'AddDatabaseDe
veloperPageExceptionFilter' and no accessible extension method 'AddDatabaseDeveloperPageExceptionFilter' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)	TodoApp	C:\Users\admin\source\repos\TodoApp\TodoApp\Program.cs	6	Active

I will Also attach Image
![ERROR](https://github.com/dotnet/AspNetCore.Docs/assets/112314639/fc40b1c9-4b6b-4cf7-8bd4-774c1bc8a9a0)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md

### Document ID

ab408035-6313-a183-9940-32de00e0e977

### Article author

@wadepickett

**Comment by wadepickett** [comment]
@Jashi18, thanks for letting us know you ran into an issue with the tutorial, greatly appreciated.

The error: 'IServiceCollection' does not contain a definition for 'AddDatabaseDeveloperPageExceptionFilter' typically occurs when the necessary package or namespace is not included in your project. See, "Follow the preceding instructions to add the `Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore` package."

There are two very likely possibilites here to check out:

[Missing NuGet Package: The method AddDatabaseDeveloperPageExceptionFilter is part of the Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore package] If this package is not installed in your project, you will encounter this error. You can install it via NuGet package manager per the instructions in the tutorial.

Given it is the 2nd package you are to add in the instructions, it is possible you missed the instruction for adding the 2nd one.  See, step "Follow the preceding instructions to add the `Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore package`.

Another possiblity is that the "Add NuGet packages" section has a step to "Select Include prerelease".  This step is unfortunately out of date and I will remove it (with the issue you have created here as the tracking issue").  This step was correct prior to the .NET 8 release, but with .NET 8 released now the latest prerelease of this package is not needed, and it is possible a package version issue caused the problem.  

Uninstalling and reinstalling the packages:
In the NuGet Package Manager you can uninstall as well as install.  There is an *Installed* tab you can select, then select the installed packages, and then select the project they are in on the right and there is an uninstall button that appears below that.  After uninstalling the packages, go through the steps from the tutorial for adding them back in, but make sure "Include prerelease" is unchecked.

One other less likely possiblity: You may have a missing using Directive.  Make sure the following was added at the top of your `Program.cs" file from the "Add the API code" section of the tutorial:
`using Microsoft.EntityFrameworkCore;`
I say it is not as likely since that step is to simply replace the code with the copy provided, so it would be not as likely to just miss the first line but it could happen.

I will fix the issue of the prerelease package step.  Hopefully one of the steps avove helps you out.
