### ISSUE TITLE
issue on recognizing Javascript method - await JS.InvokeVoidAsync

### ISSUE THREAD

**Issue by shilpaCM** [dotnet/AspNetCore.Docs#31917]
[EDIT by guardrex to add code-fencing]

### Description

Hi,

i am trying to invoke javascript method using await JS.InvokeVoidAsync as per described in the article. but it gives error has 
Could not find method or method was undefined. PFB test sample used in .NET MAUI Blazor page(.razor)

```razor
@inject IJSRuntime JSRuntime;

<script>
  function displayTickerAlert1{
    console.log("displayTickerAlert1");
  };
</script>
```

in C#

```razor
@code {
    await JSRuntime.InvokeVoidAsync("displayTickerAlert1");
}
```

error as displayTickerAlert1 is not recognized(displayTickerAlert1  was undefined);

i have also tried defining method as below:

```html
<script>
  window.displayTickerAlert1 = (symbol, price) => {
    alert(`${symbol}: $${price}!`);
  };
</script>
```

invoking in c#

```csharp
await JS.InvokeVoidAsync("displayTickerAlert1", stockSymbol, price);
```

even this gives same error. Please help

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md

### Document ID

9e197a8b-2616-8363-0a15-38cac802e82e

### Article author

@guardrex

**Comment by guardrex** [comment]
I can't reproduce a problem with the example ...

![image](https://github.com/dotnet/AspNetCore.Docs/assets/1622880/1d0e920e-8c13-4598-8936-deecdf615629)


Make sure you're placing the JS (`<script>...</script>`) in the `wwwroot/index.html` file or colocate a JS file SxS with the component per the guidance. Don't place scripts into Razor components (as the guidance states). The guidance is at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0#javascript-location

Otherwise, seek assistance from the community if you're still having trouble. We recommend the usual chats/forums ...

* [Stack Overflow (tag: `blazor`)](https://stackoverflow.com/questions/tagged/blazor)
* [ASP.NET Core Slack Team](https://aspnetcore.slack.com/join/shared_invite/zt-1mv5487zb-EOZxJ1iqb0A0ajowEbxByQ#/shared-invite/email)
* [Blazor Gitter](https://gitter.im/aspnet/Blazor)
