### ISSUE TITLE
Reduce the amount of front matter in the Blazor Call an API doc

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#31940]
### Description

This article has a lot of front matter before it really starts to discuss the scenario of making an API call from a component. 
Can we remove or reduce this front matter and get to the article's topic quicker? The front matter currently includes a lot of stuff that is covered elsewhere and isn't strictly related to calling an API from Blazor. 

Currently the doc covers the following before getting into calling an API, which seems excessive:

- Defining server-side vs client side
- Describing how interactive render modes are applied
- Describing that client-side is public and can be decompiled and inspected
- Pointers to project structure docs
- Instructions on how to run the Blazor samples
- A note about nullability support
- A note that the article is pivoted for WebAssembly and Server content

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/call-web-api.md

### Document ID

c7e59a08-1c60-32c2-75fd-33cb77ff7a5d

### Article author

@guardrex

**Comment by guardrex** [comment]
Yes, but note that this much content was only going to be here for the 8.0 release in order to "train" devs on BWAs and the major doc change from hosting model to render mode language, along with some of the other mentions (e.g., NREs). This front matter is in most of the articles for this purpose for this release only. My plan was to strike most of it at (or near) 9.0.

Fortunately, the front matter is placed via an INCLUDE, so an update will update all articles in one shot.

> A note that the article is pivoted for WebAssembly and Server content

IIRC, that came about I think in a discussion with you a long time ago when it wasn't clear where the WASM JSON helpers were covered when you land on this article's sever pivot. We can resolve that problem if I place a ***PAIR*** of articles here in a node (folder) and drop the pivot in a single article. Would you like me to do that?

**Comment by danroth27** [comment]
> UPDATE: Per the other issue, going back to a single (long) article will also solve the problem on surfacing JSON helpers.

Yeah, I'd prefer to keep this as one article. Let's see what we can do to simplify the content to keep the length under control.
