### ISSUE TITLE
"Sample code" links on Blazor EF Core page are unclear

### ISSUE THREAD

**Issue by nivekh** [dotnet/AspNetCore.Docs#31975]
### Description

The link "[View or download sample code](https://github.com/dotnet/blazor-samples)" just leads to the root of a repo with multiple examples, and the linked "[how to download](https://learn.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-8.0#how-to-download-a-sample)" page has instructions which direct the reader to download a zip of a completely different example repo. Neither of these links are quite as helpful as they could be.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/blazor-ef-core.md

### Document ID

2ebc5e4d-bab4-6d30-9018-9a712c482236

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @nivekh ... I don't really have a choice on a deeper link because it depends on what version the developer is working with, and I can't know that in advance. What I can do is mention the name of the sample and tell the reader to select the version folder that matches the version that they're working with. I'll see if I can fix this up now in the *Sample app* section of this article. Thanks for the feedback.

**Comment by guardrex** [comment]
> is written for a different context

Yes, it's meant to be for the whole repo, and we have two sample app areas. I'll review that content now, as it probably changed over time.

**Comment by guardrex** [comment]
Yes, I see what you mean. I opened https://github.com/dotnet/AspNetCore.Docs/issues/31977 to fix it, and I'll knock that out first thing tomorrow morning.

**Comment by nivekh** [comment]
Thank you!
