### ISSUE TITLE
Advanced input component scenarios with `ValueExpression` coverage

### ISSUE THREAD

**Issue by hakenr** [dotnet/AspNetCore.Docs#31982]
[EDIT by guardrex to update the metadata: The new content will go into the Forms > Binding article]

### Description

Not sure if this is intentional, but the commonly used `ValueExpression` element of the data binding is not documented et al.
(E.g. used by input components for `FieldIdentifier` in validations etc.)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/binding?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms/binding.md

### Document ID

19296123-d389-3d2f-da8f-89420cc3a96e

### Article author

@guardrex

**Comment by guardrex** [comment]
By-design in the sense that the PU never requested that it be covered in the docs. They might have not asked for it because it's provided automatically by `@bind-Value` for typical InputX component scenarios. I think all of our examples bind with `@bind-Value`. However, it's possible that it didn't occur to them years ago to request coverage, and they weren't receiving PU repo issues from confused devs about it. You're the first to ever ask about it here. I'll ping Steve to ask if it should be covered.

**Comment by guardrex** [comment]
This will be covered as part of a new section on advanced input components ... a non-`InputBase` subsection will have a bit on `ValueExpression` with an example and an `InputBase`-based component that won't have `ValueExpression` but is just part of the general effort to cover both of these advanced input component cases.

I'm going to modify the title of this issue just a bit to cover everything.
