### ISSUE TITLE
Incorrect sentence: Microsoft.NET.Sdk does not need Microsoft.AspNetCore.App.

### ISSUE THREAD

**Issue by pauldendulkgeodan** [dotnet/AspNetCore.Docs#32254]
### Description

The page contains this sentence:

> Projects that target Microsoft.NET.Sdk or Microsoft.NET.Sdk.Razor SDK, should add an explicit FrameworkReference to Microsoft.AspNetCore.App:

This would mean that if a project targets Microsoft.NET.Sdk it should add a reference to Microsoft.AspNetCore.App. This is not true. Any new console app targets Microsoft.NET.Sdk but it should not reference Microsoft.AspNetCore.App.

It seems rather obvious but my colleague was confused by it.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-8.0&tabs=visual-studio#framework-reference

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/22-to-30.md

### Document ID

f9f2b0f3-01eb-cf58-8767-194fe0fc0e44

### Article author

@Rick-Anderson

**Comment by guardrex** [comment]
Hello @pauldendulkgeodan ... This guidance isn't primarily for console apps, which typically don't use ASP.NET Core, but you can reference it in such apps. It's focused on class libs and Razor class libs ...

* https://learn.microsoft.com/aspnet/core/fundamentals/target-aspnetcore#use-the-aspnet-core-shared-framework
* A [Razor class lib](https://learn.microsoft.com/aspnet/core/razor-pages/ui-class) based on `Microsoft.NET.Sdk.Razor` will also have the framework ref.

Because the whole section scopes the content with ...

> Features of ASP.NET Core ...

... it's probably ok in its present form. However, Rick will be along in a bit to take a look. He maintains this article.

**Comment by Rick-Anderson** [comment]
<img width="554" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/3605364/044e0f40-b1dc-491e-8207-078c7817666c">

<img width="559" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/3605364/fea03868-99ad-4f6e-aaba-9347f746dd7a">
