### ISSUE TITLE
Clearly describe what happens when a call to `base.SetParametersAsync` is skipped

### ISSUE THREAD

**Issue by runceel** [dotnet/AspNetCore.Docs#32273]
### Description

In the `SetParametersAsync` section, it is mentioned that the default implementation of `SetParametersAsync` and the ability to skip its call are as follows:

```
If [base.SetParametersAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.setparametersasync) isn't invoked, developer code can interpret the incoming parameters' values in any way required. For example, there's no requirement to assign the incoming parameters to the properties of the class.
```

However, if the call to `base.SetParametersAsync` is omitted, other lifecycle methods such as `OnInitialized` will not be called, so it is usually necessary to call `base.SetParametersAsync`. Therefore, I believe it is necessary to describe in more detail what happens when `base.SetParametersAsync` is not called.

### Page URL

https://learn.microsoft.com/ja-jp/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#component-disposal-with-idisposable-and-iasyncdisposable

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md

### Document ID

4871f4f7-9cf6-ac7a-0f21-c65d34bd1119

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @runceel ... Let's ask ...

@MackinnonBuck ... I don't know if there was a framework change on this point or if at the time we placed the content, which predates your arrival, they just didn't give me more info on this for the section. I can see initialization being called in `ComponentBase`; so as @runceel says, if the base set params method isn't called, I can see the initialization not occurring because those calls aren't made ...

https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/ComponentBase.cs#L249-L250

If that's correct, what guidance should we be giving? In the old days, I think the idea was that not calling the base class method was useful when, as the article states, you want to take total control of how incoming params are assigned.

**Comment by runceel** [comment]
@guardrex If `base.SetParametersAsync` is not called, developers must properly invoke `OnInitialized{Async}` and `OnParametersSet{Async}`. `OnInitialized{Async}` should only be called once, and in addition to the lifecycle methods, `StateHasChanged` must also be invoked to ensure the screen is rerendered correctly. Implementing this correctly can be difficult, so personally, I think it’s better to call `base.SetParametersAsync`. If you don’t need the framework to set the parameters, I think it’s a good idea to pass an empty `ParameterView` like `base.SetParametersAsync(ParameterView.Empty)`. Doing so will execute reflection processing in the background, so there isn’t much of a performance advantage… but I think it’s better than implementing the lifecycle methods to work perfectly.

**Comment by guardrex** [comment]
> OnInitialized{Async} should only be called once

IIRC, isn't it ***once each***? You can call both of them, but only once. I don't think the text explicitly needs to call this out.

Indeed! I forgot about the `StateHasChanged` call. I see that in the API code comments in ref source. I'm going to modify the suggestion :point_up: to refer readers to ref source on it. I agree that this is a bit tricky to explain out.

> `base.SetParametersAsync(ParameterView.Empty)`

👍 That's a nice add, too. I've placed a remark on it :point_up:.

**Comment by guardrex** [comment]
I placed the PR. Let's pick up discussion of the draft text there ...

# https://github.com/dotnet/AspNetCore.Docs/pull/32285
