### ISSUE TITLE
Link directs to wrong page and enhance QuickGrid coverage

### ISSUE THREAD

**Issue by johndhunter** [dotnet/AspNetCore.Docs#32312]
[EDIT of the issue title by guardrex: I'll correct the link, split out and enhance the EF Core guidance into a section, and add remote data source content.]

### Description

The link that suggests using the example with Entity Framework does not go to an example using Entity Framework - 
"For an example that uses an [IQueryable](https://learn.microsoft.com/en-us/dotnet/api/system.linq.iqueryable) with Entity Framework Core as the queryable data source, see the [SampleQuickGridComponent component in the ASP.NET Core Basic Test App (dotnet/aspnetcore GitHub repository)](https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/testassets/BasicTestApp/QuickGridTest/SampleQuickGridComponent.razor)"

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/quickgrid.md

### Document ID

564e71e3-82ed-ce23-4f9f-a00a58734a62

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks for the note, @johndhunter ... That's right, and I can't find an `IQueryable` example for EF Core in the product unit's repo, neither here nor in the EF Core repo.

What will really fix this issue is to enhance the current remarks on using EF Core as the data provider with a more complete example than what we have. I can base it on what they placed in the QuickGrid sample here ...

https://aspnet.github.io/quickgridsamples/datasources

I have time now, so I'll fix this up this morning.
