### ISSUE TITLE
Difference in the using directive when changing the IDE in the tab

### ISSUE THREAD

**Issue by felipementel** [dotnet/AspNetCore.Docs#32391]
### Description

There is a difference when we select different tools in the using section. see the two attached images,

img1
![image](https://github.com/dotnet/AspNetCore.Docs/assets/14238257/b9492d4d-2c55-4909-be1f-59e08edfc038)

img2
![image](https://github.com/dotnet/AspNetCore.Docs/assets/14238257/bf48ce5a-7b2d-463a-bc97-619ffbee8dc0)

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md

### Document ID

ab408035-6313-a183-9940-32de00e0e977

### Article author

@wadepickett

**Comment by wadepickett** [comment]
Hi, thanks for letting us know your experience with this doc.  The code difference is by design.  For the Visual Studio version of this topic, the API is tested using Visual Studio's Endpoints Explorer feature.  For Visual Studio and Visual Studio for Mac, the API is tested using NSwag to produce OpenAPI documentation for testing the API which is explained in the section [Create API testing UI with Swagger](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-8.0&tabs=visual-studio-code#create-api-testing-ui-with-swagger) along with introducing the new lines of code required that you are referring to.
