### ISSUE TITLE
Getting random WebSocket failed connection on Blazor / ASP.NET Core 6.0 Application

### ISSUE THREAD

**Issue by fontainerc** [dotnet/AspNetCore.Docs#32470]
I have a web application that is built in Blazor Server / ASP.NET Core 6.0, it runs on an Azure App Service with a SignalR connection.  It works 90% of the time but 10% of time I get a loading error as documented below.  How can I fix this?

- WebSocket connection failed
- Error: Failed to start the transport 'WebSockets'
- Error: WebSocket failed to connect

Here is my Program.cs file contents for reference:

using BlazorServerApp.Data;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Connections;
using Microsoft.EntityFrameworkCore;
using System;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddSignalR();

builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();

app.MapBlazorHub();
app.MapFallbackToPage("/_Host");

app.Run();

**Comment by guardrex** [comment]
Hello @fontainerc ... Note in passing that issues should be opened from the bottom of an article using the **Open a documentation issue** link, which pings the author and tracks the document. ***However,*** that wouldn't have helped us with your report really. We mostly work on documentation here and have limited capacity to provide product support. Open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/32470
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.
