### ISSUE TITLE
.WithStatefulReconnect

### ISSUE THREAD

**Issue by troubleshootdoc** [dotnet/AspNetCore.Docs#32493]
# Issue description
I have a blazor wasm (client model) only.  We want to use SignalR serverless and Azure function as the Hub.   If we want to use the .WithStatefulReconnect , can we do it using a blazor wasm client only application  if our hub is an azure function? Is there something I would have to change in the signalr service (in serverless mode)

The blazor client would use this instead of WithAutomaticReconnect().  
hubConnection = new HubConnectionBuilder()
     .WithUrl(functionAppBaseUri, options =>
     {
     }).WithStatefulReconnect().Build();

# Software versions
.NET 8

**Comment by guardrex** [comment]
Hello @troubleshootdoc ... BTW, it's best to open issues here via the **Open a documentation issue** link at the bottom of an article, such as in the case from the bottom of the Blazor *Fundamentals* > *SignalR* article. Anyway ... your question is best for the product unit to address, so open an issue for them here ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/32493
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.

**Comment by guardrex** [comment]
Re-opening to add a NOTE that it isn't supported yet per ...

https://github.com/Azure/azure-signalr/issues/1878

... and a tracking item to back it out later when support arrives.
