### ISSUE TITLE
Tutorial does not work due to missing dependency

### ISSUE THREAD

**Issue by vichor** [dotnet/AspNetCore.Docs#32550]
### Description

[Enter feedback here]
The tutorial on page https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-8.0&tabs=visual-studio does not work when executing the step "Scaffold the movie model". The problem seems to be a missing pacakge in the project as explained in [https://developercommunity.visualstudio.com/t/vs2022-add-new-scaffold-item-there-was-an-error-ru/1580388 (see there the proposed workaround)](https://developercommunity.visualstudio.com/t/there-was-an-error-running-the-selected-code-gener-14/797775).

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md

### Document ID

7096fdb3-612e-9e00-bd0b-8ea4886a09ce

### Article author

@wadepickett

**Comment by wadepickett** [comment]
Thanks @vichor for letting us know your experience with this topic.  Visual Studio 2022 provides the needed NuGet packages for scaffolding automatically when the scaffolding step is taken.  I just tested the tutorial steps now for Visual Studio and verified it all works, just in case:

![image](https://github.com/dotnet/AspNetCore.Docs/assets/10985336/ba129128-95d6-443a-8b92-6b50af252e1f)

This latest version of the Razor Pages tutorial is designed around Visual Studio 2022 and is shown required as a prerequisite at the beginning.

The issue you referred to was filed for visual studio 2019 version 16.3.  If you are receiving the error mentioned on that link, then it could be you are using an older version of Visual Studio, or possibly there was some sort of connection problem while Visual Studio was attempting to download the needed packages during scaffolding.

I will close this issue since I just verified the tutorial steps work with the prerequisite version of Visual Studio.  Feel free to reopen this issue if we have missed something.   Thanks again.
