### ISSUE TITLE
Order of operations - calling base lifecycle methods

### ISSUE THREAD

**Issue by mstortz** [dotnet/AspNetCore.Docs#32621]
### Description

When discussing lifecycle methods, the examples call the base method last:
```
protected override async Task OnInitializedAsync()
{
    await ...

    await base.OnInitializedAsync();
}
```
Would it not be a better practice to call the base method first, as it may perform operations that the child class depends on? Is this not similar to calling the base constructor first?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#base-class-lifecycle-methods

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md

### Document ID

4871f4f7-9cf6-ac7a-0f21-c65d34bd1119

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @mstortz ... The product unit engineers have only provided the guidance that you see in the article.

For example:

* Calling the base lifecycle method when you're using a custom base class. I guess that they would say it depends on your base class and what you need to execute first ... the component's method or the base class's method ... it depends on your code.
* Library consumers calling a library base class ***where the library author says to call it in their guidance***.

If you want to inquire further with them on it, open an issue for them on their repo to ask at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/32621
```

... to the bottom of your opening comment so that I can follow along. I'll re-open this for doc work depending on what they tell you.

**Comment by guardrex** [comment]
Javier kind'a didn't answer on ***ordering***, but I think it's fair to say that that's up to the dev. This is probably why they gave me guidance to post that tells library consumers to follow the guidance of the library author about where to call the base class method when the base class is supplied by the library. I think this is one of those things where ***it depends***, and the dev should consider the ordering and call it where it makes sense in their code for their app to work properly.
