### ISSUE TITLE
Code examples in 'Alternative global exception handling' section does work as expected

### ISSUE THREAD

**Issue by TimMurphy** [dotnet/AspNetCore.Docs#33091]
### Description

I've followed the instructions at [Alternative global exception handling](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0#alternative-global-exception-handling) but my code does not work as documented / expected.

The Error property on the Counter page is always null.

The [git repository](https://github.com/TimMurphy/AlternativeGlobalExceptionHandling) shows the issue. The solution was created with the following steps:

- [Add 'Blazor Web App' template with 'Interactive render mode' as Server and 'Interactivity location' as Per page/component](https://github.com/TimMurphy/AlternativeGlobalExceptionHandling/commit/e11105fb004b4d02ef4d44f606b299efabcbb319)
- [Apply changes as documented in https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0#alternative-global-exception-handling](https://github.com/TimMurphy/AlternativeGlobalExceptionHandling/commit/80b7998f6d0821c125fc247b8cd64700bed6a151) 
- [Add info about caught exceptions to /Errors](https://github.com/TimMurphy/AlternativeGlobalExceptionHandling/commit/87f0651126167a324245531b027ec42b6bf2e875)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0#alternative-global-exception-handling

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/handle-errors.md

### Document ID

66a0b1c2-c45c-98ca-9808-6f340a861c44

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks for the report @TimMurphy. We're still updating docs for BWA scenarios, and this holdover approach from the Blazor Server days might end up not applying. I'll see if I can repro your issue sometime today, and then I'll ping the product unit for assistance if I get the same outcome.

**Comment by guardrex** [comment]
Ok ... I took a look. Two things ...

* There's a BWA project template `Error` component , so this holdover naming isn't compatible with an app generated from the template. When I created a test app for this, I diverged from the guidance in the section and named my global error handling component "`AltError`" (`AltError.razor`). BTW - Given that the added component isn't routable, it goes in the `Components` folder.
* Second, this works ***IF*** the app adopts global interactive rendering, not per-page/component rendering.

I need to ask @MackinnonBuck if there's a way to make this section work for per-page/component because when I try to just set the render mode in the `AltError` component, it 💥 with ...

> InvalidOperationException: Cannot pass the parameter 'ChildContent' to component 'AltError' with rendermode 'InteractiveServerRenderMode'. This is because the parameter is of the delegate type 'Microsoft.AspNetCore.Components.RenderFragment', which is arbitrary code and cannot be serialized.

... and that makes sense. ***BUT*** ... can the pattern be made to work around that problem?

Mackinnon, the section is here ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0#alternative-global-exception-handling

**Comment by TimMurphy** [comment]
>
> There's a BWA project template Error component , so this holdover naming
> isn't compatible with an app generated from the template.


I don't understand what you saying here. The Error component in my repo was
generated by the BWA template in Visual Studio.

**Comment by guardrex** [comment]
Correct, but the section calls for adding a component to the app with the same name `Error` (`Error.razor`). That's because this is a holdover section from before Blazor Web Apps. What I need to do is change the name of the component in the section to something else. I used `AltError` (`AltError.razor`) and placed it in the `Components` folder because it isn't supposed to be a routable component for this pattern. Even if you do that tho, this pattern only works for global interactive rendering. We'll have to see what Mackinnon thinks about doing something like this with per-page/component interactive rendering.

**Comment by guardrex** [comment]
Mackinnon has confirmed that this approach is most suited to global interactivity, so I'm going to add a remark to the top of the section calling that out.

**Comment by TimMurphy** [comment]
Fair enough. It would be helpful if a section is added for Blazor Web Apps
that adopt per-page/component render modes.

**Comment by guardrex** [comment]
Mackinnon said that they don't want to offer an alternative approach. They're only recommending the Error Boundary approach at this time, and that should work with per-page/component render modes 🤞 ... or stated another way ... I haven't received any feedback that the Error Boundary approach breaks for the per-page/component scenario. I have an 👂 open for further feedback.

**Comment by TimMurphy** [comment]
It's because of the way I think <ErrorBoundary> works that I started down the rabbit hole of using the alternative global exception handling section.

I've created https://github.com/TimMurphy/ErrorBoundaryWithPerPageInteracvtity. It is BWA with per-page/component mode.

In the generated /counter page I've wrapped to the HTML with <ErrorBoundary>. Press the button 3 times and you'll see the <ErrorBoundary> has no effect.

I've added a WorkingCounter page that works with <ErrorBoundary>. This solution involves having a page, ie WorkingCounter, with a <ErrorBoundary> and the actual content for the page in a separate file, ie. WorkingCounterComponent.

Is this the correct way to use <ErrorBoundary>? Seems like more work than it should be.

How I'm using per-page/component mode is the public side of the site SSR and the admin section, /admin, I'm using Interactive rendering. I'd like the entire site to be interactive rendering but from the documentation I've read this is not a good idea because it may require higher spec server and I'm trying to keep costs to a minimum and use the lowest server configuration Azure provides. Am I wrong in this approach?
