### ISSUE TITLE
Blazor OIDC sample: wrong user-settings command

### ISSUE THREAD

**Issue by albi005** [dotnet/AspNetCore.Docs#33873]
### Description

The documentation says to use the following command to set the client secret:
```sh
dotnet user-secrets set "MicrosoftOidc:ClientSecret" "{SECRET}"
```
Instead it should be
```sh
dotnet user-secrets set "Authentication:Schemes:MicrosoftOidc:ClientSecret" "{SECRET}"
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=without-bff-pattern

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/blazor-web-app-with-oidc.md

### Document ID

c3346d3a-346b-8db4-2650-ec044b3f0dd9

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @albi005 ... I'll fix this right now 🏃. I broke it by mistake because I was matching it to the Azure key for Entra. It appears that the OIDC provider API uses this longer configuration key (`Authentication:Schemes:MicrosoftOidc:ClientSecret`), which I had there before I made the change 🙈😆. I'll get the update on the live site in a few minutes. Thanks for writing in on it!
