### ISSUE TITLE
When targetting .Net8, it is necessary to use "8.x" versions of nugets, NOT "latest", which is now "9.x".

### ISSUE THREAD

**Issue by ToolmakerSteve** [dotnet/AspNetCore.Docs#34207]
### Description

There are multiple places in .Net docs where this is relevant, now that .Net 9 is released.

I have found that  (some? all?) "9.x" Nugets do NOT support .Net 8.

For example, [Build a Windows Presentation Foundation (WPF) Blazor app](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/wpf):

> Use [NuGet Package Manager](https://learn.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio) to install the [Microsoft.AspNetCore.Components.WebView.Wpf](https://nuget.org/packages/Microsoft.AspNetCore.Components.WebView.Wpf) NuGet package:

By default, "Latest stable" is selected for installation. Currently, this is `9.0.10`.

If install that in a project that targets .Net 8, there will be a variety of build errors.  
Most of the errors won't mention namespace `Microsoft.AspNetCore.Components.WebView.Wpf`.  
Rather, they mention OTHER namespaces, from nugets that are dependencies of that one.  
For example, `Microsoft.AspNetCore.Components.Web` and `Microsoft.Extensions.DependencyInjection`.

However, those dependencies do not get included. (Nor should they, given the incompatibility between `9.x` nugets and `.Net 8`.)

Because of the non-obviousness of the error messages, it is important to alert developers to be careful that they select nuget versions starting with `8.`, when targetting `.Net 8`.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/wpf?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/wpf.md

### Document ID

94872f14-0dce-0cf3-0d25-88f23ca8d8ef

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+94872f14-0dce-0cf3-0d25-88f23ca8d8ef)

**Comment by gfoidl** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/59115

**Comment by guardrex** [comment]
Hello @gfoidl ... This looks like a regression in the NuGet Package Manager. Let's keep an eye on where your other issue goes because something like this wouldn't be worked from here ... from the documentation repo. If indeed they need to fix the NuGet Package Manager, that would be handled via an internal issue. We don't document short-term bug fix scenarios. We just allow them to fix the bug. If a tooling problem is going to take a long time to fix ... more than a week or two ... then we do tend to place remarks in documentation about it. I'll keep an 👁 on your other issue to confirm that they'll get right on this problem. I'll also send an internal email to Dan Roth, Principal Product Manager for .NET, to make sure that he sees your other issue quickly 🏃‍♂ ... like ***today!*** 🏃‍♂🏃‍♂🏃‍♂🏃‍♂🏃‍♂🏃‍♂
