### ISSUE TITLE
load .br，use no-cache，but why?

### ISSUE THREAD

**Issue by bxjg1987** [dotnet/AspNetCore.Docs#34205]
### Description

.net9

app.MapStaticAssets();

const response = await fetch(defaultUri + '.br', { cache: 'no-cache' });  

why use cache: 'no-cache'

### Page URL

https://learn.microsoft.com/zh-cn/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-9.0#compression

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md

### Document ID

250e7458-3c1d-0117-261d-c03ac136f16a

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+250e7458-3c1d-0117-261d-c03ac136f16a)

**Comment by guardrex** [comment]
Hello @bxjg1987 ... I'll ask the product unit to confirm that this guidance shouldn't be followed when `MapStaticAssets` routing endpoint conventions are used. If that's correct, I'll add a remark to the top of the section.

I think the section can also say that files aren't cached in order to avoid a problem where some cached assets load with non-cached assets resulting in a mismatched set of framework files that can break the app. That's just a guess tho. We'll find out shortly.

*Stand-by ... I'll ping Javier to look at this on Monday.*

**Comment by guardrex** [comment]
Ok ... I'm back. This guidance is only for Blazor WebAssembly, so Map Static Assets routing endpoint conventions don't apply and the guidance is still viable for compression with that type of Blazor app.

WRT stating why files aren't cached, I'll add a remark that it's to avoid a mismatched set of framework files. We'll see on review if my hunch is correct.
