### ISSUE TITLE
Why doesn't my BindTheory.razor page work?

### ISSUE THREAD

**Issue by rfalanga** [dotnet/AspNetCore.Docs#34238]
### Description

According to your tutorial, when I interact with the BindTheory.razor page:

> When the BindTheory component is rendered, the value of the HTML demonstration <input> element comes from the InputValue property. When the user enters a value in the text box and changes element focus, the onchange event is fired and the InputValue property is set to the changed value. In reality, code execution is more complex because @bind handles cases where type conversions are performed. In general, @bind associates the current value of an expression with the value attribute of the <input> and handles changes using the registered handler.
>
> Bind a property or field on other DOM events by including an @bind:event="{EVENT}" attribute with a DOM event for the {EVENT} placeholder. The following example binds the InputValue property to the <input> element's value when the element's oninput event (input) is triggered. Unlike the onchange event (change), which fires when the element loses focus, oninput (input) fires when the value of the text box changes.

Ah, no. Nothing happens. Why does nothing happen? I put BindTheory.razor into the Components/Pages folder of the main project, not the Client problem. Is that why it doesn't work?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md

### Document ID

3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc)

**Comment by guardrex** [comment]
> Ah, no. Nothing happens. Why does nothing happen? I put BindTheory.razor into the Components/Pages folder of the main project, not the Client problem. Is that why it doesn't work?

Yes ... if you set the component to adopt Interactive Server rendering in a per-page/component solution with a client project and place the component in the server project. We used to have coverage on that scenario, but management doesn't think that that's a particularly good app choice ... and it is confusing. Such a component has to go in the client project because the router is in the client project. You'll see an Interactive Server component placed in the server project flash briefly on the screen via static server-side rendering and then disappear when the client-side router takes over and can't find it.

Anyway ... generally speaking ... place that component where it can render with an interactive render mode and it will work.

I'll close as answered.
