### ISSUE TITLE
UseMiddleware<> ordering could be clearer

### ISSUE THREAD

**Issue by mattfrear** [dotnet/AspNetCore.Docs#8063]
I just wasted hours wondering why my Middleware wasn't working. My problem was my Configure method looks like this: 
```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment 
{
    // blah blah

    app.UseMvc();
    app.UseMiddleware<MyMiddleware>();
```

when my call to `UseMiddleware<>` has to be BEFORE the call to `app.UseMvc()`. That is not obvious from the documentation or from the examples.

In fact this entire page is bad. No one in a production web api app is going to use `app.Use` or `app.Run` so why have those minimal contrived examples? We're always gonna extract our middleware to a class and use `app.UseMiddleware<>()` but it feels like that is skimmed over. I mean who goes File -> New -> Empty web project? No one. It's always File ->  New -> Web API for those of us in the real world. Sorry for ranting but I'm annoyed I just wasted so much time when a better real world example on such a fundamental topic could have saved me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
At a minimum the table is missing MVC Middleware. Without an entry for it, there's no opportunity to say that when MVC Middleware handles a request that it's a terminal middleware.

I'll patch that now as a quick fix to this specific problem, but a larger rewrite/overhaul is probably a good idea here. @Rick-Anderson @scottaddie Do you think it's time for this one? I can do it out perhaps 141-142 time frame.

**Comment by scottaddie** [comment]
@guardrex I'm in favor of improving the doc. While you're in there, the tabs should be replaced with conceptual versioning.

**Comment by mattfrear** [comment]
@guardrex thank you for cleaning up this page. I think it's still missing the crucial bit, which is an example of using `UseMiddleware<>` along with `app.UseMvc` and the fact that UseMiddleware needs to come first

**Comment by guardrex** [comment]
It's covered generally by virtue of the fact that any terminal middleware that completely resolves any request will prevent any following middleware from processing the request. I'll note this issue on issue for revising the whole topic and take a closer look when I get to work on that.

**Comment by mattfrear** [comment]
> It's covered generally by virtue of the fact that any terminal middleware that completely resolves any request will prevent any following middleware from processing the request

Wow, I didn't know that. And where is that documented? A search of "terminal" on that page doesn't define what terminal means in this context.

**Comment by guardrex** [comment]
Yes, I think it's a word that should be used/explained higher in the topic. The authors were trying to get the point across by describing how the request pipeline might be **_short-circuited_** by some middlewares. When short-circuiting occurs, no following middleware will process the request.

The topic should be careful with the concept because a middleware isn't terminal if it allows the request to pass. For example, MVC isn't terminal if routing doesn't match the request; MVC will let the request pass to the next middleware. If routing matches the request, MVC fully processes the request and terminates the pipeline. I think this concept could be stated a bit more plainly, and it's probably a good idea to use MVC as the example (or one of the examples).

The authors were trying to make it clear with the following remarks ...

> Each middleware component in the request pipeline is responsible for invoking the next component in the pipeline, or short-circuiting the chain if appropriate.

> A delegate can also decide to not pass a request to the next delegate, which is called short-circuiting the request pipeline. Short-circuiting is often desirable because it avoids unnecessary work. For example, the static file middleware can return a request for a static file and short-circuit the rest of the pipeline.

> The first app.Run delegate terminates the pipeline.

... and `Run` in the API comments uses the word "terminal." https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.builder.runextensions

The table lists the middlewares that are "terminal." As a quick fix, I just added MVC to the table.

I'll work on it further when I get to #8071, which I hope to reach no later than the next sprint.
