### ISSUE TITLE
Update VSC Create a web project instructions

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#9488]
Determine the preferred workflow for new project creation in VS Code. Update the tutorials accordingly. For example:

[Create a web project](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio-code#create-a-web-project)

Include #10579 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio-code#create-a-web-project)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@wadepickett  work with @scottaddie  on this.

**Comment by wadepickett** [comment]
@Rick-Anderson, thanks!

**Comment by wadepickett** [comment]
Pinged PM to weigh in first...

**Comment by wadepickett** [comment]
Went through all tutorials that use "dotnet run".    For top level tutorials there was only this fix that was needed:
fixed with   #14644,  #15124
I ran through all the rest of the tutorials for every level and the cases where "dotnet run" was specifically used, however for all but the few I fixed listed above there were not any steps requiring further code changes so "watch" was not needed. So not as wide spread of an issue as I thought it would be.
